alphagov/paas-cf

- manifests/prometheus/alerts.d/ec2_cpu_credits.yml
What
----
T3 instances do not have launch credits, unlike T2 instances. This means
that this alert would fire as soon as the instances were launched.
How to review
-------------
Be @richardTowers
> Update cpu credits alert to not be noisy for t3

- manifests/cloud-config/cloud-config.yml
- manifests/prometheus/operations.d/100-update-vm-types.yml
- manifests/prometheus/spec/operations/monitor_cf_spec.rb
- manifests/prometheus/spec/operations/update_vm_types_spec.rb
- manifests/variables.yml
**Depends on  [this paas-bootstrap PR](https://github.com/alphagov/paas-bootstrap/pull/289) being merged and deployed**
[Story](https://www.pivotaltracker.com/story/show/166728064)
What
----
This PR removes the `{medium,nano}_previous_generation` instances which we added for grafana/prometheus/alertmanager (the things with disks in paas-cf). Since we have upgraded the bosh-aws-cpi-release to >=v74 ([this pr]()) we can now upgrade these instances to the latest generation also.
How to review
-------------
Code review
Look at Travis
Run it down your pipeline
Who can review
--------------
Not @tlwr
> [#166728064] Upgrade prometheus to latest generation

- concourse/pipelines/create-cloudfoundry.yml
What
----
Updates the paas-accounts deploy job to add the admin user to the users table
Also includes the following changes:
- https://github.com/alphagov/paas-admin/pull/279
- https://github.com/alphagov/paas-accounts/pull/10
- https://github.com/alphagov/paas-accounts/pull/11
Before Merging 
-----
**Update the paas-accounts tag after merging paas-accounts/pull/11**
How to review
-------------
- Deploy to your dev env and follow the testing instructions in the above PRs
Who can review
--------------
Not me or @AP-Hunt
> [#166334937] Bump paas-admin and paas-accounts

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
Upgrade stemcells to `315.41` from `170.69`; so we are running the latest and greatest versions/patches.
**Contingent on https://github.com/alphagov/paas-bootstrap/pull/291 having been merged and deployed beforehand**
How to review
-------------
Run this down your pipeline
Who can review
--------------
Not @tlwr
> Upgrade stemcells to 315.41

- scripts/migrate_uaac_users_to_accounts.rb
What
----
This script is a one-off, but we're raising it on a separate branch so we can
review it in our normal workflow.
The script fetches all UAA users, and either creates or updates them in
paas-accounts as appropriate. If the username is a valid email, we populate the
email field. Otherwise, it is null.
How to review
-------------
1. Code review
1. Test it in your environment
1. You must deploy paas-accounts from https://github.com/alphagov/paas-accounts/tree/add-username-to-users-166334937 before you test
Who can review
--------------
Not @AP-Hunt or @mogds
> [#166334937] Script for adding existing UAA users to paas-accounts [skip ci]

- manifests/cf-manifest/operations.d/200-awslogs.yml
- manifests/cf-manifest/operations.d/320-cc-enable-security-event-logging.yml
- manifests/cf-manifest/operations.d/320-cc-ship-logs-for-auditing.yml
- terraform/cloudfoundry/cc_security_events_log_retention.tf
What
----
As part of increasing the security on the PaaS we want to collect all of the [Security Events from Cloud Controller](https://docs.cloudfoundry.org/loggregator/cc-uaa-logging.html#cc). 
We have forked a boshrelease from 18F and modified it for this usecase. Those changes were already merged in [awslogs-boshrelease](https://github.com/alphagov/paas-awslogs-boshrelease).
We are retaining the logs for 18 months as that gives plenty of scope for moving backwards in time with auditing actions on the platform. 
How to review
-------------
* Code review;
* This is deployed in the `miki` dev env and is deploying (as of 10:21am on the 26th) in the `towers` dev env. Feel free to deploy yourself but those will save you time. These logs should then be visible in CloudWatch Logs in the AWS …
> [#166351405] Audit CloudController events

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
My firebreak project is two apps:
* One named `paas-auditor` will regularly fetch CC Audit Events and save them into a Postgres database;
* The other named `paas-activity` will display a summary of tenant activity on the platform using that Postgres database.
I have failed to manually configure the UAA client that this commit configures, so I am putting it in the pipelines. This work is all a proof-of-concept and so the apps themselves are not included.
Depending on whether this firebreak project appeals this commit may be reverted next week.
How to review
-------------
Code review. Compare it to the `paas-billing` YAML which is immediately above both the changed lines.
Who can review
--------------
Not @46bit
> Add a UAA client for paas-auditor

- concourse/pipelines/create-cloudfoundry.yml
What
----
https://github.com/alphagov/paas-admin/compare/v0.153.0...v0.158.0
Supercedes #1958
How to review
-------------
* Check the diff here is agreeable: https://github.com/alphagov/paas-admin/compare/v0.153.0...v0.158.0
Who can review
--------------
> Bump paas-admin to get nice new cost reports

- Makefile
- concourse/scripts/pause-kick-off.sh
What
----
With Concourse 5.x series pausing and unpausing of resources has been replaced by pinning and unpinning of resources. This PR reinstates the behaviour we had previously.
How to review
-------------
Code review
Deploy in your env and let it pin
unpin later in the day and see you have an env ready in the morning
Who can review
--------------
Anyone
> Update the pausing and unpausing of kickoff

- manifests/cf-manifest/operations.d/330-uaa-ship-logs-for-auditing.yml
- terraform/cloudfoundry/audit_log_retention.tf
What
----
Ships the UAA Audit Events from https://docs.cloudfoundry.org/loggregator/cc-uaa-logging.html#uaa into CloudWatch Logs. See commit messages for more details.
This is very similar to #1960 which did this for Cloud Controller.
How to review
-------------
* Code review;
* Look at the logs in CloudWatch Logs coming from `miki` dev env.
Who can review
--------------
Not @46bit
> [#166381355] Store auditing logs for UAA

- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/pipelines-cloudfoundry.sh
[Story](https://www.pivotaltracker.com/story/show/166154766)
What
----
We currently have three problems which this PR attempts to address:
- We have to manually bump the `tag_filter` for the `paas-admin` git resource. 
- A staging pipeline run where the paas-admin acceptance tests fail can proceed to production and break production paas-admin.
- The entire staging pipeline must run even if the only thing which has changed is paas-admin.
It does this by cribbing off the existing tagging script, but puts it inside the pipeline and simplifies it somewhat. This is done with a view to doing it for paas-billing, paas-accounts, paas-auditor, etc in the future.
How to review
-------------
- Code review commit by commit
- Ensure that this does nothing in your dev pipeline
- Ensure that the …
> [#166154766] Continuously deploy PaaS-admin

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
What
----
See https://www.cloudfoundry.org/blog/cve-2019-3794/
How to review
-------------
Code review
- [see tlwr pipeline - check `paas-cf` resource](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/19)
Who can review
--------------
Not @tlwr
> Bump UAA to 73.4.0 to fix CVE-2019-3794

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
What
----
This reverts commit 3f98975b524eafd3ef262effde953bdc0e10a2ba.
We experienced elevated 401s during the deployment to staging which were
not experienced in development.
Reverting to unblock staging pipeline
How to review
-------------
Code review
> Revert "Bump UAA to 73.4.0 to fix CVE-2019-3794"

- tools/metrics/acceptance/acceptance_suite_test.go
- tools/metrics/acceptance/cdn_broker_test.go
What
----
In staging and other non-prod environments, there are sometimes no CDN route services. As such we do not get some metrics exported by paas-metrics.
This updates the acceptance tests to work in staging by skipping some more tests.
How to review
-------------
- Code review
- `cd paas-cf/tools/metrics` ; `PAAS_METRICS_URL='https://paas-metrics.london.staging.cloudpipelineapps.digital/metrics' ginkgo acceptance`
> Skip some more metrics in paas-metrics acceptance

- terraform/pingdom/pingdom.tf
What
----
I accidentally deleted the route in CF for PaaS-admin, because I am a fool and because `cf d -r -f app` which shares a route with another app deletes routes for both apps.
I would like to avoid this happening again, by making Pingdom tell us when PaaSmin goes down.
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Add PaaS-admin to Pingdom

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
***do not merge***
What
----
We want to release a version of UAA which uses the
DelegatingPasswordEncoder which is zero downtime, once UAA understands
BOTH password hashes with the "{bcrypt}" prefix and without, then we can
release a version which runs migrations to ensure that all password
hashes start with '{bcrypt}'
How to review
-------------
Be @richardTowers
> Update uaa release to be zdd with v73.4.0

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
We are using our own custom version of UAA which doesnt do silly things
with migrations which will break everything:
- password hashes with {bcrypt} prepended would get {bcrypt} prepended
again
- but we have our own custom migrations which fix this
How to review
-------------
Code review
See [tlwr pipeline](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/acceptance-tests/builds/56) (red but only with flakey test)
Who can review
--------------
Not @tlwr
> UAA migrations not double

- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/lib/microsoft-oauth.sh
- concourse/scripts/pipelines-cloudfoundry.sh
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/operations/uaa-add-microsoft-oauth.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
- manifests/shared/spec/fixtures/environment-variables.yml
- scripts/upload-microsoft-oauth-secrets.sh
What
----
This replays the reverted PR #1961 with a later version.
We had some trouble with UAA version 73.4.0 due to bad ZDD changes and database migrations which we had to workaround with some semi-manual work and a lot of revert/revert changes.
This pull request reverts the revert of #1961 with an updated version of alphagov/paas-uaa
How to review
-------------
Code review
pending see [tlwr pipeline()
Who can review
--------------
Done as pair with @AP-Hunt - will merge when TLWR pipeline is green
> Bump UAA to paas-uaa/0.1.9

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
This addresses a number of CVEs, including:
https://www.cloudfoundry.org/blog/usn-4019-1/ (SQLite)
https://www.cloudfoundry.org/blog/usn-4034-1/ (ImageMagick)
and a few others. If you're super interested you can read the release
notes since the last release:
https://github.com/cloudfoundry/cflinuxfs3/releases/tag/0.95.0
https://github.com/cloudfoundry/cflinuxfs3/releases/tag/0.96.0
https://github.com/cloudfoundry/cflinuxfs3/releases/tag/0.97.0
https://github.com/cloudfoundry/cflinuxfs3/releases/tag/0.98.0
https://github.com/cloudfoundry/cflinuxfs3/releases/tag/0.99.0
https://github.com/cloudfoundry/cflinuxfs3/releases/tag/0.100.0
https://github.com/cloudfoundry/cflinuxfs3/releases/tag/0.101.0
https://github.com/cloudfoundry/cflinuxfs3/releases/tag/0.102.0 …
> Upgrade cflinuxfs3 to v0.115.0

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/cf-manifest/operations.d/040-log-cache.yml
- manifests/cf-manifest/operations.d/210-cf-disable-routing-api.yml
- manifests/cf-manifest/operations.d/329-capi-release.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations.d/900-cf-cert-rotation.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
[Story](https://www.pivotaltracker.com/story/show/167008683)
[Release notes](https://github.com/cloudfoundry/cf-deployment/releases/tag/v10.0.0)
What
----
This pull request updates cf-deployment to v🔟, but does not include the Envoy changes.
This pull request is zero-downtime for the API, applications, and metrics; but it significantly changes how metrics are collected.
Each change is made in a separate commit
- The version of CAPI we are using is latest; so remove the upgrade ops file
- Our fork of UAA is 73.4, but cf-deployment is also v73.4 (previously v72); so update the pin
- Our update of log-cache-release is now behind latest; so remove it to get the latest
- Update smoke test version and acceptance test versions in pipeline
- UAA without TLS is now deprecated, we were using TLS; …
> cf-deployment v🔟 Episode I - The Phantom Istio

- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/lib/google-oauth.sh
- concourse/scripts/pipelines-cloudfoundry.sh
- config/users.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations/uaa-add-google-oauth.yml
- manifests/cf-manifest/operations/uaa-add-microsoft-oauth.yml
- scripts/lib/uaa_sync_admin_users.rb
- scripts/migrate-google-sso-users.rb
- scripts/sync-admin-users.rb
- scripts/upload-google-oauth-secrets.sh
What
----
- Script to migrate Google SSO users to have Google id's as usernames, given a CSV of email addresses and corresponding id's. This is a one-off script that needs to be run against each environment
- Adds the paas-admin Google client ID and secret so non-GDS users to enable Google SSO
- Maps the UAA username to the Google token sub
**Please hold off merging until the migration work has been completed**
How to review
-------------
- Run the upload-google-oauth-secrets make task
- ~Review https://github.com/alphagov/paas-admin/pull/343~ done
- ~Review https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/10~ done
- ~Deploy to your dev env~ done
- ~⚠️ **Update the paas-uaa-customized-boshrelease version**~ done
Who can review
--------------
Not me
> [#166927205] Add PaaS-Admin Google OIDC Client ID/Secret

- manifests/cf-manifest/operations.d/350-diego-cell.yml
- manifests/cf-manifest/operations.d/900-cf-cert-rotation.yml
- manifests/cf-manifest/spec/manifest/diego_spec.rb
[Story](https://www.pivotaltracker.com/story/show/167008683)
[Release notes](https://github.com/cloudfoundry/cf-deployment/releases/tag/v10.0.0)
***[Prerequisite PR](https://github.com/alphagov/paas-cf/pull/1995) must be merged first***
What
----
This is a follow up PR to #1995, which adds 3 commits, one of which is empty.
Previously, in #1333, we moved to cf-deployment with a no-op manifest. I.e. we replicated our own version of deployment of CF, using cf-deployment, rather than having a deployment that looked like cf-deployment.
One of [the commits](https://github.com/alphagov/paas-cf/pull/1333/commits/01730f50f4c9c216b4678a997329b6c2026d1205#diff-28c13109122f766fc787ca1c0aa21126R34) removed the `containers` configuration block of `rep` which, as of cf-deployment v🔟, is now `enabled: …
> cf-deployment v🔟 Episode II - The Attack of the Envoys

- concourse/pipelines/create-cloudfoundry.yml
What
----
Sometimes the paas-metrics acceptance test goes red in the pipeline. This is because it has not yet had enough time to collect metrics.
Sleep a few minutes before acceptance testing so we can ensure that paas-metrics has had enough time to collect the metrics that we test.
How to review
-------------
Code review
> Wait a bit before running paas-metrics acceptance

- manifests/prometheus/alerts.d/uaa-5xx-errors.yml
- manifests/prometheus/spec/alerts/uaa-5xx-errors.test.yml
What
----
Adds an alert to monitor UAA. The alert will be triggered if there's an increase in UAA 5xx errors over a 6 hour period.
How to review
-------------
Code review
Who can review
--------------
Not me
> [#167194597] Monitor UAA Errors

- scripts/generate_logit_filters.sh
What
----
In [3cd9ca36fb5b60bb0f79a405027114b9ac78549e](https://github.com/alphagov/paas-cf/commit/3cd9ca36fb5b60bb0f79a405027114b9ac78549e) one of the files was renamed but updating the path in the generate logit filters script was missed.
How to review
-------------
Code review and run `make logit-filters`
Who can review
--------------
Anyone
> [SUPPORT] Update the logit filter script file paths

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
See https://github.com/alphagov/paas-cdn-broker/pull/21 and https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/17
Done as pair with @AP-Hunt and has had manual testing of
- create
- update without domain
- update domain
- update without domain
- update domain
- delete
The codepath for renew has not changed significantly
> Bump CDN broker version to 0.1.15

- concourse/pipelines/create-cloudfoundry.yml
- tools/metrics/gauges_billing.go
- tools/metrics/gauges_billing_test.go
- tools/metrics/main.go
What
----
This adds a total costs by plan metric to that's collected via billing's /costs endpoint.
```
paas_billing_total_costs_count{plan_guid="9e29a085-95cc-4f48-9fa1-cd5e5cb61c67"} 3.14
paas_billing_total_costs_count{plan_guid="1e61512c-39c1-4426-aa0e-d4cb8b2d8c17"} 1.03
paas_billing_total_costs_count{plan_guid="54b75748-e8d1-4a01-9db0-e0d119823d2f"} 1.09
```
How to review
-------------
- Review and merge https://github.com/alphagov/paas-billing/pull/83
- Code review
- Deploy to your dev env and confirm the metric is in prometheus
- Update the paas-billing resource tag
Who can review
--------------
Not me or Lee
> [#167483203] Add billing costs by plan metric

- concourse/pipelines/create-cloudfoundry.yml
What
----
See https://github.com/alphagov/paas-billing/compare/v0.65.0...v0.66.0
How to review
-------------
Who can review
--------------
> Bump paas-billing to v0.66.0 (timing for /totals)

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
We were falling behind with our fork of UAA
How to review
-------------
Deploy from this branch in dev and make sure UAA still works
Then head over to https://github.com/alphagov/paas-uaa/pull/6 to review and merge
Following that it's a quick hop to https://github.com/alphagov/paas-uaa-release/pull/9 to update the submodule and merge that.
Finally this PR just needs tweaking with the updated boshrelease from https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-release
Who can review
--------------
Anyone
> [SUPPORT] Bump UAA release

- terraform/cloudfoundry/rds_broker.tf
What
----
The extension can now be enabled when creating/updating the database through the rds broker. The broker manages its own custom parameter groups.
All databases have been migrated to the new parameter groups so this one can be removed.
❗️ The PR can not be merged until all databases have been migrated to the new parameter group. Check https://www.pivotaltracker.com/n/projects/1275640/stories/163795598 for the list of databases to check.
How to review
-------------
Code review is enough
Who can review
--------------
Not me.
> [#163795598] Delete the db parameter group used for manually enabling the pg_stat_statements extension

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Release https://github.com/alphagov/paas-cdn-broker/pull/25 and https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/20.
How to review
-------------
🐝 *Merge https://github.com/alphagov/paas-cdn-broker/pull/25 first. Before merging this PR, update the `[WIP]` commit to point to the boshrelease built from its updated master.* 🐝 
Who can review
--------------
Not @46bit
> [#167668232] Ship updated CDN Broker documentation URL

- concourse/pipelines/create-cloudfoundry.yml
What
----
Release https://github.com/alphagov/paas-aiven-broker/pull/19. 
Also includes https://github.com/alphagov/paas-aiven-broker/pull/18, which only changed the tests.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit.
> Ship Aiven broker with more resilient Unbinding

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/040-cf-routing.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/230-loggregator-deployment.yml
- manifests/cf-manifest/operations.d/360-log-api.yml
- manifests/cf-manifest/operations.d/900-cf-cert-rotation.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Upgrades our `cf-deployment` from `v10.0.0` to [`v11.0.0`](https://github.com/cloudfoundry/cf-deployment/releases/tag/v11.0.0).
ℹ️ This would include UAA `74.0.0` except for our fork. In https://github.com/alphagov/paas-cf/pull/2021 we have already upgraded our fork to be based on that version.
ℹ️ This would upgrade our buildpacks except I've been told we pin them.
How to review
-------------
* Code review;
* See if the tests pass;
* Try deploying to your dev env and check everything passes;
* Check that the buildpacks were not upgraded (as we'd need to do tenant comms.)
So long as support stays quiet, Miki is going to deploy it and test it to speed things up.
Who can review
--------------
Not @46bit
> [#167862846] [CVE-2019-9893] Upgrade to cf deployment v11.0.0

- concourse/pipelines/create-cloudfoundry.yml
- manifests/prometheus/alerts.d/paas-billing-costs.yml
- tools/metrics/billing.go
- tools/metrics/gauges_billing.go
- tools/metrics/gauges_billing_test.go
- tools/metrics/main.go
What
----
- Updates the paas-metrics deployment to include a file with a map of plan_guid to name that's used to add a name label to the paas_billing_total_costs metric
- Adds an alert to monitor the paas-billing costs against AWS EC2/RDS costs
How to review
-------------
- Code review
Who can review
--------------
Not me
> [#167835423] Monitor paas-billing costs

- concourse/pipelines/create-cloudfoundry.yml
What
----
In #2024 we pinned https://github.com/cloudfoundry/cf-acceptance-tests in an unusual way because their build pipeline was broken and so the normal way wasn't available. This PR moves us back to the normal way now things are fixed. See commit message for more details.
How to review
-------------
* Code review;
* See if the tests go green;
* I think we're fine to deploy this straightforwardly.
Who can review
--------------
Not @46bit
> Switch back to normal cf-acceptance-tests pinning

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/set-smoke-test-creds.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/upload-test-artifacts.yml
What
----
- Updates image tags
- Adds a task to copy vars from S3 to credhub
- Updates the create-cloudfoundry pipeline to use credhub values when deploying paas-admin, paas-billing, paas-metrics and paas-accounts
- Removes retrive-config task from the above
How to review
-------------
Who can review
--------------
Not me
> [#167572519] Use credhub to deploy paas-apps

- tools/metrics/gauges_aws_cost_explorer.go
What
----
Because we reserve instances, the UnblendedCost appears artificially low
(since most of our instances were paid for back in July).
This makes comparing the money we're spending on AWS with the money
we're getting from billing very difficult - it would be much easier if
we reported the AmortizedCost metric instead.
How to review
-------------
* Code review
* Run it down a pipeline and check the metrics still work
Who can review
--------------
Not Richard
> Switch from UnblendedCost to AmortizedCost

- manifests/prometheus/alerts.d/paas-billing-costs.yml
What
----
These are currently alerting because we're only billing for ~70% of our
RDS usage, but this may actually be reasonable because we run some RDS
instances ourselves.
The EC2 alerts were pointing at the wrong metrics, which themselves were not being calculated correctly given our reserved instances (fixed in #2031).
I've also added a "layer: billing" label to them so we can hide them from Grafana.
How to review
-------------
* Code review should be enough
Who can review
--------------
Not Richard
> Fixes for billing alerts

- config/billing/config.json.erb
What
----
It's been 0.8 since at least March 2018
(alphagov/paas-billing@838212be12318a4c03598666e525fb5b9ea899b1). For
most of that time the actual rate has been quite a bit lower than that,
but now it's more like 0.82.
Updating it to match so we don't undercharge people for the AWS
resources we're using.
This will affect all non-consolidated bills (so everything from the
month this is merged onwards).
How to review
-------------
* Check 'em
Who can review
--------------
Not richard, probably should run it past Luke
> Update exchange rate to match current average

- terraform/pingdom/pingdom.tf
What
----
`/calculator` requires billing to be up, which should be healthchecked separately.
We should just check whether paasmin's `/healthcheck` is healthy or not.
If we need a better check for health of paasmin, it should be
implemented in code in paasmin, and be used to compute the statuscode of
`/healthcheck`
Currently this is noisy because of problems with billing of which we are aware
How to review
-------------
Code review
> Use /healthcheck for paasmin pingdom healthchecks

- config/billing/config.json.erb
What
----
This reverts commit f0ad7e6670ac066be39020b5543d7d6d07599d22.
It turns out that the extra complexity that this adds to billing's
queries causes it to fall over.
We could consider changing the `epoch` exchange rate and relying on the
consolidation to keep the past consistent, but for now let's just try
and fix the thing.
How to review
-------------
* Code review should be enough
Who can review
--------------
> Revert "Update exchange rate to match current average"

- manifests/cf-manifest/operations.d/350-diego-cell.yml
No story
What
----
We have seen some weird timeouts with some of our tenants, during all
parts of HTTP requests.
Hypothesis is that Envoy is running out of memory which causes the
timeouts
Increase memory 32mb to 48mb
How to review
-------------
Run it down your pipeline in an environment where `SLIM_DEV_DEPLOYMENT` is `false`
Who can review
--------------
Not @tlwr
> Increase memory allocation to Envoy proxy

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Our dopplers are once again at capacity, scale them up +6 to deal with
new log volumes.
Who can review / How to review
-------------
Config change done as pair, manually applied to production
> Scale up London Dopplers

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- manifests/cf-manifest/scripts/generate-manifest.sh
- manifests/cf-manifest/spec/manifest/uaa_spec.rb
- manifests/prometheus/scripts/generate-manifest.sh
- manifests/prometheus/spec/support/manifest_helpers.rb
What
----
- Migrates cf-vars-store and prometheus-vars-store to credhub.
- Updates the cf and prometheus deployments to no longer use the vars-store
- Updates task that copies secrets to the concourse namespace to copy from the bosh namespace instead of the vars-store
- Updates relevant jobs to use credhub vars and removes cf-vars-store inputs
How to review
-------------
- Review and deploy https://github.com/alphagov/paas-bootstrap/pull/300
- Code review
Who can review
--------------
Not me
> [167571906] Migrate cf-vars-store and prometheus-vars-store to Credhub

- terraform/prod-lon.vpc_peering.json
Adding a second VPC peer for dit-services / datasci. Note that the same peer_name, `dit-services_datasci`, is used as the original peer. I'm not sure if this is desired or if it would cause problems.
> Add second VPC peer for dit-services / datasci

- terraform/cloudfoundry/cf_rds.tf
What
----
The following commits
* bc29e018 Switch m5 to m4 instance types for CF's RDS
* faf363b4 Apply DB instance upgrade immediately
* 5906f424 Upgrade CF RDS instance class and storage
changed the databases within business hours, rather than the maintenance
window, because database performance was degraded.
We usually want do do database updates during our maintenance window
unless explicitly set.
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Remove apply immediately after database upgrade

- concourse/pipelines/create-cloudfoundry.yml
- config/buildpacks.yml
What
----
Upgrades the buildpacks, and bumps the version of paas-aiven-broker to a version that is supported by the upgraded Go buildpack
How to review
-------------
1. Code review
2. Run it down your pipeline
Once you've approved
----------------
1. Send out the tenant comms email
2. Put a time-based blocker on the story in Pivotal
Who can review
--------------
Anyone
> [#167506774] Buildpack upgrade 11 September '19

- manifests/cf-manifest/operations.d/360-log-api.yml
- manifests/cloud-config/cloud-config.yml
- terraform/cloudfoundry/lbs.tf
What
----
This commit is the first step in moving doppler.((system_domain)) to live
behind the existing Loggregator ALB.
Future commits will upgrade doppler, point the DNS entry at the ALB, and retire
the classic load balancer currently serving traffic on that domain.
🚨 **There are more PRs in this chain** 🚨 
Also see #2053 and #2050
N.B.
---
This PR must me merged and fully deployed before the others
How to review
-------------
1. Code review
2. Run it down your pipeline, then run #2053 and #2050 in order
Who can review
--------------
Not I
> [#167986184] Attach logapi instances to Doppler ALB target group

- manifests/prometheus/alerts.d/paas-billing-costs.yml
- manifests/prometheus/dashboards.d/user-impact.json
What
----
Move billing alerts out of "Platform Alerts" and relax billing alerts so
they don't constantly fire.
How to review
-------------
* Code review
* Compare [the snowflaked ireland
region](https://grafana-1.cloud.service.gov.uk/d/paas-user-impact/user-impact-prod)
with [the standard London
region](https://grafana-1.london.cloud.service.gov.uk/d/paas-user-impact/user-impact-prod)
Who can review
--------------
> Make billing alerts less noisy

- manifests/cf-manifest/operations.d/360-log-api.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
- manifests/cloud-config/cloud-config.yml
- platform-tests/src/platform/acceptance/tls_version_test.go
- terraform/cloudfoundry/dns-records.tf
- terraform/cloudfoundry/lbs.tf
What
----
Point `doppler.((system_domain))` at ALB, and upgrade the version of doppler in use.
This commit is the second step in serving traffic for `doppler.((system_domain))` from the existing Loggregator ALB. Future PRs will retire the classic load balancer currently serving traffic on the domain.
N.B.
---
This PR should not be merged before #2052 has been merged and fully released.
This branch is branched from `add_logapi_instances_to_doppler_alb_target_group_167986184` and the first commit does not matter.
How to review
-------------
1. Code review
2. Deploy in sequence with #2052 and #2050
Who can review
--------------
Not I
> [#167986184] Point doppler domain at ALB

- concourse/scripts/lib/pagerduty.sh
- concourse/scripts/pipelines-cloudfoundry.sh
- manifests/prometheus/alerts.d/concourse-billingsmoketests-failures.yml
- manifests/prometheus/alerts.d/concourse-smoketests-failures.yml
- manifests/prometheus/operations.d/310-alertmanager-routes.yml
- manifests/prometheus/operations/disable-alert-notifications.yml
- manifests/prometheus/spec/alerts/concourse-smoketests-failures.test.yml
- manifests/prometheus/spec/operations/alertmanager_routes_spec.rb
- manifests/shared/spec/fixtures/pagerduty-secrets.yml
- scripts/upload-pagerduty-secrets.sh
What
----
This PR changes alerting behaviour for failed billing smoke tests. They will now only page us in-hours. To do that it does some tidyup and adds a second set of Pagerduty credentials. It goes alongside https://github.com/alphagov/paas-credentials/pull/158. See the commit messages for more context.
How to review
-------------
* 🐝 Code review alongside https://github.com/alphagov/paas-credentials/pull/158;
* ℹ️ Run the updated `upload-pagerduty-secrets` using the updated credentials (if you haven't done that the deploy will fail harmlessly);
* ⚠️ After merging and deploying to prod, trigger various alerts and check we get paged appropriately (or at least, be sure that smoke test failures will page us out-of-hours.)
I have already verified that this triggers Pagerduty and emails …
> [#168214024] Billing smoke tests should not page out of hours

- config/logit/11_app_syslog_drain.conf
- config/logit/20_custom_cf_filters.conf
- config/logit/output/generated_logit_filters.conf
- scripts/generate_logit_filters.sh
What
----
A paas-billing improvement was not added to the generate script, so I added it.
Gorouter reports a few numbers which we should index as numbers:
- `gorouter.header.response_time` the duration in seconds, should be indexed as float - this is required for HAProxy deprecation
- `gorouter.bytes{sent,received}`
CF Syslog drain sets the destination as `$orgname.$spacename.$appname` which we can re-index so that we can do queries like:
```
@source.app_name:paas-admin
```
or
```
@source.org_name:admin
```
I chose `app_name`, `org_name`, and `space_name` because they are consistent with `app_id`, although arguable `app_org_name` `app_space_name` `app_name` are better
How to review
-------------
Look at the following links:
- [gorouter example, click JSON on a log and ensure that …
> [skip-ci] Logstash filters index app source, and gorouter numbers

- tools/metrics/gauges_billing_api_performance.go
- tools/metrics/gauges_billing_api_performance_test.go
- tools/metrics/gauges_billing_collector_performance.go
- tools/metrics/gauges_billing_collector_performance_test.go
- tools/metrics/main.go
- tools/metrics/maths.go
What
----
In #2029 we made paas-metrics query elasticsearch to fetch the timings
of some of the SQL queries that paas-billing's collector makes, so we
could report them to prometheus and track their performance over a
longer time frame.
This commit does the same thing, but for the queries billing API makes.
This gives us more of an insight into the user-facing performance of
billing. As the pages in paas-admin generally only make one API call,
which only makes one slow SQL query these numbers are a good proxy for
how long the pages users see take to load.
As with the other PR, because this queries logit this spans multiple
deployments (so we'll see both `prod` and `prod-lon` in production).
In my dev environment this looks like:
``` …
```
> Convert billing API perf logs to metrics

- Makefile
What
----
The lines removed by this commit were added to make the `Makefile` cleaner. However in practice they don't work:
1) Self-update pipeline run on Concourse will fail because it doesn't have those `pass` credential stores checked out;
2) Engineers without the high pass store won't be able to interact with production.
How to review
-------------
Code review. For bonus points, try pushing secrets.
Who can review
--------------
Not @46bit
> [#167971884] Don't check password stores exist on Concourse

- manifests/cf-manifest/env-specific/prod.yml
What
----
A tenant reported some erratic API errors in Ireland. After some digging we suspect Cloud Controller can get a bit overloaded. This commit scales Ireland up from 4 to 6 Cloud Controller instances to better meet demand.
At present our `api` VMs use EC2 `m5.large` instances. An on-demand `m5.large` in Ireland (`eu-west-1`) costs ~$77/month. If reserved this goes down to ~$54/month. (Prices from https://www.ec2instances.info/?region=eu-west-1&selected=m5.large.) Therefore these 2 extra instances will cost $108–$154 depending upon how many are already reserved.
London has 12 `api` instances, whereas this PR only takes Ireland up to 6. Money doesn't grow on trees and we haven't seen big enough problems to scale Ireland up all the way yet.
How to review
-------------
* Code review;
* …
> Scale up Ireland to 6 Cloud Controller instances

- concourse/pipelines/create-cloudfoundry.yml
What
----
The `BILLING_DB_PLAN` environment variable is only used when creating
new databases, so this will not actually have any effect.
Still worth correcting it so the pipeline matches what we currently
have, and so it's not misleading if we need to spin up a new production
environment.
How to review
-------------
* Code review should be enough (confirm that the BILLING_DB_PLAN
variable is only used to create new DBs)
Who can review
--------------
Not Rich
> Upgrade prod billing DBs from medium to large

- manifests/cf-manifest/operations.d/750-s3-broker.yml
- platform-tests/src/platform/acceptance/run_tests.sh
- platform-tests/src/platform/broker-acceptance/run_tests.sh
- platform-tests/src/platform/broker-acceptance/s3_broker_test.go
- platform-tests/upstream/run_acceptance_tests.sh
What
----
Bumps the version of the S3 broker to a version that supports locking on bucket operations, and configures the release appropriately
Also adds an acceptance test to cover the race condition.
See [the S3 broker PR](https://github.com/alphagov/paas-s3-broker/pull/16) for most of the details
How to review
-------------
1. Code review
2. Run this branch down your pipeline
3. Test
Who can review
--------------
Anyone
> Bump s3 broker and configure locket for it

- manifests/prometheus/env-specific/prod-lon.yml
What
----
In support case
https://console.aws.amazon.com/support/cases#/6436861931/en we increased
our limit for aws_limits_elasticache_cache_parameter_groups and
aws_limits_elasticache_nodes to 300
This makes the alert match our limit, so the alert stops being red unnecessarily.
How to review
-------------
Read the support ticket: https://console.aws.amazon.com/support/cases#/6436861931/en 
Code review
Who can review
--------------
Not @tlwr
> Increase the node alert limit for elasticache

- scripts/templates/credhub_bashrc.sh
What
----
Fix path of cf admin password in credhub preamble - it was using
prometheus, but it should be using the deploy env.
How to review
-------------
Who can review
--------------
> Fix path of cf admin password in credhub preamble

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/800-set-vcap-password.yml
- manifests/cf-manifest/scripts/generate-manifest.sh
- manifests/prometheus/operations.d/800-set-vcap-password.yml
- manifests/prometheus/scripts/generate-manifest.sh
- manifests/prometheus/spec/support/manifest_helpers.rb
What
----
Following on from https://github.com/alphagov/paas-bootstrap/pull/308, this updates the create-cloudfoundry pipeline to use the bosh values stored in credhub's concourse namespace. 
It also updates the cf and prometheus deployments to use the bosh values stored in credhub.
How to review
-------------
- Review and deploy https://github.com/alphagov/paas-bootstrap/pull/308
- Code review
Who can review
--------------
Not me
> [#168427541] Update create-cloudfoundry to use bosh vars stored in credhub

- README.md
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/scripts/environment.sh
- concourse/scripts/fly_sync_and_login.sh
- concourse/scripts/pipelines-cloudfoundry.sh
- scripts/templates/credhub_bashrc.sh
[Story](https://www.pivotaltracker.com/story/show/168427704)
🐝 This is contingent on https://github.com/alphagov/paas-bootstrap/pull/307 🐝 
What
----
We now have credhub and can avoid using the concourse admin password in
stored in s3.
We don't need to use the concourse admin username/password in paas-cf
because we are using github everywhere now. As a result we can use our
own identities when doing operations locally.
How to review
-------------
Code review
Run `make dev pipelines` locally (Did I break your workflow)
Run `create-cloudfoundry` and ensure it can set its own pipeline
Who can review
--------------
Not @tlwr
> Use Concourse web password from credhub not s3

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/set-smoke-test-creds.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/upload-test-artifacts.yml
- scripts/credhub_shell.sh
- scripts/upload_secrets.rb
What
----
Upgrade to the latest version of paas-docker-cloudfoundry-tools
Specifically to the latest version of Terraform / Terraform+AWS
We experience crashes when running terraform for the first time, when
getting certificates from ACM we get EOFs. This should be fixed with a
terraform upgrade.
I think the crash is fixed [here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1560-january-16-2019)
How to review
-------------
Code review
Staging pipeline should be enough, but if you want run it down your pipeline; I've run it down mine
Who can review
--------------
Not @tlwr
> Use terraform 0.11.14

- .travis.yml
- concourse/pipelines/create-cloudfoundry.yml
- terraform/scripts/lint.sh
- terraform/scripts/set-up-pingdom.sh
- terraform/version_constraint.tf
What
----
This was missed (not rebased) in a previous commit, due to my dev env being different
Upgrade to the latest version of paas-docker-cloudfoundry-tools
Specifically to the latest version of Terraform / Terraform+AWS
We experience crashes when running terraform for the first time, when
getting certificates from ACM we get EOFs. This should be fixed with a
terraform upgrade.
How to review
-------------
Code review
> Use terraform 0.11.14 (part 2)

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- platform-tests/upstream/run_acceptance_tests.sh
What
----
Whilst on support we received a user query about a docker application not health-checking properly, this is a bug in CAPI which was fixed in https://github.com/cloudfoundry/capi-release/releases/tag/1.85.0 which is present in CF deployment >= 11.1 (we are on 11.0)
I didn't go straight to 12 because this is a support task and CF deployment 12 allegedly needs a change to BOSH DNS service aliases, which we can look into in the actual story. Also it is firebreak so I want to fix the tenant's issue with a small review.
Read the commit message, but this drops my CF acceptance test time in my pipeline to 25 minutes from 40 (previously 1 hour).
See the last two commits for details.
- Bump stemcells to `456.27` (alphagov/paas-bootstrap PR todo)
- Bump cflinuxfs3 to `0.129.0`
How to …
> [Support] Upgrade CF to 11.2, increase test parallelism, respond to CVEs

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cloud-config/paas-cf-cloud-config.yml
- manifests/cloud-config/scripts/generate-cloud-config.sh
- manifests/cloud-config/spec/compilation_spec.rb
- manifests/cloud-config/spec/vm_types_spec.rb
- manifests/prometheus/operations.d/201-monitor-bosh-internally.yml
[Story](https://www.pivotaltracker.com/story/show/168881844)
What
----
We need some cloud config to live in paas-bootstrap, so that we can move the concourse manifest to be a v2 bosh manifest.
Cloud config cannot overlap, so we have to delete some things from the cloud config in paas-cf:
- the vm definitions for compilation
- the compilation section definition
Additionally we have to specify the cpi defined in paas-bootstrap
We should name the cloud config defined in paas-cf "paas-cf" instead of "default" otherwise it is confusing.
How to review
-------------
Code review
Run this down your pipeline after https://github.com/alphagov/paas-bootstrap/pull/311
Who can review
--------------
Not @tlwr
> [#168881844] transition cloud-config to paas-cf cloud-config

- concourse/scripts/pause-kick-off.sh
What
----
Now that pinning and unpinning of dev resources is present in Concourse we can resurrect this behaviour to save money from unused dev instances.
How to review
-------------
Code review and test with
```
export VERSION="bin/fly -t $DEPLOY_ENV resource-versions -r deployment-kick-off/deployment-timer | grep time | cut -d ' ' -f3"
bin/fly -t $DEPLOY_ENV "pin-resource" -r "deployment-kick-off/deployment-timer" -v $VERSION
```
Who can review
--------------
Anyone
> Update pausing of dev deployments

- terraform/prod-lon.vpc_peering.json
What
----
There are two rules called dit-services_datasci, the later of which is
actually the VPC peering config for dit-services/datasci
The former rule is actually intended for traderemedies-services/datasci
See https://govuk.zendesk.com/agent/tickets/3823235 for context
For vpc peering configurations, the last entry with the correct name
wins
How to review
-------------
See this zendesk ticket: https://govuk.zendesk.com/agent/tickets/3823235
Who can review
--------------
Not @tlwr
> Fix VPC peering for traderemedies-services

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
For 4 reasons:
- We foresee traffic increasing until the end of october, and possibly
thereafter. This has been communicated to us by
a) the news
b) our tenants
- There are some instances of a single Gorouter randomly throwing bad
gateways for a second.
- Gorouter currently sees daily peaks of just over 50% CPU. If we were
in the middle of rolling cells, and there were only 2 gorouter
instances, we might start dropping requests.
- If we were rolling cells and we only had 2 gorouter instances, we
would only have two AZs active
The cost impliciations of this are $210USD per environment per month as
we have not reserved more router instances
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
@lukemalchergds has approved this
> Scale up routers

- manifests/prometheus/alerts.d/paas-billing-costs.yml
- tools/metrics/gauges_aws_cost_explorer.go
What
----
There's no currency conversion happening on the results of the AWS Cost
Explorer call, so the results are still in dollars.
Fixing the unit will change the name of the metric, which is a bit
annoying, but it's better than it being wrong forever.
I've fixed the alerts which refer to the metric by name - I'm not
dealing with the currency conversion in the alerts for now because I
think I'll change the way they work a bit in a future commit.
How to review
-------------
* Have a look at the surrounding code and check I'm right about the units
* That's probably enough to be honest
Who can review
--------------
> Correct unit of paas_aws_cost_explorer_by_service

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Doppler is the component in our system that handles logs from tenant
applications. When it's overloaded it will drop some logs, so tenants
will not recieve all the logs they expect.
Looking at `ALERTS{alertstate="firing",layer="",alertname="DopplerDroppedEnvelopes"}`
shows that our alert for dropped log messages have been firing almost
constantly for the last 90 days in both regions:
* [Ireland](https://grafana-1.cloud.service.gov.uk/explore?left=%5B%22now-90d%22,%22now%22,%22prometheus%22,%7B%22expr%22:%22ALERTS%7Balertstate%3D%5C%22firing%5C%22,layer%3D%5C%22%5C%22,alertname%3D%5C%22DopplerDroppedEnvelopes%5C%22%7D%22,%22format%22:%22time_series%22,%22instant%22:true,%22intervalFactor%22:1,%22legendFormat%22:null,%22step%22:null%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D …
> Scale up doppler in both regions

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/scripts/pipecleaner.py
- concourse/scripts/unbind_job.rb
- concourse/scripts/unbind_job_test.go
- concourse/spec/files_spec.rb
- concourse/tasks/create_admin.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/set-smoke-test-creds.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/upload-test-artifacts.yml
- manifests/prometheus/dashboards.d/user-impact.json
- scripts/credhub_shell.sh
- scripts/upload_secrets.rb
What
----
The changes should be fairly self-explanatory when looking at the commits, but the nuts and bolts are:
* The tasks are created in meta and are referred to as anchors throughout (because of reuse);
* The annotations are created in grafana's internal data store - this removes the need for it to be 'pulled' by prometheus, meaning it should all be pretty real-time;
* Annotations are created as a 'point', with `*add-grafana-job-annotation` and `*add-grafana-overview-annotation`, with the start and end time being the same. Once the respective `end-*` tasks are run, the end time for the annotation is updated to the current time, and the annotation changes to a range. This happens in real-time, so you can watch the deploy on grafana;
* Job annotations are for each individual build job; …
> [Firebreak] [#169004501] Concourse deploy markers in Prometheus

- manifests/cf-manifest/operations.d/310-router.yml
- manifests/cf-manifest/operations.d/329-capi-release.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
See [the release notes](https://github.com/cloudfoundry/capi-release/releases/tag/1.87.0)
This release has a number of bug-fixes for internal routes, the ones we care about are:
- failure when pushing an app for the first time with internal route
- updating a docker app will not pass healthchecks in some cases
@andy-paine can provide more context
Gorouter talks to Envoy sidecars which in turn talk to app processes.
Gorouter by default keeps 100 TCP connections open to application containers ([see docs](https://docs.cloudfoundry.org/adminguide/routing-keepalive.html))
I've set this somewhat arbitrarily to 2500 which means Gorouter is 25x more likely to keep connections open than it was previously. The cost of this is:
- a small memory increase (but we just scaled out 2x)
- …
> Upgrade CAPI and increase router max idle connections

- scripts/cf_subshell_scoped_login.sh
What
----
When logging in to CloudFoundry using SSO at the command line, users are
required to provide an authentication code that they're given at the end of the
browser-based login flow. The URL to begin the flow is given at command line,
and highlighting it to open it with the browser is annoying. This commit opens
that URL in the user's browser as a convenience, before running `cf login`.
How to review
-------------
1. Code review
2. Give it a whirl
Who can review
--------------
Anyone
> Open SSO passcode URL when using subshell login

- manifests/prometheus/dashboards.d/billing-compared-to-spending.json
- manifests/prometheus/dashboards.d/billing-sli.json
What
----
A couple of new dashboards. The main one is the billing SLI dashboard,
which shows the things we said we'd track:
* API response time
* Percentage of Billing smoke tests passing
* Performance of the slowest collector job
* Proportion of our AWS service costs which are billable
I've also added a more detailed view of the last point, which shows how
much of each service we're recharging.
How to review
-------------
* Have a quick look at the JSON
* Check the dashboards I snowflaked in to London (which should be the same):
https://grafana-1.london.cloud.service.gov.uk/d/QyoNVdTZz/richard-billing-noodling-2?orgId=1
https://grafana-1.london.cloud.service.gov.uk/d/YnS3SjOWk/richard-billing-noodling?orgId=1
* Observe that the dashboards deployed cleanly in my dev environment: …
> [#169039587] Add Grafana dashboards for billing performance

- scripts/create-org.sh
- scripts/list-org-owners.sh
What
----
So when we create new organisations they're tagged with the right owner.
Also adds a script to get the current list of orgs and their owners.
How to review
-------------
* Code review
* Run `scripts/list-org-owners.sh` against the prod environments
* Run `scripts/create-org.sh` against your dev environment
* Check that the org created has the right annotation
Who can review
--------------
> Update create-org.sh to annotate orgs with their owner

- config/billing/config.json.erb
What
----
The current USD - GBP exchange rate is 0.78
We want to try changing the rate in production to prove that there's no
adverse effect on billing performance (last time we tried it there was,
but billing had a smaller DB then, and we had a bug in the calculator
that was wrecking performance).
How to review
-------------
Who can review
--------------
> Update exchange rate to prove we can

- platform-tests/src/platform/acceptance/apps_domain_dns_tls_test.go
What
----
We have a test which compares DNS records. This test will be flakey when we have canary on the LBs
Skip DNS records acceptance test while we are canarying the LBs
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Skip DNS records acceptance test

- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/env-specific/stg-lon.yml
- manifests/cf-manifest/operations.d/380-scale-adapter.yml
What
----
Adapter instances are only deployed in z1 and z2. By default there are two of
them, so we think it makes sense to keep them at a multiple of 2, in order to
prevent one zone from receiving a majority of the traffic.
This [documentation linked in the alert](https://github.com/cloudfoundry/cf-syslog-drain-release/tree/v6.4#syslog-adapter) suggests we scale it slightly less, but I think balancing the AZs is more important than sticking exactly to the formula.
How to review
-------------
1. Code review
Deploying in a dev env won't have any effect. This will 
Who can review
--------------
Anyone
> [SUPPORT] Scale adapter instances in London to 4

- concourse/pipelines/create-cloudfoundry.yml
What
----
Release https://github.com/alphagov/paas-billing/pull/89.
How to review
-------------
* Code review.
* `paas-billing` v0.67.0 seems to have been a no-op.
Who can review
--------------
Not @46bit.
> [#169035672] Add support for daily billing exchange rate change

- manifests/cf-manifest/operations.d/310-router.yml
What
----
We have got to the point where the problem seems to be isolated to the
keepalives between gorouter and the backends. i.e. the changes to http
1.0 -> 1.1 on proxy servers has eliminated some source of errors
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Revert "Merge pull request #2108"

- terraform/cloudfoundry/lbs.tf
What
----
We should change our idle timeout to 900 seconds, which matches HAProxy, the default is 60
How to review
-------------
See the [docs](https://www.terraform.io/docs/providers/aws/r/lb.html#idle_timeout)
See [my pipeline](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/63)
Who can review
--------------
Not @tlwr
> Add idle timeout to our application LBs

- manifests/prometheus/alerts.d/cf-syslog-drains.yml
- manifests/prometheus/scripts/generate-manifest.sh
- manifests/prometheus/spec/alerts/cf-syslog-drains.test.yml
What
----
The alert was hardcoded to go off when any of the schedulers reached more than
250 drains. However, the documentation that we link to in the alert indicates
that the number of adapters should be:
(cf-syslog-drain.scheduler.drains / 250) + 2
Previously, we were running only 2 instances across the 2 availability zones,
and it was running fine, so experience suggests that the below is probably fine
as a gauge of the number adapters needed:
(sum(drains) / 250)
In this commit, I've included the
`manifests/cf-manifest/env-specific/${ENV_SPECIFIC_BOSH_VARS_FILE}` in the vars
used to generate the Prometheus manifest, so that the alerts have access to
useful variables about the scale of different components. I've then used the
`adapter_instances` variable in the alert ops file so that in …
> [SUPPORT] Update CFSyslogDrains alert to track adapter numbers

- terraform/cloudfoundry/cf_rds.tf
What
----
Since even minor version upgrades can cause downtime which we'd like to
announce ahead of time, we think it's better if we set
`auto_minor_version_upgrade` to false. This will ensure AWS don't
upgrade our database for us, but it will mean we have to schedule
updates ourselves.
We'll need to play follow up stories to upgrade to later versions of the
11.x stream.
At the moment 11.1 won't auto upgrade, according to `aws describe-db-engine-versions`:
```
{
"Engine": "postgres",
"EngineVersion": "11.1",
"DBParameterGroupFamily": "postgres11",
"DBEngineDescription": "PostgreSQL",
"DBEngineVersionDescription": "PostgreSQL 11.1-R1",
"ValidUpgradeTarget": [
{
"Engine": "postgres",
"EngineVersion": "11.2",
"Description": "PostgreSQL 11.2-R1",
"AutoUpgrade": false,
"IsMajorVersionUpgrade": …
```
> [#168372375] Pin version of cloud foundry's postgres

- manifests/prometheus/alerts.d/doppler-dropped-envelopes.yml
- manifests/prometheus/dashboards.d/user-impact.json
- manifests/prometheus/spec/alerts/doppler-dropped-envelopes.test.yml
What
----
It's constantly firing which is causing alert blindness. Ideally we'd
fix it, rather than ignoring it. We are going to raise a story to do
that. In the meantime though it's more important that we notice the other
alerts when they fire.
Also makes the "Other" alert have a dark grey background instead of the
almost-red orange we were using before.
How to review
-------------
* Code review is probs enough
Who can review
--------------
> Move the DopplerDroppedEnvelopes alert to "Other"

- concourse/pipelines/create-cloudfoundry.yml
What
----
When we were converting our pipelines to use Credhub I think we messed up how we create/update our logit drains:
- PaaS-admin was updated properly in the pipeline but with bad credentials
- PaaS-billing was not updated after it was first created so never got the bad credentials
This PR ensures the drains are always properly created/updated and that the credentials are good
How to review
-------------
Code review
Check that both tlwr paas-admin and paas-billing are shipping logs into Logit:
```
https://kibana.logit.io/s/c7358874-2b30-44a6-8271-554ad3996e50/app/kibana#/visualize/create?type=line&indexPattern=logstash-*&_g=()&_a=(filters:!(),linked:!f,query:(query_string:(analyze_wildcard:!t,query:'@source.app_name:"paas-admin"%20OR%20@source.app_name:"paas-billing-api"')),uiState:( …
```
> Make shipping logs via logit actually work

- concourse/pipelines/create-cloudfoundry.yml
What
----
The first time the `create-cloudfoundry` pipeline runs, it doesn't have
a value for `cf_pass` in credhub. This is required in the `pre-deploy`
step, which causes the pipeline to fail.
Ordinarily `cf_pass` would be generated by bosh as part of `cf-deploy`,
but since that happens later it's not much help.
Instead, this commit adds a task to generate secrets which uses credhub
to generate a value for the cf admin password (in the bosh namespace),
using the `--no-overwrite` flag to prevent this from clobbering the old
value. It then copies this secret from the bosh namespace to the
concourse namespace so it can be used in the pipeline.
How to review
-------------
* Code review
* Bootstrap a cloudfoundry using this commit to show it works (@46Bit is doing this)
Who can review …
> Fix "cf_pass is not set" on first pipeline run

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Over the last 180 days we've seen a steady upward trend of memory consumption
on the Diego cells (see GitHub PR). Today, the alarm for <30% availability was
triggered, indicating that we should scale up.
We are scaling from 33 to 36, so that we get one new cell in each AZ.
How to review
-------------
1. Code review
Who can review
--------------
Anyone
> Scale Diego cells in London to 36

- concourse/pipelines/create-cloudfoundry.yml
What
----
Fixes #2124, as `credhub generate --no-overwrite` doesn't do what we wanted. See commit message for details.
How to review
-------------
Code review. Ideally deploy to an existing env and check it doesn't update your secrets.
Who can review
--------------
Not @46bit.
> Avoid CredHub issue to generate CF admin password

- concourse/scripts/pause-kick-off.sh
What
----
In Fly v5.6.0, the `unpin-resource` action does not take a `-v|--version`
argument, but `pin-resource` does. The way the script was written did not
distinguish between the two actions, and provided the same arguments for both.
This resulted in the `unpin-resource` action doing nothing but printing out the
version of Fly.
```
$ ./bin/fly -t andyhunt unpin-resource \
-r deployment-kick-off/deployment-timer \
-v 2019-10-25T07:00:39.704321576+01:00
5.6.0
```
This commit recognises the difference between the required arguments, so that
the `unpin-resource` actually does something.
How to review
-------------
Use the `make` targets to pause an unpause your kick off deployment timer resource, and check that does what it should.
Who can review
--------------
Anyone
> Correctly (un)pin deployment kick off resource in Concourse

- manifests/prometheus/alerts.d/bosh-high-cpu-utilisation.yml
- manifests/prometheus/spec/alerts/bosh-high-cpu-utilisation.test.yml
What
----
We have an alert which tells us if a BOSH managed instance is under load.
Before this PR Diego cells and Concourse VMs were exempt from the alert.
After this PR the following instances are exempt from the alert:
- Diego cells (no change)
- Concourse (no change)
- Concourse workers (if Concourse is exempt the workers should be too)
- Compilation VMs (deploys are noisy, they should have high CPU anyway)
How to review
-------------
- Behaviour review
- Code review
- [Review this dashboard](https://grafana-1.london.cloud.service.gov.uk/d/HnfjWh0Zz/noisy-alerts?orgId=1&from=now-2d&to=now)
Who can review
--------------
Not @tlwr
> Tweak bosh high cpu alert

- terraform/cloudfoundry/dns-records.tf
- terraform/dev.tfvars
- terraform/prod.tfvars
- terraform/staging.tfvars
What
----
This was done via ClickOps and now we should put it in code
A follow up PR will remove the canary weighted set record and all traffic will go to the ALB
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Switch DNS to point to ALB

- terraform/dev.tfvars
- terraform/prod.tfvars
- terraform/staging.tfvars
What
----
The non-canary DNS record is also pointing back to the ALB
Send all traffic so the canary is not used...
How to review
-------------
Code review: verify that the regular DNS record is pointing to the ALB not the ELB: #2131 
Who can review
--------------
Not @tlwr
> Move traffic back to non-canary DNS record

- config/billing/config-parts/currency_rates.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
What
----
We think it's better for us to charge the exchange rate that we get when
we pay for our AWS usage, rather than the rate from the central bank.
This better reflects the costs which we're passing on to tenants.
This means we should not have changed the exchange rate to 0.78, and
going forwards we should update the rate whenever we make a new AWS
prepayment.
How to review
-------------
* Code review
Who can review
--------------
> Revert change to exchange rate

- manifests/cf-manifest/operations.d/100-cf-update-vm-types.yml
What
----
The scheduler VM in prod has a high load average on the active instance.
There are singleton components which run on the scheduler VM, as such
horizontally scaling it will not solve the problem.
Changing it from a medium to a large takes it from a t3.medium to an
m5.large which adds some cost, however increases the vCPU shares
allocated to it.
Additionally, when we schedule t3 instances they start with 0 CPU
credits, which means that it has no capacity to burst when under high
load. This is especially problematic when we are doing a deployment and
the scheduler VM is rolled, a new one comes up with no capacity for
bursting CPU
_Image of CPU usage from Amazon, where >100% is burst_
_Image of CPU usage from BOSH/Prometheus, review user CPU usage and load average_
The load average …
> Vertically scale the CF scheduler VM

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
This commit includes fixes for issues that were preventing upgrading tenant databases from Postgres 10 to 11 and MySQL 5.7 to 8.0 [1]. It also prevents people attempting an upgrade from Postgres 9.5 as we know that doesn't work due to issues upgrading PostGIS [2].
[1] https://github.com/alphagov/paas-rds-broker/pull/109
[2] https://www.pivotaltracker.com/story/show/169477843
How to review
-------------
Check this matches the hash of the release build of https://github.com/alphagov/paas-rds-broker-boshrelease/pull/87.
Who can review
--------------
Not @46bit
> [#169401847] Release a fix for upgrading RDS instances

- concourse/pipelines/create-cloudfoundry.yml
- terraform/cloudfoundry/outputs.tf
- terraform/cloudfoundry/paas-admin-metrics.tf
What
----
This adds an IAM user with read access to cloudwatch metrics, stores the AWS creds in credhub and passes them to paas-admin.
Related PR: https://github.com/alphagov/paas-admin/pull/493
How to review
-------------
Deploy to your dev env
Who can review
--------------
Not me
> [#169180189] Add PaaS Admin IAM User

- concourse/scripts/pipecleaner.py
- concourse/scripts/pipecleaner_test.go
- concourse/scripts/spec/fixtures/pipecleaner_secrets_interpolation.yml
What
----
We want to avoid accidentally writing bits of the pipeline like this:
```
jobs:
- name: secrets-interpolate
plan:
- task: bad-secrets-interpolate
config:
params:
SOME_KEY_THING: some-non-interpolated-value
```
It's quite likely that if the parameter key contains `KEY` or `SECRET`
the developer meant to interpolate the value with parens, like:
```
SOME_KEY_THING: ((some-interpolated-value))
```
In some cases this could cause a broken pipeline, in others it could
cause a security issue.
It's possible that there might be some legitimate use cases that cause
this test to fail in the future - it should be fine to update the test
to ignore these specifics when they come up.
How to review
-------------
* Code review
* Check the tests pass
Who can review
--------------
Not …
> Check secrets are interpolated in pipecleaner

- terraform/cloudfoundry/lbs.tf
- terraform/spec/alb_spec.rb
What
----
When registering new gorouters in the ALB, let's give them 45s to warm up before getting a full share of traffic. This will help us reduce the impact of the rare case where a gorouter has an incomplete routing table and doesn't know about all endpoints.
In the case where there is only a single target, then slow start mode is not activated.
How to review
-------------
Code review
Inspect the documentation on [slow start mode](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html)
Who can review
--------------
Not @tlwr
> Slow start router ALBs

- manifests/prometheus/dashboards.d/billing-compared-to-spending.json
- manifests/prometheus/dashboards.d/billing-sli.json
What
----
`increase` expects the metric to be a counter, which means it should
always either increase or reset to zero.
`paas_billing_total_costs_pounds` sounds like a counter, but it's
actually possible for it to go down (e.g. if we change our historical
exchange rate to be more favourable to tenants). In this case,
prometheus's `increase` function will assume it's a counter reset
followed by an unbelievably massive spend, which throws all the maths
out.
Switching to `delta` fixes this issue as it doesn't assume the metric is
a counter and therefore doesn't handle resets.
How to review
-------------
* Code review
* Compare the metrics computed [with delta](https://grafana-1.cloud.service.gov.uk/explore?left=%5B%22now-30d%22,%22now%22,%22prometheus%22,%7B%22expr%22:%22sum(delta(paas_billin …
> Switch billing costs from `increase` to `delta`

- concourse/pipelines/create-cloudfoundry.yml
- config/buildpacks.yml
- platform-tests/example-apps/healthcheck/manifest.yml
- platform-tests/example-apps/http_tester/Godeps/Godeps.json
- platform-tests/example-apps/http_tester/Godeps/Readme
- platform-tests/example-apps/http_tester/go.mod
- platform-tests/example-apps/http_tester/manifest.yml
- platform-tests/example-apps/logging-pipeline/manifest.yml
- tools/buildpacks/go.mod
- tools/metrics/go.mod
[Story](https://www.pivotaltracker.com/story/show/169572618)
🐝 [Review this PR](https://github.com/alphagov/paas-accounts/pull/12) in paas-accounts, then this commit will have to be updated
What
----
This is specifically for `ruby_buildpack` version: `v1.8.2` (we were asked by a tenant)
I had to update Go versions for the following microservices:
- paas-accounts
- paas-metrics
- platform-tests/example-apps/http_tester
- platform-tests/example-apps/healthcheck
- platform-tests/example-apps/logging-pipeline
How to review
-------------
Code review
Throw it down your pipeline
See [tlwr pipeline](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/79)
Who can review
--------------
Not @tlwr
> [#169572618] Update buildpacks [waiting until 2019/11/13]

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/scripts/pipelines-cloudfoundry.sh
- concourse/scripts/sleep_for_deploy_env.sh
What
-----
🙊 
This change should only affect the DEV environments. The await is useful and serves a purpose. But there are times, where you need to run crazy and waiting 45 minutes and 25 seconds in my case is just insaaaane.
How to review
-------------
- Code review
- `SKIP_AUTODELETE_AWAIT=true make dev pipelines`
> Add SKIP_AWAIT flag for AutoDeletion

- scripts/create-org.sh
What
----
We accidentally added some orgs with the email of their owner instead of
the name of the department that owns the org. Making the script reject
things that look like emails should prevent this in the future.
How to review
-------------
* Code review
* In a dev env, check that the script rejects emails and accepts other things
Who can review
--------------
> Check if $OWNER contains an @ and reject it if so

- manifests/prometheus/operations.d/221-monitor-cf.yml
What
----
The current scrape interval results in gaps of 5 minutes between each data point. This is because prometheus considers it stale. This lowers the scrape interval to 4 minutes.
How to review
-------------
Code review
Who can review
--------------
Not me
> [#167590572] Lower cf_exporter scrape interval

- manifests/prometheus/dashboards.d/user-impact.json
What
----
We've enabled the CF exporter, which is now noisy alerting for tenant apps
We should disable it
How to review
-------------
Code review
Check [TLWR](https://grafana-1.tlwr.dev.cloudpipeline.digital/d/paas-user-impact/user-impact-tlwr?orgId=1&refresh=5s)
Who can review
--------------
Not @tlwr
> Ignore CFApp alerts

- Makefile
- config/.rspec
- config/billing/config-parts/influxdb_pricing_plans.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/spec/billing_spec.rb
- config/spec/spec_helper.rb
What
----
Richard discovered that the billing collector has been stopped since InfluxDB was released to beta
This is because the pricing plans are violating the DB constraint that they must be valid from the start of the month
This PR fixes this, and adds a test
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Correct pricing plans for InfluxDB

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Bumps the CDN broker version to include https://github.com/alphagov/paas-cdn-broker/pull/26
How to review
-------------
Code review (Already deployed to my env)
Who can review
--------------
Not me
> [#169728785] Bump cdn-broker; Use acme V2 for account creation

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
See https://github.com/alphagov/paas-uaa-release/pull/16
Use the latest version of UAA on our fork, so we are not vulnerable to CVEs
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Update UAA to use 74.10.0 fork

- manifests/prometheus/dashboards.d/user-impact.json
What
----
We have a chart on the user impact dashboard in Grafana which shows the number
of application instances that are running, versus how many should be running.
At the moment, the y-axis is scaled from zero to the maximum number of
instances in the time range. We have >1000 application instances in London and
>800 in Ireland, so the granularity of the y-axis is pretty coarse; 250 in
London, 200 in Ireland). This makes it difficult to see anything but the most
drastic changes in the number of instances.
Instead, in this commit we allow Grafana to pick a sensible scale for the axis
based on the data being charted.
Below is an example of how it would look in Grafana
Versus how it looks now
How to review
-------------
1. Code review
2. Discuss if we think this is a good thing
Who can …
> Automatically scale the Y-axis of the app instances chart

- manifests/cf-manifest/operations.d/750-s3-broker.yml
What
----
This PR fixes up #2172, which sadly shipped a too-old version of the S3 Broker.
This releases version 0.1.11 of the S3 Broker BOSH Release, as built by [1]. The S3 Broker commit used to build that is definitely one that includes the ability to configure CORS [2].
[1] https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/s3-broker-release/jobs/build-final-release/builds/2
[2] https://github.com/alphagov/paas-s3-broker-boshrelease/commit/c2287df6e44c8e44f50841acddf06680b09760f4
How to review
-------------
* Double-check the BOSH Release being shipped does include CORS;
* We *can* deploy this to a dev env to check, but from the story summary I'm pretty sure @richardTowers already successfully did that work for us 🎉 
Who can review
--------------
Not @46bit
> [#169891611] Release feature for users to configure CORS on S3

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- scripts/upload-splunk-secrets.rb
What
----
We'd like to be constantly pushing this to our environment allowing
splunk to receive the audit events from CF API.
We're adding set of credentials into the system, that will be then used.
Splunk URL is not really a secret, therefore doesn't deserve a place in
our secret store.
How to review
-------------
- Sanity check
- See `rafalp` environment
**Note:** I have uploaded the certs to all envs, but doesn't hurt to do again.
> Deploy app shipping audit events to Splunk

- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
What
----
On 2019-12-03, AWS support upped our Elasticache node and parameter group
limits in Ireland and London. This commit updates those values in our alarms,
so that we're alerting on them properly.
How to review
-------------
1. Code review
Who can review
--------------
Anyone
> [SUPPORT] Update Elasticache node and param group limits

- config/users.yml
What
----
This commit adds Global Auditor to Satwinder in PMO. This will allow them to see things such as billing reports. The Google ID is sourced from their existing PaaS account in London, which they already switched to signing in with Google SSO.
How to review
-------------
* Code review.
Who can review
--------------
Not @46bit.
> Grant Global Auditor to Satwinder in PMO

- config/users.yml
What
----
This commit adds information to `config/users.yml` explaining what it
is and what permissions are granted. This commit then gives
instructions on how to add brand new users, including how to avoid a
frustrating edge-case that we investigated in [Pivotal #170056541](https://www.pivotaltracker.com/n/projects/1275640/stories/170056541).
How to review
-------------
* Read the instructions and see if they make sense to you;
* I checked that this comment didn't cause problems for the things using this file. My `miki` dev environment deployed fine with this comment.
Who can review
--------------
Not @46bit.
> [#170056541] Add instructions to the platform users config

- tools/metrics/gauges_cf.go
- tools/metrics/go.mod
- tools/metrics/go.sum
What
----
Previous version was from 2017 and did not follow the next URL for the service plan endpoint. That meant it couldn't get more than one page.
This also updates the findServicePlan error to include the ServicePlanGuid.
How to review
-------------
Paired on with @AP-Hunt
> [Support] Bump go cf-client version

- tools/user_management/lib/group.rb
- tools/user_management/spec/group_spec.rb
- tools/user_management/spec/spec_helper.rb
What
----
The `origin` field of a group member is not the same as the `origin` field of a user. From https://docs.cloudfoundry.org/api/uaa/version/74.4.0/index.html#add-member:
> `origin`: The originating IDP of the entity, or "uaa" for groups and internal users
So users signing in with Google should have an origin of `google`, but their group memberships should have an origin of `uaa`.
How to review
-------------
* See that the tests go green;
* Code review.
I've run this manually against staging and it worked as expected 🎉:
* The existing group memberships with `origin=google` were all removed.
* New group memberships with `origin=uaa` were created.
* Subsequent runs don't make any unexpected changes.
Who can review
--------------
Not @46bit.
> [#170056541] UAA group member's origin should equal "uaa"

- concourse/pipelines/create-cloudfoundry.yml
What
----
Currently, the design of this application is not perfect. Upon crash or
restart it's job will be to re-ingest all the audit events from CF to
Splunk over and over again. This is limited by a specific date, which
now is almost a month ago, meaning the number of duplicated logs will
get insane soon...
There is an improvement, which instead of locking down to a date, will
lock down to N minutes ago, which should sanitise the ingestion but not
eliminate the problem fully.
How to review
-------------
- Sanity check
> Bump the paas-audit-to-splunk app

- concourse/pipelines/create-cloudfoundry.yml
[Story](https://www.pivotaltracker.com/story/show/170129714)
What
----
The deploy-aiven-service-broker task currently fails if another broker is added
with an elasticsearch service. This updates the command to specify the aiven
broker.
How to review
-------------
Code review
Who can review
--------------
Not me
> [#170129714] Specify broker when enabling Elasticsearch service

- config/spec/users_spec.rb
- config/users.yml
What
----
This commit adds some tests that entries in the `config/users.yml` file are sensible. It ensures that users _with the same permissions_ are listed with their emails in alphabetical order.
This means we can still cluster similar users (e.g., people with `cf_admin: true`) while keeping those clusters alphabetical.
I'm fairly confident this is compatible with @richardTowers current work to drop the `cf_admin` boolean and use YAML anchors instead. The expected fields and the fields used to group permissions will need changing, but not the approach.
I did this as part of adding two new joiners as Global Auditors, but then I realised we don't have their Google IDs yet.
How to review
-------------
* Code review;
* See that the tests pass.
Who can review
--------------
Not @46bit.
> Alphabetise users with the same permissions

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
There has been a steady increase in in cell memory usage over the last 30 days. This increases the number in London to 42.
How to review
-------------
Code review
Who can review
--------------
Not me
> [Support] Scale Diego cells in London to 42

- concourse/scripts/rds_instances.sh
What
----
In commit 0242505330c72550b85d817c81c5328b5ee66bf2, the shebang for
`concourse/scripts/rds_instances.sh` was changed to `/bin/bash`. However, the
container iin which this script runs does not contain `/bin/bash`, only
`/bin/sh`. This resulted in environment kickoffs being broken.
How to review
-------------
1. Code review
Who can review
--------------
Anyone but me
> Revert the change to RDS database kick off in 0242505330c7

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/310-router.yml
- manifests/cf-manifest/operations.d/329-capi-release.yml
- manifests/cf-manifest/operations.d/360-log-api.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
v12.18.0 was released 7 days ago (2019-12-04) relative to now (2019-12-10). There are more recent releases 2 days ago, 18 hours ago and 16 hours ago, but I’m choosing v12.15.0 for the sake of not releasing something which other people haven’t had chance to test.
Upgrade notes are in [this hackmd document](https://hackmd.cloudapps.digital/AOadTZQPTOGidskEPFSAnQ?view)
How to review
-------------
1. Review my notes
1. Review the PR
1. Check my pipeline (N.B. acceptance tests failed because I'd pushed a custom buildpack whilst it was running. There's a second run which passes once I deleted the buildpack)
1. Run it down your pipeline
Who can review
--------------
Anyone
> [#169775886] Upgrade to cf v12.15.0

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- scripts/upload-paas-trusted-people.sh
- tools/user_management/lib/user.rb
- tools/user_management/main.rb
- tools/user_management/spec/user_spec.rb
What
----
We had to handle a slightly different configuration file format, so:
```
- email: ''
roles: []
```
instead of:
```
- email: ''
cf_admin: true
```
so we're fixing the tools/user_management scripts to work with the new
format.
paas-trusted-people is a private repo, so we have to upload it to S3 and
then download it in the pipeline (because the pipeline can't clone
private repos).
How to review
-------------
* Code review
* Upload paas-trusted-people to S3 in your dev env by running `make upload-paas-trusted-people DEPLOY_ENV=blah`
* Run the create-cloudfoundry pipeline and check that the `post-deploy/sync-admin-users` task does something sensible
Who can review
--------------
Not @richardtowers or @schmie
> Use paas-trusted-people user configuration file

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/030-bosh-dns.yml
- manifests/cf-manifest/spec/manifest/bosh_dns_spec.rb
What
----
See https://github.com/alphagov/paas-bootstrap/pull/331 for info WRT stemcells
Since we did #2197 the log-api instance has had high CPU, and has been generating many logs, this is because of changes to trafficcontroller (a partially deprecated loggregator component).
The reason for this is that many successful DNS requests are being logged, which is a bit pointless, and very noisy. In 1 hour it generated 8 million DNS requests in my development environment.
We're updating BOSH DNS because we were a bit behind, and we are setting the log level to WARN instead of DEBUG/INFO
Problems with DNS resolution should be caught by the blackbox DNS canary on each VM. We added some spec tests for BOSH DNS as well
Because BOSH DNS is an addon, we are doing it in the same PR as a stemcell …
> Upgrade BOSH DNS, set log level, update stemcells

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/500-syslog-forwarder.yml
What
----
Updates cf-deployment to 12.19
Updates syslog release to 11.6
How to review
-------------
See [hackmd](https://hackmd.cloudapps.digital/xX3r3HQOSZqxVwgJy3yTkg)
Check that [TLWR](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/acceptance-tests/builds/32) went green (except for custom domain CATS because I have an extra shared domain)
Maybe run it down a dev env
Who can review
--------------
@LeePorte
> Update cf-deployment to 12.19 and bump syslog release to 11.6

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/data/100-tenant-uaa-client-config.yml
- manifests/cf-manifest/scripts/generate-manifest.sh
- manifests/cf-manifest/scripts/generate-tenant-uaa-client-ops-file.rb
- manifests/cf-manifest/spec/fixtures/tenant-uaa-client-fixtures.yml
- manifests/cf-manifest/spec/manifest/tenant_uaa_clients_spec.rb
- manifests/cf-manifest/spec/support/manifest_helpers.rb
What
----
In some cases, we'll grant a tenant a custom UAA client. The client should only
exist in a specific environmen, and its secret is managed in by our credhub
instance.
The configuration of the clients is managed in
`manifests/cf-manifest/data/100-tenant-uaa-client-config.yml`, and a task in
the `generate-cf-config` stage of the pipeline generates an ops file for Bosh
based on that config, for the given deployment env.
How to review
-------------
1. Code review 
2. Do a proper pipeline review
Who can review
--------------
Anyone
> [SUPPORT] Create custom UAA clients for tenants in different deployments

- config/logit/20_custom_cf_filters.conf
- config/logit/output/generated_logit_filters.conf
What
----
In routing-release 0.196.0, gorouter began logging two new metrics:
`gorouter_time` and `app_time`. These metrics tell operators how long a request
spent in the gorouter and the app, respectively. Previously, it was only
possible to see a `response_time` metric, which showed the time for the full
roundtrip.
We have been receiving the fields since we upgraded to routing-release 0.196.0,
but we haven't been correctly indexing them. This commit addresses that, by
converting the fields in to floats.
What you should know
-------------
I've applied the filter in the `dev` ELK stack and refreshed the fields. I think that, since we've been ingesting this field for a while, it already exists, and its type can't be (trivially) changed in the current index. The next time an index is …
> [#170423077] Convert gorouter {gorouter,app}_time metrics to floats

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/cf-manifest/operations/change-vm-types-dev.yml
- manifests/cf-manifest/operations/scale-down-dev.yml
- manifests/cf-manifest/spec/manifest/dev_scaling_spec.rb
- manifests/cf-manifest/spec/manifest/prometheus_spec.rb
What
----
The CF Prometheus for our users should be highly available, which it currently isn't with 1 instance. This commit makes it highly available but only 2 instances which is probably enough
The CF Prometheus in London is currently running quite hot (85% memory) usage due to Prometheus. This is causing it to use swap lots. In non-dev environments make it a t3.medium
In dev, we will rarely scrape anything, so we can keep the values as they are
How to review
-------------
Travis
Code review
Look at [prod-lon](https://grafana-1.london.cloud.service.gov.uk/explore?left=%5B%22now-6h%22,%22now%22,%22prometheus%22,%7B%22expr%22:%22bosh_job_mem_percent%7Bbosh_job_name%3D%5C%22prometheus%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
Who can review
--------------
Not @tlwr
> Scale up CF prometheus in non-dev environments

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/cf-manifest/spec/manifest/prometheus_spec.rb
[Story](https://www.pivotaltracker.com/story/show/170070487)
What
----
We have a single aiven project for prod and prod-lon
This mean aiven service discovery was discovering both regions and the
CF prometheus was trying to scrape all prometheis, even those in a
different region. It cannot scrape those in a different region due to ip
restrictions
This commit updates the service discovery version to a version which
labels the targets using the cloud name exposed by aiven, and uses a
prometheus relabel to only keep instances that are in the same region
How to review
-------------
Code review
Review this screenshot of my dev environment (London), not discovering Rafal's Elasticsearch (Ireland)
Check [my custom acceptance test passed](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/p …
> [#170070487] Aiven service discovery only discover same region

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/230-loggregator-deployment.yml
What
----
- Bump `cflinuxfs3-release` to `0.153`
- Bump stemcells to `621.41`
- Bump `loggregator-release` to `106.3.4`
See the commits for details
How to review
-------------
Code review
Check TLWR pipeline:
- [Acceptance tests](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/acceptance-tests/builds/47) 🍏 
- [Custom acceptance tests](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-acceptance-tests/builds/50) red only because of my custom domain
- [Broker acceptance tests](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-broker-acceptance-tests/builds/51) 🍏 
Who can review
--------------
Not @tlwr
> Respond to CVEs

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/cf-manifest/spec/manifest/dev_scaling_spec.rb
What
----
Our cf prometheus (the one scraping elasticsearch) is using a considerable amount of swap space, because it does not have enough memory
This PR scales it up when we are not in dev, to a large vm, so that it has enough memory to do its duty
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Scale up CF prometheus when not in dev

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/cf-manifest/spec/manifest/prometheus_spec.rb
What
----
We should keep metrics for some time
We should configure both retention time and retention size such that:
- we do not store data for much longer than a year
- we do not attempt to store more data than we have available space on
our persistent volume
The [prometheus documentation](https://prometheus.io/docs/prometheus/latest/storage/) provides the following guidance:
> If both time and size retention policies are specified, whichever policy triggers first will be used at that instant.
so if we start to run out of space, then we will get rid of the oldest metrics, and we will still be able to collect metrics
How to review
-------------
Code review
CI
This has been deployed to my dev environment, where you can check the [command line …
> Configure long term storage of CF prometheus

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/cf-manifest/spec/manifest/dev_scaling_spec.rb
- manifests/cloud-config/paas-cf-cloud-config.yml
- manifests/variables.yml
What
----
We are experiencing scaling issues with our CF prometheus in London
It is doing a lot of work, and tsdb compaction (or something else) seems to be using most of its resources, whilst it is also trying to collect metrics for >~ 100 ES instances
Giving it some more resources will let it do its job
_An image of Grafana showing metrics of the CF Prometheus BOSH instance; CPU is pegged to the 50% alloted via bpm, and memory is almost maxed, after something (probably compaction)_
How to review
-------------
Code review
CI
Who can review
--------------
Not @tlwr
> Add xlarge instance type and use for cf-prometheus

- manifests/cf-manifest/operations.d/500-prometheus.yml
- scripts/credhub_shell.sh
- scripts/showenv.sh
What
----
Adds a new user to the CF prometheus with username `operator`
Documents the URL for the CF prometheus in `make showenv`
Documents the usernames for various things in `make credhub`
How to review
-------------
Run this down your pipeline
Verify `make dev showenv` has the URL for CF prometheus
Log into the CF prometheus using the URL, and the username/password from `make credhub`
Who can review
--------------
Not @tlwr
> Add cf prom info/docs to showenv/credhub shell

- manifests/prometheus/dashboards.d/user-impact.json
- manifests/prometheus/operations.d/207-monitor-alertmanager.yml
What
----
If we have a long running noisy alert that we are waiting for upstream to fix, we would like to silence it, so that we do not succumb to alert blindness.
However, currently, our user impact dashboard naively displays the number of firing alerts (with some extra filtering), and does not know about alertmanager at all.
If we silence alerts in alertmanager, we should subtract the number of suppressed alerts on the user impact dashboard alerts tile.
Example
-------
Consider the following alerts firing:
```
log-api/0 BoshHighCPUUtilisation
log-api/1 BoshHighCPUUtilisation
log-api/2 BoshHighCPUUtilisation
log-api/3 BoshHighCPUUtilisation
log-api/4 BoshHighCPUUtilisation
log-api/5 BoshHighCPUUtilisation
scheduler/0 AuctioneerLockHeldOnce
```
there are 7 alerts firing.
If we had a …
> Scrape alertmanager to subtract suppressed alerts from the user-impact dashboard

- manifests/prometheus/dashboards.d/user-impact.json
What
----
We run multiple alertmanagers in non-dev so summing the number of silenced alerts duplicates the number of silences
How to review
-------------
Calculate that `7 - sum(7, 7)` is not 0
Calculate that `7 - avg(7, 7)` is 0
Code review
Who can review
--------------
Pair with @schmie
> Correctly aggregate multiple alertmanager silences

- manifests/cf-manifest/operations.d/030-bosh-dns.yml
- manifests/cf-manifest/operations.d/230-loggregator-deployment.yml
What
----
Since we most recently upgraded `cf-deployment` we have had a long running issue with high CPU utilisation on `log-api` instances.
This release:
* https://github.com/cloudfoundry/bosh-dns-release/releases/tag/v1.17.0
Contains the following fixes:
* stop redundant health check retries between poll intervals
* stop redundant health check requests when querying a domain
* Fix compilation error on windows due to broken symlinks
* health server should shutdown cleanly on sigterm
The following fixes:
* stop redundant health check retries between poll intervals
* stop redundant health check requests when querying a domain
cause loggregator component trafficcontroller's very chatty dns
healthcheck to be cached by bosh-dns, which will reduce the currently
high cpu usage (there is another …
> Upgrade bosh-dns-release to 1.17

- manifests/prometheus/alerts.d/elasticache-node-count.yml
- manifests/prometheus/env-specific/prod-lon.yml
What
----
The ElastiCache nodes limit in London has been increased to 500. This updates
the config to reflect the new limit.
How to review
-------------
Code review
Who can review
--------------
Not me
> [Support] Bump Elasticache Node Limit In London

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/cf-manifest/spec/manifest/prometheus_spec.rb
What
----
Our prometheus uses a lot of memory in london because it has to deal with a lot of metrics
We do not care about a lot of these metrics, as we only surface 8 of them to our users
We can drop a few metrics to save on disk space and memory usage (cache + compaction)
How to review
-------------
Code review
Look at the tests
[Evaluate this query as an example](https://prometheus.london.cloud.service.gov.uk/graph?g0.range_input=1h&g0.expr=count%20by%20(__name__)(%7B__name__%3D~%22elasticsearch_(breakers%7Cthread%7Cfs%7Cindices%7Cos)_.*%22%7D)&g0.tab=1)
[Review this chart](https://grafana-1.london.cloud.service.gov.uk/explore?left=%5B%22now-30d%22,%22now%22,%22prometheus%22,%7B%22expr%22:%22max%20by%20(bosh_job_process_name)%20(bosh_job_process_mem_percent%7Bbosh_job_name%3D%5C%22promet …
> Drop unnecessary metrics from cf prometheus

- concourse/tasks/configure-grafana.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations.d/333-uaa-add-oauth.yml
- scripts/upload-secrets/upload-google-oauth-secrets.rb
- tools/user_management/lib/group.rb
- tools/user_management/lib/user.rb
What
----
We'd like to be able to log into the platform as admins, on rare occasion.
This can be achieved with having another OAuth application.
How to review
-------------
- Sanity check
- Deploy to your own dev env; or
- Log into `rafalp` and play with both roles
🐝🐝🐝 Before merge 🐝🐝🐝
------------
- Make sure that the WIP commit is pointing to stable release
> Separate platform-operator level access login

- manifests/cf-manifest/operations.d/230-loggregator-deployment.yml
What
----
See https://github.com/cloudfoundry/loggregator-release/issues/401 and https://github.com/cloudfoundry/loggregator-release/releases/tag/v106.3.8
_Image of `log-api` instance CPU usage in my development environment, where the reduction in CPU usage is the change_
See #2233 for another `log-api` DNS related change
How to review
-------------
Code review
CI
Read the links above
Who can review
--------------
Not @tlwr
> Bump loggregator to version which does not DOS DNS

- manifests/cf-manifest/operations.d/333-uaa-add-oauth.yml
- manifests/cf-manifest/spec/manifest/oauth_spec.rb
- tools/user_management/lib/actions.rb
- tools/user_management/lib/group.rb
- tools/user_management/lib/user.rb
- tools/user_management/main.rb
- tools/user_management/spec/group_spec.rb
- tools/user_management/spec/user_spec.rb
[Story](https://www.pivotaltracker.com/story/show/170702697)
What
----
Read the code for full context, however:
- We now have two identity providers which are both Google
- We were using `sub` as the UAA username, which meant we had duplicate usernames between origins
- Cloud Controller and the CF CLI do not deal well with duplicate usernames _at all_
- Admin users cannot use `cf create-space` as a result, due to duplicate usernames, because it attempts to assign space manager to the creator, but fails when the usernames are not unique
This PR:
- More thoroughly tests the OAuth operations
- Adds a test to ensure that the attribute mappings across identity providers is unique
- Updates the user management tool to use `username` which is determined by `main.rb` using the `cf-admin` role as …
> [#170702697] Fix admin google OIDC claim

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/cf-manifest/operations/change-vm-types-dev.yml
- manifests/cf-manifest/spec/manifest/dev_scaling_spec.rb
- manifests/cf-manifest/spec/manifest/prometheus_spec.rb
- manifests/cloud-config/paas-cf-cloud-config.yml
What
----
We are now storing up to 370 days of metrics, which will require > 100GB of storage
This will also give us more IOPS, which should reduce resource usage during compaction
The cost implications in prod are:
- before: 4 * 100 GB = 42.92USD
- after:  4 * 500 GB = 288.52USD
There are no cost implications in development environments
We also have recently had problems with memory usage, when [prometheus is compacting](https://prometheus.io/docs/prometheus/latest/storage/#compaction). The increased disk size will give us more IOPS, by a factor of 5 (because we are increasing the disk size by 5). This may make compaction a bit more efficient and require less memory usage.
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Increase size of  CF prometheus persistent disk

- manifests/prometheus/alerts.d/cf-audit-events-collecting.yml
- manifests/prometheus/alerts.d/cf-audit-events-shipping.yml
What
----
We'd like to be notified if:
* we aren't collecting events we should have a warning alert
* we aren't shipping events we should have a warning alert
Setting up these two alerts should trigger a warning, if the above are
true.
This particular change is making me concerned, as we appear to be
shipping 20 times more events than we collect on average.
How to review
-------------
- Sanity check
- Visit our prometheus and run the queries
- play with the time frames and values to see sweet spots
> Add PaaS Auditor alerts

- config/logit/20_custom_cf_filters.conf
- config/logit/output/generated_logit_filters.conf
What
----
You know what.
How to review
-------------
* Code review.
* See that this has worked in staging:
Who can review
--------------
Not @46bit
> Drop debug logs from Cloud Controller job queue

- concourse/pipelines/create-cloudfoundry.yml
What
----
The informer database metric did a naive `COUNT(*)` which takes ages, we've used `relcount` to amortise this
This PR promotes the tag
Done as pair with @paroxp
> Promote paas-auditor tag with fast informer metric

- manifests/prometheus/env-specific/default.yml
- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
- manifests/prometheus/env-specific/stg-lon.yml
What
----
We had a small incident where our proudction environments reached the limit on
the number of AWS RDS instances they could create in their respective regions.
This happened because we didn't have an alert for it, like we do for the number
of ElastiCache nodes and S3 buckets. We didn't have an alert because we didn't
have data.
This commit adds a new `aws_limits_rds_instances` variable, so that when we get
a metric for the number of RDS instances in a region, we can create alerts. It
also acts as a bit of documentation about our limits.
How to review
-------------
1. Just check I've not somehow mucked something up. There are no changes in behaviour.
Who can review
--------------
Anyone
> Add `aws_limits_rds_instances` variable to Prometheus env-specific vars

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Bumps CF to 12.29.0
Bumps UAA fork 
How to review
-------------
- Review https://github.com/alphagov/paas-uaa/pull/15 & https://github.com/alphagov/paas-uaa-release/pull/18
- Update WIP commit and pinned release test
Who can review
--------------
Not me or @schmie
> [#171053583] Upgrade CF to 12.29.0

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
This releases https://github.com/alphagov/paas-cdn-broker/pull/27, which removes an unwanted log line from the CDN Broker.
How to review
-------------
Double-check the boshrelease build matches the output from https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/cdn-broker-release/jobs/build-final-release/builds/3.
Who can review
--------------
Not @46bit
> [#171132351] Drop unnecessary CDN Broker log line

- manifests/cf-manifest/operations.d/310-router.yml
- manifests/cf-manifest/spec/manifest/router_spec.rb
What
----
We enable keepalives and they caused some base 502s due to keepalives
We validated this was a problem for 45 minutes with Notify and noticed ~39
random 502s which couldn't be correlated to anything else
How to review
-------------
CI
Code review
Who can review
--------------
@paroxp
> Disable keepalives again

- scripts/credhub_shell.sh
[Story](https://www.pivotaltracker.com/story/show/170894390)
What
----
We are now using user identities for BOSH and Credhub shells
Let's use them instead of the shared client
How to review
-------------
Code review
Try it out
Who can review
--------------
@AP-Hunt
> Use user identity for credhub shell

- scripts/upload-secrets/upload_secrets.rb
What
----
This PR was made in the context of us now using individual IDP identities rather than shared credentials for accessing credhub
We do not need the layers of docker to do things, we can just compose the shell tasks
i.e. the workflow shouldnt be:
```
- make dev upload-all-secrets # do all the things
```
instead we can rely on people to compose the steps correctly, with appropriate pointers along the way. This way the code is easier to follow and is less fragile to change:
```
- make dev credhub
> credhub login --sso
> make upload-all-secrets
```
(where > represents a subshell)
How to review
-------------
You might need the latest paas-bootstrap to do this, or try against staging:
```
$ make stg-lon credhub
credhub subshell $ credhub login --sso
credhub subshell $ make …
```
> Use credhub shell for uploading secrets

- manifests/cf-manifest/operations.d/510-add-prometheus-blackbox-exporter.yml
What
----
Our Prometheus in the CF BOSH deployment is responsible for scraping a large quantity of metrics from Elasticsearch (ES) instances. Our users query Prometheus to see metrics about their ES instances.
Periodically, Prometheus compacts metrics it has collected into smaller blocks. We see really high memory during TSDB compaction:
Which is fixed in Prometheus 2.15:
- [Release](https://github.com/prometheus/prometheus/releases/tag/v2.15.0)
- See "TSDB: Significantly reduced memory footprint of loaded TSDB blocks"
- See "TSDB: Significantly optimized what we buffer during compaction which should result in lower memory footprint during compaction"
- See "TSDB: Improve replay latency"
- See "TSDB: WAL size is now used for size based retention calculation"
Prometheus BOSH deployment …
> Upgrade cf-prometheus release

- manifests/prometheus/operations.d/201-monitor-bosh.yml
- manifests/prometheus/operations.d/205-monitor-node-UPSTREAM.yml
- manifests/prometheus/operations.d/206-monitor-node.yml
[Story](https://www.pivotaltracker.com/story/show/169397386)
What
----
We are deploying the Prometheus node exporter as an addon, since https://github.com/alphagov/paas-bootstrap/pull/350
We need to:
- Add the director as a scrape target
- Add the local prometheus node exporter as a scrape target
- Only scrape internally (i.e. no external IPs - only 10/8 127.0.0.1)
How to review
-------------
Deploy https://github.com/alphagov/paas-bootstrap/pull/350
Run CF pipeline
Check Prometheus is scraping all the node exporters in all deployments
Who can review
--------------
Not @tlwr
> [#169397386] Add node exporter

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Ship https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/25 to increase request timeouts through new CDN Route instances to 60 seconds.
How to review
-------------
1. Review https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/25
2. Update the boshrelease build YAML in this to the final build once https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/25 is merged
Who can review
--------------
Not @46bit
> [#170622539] Increase cdn-route response timeouts to 60 seconds

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Upgrades `cf-deplyoment` from `v12.29.0` to `v12.33.0` to address the following USNs
- USN 4269-1
- USN 4263-1
- USN 4274-1
- USN 4277-1
This also has the side effect of resolving a CAPI issue which causes apps with a large number of environment variables to fail to deploy.
Left to do
-----------
How to review
-------------
1. Code review
2. Check the versions bumped to here match those in the pivotal story
3. Check it runs down a pipeline OK
Who can review
--------------
Anyone
> [#171404935] Upgrade cf-deployment from v12.29.0 to v12.33.0 to address USNs

- concourse/pipelines/create-cloudfoundry.yml
What
----
We want to rotate the broker passwords. This commit adds a new job that will rotate the passwords in Credhub. When the main `create-cloudfoundry` deploy pipeline is next run it will update the brokers to use the new credentials and update Cloud Controller to use those new credentials too.
This operation is not zero-downtime; our brokers do not support multiple credentials at once. But for the cases when we want to rotate it's OK to have brief downtime for creating or updating services. Apps talking to existing services aren't affected.
This does not rotate every broker-related secret. The RDS Broker's `master_password_seed` property is not rotated. Thankfully we don't need to rotate that right now because there is no easy way to rotate it.
How to review
-------------
This can be …
> [#171180051] Add a concourse job to rotate broker credentials

- config/billing/config-parts/redis_pricing_plans.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- platform-tests/src/platform/broker-acceptance/redis_service_test.go
What
----
Enables and configures Redis 4.x and 5.x plans
Blockers
---
How to review
-------------
1. Code review
2. Check it ran down [my pipeline](https://deployer.andyhunt.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry) successfully
3. Check paas-elasticache-broker-boshrelease is using a prod release, and not a dev release.
After review
---
1. Merge the [`paas-elasticache-broker` PR](https://github.com/alphagov/paas-elasticache-broker/pull/21)
2. Bump the version in the [`paas-elasticache-broker-boshrelease` PR](https://github.com/alphagov/paas-elasticache-broker-boshrelease/pull/11) and merge it
3. Update [the commit setting the version of `paas-elasticache-broker-boshrelease`](https://github.com/alphagov/paas-cf/pull/2268/commits/3cf9d17b8f85780053a97c7ace87b10d3d58 …
> [#171183319]Configure redis 4x 5x plans

- manifests/prometheus/operations.d/303-scrape-bosh-auditor.yml
What
----
Since https://github.com/alphagov/paas-bootstrap/pull/356 we have a microservice running on the BOSH VM which exposes metrics about how many audit events have been shipped.
The prometheis we use for operator metrics should scrape these exposed metric(s).
Who worked on this
----
Pair with @schmie
> prometheus should scrape bosh-auditor

- config/buildpacks.yml
What
----
Upgrading buildpack due to cve-2019-15605
How to review
-------------
Code review
Upgrades to the version specified in https://github.com/alphagov/paas-cf/pull/2272
Who can review
--------------
Not me
> [Support] Bump NodeJS Buildpack to v1.7.13

- scripts/cf_subshell_scoped_login.sh
What
----
The extra slash was creating a value for CF_HOME which was not the actual path.
How to review
-------------
1. Look at the one character I removed
Who can review
--------------
Me, probably.
> Remove extraneous slash in CF_HOME set by subshell script

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Scaling due to memory alert for diego cells. Our chart also shows that it's time to increase the number of cells.
How to review
-------------
Code review
Who can review
--------------
Not me
> [Support] Scale Diego cells in London to 48

- manifests/cf-manifest/env-specific/prod.yml
What
----
We expect Ireland to receive new services soon with lots of traffic. Scaling up now will give us plenty of capacity when that happens.
Routing: This PR scales us from 6 to 12 gorouters. My belief is these 12 routers will cope with 1,200–3,600rps. If CDN route caching is setup properly that should be enough. It's very possible this will expose other bottlenecks within PaaS.
Logging: This PR scales us from 24 to 27 dopplers. We don't expect them to log massively, but expanding our ability to process logs will reduce the chance of nasty surprises affecting other tenants.
How to review
-------------
Consider whether this scale is appropriate. If you need to discuss details of the new services I suggest talking in the [Pivotal …
> [#171896989] Scale Ireland up for new services

- manifests/cf-manifest/operations.d/530-ipsec.yml
[Story](https://www.pivotaltracker.com/story/show/164728382)
What
----
Do not use our IPSec release, use SAP's (upstream) instead
We forked the release to change some file permissions, which has been merged upstream.
This doesn't actually change any packages at all, so [it didn't modify any instances during deployment](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/151).
How to review
-------------
[Review the no-op changes upstream](https://github.com/alphagov/paas-ipsec-release/compare/gds_master...SAP:master)
Who can review
--------------
Not @tlwr
> [#164728382] Use upstream ipsec release

- platform-tests/src/platform/broker-acceptance/run_tests.sh
What
----
We have been hitting the limit on the current timeout for the broker acceptance tests since adding the new ElastiCache plans due to the additional work that is happening in the broker acceptance tests. I have increased the timeout as a result.
How to review
-------------
Code review
Who can review
--------------
Anyone
> Increase broker acceptance timeouts

- concourse/pipelines/create-cloudfoundry.yml
What
----
The ability to share service instances between spaces has been requested by some tenants as it enables some of our tenants to speed up the creation of PR test instances to aid in their CI/CD workflow.
How to review
-------------
Code review
Have deployed to my dev env without issue. feel free to check there
Who can review
--------------
Anyone
> Enable `service_instance_sharing` flag

- concourse/pipelines/create-cloudfoundry.yml
- config/service-brokers/aiven/config.json
- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/711-rds-broker-postgres95-plans.yml
- manifests/cf-manifest/operations.d/712-rds-broker-mysql57-plans.yml
- manifests/cf-manifest/operations.d/713-rds-broker-mysql57-plans-high-iops.yml
- manifests/cf-manifest/operations.d/714-rds-broker-postgres10-high-iops-plans.yml
- manifests/cf-manifest/operations.d/715-rds-broker-postgres10-plans.yml
- manifests/cf-manifest/operations.d/716-rds-broker-postgres11-plans.yml
- manifests/cf-manifest/operations.d/717-rds-broker-postgres11-high-iops-plans.yml
- manifests/cf-manifest/operations.d/718-rds-broker-mysql80-plans.yml
- manifests/cf-manifest/operations.d/719-rds-broker-mysql80-plans-high-iops.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/operations.d/750-s3-broker.yml
What
----
The goal is to have some nicely presented data in our PaaS Admin tool.
The ServiceBroker API supports metadata bag of keys, so we're coming up
with our custom schema for that data to be presented.
This should be non-invasive procedure provided we're not removing GUIDs
or plans.
One potentially drastic change, is me setting the `active: false` flag
to the deprecated plans, with hope that these will no longer be
available for consumption. Tell me off.
How to review
-------------
- Sanity check
> Provide metadata to our services and plans

- tools/user_emails/.gitignore
- tools/user_emails/emails/emails.go
- tools/user_emails/emails/emails_test.go
- tools/user_emails/emails/stubs/cf.go
- tools/user_emails/main.go
- tools/user_emails/utils/status.go
What
----
Output user email details in JSON
Sometimes we want to get an output from the user emails tool which is machine easily parseable. JSON output fits that bill nicely.
Usage:
make [env] show-tenant-comms-addresses FORMAT=json
How to review
-------------
1. Code review. It's probably easiest to review it commit by commit because the last commit runs `go fmt` across the codebase.
2. Give it a go!
Who can review
--------------
Anyone
> User emails tool outputs JSON

- tools/metrics/gauges_elasticache_updates.go
- tools/metrics/gauges_elasticache_updates_test.go
What
----
In some earlier work we exposed a bunch of new metrics about Elasticache
instances and their service updates. On thoe metrics, we added space and org
guid's and names, and service instance guids .. but never service instance
names. This commit fixes that.
How to review
-------------
1. Code review
Who can review
--------------
Anyone
> [#172204530] Add `service_instance_name` label to Elasticache metrics

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
We've update the login form fields in alphagov/paas-uaa-customized-boshrelease#16
and this is to update UAA with the latest build release number
How to review
-------------
Compare the updated values with https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-customized-release/jobs/build-final-release/builds/3
> Update uaa-customized build release details

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/030-bosh-dns.yml
- manifests/cf-manifest/spec/manifest/certificates_spec.rb
What
----
1. Add 2 pipeline jobs to manage the healthcheck deployment
During debugging of this problem, the logging pipeline was broken in staging. I wanted to re-run the pipeline, but could not because the healthcheck was set to "deployed".
The healthcheck could not be ascertained to be available by the pipeline because the logging pipeline was broken.
Add a task to check the state, and set the healthcheck deployed status to false, to allow us to run the pipeline in such situations.
2. Fix BOSH DNS CA certificate rotation
If you use `((ca.certificate))` when refering to a certificate's CA cert, then you will only get the latest CA certificate interpolated in the manifest.
You must instead use `((certficate.ca))`
When you use `((certificate.ca))` and the latest CA has the "transitional" …
> Fix BOSH DNS CA certificate rotation

- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/env-specific/stg-lon.yml
- manifests/cf-manifest/operations.d/320-cc-worker-scaling.yml
- manifests/cf-manifest/spec/manifest/cc_spec.rb
What
----
The V3 API uses tasks a lot more, and we have seen our cc job queue increase in length
Adding more workers in production will ensure jobs are completed in a timely manner
How to review
-------------
Code review
CI
Who can review
--------------
Not @tlwr
> Scale CC workers in production

- manifests/cf-manifest/operations.d/320-cc-increase-max-app-disk.yml
What
----
Sets the max disk space property in both places that it's needed. Sets that value to 6gb, because we have legitimate use cases for slightly bigger max disk sizes.
How to review
-------------
1. Deploy this branch to your dev env.
2. Test you can request 6gb worth of disk, both initially and in an update
```
cd $(mktemp -d)
echo "Hi" > index.html
cf push six-gig-app -b staticfile_buildpack -k 6G
cf push two-gig-app -b staticfile_buildpack -k 2G; cf scale two-gig-app -k 6G;
cf delete -f -r six-gig-app
cf delete -f -r two-gig-app
```
This is deployed in the `andyhunt` dev env, so you could try it there [and check my pipeline](https://deployer.andyhunt.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/4). It may not be up and running when …
> Raise max app disk space to 6gb

- manifests/cf-manifest/spec/manifest/cc_spec.rb
What
----
Add two spec tests to ensure that cc worker and cc api are in sync, so they do not drift
If they drift, you can get the situation where a create is allowed, but an update is not
How to review
-------------
Code review
CI
Who can review
--------------
@AP-Hunt
> Ensure cc worker and cc api properties are in sync

- manifests/cf-manifest/operations.d/320-cc-increase-max-app-disk.yml
- manifests/cf-manifest/spec/manifest/cc_spec.rb
What
----
See https://govuk.zendesk.com/agent/tickets/4051938
CC deployment updater handles rolling updates
It is currently cancelling some deployments if the manifest requests "too much disk"
The value for too much disk is wrong, and should be the same as CC API and CC worker
How to review
-------------
Code review
Look at zendesk ticket
Who can review
--------------
Not @tlwr
> CC deployment updater should allow 6g of disk

- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/711-rds-broker-postgres95-plans.yml
What
----
Bumps the version of the RDS broker being deployed to include the changes that allow Postgres 9.5 databases to be upgraded.
Removes the `postgis` extension from the list of default extensions for Postgres 9.5 plans. This is necessary for the upgrades to work.
How to review
-------------
Deploy to your dev env and follow the tests I performed below
* Can create databases with and without extension
```
$ cf cs postgres tiny-unencrypted-9.5 without-postgis
$ cf cs postgres tiny-unencrypted-9.5 with-postgis -c '{"enable_extensions": ["postgis"]}'
```
*   Can’t go straight to 11 
```
 $ cf update-service without-postgis -p tiny-unencrypted-11
Updating service instance without-postgis as andy.hunt@digital.cabinet-office.gov.uk...
FAILED
Server error, status code: 502, error code: …
```
> [#172528011] Enable Postgres 9.5 upgrades

- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/check-certificates.rb
[Story](https://www.pivotaltracker.com/story/show/172599318)
What
----
1. Make the `check-certificates` Concourse job use `openssl verify` to check for chain validity
2. Run the `check-certificates` job after the `rotate-certificates`
Why
----
We recently [had an incident](https://status.cloud.service.gov.uk/incidents/92gmvk51zw19) because our certificates were generated in an invalid state.
Our pipeline rotates certificates close to the end, so that new certificates will be deployed on the next run.
After we regenerate the certificates, we should check that they have been generated correctly. This new job happens before the pipeline is unlocked, so any improper certificates will ensure an operator has to intervene before a new pipeline run can happen, thereby preventing invalid …
> [#172599318] Check certs in pipeline

- terraform/cloudfoundry/shield_and_waf.tf
What
----
We didn't have a lifecycle on shield resources with would cause a failed
delete run to not be able to complete the teraform destroy.
How to review
-------------
code review
destroy your CF if you wish and check that it works
Who can review
--------------
Anyone
> Add lifecycle to Shield resources

- manifests/cf-manifest/operations.d/009-add-disabled-syslog-agent-for-upgrade-UPSTREAM.yml
What
----
Adds the `add-disabled-syslog-agent-for-upgrade.yml` ops file so we can avoid logs on app syslog drains being duplicated or dropped for much of the duration of the deploy when upgrading CF to >= 13.0.0
How to review
-------------
Deploy to your dev env
Who can review
--------------
Not me
> [#172697662] Add syslog agent in preparation for CF 13 upgrade

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/scripts/ca-rotation-move-transitional.rb
- concourse/scripts/ca-rotation-remove-transitional.rb
- concourse/scripts/ca-rotation-set-transitional.rb
- concourse/scripts/check-certificate-hierarchy.rb
- concourse/scripts/check-certificates.rb
- concourse/scripts/lib/credhub.rb
- concourse/scripts/lib/formatting.rb
- concourse/scripts/pipelines-cloudfoundry.sh
- platform-tests/src/platform/availability/helpers/concourse.go
[Story](https://www.pivotaltracker.com/story/show/172480682)
Summary
----
1. Parameterise availability tests, so they can be re-used
1. Implement a concept of test pipelines, for use in development
1. Create a test pipeline to automate the testing of our certificate rotation process
1. Colourise and reformat the output of certificate rotation scripts, and add action summaries
1. Add more error handling to certificate rotation scripts
1. Add a test to ensure that our certificate hierarchy has a depth of two
1. Fix bug where leaf certificate were regenerated twice
1. Fix bug where certificate rotation ordering depended on string value of expiry date
1. Rotate certificates in development very often
1. Rotate certificates in staging more often
Testing the critical path
-------------
Ensure …
> [#172480682] Rotate certs often dev

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Lets Encrypt's ACMEv1 API is going down on Monday 1st June for 24h. This will break the
CDN broker. The API will return on Tuesday 2nd June. To prevent our tenants failing
to provision a CDN route service during the outage, we're patching the CDN broker to
prevent it, and informing tenants via Status Page.
We deploy a development release of the broker, based on [the PR which patches out the actions](https://github.com/alphagov/paas-cdn-broker/pull/38), so that we can easily roll it back by reverting just this commit.
How to review
-------------
1. See if you agree with this approach
Who can review
--------------
Anyone
> Deploy a development release of the CDN broker which has its actions disabled

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
🚨 **DO NOT MERGE UNTIL 2020-06-01 1630** 🚨 
What
----
This reverts commit 202c479501cedd37dc7fd5477c88aef2a5ac9bcd, which disabled the CDN brokers actions during the maintenance window.
How to review
-------------
1. Doesn't really need one
Who can review
--------------
Anyone
> [DO NOT MERGE UNTIL 2020-06-01 1630] Reenable CDN broker actions

- manifests/cf-manifest/operations.d/350-networking.yml
What
----
The releases are built with Go 1.14 and also include a fix for https://github.com/cloudfoundry/cf-networking-release/issues/76
Which will fix the long-standing issue that @uktrade have with unreliability during cell rolling
How to review
-------------
Run this down your development environment
Read the release notes
- [silk](https://github.com/cloudfoundry/silk-release/releases/tag/2.30.0)
- [cf-networking](https://github.com/cloudfoundry/cf-networking-release/releases/tag/2.30.0)
Who can review
--------------
Not @tlwr
> Update silk and cf-networking to 2.30

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
In the previous broker behaviour instances that were in
`storage-optimization` remained in `InProgress` which prevented
applications from being bound to the instance.
However according to AWS support
```
While the instance is in the 'storage-optimization' state,
- The instance is fully operational.
- You cannot make any 'storage' related modifications but other modifications are allowed.
```
So we should enable tenants to bind applications whilst this background
operation is happening.
How to review
-------------
Code review against https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker-release/jobs/build-final-release/builds/5
Who can review
--------------
Anyone
> [support] Allow apps to be bound when in `storage-optimization` state

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Deploy a version of the CDN broker that uses ACM instead of Let's Encrypt.
See [the `paas-cdn-broker` pull request](github.com/alphagov/paas-cdn-broker/pull/36) for full details
How to review
-------------
1. *Before deploying this branch* create two cdn-routes, so that you have some to test the migration path with
1. Deploy this branch
1. Run the manual tests outlined in [the `paas-cdn-broker` pull request](github.com/alphagov/paas-cdn-broker/pull/36)
Who can review
--------------
Anyone
> [#172180437] Use ACM not Lets Encrypt in CDN broker

- config/service-brokers/aiven/config.json
- config/spec/service_broker_spec.rb
- platform-tests/src/platform/broker-acceptance/common_service_test.go
- scripts/uaa_lock_user_test.go
[Story](https://www.pivotaltracker.com/story/show/173220465)
What
----
The services that we provide as part of our platform are not shareable by default.
As service broker authors we have to implicitly opt-in for the broker to create 'shareable' service instances. To do that, we have to change the metadata of the service broker catalog definitions to make it a shareable service.
This PR will make two first services - `elasticsearch` & `influxdb` to become shareable.
How to review
-------------
1. Code review
2. Deploy this branch to your dev env.
3. Make sure that `custom-broker-acceptance-test` job in `create-cloudfoundry` pipeline is passing.
4. [Optional Step] After you deployed this branch to your dev env - you can create an instance of `elasticsearch` or `influxdb` service. Then run …
> [#173220465] Make services in aiven broker 'shareable'

- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/spec/manifest/elasticache_broker_spec.rb
- platform-tests/src/platform/broker-acceptance/common_service_test.go
[Story](https://www.pivotaltracker.com/story/show/173220478)
What
----
The services that we provide as part of our platform are not shareable by default.
As service broker authors we have to implicitly opt-in for the broker to create 'shareable' service instances. To do that, we have to change the metadata of the service broker catalog definitions to make it a shareable service.
This PR will make the redis (based on Amazon ElastiCache) service to become shareable.
How to review
-------------
1. Code review
2. Deploy this branch to your dev environment
3. Make sure that `custom-broker-acceptance-test` job in `create-cloudfoundry` pipeline is passing.
4. [Optional Step] After you deployed this branch to your dev env - you can create an instance of redis service. Then run cf service …
> [#173220478] Making Elasticache service shareable

- manifests/cf-manifest/operations.d/711-rds-broker-postgres95-plans.yml
- manifests/cf-manifest/operations.d/712-rds-broker-mysql57-plans.yml
- manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
- platform-tests/src/platform/broker-acceptance/common_service_test.go
[Story](https://www.pivotaltracker.com/story/show/173220501)
What
----
The services that we provide as part of our platform are not shareable by default.
As service broker authors we have to implicitly opt-in for the broker to create 'shareable' service instances. To do that, we have to change the metadata of the service broker catalog definitions to make it a shareable service.
This PR will make the `postgres` & `mysql` (based on Amazon Relational Database Service) services to become shareable.
How to review
-------------
1. Code review
2. Deploy this branch to your dev environment
3. Make sure that custom-broker-acceptance-test job in create-cloudfoundry pipeline is passing.
4. Issue `cf curl /v3/service_offerings?names=mysql,postgres | jq '.resources[] | [.name , …
> [#173220501] Shareable rds broker

- manifests/cf-manifest/operations.d/750-s3-broker.yml
- manifests/cf-manifest/spec/manifest/s3_broker_spec.rb
- platform-tests/src/platform/broker-acceptance/common_service_test.go
[Story](https://www.pivotaltracker.com/story/show/173220546)
What
----
The services that we provide as part of our platform are not shareable by default.
As service broker authors we have to implicitly opt-in for the broker to create 'shareable' service instances. To do that, we have to change the metadata of the service broker catalog definitions to make it a shareable service.
This PR will make the `aws-s3-bucket` (based on Amazon Simple Storage Service) service to become shareable.
How to review
-------------
1. Code review
2. Deploy this branch to your dev environment
3. Make sure that custom-broker-acceptance-test job in create-cloudfoundry pipeline is passing.
4. Issue `cf curl /v3/service_offerings?names=aws-s3-bucket | jq '.resources[] | [.name , …
> [#173220546] Making AWS S3 service shareable

- manifests/cf-manifest/operations.d/200-paas-admin-uaa-client.yml
[Story](https://www.pivotaltracker.com/story/show/170700038)
What
----
We'd like to moce the forgotten password functionality from UAA to
Pazmin, to gain more control of what's happening and how it's being
presented to our beloved users.
The Password Reset API call requires either: `uaa.admin`, `oauth.login`
or `zones.uaa.admin` scope to perform it's action.
Now that we've moved that functionality into Pazmin, we need to make
sure our login page points to it.
We'll be sending new email from pazmin to our beloved tenants. We need
to point to the template in notify, which should be used for that action
to be performed.
How to review
-------------
- Deploy to your dev environment
- Review alphagov/paas-admin#893
⚠️ This needs to be merged after the alphagov/paas-admin#893 ⚠️ …
> [#170700038] Allow pazmin password resets

- concourse/pipelines/create-cloudfoundry.yml
What
----
In concourse 6.3 the bundled pool resource was updated to 1.1.2 which is
broken for our use-case (unintentionally)
See:
https://github.com/concourse/pool-resource/issues/54
https://github.com/concourse/pool-resource/issues/55
Pin to 1.1.1 fixes the issue
How to review
-------------
Code review
See https://deployer.london.staging.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/pipeline-release-lock/builds/8 is green
Who can review
--------------
@LeePorte
> Pin pool resource to 1.1.1

- tools/metrics/gauges_tls.go
- tools/metrics/gauges_tls_test.go
- tools/metrics/main.go
- tools/metrics/pkg/tlscheck/fakes/fake_cert_checker.go
- tools/metrics/pkg/tlscheck/tls.go
- tools/metrics/pkg/tlscheck/tls_test.go
What
----
We've asked our tenants to perform a `cf update-service` call to migrate their
CDN route services between certificate authorities. By exposing a metric for
the number of CloudFront instances presenting certificates signed by different
authorities, we can track how many tenants have performed the migration.
How to review
-------------
1. Code review
Unless you have an old CDN route service in your dev env, you won't be able to test that it counts >1 certificate authority. The unit tests should test that.
Who can review
--------------
Anyone
> Expose metric for the number of CDN route TLS certs issued by different certificate authorities

- tools/metrics/gauges_tls.go
- tools/metrics/pkg/tlscheck/tls.go
What
----
When an expired/invalid certificate was encountered, a nil pointer error was
encountered, and the program crashed. The fix is to return an error when the
certificate is invalid.
How to review
-------------
1. Code review
Who can review
--------------
Anyone
> Fix bug in paas-metrics CDNTLSCertificateAuthorityGauge

- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/env-specific/stg-lon.yml
- manifests/cf-manifest/operations.d/380-scale-scheduler.yml
- manifests/cf-manifest/spec/manifest/scheduler_spec.rb
- manifests/shared/spec/support/shared_examples.rb
What
----
We want to support more DNS requests per second served by service-discovery-controller
We want to have more instances, so that when we deploy we do not have a single instance of scheduler
Context
----
Yesterday one of our users (GOV.UK Notify) experienced an outage pertaining to internal DNS
The DNS request path is like this
During the incident we experienced a high rate of DNS failures
During the incident the number of DNS requests went up by roughly 4x (this is important)
We can observe that these are DNS requests to service-discovery-controller (that's what backs the DNS requests made by bosh-dns-adapter). We can observe that there was a spike in requests
We can correlate this to the number of concurrent socket allocations on the scheduler instances
We can correlate this to …
> cf: horizontally scale scheduler VM

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Deploys a version of the CDN broker with the fix from https://github.com/alphagov/paas-cdn-broker/pull/40
How to review
-------------
1. Deploy and test that updating CDN route still works
Who can review
--------------
Anyone
> Deploy CDN broker 0.1.36

- concourse/pipelines/create-cloudfoundry.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/tag-repo.yml
What
----
In https://github.com/alphagov/paas-cf/pull/1968 we got paas-admin continuously deployed. This has been working well and reduced toil / increased speed at which we can do changes
So that we can iterate on paas-billing faster, we should continuously deploy it. We didn't do this at the same time as paas-admin because we didn't have acceptance tests and altering, now we do.
Soon we are going to kick off some work on dynamic billing, so being able to make changes faster will be good
This PR:
* moves the paas-admin `tag-app-repo` task into a task file, and makes it more generic
* re-uses the task for paas-billing
* adds a task for generating git keys, this is only really used in stg-lon
* uses credhub for app repo git keys instead of s3
How to review
-------------
Code review, commit …
> Continuously deploy paas-billing

- Makefile
- config/logit/20_custom_cf_filters.conf
- config/logit/output/generated_logit_filters.conf
- scripts/generate_logit_filters.sh
What
----
Update to latest version of logsearch-for-cloudfoundry and logsearch-boshrelease which supports cf-deployment v12.27
Add logstash config to index `vcap_request_id` correctly in `cloud_controller_ng`/`vcap_nginx_access`
Do not delete `syslog_sd_params` from logs
How to review
-------------
I have updated the logstash config in the development logit instance, so our dev envs use this config
Review [a kibana visualisation showing grokparsefailures](https://kibana.logit.io/s/c7358874-2b30-44a6-8271-554ad3996e50/goto/a1ede4876bdd5dedabe3f28222b0d1d2) check that the `vcap_nginx_access` grokparsefailures have been eliminated
Review [a RTR log from paas-admin](https://kibana.logit.io/s/c7358874-2b30-44a6-8271-554ad3996e50/app/kibana#/doc/logstash-*/logstash-2020.07.01/logs?id=AXMLTrqVj_R …
> Update logstash filters

- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/env-specific/stg-lon.yml
- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/cf-manifest/operations/change-vm-types-dev.yml
- manifests/cf-manifest/spec/manifest/dev_scaling_spec.rb
- manifests/cf-manifest/spec/manifest/prometheus_spec.rb
- manifests/cloud-config/paas-cf-cloud-config.yml
What
----
We have 370d retention on the metrics for our users
We are reaching 85% prometheus disk capacity, we should increase max capacity
Ireland does not need more disk, just London, so make it specific to London
How to review
-------------
[Check grafana](https://grafana-1.london.cloud.service.gov.uk/explore?left=%5B%22now-6h%22,%22now%22,%22prometheus%22,%7B%22expr%22:%22bosh_job_persistent_disk_percent%7Bbosh_job_name%3D%5C%22prometheus%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
CI
Who can review
--------------
Not @tlwr
> cf: prometheus in london has big disk

- manifests/cf-manifest/operations.d/320-cc-release.yml
[Story](https://www.pivotaltracker.com/story/show/173659071)
What
----
updating CAPI to 1.96 release to get the fix for the bug when CC issues an orphaned mitigation on service instances with failed updates resulting in the removal of the service instance.
The original issue in the upstream is [here](https://github.com/cloudfoundry/cloud_controller_ng/issues/1690)
Detailed release notes for CAPI 1.96 is [here](https://github.com/cloudfoundry/capi-release/releases/tag/1.96.0)
How to review
-------------
Code review.
[Optional] Apply this fix to your DEV environment. 
*Assumptions - you have control of the domain (E.g.: example.com) and can add CNAME records.*
Steps to verify that failed update to service instance is not triggering removal of the service instance :
- create a first cdn …
> upgrading CAPI to 1.96 to fix a bug.

- manifests/cf-manifest/operations.d/350-networking.yml
[Story](https://www.pivotaltracker.com/story/show/173684528)
Signed-off-by: Toby Lorne <toby.lornewelch-richards@digital.cabinet-office.gov.uk>
What
----
`silk` and `cf-networking` are released together
`cf-networking` 2.31 contains:
* https://github.com/cloudfoundry/cf-networking-release/pull/80
* https://github.com/cloudfoundry/cf-networking-release/pull/81
which were raised from our recent Ireland DNS outage
and
* https://github.com/cloudfoundry/cf-networking-release/issues/78
which has caused one (1) support ticket in the past
How to review
-------------
Read the [story](https://www.pivotaltracker.com/story/show/173684528)
Read the [release notes](https://github.com/cloudfoundry/cf-networking-release/releases/tag/2.31.0)
Deploy to your development environment
Who can review …
> [#173684528] cf: cf-networking and silk to 2.31

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/scripts/upload-buildpack.sh
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- platform-tests/example-apps/create-account-holding-page/manifest.yml
- platform-tests/example-apps/healthcheck/manifest.yml
- platform-tests/example-apps/http_tester/manifest.yml
- platform-tests/example-apps/logging-pipeline/manifest.yml
What
----
In https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/193 we started to use the generally available version of the CF CLI in our `cf-cli` docker image
This enables us to use `cf push --strategy=rolling` instead of using the blue-green plugin or autopilot plugin, and enables us to avoid the legacy `buildpack` parameter (instead of `buildpacks`) in our manifests
How to review
-------------
CI
Deploy to your development environment
Run all the deploy jobs:
Who can review
--------------
Not @tlwr
> Use CF CLI v7

- concourse/pipelines/create-cloudfoundry.yml
- platform-tests/example-apps/healthcheck-pinger/main.go
- platform-tests/example-apps/healthcheck-pinger/manifest.yml
- platform-tests/example-apps/healthcheck-ponger/main.go
- platform-tests/example-apps/healthcheck-ponger/manifest.yml
[Story](https://www.pivotaltracker.com/story/show/173692258)
What
----
We are going to availability test internal networking during our pipeline
To do this we need some apps which use internal networking and internal DNS
This PR adds two new example apps:
- healthcheck-pinger
- healthcheck-ponger
The ponger app always returns 200 OK
The pinger app returns 200 OK if the ponger app returns 200 OK, otherwise 503
This PR deploys the two apps as part of the deploy-healthcheck step
In a later PR we will actually availability test them
How to review
-------------
Deploy to your development environment
(⚠️  this requires https://github.com/alphagov/paas-cf/pull/2371 because of how `cf add-network-policy` works ⚠️ )
`curl https://healthcheck-pinger.$env.london.cloudpipelineapps.digital` should …
> [#173692258] Add pinger and ponger health check apps

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/cf-manifest/spec/manifest/prometheus_spec.rb
What
----
Miki was looking into this for a tenant broker story
relabel_configs only applies to dropping targets, we want to drop metrics instead
fix the test and the dropping to actually drop the metrics
How to review
-------------
Code review
Check [tlwr pipeline is green](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/prometheus-deploy/builds/139)
Review timeseries showing number of metrics, before and after relabelling changes:
Who can review
--------------
@46bit
> prometheus: actually drop the metrics properly

- manifests/cf-manifest/operations.d/310-router.yml
What
----
CVE-2020-15586 [1] is mitigated by using a release >= 0.203.0
[1] https://www.cloudfoundry.org/blog/cve-2020-15586/
How to review
-------------
Run the branch down your pipeline
Who can review
--------------
Anyone
> Use v0.203.0 of routing-release

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cloud-config/operations/use-spot-instances-in-dev.yml
- manifests/cloud-config/scripts/generate-cloud-config.sh
- manifests/cloud-config/spec/support/cloud_config_helpers.rb
- manifests/cloud-config/spec/vm_types_spec.rb
- manifests/variables.yml
What
----
⚠️  https://github.com/alphagov/paas-bootstrap/pull/376 must be deployed first ⚠️ 
Use spot instances in development environments, to save money
This doesn't affect BOSH Director or Concourse deployments
_EC2 costs in my development environment_
How to review
-------------
Deploy to your development environment
Do a `bosh recreate` just for fun
Code review, ensure spot is not used for prod (double check tests)
Look at the spot bid pricing history, and EC2 pricing tables, to check that we are not overpaying, or underpaying
Who can review
--------------
Not @tlwr
> cf: use spot instances for dev environments

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- scripts/upload-secrets/upload-zendesk-secrets.rb
What
----
We'd be using the ZenDesk integration in our PaaS Admin application to
have a better and accessible support form for our tenants.
How to review
-------------
- `make dev upload-zendesk-secrets`
- run `create-cloudfoundry` pipeline
- expect appropriate secrets set for PaaS Admin (zendesk ones)
> Setup secrets upload for ZenDesk

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
In response to some recent CVEs, we're upgrading the versions of cflinuxfs3 and ubuntu-xenial to meet with the suggested mitigations.
This PR does not include cf-deployment bump - also recommended in the write up.
How to review
-------------
> Bump cflinuxfs3 and xenial versions

- concourse/pipelines/create-cloudfoundry.yml
What
----
Upgrading cflinuxfs3 and stemcells have caused the acceptance tests to fail because nodejs buildpack in the acceptance tests is old
this is fixed in the cf cli v7 acceptance tests which we can switch to once we play the upgrade cf deployment story
How to review
-------------
https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/acceptance-tests/builds/125 is green
We can try this out in staging which is currently red
This is mentioned in https://www.pivotaltracker.com/n/projects/1275640/stories/173660576
Who can review
--------------
Not @tlwr
> concourse: use cf-acceptance-tests with newer node

- config/billing/config-parts/elasticsearch_pricing_plans.json.erb
- config/billing/pricing_data.yml
- config/service-brokers/aiven/config.json
What
----
This adds an `elasticsearch xlarge-ha-6.x` plan mapping onto Aiven's Business-32 offering.
A tenant is reporting performance issues with one of their clusters and Aiven are suggesting that the cluster might actually hit a performance limit due to sharding.
How to review
-------------
- Code review
- (Check if this change is indeed sufficient to add the new plan/ that I have not overlooked sth)
Who can review
--------------
not @schmie
> Add xlarge elasticsearch 6 plan

- manifests/prometheus/dashboards.d/component-indicators.json
[Story](https://www.pivotaltracker.com/story/show/173656955)
What
----
Creates a component indicators dashboard
This has some problems:
- the firehose exporter is not great for counters for the syslog agents - hence the odd numbers
- the metrics obtained directly from the components via their prometheus endpoints provides richer metrics - follow up story to use those instead
How to review
-------------
Deploy to your env and look at the `Component Indicators - ((deploy_env))` dashboard
Who can review
--------------
Not @tlwr
> [#173656955] Add component indicators dashboard

- config/service-brokers/aiven/config.json
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations.d/711-rds-broker-postgres95-plans.yml
- manifests/cf-manifest/operations.d/712-rds-broker-mysql57-plans.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/operations.d/750-s3-broker.yml
- manifests/cf-manifest/spec/manifest/base_properties_spec.rb
What
----
[We've moved support forms into paas-admin](https://github.com/alphagov/paas-admin/pull/936), so urls need to be updated
How to review
-------------
- check urls take you to the correct page
Who can review
--------------
not @kr8n3r
> Update links to support & signup forms

- concourse/pipelines/create-cloudfoundry.yml
What
----
We silenced Shellcheck rule SC2039 because it alerts on us using features that
aren't defined in the POSIX spec, but we still wanted to use those features.
But we were still using the `sh` shell to run the task, so the behaviour was
still undefined, and it still didn't work. Using `bash` ought to fix that.
How to review
-------------
Code review
Who can review
--------------
Anyone
> Use `bash` instead of `sh` in `register-csls-splunk-broker` task

- concourse/pipelines/create-cloudfoundry.yml
What
----
We configure many of our apps to use HTTP healthchecks. There is a change in how this has to be configured which only became apparent when deploying a new PaaS dev environment.
In CF CLI v6, we specify `health-check-type: http` in the app manifest and CF will automatically health check the `/` route.
In CF CLI v7, the endpoint to be used for HTTP healthchecks now has to be specified (there is no default.)
This only became apparent when Miki deployed a new environment because in all existing environments CF has probably stored the default endpoint value from when we still used CF CLI v6.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit.
> Fix HTTP healthcheck in CF CLI v7 manifests

- terraform/prod.vpc_peering.json
- terraform/scripts/generate_vpc_peering_test.go
What:
Update to the VPC subnet configured for GOV.UK Development peering.
Why:
"subnet_cidr" represents client subnet as per: step 1&2 of PaaS guide at https://team-manual.cloud.service.gov.uk/guides/vpc_peering/#content
> Update VPC peering for govuk_development

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
We are not prescribing the patch level in the RDS service catalog plans in order to make use of the auto minor version upgrade feature.
This means that AWS chooses the patch level when creating or modifying an instance. If the patch-level chosen for the modification is for some reason lower than the patch-level of the current instance cf update-service will fail.
This change preserves the patch-level of the current instance when updating the plan, if the major and minor versions are the same. It also adds tests.
See https://github.com/alphagov/paas-rds-broker/pull/118 for further info
How to review
-------------
Code review
Who can review
--------------
Me
> [#173938510]  Keep patch level when modifying similar engine versions

- concourse/pipelines/create-cloudfoundry.yml
- config/logit/20_custom_cf_filters.conf
- config/logit/output/generated_logit_filters.conf
- manifests/runtime-config/operations.d/100-syslog-forwarder.yml
- manifests/runtime-config/scripts/generate-runtime-config.sh
- manifests/runtime-config/spec/support/runtime_config_helpers.rb
- manifests/runtime-config/spec/syslog_forwarder_spec.rb
What
----
We currently do not populate the `syslog.director` bosh property, which defaults to the empty string, and in logstash we drop it.
This PR:
- populates `syslog.director`
- does not drop it in logstash
so we now can run the following queries:
- `@source.director:"prod" AND @source.deployment:prometheus`
- `@source.director:"prod-lon" AND @source.deployment:prometheus`
to differentiate between the two different Prometheus deployments in production
How to review
-------------
Code review
Check [Kibana in dev](https://kibana.logit.io/s/c7358874-2b30-44a6-8271-554ad3996e50/app/kibana#/visualize/create?type=pie&indexPattern=logstash-*&_g=()&_a=(filters:!(),linked:!f,query:(query_string:(analyze_wildcard:!t,query:'@source.director:tlwr')),uiState:(),vis:(aggs:!((enabled:!t,id:'1',params: …
> runtime-config: syslog forwarder has director name

- manifests/prometheus/alerts.d/bosh-director-disk.yml
- manifests/prometheus/spec/bosh-director-disk.test.yml
What
----
We saw our bosh director disk fill up, we should have an alert that predicts when it will fill
How to review
-------------
Code review
[Check the curve](https://grafana-1.tlwr.dev.cloudpipeline.digital/explore?left=%5B%22now-6h%22,%22now%22,%22prometheus%22,%7B%22expr%22:%22predict_linear(node_filesystem_avail_bytes%7Binstance%3D%5C%2210.0.0.6:9100%5C%22,%20mountpoint%3D%5C%22%2Fvar%2Fvcap%2Fstore%5C%22%7D%5B1h%5D,%203%20*%2024%20*%2060%20*%2060)%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
Who can review
--------------
Not @tlwr
> prometheus: alert when bosh director disk filling

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/310-router.yml
What
----
CVE-2020-5416 [1] is mitigated using a release >= 0.204.0
[1] https://www.cloudfoundry.org/blog/cve-2020-5416/
How to review
-------------
Test branch in dev
Who can review
--------------
Anyone
> Use v0.205.0 of routing-release

- concourse/scripts/pipelines-cloudfoundry.sh
What
----
Support both terraform state files version 3 and 4 in the `self-update-pipelines` task in `pipeline-lock`.
The data structure of terraform state files has changed with version 4 / terraform 0.12. This occurrence was overlooked in the 0.12 upgrade.
How to review
-------------
Code review
Check branch in dev ([works in `schmie`](https://deployer.schmie.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/pipeline-lock/builds/14))
Who can review
--------------
Not @schmie
> Fix tfstate file parsing for self-update-pipelines

- concourse/pipelines/create-cloudfoundry.yml
What
----
During a rebase, `external_credhub_database_password` was [added to our secrets generation script erroneously](https://github.com/alphagov/paas-cf/commit/2c4bf4f15ee450eebe01e3944e84263b4b958ec4)
Additionally we need to add `external_app_autoscaler_database_password` to concourse secrets generation
How to review
-------------
Code review
Who can review
--------------
@LeePorte
> App autoscaler pipeline

- concourse/pipelines/destroy-cloudfoundry.yml
What
----
The structure of tfvars files has changed with the upgrade to terraform
0.12. This change reflects this in the cf-terraform-destroy task.
How to review
-------------
Code review
Check that the task `cf-terraform-destroy` does not fail in dev (optional, I think - tested in `schmie`)
Who can review
--------------
Not @schmie
> Add cloudfoundry/((aws_account)).tfvars in destroy

- manifests/cf-manifest/operations.d/320-cc-release.yml
What
----
[Ticket](https://govuk.zendesk.com/agent/tickets/4193788)
[Addresses](https://www.cloudfoundry.org/blog/cve-2020-5417/)
How to review
-------------
Code review
[Version](https://api.tlwr.dev.cloudpipeline.digital/)
[Release notes](https://github.com/cloudfoundry/capi-release/releases/tag/1.97.0)
Who can review
--------------
Not @tlwr
> cf: bump capi to 1.97

- concourse/pipelines/create-cloudfoundry.yml
What
----
Use upload-runtime-config instead of upload-config in cf-deploy.
The latter does not upload releases configured in the runtime config
(See [discussion on this GitHub issue](https://github.com/cloudfoundry/bosh/issues/2209)).
How to review
-------------
- Code review
- To test in dev (requires destroyed cloudfoundry) - or [see it working in my dev env](https://deployer.schmie.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/6)
- `BOSH (your_dev) $ bosh delete-release syslog`
- Run create-cloudfoundry and see the release uploaded in `update-paas-cf-runtime-config` / `cf-deploy` not failing with `Error: Release 'syslog' doesn't exist`
Who can review
--------------
Not @schmie
> Use upload-runtime-config in cf-deploy

- manifests/prometheus/alerts.d/bosh-stemcells-not-in-sync.yml
What
----
We have an alert that warns us if we are running multiple Stemcells (OS base images.) This alert was hardcoded to expect 3 BOSH Deployments.
We recently deployed the CF Autoscaler using BOSH. It is a separate BOSH deployment, our fourth. When that was deployed the "multiple stemcell" alert went off.
This commit edits that alert so that it directly counts the number of stemcells in use, rather than being hacky. Credit to @tlwr.
How to review
-------------
Code review :)
Who can review
--------------
Not @46bit.
> Fix the stemcells not in sync alert

- manifests/app-autoscaler/operations.d/300-set-plans.yml
- manifests/app-autoscaler/spec/autoscaler_spec.rb
What
----
Autoscaler plans should be guids
@46bit found that the default guids in the app autoscaler catalog are not guids, and this is causing paas-billing to have a sad time:
```
"error":"/home/vcap/app/eventstore/sql/create_events.sql: invalid input syntax for uuid: \"autoscaler-free-plan-id\""
```
This PR:
- tests that the app-autoscaler catalog uses UUIDs
- makes the app-autoscaler catalog use UUIDs
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Autoscaler plans

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/prometheus/alerts.d/app-autoscaler-is-not-scaling.yml
- manifests/prometheus/spec/alerts/app-autoscaler-cpu.test.yml
- platform-tests/example-apps/app-autoscaler-cpu-usage/manifest.yml
What
----
Make explicit the stemcells used by the autoscaler instances, in the same way as the `prometheus` deployment
Relax the autoscaler alert canary from 30m to 1h to avoid instances where:
- the cf_exporter is scraped every 4 mins
- the app autoscales up and down within that time period
- the metric for number of instances does not change
(a proper fix is to scrape the autoscaler directly)
How to review
-------------
Check that [these changes will not make the alert more noisy](https://grafana-1.london.cloud.service.gov.uk/explore?left=%5B%22now-6h%22,%22now%22,%22prometheus%22,%7B%22expr%22:%22avg%20(cf_application_instances%7Bapplication_name%3D%5C%22app-autoscaler-cpu-usage%5C%22%7D)%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
CI
Who can review
--------------
Not …
> Autoscaler tweaks

- terraform/prod.vpc_peering.json
What
----
This change adds GOV.UK Pay's staging account to the list of peered VPCs in the PaaS Ireland region. A subnet CIDR of `172.16.36.0/22` has been selected following the guidance in the PaaS team manual.
This will be used to test connectivity between PaaS applications and  RDS instances managed by GOV.UK Pay in a separate account.
Who can review
--------------
Anyone on the PaaS team responsible for infrastructure.
> Add peered VPC for GOV.UK Pay staging environment to PaaS Ireland

- platform-tests/aiven-broker-acceptance/elasticsearch_service_test.go
What
----
We need to unblock the pipeline so we can release new changes
Aiven have EOLd 6.x ES, so this test is failing
Skip it, so that when we add ES 7.x we can unskip it using 7.x
How to review
-------------
Code review
Who can review
--------------
@LeePorte
> tests: skip elasticsearch provisioning test

- platform-tests/broker-acceptance/common_service_test.go
What
----
In 52b98b9 we've added a test to find any non-unique IDs to prevent some
issues in billing.
This test, is also validating weather the GUID is an actual GUID. This
sadly is not true, for any of our stubs and tests that create a GUID in
a form of: `CATS-2-SVC-PLAN-c73c869d65f9762e`.
To prevent the pipeline from erroring out, we can skip the GUID if it
starts with `CATS-`.
How to review
-------------
- Sanity check (https://play.golang.com/p/S2DHlFBdZpr)
> Ignore CATS GUIDs in tests

- manifests/prometheus/alerts.d/paas-billing-costs.yml
What
----
This improves our alerts for problems with billing and recharging:
1. Adds a `PaaSBillingIsNotIncreasing` alert that will warn us if `paas-billing`'s totals have stopped increasing. This would have alerted us to #2428 much earlier
2. Fixes the alert message of the existing AWS recharge alerts. They have been converting a percentage to currency and misrepresenting a 50% recharge rate as us recharging all but 50p. 🤦🏻‍♀️
3. Reduces the expected RDS recharge rate to 50%, as this is in line with what I see in Grafana.
It may be that (3) needs further investigating and there are more costs to recoup, but right now all that is happening is the RDS recharge alert is going off constantly and isn't actionable.
How to review
-------------
See what you think 🤷 
Who can review
-------------- …
> Better alerts for billing that don't misrepresent how well we recharge

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/runtime-config/operations.d/510-add-prometheus-blackbox-exporter.yml
- manifests/runtime-config/scripts/generate-runtime-config.sh
- manifests/runtime-config/spec/support/runtime_config_helpers.rb
What
----
We use bosh dns in multiple deployments
We should canary dns in all those deployments
So we should deploy the blackbox exporter in all deployments using a runtime config addon
How to review
-------------
Code review
Check `count(ALERTS{alertstate="firing", alertname="PrometheusScrapeError"})` in your environment before and after the deployment
Who can review
--------------
Not @tlwr
> bosh: blackbox exporter is a runtime config addon

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/test-certificate-rotation.yml
What
----
We are using the BOSH resurrector to automatically restart/recreate VMs that need recreating. During deployment there is a lock in place which prevents this from occurring.
If a VM is not available during a deployment, then the deployment is stopped prematurely, with the following resolutions available:
1. An operator deletes the VM using the BOSH CLI
1. An operator deletes the VM using the AWS Console
1. An operator `fly hijack`s the Concourse job and reruns `bosh deploy` with `--fix`
1. An operator `make bosh-cli`s from `paas-bootstrap` and runs `bosh recreate` or `bosh cck`
There is no automatic resolution, and each approach has its own pros/cons, although some cons are not immediately obvious. For example running `bosh recreate --fix instance/guid` could rollback versions of …
> Use --fix when running bosh deploy

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
- terraform/cloudfoundry/acm.tf
- terraform/cloudfoundry/lbs.tf
- terraform/cloudfoundry/outputs.tf
- terraform/cloudfoundry/paas-prometheus-endpoints.tf
What
----
This deploys the Redis prometheus endpoint from https://github.com/alphagov/paas-prometheus-endpoints. A tenant can scrape metrics about Redis services by targeting a Prometheus at `https://redis.metrics.${SYSTEM_DNS_ZONE_NAME}/metrics`. They get Prometheus to do basic auth with a PaaS username/password for a user with "Space Auditor" privileges.
How to review
-------------
Who can review
--------------
Not @46bit.
> [#171281178] Ship Prometheus endpoint for Redis

- manifests/cf-manifest/operations.d/760-sqs-broker.yml
- platform-tests/example-apps/healthcheck/sqs.go
* Updates sqs-broker to v0.1.5 which includes changes to how binding credentials for queue access are stored/fetched to use secrets manager instead of cloudformation outputs.
* Updates binding credentials to be `snake_case` not `CamelCase` for consistancy with other brokers (required updating broker acceptance test in this PR to match)
See: https://github.com/alphagov/paas-sqs-broker/pull/7
:warning: this change requires a policy change for the broker's IAM role.
* I ~~am just running~~ have run this [through the `autom8` dev env now](https://deployer.autom8.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-broker-acceptance-tests/builds/31)
* Ensure that the account-wide policy changes are merged and applied to all environments.
* You may wish to check the …
> sqs: bump broker to v0.1.5

- platform-tests/broker-acceptance/sqs_broker_test.go
What
----
`-d` for domain is deprecated and not supported in cf cli v7 and also unnecessary
How to review
-------------
Code review
Read [error message](https://deployer.london.staging.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-broker-acceptance-tests/builds/252)
Who can review
--------------
Not @tlwr
> tests: sqs tests do not use deprecated flag

- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/env-specific/stg-lon.yml
- manifests/cf-manifest/operations.d/300-nats.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations.d/350-diego-api.yml
- manifests/cf-manifest/spec/manifest/ha_spec.rb
What
----
I'm being sneaky and labelling this BAU PR as [#173621061](https://www.pivotaltracker.com/story/show/173621061)
I noticed during a fit of paranoia that we only had two NATS instances in production, which was especially ~terrifying~ exciting when we moved from using `nats` to `nats-tls` in the recent CF upgrade. All's well that ends well because we didn't see any measured downtime (and it was only for `metrics-discovery-registrar`)
This PR adds some tests which assert that all production(s) instance groups are highly available, and then scales up all components to make the tests pass. The reasoning behind the change is in the commit which implements the tests.
How to review
-------------
Code review
Have a look at `count by (bosh_job_name) …
> Ensure prod is highly available

- .travis.yml
- Makefile
What
----
We have one large monolithic travis job which does all the things.
This means all of our tests run in serial, and we wait a long time for things to install. If we experience a flake during a test, we have to re-run everything.
This PR does some questionable things to the Makefile, as well as `travis.yml` with the goal of
- caching dependencies
- avoid misusing `GOPATH`
- split out the `make test` single job into multiple jobs which can (in theory) be run in parallel
- steps can be re-run individually
How to review
-------------
Code review
Travis should pass
Travis should do what it is supposed to
Who can review
--------------
Not @tlwr
> Make travis faster [citation needed]

- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/env-specific/stg-lon.yml
- manifests/cf-manifest/operations.d/320-cc-set-staging-timeout.yml
What
----
Having been pushing a large R Shiny app it takes more than the default
of 900 seconds to compile all the dependencies that it needs. This PR
doubles the time to 1800 seconds and makes it configurable via the env
specific files we have.
How to review
-------------
Code review
Who can review
--------------
@paroxp
> Increase app staging times

- manifests/cf-manifest/operations.d/760-sqs-broker.yml
updates the sqs-broker boshrelease to pull in the latest version that resolves issues with FIFO queues being unable to be provisioned.
* check you are happy with [recent changes to the broker](https://github.com/alphagov/paas-sqs-broker/pull/14)
* It'll be deployed on [autom8foundary](https://deployer.autom8.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry) soon
Not me
> sqs: bump broker to fix fifo queues

- platform-tests/availability/app/healthcheck_availability_during_deployment_test.go
What
----
Our tests being at 100% were too stringent causing pipelines to become
blocked on one failure out of 14,000.
How to review
-------------
Code review
Who can review
--------------
Anyone
> Give a bit more wiggle room on availability tests

- manifests/cf-manifest/operations.d/530-ipsec.yml
[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/174773005)
Please review this in conjunction with part two: https://github.com/alphagov/paas-cf/pull/2454
What
----
We are removing ipsec because the release is deprecated and we do not need it anymore because we have mtls between gorouter and apps (which satisfies the e2e encryption requirement)
IPSec has two levels `require` and `use`. Where `require` rejects all packets which are not encrypted from the CIDR ranges configured for IPSec and `use` makes IPSec optional
How to review
-------------
Run this down your pipeline, it should do nothing whatsoever
Who can review
--------------
Not @alphagov/tech-ops-contributors
> [#174773005] Make IPSec optional

- manifests/prometheus/alerts.d/aiven-cost.yml
What
----
This alert went off because a tenant created a large new Elasticsearch. We actually can spend a bit more now without problems, so we don't have to do anything. This commit increases where the alert goes off to be more relevant to our current finance limits.
How to review
-------------
See [discussion on Slack](https://gds.slack.com/archives/CAEHMHGJ2/p1600969001063200).
Who can review
--------------
Not @46bit
> Increase Aiven billing alert to £28,500

- manifests/prometheus/alerts.d/auctioneer-lock-held-once.yml
- manifests/prometheus/alerts.d/bbs-lock-held-once.yml
What
----
These alerts are noisy
The firehose exporter has a bit of latency built into it, and so if a deployment happens, then the locks always appear held twice, even though a swap has happened
adding a 10m caveat to these alerts will reduce noise and hopefully make us trust these alerts more
For example, the following should not alert us, as it is a deployment happening:
How to review
-------------
Code review
CI
---
⚠️ Please do not merge this pull request via the GitHub UI ⚠️
> alerts: lock held once must breach for duration

- concourse/pipelines/create-cloudfoundry.yml
- tools/metrics/acceptance/acceptance_suite_test.go
- tools/metrics/acceptance/aiven_test.go
- tools/metrics/acceptance/aws_test.go
- tools/metrics/acceptance/cdn_broker_test.go
- tools/metrics/acceptance/cf_test.go
- tools/metrics/acceptance/currency_test.go
- tools/metrics/acceptance/tls_test.go
- tools/metrics/acceptance/uaa_test.go
What
----
:one: Our paas-metrics acceptance tests use the `HaveKey` matcher which produces massive test output. We only care about the metric name, so using `ContainElement` produces more readable test output.
:two: Our acceptance tests currently work via getting all the metrics once at the beginning. Taking inspiration from #2455 I refactored the tests to check metrics each time, so that `Eventually` is possible to use within each test.
3️⃣  I cherry picked the commit adding logging from #2455 thanks to @46bit
Why
---
I want to debug why https://deployer.london.cloud.service.gov.uk/teams/main/pipelines/create-cloudfoundry/jobs/deploy-paas-metrics/builds/268 is consistently failing, but it is difficult because the test output will not load on my computer, due to 1️⃣ .
How to review …
> Eventually metrics acceptance

- manifests/cf-manifest/operations.d/760-sqs-broker.yml
- terraform/cloudfoundry/iam.tf
- terraform/cloudfoundry/outputs.tf
- terraform/cloudfoundry/policies/restrict_to_local_ips.json.tpl
What
----
Depends on https://github.com/alphagov/paas-sqs-broker/pull/15 and a
corresponding boshrelease to push that out.
This adds a new managed policy, local_vpc_access_only, which can be
attached to an IAM User or Role to restrict use of that User/Role to
only be permitted from the local VPC.  This mitigates against
credentials that are leaked.
The S3 broker has a similar feature in
s3_broker_ip_restriction_policy_arn, but I decided to go with an
approach based on `aws:SourceVpc` rather than `aws:SourceIp`.  This is
so that: a) the policy doesn't have to care about specific IP
addresses, and b) the policy will work whether the AWS API is accessed
over public internet or via a private endpoint (at some point in the
future).
I deliberately made the local_vpc_access_only policy's name …
> Configure SQS broker to only permit access from local VPC

- manifests/prometheus/dashboards.d/user-impact.json
What
----
Our monitoring dashboard has a count of the currently firing alerts from Alert
Manager. It is configured to be a link to Prometheus, where one can see which
alerts are firing.
However, getting access to Prometheus is annoying, because it uses basic auth,
and to get those credentials we have to go to Credhub.
Instead, this commit changes the link to point to the same data, but presented
by Grafana. The user will already be logged in to Grafana, so it won't be
annoying.
How to review
-------------
Check the link works
---
> Link monitoring dashboard alerts count to Grafana not Prometheus

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/prometheus/operations.d/250-grafana-oauth.yml
- manifests/runtime-config/operations.d/510-add-prometheus-blackbox-exporter.yml
[Story](https://www.pivotaltracker.com/story/show/170669768)
What
----
Upgrades the Promethes BOSH release to [v26.3.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.3.0)
Use the [`paas-grafana-annotation-resource`](https://github.com/alphagov/paas-grafana-annotation-resource) instead of a task (resource is only compatible with Grafana 6.4 or greater)
Gotchas
----
- Annotations only get reported to Grafana in Z1, rather than both Z1 and Z2
- Prometheus has been upgraded several versions (with performance improvements)
- Grafana has been upgraded several versions (with usability improvements)
How to review
-------------
CI
Deploy to your dev env
Check that user impact dashboard annotations still work
---
🚨⚠️ Please do not merge this pull request via the GitHub …
> [#170669768] Upgrade Prometheus BOSH release

- tools/aws_redis_update_manager/aws_redis_update_manager
- tools/aws_redis_update_manager/lib/aws_redis_update_manager.rb
- tools/aws_redis_update_manager/lib/tenant_notifier.rb
- tools/aws_redis_update_manager/spec/tenant_notifier_spec.rb
What
----
Nobody made use of the alternate slot last time, so it seems unnecessary to
publish two. Instead, tenants can email us if the time doesn't suit them, and
we'll work it out.
How to review
-------------
1. Code review
2. Run it in your dev env, with `--action preview`
I've previewed the email in `prod-lon` and confirmed that preview works as intended.
---
> Remove alternate time slot from AWS redis update manager

- manifests/cf-manifest/operations.d/760-sqs-broker.yml
Reverts alphagov/paas-cf#2481
This seemed to break the platform tests with
```
• Failure [1.326 seconds]
SQS broker
/tmp/build/64614f0d/paas-cf/platform-tests/broker-acceptance/sqs_broker_test.go:16
creating an SQS queue
/tmp/build/64614f0d/paas-cf/platform-tests/broker-acceptance/sqs_broker_test.go:36
is accessible from the healthcheck app [It]
/tmp/build/64614f0d/paas-cf/platform-tests/broker-acceptance/sqs_broker_test.go:42
Expected
<int>: 1
to match exit code:
<int>: 0
```
> Revert "bump sqs-broker again"

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
There was a brief period where our calculations deemed 64 necessary
We are also onboarding new tenants (eg DCS for testing) in London
Increase to 63 from 60 (multiples of 3)
How to review
-------------
Code review
---
> cf: scale london to 63 cells

- manifests/prometheus/dashboards.d/service-type-adoption.json
What
----
Adds a Grafana dashboard to track service usage by type
The dashboard shows each of the following for each type of service on the
platform:
+ 7 day change
+ 30 day change
+ daily usage (min, max, average service instances)
How to review
-------------
Deploy this branch and check the dashboard exists in Grafana.
---
> [#174804724] Add a Grafana dashboard to track service usage by type

- manifests/cf-manifest/isolation-segments/prod-lon/egress-restricted-1.yml
- manifests/cf-manifest/spec/manifest/isolation_segment_spec.rb
What
----
Egress restricted isolation segment for DCS to test in
Scaled to two, so draining during deployments can happen without stopping apps manually
_(which would have to happen if there was only 1 cell)_
How to review
-------------
Code review
---
> isoseg: scale prod-lon isoseg from 0 to 2

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
CPU pegged during tenant load test (GDS VPS) which caused 5xxs across
the whole platform: we need more gorouters during high load
My interpretation of this chart is that something (it may not necessarily be CPU) is constrained during high periods of load, I believe that horizontally scaling will alleviate this problem
BOSH processes additionally have CPU limits
How to review
-------------
Code review
---
> cf: scale london gorouters from 6 to 15

- scripts/upload-secrets/upload-mailchimp-secrets.rb
- scripts/upload-secrets/upload_secrets.rb
What
----
Add an optional argument to the `get_secrets` function in order to pass a default (dummy) value to be used if the lookup in `paas-credentials` fails. Also set a dummy Mailchimp API key via this new route.
Why 
----
Some secrets, such as the Mailchimp API key, are only required in prod, but we still need to set a dummy value in staging and dev environments as it is expected to be non-nil during deployment/execution.
How to review
-------------
- Code review
- Check out the branch, run `CREDHUB (DEPLOY_ENV) $ make dev upload-all-secrets` and make sure it works as expected
---
> Allow to pass a default into get_secrets

- manifests/cf-manifest/env-specific/prod.yml
What
----
A tenant in Ireland is doing some load testing and may be seeing a little noisy neighbouring. This commit increases our routers by 50% which should firmly prevent that happening.
We've already decided to actually benchmark our routing, so soon this should happen based on data rather than intuition.
How to review
-------------
* Code review
---
> Increase ireland routers by 50%

- tools/metrics/pkg/health/service.go
- tools/metrics/pkg/health/service_test.go
What
----
Account notification events appear to be for long running things like
deprecations or other AWS service changes. We don't really want these to be
appearing in our alerts, because they're going to be long running and noisy.
We care about short term, service impacting events.
How to review
-------------
1. See if you agree with the change in principal
2. Code review
3. [See if I haven't included an event category that I should have](https://docs.aws.amazon.com/health/latest/APIReference/API_EventFilter.html#AWSHealth-Type-EventFilter-eventTypeCategories)
---
> Ignore account notification events in AWS health metrics

- concourse/pipelines/create-cloudfoundry.yml
What
----
Many of our automated tasks create temporary admin users. They are
temporary by two mechanisms:
1) the password is discarded as soon as the task finishes
2) the user is deleted before the task finishes
Recently we have seen at least one occasion where deleting the admin
user froze for more than 6 hours. `cf delete-user -f` seemed to just
freeze. Having looked at the source code I'm not sure why.
This commit makes deleting the admin user optional. It will time out after 5 minutes. The task should still fail, giving us some notice of the problem, but users will be left behind.
This is even more OK because we still remove the admin permissions from users that are left behind. When we do a deploy, the `sync-admin-users` step of the `post-deploy` job removes admin from any unexpected …
> Timeout on deleting admin users after 5 minutes

- config/service-brokers/aiven/config.json
- manifests/cf-manifest/operations.d/711-rds-broker-postgres95-plans.yml
- manifests/cf-manifest/operations.d/712-rds-broker-mysql57-plans.yml
- manifests/cf-manifest/operations.d/713-rds-broker-mysql57-plans-high-iops.yml
- manifests/cf-manifest/operations.d/714-rds-broker-postgres10-high-iops-plans.yml
- manifests/cf-manifest/operations.d/715-rds-broker-postgres10-plans.yml
- manifests/cf-manifest/operations.d/716-rds-broker-postgres11-plans.yml
- manifests/cf-manifest/operations.d/717-rds-broker-postgres11-high-iops-plans.yml
- manifests/cf-manifest/operations.d/718-rds-broker-mysql80-plans.yml
- manifests/cf-manifest/operations.d/719-rds-broker-mysql80-plans-high-iops.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/operations.d/750-s3-broker.yml
- manifests/cf-manifest/operations.d/760-sqs-broker.yml
What
----
Service plans have a boolean property `free` which tells CloudFoundry if the
plan is available to trial orgs. Unfortunately, `cf marketplace -e SERVICE`
says "free" whenever that property is true. That's a bit misleading for
billable orgs, who DO have to pay for it.
We don't have influence over the format of the `cf marketplace` command, so
instead of correcting it be more nuanced, we introduce a clarifying statement
in the description of the "free" plans.
How to review
-------------
1. Check you agree with the message.
---
> [#175232600] Clarify just how "free" service plans are

- manifests/prometheus/alerts.d/aiven-cost.yml
What
----
Adjust the Aiven spending alert to the current spending limit.
Why
----
Our Aiven spending has increased and is currently triggering this alert.
We are able to raise the alerting limit as our spending is still within the limit of the agreed budget.
How to review
-------------
Code review
---
> Update Aiven cost alert value

- concourse/pipelines/create-cloudfoundry.yml
What
----
Adds the -b flag when running cf disable-service-access elasticsearch due to a deploy failure.
How to review
-------------
Code review
---
> [Support] Specify elasticsearch broker with -b flag

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- scripts/upload-secrets/upload-cronitor-secrets.rb
What
----
[Story](https://www.pivotaltracker.com/story/show/175540593)
We want to be alerted when our smoke-tests are failing in production or more importantly are not running at all.
To achieve that, we are using cronitor to monitor our continuous smoke tests job.
How to review
-------------
you will have to have a Cronitor account or access to GDS Cronitor account.
1. Code review
2. Upload cronitor secrets to be sure that your dev environment is pointing to a valid Cronitor account and valid Monitor.
3. Deploy to your dev environment
4. Continuous smoke tests job should now ping Cronitor monitor at the start and finish of the job, in addition it will report failure, abort and error of the job.
5. Login to the Cronitor account (the one that you are testing against) and see that you are …
> Ensure we are alerted when our periodic tests do not run

- terraform/cloudfoundry/vpc_peering.tf
What
----
Adding a new vpc peering entry results in terraform recreating existing
connections because it uses the count parameter. This updates the resources
to use the for_each parameter so this doesn't happen.
How to review
-------------
- Code review
- Delete test VPC peering connections in the dev account
- Create devenv.vpc_peering.json and add a test vpc
- Update devenv.vpc_peering.json with a new vpc and redeploy
- Confirm previous peer is still connected
---
> [Support] Update VPC peering terraform

- scripts/common.sh
What
----
Until now, running commands such as `make dev pipelines` when not on the VPN resulted in an awful and incorrect error:
```
An error occurred (AccessDenied) when calling the ListAccountAliases operation: User: arn:aws:sts::_____:assumed-role/____________/______ is not authorized to perform: iam:ListAccountAliases on resource: * with an explicit deny
Required AWS account is dev, but your aws-cli is using keys for
Makefile:16: recipe for target 'check-env' failed
make: *** [check-env] Error 1
```
This commit adds a check that detects when the AWS API call fails, and warns about that. It also suggests users check they are on the VPN:
```
An error occurred (AccessDenied) when calling the ListAccountAliases operation: User: arn:aws:sts::_____:assumed-   is not authorized to perform: …
```
> Improve error message when not on the VPN

- manifests/cf-manifest/isolation-segments/prod/govuk-notify-staging.yml
- manifests/cf-manifest/spec/manifest/isolation_segment_spec.rb
What
----
GOV.UK Notify want to do load testing without interfering with their production workload. We've been having CPU capacity problems when they do it on the main PaaS Ireland cells.
This commit creates an Isolation Segment for them:
* Twelve cells, which is 1/4 the size of PaaS Ireland.
* To start with, the same `r5.xlarge` EC2 instance type as we use normally.
* These are just dedicated cells. We aren't doing any egress filtering or other security measures.
This commit doesn't assign their `staging` space to this Isolation Segment. I think it's fine for us to do that manually after deploy.
How to review
-------------
I think code review is fine.
---
> [#175778451] Create dedicated servers for GOV.UK Notify to do load testing against staging

- manifests/cf-manifest/operations.d/100-cf-update-vm-types.yml
What
----
For some time the active `diego-api` VM in Ireland has been exhausting its CPU credits. This VM runs [BBS](https://docs.run.pivotal.io/concepts/diego/diego-architecture.html#components), a Cloud Foundry component which manages the cluster of app instances. This has predictably experienced higher load as tenants have been doing more autoscaling.
This PR changes the EC2 instance type used for the `diego-api` VM. It upgrades from a `t3.medium` instance type to an `m5.large` [Benchmarks show](https://www.drlinkcheck.com/blog/t3-vs-m5) that the `m5.large`'s constant CPU performance is roughly equal to the burst performance of the `t3.medium`. This means that it will have substantially more CPU available at all times.
Cost estimate is something like $120/month in each non-dev …
> Run BBS on a higher-CPU instance type

- manifests/cf-manifest/isolation-segments/prod/govuk-notify-staging.yml
- manifests/cf-manifest/spec/manifest/isolation_segment_spec.rb
What
----
We recently created an isolation segment for GOV.UK Notify. They are using it to conduct load testing against their staging environment without affecting the rest of the PaaS.
We chose 12 cells to start with. This was based on the maximum memory usage if their staging environment autoscaled all the way up. We already suspected they might run low on CPU resources. They have now run more load tests and we can see that the isolation segment's cells all went up to 100% CPU.
This commit doubles the isolation segment's size from 12 cells up to 24. This will provide twice as much CPU.
An alternative approach is to use an EC2 instance type that has more vCPU cores. We may still do that, and it is cheaper (at least if we ignore existing Reserved Instances.) For now though we want load …
> Scale Notify staging isolation segment to 24 cells

- concourse/pipelines/create-cloudfoundry.yml
- config/billing/config-parts/postgres_12_high_iops_pricing_plans.json.erb
- config/billing/config-parts/postgres_12_pricing_plans.json.erb
- config/billing/config.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/720-rds-broker-postgres12-plans.yml
- manifests/cf-manifest/operations.d/721-rds-broker-postgres12-high-iops-plans.yml
- manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
- platform-tests/broker-acceptance/postgres_service_test.go
[Story](https://www.pivotaltracker.com/story/show/175721576)
What
----
We want to add Postgres 12.X database engine to our RDS Broker offering.
rds-broker-boshrelease PR is [here](https://github.com/alphagov/paas-rds-broker-boshrelease/pull/98)
How to review
-------------
- Code review
- Make sure that `post-deploy` and `custom-broker-acceptance-tests` jobs are `green`.
- Check that postgres 12 plans are visible when you are running `cf m -e postgres`
- [Optional] Create a service instance with one of the postgres 12 plans (`tiny-unencrypted-12` is the smallest one).
- [Optional] Check that the database was created correctly either via psql or via AWS Console.
Who can review
===
Not @barsutka 
---
> Add support for postgres 12 plans to the RDS broker

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/030-bosh-dns.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/spec/manifest/certificates_spec.rb
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
- manifests/prometheus/alerts.d/bosh-duplicate-releases.yml
What
----
Addresses a collection of CVE's from November 2020 by upgrading the platform to `cf-deployment` v15.0.0. It also takes the opportunity to silence some alerts.
How to review
-------------
1. Code review
2. Run it down your dev env
---
> [#175819180] Address November CVEs through platform upgrade

- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
What
----
- Elasticache (Redis) node and S3 bucket usage has recently surpassed 80 percent of our service limits triggering alerts in prod-lon.
- We have been granted service limit increases to 700 Redis nodes and 300 buckets now.
How to review
-------------
Check the new limits
---
> Increase alert thresholds for AWS service limits

- manifests/cf-manifest/operations.d/320-cc-release.yml
What
----
Deploys CAP 1.102.0 because it contains a fix for a CVE.
How to review
-------------
1. Check I got the release details right
2. Run it down your pipeline (n.b. it contains a database migration from 1.101.0, so you can't go back to before this release in your env)
---
> Address CVE-2020-5423 by deploying CAPI 1.102.0

- concourse/pipelines/create-cloudfoundry.yml
[Story](https://www.pivotaltracker.com/story/show/175936044)
What
----
Due to EOL of  Postgres 9.5, we have to use Postgres 12 for our healthcheck-db.
How to review
-------------
1. Code review
2. Deploy it to your DEV env, don't forget to switch the DISABLE_HEALTHCHECK_DB environment variable to `false` in the [Makefile](https://github.com/alphagov/paas-cf/commit/3c1c71b01e251515294914d2d3c5144779ff0670)
Who can review
----
Not @barsutka 
---
> Use Postgres 12 for the healthcheck-db in post-deploy job.

- manifests/cf-manifest/env-specific/prod.yml
What
----
There is a bug in the currently deployed version of Cloud Controller (1.102.0)
which is causing CF CLI v6 to misbehave and send polling requests as fast as it
possibly can. That's resulting in Notify getting rate limited when trying to
deploy.
We don't have a fix for the bug at the moment, and the rate limit is blocking
Notify's deploys. This commit triples the limit in Ireland to allow them to get
stuff out while we look for a fix.
How to review
-------------
1. See if you agree with the problem and the solution
---
> Triple cloud controller rate limit in Ireland

- manifests/cf-manifest/operations.d/350-diego-cell.yml
What
----
- At the moment, grootfs cache clean-up is not configured to kick in until a disk fills up.
- This leads to the team receiving BOSHJobEphemeralDiskPredictWillFill warnings and BOSHJobEphemeralDiskFull alerts.
- We set the grootfs.reserved_space_for_other_jobs_in_mb to 21 GiB in order to prevent these alerts from occurring during normal operation.
How to review
-------------
- Code review
- CI
- Check deployment to dev env
---
> garden: Set cleanup threshold to prevent full disk

- manifests/cf-manifest/isolation-segments/prod/govuk-notify-staging.yml
- manifests/cloud-config/operations/use-spot-instances-in-dev.yml
- manifests/cloud-config/paas-cf-cloud-config.yml
- manifests/variables.yml
What
----
Notify would like to test their app on instances with more CPU whilst keeping the memory the same
How to review
-------------
Code review
---
> change notify isolation-segment instance type

- manifests/cf-manifest/scripts/generate-isolation-segment-ops-file.rb
What
----
At the moment, this value seems to be ignored, in favour of some custom
functionality in regards to `isolation_segment_size`.
This is rather unwanted and perhaps unfamiliar behaviour, but we're not
here to fix the way we run the show, only the thing at hand.
Adding vm_type variable before the block, will make sure it has been set
to something, before the custom logic kicks in and perhaps overrides it.
The assignment line has been moved out of the block, to run after, to
make sure both cases are handled in the same way...
Ruby foo bad - sorry future generations.
How to review
-------------
- Sanity check
---
> isoseg: Respect the vm_tyme from data file

- manifests/cf-manifest/env-specific/prod.yml
What
----
Notify are load testing at almost 2000 req/s, and causing all of the routers to sit at 70%+ CPU usage. Adding 6 more should take the pressure off a bit.
How to review
-------------
Check I did my maths right, and that it's a multiple of 3.
Tell me if you disagree with the approach.
---
> Add 6 extra routers in Ireland to support Notify load tests

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
For a full description of what's being released here, see alphagov/paas-rds-broker#129. In short, it makes the broker a bit smarter about which versions of the different database engines it picks.
How to review
-------------
1. Run it down your env
2. Create a Postgres 10 services and try upgrade it to 12. This should work.
3. Repeat for 10 to 11, and 11 to 12.
4. Create a Postgres 9.5 service and try upgrade to 11 or 12. This should give you a helpful error message.
5. Upgrade the Postgres 9.5 to 10, then 12.
---
> [#175995621] Update RDS broker with Postgres 9.5 upgrade fixes

- manifests/cf-manifest/isolation-segments/prod/govuk-notify-production.yml
Mimics the segment given to their staging environment after load tests
on the staging segment have seen a significant impact in terms of
performance.
The plan is hopefully to only keep these around for a few months and pay
the cost of that whilst we bring things under control and can look at
reducing our CPU usage in a more long term manner.
> Add notify production isolation segment

- manifests/prometheus/alerts.d/diego_cell_rep_memory_capacity.yml
- manifests/prometheus/dashboards.d/user-impact.json
What
----
Since we introduced isolation segments, we've had more than 1 set of cells per environment. Unfortunately, our metrics didn't distinguish between them fully, leading to counts and charts that weren't quite true.
This PR includes the `bosh_job_name` label in the memory metrics, and updates the cell count chart in the user impact dashboard to only show figures for the default cells.
N.B. see commit message for the reasoning behind the change to the chart
How to review
-------------
1. Run it down a pipeline (deployed to mine)
2. Make sure [the cell count chart in the user impact dashboard](https://grafana-1.andyhunt.dev.cloudpipeline.digital/d/paas-user-impact/user-impact-andyhunt?orgId=1&refresh=5s) isn't broken (you might need to zoom the chart in a bit, because it hasn't been …
> Distinguish cell memory metrics by `bosh_job_name`

- manifests/prometheus/alerts.d/diego_cell_rep_memory_capacity.yml
- manifests/prometheus/dashboards.d/user-impact.json
What
----
Reverts the changes made in #2551 because they broke the chart in prod and prod-lon.
How to review
-------------
Check I reverted all of the commits in the original PR.
---
> Revert cell memory metric changes

- manifests/prometheus/dashboards.d/user-impact.json
What
----
Recently introduced and reverted a change that differentiated cell memory
metrics by isolation segment. Now that it's reverted, new metric values are no
longer differentiated, but old ones are. In order to have the cell counts chart
display properly, we need to explicitly look at the `diego-cell` segment.
How to review
-------------
1. Check I got the expression right
2. Compare it [a modified version in prod](https://grafana-1.cloud.service.gov.uk/d/HVQu5D-Mk/andy-user-impact-prod?orgId=1&refresh=5s)
---
> Pin cell counts chart to default cell segment only

- manifests/cf-manifest/env-specific/prod.yml
What
----
This is a follow up to 4fa6ddb27747f55a479fe2c6f3397853b0b91191, and reduces
the number of cells in the default cell segment in Ireland. Notify are no
longer using them, so we need fewer.
How to review
-------------
1. See if you agree
---
> Remove 9 cells from Ireland

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Adds 6 extra cells in London. Adding 6 and not 3 to give us some room for growth before the next bump.
(Cell count chart is a bit broken atm, but chart shows the trajectory)
How to review
-------------
Do you agree with my decision?
---
> Increase cells in London to 78

- terraform/prod-lon.vpc_peering.json
What
----
We already removed the cabinet-office-nsra organisation but forgot to remove the VPC peering.
How to review
-------------
Code review
---
> Remove cabinet-office-nsra's VPC peering

- manifests/cf-manifest/env-specific/prod.yml
What
----
Notify are ditching their staging isolation segment for the time being. We need to restore the 
number of cells their staging environment was occupying before, so there's room for their 
apps to come back. We don't need to restore the full 24 from the isolation segment, because
they won't be running load tests agains staging and thus won't need the extra capacity.
How to review
-------------
1. Do you agree with the number?
---
> Add 12 cells to Ireland

- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
What
----
The broker stops plans from being updated [1], but the broker says they're allowed. This results
in a `cf update-service -p` call leading to a Redis service instance in a `failed` state. Rather
than that, we should make it clear that the plans can't actually be updated.
[1] https://github.com/alphagov/paas-elasticache-broker/blob/master/broker/broker.go#L212
How to review
-------------
1. Run this down your env
2. Check it prevents you from updating the plan of a Redis service instance, without getting in to a failed state
---
> Prevent Redis plans from being updated

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We've been seeing a lot of HTTP 502s coming out of GoRouter recently. We think that's caused by apps not responding in time.
We're seeing high CPU usage in around 1 in 8 of the cells (memory consumption remains fine). We think this could be the cause of apps not responding in time. Adding more cells provides more CPU cores to carry out the work of the apps.
In 7 days we'll check back on the rate of HTTP 502s to see if adding cells had a positive impact.
How to review
-------------
1. Do you agree with the rationale?
1. Do you agree with the number of cells being added?
---
> Add 3 cells to London

- scripts/cf_subshell_scoped_login.sh
What
----
Fixed some incorrect behaviour when run on linux
* TMPDIR was being set without a trailing slash, and mktemp could not
create `/tmpcf_home.XXXXXX`
* `open` does not exist on linux. test if it's available, and if not,
use `xdg-open` instead.
How to review
-------------
Use `scripts/cf_subshell_scoped_login.sh` on a mac to ensure it still functions correctly.
---
> Fix some incorrect behaviour when run on Linux

- config/service-brokers/sqs/prod-config.json
- config/service-brokers/sqs/prod-lon-config.json
What
----
Add `gds-techarchs` org to list of orgs that are using the sqs broker
@whi-tw has manually enabled sqs for these orgs however for consistency I am updating the sqs config
How to review
-------------
- validate json
- test the pipeline
- validate that the orgs are enabled to use sqs 
---
> enable sqs for gds-techarchs orgs

- manifests/prometheus/alerts.d/diego_cell_rep_memory_capacity.yml
- manifests/prometheus/dashboards.d/user-impact-redux.json
- manifests/prometheus/spec/alerts/diego_cell_rep_memory_capacity.test..yml
What
----
Rework cell capacity metrics and alerts
We recently introduced isolation segments in to our production environments.
Isolation segments are collections of diego cells that are reserved for the
exclusive used of the Cloud Foundry orgs that are granted access to them. Aside
from this and their instance type, they exhibit identical characteristics.
For a long time we’ve a chart on our monitoring dashboard that shows us the
number of cells we have deployed, versus the number of cells we think we need
to meet our cell capacity goals, as per ADR021 [1]. With the introduction of
isolation segments, this chart has been misreporting the number of deployed
cells (and thus the required number), because the metrics haven’t distinguished
between different groups of cells.
On top of that, the …
> [#175872448] Show isolation segments in cell capacity chart

- manifests/prometheus/dashboards.d/user-impact-redux.json
What
----
The alerts count link went to my dev env by mistake. Updates it to use the correct domain.
How to review
-------------
Probably doesn't need review. It's not critical to anything, and it's a very small, unimportant change.
---
> Correct the link for currently firing alerts in the user impact dashboard redux

- manifests/cf-manifest/isolation-segments/prod/govuk-notify-staging.yml
- manifests/cf-manifest/spec/manifest/isolation_segment_spec.rb
What
----
They no longer need their isolation segment. We've already added the number of cells required for them in to the main segment.
How to review
-------------
1. Check I deleted the wrong file
2. Run `cf isolation-segments` to make sure they aren't still entitled to it
After deployment
------------------
1. We probably need to run `cf delete-isolation-segment` to get rid of it in CF, since I don't think the pipeline does it. The pipeline only removes the cells.
---
> Remove Notify's staging isolation segment

- manifests/prometheus/dashboards.d/user-impact-redux.json
What
----
The `diego_cells_required` metrics shows the number of cells required to run
tenant workloads with 33% spare capacity. The cell action alerts were
calculating the 33% spare capacity again, in error.
They should instead instruct us to add/remove cells when we're near to those
thresholds.
How to review
-------------
See if you agree with the thresholds
---
> Correct thresholds on cell actions in user impact redux dashboard

- manifests/prometheus/env-specific/prod-lon.yml
We maintain alerts for reaching 80 percent use of our service limits.
Alerts for S3 and ElastiCache parameter groups have been triggered and an increase was requested from AWS.
What
----
Increased service limits alert threshold: 400 S3 Buckets, 500 Elasticache parm groups
How to review
-------------
Sanity check numbers / check for typos / CI
---
> Increase alert threshold for AWS service limits

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/spec/image_resource_spec.rb
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
What
----
We want to stop using DockerHub images because the rate limiting could impact our ability to run CI/CD jobs. This adds a test which will stop us using DockerHub images. We plan to use GitHub Container Registry instead.
How to review
-------------
This is one of several PRs in `#176226306`. Review the others first.
⚠️  Before merging this PR, the Docker image tags need updating to what's built when the other PRs are merged.
---
> [#176226306] Stop using DockerHub images

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Upgrades `cf-deplyoment` from `v15.0.0` to `v15.4.0` to address the following USNs
- usn-4660-1
- usn-4635-1
- usn-4662-1
- usn-4665-1
- usn-4668-1
- usn-4667-1
Left to do
-----------
How to review
-------------
1. Code review
2. Check the versions bumped to here match those in the pivotal story
3. Check it runs down a pipeline OK
Who can review
--------------
Anyone
---
> Upgrade cf-deployment from v15.0.0 to v15.4.0 to address USNs

- terraform/cloudfoundry/cdn_broker.tf
What
----
Targeting a specific version of Postgres for the CDN database makes some
upgrade paths impossible. By targeting only the major version, AWS RDS can pick
an appropriate upgrade target in the event one is needed (e.g. for dev envs
going from an earlier version).
This should have no impact on instances already of Postgres 12.
How to review
-------------
1. Code review
2. Deploy it to an env that already has a Postgres 12 CDN broker database
---
> Target Postgres 12 major version only for CDN database

- concourse/pipelines/create-cloudfoundry.yml
What
----
We'd like the scraper to be reliable. It is possible, that during the
day, a lot of users are impacting prometheus' performance, sometimes
preventing us from gathering the metrics.
Running late at night, should allow the data to be collected
uninterrupted...
There are two prometheus instances, and due to how reliable we'd like
the scraper to be, we could attempt to use the prometheus that isn't
that frequently used.
How to review
-------------
- Sanity check
---
> Pazmin platform prometheus

- manifests/cf-manifest/operations.d/714-rds-broker-postgres10-high-iops-plans.yml
- manifests/cf-manifest/operations.d/715-rds-broker-postgres10-plans.yml
- manifests/cf-manifest/operations.d/716-rds-broker-postgres11-plans.yml
- manifests/cf-manifest/operations.d/717-rds-broker-postgres11-high-iops-plans.yml
- manifests/cf-manifest/operations.d/720-rds-broker-postgres12-plans.yml
- manifests/cf-manifest/operations.d/721-rds-broker-postgres12-high-iops-plans.yml
What
----
We believe that the `postgis` extension is causing problems when upgrading
Postgres major versions. We're making a change the RDS broker to force it to be
disabled when upgrading, but in order to do that the extension has to be
removed from the list of defaults.
How to review
-------------
1. Make sure I didn't miss anywhere
2. See if it [deployed OK in my environment](https://deployer.andyhunt.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry)
3. See if you can enable and disable the `postgis` extension on a Postgres database
---
> [#176574936] Remove `postgis` from default Postgres extensions

- manifests/prometheus/env-specific/prod.yml
What
----
The S3 service limit threshold for alerts needs to be configured for
both London and Ireland dashboard, this was overlooked last time.
How to review
-------------
Check the value
---
> Bump S3 service limit in Ireland as well

- concourse/pipelines/create-cloudfoundry.yml
What
----
Remove the concourse-tfstate input, we don't `get` it and we also don't use it.
How to review
-------------
* Sanity check
---
> PSN connection for DCS: Remove broken and unused concourse-tfstate reference

- manifests/prometheus/alerts.d/cloudfront_instances_quota.yml
- manifests/prometheus/env-specific/default.yml
- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
- tools/metrics/README.md
- tools/metrics/gauges_cloudfront_instances.go
- tools/metrics/gauges_cloudfront_instances_test.go
- tools/metrics/main.go
What
----
Add a gauge and alert for the number of Cloudfront Distributions in the account.
How to review
-------------
* Code Review
* Run tests
* Run down pipeline to check
---
> [Support] Add a gauge to keep track of the number of CloudFront Distributions

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
This is in response to https://www.cloudfoundry.org/blog/usn-4719-1/
How to review
-------------
Code review against https://bosh.io/releases/github.com/cloudfoundry/cflinuxfs3-release?all=1
---
> [##177078795] Override cflinuxfs3 to 0.226.0

- concourse/pipelines/create-cloudfoundry.yml
What
----
Adds `bosh-tfstate` input to the PSN terraform part of the pipeline in response to error:
```
missing inputs: bosh-tfstate
```
How to review
-------------
1. Code review by me
---
> [#177001717] Adds `bosh-tfstate` input to the PSN terraform part of the pipeline

- terraform/psn/data/security-group-seed.json.tpl
- terraform/psn/psn.tf
What
----
Cloud Foundry's Cloud Controller expects that security groups
will specify a destination as a single string. As a result, our
script for generating ops files for security groups bakes in
the assumption that its input will have a single string in the
corresponding part (the `subnet_cidr` parameter).
The PSN Terraform code was outputting an input for that script
which gave the `subnet_cidr` parameter as an array of strings,
because the PSN VPC connection has multiple IPs. This caused an
error when deploying to Cloud Foundry that we could only catch
in a production deploy.
To mitigate this, we mutate the output from the PSN Terraform
to output one seed per subnet. The script we have for
generating security groups is already capable of generating
multiple security groups. This is …
> [#177001717] Alter PSN Terraform to output multiple subnet group seeds

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
Bum xenial stemcell to 621.108 to mitigate [USN-4749-1](https://www.cloudfoundry.org/blog/usn-4749-1/)
How to review
-------------
Run down pipeline
Who can review
--------------
Not Me
---
> Bump xenial stemcell version to mitigate usn-4749-1 and bump cflinuxfs3

- concourse/pipelines/create-cloudfoundry.yml
What
----
Updates generate-cf-config job so it isn't dependent on the vpc-peering-terraform job
How to review
-------------
Code review
---
> [Support] Remove vpc-peering-terraform job dependency

- terraform/cloudfoundry/rds_broker.tf
What
----
A tenant using Drupal has had problems with the default value of `max_allowed_packet` in RDS. The default is 4MB and that seems to prevent using strings or blobs larger than that.
In https://github.com/alphagov/paas-rds-broker/pull/135 we increased `max_allowed_packet` to 256MB. That worked, but then broke again.
It turns out that MySQL 5.7 is also configured in Terraform. It's a bit tricky to try and remove it (needs some state editing.) For now I'm just going to set `max_allowed_packet` in Terraform as well.
How to review
-------------
Code review should suffice.
---
> Fix setting max_allowed_packet for MySQL 5.7

- manifests/prometheus/operations.d/311-silence-cf-app-alerts.yml
What
----
The Prometheus Bosh release gives us a package of CloudFoundry
alerts. Many of these we care about, but two in particular are
very noisy and don't provide us any useful information:
- CFAppCrashed
- CFAppUnhealthy
The Bosh release doesn't feature configuration options for
which alerts to enable/disable, or to configure their alert
level.
Instead of making a PR to the upstream, which will take a long
time to get merged and released, we can reduce our alert noise
quickly by directing those alerts in to a black hole in
Alertmanager.
How to review
-------------
1. [See that it deployed OK in my env](https://deployer.andyhunt.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/prometheus-deploy/builds/91)
2. See if you agree [with the …
> [#176655014] Silence CF app alerts by pointing them in to a black hole

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- scripts/upload-secrets/upload-slack-secrets.rb
What
----
We add a script that
- checks users for the AWSCompromisedKeyQuarantine policy attachment
- deactivates all AWS Access keys of the user
This is introduced to automate the first response to leaked S3 AWS Access Keys on GOV.UK PaaS.
The job is run as often as possible (every 1 min - effectively runs every 3-4mins)
The job notifies Cyber via the #cyber-security-alerts channel
How to review
-------------
- Code review
- Deploy to dev env:
- `CREDHUB $ make dev upload-slack-secrets`
- `make dev pipelines`
- Optionally - LET CYBER KNOW IF YOU DO THIS - attach AWSCompromisedKeyQuarantine policy to a test user and see the script do it's thing.
---
> Add job to automate leaked key deactivation

- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
The cabinet-office-people-finder` org has been deleted, however the
broker is still trying to enable the CSLS broker for this non existent
org. It was removed vi https://govuk.zendesk.com/agent/tickets/4397156
How to review
-------------
Code review
---
> Remove `cabinet-office-people-finder` from CSLS orgs

- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/720-cdn-broker.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
What
----
This PR updates the deployed broker releases to include versions that set cost tags for their respective backing services
How to review
-------------
Code review against
https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/cdn-broker-release/jobs/build-final-release/builds/15
https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-rds-broker/jobs/build-prod-release/builds/66
https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/elasticache-broker-release/jobs/build-final-release/builds/4
---
> [#177219242] Update broker releases to versions that set cost tags

- manifests/prometheus/operations.d/100-update-vm-types.yml
- manifests/prometheus/spec/operations/monitor_cf_spec.rb
- manifests/prometheus/spec/operations/update_vm_types_spec.rb
What
----
We're utilising Prometheus a bit more, and pushing it a bit harder. A larger VM type should help it stay available for us.
How to review
-------------
1. Deploy your env, leave it half an hour so there's some historic data
2. Deploy this branch
3. Check that the historic data is there after deploy
In my env the deploy happened at ~1530 and lasted 20 minutes.
---
> [#177263693] Use a 'large' type VM for platform Prometheus instances

- manifests/prometheus/operations.d/221-monitor-cf.yml
- manifests/prometheus/spec/operations/monitor_cf_spec.rb
What
----
We have "Firehose" VMs that run the [Firehose Exporter](https://github.com/bosh-prometheus/firehose_exporter).
Until now our Firehose VMs have used the t3.medium instance type. But in London they have been experiencing exhausted CPU credits for months now. CPU usage is not very high but they use just a bit more CPU than they have CPU credits. Moving them to m5.large will resolve this by giving them consistent amounts of CPU.
Here's a Firehose in London:
Here's a Firehose in Ireland:
You can see that the CPU credit usage isn't all that much higher in London, but it's enough to exhaust them. I think it's better to just move all Firehose VMs rather than just doing some.
How to review
-------------
Code review should be good enough. I'm pretty confident the `path` is correct based …
> Enlarge Firehose VMs to avoid exhausted CPU credits

- concourse/pipelines/create-cloudfoundry.yml
What
----
This is done as sharing a serial execution group with the leaked key check prevented smoke-tests, etc. being run in prod (only one running job per serial group is allowed).
The leaked key detection job is just a simple bash script, so it is safe to execute in parallel to smoke-tests.
We also saw the checks taking more time in prod (17 mins) as compared to dev (4 mins), so increasing the leaked key timer interval to 20 mins.
How to review
-------------
- Apply changes to pipeline in dev environment
- Check the jobs `continuous-leaked-aws-key-check` AND (`continuous-smoke-tests` OR `continuous-billing-smoke-tests`) can run in parallel.
---
> Move AWS leaked key check into separate group

- Makefile
- README.md
What
----
We've introduced two shared, persistent dev envs. We don't want them auto-deleting every night.
How to review
-------------
1. Code review. In particular, see commit messages for an explanation of the dark Make magic.
---
> [#177474241] Prevent persistent dev envs being autodelete

- manifests/cf-manifest/operations.d/320-cc-release.yml
What
----
Address CVE-2021-22115 by bumping capi to 0.106.0
How to review
-------------
- Check release details against https://bosh.io/releases/github.com/cloudfoundry/capi-release?version=1.106.0
- Run down your dev environment pipeline
---
> Address CVE-2021-22115 by bumping capi to 0.106.0

- Makefile
What
----
We couldn't do this before, as some of the variables in `dev` target are
generated based on DEPLOY_ENV value.
We can override those to however, making it all seemless and making Make
happy with a single target at all times...
How to review
-------------
- Sanity check
---
> Reduce number of targets to one

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Scaling as it's recommended to [have as many traffic controller instances](https://docs.cloudfoundry.org/loggregator/log-ops-guide.html#-traffic-controller) as doppler instances.
How to review
-------------
Code review 
---
> [#175872094] Scale Traffic Controller Instances

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Reverts our recent UAA bump due to an issue with the invite link. 
How to review
-------------
Code review (already deployed to dev02)
---
> [Support] Revert our UAA release to 74.31.0

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
This updates the CDN broker to 0.1.38 whihc updates the TLS ciphers used
on CDN distributions to be the latest AWS config.
How to review
-------------
Code review against https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/cdn-broker-release/jobs/build-final-release/builds/16
---
> Update CDN broker to latest release

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Upgrade: 
- cf-deployment to 16.13
- stemcell to 621.123
- cflinuxfs3 to 0.236
To address various CVEs listes in [story #177983221 on Tracker ](https://www.pivotaltracker.com/story/show/177983221).
Also shoehorning in scaling up of paas-admin app instances to reduce alert noise while implementing a proper fix.
How to review
-------------
- Code review
- Run down dev / see it deployed in schmie.dev
---
> [#177983221] Upgrade cf-deployment 16.13

- manifests/cf-manifest/data/100-tenant-uaa-client-config.yml
What
----
In order to run the tests against terraform there is a need for a custom
UAA client. in order to not have any conflict with Prod this has been
placed in staging.
How to review
-------------
Code review
Check there is a cred set via `credhub get -n /stg-lon/stg-lon/secrets_uaa_clients_terraform_provider_test_account_secret`
---
> Add terraform provider UAA client

- manifests/cf-manifest/data/100-tenant-uaa-client-config.yml
What
----
Fixing `Missing property: uaa.clients.terraform-provider-test-account.authorized-grant-types)`
How to review
-------------
Code review
---
> Fix missing authorized-grant-types

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/pipelines-cloudfoundry.sh
What
----
PaaS admin is usually re-deployed every time a new release is detected. In some environments, we don't want this to happen, because it wrecks developer productivity, or overwrites a deliberate change that is being tested.
Running the below will now disable the continuous deployment in an environment
make ENV pipelines ENABLE_PAAS_ADMIN_CONTINUOUS_DEPLOY=false
How to review
-------------
See if you agree with the changes
---
> Allow the continuous deployment of PaaS admin to be disabled

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
What
----
The updated docker containers are built with an alpine 3.13.3 as the
base image rather than 3.12
How to review
-------------
Code review
Who can review
--------------
Anyone
---
> Update docker containers

- manifests/prometheus/env-specific/prod-lon.yml
What
----
We are alerted if using more than 80 percent of the current limit (500).
AWS raised the service limit to 700 for us.
How to review
-------------
- Code review
---
> Bump London Elasticache Parm Group service limit

- manifests/prometheus/alerts.d/s3_bucket_count.yml
What
----
Previously we were alerting when were over 80% of our quota. This made sense
when the limit was smaller. We're at 400 now, which means we're getting
alerted when we're at 320/400. That's too early, and the S3 bucket count growth
rate doesn't indicate we need to act soon; we've gained ~40 buckets (10%) in
the 30 days between 3rd May and 2nd June 2021.
If we continue alerting on 20% remaining, the alerts will continue to get
earlier and earlier and we get more and more blind to them.#
We should instead alert ourselves when there are 50 remaining. Our growth rate
suggests that gives us more than enough time to act.
How to review
-------------
Do you agree?
---
> Alert us when we've <=50 S3 buckets left in the quota

- concourse/scripts/smoke_tests_email.sh
What
----
When a smoke test fails, we get an email like this:
`The smoke tests have failed in environment prod-lon. See Concourse for details`
With `Concourse` being a link to e.g. https://deployer.london.cloud.service.gov.uk/teams/main/pipelines/create-cloudfoundry?groups=health
But that URL doesn't work, it should be https://deployer.london.cloud.service.gov.uk/teams/main/pipelines/create-cloudfoundry?group=health
How to review
-------------
Check the old link doesn't work and the new one does.
---
> Fix link to Concourse create-cloudfoundry health group in smoke test failures

- scripts/create_buildpacks_email.sh
- tools/buildpacks/.gitignore
- tools/buildpacks/email.go
- tools/buildpacks/email.tmpl
- tools/buildpacks/go.mod
- tools/buildpacks/go.sum
What
----
When we send out an email to tenants about buildpack upgrades, we list all of the dependency version changes, along with links to all of the release notes. This is decent chunk of information, and it would be easy for tenants to not read through all of the release notes for all the buildpacks they use, and/or to miss something important.
To make life easier for them, we should read the release notes ourselves as operators, and summarise the important bits (e.g important versions being removed, shiny new versions being added, whole new buildpacks being introduced).
The buildpack email generation Go program now interactively prompts users to read the notes and edit a message about them (n.b. it respects the $EDITOR env var). Those messages are compiled in to the final email.
How …
> Buildpack email generation interactively prompts for highlights

- concourse/pipelines/create-cloudfoundry.yml
- config/service-brokers/aiven/config.json
- platform-tests/aiven-broker-acceptance/elasticsearch_service_test.go
What
----
Deprecate ElasticSearch 6.x plans in the Aiven broker.
Doing this using Maxim and Miki's commit from last year, it should now work.
How to review
-------------
Code review.
---
> Deprecate elasticsearch 6.x plans in the aiven broker.

- concourse/pipelines/create-cloudfoundry.yml
- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
What
----
As in [1] and [2], the CF app autoscaler isn't working with the Ubuntu Bionic stemcells right now, and needs to be deployed with the old Xenial stemcells instead.
This has been working in environments that existed prior to the Xenial->Bionic switch, because the Xenial stemcell image continued to exist in Bosh's storage. However, this isn't true for new environments, and thus they fail to deploy the autoscaler.
To remedy this, we take a copy of the stemcell uploading Concourse task, and pop it in the pipeline just before the autoscaler is deployed. We also replicate the ops file that sets the stemcell from `cf-manifest`. The two combine to download the correct stemcell image, and upload it to Bosh.
[1] https://github.com/cloudfoundry/app-autoscaler-release/pull/254
[2] …
> Upload stemcells during autoscaler deploy

- .gitmodules
What
----
Point to our own fork, for the autoscaler, making it workable again by our pipelines...
The SRC has not changed, since it's on the same commit.
How to review
-------------
- Deploy to `dev01` by either using this branch or cherry-picking the commit (@risicle)
- See pipelines unblocking
---
> autoscaler: Point to our fork

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We're starting to see dropped messages from the system. The rule of
thumb is that we keep the ratio of cells to dopplers around 2:1.
This increase should suffice for a short while.
Ireland does not grow, and we didn't see issues thus far. If anything,
it is generously provisioned.
How to review
-------------
- Sanity check
---
> Increase number of doppler instances

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/spec/manifest/env_spec.rb
What
----
We believe that we should have roughly 1 Doppler instance for every Diego Cell.
In the past, we haven't adjusted doppler counts when adjusting cell counts.
This test should force us to do that when it's appropriate.
How to review
-------------
Do you agree? Does the test look good?
---
> Test that we have roughly the right number of Doppler instances

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/scripts/nagging_email.sh
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
~This is a draft because it sits on top of #2683, and needs that to be merged first.~
What
----
Now that we have switches with which we can "easily" disable troublesome AZs, it would be good to have some visibility of the effective state of these switches and also some alerts to remind us to restore the AZs once we think the incident is over. One of the switches now has the additional side effect of disabling the resurrector - but doesn't automatically re-enable it when flipped back, so making the state of the resurrector visible and also raising reminder alerts would be useful too.
This PR creates a periodic job for each bit of state, using a naming pattern `-is-enabled-`. The jobs are set to "fail" when the relevant bit is _not_ enabled, allowing the job to be used effectively as a …
> [#178621826] create-cloudfoundry pipeline: add AZ-status-related indicator/alert jobs

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/spec/manifest/env_spec.rb
What
----
> Traffic Controller resources are usually scaled in line with Doppler
> resources. The recommended formula for determining the number of Traffic
> Controller instances is:
> Number of Traffic Controller instances = Number of Doppler instances / 2
As we do not work in single instances, we increase things in pairs of threes.
We're also refining the tests for number of dopplers... As we seem to be
just on the edge and to incorporate the following:
> Doppler resources can require scaling to accommodate your overall log
> and metric volume. The recommended formula for estimating the number of
> Doppler instances you need to achieve a loss rate of < 1% is:
> Number of Doppler instances = doppler.ingress / 16 000
> where doppler.ingress represents the per-second rate of change of the …
> Make instance count changes

- concourse/pipelines/create-cloudfoundry.yml
- concourse/tasks/check-az-is-enabled-in-manifest.yml
- concourse/tasks/check-az-is-enabled-in-vpc.yml
- concourse/tasks/send-nagging-email-alert.yml
What
----
This is mostly a fixup to #2694's lack of foresight, not providing `paas-cf` as an input to the email-sending tasks. I made the provided `paas-cf`s use a `passed` of `pipeline-lock`, so that it would only try to use tasks & scripts matching the currently set pipeline.
As I was fixing it I was embarrassed and annoyed by the amount of repetition required and how verbose my previous solution was, so I did some refactoring here, pulling three of the steps out into separate tasks.
How to review
-------------
Same as #2694, though TBH we're unlikely to be able to test it properly (the emails) until it hits staging.
---
> [#178621826] Fixup nagging alerts

- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/env-specific/stg-lon.yml
- manifests/cf-manifest/operations.d/320-cc-set-healthcheck-timeout.yml
What
----
Up the cc max health check timeout to 300s
We have a tenant struggling with health check timeouts when deploying a large Python app ([Link to ticket](https://govuk.zendesk.com/agent/tickets/4613945)).
How to review
-------------
Deploy to dev environment and `cf push` an app with `applications.timeout: 300` in the manifest.
---
> Up the cc max health check timeout to 300s

- config/logit/20_custom_cf_filters.conf
- config/logit/output/generated_logit_filters.conf
What
----
Handle as DEBUG (i.e., drop) spammy type=SYSCALL logs. We send way too many GBs of logs to Logit and these look like they can be safely dropped.
How to review
-------------
* Code review
* Try it out on PaaS Dev.
---
> Logit config: Handle as DEBUG (i.e., drop) spammy type=SYSCALL logs

- config/billing/config-parts/influxdb_pricing_plans.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/billing/pricing_data.yml
- config/service-brokers/aiven/config.json
What
----
A tenant requires more than 50 GB storage. I have added the next two
larger plans up to facilitate an upgrade.
We add in a medium and large plan with 15G RAM / 140G storage and 31G RAM and 280G storage respectively
How to review
-------------
- Code review
- Deploy in dev and check Influx can be provisioned with new plan
---
> Add medium and large influxdb plans

- terraform/cloudfoundry/cf_rds.tf
What
----
We need to upgrade from Postgres 11.1 because of a vulnerability. At the time of writing, 11.12 is the highest minor version we can target.
```
$ aws rds describe-db-engine-versions --engine postgres --engine-version 11.1 | \
jq '.DBEngineVersions[].ValidUpgradeTarget[] | select(.EngineVersion | startswith("11.")) | .EngineVersion'
"11.2"
"11.4"
"11.5"
"11.6"
"11.7"
"11.8"
"11.9"
"11.10"
"11.11"
"11.12"
```
How to review
-------------
This is difficult to test. In dev, all we can do is apply the upgrade to the database manually and immediately, then roll this PR out afterward, to check Terraform doesn't do anything unexpected.
We could, optionally, test the theory that Terraform will schedule the upgrade for the next maintenance window by rolling out the PR in a dev env without …
> [#178053268] Pin the CloudFoundry database to Postgres 11.12

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Scale Cells in London to 111 and doppler/log-api instances to match the increase
How to review
-------------
Look in grafana and see if it's appropriate 
---
> [Support] Scale Cells in London to 111

- config/billing/config-parts/sqs_pricing_plans.json.erb
- config/billing/config.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/billing/pricing_data.yml
What
----
Added a pricing plan for sqs queues so we can charge for them so profit.
For the `component.name` I assumed these were relatively free-form and we don't quite have anything like this yet so i just put `queue`. Good enough?
As it is, I've set this to start collecting queue prices from the first of Aug, but if this isn't merged before then (likely), I'll probably bump it forwards to something post-rollout.
How to review
-------------
Well, *I* tested this by creating a billable organization on a dev paas with only SQS queues in a space, then kicking the billing collector until it woke up and did its job, counting the price of the sqs service:
You could probably do similar quite easily. (But if you do so remember first to bump back the `valid_from` dates to something in the past) …
> [#178944646] billing: add sqs pricing plan

- concourse/pipelines/create-cloudfoundry.yml
What
----
AWS have started to use "AWSCompromisedKeyQuarantineV2" on compromised
keys, this commit updates our logic to take account of encountering this
or the previous policy when runningundertaking matches.
How to review
-------------
Code review
---
> Update to include new AWS quarantine policy

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/nagging_email.sh
- concourse/scripts/pipelines-cloudfoundry.sh
- concourse/tasks/curl-az-healthcheck.yml
- terraform/az-monitoring/main.tf
- terraform/az-monitoring/module/main.tf
- terraform/az-monitoring/module/outputs.tf
- terraform/az-monitoring/module/variables.tf
- terraform/az-monitoring/outputs.tf
- terraform/az-monitoring/variables.tf
- terraform/az-monitoring/versions.tf
- tools/simple-healthcheck/.gitignore
- tools/simple-healthcheck/Dockerfile
- tools/simple-healthcheck/index.js
- tools/simple-healthcheck/package.json
What
----
We'd like to be simply running a small application on different set of
services, with very minimal response time and data. We'd like to assure
the response is not cachable - or rather that we can determine if it
hasn't been.
We will be running 3 VMs across all AZ running out healthcheck
application, which then later will be pingable by our monitoring system.
How to review
-------------
- Code review
- Run the pipelines with `DISABLE_AZ_HEALTHCHECK=false`
- Monitor checks
---
> Add AZ monitoring

- config/billing/config-parts/redis_pricing_plans.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- platform-tests/broker-acceptance/redis_service_test.go
What
----
Config mostly cloned from 5.x plans except we no longer have any control over minor redis versions.
Here I have also switched the common parameter `reserved-memory` to `reserved-memory-percent`, which seems to be the newer more broadly supported form of the parameter, because it seems like `redis6.x` has quietly dropped support for `reserved-memory`. Still, since this is universally set to 0, surely 0% of X = 0, right?
Thoughts welcome.
How to review
-------------
Deploy. Try to provision a redis 6.x instance.
---
> [#177724957] elasticache broker: add plans for redis 6.x

- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
Gives the `gds-digital-identity-authentication` org access to the Splunk broker
How to review
-------------
Did I get the org name right?
---
> Grant Splunk broker access to gds-digital-identity-authentication

- .github/workflows/test_on_pr.yml
- go.mod
What
----
Our CI is currently failing as Gomega now requires Go >= 1.16.
Bumping to Go 1.17 which is the current release.
Also adding in a minimal `go.mod` as is required by Go >= 1.16.
Currently open PRs failing CI will require a rebase once this is merged.
How to review
-------------
- Code review
- Make sure CI tests are passing
---
> Bump GitHub Actions Go version to 1.17

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We had a tenant notifying us of slow/timing out deployments in London and the current cell utilisation is close to the required cell count mark. Adding in 2x3 extra cells as recently we hit a maximum of 115 required.
Also increasing Doppler instance count to 60 as needs to be >= 50 percent Diego-cells and divisible by 3 (58.5 -> 60)
How to review
-------------
- Code review
---
> Increase London cell count to 117

- concourse/scripts/unbind_job.rb
What
----
`run_job` has been broken for a while.
We added `steps` under `in_parallel`, so it couldn't find the `get` step.
To fix this, when recursing, also scan any objects with the key `steps`.
How to review
-------------
Code Review
---
> BAU: Fix unbind_job make target

- terraform/cloudfoundry/policies/elb_access_log_bucket.json.tpl
What
----
Allow the SRT access role to access our access log buttons. ([access](https://en.wikipedia.org/wiki/Semantic_satiation))
How to review
-------------
Run down a dev env
---
> [#175917036] Shield SRT access bucket policy

- config/service-brokers/csls-splunk/prod-config.json
What
----
Given `gds-security` org access to the csls splunk broker. Looks like they must have had it in the past, but no longer do. This should make it permanent.
How to review
-------------
Look at it. I don't think deploying to a dev instance will have any effect.
---
> csls-splunk broker: enable access from gds-security in prod

- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
Removes csls-splunk broker access for gds-shielded-vulnerable-people-service as the org has been deleted.
How to review
-------------
Code review
---
> [Support] Remove gds-shielded-vulnerable-people-service

- concourse/pipelines/create-cloudfoundry.yml
What
----
The path to the state file was wrong, which caused an error message to be
silently written to the output file, which was subsequently ingested in a later
task. The value it ingested was of no use to it, and caused an error, which
manifest itself as a failed healthcheck.
How to review
-------------
We mobbed it on a call and saw it worked
---
> Correct path to TF state file in AZ healthcheck output extraction

- terraform/cloudfoundry/cf_rds.tf
What
----
Remove the parameter group for pg11 as we have migrated to 13.
How to review
-------------
Tested in dev02, it should hit staging first so will see if it causes issues.
---
> Remove DB parameter group for postgres 11 - **Merge after 08/11/21**

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Updated our RDS broker to that merged in https://github.com/alphagov/paas-rds-broker/pull/144, which brings in the metric collector golang upgrade etc.
How to review
-------------
This has already been rolled out to a dev deployment, do we need to do so again or is staging enough?
---
> update rds broker to 1.17.0

- concourse/pipelines/destroy-cloudfoundry.yml
What
----
The [upgraded terraform](https://github.com/alphagov/paas-cf/pull/2750) has changed a couple of things and now this script is broken. To fix it:
- `-force` has been replaced by `-auto-approve` as the former is no longer recognised
- ~~use `-chdir` to change the directory from which the command is executed https://www.terraform.io/docs/cli/commands/#switching-working-directory-with-chdir~~
How to review
-------------
Run the `destroy-cloudfroundry` pipeline in a dev environment and check that terraform doesn't complain about running this command
---
> Bugfix: Replaces deprecated terraform command

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
- Bump cf-deployment to 16.25, excluding buildpacks
- Bump cflinuxfs3 to 0.263.0 (cf-deployments requires or higher 0.262.0. 0.263.0 addresses other CVEs)
- Bump capi to 1.119.0, in line with cf-deployment 16.25
- Bump cf-acceptance-tests to 16.25
- Bump ubuntu-bionic stemcells to 1.36
How to review
-------------
- Code review commit by commit
- Deploy to dev env 
- Check against acceptance criteria in [the story](https://www.pivotaltracker.com/story/show/180113784)
---
> [180113784] Address CVEs (Bump cf deployment to 16.25)

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Bumps CDN broker to include TLSv1.2_2021
https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/44
How to review
-------------
Code review
---
> [180067724] Bump CDN broker to include TLSv1.2_2021

- Makefile
This is a fixup of a mess I made in #2780. Apparently my export of BRANCH didn't actually do anything? `make` is weird sometimes.
What
----
* Fix `current-branch` make target so it actually functions correctly.
```Makefile
.PHONY: current-branch
current-branch: ## Deploy current checked out branch
$(eval export BRANCH=$(shell sh -c "git rev-parse --abbrev-ref HEAD"))
@true
.PHONY: tnw-test
tnw-test:
/bin/sh -c "echo $${BRANCH}"
```
```shell
❯ make current-branch tnw-test
/bin/sh -c "echo ${BRANCH}"
development_make_target_improvements
```
How to review
-------------
* Code review.
---
> [FIX] Make `current-branch` make target actually function correctly

- config/billing/config-parts/postgres_13_high_iops_pricing_plans.json.erb
- config/billing/config-parts/postgres_13_pricing_plans.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
What
----
New billing has a number of known formulae it expects. The formulae without
(), for postgres 13, is not currently in new billing.
This changes the formulae to make them be picked up happily by new
billing.
Paas-billing change is here
https://github.com/alphagov/paas-billing/commit/e673723e9ecb7bb5a6fdbfbdbca8161c2260eb5a
How to review
-------------
Code review - not @whpearson 
---
> Make Postgres 13 formulae consistent with new billing

- config/billing/config-parts/platform_pricing_plans.json.erb
What
----
Accidentally updated valid_to across the platforms billing template -
unknown plan and Prometheus plans became unvalid after 2019-02-28 for
new billing.
How to review
-------------
- Code review
---
> Fix valid_to for Prometheus and unknown plans

- concourse/pipelines/create-cloudfoundry.yml
What
----
This step was failing to find a user in paas-accounts (we were getting 404), and also not creating one. 
This change that an user is created when we get 404
How to review
-------------
Code review + try out on dev environment 
---
> Changes condition for checking if admin user exists in paas-accounts

- concourse/pipelines/create-cloudfoundry.yml
What
----
- Revert "REMOVEME: remove vestigial envar"
This was just to ensure an old envvar was removed on the first deployment. It is now not needed, as it has been run once.
How to review
-------------
* Code review
---
> [#180081291] stop removing envvar

- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
What
----
Fix billing plan valid_to for prometheus and unknown plans.
When corrected in the templates earlier, I forgot to run the generate output script.
How to review
-------------
- Code review
---
> Fix billing plan valid_to for prom and unknown

- concourse/pipelines/create-cloudfoundry.yml
What
----
This bug means that when the job first runs there is no
'PLATFORM_PROMETHEUS_PASSWORD' to get. We seem to have been doing it manually
on the first run of new dev environments. 
How to review
-------------
Code review. 
You can delete the prometheus password from credhub, and confirm that this (running cf-deploy) doesn't fail and creates a dummy one.
Also check that the it doesn't break the current flow, i.e. if the password already exists, then it is used
---
> Create dummy password for prometheus to prevent cf-deploy failing

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are alerted that currrent required capacity is 133.
Also increasing Doppler instances to 69 (>= 50% of cells and needs to be divisible by 3).
Also increasing log-api instances to 36 (>= 50% of Doppler instances and needs to be divisible by 3).
How to review
-------------
- Code review
---
> Increase london cells to 138

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Release 0.1.31 includes a mitigation for CVE-2021-44228
How to review
-------------
I saw it go out ok in `dev02`
---
> Bump UAA to release 0.1.31

- config/buildpacks.yml
What
----
Bumped java buildpack to 4.44 to address CVE-2021-44228.
https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.44
How to review
-------------
Look at it, see it working on a dev instance?
---
> java buildpack: bump to 4.44

- manifests/cf-manifest/spec/manifest/instance_type_counts_in_envs_spec.rb
What
----
This test does not take into account diego-cells in isolation segments.
We need to scale Notify isolation segments for load-testing in anticipation of higher utilisation and not bottleneck on the infra
level.
This is required to pass https://github.com/alphagov/paas-cf/pull/2803
How to review
-------------
- Code review
---
> Comment out high infra instance count check

- manifests/cf-manifest/spec/manifest/instance_type_counts_in_envs_spec.rb
What
----
These test does not take into account diego-cells in isolation segments.
We need to scale Notify isolation segments for load-testing in anticipation of higher utilisation and not bottleneck on the infra level.
This is required to pass #2803
How to review
-------------
- Code review
---
> Comment out more high infra instance count check

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Updating uaa release to fix log4j by updating to log4j 2.16
See  https://lists.apache.org/thread/83y7dx5xvn3h5290q1twn16tltolv88f
for details
How to review
-------------
Code review
---
> Updating uaa release to fix log4j by updating to log4j 2.16

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Reverting to UAA 74.31 fork as 75.x is breaking email signup. Added log4j mitigations.
How to review
-------------
- Code review
- UAA dev release 0.0.1639589474 deployed in `schmie`
---
> Update UAA to local release 0.1.33

- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/isolation-segments/prod/govuk-notify-staging.yml
What
----
Notify asked us to increase the isolation segments to 36 for staging
Increasing other cells to roughly match
There were problems with doppler in the last load test, which is why
they are increased a bit more.
How to review
-------------
Make sure that the increases make sense.
---
> Increase notify staging isolation segments

- manifests/cf-manifest/env-specific/prod.yml
What
----
GOV.UK Notify are load testing for high anticipated traffic. We have seen the router instances under pressure as well as an increase in CC queued items possibly related to Notify's use of the autoscaler.
How to review
-------------
- CI
- Code review
---
> Scale router, scheduler, cc_workers in Ireland

- manifests/cf-manifest/operations.d/100-cf-update-vm-types.yml
- manifests/cloud-config/operations/use-spot-instances-in-dev.yml
- manifests/cloud-config/paas-cf-cloud-config.yml
- manifests/variables.yml
What
----
During load tests of GOV.UK Notify, we have found the logging backend to be potentially CPU (thread performance) bound. We are introducing a new `high_cpu_xlarge_vm_instance_type`, `high_cpu_xlarge` and assign it to log-api and doppler instances.
How to review
-------------
- Code review
- Change is currently rolling out to `schmie` dev env (overrode dev downscale to check new instance type).
---
> Change log-api, doppler vm_type to c5.xlarge

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
with fix for CVE-2021-45105 and CVE-2021-45046
What
----
Includes log4j 2.17.0 with fix for CVE-2021-45105 and CVE-2021-45046
How to review
-------------
:eyes: 
---
> uaa: bump to paas-uaa 0.1.34

- manifests/prometheus/operations.d/221-monitor-cf.yml
- manifests/prometheus/operations/change-vm-types-dev.yml
- manifests/prometheus/scripts/generate-manifest.sh
- manifests/prometheus/spec/operations/monitor_cf_spec.rb
What
----
It looks like the first envelopes dopplers start dropping are destined for prometheus' firehose instances. Perhaps because these appear to be built without the anti-backpressure measures later implementations of loggregator components were. These firehose instances do appear to spike up to ~70% cpu utilization under heavy load, so we should probably upgrade them similarly to how we've upgraded other doppler clients.
How to review
-------------
Look at `dev03` and be happy.
---
> prometheus: upgrade firehose instance group to high_cpu_xlarge

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Bumped the rds broker to 1.19 to roll out https://github.com/alphagov/paas-rds-broker/pull/147
How to review
-------------
Roll out to a dev env? Or maybe just trust the integration tests and staging?
---
> paas-rds-broker: bump to 1.19.0

- manifests/cloud-config/paas-cf-cloud-config.yml
https://www.pivotaltracker.com/story/show/180312173
What
----
Increased the size of the ephemeral disks attached to the diego cells, to give them more headroom and prevent them alerting us so frequently.
I've chosen to multiply the current sizes by 1.5x. Perhaps we could go further, but to me this seems like a good conservative place to start.
---
> diego cells: increase ephemeral disk size

- manifests/cf-manifest/isolation-segments/prod/govuk-notify-staging.yml
What
----
Deleted the `govuk-notify-staging` isolation segment from `prod` as per their request. Their load testing is complete for the time being.
Need to make sure they have migrated their space(s) away from this segment and restaged their apps before deploying this.
Not sure if we should also reduce the loggregator-related instance groups to match.
How to review
-------------
Not sure you can.
---
> prod isolation-segments: remove govuk-notify-staging

- terraform/cloudfoundry/variables.tf
What
----
We have ran out of assignable IPs on all subnets in eu-west-2c and expecting this to be the cause for "incompatible-network" errors when deploying new RDS instances.
This is likely not a complete fix to that, but we will require the additional subnets.
How to review
-------------
- Code review: check consistency
---
> Add 3 additional subnets for aws backing services

- terraform/eu-west-1.tfvars
- terraform/eu-west-2.tfvars
What
----
In #2828 we added additional subnets for the aws-backing-services to address a shortage of free IPs in eu-west-2c. As the CIDR blocks are not automatically mapped, this change is required as well
How to review
-------------
- Code review
- Optional testing in a dev env
---
> Map additional backing-service subnets to AZs

- terraform/cloudfoundry/outputs.tf
What
----
We added more subnets in #2828 and #2829 to make more IPs available to RDS in eu-west-2c, but did miss that we have to  extend the ip range for the security groups as well in order to make them accessible.
How to review
-------------
- Code review
- Test in dev env
---
> Extend the aws backing service ip range for sg

- concourse/scripts/set_security_groups_from_manifest.rb
- concourse/scripts/spec/security_groups_setter_spec.rb
What
----
It looks like cf's output has changed enough to make the regex not work correctly anymore, so use json from `cf curl` instead.
We could probably take some further steps to ensure this has gone through ok, e.g. try to read back the configuration after an attempted update, but we want to get this out.
How to review
-------------
Look at `dev01`.
---
> set_security_groups_from_manifest: don't scrape cf output, use cf curl

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Deploys a new release of `paas-cdn-broker` which implements the `GetInstance` endpoint
How to review
-------------
See [the PR for the change to the broker](https://github.com/alphagov/paas-cdn-broker/pull/50)
---
> Deploy release of paas-cdn-broker

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
https://www.pivotaltracker.com/story/show/180992703
Bumped cflinuxfs3 as it has quite a few security fixes.
https://github.com/cloudfoundry/cflinuxfs3/compare/0.268.0...0.272.0
How to review
-------------
Either roll it out to a dev env yourself or ~look at `dev02` and be happy.~ (now being used for cf-deployment 17.1.0 testing).
---
> cflinuxfs3: 0.268.0 -> 0.272.0

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
https://www.pivotaltracker.com/story/show/180992672
Upgrade cf-deployment, mainly to cover some USNs.
https://github.com/cloudfoundry/cf-deployment/compare/v17.0.0...v17.1.0
How to review
-------------
Deploy to a clean, non-slim dev environment. Or look at `dev02` where it's currently deployed.
---
> cf-deployment: 17.0.0 -> 17.1.0

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
The recent general dependencies bump appears to have prevented the cdn broker from authenticating with the CC. Revert it for now.
See https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/47 and thereon https://github.com/alphagov/paas-cdn-broker/pull/53
How to review
-------------
Look at `dev02` (and ignore the unrelated grafana failure)
---
> cdn-broker: 0.1.44 -> 0.1.45, reverting dependencies bump

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
The creation of temporary tables was causing triggers to be run that
attempted to lock tables to add permissions. This is unnecessary for
temporary tables, as they are scoped to a user.
This updates the broker to make the triggers no longer run.
How to review
-------------
Have a look in dev03 (where it is deployed) and see that it creating a temporary table is no longer verbose.
---
> Fix creation of temporary table locking issues

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are seeing the Cloud Controller queue length hit 10+ and have tenants
reporting issues with automated deploys ([ZenDesk ticket](https://govuk.zendesk.com/agent/tickets/4873890)).
How to review
-------------
- Code review
- Check user-impact dashboard for London (optional) 
---
> Bump number of CC worker and scheduler instances

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are getting close to the cell limit of 138, to get some head room
increase it to 144
.
Also increasing Doppler instances to 72 (>= 50% of cells and needs to be divisible by 3).
Keep log-api instances at 36 (>= 50% of Doppler instances and needs to be divisible by 3).
How to review
-------------
Check it looks sensible
---
> Increase london cells to 144

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are still seeing problems with automated deployments using terraform. The API queue is increasing.
The database does not show any particular problems, so to try and speed up the processing of the queue I am increasing the number of workers.
How to review
-------------
Make sure the number change makes sense.
---
> Increase cloud controller workers to 12 in prod-lon

- terraform/psn/versions.tf
What
----
Here's my naive attempt to fix psn trying to use a newer version of the aws provider. I'm assuming it should be like others in https://github.com/alphagov/paas-cf/commit/a6195f00fa571c2cdec95ea9a187a7493cdab108
How to review
-------------
I'm not sure how to test as it only seems to run in prod
---
> Pins aws version for psn

- platform-tests/broker-acceptance/cdn_broker_test.go
- platform-tests/broker-acceptance/init_test.go
Description:
---
- Adds a basic acceptance test for the CDN Broker which tests if a CDN service with a custom domain can be setup
How to review
-------------
- Code review.
- Deploy to dev01.
---
> 18107319- Add CDN Broker acceptance test

- concourse/pipelines/create-cloudfoundry.yml
Description:
- Acceptance tests for the CDN broker require the private_domain_creation feature flag to be enabled
- Prod and the other environments already have this enabled so this will ensure it is turned on when
Cloud Foundry is deployed
> 181073179 - Add enable private domain creation step to create Cloud Foundry pipeline

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations/local-dev-paas-admin-oauth-client.yml
- manifests/cf-manifest/scripts/generate-manifest.sh
What
----
We want to be able to point our local PaaS admin instances at a CloudFoundry
development environment, so that we don't have to push to CF all the time when
working on it.
WARNING: The OAuth client is configured insecurely. It has
1. static credentials
2. a callback URL of "localhost:3000".
3. full admin access.
This is not something that should be present outside of development
environments. A warning has been added to the generate manifest script.
This is related to the [the `paas-admin` PR for the quality of life enhancement](https://github.com/alphagov/paas-admin/pull/2357)
How to review
-------------
It has been deployed to `dev03` and demonstrated to work, so code review only.
This should have no impact on staging or prod.
---
🚨⚠️ Please do not merge this pull request via …
> [#179606510] Add an OAuth client for the API for use by PaaS admin local development

- concourse/pipelines/create-cloudfoundry.yml
What
----
The acceptance tests for the new billing require the database to be setup
before they work.
This just moves the acceptance tests after the db has been setup.
How to review
-------------
Code review
---
> Run acceptance tests after db has been setup

- manifests/cf-manifest/isolation-segments/prod/govuk-notify-production.yml
What
----
The govuk-notify-production is being underutilised so they can be scaled down
How to review (also questions)
-------------
- any reasons why this shouldn't be done? I've double checked memory and cpu usage
- do they need to do anything before this change is applied?
- do we need to scale back instances? https://github.com/alphagov/paas-cf/pull/2803/commits/bdf63a684d49b172953db4dbfa87ca8eb312ebc8
---
> Decrease notify cells

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
0.1.46 contains a fix for a bug in the GetInstance endpoint.
See https://github.com/alphagov/paas-cdn-broker/pull/54.
How to review
-------------
I'll run it down a dev env to make sure it's not totally broken
See that [it was successfully deployed](https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/188) and [it was successfully enabled](https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/post-deploy/builds/128)
---
> Deploy CDN broker 0.1.46

- concourse/scripts/check-certificates.rb
What
----
Change the error message displayed by the `check-certificates`(`-after-rotation`) job when certificates are expiring very soon.
The previous error message was vague and might lead the operator to retry just the rotate-certs job, which it turns out would be a bad thing to do.
How to review
-------------
:eyes: 
---
> check-certificates: improve error message for soon-expiring certs

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
Bumped `cflinuxfs3` and the bionic stemcells to keep up with the latest round of security advisories.
How to review
-------------
~Don't yet.~ See it successfully deployed to `dev03` with the continuity tests having passed.
---
> cflinuxfs3: 0.272.0 -> 0.275.0, bionic stemcells: 1.54 -> 1.67

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
https://www.pivotaltracker.com/story/show/181594743
Bump cflinuxfs3 from 0.275.0 to 0.278.0, addressing multiple CVEs
https://github.com/cloudfoundry/cflinuxfs3/compare/0.275.0...0.278.0
How to review
-------------
Either deploy to a dev env yourself or look at `dev01` right now.
---
> cflinuxfs3: 0.275.0 -> 0.278.0

- tools/aws_redis_update_manager/lib/aws_redis_update_manager.rb
- tools/aws_redis_update_manager/lib/tenant_notifier.rb
What
----
We don't want the script to fail when it trips over one email address.
Instead, continue and generate a list of failed attempts at the end.
How to review
-------------
Code review
---
> Carry on sending emails even if one fails

- terraform/cloudfoundry/broker_alb.tf
- terraform/cloudfoundry/cdn_broker.tf
- terraform/cloudfoundry/elasticache_broker.tf
- terraform/cloudfoundry/elbs.tf
- terraform/cloudfoundry/lbs.tf
- terraform/cloudfoundry/prometheus.tf
- terraform/cloudfoundry/rds_broker.tf
- terraform/cloudfoundry/s3_broker.tf
- terraform/cloudfoundry/sqs_broker.tf
- terraform/globals.tf
What
----
Upgrades from to 'ELBSecurityPolicy-TLS-1-2-2017-01' to 'ELBSecurityPolicy-TLS-1-2-Ext-2018-06' for ALB/NLB and 'ELBSecurityPolicy-TLS-1-2-2017-01' for classic load balancers. As it stands today (2022-02-23), AWS does not have an ELB security policy which supports TLS 1.3 on Application Load Balancers. One is avaibale for Network Load Balancers, but in the interests of consistency we will only use it when ALBs have the same support.
The policy names for ALB/NLBs and classic load balancers have diverged in AWS, so we've had to diverge the two properties here too.
The presence of the 'SslPolicy' field on the 'ModifyListener' action of AWS' Elastic Load Balancing API [1] suggests that we will be able to modify the policy without downtime. Equally, the AWS Terraform provider …
> [#180965549] Upgrades the TLS cipher suite we use on load balancers

- terraform/globals.tf
What
----
Remove old IP address range as published in GDS update
How to review
-------------
Check that the list matches https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/working-at-the-white-chapel-building/gds-internal-it/gds-internal-it-network-public-ip-addresses
---
> Update ip addresses

- concourse/pipelines/create-cloudfoundry.yml
What
----
The `deploy-cloudwatch-exporter` task of the `prometheus-deploy` job expects the `logit-syslog-drain` service to exist in the `admin` / `monitoring` space, making no effort to create it if it doesn't.
Looks like the place this is normally created is in `deploy-paas-metrics`, which comes _after_ it in the pipeline, which is not ideal. So copy the existing pattern to ensure it exists before attempting to deploy.
How to review
-------------
Technically you'd have to destroy a dev env and recreate it from scratch to see this in action. But you could just deploy to an existing dev env and check it doesn't break everything.
Who can review
------------
Not @risicle or @nimalank7 as we are both complicit.
---
> create-cloudfoundry: ensure logit-syslog-drain exists before creating cloudwatch exporter

- manifests/cf-manifest/operations.d/000-cf-deployment-19-preemptively-add-log-cache.yml
- manifests/cf-manifest/operations.d/100-cf-update-vm-types.yml
- manifests/cf-manifest/operations.d/365-log-cache.yml
- manifests/cf-manifest/operations.d/800-set-vcap-password.yml
What
----
https://www.pivotaltracker.com/story/show/181415115
This lays the ground for cf-deployment 19.0.0 to go out.
cf-deployment >=18 separates the `log-cache` from the `doppler` instances. It helps if all the cluster's instances are aware of the log-cache bosh dns alias before the full deployment goes out.
We're going for the same number of instances and vm types as the existing dopplers so we know we're not underprovisioning. Once we've observed production load using this we can decide what to downscale and how.
Doing the scaling & sizing in this initial deployment mostly so the tests don't whine at us about something they see as a misconfiguration.
How to review
-------------
Roll out to a (**non-slim**) dev env and watch for any downtime?
---
🚨⚠️ Please do not merge this pull …
> cf-depoyment v19 precursor: add an initial simplified log-cache instance group

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
https://www.pivotaltracker.com/story/show/181770492
Addresses CVE-2022-22965 though a Spring bump.
How to review
-------------
Either deploy to a dev env and test inviting a new user manually, or look at `dev01` where (I think) it's still running this.
---
> paas-uaa: 0.1.34 -> 0.1.35

- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/env-specific/stg-lon.yml
- manifests/cf-manifest/operations.d/365-log-cache.yml
- manifests/cf-manifest/spec/manifest/env_spec.rb
What
----
https://www.pivotaltracker.com/story/show/181832139
We deployed cf-deployment 19 with surplus `log_cache` instances to avoid the possibility of underprovisioning with doing a complex release. Wisdom from cf slack suggests that we should be able to halve the number of log_cache instances now, and our metrics seem to support this.
How to review
-------------
This really only makes changes to production so I'm not sure it's sensibly possible.
---
> log-cache instances: halve number in prod and prod-lon

- terraform/cloudfoundry/smtp.tf
What
----
An IAM access key's `ses_smtp_password_v4` appears to be generated using the region of the iam resource's provider, which is not necessarily the region we're going to use it in. This causes auth failures when alertmanager in eu-west-2 tries to send emails via our SES in eu-west-1.
How to review
-------------
Have tested this in the `schmie` dev env (being eu-west-2), and it successfully stops the smtp auth failure messages which have also been seen in `prod-lon`. Haven't managed to get any actual emails through yet, but dev isn't really set up for that.
---
> terraform: add dedicated provider alias for ses smtp

- config/logit/30_various_timestamps.conf
- config/logit/output/generated_logit_filters.conf
- scripts/generate_logit_filters.sh
What
----
From a trawl of a month's worth of logs, these appear to be the fields already present that contain earlier, more accurate, host-generated timestamps. Some are ISO timestamps, some are unix epoch floats.
The ISO timestamps seem to be interpreted at some point after the logstash filters (?) (though not set to be the `@timestamp` value). The unix epoch values are ingested as strings, so not sortable.
How to review
-------------
Think we need to run `make logit-filters` and use the result to populate one of our logit stacks logstash configurations and testing it out.
---
> logit lostash filters: interpret various more accurate timestamp fields

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
What
----
Set autoscaler bionic stemcell to 1.76  as part of CVE mitigation.
How to review
-------------
- Code review
- Test in dev env
---
> [181943509] Set autoscaler bionic stemcell to 1.76

- .github/workflows/test_on_pr.yml
- manifests/prometheus/alerts.d/concourse-check-certificates-errors.yml
- manifests/prometheus/alerts.d/concourse-check-certificates-failures.yml
- manifests/prometheus/spec/alerts/app-autoscaler-cpu.test.yml
- manifests/prometheus/spec/alerts/bosh-high-cpu-utilisation.test.yml
- manifests/prometheus/spec/alerts/cloud-controller-unregistry.test.yml
- manifests/prometheus/spec/alerts/cloudfront_tls_certificates_expiry.test.yml
- manifests/prometheus/spec/alerts/concourse-smoketests-errors.test.yml
- manifests/prometheus/spec/alerts/concourse-smoketests-failures.test.yml
- manifests/prometheus/spec/alerts/diego_cell_available_memory.test.yml
- manifests/prometheus/spec/alerts/diego_cell_rep_container_capacity.test.yml
- manifests/prometheus/spec/alerts/diego_cell_rep_memory_capacity.test..yml
- manifests/prometheus/spec/alerts/doppler-dropped-envelopes.test.yml
- manifests/prometheus/spec/alerts/gorouter-latency.test.yml
- manifests/prometheus/spec/alerts/router_total_routes.test.yml
- manifests/prometheus/spec/alerts/uaa-5xx-errors.test.yml
What
----
I started writing up a ticket for this (https://www.pivotaltracker.com/story/show/182035914) but decided to just do it as I'd already done most of the work anyway.
Previous expression would substitute all missing values with 0, which would get picked up as resets by `increase()`, meaning a spotty value would get counted many times. Instead only use 0 when we haven't seen any values in the last 12h otherwise use `max_over_time` from the last 12h.
Ideally we'd use `last_over_time`, but that's only available from prometheus 2.26 onwards, which we don't quite have yet.
How to review
-------------
Deploy to a dev env, see perhaps see if alertmanager alerts appear following repeated failures? Could take multiple days. Could otherwise just suck it and see.
---
🚨⚠️ Please do not merge …
> alerts: improve expression for certificate check failure alerts

- scripts/cleanup_leftover_test_orgs.sh
What
----
Our continuous smoke tests, acceptance tests and the like
create organizations in CF, and provision backing services.
Sometimes the tests fail and the resources don't get cleaned
up. This script tidies up.
How to review
-------------
1. Code review
2. Try it out in `dev02`
---
> Adds a useful script for cleaning up unused test orgs

- manifests/prometheus/alerts.d/cloudfront_tls_certificates_expiry.yml
- manifests/prometheus/spec/alerts/cloudfront_tls_certificates_expiry.test.yml
What
----
When certs expire, the days until expiring is zero
rather than a negative number. We should not get alerted
for certs that have 0 days left
How to review
-------------
code review
---
> Increase lower limit for expiry days to be greater than zero

- platform-tests/broker-acceptance/common_service_test.go
- platform-tests/example-apps/healthcheck/main.go
- platform-tests/example-apps/healthcheck/opensearch.go
- scripts/audit-services.rb
What
----
Reworked the pipelines to refer to and access Opensearch instances, not elasticsearch
How to review
-------------
- Code Review
- Check that the pipelines run successfully (https://deployer.dev01.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/pipeline-lock/builds/254)
---
> [#181652216] Update pipelines to test against Opensearch

- concourse/pipelines/create-cloudfoundry.yml
- concourse/tasks/check-billing-comparison-with-cf.yml
What
----
We are introducing a test comparing the billing data on running services to the cloud foundry data on running services in order to detect billing collector failures and database issues.
How to review
-------------
- Code review
- Check output of [the test](https://github.com/alphagov/paas-billing/pull/145) manually against prod data and make sure they are not failing (can be treated as optional as we have not attached alerts to this, yet).
- Deploy branch and check the test is working (currently in dev03).
---
> Add billing comparison tests

- manifests/prometheus/alerts.d/watchdog.yml
- manifests/prometheus/operations.d/310-alertmanager-routes.yml
- scripts/upload-secrets/upload-cronitor-secrets.rb
What
----
Configure prometheus to call out to cronitor every 5 minutes, via a persistent alarm.
As this alarm is generated from Prometheus, it is essentially an e2e test of whether Prometheus is working.
How to review
-------------
* Run this down a dev pipeline (or just check that dev03 has it deployed)
* Check that the healthcheck in Cronitor is working (link in pivotal)
This will require the cronitor secrets to be rolled out first for each environment, otherwise the deploy will fail. See the other PR linked in Pivotal.
---
> [#181945547] Add prometheus watchdog

- config/logit/20_custom_cf_filters.conf
- config/logit/output/generated_logit_filters.conf
What
----
X-forwarded-for field in kibana is a string of comma separated ips. We want to be able to easily filter by ip. This PR converts the field into an array of ips
How to review
-------------
- Code review
- [Check that you can filter this field by individual ips ](https://kibana.logit.io/s/c7358874-2b30-44a6-8271-554ad3996e50/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))&_a=(columns:!(gorouter.header.x_forwarded_for),filters:!(('$state':(store:appState),exists:(field:gorouter.header.x_forwarded_for),meta:(alias:!n,disabled:!f,index:'logstash-*',key:gorouter.header.x_forwarded_for,negate:!f,type:exists,value:exists))),index:'logstash-*',interval:auto,query:(match_all:()),sort:!('@timestamp',desc)))
After merging …
> Split ips in x-forwarded-for

- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/720-cdn-broker.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/operations.d/750-s3-broker.yml
- manifests/cf-manifest/operations.d/760-sqs-broker.yml
What
----
https://www.pivotaltracker.com/story/show/181929453
This incorporates minor bumps of `rds-broker`, `cdn-broker`, `elasticache-broker`, `s3-broker` & `sqs-broker` bringing them all up to golang 1.18.0-using versions.
How to review
-------------
Deploy to dev & see tests pass?
---
> Bump various components to golang 1.18.0-using versions

- manifests/cf-manifest/env-specific/prod.yml
What
----
We seem to be levelling around 20 cells' usage in `prod` - 36 cells is a waste. Haven't changed any of the rest of the infra to match due to the presence of Notify.
But I do note we have over twice as many router instances in `prod` as we do in `prod-lon` and only half the cells.
How to review
-------------
:eyes: 
---
> prod: scale down to 24 cell_instances

- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
Description:
- Points to upstream CloudFoundry UAA 75.1.0
- Points to release 0.1.33 of the UAA customization bosh release
Point the UAA to CloudFoundry version to test what breaks in our customized UAA PaaS configuration
How to review
-------------
See Pivotal story for fuller discussion on how to review
---
> 180444788 - Unfork UAA

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations.d/720-cdn-broker.yml
- platform-tests/broker-acceptance/cdn_broker_test.go
- platform-tests/broker-acceptance/init_test.go
What
----
https://www.pivotaltracker.com/story/show/181233950
Depends on https://github.com/alphagov/paas-cdn-broker/pull/56
See individual commit comments for details, but this firstly fixes the provisioning of the cdn-broker's uaa secret, _then_ bumps our cdn-broker to the result of https://github.com/alphagov/paas-cdn-broker/pull/56 (which should add domain ownership checking and better error handling), _then_ adds tests for cf domain existence and ownership to the custom-broker-acceptance-tests.
How to review
-------------
Deploy to a dev env. Ensure custom-broker-acceptance-tests pass. Maybe even run `rotate-cloudfoundry-credentials` and check a re-deploy succeeds and tests pass again.
---
> cdn-broker: fix cf domain checking among other things

- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Now that we've unforked our uaa dependency we're potentially vulnerable to breakage on uaa updates in areas that aren't covered by automated testing.
This is possible because of the tight coupling of our uaa customization, problems with which prevented us from unforking for so long in the first place.
This is a precursor to the cf-deployment 21.x upgrade (https://www.pivotaltracker.com/story/show/182344728), which will be the first time in ages we've done a "routine" uaa upgrade.
How to review
-------------
Try overriding the version in the manifest, see if the error message is sensible?
---
> manifest spec: reintroduce uaa version checks outlining necessary testing

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
A precursor to the cf-deployment 21.x upgrade in https://www.pivotaltracker.com/story/show/182344728, these include some security fixes we've fallen a little behind on and it would be good to get these out quickly rather than let them get held up by any complications #2919 may encounter
How to review
-------------
Deploy to a dev env or just look at `dev02` now-ish.
---
> cflinuxfs3: 0.299.0 -> 0.307.0, ubuntu-bionic stemcells: 1.84 -> 1.90

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
What
----
Bumped autoscaler's stemcell to match the cf stemcells bumped in https://github.com/alphagov/paas-cf/pull/2920
How to review
-------------
:eyes: https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/app-autoscaler-acceptance-tests/builds/137
---
> app-autoscaler: bionic stemcell: 1.84 -> 1.90

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
`prod-lon` has been complaining about `DiegoCellRepMemoryCapacity` for about a week. Give it what it wants.
How to review
-------------
:eyes: 
---
> prod-lon: bump diego-cells to 141

- manifests/prometheus/operations.d/100-update-vm-types.yml
- manifests/prometheus/spec/operations/update_vm_types_spec.rb
What
----
The previous instance type gave the machine 8gb RAM, which was proving not to be enough and caused Prometheus to dip in to its swap regularly. The `xlarge` instance type will give it 16gb RAM.
How to review
-------------
1. Check I used the right instance type name from the cloud config
---
> [#182177000] Use xlarge instance type for platform Prometheus machines

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/009-disable-dynamic-asgs-UPSTREAM.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
- platform-tests/acceptance/tls_version_test.go
- platform-tests/upstream/run_acceptance_tests.sh
What
----
https://www.pivotaltracker.com/story/show/182344728
Bump cf-deployment to v21.3.0.
More details in individual commit messages, but this also switches to dynamic ASGs and re-enables the acceptance test for them.
Deploying this on a clean non-slim deployment succeeds with only the `api-availability-tests` failing at 99.82%. However, all the failures return a sensible and reasonable error message so I feel ok about it (see https://deployer.dev03.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/api-availability-tests/builds/88)
Manual UAA tests pass.
How to review
-------------
Deploy to a clean, non-slim dev env.
---
> cf-deployment: v20.2.0 -> v21.3.0

- tools/buildpacks/email.tmpl
What
----
The template for the buildpack email generator was outputting Markdown that
caused the release notes links to turned in to a header:
```
[link](url)
----
```
Instead of
```
[link](url)
---
```
How to review
-------------
Run the script and check the Markdown output looks OK when rendered.
---
> Improve Markdown output for buildpack emails generator

- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
What
----
https://www.pivotaltracker.com/story/show/182769592
This is as opposed to setting a size-based retention policy, which would cause us to stop getting alerts when we're no longer able to retain our requested 450d of metrics.
Looking back in history the "450d" comes from a desire to have more than a year's worth of metrics available to us for analysis.
How to review
-------------
:eyes: 
---
> external prometheus: increase prometheus_disk_size to 250G in prod & prod-lon

- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/spec/manifest/base_properties_spec.rb
What
----
Bump UAA release version and remove test that checks for the existence of sign-up link on the admin login page as we're [removing](https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/30) it 
How to review
-------------
tests still pass
check tarball version and sha against https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-customized-release/jobs/build-final-release/builds/3
---
> Update UAA release and remove test for signup link on paas-admin login page

- manifests/cf-manifest/spec/integration/integration_spec.rb
- manifests/cloud-config/paas-cf-cloud-config.yml
- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
- manifests/prometheus/env-specific/stg-lon.yml
- manifests/prometheus/scripts/generate-manifest.sh
- manifests/prometheus/spec/manifest_validation_spec.rb
- manifests/prometheus/spec/support/manifest_helpers.rb
What
----
https://www.pivotaltracker.com/story/show/182769592
Firstly this changes the "generic manifest tests" (called "integration" for the cf manifest) to run once for each env, because some important values e.g. disk types are affected by the env config and we want to make sure they're all valid.
Secondly this changes the way the `prometheus` deployment's manifest is generated. Previously we were prioritizing env-specific variables from the top-level/"cf" deployment over those specified in the prometheus deployment's env-specific vars. This meant that the `prometheus_disk_size` settings we had set there were never actually being used. Instead the "external" prometheus' was using the setting intended for just the "internal" prometheus.
Set the external prometheus `prometheus_disk_size` …
> fix prometheus manifest generation, bump disk sizes

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
This is to continue discovering more about the performance characteristics of our shared infrastructure.
How to review
-------------
:eyes: 
---
> prod-lon: reduce number of log-api and log-cache instances to 27

- manifests/cf-manifest/env-specific/prod.yml
What
----
Both dopplers and log_api instances not yet showing adverse effects of downscaling.
How to review
-------------
:eyes: 
---
> prod: reduce number of dopplers to 24, log_api instances to 15

- concourse/spec/vars_files_spec.rb
What
----
Adds a simple test that compares the file modification time of `./.gpg-id` to
that of `./concourse/vars-files/gpg-keys.yml`. In theory, we should never
updated `.gpg-id` without updating `gpg-keys.yml`, and so we should always see
the latters file modification time is after the formers.
Test failure looks like
```
1) vars files gpg-keys.yml was updated after a change to .gpg-id
Failure/Error: expect(gpg_keys_mod_time).to be >= gpg_id_mod_time
expected: >= 2022-07-27 10:43:07.433614004 +0000
got:    2022-07-27 10:41:41.427827006 +0000
```
How to review
-------------
Do you reckon this will cover us in the future?
---
> Detect when the Concourse GPG keys file hasn't been updated

- manifests/prometheus/dashboards.d/bosh-jobs-heatmaps.json
- manifests/prometheus/dashboards.d/forwarder-agents.json
- manifests/prometheus/dashboards.d/grootfs.json
- manifests/prometheus/dashboards.d/log-cache.json
- manifests/prometheus/dashboards.d/reverse-log-proxy.json
- manifests/prometheus/dashboards.d/syslog-agents.json
- manifests/prometheus/dashboards.d/trafficcontroller.json
What
----
Some newly created, some have been kicking around for a while as ad-hoc dashboards.
Related to https://www.pivotaltracker.com/story/show/182790768
How to review
-------------
See grafana on dev02 where these dashboards have been populated via the pipeline. e.g. https://grafana-1.dev02.dev.cloudpipeline.digital/d/log-cache/log-cache?orgId=1
---
> grafana: add several new dashboards

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
- Upgrade bionic-stemcell to 1.91
- Upgrade cflinuxfs3 to 0.312
The cflinuxfs3 upgrade is not technically required by CVE, but looks to contain useful fixes.
How to review
-------------
- Code review - any typos
- Deploy to dev environment (edit: [deployed Jul 29th](https://deployer.dev01.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/232.1) to `dev01`). 
---
> [#182852599] Address CVE 2022-2068

- concourse/pipelines/create-cloudfoundry.yml
Description:
- GOPATH is already defined in the docker image so no need to define it here
- Fixes the error as "$PWD" is not in the PATH
> 182427769-Fix-GOPATH-error

- manifests/cf-manifest/operations.d/270-cf-enable-space-developer-self-service-network-policies.yml
What
----
We have a tenant making heavy use of private networking for their Prometheus
metric scraping, and they have hit the 100 policies per app limit. What they're
doing is smart and we don't want to discourage it, so the sensible thing to do
is raise the limit. The number we're using is pretty arbitrary anyway.
We shouldn't expect any adverse affects from this. Most other tenants make very
limited use of private networking policies, and their implementation can very
easily handle thousands per app (based on IPTables IIRC).
How to review
-------------
Agree with the change? Different number?
---
> Raise maximum number of CF network policies per app source to 200

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Scale diego cells in London to 144.
Memory pressure / desired cell count is creeping up to current value of 141.
How to review
-------------
Code review
---
> Scale diego cells in London to 144

- manifests/cf-manifest/operations.d/100-cf-update-vm-types.yml
- manifests/cloud-config/operations/use-spot-instances-in-dev.yml
- manifests/cloud-config/paas-cf-cloud-config.yml
- manifests/variables.yml
What
----
https://www.pivotaltracker.com/story/show/182790768
Doppler doesn't use the memory we give it and log-cache could use more if we gave it. Following this we might be able to horizontally downscale log-cache a little further, particularly if we increased the percentage of memory it was allowed to use for logs.
Following some stress-testing on dev02, it was possible to push `c5.large` dopplers to receiving 8k messages/sec each without their memory usage going above 15%. This is well above what our current doppler load is, so I'm happy this halving of the dopplers' memory will have no ill effects.
As for the log-cache instances, that is effectively an _upgrade_, doubling their memory.
So all in all I'm quite confident in this change not having immediate ill effects.
How to review …
> loggregator instances: switch doppler and log cache to more appropriate instance types

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- platform-tests/upstream/run_acceptance_tests.sh
Description:
- GOPATH is already set in the base docker images and doesn't need to be set again to PWD
- Go 1.18 always has -d enabled so it is redundant to include it here
What
----
How to review
-------------
---
> 181929453 - Remove unnecessary GOPATH

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/operations.d/235-log-cache-tuning.yml
What
----
https://www.pivotaltracker.com/story/show/182790768
First we push the `memory_limit_percent` another 5%, which it looks like it can afford.
Then we adjust the instance counts based on what the metrics look like after the instance type switch.
How to review
-------------
:eyes: 
---
> log-cache: set `memory_limit_percent` to 70, adjust instance counts

- manifests/variables.yml
What
----
The current underbidding we do causes spot interruption, which is not handled well by bosh and is quite disruptive to the dev process.
A longer term alternative to this would be to add an operator job to concourse to `bosh recreate --fix` any missing instances which a dev could run just before they start using an env. Then we could perhaps reduce these numbers by ~25%.
But for now we just want to get some work done.
How to review
-------------
:eyes: and either trust or go and double check the prices yourself.
---
> spot bid prices: set these to the ireland ondemand prices

- terraform/az-management/README.md
- terraform/az-management/main.tf
What
----
https://www.pivotaltracker.com/story/show/182772579
This covers RDS & Elasticache instances - these won't automatically handle endpoints being unreachable, so disconnecting their subnets would just result in any non-HA (or HA-but-not-failed-over) service instances being cut off from their apps.
This was @cadmiumcat 's work mostly, I just tested it & fixed a syntax change.
How to review
-------------
Well, I'll describe how I tested it, you can decide to what extent you want to do similar:
- Deploy this to a dev env.
- Create a non-ha database in cf
- Look at the AWS console to see which AZ it was placed in. If it gets put in the same AZ as your rds broker (or elasticache broker if you've chosen an elasticache db), try again. Slim dev envs only have one of each broker and if you …
> az-management: exclude backing services when disabling subnets

- manifests/cf-manifest/operations.d/235-log-cache-tuning.yml
What
----
On reflection, leaving log-caches with a little more headroom for when e.g. their siblings disappear is probably a good thing.
Yesterday's difficult rollout resulted in instances going into swap briefly.
How to review
-------------
:eyes: 
---
> Revert "log-cache: set memory_limit_percent to 70"

- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
What
----
- Uses the latest release of the elasticache-broker-release.
- Sets multiAZ to "enabled" by default for highly available plans
How to review
-------------
Check that the tag in the release corresponds to the one created in https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/elasticache-broker-release/jobs/build-final-release/builds/3
This has been tested in a dev environment already
---
> 182773204 enable multi az

- platform-tests/broker-acceptance/s3_broker_test.go
Description:
- Ginkgo has deprecated using done for asynchronous tests
- Functionality has been replaced by asynchronous matchers in the test
What
----
How to review
-------------
Check against https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-broker-acceptance-tests/builds/140
---
> 182427769 - Remove deprecated Ginkgo V1 functionality

- manifests/app-autoscaler/operations.d/001-release.yml
What
----
Update autoscaler to 6.1.0 #2967
We have a tenant report that all apps managed by the autoscaler have scaled to max and we reached the Diego max memory limit in London as well.
How to review
-------------
- code review
---
> Revert "Update autoscaler to 6.1.0"

- Makefile
What
----
Having these set to 360 (i.e. having a cert rotation happen every 5 days) is too disruptive to the development process and may even make dev testing _more_ unreliable, as we will frequently be testing with setups that roll more nodes on a deploy than production will.
How to review
-------------
:eyes: :brain: 
---
> dev environments: set CA_ROTATION_EXPIRY_DAYS to 345

- platform-tests/example-apps/app-autoscaler-cpu-usage/main.go
What
----
This is an app that is deployed with our autoscaler to continuously exercise it by spinning for a period of time and then sleeping for a period of time. But the way it's written it's a little flaky and quirky. If we're going to set up an alert to ensure this is always behaving correctly (as appears to have been the original intention), it would be nice to be able to eliminate any of these strangenesses. The goal here is to, as much as possible, have all instances of this app perform their spinning at the same time (two instances "out of phase" will result in an approximately constant average cpu usage, which won't result in the desired scale-up-scale-down behaviour). Using this technique, that is much more reliable.
Before:
After (ignore gap while prometheus was being …
> `app-autoscaler-cpu-usage` example app: revamp for better reliability, simplicity

- manifests/cf-manifest/operations.d/320-cc-increase-max-app-disk.yml
What
----
One of our users requires extra disk space to be able to temporarily store and scan file uploads. This increases it to 8gb
How to review
-------------
Deploy to dev environment, check that you can scale an app to use more than 6gb of disk space, e.g. `cf scale paas-admin -k 8GB`
> Raise maximum disk space an app can request to 8gb

- concourse/pipelines/create-cloudfoundry.yml
What
----
Postgres 10 is being removed by AWS in the first half of 2023. We need to get people to migrate away, but some folks are still using a set of database plans that we deprecated, and they can't do anything until the plan is re-enabled for them.
How to review
-------------
I've deployed it to [dev02](https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/289) check that you can create a service using the *-10-old postgres plans
---
> Re-enable *-10-old postgres plan

- config/service-brokers/csls-splunk/prod-config.json
- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
We have removed these orgs, so we no longer need them in the list
How to review
-------------
Check that the correct orgs are being removed
---
> Remove orgs from the allowed csls-splunk list

- concourse/pipelines/create-cloudfoundry.yml
- manifests/prometheus/alerts.d/app-autoscaler-is-not-scaling.yml
- manifests/prometheus/spec/alerts/app-autoscaler-cpu.test.yml
- platform-tests/example-apps/app-autoscaler-cpu-usage/manifest.yml
What
----
https://www.pivotaltracker.com/story/show/183165018
Here we add a multi-process continuously autoscaling test app to catch issue affecting only such apps. We leave in place (but rename) the single-process one and ensure there is an alert for each.
Also reduce the memory & disk allocation for each app, as each actually uses <16M, this is still generous.
How to review
-------------
How I did it:
- deploy to a dev env
- see both new apps running in grafana, scaling up and down
- look at env's alertmanager, see no relevant alert
- detach one of the apps' scaling policies, e.g. `cf dasp app-autoscaler-cpu-usage-multiproc`
- do something else for a couple of hours
- check alertmanager for a relevant alert
---
> app-autoscaler-cpu-usage test app: add `app-autoscaler-cpu-usage-multiproc`

- manifests/cf-manifest/operations.d/750-s3-broker.yml
What
----
As per the [Tracker story](https://www.pivotaltracker.com/n/projects/1275640/stories/183264581) this integrates [this s3-broker PR](https://github.com/alphagov/paas-s3-broker/pull/28) improving unbinding errors and test coverage.
How to review
-------------
- CI is happy
- Data matches [the build](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/s3-broker-release/jobs/build-final-release/builds/3#L6308db9d:37)
Acceptance tests for the code deployed by this passed [here](https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-broker-acceptance-tests/builds/153)
---
> Update s3-broker-boshrelease to 1.17, unbind improvements

- concourse/pipelines/create-cloudfoundry.yml
What
----
Pin Ginkgo CLI version to the one used in packages. Using latest has caused acceptance tests to fail with a version mismatch.
How to review
-------------
- Double-check in a dev env that deploy-paas-metrics/acceptance-tests pass
---
> Pin Ginkgo CLI version to the one used in packages

- manifests/prometheus/env-specific/prod-lon.yml
What
----
We've increased the aws-enforced limit in eu-west-2 to 1500 for both of these values.
How to review
-------------
:eyes: 
---
> alerts: reflect bumped elasticache resource limits in prod-lon

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/operations/scale-down-dev.yml
- manifests/cf-manifest/spec/manifest/certificates_spec.rb
- manifests/cf-manifest/spec/manifest/dev_scaling_spec.rb
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
* Upgrade CF to `21.11.0`
* Use latest versions of docker tools (fixes for the new need for CF v3 api, so update CF CLI)
* Increase number of Diego cells in dev from 2 to 3 - this should kill off some test failures while developing in future
How to review
-------------
Check it's gone down a dev environment 'greenly' (see `dev01`)
Who can review
--------------
Mob review with @dark5un @corlettb @jackjoy-gds 
---
> #183452476 Update cf-deployment to 21.11.0

- concourse/pipelines/create-cloudfoundry.yml
What
----
https://www.pivotaltracker.com/story/show/183510169
These now appear to be reliable enough on staging and production that this shouldn't be a problem.
How to review
-------------
Either deploy to your own dev env and observe the pipeline running or just look at dev02, which may still be running this branch.
---
> create-cloudfoundry: make `app-autoscaler-acceptance-tests` mandatory to continue

- .github/workflows/test_on_pr.yml
- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- terraform/.terraform.lock.hcl
- terraform/versions.tf
What
----
- Upgrade terraform version to 1.3.3
- Upgrade providers. ~~Pingdom now uses api-token~~
How to review
-------------
- Check that the [pipeline](https://deployer.dev03.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/pipeline-lock/builds/19) is green and happy 
- ~~Does pingdom still work?~~
---
> Upgrade terraform

- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
We've had a request to enable splunk for this org. We need to add it to the allow list too
How to review
-------------
Name of the org matches `cs-conclave-evidence-locker`?
---
> Allow new org so that they can use splunk

- concourse/pipelines/destroy-cloudfoundry.yml
- terraform/cloudfoundry/buckets.tf
- terraform/cloudfoundry/dev.tfvars
- terraform/cloudfoundry/prod.tfvars
- terraform/cloudfoundry/staging.tfvars
- terraform/cloudfoundry/variables.tf
What
----
Fixes the cloudfoundry destroy pipeline so that manual removals are not necessary.
- Set the force_destroy option in dev environments to the cloud foundry s3 buckets.
- Remove the auditor postgres db before the bosh destroy happens.
How to review
-------------
A successful log file of a full destroy can be seen [here](https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/destroy-cloudfoundry/jobs/delete-deployment/builds/6#L635a75f6:1) and [here](https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/destroy-cloudfoundry/jobs/terraform-destroy/builds/7#L635a76f2:1).
Ensure you are happy with the protection of non-dev buckets. 
---
> Fix cloudfoundry destroy pipeline.

- concourse/pipelines/create-cloudfoundry.yml
What
----
We currently have a timing issue between acceptance tests and custom acceptance tests. These tests run at the same time. The acceptance test will add buildpacks and the custom acceptance tests checks for no extra build packs.
An example of this failure can be seen [here](https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-acceptance-tests/builds/2#L635940ea:46).
This fix moves the check for the build packs from the custom acceptance tests to the post-deploy job. 
How to review
-------------
Modified pipeline builds can be seen [here](https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/post-deploy/builds/7#L635a7f5e:1)
There are many different ways to fix this issue. Ensure you are happy …
> Fix timing issue between acceptance tests and custom acceptance tests

- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
What
----
Bump the elasticache service broker to allow accessing maintenance and backup windows.
How to review
-------------
* Check the bosh release is the version  created after merging of alphagov/paas-elasticache-broker-boshrelease#18
Currently deployed to `dev03`.
in org/space `tnw / tw-test` I have deployed two redis instances. One with a `preferred_maintentance_window` set at provision-time and one without. Please ensure that:
* the instance metadata can be retrieved with the `cf service xxx --params`
* the maintenance window can be updated via `cf update-service xxx -c '{"preferred_maintenance_window":"mon:00:03-mon:01:42"}'`
---
> [#183047939] Bump elasticache service broker

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
The new version of the rds broker includes a fix for this [issue](https://www.pivotaltracker.com/story/show/183378729).
How to review
-------------
This branch has been deployed to dev-04. See [link](https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/pipeline-lock/builds/15)
---
> Release new version of the rds broker (1.38.0)

- manifests/prometheus/dashboards.d/cell-memory.json
What
----
https://www.pivotaltracker.com/story/show/183164959
Added a dashboard showing information about how much available memory our cells have across the instance group.
How to review
-------------
Deploy to a dev env and look for the dashboard in "General"?
https://grafana-1.dev02.dev.cloudpipeline.digital/d/cell-memory/cell-memory?orgId=1&var-environment=dev02&var-bosh_director=dev02&var-bosh_deployment=dev02&var-bosh_job_name=diego-cell&var-bosh_job_id=All&var-bosh_job_ip=All&var-zone=All
---
> add "cell memory" dashboard

- concourse/pipelines/create-cloudfoundry.yml
What
----
This change switches billing-collector from a process check to a http call. This change is linked to a change in [paas-billing](https://github.com/alphagov/paas-billing/pull/160).
How to review
-------------
You should be familiar with the change in paas-billing.
---
> Switch billing-collector to use a http endpoint for probes

- concourse/pipelines/create-cloudfoundry.yml
What
----
This ended up in the wrong place following all the moving about (_before_ we `cd` into the correct directory).
How to review
-------------
:eyes: 
---
> billing integration tests: move `APP_ROOT` to correct place in task

- manifests/prometheus/alerts.d/rds_db_manual_snapshot_quota.yml
- tools/metrics/acceptance/aws_test.go
- tools/metrics/gauges_rds_db_manual_snapshots.go
- tools/metrics/gauges_rds_db_manual_snapshots_test.go
- tools/metrics/main.go
What
----
Add manual db snapshot quota alert.
This change adds new metrics paas_aws_rds_manual_snapshot_count and paas_aws_rds_manual_snapshot_quota_count to the metrics-exporter and configures a prometheus alert.
This change is dependant on the following [change](https://github.com/alphagov/paas-aws-account-wide-terraform/pull/329).
How to review
-------------
Pipeline Jobs can be viewed [deploy-paas-metrics](https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/deploy-paas-metrics/builds/8) and [prometheus-deploy](https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/prometheus-deploy/builds/18)
Prometheus alert can be viewed [here](https://prometheus-1.dev04.dev.cloudpipeline.digital/alerts?search=snapshot …
> Add rds manual db snapshot quota alert

- concourse/pipelines/create-cloudfoundry.yml
What
----
https://www.pivotaltracker.com/story/show/183803351
This allows us to use a db that is shared from the billing space without name collisions. The reason for using a space-shared database is to allow us to start with a clone of the real production `billing-db`, but clones can only easily be done into the same space. So we have to choose a db name that won't collide with one already in the production `billing` space.
Once this is deployed I should jump into staging and both prod envs and deleting the `billing-db` services they've already created in the `billing-experimental` space.
How to review
-------------
:eyes: 
---
> billing-experimental deployment: use db named billing-experimental-db

- manifests/cf-manifest/operations.d/310-router.yml
What
----
Current default of 60s causes problems for some users: https://govuk.zendesk.com/agent/tickets/5118907
Now begins the debate of what value to set it to. I chose 900s (15m) as it matches the timeout we set on our AWS load balancers - with the idea that any query we would expect them to handle should be possible to handle with a route service.
How to review
-------------
---
> router: set route_services_timeout to 900s

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
Update cflinuxfs3 version 0.343. Not the latest, but the latest the current release of cloud foundry is using.
How to review
-------------
This has been tested in dev04.
https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/pipeline-lock/builds/22
---
> Upgrade cflinuxfs3 version to 0.346

- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
What
----
Bump elasticache broker: [Adds test_failover option to broker to allow a user to test the failover of their ha cluster](https://github.com/alphagov/paas-elasticache-broker/pull/33)
How to review
-------------
Already tested (I think). [Check it's the right version and sha?](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/elasticache-broker-release/jobs/build-final-release/builds/6)
---
> Bump elasticache broker

- terraform/prod.vpc_peering.json
What
----
Create VPC peering connections with Notify's AWS accounts. 
We will need these connections in place to migrate the database, traffic, etc.
How to review
-------------
Check names and json formating
---
> Add vpc peering connections with Notify's accounts

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
https://www.pivotaltracker.com/story/show/183923174
This includes some tooling changes that shouldn't be relevant to the boshrelease, along with the additions of the cloudfront distribution id in GetInstance responses.
How to review
-------------
:eyes:  This previously went out to dev04 where it worked fine: https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-broker-acceptance-tests/builds/14
(Ignore https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-broker-acceptance-tests/builds/15 where I tried to add a positive test for this feature and realized it would never work without a lot more work on the integration tests...)
---
🚨⚠️ Please do not merge this pull request via the …
> cdn-broker: 0.1.50 -> 0.1.51

- terraform/cloudfoundry/lbs.tf
What
----
After recreating an environment we got the following error pipeline error:
```
│ Error: adding LB Listener Certificate: UnsupportedCertificate: The certificate 'arn:aws:acm:eu-west-1:595665891067:certificate/3a91fd44-c879-4410-9073-8e962ccd23c4' must have a fully-qualified domain name, a supported signature, and a supported key size.
│ 	status code: 400, request id: 125e048b-64ee-4e96-a97c-d9d3fe599391
│ 
│   with aws_lb_listener_certificate.cf_router_metrics_domain_https,
│   on lbs.tf line 242, in resource "aws_lb_listener_certificate" "cf_router_metrics_domain_https":
│  242: resource "aws_lb_listener_certificate" "cf_router_metrics_domain_https" {
```
[from this concourse job.](https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-t …
> Fix terraform dependency order with certificate validation

- terraform/prod.dms.json
What
----
We're performing a test migration with Notify to understand .. stuff better. This commit adds a new DMS migration instance and task ready to go.
* Allocated storage is ~1.2tb, which is 50% of the source database size.
* Maintenance window matches the source database
* AZ matches the source database
* Replication instance class is a guess
How to review
-------------
Do you think I've missed anything?
Should we tweak anything?
---
> Introduce DMS configuration for Notify test database

- terraform/prod.dms.json
- terraform/spec/dms_spec.rb
What
----
In #3062 I introduced a DMS configuration whose name contained spaces. Spaces are not valid in the name.
I've now fixed the name and added a little test to prevent it happening again
How to review
-------------
1. Tests pass, indicating name is OK
---
> Correct Notify DMS test name

- manifests/cf-manifest/operations.d/770-secret-manager-endpoint.yml
- terraform/spec/dms_spec.rb
What
----
This pull request aims to open up the Cloud Foundry security groups to the AWS Secret Manager endpoint subnet, which was added by the tf-dms module. Instead of linking the output of tf-dms like other security group ranges, the subnets have been hardcoded to prevent dependencies within Concourse jobs. Additionally, a test case has been added to ensure that the CIDRs and ranges stay consistent in the future.
Why
----
Fixes the issue experienced on the last deployment where applications running in cloud foundry could no longer access aws secret manager.
How to review
-------------
This pull request has been tested in the dev01 environment, and it has been confirmed that the security group update will take effect on already running applications.
``` …
```
> [#184303348] Open cloud foundry security groups to secret manager endpoint subnet

- scripts/suspend-org.sh
What
----
Allows suspending an org by name, and includes a 'hidden' unsupend method.
This will make suspension simpler, as we won't have to copy and paste from the docs or remember the syntax.
There is also a sanity check step to make sure you're suspending the right org in the right environment.
How to review
-------------
1. Log in to a cf instance
1. Choose an org to suspend
1. Check suspending works: `scripts/suspend-org.sh $ORG_NAME` (should return '"suspended": true' and show 'SUSPENDED' in paasmin)
1. Check unsuspending works: `UNSUSPEND=1 scripts/suspend-org.sh $ORG_NAME` (should return '"suspended": false' and no longer show 'SUSPENDED' in paasmin)
---
> [chore] Add a script to simplify suspending cf orgs

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
After getting a number of BoshHighCPUUtilisation alerts for log-cache, we have decided to increase the number of nodes.
How to review
-------------
Look at the change.
---
> Increase prod-lon log-cache nodes to 30

- manifests/prometheus/dashboards.d/usage-by-organization.json
- manifests/prometheus/dashboards.d/usage-by-space.json
What
----
Nobody asked for this, but the other day's exercise where the platform was seeing elevated app crashes gave me an itch about the visibility of this sort of thing, so I added a (slightly hacky) plot for container start rate to the dashboards from #3048.
How is this useful? If we're seeing elevated crashes this could help determine if the problem is restricted to one tenant or if it could be a wider platform problem.
This is currently in place in london's grafana-1 under the `(noodling)` dashboard copy.
From the panel's description, in case it's interesting:
> Lacking a real (and sufficiently-labeled) metric for containers being started, this actually measures the number of very young containers attributable to an organization.
> 
> A surge of apparent container starts *could* …
> grafana dashboards: add "container start rate" to usage-by-org/space

- manifests/prometheus/operations.d/311-add-smtp-alert.yml
- scripts/upload-secrets/upload-pagerduty-secrets.rb
What
----
This change is to satisfy the requirements of ticket [alerts for missing alerts](https://www.pivotaltracker.com/n/projects/1275640/stories/181970904). A new boshrelease has been created and added to the prometheus manifest.
The smtp_alert script runs every 15 mins.
How to review
-------------
1. The new pagerduty secrets have to be put into credhub for each env: ```make dev04 upload-pagerduty-secrets```. This operation needs to run with the new branch checked out so that the updated upload-pagerduty-secrets.rb script is used.
1. Run the branch into a dev env.
1. ssh onto the alertmanager vm.
1. Check for an smtp_alert file in /etc/cron.d.
1. Change the "pass" var in smtp_alert.rb to raise an incident on pagerduty.
1. Set the "pass" var back to the correct password and check that …
> [#181970904] Add smtp-alert to prometheus

- manifests/cf-manifest/operations.d/235-log-cache-tuning.yml
What
----
https://www.pivotaltracker.com/story/show/184518513
This should reduce the frequency at which go's garbage collector has to scan the whole process memory for unreachable objects, which is quite taxing and probably a significant CPU burden.
How to review
-------------
Can check it _works_ on a dev env (example deployment https://deployer.dev05.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/3). Probably can't check whether it has a beneficial effect to production on anything except production.
---
> log-cache: increase `prunes_per_gc` from 3 -> 5

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Add more prod-lon diego-cells to resolve DiegoCellRepsReachingTotalMemoryCapacity alert
How to review
-------------
Consider the production deployment.
---
> Add more prod-lon diego-cells

- manifests/prometheus/dashboards.d/forwarder-agents.json
What
----
...even though technically it's a metric of the "loggregator agent", downstream from the "forwarder agent", the figure should be similar. I don't think there's enough information about the "loggregator agent" to warrant giving it its own dashboard.
How to review
-------------
Look at dev04's grafana where this PR has been deployed.
---
> dashboards: add "average envelope size" to "forwarder agents" dashboard

- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- manifests/app-autoscaler/operations.d/001-release.yml
- manifests/app-autoscaler/operations.d/900-temp-fix-for-v10.0.0.yml
- manifests/app-autoscaler/operations.d/910-add-plan-options.yml
What
----
Upgrade autoscaler to v10.0.0.
A few issues were discovered during the upgrade:
- They've switched their .envrc file to be "not bash". So I've just put in the PATH changes into our pipeline.
- They failed to update the release url in our deployment template. [Here is the issue.](https://github.com/cloudfoundry/app-autoscaler-release/issues/1461)
- They failed to add the settings instances_retrievable and bindings_retrievable to the [app-autoscaler-deployment.yml](https://github.com/cloudfoundry/app-autoscaler-release/blob/main/templates/app-autoscaler-deployment.yml) template. We should look to migrate to their "tested" template [app-autoscaler.yml](https://github.com/cloudfoundry/app-autoscaler-release/blob/main/templates/app-autoscaler.yml).
- They have broken the memory tests …
> Upgrade app-autoscaler to v10.0.0

- Gemfile.lock
- Makefile
- config/logit/alerts.d/flatline.yaml.erb
- scripts/generate_logit_alerts.rb
- scripts/generate_logit_filters.sh
- tools/cops/backtick_cop.rb
- tools/cops/spec/backtick_cop_spec.rb
What
----
Add script to create the content of alert yaml files for logit
The one alert I've created is for a flatline alert - if fewer than 1200 log entries are received in 10 minutes, the alert will fire.
This alert is sent to pagerduty. Currently the pagerduty alert is only for GOV.UK PaaS Email only - this is changed from within PagerDuty, though.
Also, I've fixed the `backtick` custom cop - it didn't allow me to do a thing (which it should have) so I have fixed that.
This is blocked by https://github.com/alphagov/paas-credentials/pull/242 - as currently the secrets are only present on my local machine.
How to review
-------------
- Code Review
---
> [#180362804] Logit flatline alerts

- manifests/cf-manifest/isolation-segments/prod-lon/egress-restricted-1.yml
- manifests/cf-manifest/spec/manifest/instance_type_counts_in_envs_spec.rb
- manifests/cf-manifest/spec/manifest/isolation_segment_spec.rb
- when checking for evenly distributable instance groups, check all
instance groups that start with the given name, not just the first one
that matches. This means we take isolation segment diego-cell count
into account
- remove commented out code - we have managed to last for a while
without it, so should be fine to remove it
This is required because we are now testing the number of cells in isolation segments, and 2 is not divisible by 3.
- ensure the tests run correctly in GHA
- code review :eyes:
---
> [#180635817] Improve tests

- manifests/cf-manifest/operations.d/320-cc-increase-max-app-disk.yml
What
----
One of our users has requested an increase of the maximum app disk space to 10gb.
How to review
-------------
Tested in dev03
Before:
```
cf scale benc-test-app -k 9GB
...
disk_quota too much disk requested (requested 9216 MB - must be less than 8192 MB)
FAILED
```
After:
```
cf scale benc-test-app -k 9GB
...
#0   running   2023-03-22T15:55:39Z   0.0%   38.2K of 1G   75M of 9G   0/s of 1M/s  
```
---
> [#184769368] Increase maximum disk space an app can request to 10gb

- tools/metrics/fakes/http.go
- tools/metrics/gauges_elb_test.go
What
----
Fixing a timing issue in the elb gauges test code. [Example failure](https://github.com/alphagov/paas-cf/actions/runs/4467412084/jobs/7846839945#step:12:58).
This is happening because of the nonblocking:
`go server.ListenAndServe()` 
If the listener doesn't start before we start the tests we will get a failure.
The fix starts the port listen non-blocking. 
For extra safety I'm also increasing the http request timeout to 2 seconds. 
How to review
-------------
The unit tests will run as part of the PR. So look at the code.
---
> [#184749358] Fix intermittent failure on test cases caused by timing issue.

- concourse/pipelines/create-cloudfoundry.yml
What
----
The changes in this PR implement the requirement of the associated [Pivotal Tracker Story](https://www.pivotaltracker.com/n/projects/1275640/stories/184581852). All the terraform jobs have been removed from the serial group "cf-deploy" and now run in parallel.
How to review
-------------
Run the branch into a dev env and perform some cf commands.
Who can review
---
Any paas developer.
> [#184581852] Make terraform jobs run in parallel

- scripts/create_buildpacks_email.sh
What
----
https://www.pivotaltracker.com/story/show/184821954
Lowercase `head` doesn't appear to be an alias on all systems
How to review
-------------
:eyes: 
---
> create_buildpacks_email.sh: use `HEAD` instead of `head` for git ref

- concourse/pipelines/create-cloudfoundry.yml
What
----
https://www.pivotaltracker.com/story/show/184518969 upgraded all our components to work with go 1.20 but didn't bump the versions specified in the create-cloudfoundry pipeline. We only pin versions like this for 3 components.
This is needed to be able to release the new set of buildpacks in https://www.pivotaltracker.com/story/show/184821954
How to review
-------------
Deploy to a dev env?
---
> Bump `paas-*` components their go 1.20 versions

- manifests/prometheus/alerts.d/bosh-job-ephemeral-disk-full.yml
- manifests/prometheus/alerts.d/bosh-job-ephemeral-disk-predict-will-fill.yml
What
----
Concourse's disk usage pattern falsely triggers this all the time when it has a remotely full disk, even though concourse's garbage collector will generally kick in and prevent it actually running out of space. Increase the threshold for these alerts to 90% for concourse-worker nodes.
Here we have to do the same trick we did previously in the `BoshHighCPUUtilisation` upstream alerts which we wanted to alter - disable upstream's one with a very high threshold and then add our own with the same name.
Consciously no tests for this - it's a copypasta of upstream and upstream doesn't have any tests, What's more it seems the deeper you dig into the specifics of prometheus' `predict_linear` behaviour the less sane it shows itself to be.
How to review
-------------
:eyes: ? See it …
> alerts: internalize "ephemeral disk full" alerts with higher threshold for concourse

- terraform/dms/dms.tf
- terraform/dms/locals.tf
- terraform/dms/variables.tf
- terraform/prod.dms.json
What
----
Add extra connection attributes to dms configuration.
Why
----
We have seen some connection timeouts during the dms replication process. The default query timeout is 60 seconds. 
This needs to be increased via the terraform "extra_connection_attributes" attribute on the aws_dms_endpoint resource.
How to review
-------------
Look at the change.
This change has been "planned" against prod to verify it.
Notes
------
- The terraform may fail to apply if the dms processes affected are in a state of "Running". They will need to be stopped while this change is applied. 
---
> Add dms optional extra connection attributes to dms endpoint configuration

- terraform/prod.dms.json
What
----
Increase notify dms sql execute timeout to 1 hour.
Why
----
During previous successful tests this has been set at 1 hour. It was reduced to 10 mins to see if that was enough. It was not.
```
RetCode: SQL_ERROR SqlState: 57014 NativeError: 1 Message: ERROR: canceling statement due to statement timeout; Error while fetching the next result [1022502] (ar_odbc_stmt.c:3329)
```
How to review
-------------
This will only change the production environment. So just the change for obvious mistakes.
---
> Increase sql execute timeout to 1 hour for notify dms config

- terraform/cloudfoundry/buckets.tf
- terraform/cloudfoundry/cdn_broker.tf
What
----
Necessary since https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/ otherwise bringing up an env from scratch will fail with Access Denied when attempting to set up the buckets.
Uses `depends_on` in an attempt to ensure settings are put in place early enough. I *think* I'm doing the right thing with `aws_s3_bucket_public_access_block` for `cdn_broker_bucket` but would love if someone would confirm this for me.
How to review
-------------
Bring up a fresh dev env using this?
---
> s3 bucket terraform: enable ACL mode via ownership_controls BucketOwnerPreferred

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/runtime-config/operations.d/510-add-prometheus-blackbox-exporter.yml
What
----
https://www.pivotaltracker.com/story/show/184821965
This should hopefully resolve issues we've had with the `cf_exporter` since 28.0.0 (due to  https://github.com/bosh-prometheus/cf_exporter/issues/82)
How to review
-------------
Deploy to a dev env, see how reliable the `cf_exporter` process in the `prometheus2` job of the prometheus instances is. Though problems may only be visible in prod where we have an extensive enough cf database that scraping requests can take long enough (I've tried my best by filling dev05 with spaces and routes but it's not enough and we need to get a move on with this - look at [this period](https://grafana-1.dev05.dev.cloudpipeline.digital/d/usage-by-organization/usage-by-organisation?orgId=1&var-environment=dev05&var-bosh_director=dev05&var-bosh_dep …
> prometheus-boshrelease: 28.0.0 -> 28.1.0

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
Upgrade stemcell to 1.108. This is being expedited due [this issue](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/287) in 1.102.
How to review
-------------
tbd
---
> [#185156395] Upgrade stemcell to v1.108

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/check-az-is-enabled-in-manifest.yml
- concourse/tasks/check-az-is-enabled-in-vpc.yml
- concourse/tasks/check-billing-comparison-with-cf.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/curl-az-healthcheck.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/send-nagging-email-alert.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
Description:
- Updates all docker images to the latest ghcr version see [https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/276](https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/276)
- See [here](https://deployer.dev03.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry) for a clean run
How to review
-------------
---
> 18504128 - Update docker images

- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/720-cdn-broker.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/operations.d/750-s3-broker.yml
- manifests/cf-manifest/operations.d/760-sqs-broker.yml
What
----
https://www.pivotaltracker.com/story/show/184967033
How to review
-------------
Either deploy to a dev env and check the broker acceptance tests are passing or look at dev04: https://deployer.dev04.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-broker-acceptance-tests/builds/24
---
> Bump boshrelease-deployed brokers to use golang 1.20-based releases

- terraform/dms/default_task_settings.json
- terraform/prod.dms.json
What
----
- Change TargetTablePrepMode to DO_NOTHING. DMS should not be trusted to handle any part of the schema.
- Enable validation. This might be disabled later, but at the moment this gives us more confidence about the cutover.
- Enable additional dms target db tables. These give us all sorts of useful info on the state of the dms process.
- Upgrade preview replication instance to have enough memory for the validation.
How to review
-------------
---
> Updates to DMS config

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/spec/manifest/base_properties_spec.rb
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Upgrading cf-deployment to v27.2.0 and the associated manifest changes.
How to review
-------------
Run through the upgrade procedure in our internal docs: https://team-manual.cloud.service.gov.uk/guides/upgrade_cf-deployment/
---
> Upgrade to cf-deployment v27.2.0

- concourse/pipelines/create-cloudfoundry.yml
- manifests/prometheus/dashboards.d/billing-compared-to-spending-new_metrics.json
- manifests/prometheus/dashboards.d/billing-compared-to-spending.json
- manifests/prometheus/dashboards.d/billing-echoframework.json
- manifests/prometheus/dashboards.d/billing-performance.json
- manifests/prometheus/dashboards.d/billing-sli-new_metrics.json
- manifests/prometheus/dashboards.d/billing-sli.json
- manifests/prometheus/dashboards.d/bosh-jobs-heatmaps.json
- manifests/prometheus/dashboards.d/cell-memory.json
- manifests/prometheus/dashboards.d/component-indicators.json
- manifests/prometheus/dashboards.d/doppler-heatmaps.json
- manifests/prometheus/dashboards.d/forwarder-agents.json
- manifests/prometheus/dashboards.d/grootfs.json
- manifests/prometheus/dashboards.d/log-cache.json
- manifests/prometheus/dashboards.d/reverse-log-proxy.json
- manifests/prometheus/dashboards.d/service-type-adoption.json
- manifests/prometheus/dashboards.d/sli.json
- manifests/prometheus/dashboards.d/syslog-agents.json
- manifests/prometheus/dashboards.d/trafficcontroller.json
- manifests/prometheus/dashboards.d/usage-by-organization.json
- manifests/prometheus/dashboards.d/usage-by-space.json
- manifests/prometheus/dashboards.d/user-impact-redux.json
- manifests/prometheus/dashboards.d/user-impact.json
- manifests/prometheus/operations.d/304-scrape-paas-billing.yml
- manifests/prometheus/spec/dashboard_validation_spec.rb
What
----
- Scrape metrics directly from paas billing apps
- Remove billing metrics from paas-metrics
- Add grafana dashboards with new billing-app-sourced-metrics
- fix grafana dashboard uploading (remove json wrapper)
- new envars for billing apps
- deploy billing apps in parallel
How to review
-------------
check it deploys
---
> [#184604154] Get metrics directly from paas-billing

- manifests/prometheus/dashboards.d/billing-compared-to-spending-new_metrics.json
- manifests/prometheus/spec/dashboard_validation_spec.rb
What
----
Dashboard UIDs should be <= 40 characters in length. The UID for this dashboard was 41 characters.
I've removed a character.
Also, added a test to prevent this in future.
Context: I changed the UID after the last deploy attempt, and before it was deployed to staging, so missed it - sorry!
How to review
-------------
👀
---
> fix: fix uid for 'Billing compared to spending (new billing metrics)' dashboard

- manifests/prometheus/dashboards.d/logging-volume.json
- manifests/prometheus/dashboards.d/usage-by-organization.json
- manifests/prometheus/dashboards.d/usage-by-space.json
What
----
This is already a rate measurement - don't take the rate of it a second time.
Also include new dashboard "logging volume" which you can play with on prod-lon.
How to review
-------------
:eyes: 
See it deployed @ https://deployer.dev05.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/prometheus-deploy/builds/53
---
> dashboards: usage-by-organization/space: fix use of `firehose_http_start_stop_requests` metric

- Makefile
What
----
Disable the auto-delete pipeline when using the "dev" makefile target.
Several people have fallen into this trap.
How to review
-------------
---
> Disable auto-delete pipeline when using the dev make target

- concourse/pipelines/create-cloudfoundry.yml
- concourse/tasks/curl-az-healthcheck.yml
- terraform/az-monitoring/main.tf
- terraform/az-monitoring/module/main.tf
- terraform/az-monitoring/module/variables.tf
- terraform/az-monitoring/variables.tf
What
----
Added a blocker to the terraform responsible for building the az-healthcheck instances. The blocker waits until the healthcheck service is responding before allowing the pipeline to continue. New tasks after the terraform wait for the healthcheck service to start, and double check it's active just in case.
This can be disabled with the already existing `DISABLED_AZS=$ZONE`, where ZONE is a space separated AZ string e.g. `a b`. Disabling an az indicates degradation in AWS service, so this keeps the instances up but disables the checks.
How to review
-------------
Deploy the branch to a dev environment using `SLIM_DEV_DEPLOYMENT=false ENABLE_AZ_HEALTHCHECK=true SELF_UPDATE_PIPELINE=false`. You should see the `az-healthcheck-terraform` node build the instances and then a new task …
> #184950003 Block cf-deploy if az healthcheck node fails to start

- terraform/dms/default_task_settings.json
What
----
DMS default config changes:
- Disable dms validation.
- Enable awsdms_txn_state table.
- Enabled StopTaskCachedChangesNotApplied.
Why
----
- The validation doesn't work across all tables correctly when loading data without primary keys. We have proved validation anyway so we can disable.
- The awsdms_txn_state table can give us more regular updates on the state of the replication.
- We are enabling the StopTaskCachedChangesNotApplied option so we have a clear point to apply our primary keys, indices and constraints before the cdc process starts.
How to review
-------------
---
> Disable dms validation and enable awsdms_txn_state table

- terraform/cloudfoundry/backing_services.tf
- terraform/vpc-peering/variables.tf
- terraform/vpc-peering/vpc_peering.tf
What
----
https://www.pivotaltracker.com/story/show/184840850
Firstly this switches backing service subnets to use a custom VPC route table rather than the default one, allowing us finer grained control.
Then, based on Ben's #3134, this optionally adds an entry to the ~default VPC~ backing service subnet's routing table to allow packets to be routed _to_ a peer VPC. ~While the rule itself is quite general, this actually affects little more than our backing-services subnets because our infra subnet uses a custom route table as do our cell subnets.~
Security groups remain in place on individual machines, which have the main responsibility for policing access - for backing services, these only allow traffic from cells and brokers . Backing services also have no outbound rules so shouldn't be …
> vpc peers: add ability for some peers to be able to get traffic routed back from backing service subnets

- terraform/prod.vpc_peering.json
- terraform/scripts/generate_vpc_peering_test.go
What
----
- Enable backing service routing for notify vpc peers in prod
- Fix vpc_peering_test so it works with the new vpc_peer option (backing_service_routing)
How to Review
-------------
Check the changes.
---
> Enable backing service routing for notify vpc peers in prod

- terraform/cloudfoundry/cf_rds.tf
What
----
The ITHC noted that the cf RDS instance was not enabled to permit an automatic minor version update of the instance engine. This change permits that to happen.
How to review
-------------
1 - Check that the cf RDS instance associated with your development environment has its "Auto minor version upgrade" option set to "Disabled". The option can be found under the "Maintenance and backups" tab.
2 - Run the branch into the development environment.
3 - After the cf-deploy job has completed check that the "Auto minor version upgrade" option is set to "Enabled"
---
> [#185166925] Allow auto update of minor version of cf rds

- manifests/cf-manifest/operations.d/009-add-prometheus-uaa-clients-attic.yml
- manifests/cf-manifest/operations.d/030-bosh-dns.yml
- manifests/prometheus/dashboards.d/logging-demand.json
- manifests/prometheus/dashboards.d/usage-by-organization.json
- manifests/prometheus/dashboards.d/usage-by-space.json
- manifests/prometheus/operations.d/030-bosh-dns.yml
- manifests/prometheus/operations.d/221-monitor-cf-attic-UPSTREAM.yml
- manifests/prometheus/operations.d/222-monitor-cf.yml
- manifests/prometheus/operations.d/223-unique-firehose-subscription-id.yml
- manifests/prometheus/scripts/generate-manifest.sh
- manifests/prometheus/spec/operations/monitor_cf_spec.rb
- manifests/runtime-config/operations.d/510-add-prometheus-blackbox-exporter.yml
What
----
Switch to using the bosh-prometheus new 7.0 firehose.
The new jobs require bosh dns in order to function so adding it as part of this PR.
This PR also fixes our dashboards as the metrics have been changed as part of the firehose 7.0 release.
How to review
-------------
Review the changes
Deploy to an environment.
---
> Switch to using the bosh-prometheus new 7.0 firehose

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
https://www.pivotaltracker.com/story/show/185263720
Fixing this involved some rearranging of the script injected in `uaa-customized` and adding its hash to UAA's `script-src` CSP statement.
How to review
-------------
Deploy to dev env. Log in to the dev env's tenant facing "front door" and try to retrieve a passcode. See copy button work.
---
> uaa: re-enable passcode copy button despite CSP

- .github/workflows/check_gpg_keys.yml
- .github/workflows/generate_buildpack_bump_pr.yml
- .github/workflows/test_on_pr.yml
Description:
-------------
- Currently we pin to versions which means that we automatically pull in the latest changes which presents a security risk as we don't know which code is running in our build pipeline.
- This PR fixes this by pinning to a specific hash
- A future PR will configure dependabot to raise PR's automatically for later versions of GitHub Actions against their hashes
How to review
-------------
Verify if the GitHub actions have passed.
---
> 185509385 - Pin GitHub Actions to specific hashes

- manifests/prometheus/dashboards.d/logging-demand.json
What
----
In #3284 I only added the `app_name` term to the container log rate series' aggregation, so we weren't matching any of these and subtly not counting the request-proportional logs.
How to review
-------------
:eyes: 
---
> logging demand dashboard: re-fix join condition

- manifests/prometheus/operations.d/222-monitor-cf.yml
- manifests/prometheus/spec/operations/monitor_cf_spec.rb
What
----
In reality this just gives it more memory and only a very slight cpu downgrade. Hopefully this will prevent the issues we've had with the firehose-exporter going into swap occasionally since we moved to the new version.
How to review
-------------
:eyes: 
---
> firehose instance: move from `high_cpu_xlarge` -> `xlarge`

- terraform/prod-lon.vpc_peering.json
What
----
The team at DLUHC are re-creating their VPC, which means their VPC ID will change and our peering will be broken. We're removing our side of the peering while they re-create their shiny new VPC.
How to review
-------------
Is the file still valid? Did I miss anything?
---
> Temporarily remove DLUHC VPC peering

- terraform/vpc-peering/vpc_peering.tf
What
----
This reverts commit a0cb044e7f9d4b25a266dcd3fdef108a0f48f96e.
We need to allow VPC peering removal for when/if we change VPC peers.
How to review
-------------
👀 
---
> Revert "vpc peering: mark vpc peers with prevent_destroy = true"

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
What
----
The cf cli has been upgraded to v8.7.1 as requested in Pivotal Tracker storey 185500801.
All images created by github actions in paas-docker-cloudfoundry-tools have had their tag updated.
How to review
-------------
1 - Run the branch into a dev env.
2 - Confirm that the new version of the cf cli has been installed by hijacking a relevant container and checking the version of the cf cli.
3 - Confirm that there are no errors related to the cf cli within the pipeline.
---
> [#185500801] Upgrade cf cli

- concourse/pipelines/create-cloudfoundry.yml
- config/cloudwatch-exporter/config.yml
https://www.pivotaltracker.com/story/show/185098972
What
----
Switch from our fork of yet-another-cloudwatch-exporter to the main line. [Our pr](https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/39) was merged a long time ago.
Why
----
Our fork hasn't been updated in years. We should switch back to a more well maintained version.
How to review
-------------
Take a copy of the old metrics. https://cloudwatch-exporter.dev04.dev.cloudpipelineapps.digital/metrics (replace dev04 with your env)
Deploy to an environment
Take a new copy of the metrics. https://cloudwatch-exporter.dev04.dev.cloudpipelineapps.digital/metrics (replace dev04 with your env)
Compare them. You should see extra labels and some extra metrics. All the old tags and metrics should be there.
---
🚨⚠️ Please do …
> Unfork yet-another-cloudwatch-exporter

- concourse/pipelines/create-cloudfoundry.yml
What
----
Increase memory allocation of cloudwatch exporter to 3gb.
Why
----
It looks like all the dependencies for the cloudwatch exporter need a lot of memory to compile. Seeing the following staging error in staging:
```
2023-07-28T11:33:32.02+0100 [STG/0] ERR [github.com/aws/aws-sdk-go-v2/service/ec2](http://github.com/aws/aws-sdk-go-v2/service/ec2): /tmp/contents2275605378/deps/0/go1.20.5/pkg/tool/linux_amd64/compile: signal: killed
2023-07-28T11:33:32.12+0100 [STG/0] OUT **ERROR** Unable to compile application: exit status 1
2023-07-28T11:33:32.61+0100 [STG/0] ERR Failed to compile droplet: Failed to run finalize script: exit status 12
2023-07-28T11:33:32.61+0100 [STG/0] OUT Exit status 223 (out of memory)
```
How to review
-------------
Check the changes.
---
🚨⚠️ Please do not …
> Increase memory allocation of cloudwatch exporter to 3gb

- manifests/prometheus/dashboards.d/stacks.json
What
----
Adds a new dashboard that allows us to monitor the cf app stacks our tenants are using. Helpful to see progress of tenants transitioning to cflinuxfs4.
No you don't get stack names because `cf_exporter` neglected to include them.
How to review
-------------
:eyes: , or look at the "Stacks (noodling)" dashboard on prod-lon grafana.
---
> grafana: add "stacks" dashboard

- concourse/pipelines/create-cloudfoundry.yml
- manifests/prometheus/scripts/generate-manifest.sh
- manifests/prometheus/spec/support/manifest_helpers.rb
- manifests/shared/spec/fixtures/cf-vars-store.yml
What
----
Looks like this is no longer needed since the "new" firehose_exporter (switched-to in #3276), and a pipeline expecting it to exist will choke when it hasn't been generated. e.g. when a newly-created env is brought up.
How to review
-------------
Deploy to a dev env? Look at dev03 which was brought up with this (commit applied to another branch...). dev04 had this change deployed to it directly (without a rebuild) and it seems happy.
---
> remove `uaa_clients_firehose_exporter_secret` handling in pipelines & scripts

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
https://www.pivotaltracker.com/story/show/185686086
Straightforward. Luckily `229-cf-update_cflinuxfs_releases.yml` comes after `026-use-cflinuxfs4-compat-UPSTREAM.yml`, so we just have to choose a different release to point to.
I didn't find any spec tests we apply to cflinuxfs3 to use for cflinuxfs4. Nor could I think of any sensible ones.
How to review
-------------
Deploy to a dev env
---
> cf manifest: decouple `cflinuxfs4-compat` release, bump 1.18.0 -> 1.29.0

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- config/cloudwatch-exporter/config.yml
- manifests/prometheus/alerts.d/wafv2.yml
- manifests/prometheus/spec/alerts/waf-throttling-ips-max-rate.test.yml
- terraform/cloudfoundry/shield_and_waf.tf
- terraform/cloudfoundry/variables.tf
What
----
https://www.pivotaltracker.com/story/show/185574049
This depends on https://github.com/alphagov/paas-aws-account-wide-terraform/pull/372, #3342 ~and (tangentially) #3341~
WAF v2 gives us the ability to use more complex sets of rules for configuration of rate limiting.
Firstly we exclude an environment's own egress IPs and "system" (currently just concourse) IPs from rate limiting to prevent us blocking either our own tests or tenants that are using externally routed inter-app requests.
We then have a rate limit rule for requests we've determined should *not* have `x-forwarded-for` respected. We determine this by looking for a header with a "secret" value only set by our blessed CDNs. So that the header is not visible to tenant apps we abuse the header `x-cf-instanceid` for this. …
> waf: migrate to WAF v2, adding ability to conditionally obey `x-forwarded-for`

- config/cloudwatch-exporter/config.yml
- manifests/prometheus/alerts.d/shield-attacks.yml
- manifests/prometheus/alerts.d/wafv2.yml
- manifests/prometheus/spec/alerts/shield-attacks.test.yml
- manifests/prometheus/spec/alerts/waf-throttling-ips-max-rate.test.yml
- terraform/cloudfoundry/lbs.tf
What
----
https://www.pivotaltracker.com/story/show/185815021
See the above ticket for existing alerts we have for AWS Shield Advanced events and how they don't work.
This makes cloudwatch-exporter pull some `AWS/DDOSProtection` metrics and then sets up an alertmanager alert on them.
One caveat is that cloudwatch-exporter, being an app, relies on the gorouter being up to work properly. So an outage to our gorouters could cause this metric to stop being reported. But all alarm methods have at least one caveat of their own.
Depends on https://github.com/alphagov/paas-aws-account-wide-terraform/pull/373
How to review
-------------
Deploy to a dev env to check this doesn't totally break things? Actually testing getting these metrics is near impossible.
---
🚨⚠️ Please do not merge this pull …
> AWS Shield CloudWatch metrics and alertmanager alerts

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/fast-startup-and-shutdown-cf-env.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/check-az-is-enabled-in-manifest.yml
- concourse/tasks/check-az-is-enabled-in-vpc.yml
- concourse/tasks/check-billing-comparison-with-cf.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/create_nonadmin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/curl-az-healthcheck.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_user.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/send-nagging-email-alert.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
What
----
Update paas docker images to pick up new bosh-cli-v2
How to review
-------------
Deployed in dev-04
---
> Update paas docker images to pick up new bosh-cli-v2

- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/apply_security_group_bindings_from_vpc_peering_json.rb
- terraform/env.vpc_peering.json.example
- terraform/vpc-peering/variables.tf
What
----
Added a ruby script to apply security group bindings for vpc peers in the pipeline, as configured by extending the config of the existing env specific terraform vpc_peering json files.
I have left an example file in the repo for reference:
```terraform/env.vpc_peering.json.example```
How to review
-------------
Look at the code
Create a copy of this branch
Manually create VPC(s)
Create an env specific vpc_peering.json file using the format from the example and push to your branch
Configure the chosen dev env pipeline with your branch
Run the pipeline
Ensure that the correct security-group bindings are applied
---
> added script to apply security group bindings for vpc peers

- concourse/scripts/apply_security_group_bindings_from_vpc_peering_json.rb
What
----
fix to allow script to exit cleanly when no peering file is present
How to review
-------------
look at code
test in pipeline 
---
> fix to allow script to exit cleanly when no peering file is present

- Gemfile.lock
- manifests/cf-manifest/operations.d/712-rds-broker-mysql57-plans.yml
- manifests/cf-manifest/operations.d/715-rds-broker-postgres10-plans.yml
- manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
- scripts/upgrade_instance_class.rb
- terraform/cloudfoundry/cdn_broker.tf
What
----
We have received a notification that AWS will retire the t2, m4 and r4 db instance classes by April 2024. This PR replaces the deprecated classes with t3, m5 and r5 classes as appropriate in the affected marketplace offerings.
This change also contains a script - upgrade_instance_class.rb - which will upgrade the instance class in existing rds instances where appropriate.
How to review
-------------
1. Review the code. Any feedback gratefully received.
2. Run the branch into a dev env.
3. Check that no cf rds marketplace services offer any of the deprecated instance classes.
4. Using aws ro credentials run the script in "--dry-run" mode. You should see no "not authorized" errors meaning the script is not attempting to update any aws resources.
5. I have changed the terraform for …
> [#185529919] Work associated with AWS retirement of db-instance-classes

- platform-tests/acceptance/plain_http_test.go
Description:
----
- Product pages which has been migrated to GitHub pages has a HTTP listener on port 80 which redirects to HTTPs rather than connection refused which means the test is incorrect and can be removed
> 185827634 - Remove HTTP listener test for PaaS product pages

- concourse/pipelines/create-cloudfoundry.yml
What
----
Reduce memory usage of yet-another-cloudwatch-exporter by splitting the staging process into two apps. The staging process will use 3GB and the running version will use 128MB.
Mask the AWS secret from the concourse logs.
Why
----
As part of the yet-another-cloudwatch-exporter upgrade we had to increase memory from 128M to 3GB. This was because the new aws client requires a lot of RAM to compile.
Sadly cloud foundry does not support different staging and running memory sizes. This process of downloading the droplet from one app and upload as another is a workaround to this issue.
How to review
-------------
[Tested in dev05](https://deployer.dev05.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/prometheus-deploy/builds/122#L64f74a61:4) …
> Reduce memory usage of yace by splitting the staging process

- terraform/prod.vpc_peering.json
What
----
Add notify vpc cloud foundry security group bindings
Why
----
Preview and staging were done manually a while ago. Production is still missing it's bindings.
How to review
-------------
Can't be tested in a dev environment. Look at the changes.
---
> Add notify vpc cloud foundry security group bindings

- manifests/cf-manifest/operations.d/700-broker-ca.yml
- manifests/cf-manifest/operations.d/750-s3-broker.yml
- terraform/cloudfoundry/s3_broker.tf
What
----
add bosh-signed TLS CA variables, and config to the manifest
updated s3 broker release version
added TLS listener in terraform
How to review
-------------
look at the code
deploy branch to a dev env and test s3 broker functionality
---
> Add TLS listener and config for s3 broker

- Makefile
What
----
Explicitly enable app autoscaler tests in staging and production.
Why
----
It looks like the app autoscaler tests were accidentally disabled by [this change](https://github.com/alphagov/paas-cf/pull/3047/files#diff-c761195c5ba6a7652ca048b1fd6425ceb1c3505dd1f9cb690a11a1bfd5badfceR103).
How to review
-------------
No way to test. Just look at the changes
---
> Explicitly enable app autoscaler tests in staging and production

- manifests/prometheus/dashboards.d/stacks.json
What
----
Turns out these show up as having the default "stack id" even though this is basically meaningless for docker apps.
How to review
-------------
:eyes: dev03 where this has been deployed
---
> stacks dashboard: exclude docker-based apps

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Both were a good number higher than was necessary. Numbers have been chosen to give a little wiggle room on top of what's already accounted for, so that we have time to address it if we're growing into that buffer.
London
Ireland
How to review
-------------
Do you agree with the numbers? Suggest others?
---
> Scale down London and Ireland cell counts

- terraform/globals.tf
> Add new vpn ips (#186110481)

- terraform/prod-lon.vpc_peering.json
Removed UK Space Agency from the VPC peers. Migration is complete.
Review: 👀 
---
> Remove UK space agency VPC peer

- terraform/prod.dms.json
What
----
Readd notify staging dms config
Why
----
Notify are doing some more dms tests this month before the production cutover.
How to review
-------------
No way to test in a dev environment. Look at the changes.
---
> Readd notify staging dms config

- concourse/pipelines/create-cloudfoundry.yml
What
----
https://www.pivotaltracker.com/story/show/185989513
This will of course have no effect on our existing deployments which will need manual upgrading.
How to review
-------------
Delete the paas-auditor database in a dev env & re-run `deploy-paas-auditor` from this branch? Or just :eyes: at dev03.
---
> paas-auditor: use postgresql 13 initial database

- terraform/prod.dms.json
What
----
Update notify-staging dms process to TRUNCATE_BEFORE_LOAD
Why
----
This is a much more sensible choice for operation in the case of failure for notify. We want to be able to do a full retry of the db load. Truncate the target tables makes sense when managing the schema outside of dms.
How to review
-------------
---
> Update notify-staging dms process to TRUNCATE_BEFORE_LOAD

- Makefile
Description:
----
- These 2 Makefile targets only run in the production environment
- Conditionally execute these targets if 'prod' is found as a substring in `DEPLOY_ENV`
How to review
-------------
Code review
---
> 186172165 - upload-mailchimp and upload-psn only run in production environment

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/fast-startup-and-shutdown-cf-env.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/check-az-is-enabled-in-manifest.yml
- concourse/tasks/check-az-is-enabled-in-vpc.yml
- concourse/tasks/check-billing-comparison-with-cf.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/create_nonadmin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/curl-az-healthcheck.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_user.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/send-nagging-email-alert.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
What
----
update docker tags and postgres repo to fix billing tests errors in the pipeline
How to review
-------------
deploy branch to dev env (after same change to bootstrap)
---
> update docker tags and postgres repo

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/runtime-config/operations.d/510-add-prometheus-blackbox-exporter.yml
What
----
Upgrade to prometheus-boshrelease 29.6.0
Why
----
This upgrade is getting bumped up the priority list to deal with this issue:
https://github.com/bosh-prometheus/prometheus-boshrelease/issues/485
How to review
-------------
---
> Upgrade to prometheus-boshrelease 29.6.0

- manifests/cf-manifest/operations.d/750-s3-broker.yml
- platform-tests/broker-acceptance/s3_broker_test.go
- platform-tests/example-apps/healthcheck/s3.go
- terraform/cloudfoundry/outputs.tf
- terraform/cloudfoundry/policies/s3_broker_user_common.json.tpl
- terraform/cloudfoundry/s3_broker.tf
- terraform/globals.tf
What
----
https://www.pivotaltracker.com/story/show/186090782
Roll this change out to cf, also making our custom-broker-acceptance-tests check they can successfully call `s3:GetObjectTagging`. In an ideal world we would have actually set a tag on the object to more completely test this works, but then we'd need to add `s3:PutObjectTagging` which we currently can avoid. So here we just test for the returned `TagSet`'s emptiness.
How to review
-------------
:eyes: https://deployer.dev03.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-acceptance-tests/builds/21 ?
---
> paas-s3-broker: bump to ..., provide with common user policy, expand custom-broker-acceptance-tests

- concourse/pipelines/create-cloudfoundry.yml
- scripts/migrate-db.sh
What
----
updated the paas-accounts db plan in the pipeline to add resilience
added a script to automate the db migration to the new plan
How to review
-------------
deploy the branch to a dev env
cf login to the env
run the script
test the pass-billing accounts integration (eg: https://accounts.dev04.dev.cloudpipeline.digital)
---
> 186099050 upgrade and migrate paas accounts db

- manifests/cf-manifest/operations.d/010-set-cflinuxfs3-default-stack.yml
- platform-tests/acceptance/cf_push_test.go
What
----
make cflinuxfs4 the default stack as 3 is out of support 
How to review
-------------
deploy to a dev and and test that an app without a stack defined defaults to 4
---
> make cflinuxfs4 the default stack

- scripts/get-decommission-details.sh
get app state from each org
What
----
I've added a script that will count all apps that are running for each organization.
How to review
-------------
Run the script whilst logged in to a CF
---
> Decommissioning helper script (running app count)

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Reduces London cell count down to 75, because we're overprovisioned
How to review
-------------
Agree with the count?
---
> Reduce London cell count to 69

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
- platform-tests/broker-acceptance/cdn_broker_test.go
What
----
Revert CDN broker to brokerapi v8.
Revert acceptance tests from previous PR
How to review
-------------
Look at the changes. Tested in dev05
---
> Revert CDN broker to brokerapi v8

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
- terraform/cloudfoundry/cdn_broker.tf
What
----
Remove old cdn-broker lets-encrypt config. This was removed a long time ago.
Remove old letsencrypt s3 bucket.
Why
----
This functionality is no longer used and we get security alerts about having a public bucket.
How to review
-------------
---
> Remove old cdn-broker lets-encrypt config

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Prod lon cell bump to keep us below 33%
Why
----
We have started getting the capacity alert from prod london.
How to review
-------------
---
> Prod lon cell bump to keep us below 33%

- Makefile
- scripts/add_permissions_boundary_to_existing_s3_broker_users.rb
What
----
Created ruby script to add s3BrokerUserPermission policy and s3BrokerUserCommon policy to pre-existing s3 users.
How to review
-------------
1 - In a dev env provide s3 users without the permission boundary policy or user common policy and then run script.
2 - Check that the users have both policies.
---
> 186518458 update s3 broker users with permissions boundary policy

- concourse/pipelines/create-cloudfoundry.yml
- manifests/prometheus/dashboards.d/service-operation-levels.json
- manifests/prometheus/operations.d/305-scrape-pingdom-metrics.yml
What
----
A new dashboard has been added to Grafana to display the Service Operation Levels.
How to review
-------------
1 - Review the code changes.
2 - Run into a dev env and check the new dashboard - "Service Operation Levels". Run the bare metric/s in Prometheus to ensure the data associated with that metric resembles the graphs that you see in the new dashboard.
3 - The "% URL Uptime" panel will display "No data" in dev because there are no pingdom URLs configured for the dev env.
---
> [#186779486] Added service operation levels dashboard

- scripts/decommission_organisation.rb
- scripts/get-decommission-details.sh
What
----
I've added:
- Usage help info
- Ability to filter org guids from the list instead of doing all
- Checking how many services are running for each org
Examples:
```sh
❯ ./scripts/get-decommission-details.sh -h
Usage: ./scripts/get-decommission-details.sh [comma separated list of org guids]
If no orgs are specified, all orgs will be checked
```
```sh
❯ ./scripts/get-decommission-details.sh some-org-guid
Filtering to a comma separated list of orgs: some-org-guid
organization_name,running_app_count,non_running_app_count,service_count,owner,ready_for_decommission
some-org,18,2,10,"Org Name",no
```
How to review
-------------
Log in to cf and run the script
---
> Add service checking, usage info and org filtering to decommission query script

- manifests/cf-manifest/isolation-segments/prod/govuk-notify-production.yml
- manifests/cf-manifest/isolation-segments/prod/govuk-notify-staging.yml
- manifests/cf-manifest/spec/manifest/isolation_segment_spec.rb
What
----
Notify has now decommissioned. Time to '0' the isolation segments to save money.
How to review
-------------
---
> Remove govuk-notify's isolation segments

- terraform/prod.vpc_peering.json
What
----
Remove notify vpc peers 
Why
----
Notify has now been fully migrated to ECS.
How to review
-------------
---
> Remove notify vpc peers after decommissioning

- .github/workflows/generate_buildpack_bump_pr.yml
- .github/workflows/test_on_pr.yml
- common-go/basic_logit_client/go.mod
- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- go.mod
- platform-tests/example-apps/app-autoscaler-cpu-usage/manifest.yml
- platform-tests/example-apps/healthcheck-pinger/manifest.yml
- platform-tests/example-apps/healthcheck-ponger/manifest.yml
- platform-tests/example-apps/healthcheck/go.mod
- platform-tests/example-apps/healthcheck/manifest.yml
- platform-tests/example-apps/http-tester/go.mod
- platform-tests/example-apps/http-tester/manifest.yml
- platform-tests/example-apps/logging-pipeline/manifest.yml
- tools/metrics/go.mod
- tools/metrics/manifest.yml
- tools/pipecleaner/go.mod
- tools/user_emails/go.mod
What
----
Update go to 1.21 from 1.20.
Related PRs
----
https://github.com/alphagov/paas-aiven-broker/pull/54
https://github.com/alphagov/paas-billing/pull/196
https://github.com/alphagov/paas-accounts/pull/39
https://github.com/alphagov/paas-auditor/pull/25
https://github.com/alphagov/paas-rubbernecker/pull/99
https://github.com/alphagov/paas-bootstrap/pull/740
https://github.com/alphagov/paas-elasticache-broker/pull/52
https://github.com/alphagov/paas-rds-broker/pull/195
https://github.com/alphagov/paas-cdn-broker/pull/82
https://github.com/alphagov/paas-s3-broker/pull/63
https://github.com/alphagov/paas-sqs-broker/pull/40
How to review
-------------
* Deploy this branch to a dev env and update the branch/tag filters on the other repo resources to point to the go 1.21 branch.
* Ensure …
> Update to go 1.21

- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/720-cdn-broker.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/operations.d/750-s3-broker.yml
- manifests/cf-manifest/operations.d/760-sqs-broker.yml
What
----
This PR updates the brokers to the latest releases which use go 1.21. We need to do this as go 1.20 is EOL and removed from the latest go buildpack.
This PR also includes v1.59.0 of the RDS broker, which removes MySQL 5.7 usage from integration tests, as this is now only available through RDS extended support, and has been removed from the service catalogue
Related PRs:
---
* https://github.com/alphagov/paas-rds-broker/pull/195
* https://github.com/alphagov/paas-rds-broker/pull/196
* https://github.com/alphagov/paas-elasticache-broker-boshrelease/pull/31
* https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/69
* https://github.com/alphagov/paas-s3-broker-boshrelease/pull/31
* https://github.com/alphagov/paas-sqs-broker-boshrelease/pull/21
How to review
------------- …
> Update brokers to latest releases which use go 1.21

- terraform/prod-lon.vpc_peering.json
This is needed to migrate data from their backing service. Also bind these to the right orgs and spaces.
For further context see this slack thread https://gds.slack.com/archives/CAEHMHGJ2/p1715848641349289
---
> Enable backing service routing through both new DIT VPC peers

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
There is a new cflinuxfs4-compat release 1.95.0. This PR applies this version.
How to review
-------------
Deploy the branch on a dev env:
verify that the new version is applied
see all concourse ci jobs go green
---
> Updated cflinuxfs4-compat to latest release 1.95.0

- manifests/app-autoscaler/operations.d/001-release.yml
What
----
There is a new app-autoscaler release 13.1.0 This PR applies this version.
How to review
-------------
Deploy the branch on a dev env:
verify that the new version is applied
see all concourse ci jobs go green
---
> Upgrading app-autoscaler to latest release 13.1.0

- terraform/prod-lon.vpc_peering.json
What
----
DIT have requested some additional VPC peers to perform data migrations away from PaaS into other AWS accounts
How to review
-------------
Deploy this to a dev environment and ensure the VPC peers have been created with the correct parameters
---
> Add two new DIT VPC peers for data migrations

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
There is a new cflinuxfs4-compat release 1.98.0. This PR applies this version.
How to review
-------------
Deploy the branch on a dev env:
verify that the new version is applied
see all concourse ci jobs go green
---
> upgraded cflinuxfs4-compat to latest version 1.98.0

- manifests/app-autoscaler/diffs/patch_dynamic_policy_test.patch
- manifests/app-autoscaler/operations.d/001-release.yml
What
----
There is a new app-autoscaler release 13.2.0 This PR applies this version.
How to review
-------------
Deploy the branch on a dev env:
verify that the new version is applied
see all concourse ci jobs go green
---
> app-autoscaler upgrade to latest release 13.2.0

- manifests/app-autoscaler/diffs/patch_dynamic_policy_test.patch
What
----
Increasing the heap size of dynamic_policy_test to 30
How to review
-------------
Paas Team member to check staging build
---
> enabled app auto scaler acceptance test

- terraform/pingdom/pingdom.tf
This reverts commit 4192e40965ec34836713a6ee3b86cc14fe7a3907.
The healthcheck probes are back to normal response times after the autoscaler upgrade.
---
> Reduce pingdom health check timeouts

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> reduced cell instances and api instances to save cost

- .github/workflows/test_on_pr.yml
What
----
- Changed to use v6.1.1 of the BOSH CLI which is used in paas-bootstrap
- Fixed the download URL and now uses GitHub releases link
---
> Updated test_on_pr.yml with new bosh cli version and fixed download url

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/runtime-config/operations.d/510-add-prometheus-blackbox-exporter.yml
What
----
Update prometheus boshrelase from 29.6.0 to 30.4.0. Note that newer prometheus boshrelease packages are now hosted on github releases and not `bosh.io`.
This has been deployed to dev03 successfully. Job details: https://deployer.dev03.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/113
---
> 187651125 promotheus bosh release upgrade

- concourse/pipelines/fast-startup-and-shutdown-cf-env.yml
dev03 was failing to fetch the image without this tag, but works with it
---
> Add image tag to concourse-keyval-resource in startup/shutdown pipelines

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
This uses the boshrelease of the cdn broker using the newer brokerapi (v10)
Related PRs: 
* https://github.com/alphagov/paas-cdn-broker/pull/84
* https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/77
Build job to make the boshrelease tarball: https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/cdn-broker-release/jobs/build-dev-release/builds/114
---
> Use boshrelease of cdn broker using brokerapi v10

- Makefile
We should always run the upload-psn-secrets script, which will upload a dummy secret in non-prod envs.
Without this secret being set to something, the PSN terraform step fails to interpolate the template
Same with mailchimp API keys for the deploy-paas-admin step
---
> Upload PSN and mailchimp secrets in non-prod envs

- manifests/app-autoscaler/operations.d/060-add-postgres-release.yml
What
----
We need to specify a URL for the postgres release in order to deploy app-autoscaler
---
> Specify URL and version for cloudfoundry postgres release for app-autoscaler.

- .github/workflows/generate_buildpack_bump_pr.yml
- .github/workflows/test_on_pr.yml
- common-go/basic_logit_client/go.mod
- concourse/pipelines/create-cloudfoundry.yml
- config/cloudwatch-exporter/config.yml
- go.mod
- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/720-cdn-broker.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/operations.d/760-sqs-broker.yml
- platform-tests/example-apps/app-autoscaler-cpu-usage/manifest.yml
- platform-tests/example-apps/healthcheck-pinger/manifest.yml
- platform-tests/example-apps/healthcheck-ponger/manifest.yml
- platform-tests/example-apps/healthcheck/go.mod
- platform-tests/example-apps/healthcheck/manifest.yml
- platform-tests/example-apps/http-tester/go.mod
- platform-tests/example-apps/http-tester/manifest.yml
- platform-tests/example-apps/logging-pipeline/manifest.yml
- tools/metrics/go.mod
- tools/metrics/manifest.yml
- tools/pipecleaner/go.mod
- tools/user_emails/go.mod
What
----
Update go from 1.21 to 1.22
> Initially intended to upgrade go to 1.23, but reverted to 1.22 due to current buildpack compatibility. Buildpack doesn't yet support 1.23.
Related PRs
----
https://github.com/alphagov/paas-cf/pull/3975 
https://github.com/alphagov/paas-bootstrap/pull/900 
https://github.com/alphagov/paas-prometheus-endpoints/pull/17 
https://github.com/alphagov/paas-auditor/pull/28 
https://github.com/alphagov/paas-accounts/pull/49 
https://github.com/alphagov/paas-elasticache-broker-boshrelease/pull/40 
https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/78
https://github.com/alphagov/paas-s3-broker-boshrelease/commit/ae18cbe3f5cca94a498bcd9ea01c7d52b39d5b6c  
https://github.com/alphagov/paas-sqs-broker-boshrelease/pull/29  
How to review
-------------
* …
> Upgrade Go version to 1.22
