concourse/scripts/tf-destroy.sh
concourse/tasks/tf-destroy.yml

We changed the Terraform container to use Alpine Linux instead of Ubuntu in
alphagov/paas-docker-terraform#6 which doesn't contain `bash` and causes the
destroy pipeline to fail:
➜  paas-cf git:(master) ./concourse/scripts/destroy.sh dcarley
…
unpaused 'destroy-cf'
using version of resource found in cache
using version of resource found in cache
initializing with docker:///governmentpaas/docker-terraform
running bash -c paas-cf/concourse/scripts/tf-destroy.sh
proc_starter: ExecAsUser: system: program 'bash' was not found in $PATH: exec: "bash": executable file not found in $PATH
failed
So we need to use plain `sh` instead. There aren't any `bash` specific features
in this script. Technically the shebang could be left, because calling `sh -c`
bypasses it, but we should keep them the same …

[#109030954 #109540406] Use sh instead of bash for tf-destroy.sh

---

Vagrantfile

Looks like a vim whoopsie that repeated the text three times. This was fixed
in #6, but the commits were lost just prior to merging.

[#109515840] Fix typo in Vagrantfile vm.box

---

.gitignore

Vagrant creates this when you bring a up a box using the `Vagrantfile` in
this repo. The directory contains state and should never be committed back.

[#109515840] Add .vagrant/ to .gitignore

---

README.md

I don't think that these are needed. I suspect that they were copied from the
alphagov/cf-terraform instructions, where we ran Terraform locally on our own
machines.
We're now running Terraform from within Concourse and setting the environment
variables for each task in the pipeline:
params:
DEPLOY_ENV: {{deploy_env}}
AWS_DEFAULT_REGION: {{aws_region}}
AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
TF_VAR_AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
TF_VAR_AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
The prefixed and non-prefixed environment variables within in the task are both
set from `vars` that are passed from non-prefixed environment variables on your
local machine:
➜  paas-cf git:(remove_tf_var) ✗ ack AWS_ …

[#109515840] Remove TF_VAR_ environment vars from README

---

Vagrantfile

No story ID, because I'm on review duty.
These are like "getting started" instructions when you create a new
`Vagrantfile` with `vagrant init`. You can find the same information in the
Vagrant documentation so I don't think it's useful to clutter this file:
- https://docs.vagrantup.com/v2/
To ensure that we are all using the same version of Concourse. This is the
latest version box available from Atlas and I have tested it with the
`create-deployer` pipeline in `master`.
- https://atlas.hashicorp.com/concourse/boxes/lite
On important change, if you were using 0.68.0 previously, is that `fly hijack`
now sets the correct PWD and environment variables for a job. Which
makes debugging failed jobs much easier.

Pin concourse/lite version and remove comments

---

README.md

The variables themselves were removed in 278e081, but this reference to
them was left behind.

Remove references to terraform vars from README

---

README.md
concourse/pipelines/create-deployer.yml
concourse/pipelines/destroy-deployer.yml
concourse/scripts/create-deployer.sh
concourse/scripts/deploy-pipeline.sh
concourse/scripts/destroy-deployer.sh
concourse/scripts/tf-destroy.sh
terraform/concourse/security_group.tf

This PR adds more steps to destroy deployer pipeline. Right now it will:
- get terraform and bosh-init states from S3 bucket associated to specified environment 
- destroy deployer Concourse using bosh-init
- destroy RDS, subnet etc. using terraform
- destroy VPC using terraform
- delete state bucket
We had to refactor create Concourse pipeline to be able to get generated deployment manifest and also fix bugs. 
Provision concourse environment first. If you have concourse provisioned already you have to run it anyway to export deployment manifest.
```
BRANCH=109823030_destroy_concourse LOG_LEVEL=DEBUG \
CONCOURSE_ATC_PASSWORD=atcpassword CONCOURSE_DB_PASSWORD=dbpassword \
./concourse/scripts/create-deployer.sh env_name
```
Try to destroy it:
```
LOG_LEVEL=DEBUG …
```

[#109823030] destroy concourse pipeline

---

README.md

The & in the URL needs quoting, otherwise it runs that line in a job and the
variable isn't set correctly.

Quote fly URL

---

concourse/pipelines/destroy-microbosh.yml

[#109060102 Load terraform outputs in destroy microbosh](https://www.pivotaltracker.com/story/show/109060102)
We need to load all the terraform outputs from vpc and concourse required for the terraform destroy in concourse. Specifically, we need the concourse security group which allows concourse to access the machines deployed with bosh init.
This fixes the error:
```
Required variable not set: concourse_security_group_id
```
Deploy bosh as described in the README and destroy it.

[#109060102] Load terraform outputs in destroy microbosh

---

concourse/pipelines/destroy-microbosh.yml

https://www.pivotaltracker.com/story/show/110238314
Ensure that terraform uses IAM to destory Microbosh.
Not much to do here since only the Destroy microbosh uses AWS Credentials at the moment so we've fixed that
This PR has been written in the following context:
* I want to:
* Use the IAM Profile rather than my AWS Credentials to securely manage AWS resources
* Follow the [README]( https://github.com/alphagov/paas-cf#usage) up to `Destroy a microbosh with bosh-init from concourse` 
* Any man, woman or child who is connected to the internet except @actionjack and @mtekel who worked on this PR.

[#110238314] Ensure that terraform uses IAM roles

---

concourse/pipelines/create-microbosh.yml
concourse/scripts/s3init.sh

[Use IAM profiles/roles in new Concourse pipeline](https://www.pivotaltracker.com/projects/1275640/stories/110238314)
Enhance s3init script to support using instance profile provided credentials.
Remove explicit usage of AWS credentials in the create bosh init pipeline.
Deploy concourse and bosh init pipeline. Run `bootstrap-s3-state` job. Watch the output and check the bucket for objects being created/not updated.
Anyone but @mtekel

[#110238314] s3init supports instance profile

---

concourse/scripts/s3init.sh

https://www.pivotaltracker.com/story/show/110238314
What
----
After implementing IAM profile in s3init, it would fail using static credentials
because it tries to add the x-amz-security-token header.
To fix it, we must not add that header to the request when using static
credentials.
How to test it?
---------------
Run the create-deployer pipeline in a local vagrant, which will use s3init with
static credentials
Who?
----

[#110238314] Fix bug in s3init when using static credentials

---

README.md
concourse/pipelines/create-deployer.yml
concourse/pipelines/create-microbosh.yml
concourse/scripts/s3init.sh

[#109060102 Create bootstrap pipeline to deploy BOSH](https://www.pivotaltracker.com/story/show/109060102)
What
----
Using specific containers with the minimum dependencies will help to
understand and track the dependencies added to different tools.
Requirements
------------------
#24 should be merged first to cover a bugfix in s3init.sh
Scope
-----
We use the specific containers `curl-ssl` to do curl and openssl logic and
ruby 2.2.3 instead of the multipurpose toolbox.
We use sh instead of bash in s3init script as the curl-ssl container does
not include bash.
How to test this?
Test both pipelines create-deployer and create-microbosh as described in the
README.
It can be pipelines in an already deployed environment, and it is not needed
to wait for the bosh-init tasks to …

[#109060102] Use specific containers in concourse tasks

---

README.md

I tried installing Fly inside Vagrant; it's preferable to run it on your host machine (i.e. not in Vagrant).

Clarify where to install Fly

---

manifests/concourse-base.yml

In order to pull in the fix for concourse/concourse#167 which made
`bosh-init` hang when unmounting disks from the "Deployer Concourse"
instance if there were any changes to the manifest.
This now matches the version of concourse/lite that we're using for the
"Bootstrap Concourse". We shouldn't be affected by any of the
backwards-incompatible entries in the changelog, but you will want to run
`fly sync`:
- http://concourse.ci/release-notes.html#v0.70.0
As a minimum:
1. Deploy the pipeline from this branch to your Bootstrap Concourse: `BRANCH=111149770-upgrade_deployer_concourse ./vagrant/deploy.sh`
1. Run the `create-deployer` pipeline from your Bootstrap Concourse.
1. Check that you can still login to the Deployer Concourse and that you can run a pipeline.
If you want to test whether it …

[#111149770] Upgrade deployer Concourse to 0.70.0

---

README.md
manifests/concourse-base.yml
terraform/concourse/elastic_ip.tf
terraform/concourse/elb.tf
terraform/concourse/outputs.tf
terraform/concourse/security_group.tf
terraform/globals.tf

Allow external access to Concourse via HTTPS only.
We create an ELB with HTTPS in front of Concourse and close external access to Concourse via HTTP 8080.
The default certificate used is the wildcard self-signed certificate stored in `paas-pass` and uploaded manually to AWS.
* Build a new Concourse and connect to `https://${DEPLOY_ENV}-concourse.cf.paas.alphagov.co.uk/`.
* Check that insecure access via HTTP 8080 is closed.
* Note: the certificate is self-signed so fly won't accept it unless you login with the -k option
Anyone but @actionjack or @saliceti

[#109878560] Secure external access to concourse

---

README.md
vagrant/Vagrantfile
vagrant/concourse_post_deploy.sh

**What**
We want to stop using the insecure deployer key
This PR should reviewed in the following context:
* We are no longer using the insecure deployer key
* It is still possible to ssh to your deployed vagrant machine
* We are not using the vagrant insecure default public key
**How to test this PR**
Check the branch out, run the deployment script.
```
export VAGRANT_LOG=info
./vagrant/deploy.sh
```
Verify the following appears in the log messages
```
Key inserted! Disconnecting and reconnecting using new SSH key...
```
verify you can ssh to the vagrant instance
```
(cd vagrant && vagrant ssh)
```
Verify the insecure deployer key does not appear in the /home/ubuntu/.ssh/authorized_keys file
```
cat .ssh/authorized_keys
```
**Who should review this PR** …

[#109897246] Stop vagrant using the insecure deployer key

---

terraform/concourse/elb.tf

[#109878560 Secure access to the Deployer Concourse ](https://www.pivotaltracker.com/story/show/109878560)
When running `fly hijack` command, it promotes the connection to
WebSockets for the interactive communication.
But ELB using HTTP/HTTPS protocols do not support WebSockets, so the
feature is broken.
The solution is to use the protocols SSL for LoadBalancer protocol and
TCP for the instance protocol.
This PR changes the protocols for the ELB used for SSL termination in front of concourse.
> Note: you can apply this change over a already deployed concourse by changing the variable `export BRANCH=$(git rev-parse --abbrev-ref HEAD)` and running again `./vagrant/deploy.sh <env>` to apply the changes in terraform.
1. Deploy concourse as described in the README. Remember change the BRANCH …

[#109878560] TCP+SSL in ELB allows websockets for concourse

---

README.md

So that I paste the command into my shell (zsh) without it automatically
escaping the curly braces.

Quote string with variable interpolation in README

---

concourse/pipelines/create-microbosh.yml

We don't (yet) want this pipeline to be triggered on every commit to
git. This is different to all the other pipelines and therefore causes
surprise.

Don't trigger create-microbosh from paas-cf

---

concourse/pipelines/create-microbosh.yml
concourse/pipelines/destroy-microbosh.yml

I suspect this was broken by 05b309d.
This was erroring in the destroy pipeline with a missing file error, and
was failing to upload the updates state in the create pipeline. This is
due to an incorrect path in the put that was pointing at the output of
the `get` step, and not the output of the task itself.
Each concourse job runs in a working directory. Within that, a directory
is created for each get and task. For each input to a task, the
corresponding directory is copied from the working directory into the
task's directory before the task is run (additionally, each output is
copied from the tasks directory up to the working directory after the
task has run).  Because these tasks modify files in their directory, and
don't have any outputs, it's necessary to reference the file within …

Fix put of bosh state in create/destroy microbosh pipelines

---

concourse/pipelines/create-microbosh.yml

s3init currently also downloads the file. That's why your init file
and main file name have to be different files. Otherwise you'll over-
write your init file in the checking process and instead initialize
with the file containing S3 API reply.

[#110234556] Fix bosh secret generation

---

README.md

No need to type in deployment_environment name again, as it is set
already in $DEPLOY_ENV variable used one line above. Update README
to reflect this. This way we can also simply copy & paste the
command from README directly.

Use $DEPLOY_ENV instead of <deploy_env> in README

---

README.md
concourse/pipelines/destroy-cloudfoundry.yml
concourse/scripts/destroy-cloudfoundry.sh

Destroy the Cloudfoundry deployment that was created by [initiate CF deployment from Concourse](https://www.pivotaltracker.com/story/show/110234556) story.
This pipeline uses microbosh and provided environment  name to delete CF deployment. Next it pulls CF terraform state from s3 bucket and destroys all TF resources that were created by CF deployment pipeline. Last step is to upload TF state to state bucket. 
This assumes that you have a working CF deployment already and $FLY_TARGET exported.
```
BRANCH=111293784_cf_destroy concourse/scripts/destroy-cloudfoundry.sh <env_name>
```
Anyone but @combor and @saliceti

[#111293784] Delete CF deployment from Concourse

---

README.md
concourse/pipelines/create-deployer.yml
concourse/pipelines/create-microbosh.yml
concourse/pipelines/destroy-deployer.yml
concourse/scripts/create-deployer.sh
concourse/scripts/create-microbosh.sh
concourse/scripts/destroy-deployer.sh
concourse/scripts/destroy-microbosh.sh
manifests/concourse-base.yml
terraform/bosh/outputs.tf
terraform/bosh/variables.tf
terraform/vpc/outputs.tf
terraform/vpc/ssh-key-pair.tf

https://www.pivotaltracker.com/story/show/109897246
**What**
We want to stop using the insecure deployer key
This PR should reviewed in the following context:
* We are no longer using the insecure deployer key for deployer vm
* It is still possible to ssh to the deployer vm
**How to test this PR**
1. Check the branch out
2. run the deployment as described in the README.
You can check the PR as you deploy, so:
Once the concourse deployed is created (`create-deployer` pipeline):
* check your concourse/0 vm does not use the insecure-deployer keypair by checking in the AWS interface.
* Verify you can ssh into the concourse vm: Find and download the `id_rsa` in the s3 state bucket, then ssh to the instance using this key. You can reuse the `s3get.sh` script: …

[#110234556] Stop using the insecure deployer

---

README.md

There was an apparent error in the README.

Specify correct AWS region for boostrap concourse

---

vagrant/Vagrantfile

Which introduced the `config.ssh.insert_key` option and enabled it by
default. We rely on this to replace the default insecure public key in the
concourse/lite AMI and we go to some additional effort in 67295ed to remove
any other keys.
You'll now get a more explanatory error message if you're using an older
version, rather than the following:
==> default: Mounting /var/vcap/data/garden on to ephemeral disk...
==> default: Setting up concourse basic auth as admin : ******
Permission denied (publickey).
Setting up SSH tunnel to concourse...
Permission denied (publickey).

Require Vagrant version 1.7.0 or later

---

concourse/pipelines/destroy-deployer.yml

what
----
In #43 a bug has been introduced causing the destroy-deployer pipeline fail with:
```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.
Errors:
* file: open /tmp/build/965b4427-bcc6-4015-57f4-4bf3980ef0e6/paas-cf/terraform/vpc/id_rsa.pub: no such file or directory in:
${file("${path.module}/id_rsa.pub")}
```
The reason is that VPC terraform destroy requires a id_rsa.pub file
Terraform will read from the id_rsa.pub, even when destroying because
the file is read during variable interpolation. If the
file is missing, it will fail.
Because that, we need to create a dummy file with the same name.
how to review
-------------
Try to run `destroy-deployer`  pipeline
who
---
anyone but @keymon

[#110234556] Fix error when running vpc terraform destroy due missing id_rsa.pub file

---

concourse/pipelines/create-deployer.yml
concourse/pipelines/destroy-deployer.yml
manifests/concourse-base.yml
vagrant/Vagrantfile

Remove most usage of access keys  from the bootstrap-concourse pipelines.
This updates the `{create,destroy}-deployer` pipelines to use IAM profiles for Terraform and the s3init scripts
The only thing left using access keys after this is the concourse resources themselves. These will be switched over to use profiles in another story.
This PR is the companion to https://github.gds/government-paas/terraform-iam/pull/5 which defines the roles in use here.  I've manually created roles with matching permissions in the trial account so that this can be tested.
Deploy a new concourse-lite instance (it'll need to be newly provisioned from this branch in order to be given the necessary role):
```
BRANCH=bootstrap_concourse_role ./vagrant/deploy.sh $DEPLOY_ENV
```
Run both the create-deployer and …

[#111303414] Use IAM role in bootstrap-concourse machine

---

README.md

These instructions were no longer working because:
- 48db141 changed the hostname from an EIP (which you could SSH to) to an
ELB (which only forwards HTTP[S])
- 3a5e3f1 (and preceding commits) changed the SSH key that's used

[#109878560 #109897246] README: De-dupe incorrect SSH instructions

---

README.md

Using `ProxyCommand` is preferable to `ForwardAgent` because it doesn't
expose your local agent to other users on the remote machine.
This is a reasonable blog post, for further reading on about the issue:
- https://heipei.github.io/2015/02/26/SSH-Agent-Forwarding-considered-harmful/

README: Replace ForwardAgent with ProxyCommand

---

concourse/pipelines/create-microbosh.yml

If the bosh-init deployment job fails for some reason, we still want to
push the state file so that future runs know about the VM if it's been
created, and can retry without conflicting with this VM.

Ensure bosh-init state is pushed on failure.

---

concourse/pipelines/deploy-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml

This removes the remaining usage of access keys in the deployer-concourse pipelines
This does not cover removing them from the concourse resources themselves (covered in a separate story), or from the cloudfoundry manifest (also covered in a separate story).
This relies on some additional permissions that are defined in https://github.gds/government-paas/terraform-iam/pull/6, and have been manually applied to the trial account.
Run the create-microbosh and deploy-cloudfoundry pipelines from this branch and verify that they run successfully.
Run the corresponding destroy pipelines and verify that they also work as expected.
Anyone but me.

[#111778374] Remove use of access keys in deployer concourse pipelines

---

concourse/pipelines/create-deployer.yml
concourse/pipelines/create-microbosh.yml
concourse/pipelines/deploy-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/destroy-deployer.yml
concourse/pipelines/destroy-microbosh.yml
concourse/scripts/create-deployer.sh
concourse/scripts/create-microbosh.sh
concourse/scripts/destroy-cloudfoundry.sh
concourse/scripts/destroy-deployer.sh
concourse/scripts/destroy-microbosh.sh
manifests/concourse-base.yml
vagrant/Vagrantfile
vagrant/post-deploy.d/00-remove-insecure-keys.sh
vagrant/post-deploy.d/10-mount-additional-ephemeral-disk.sh
vagrant/post-deploy.d/20-setup-basic-auth.sh
vagrant/post-deploy.d/30-add-custom-resources.py

[#111760326 Use custom resources for S3 & Semver using IAM profiles](https://www.pivotaltracker.com/story/show/111760326)
We'd like to use custom resources for S3 and Semver because this will allow us to use IAM profiles for provisioning. We will use the images generated automatically in docker hub: https://hub.docker.com/r/governmentpaas/s3-resource/builds/ and https://hub.docker.com/r/governmentpaas/semver-resource/builds/, which where setup in https://github.com/alphagov/paas-s3-resource/pull/2 and https://github.com/alphagov/paas-semver-resource/pull/3
We will also stop using static AWS credentials in the pipelines for these resources.
This PR should be reviewed in this context:
* I want to add the new resources in concourse lite, using a shell provisioner to change the required …

[#111760326] use custom s3 and semver resources with iam support

---

README.md
concourse/pipelines/deploy-cloudfoundry.yml
concourse/scripts/deploy-cloudfoundry.sh
manifests/cf-manifest/build_manifest.sh
manifests/cf-manifest/deployments/020-cf-resource-pools.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/040-cf-properties.yml
manifests/cf-manifest/deployments/aws/000-cf-infrastructure.yml
manifests/cf-manifest/spec/base_properties_spec.rb
manifests/cf-manifest/spec/fixtures/aws-secrets.yml
manifests/cf-manifest/spec/resource_pools_spec.rb
manifests/cf-manifest/spec/support/manifest_helpers.rb

Avoid requiring AWS access keys in Cloud Foundry and use IAM profile instead. This applies to the cloud controller so it can read and write from S3 buckets.
Also fixes an issue with the bucket names in the CF manifest.
Deploy Cloud Foundry from scratch. It should deploy successfully and be able to read and write to S3 buckets. For example you can check it has created content in bucket `<environment>-cf-buildpacks`.
You should be able to reuse an existing Cloud foundry. Delete the buckets first and run the full pipeline, including Terraform.
Anyone but @alext or @saliceti

[#111523754] Cloudfoundry instance profiles

---

README.md

At the moment it lists the last build, which may be a development branch
that is failing. We only really care about the stability of `master`.

[#112135729] README: Restrict Travis CI badge to master

---

README.md
concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/concourse-lite-self-terminate.yml
concourse/pipelines/deploy-cloudfoundry.yml
concourse/scripts/concourse-lite-self-terminate.sh
concourse/scripts/deploy-cloudfoundry.sh
vagrant/deploy.sh

[#108441228 Automatically shutdown dev environments at night / weekends](https://www.pivotaltracker.com/story/show/108441228)
The PR https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/14 should be merged first and we should update the container used in `./concourse/pipelines/ticking-time-bomb.yml`
Given the size of a deployed Cloud Foundry environment and the associated cost of the VMs we want to shut down all development environments at night and over weekends to minimise the overall cost of infrastructure. 
It is acceptable to leave a small number of machines running (e.g. BOSH and Concourse) if this expedites the recovery of the development environment in the morning.
This PR should be reviewed in this context:
* I want to add a job to delete the cloudfoundry deployment:
* …

[#108441228] Add pipelines to automatically delete cloudfoundry deployment and concourse-lite at night

---

concourse/scripts/concourse-lite-self-terminate.sh
concourse/scripts/deploy-cloudfoundry.sh

As per #58, the script deplo-pipeline.sh will do the unpause for us, so it is no needed for the self-terminate concourse lite or
the deploy-cloudfoundry.
Also we are sure that deploy-cloudfoundry uses th right fly command path
for deleteing the autodelete pipeline.
Check #59 for instructions
THIS PR IS ON FIRE!!!

[#108441288] Remove unnecesary unpause in setup pipeline scripts

---

README.md

In 6b0ef65 and 2e1cc94 we stopped recommending that people download the
`fly` binary to `/usr/local/bin`. Instead `vagrant/deploy.sh` downloads the
binary into your PWD and sets `FLY_CMD`. This command in the README is the
last reference to a `fly` binary on your `PATH`.
Run the commands in the modified codeblock.
Anyone but @dcarley

[#112135729] README: Replace `fly` with `${FLY_CMD}`

---

terraform/cloudfoundry/security-groups.tf

As a part of "[Test that the CF deployment is basically sound](https://www.pivotaltracker.com/n/projects/1275640)" story we are rising this PR to fix Diego logging.
NAT gateway IP is not included in inbound rules for web access security
group. All requests from internal components are being resolved to
external api IP. To allow connections between multiple CF services we
have to allow such traffic.
You need to have working CF deployment.
- push your app
```
echo hello > index.html && cf push static -b staticfile_buildpack
```
- tail for logs
```
cf logs static
```
- request your index file
```
curl static.piotr.cf.paas.alphagov.co.uk
```
You should see access logs appearing on your screen.
Anyone but @combor and @mtekel

[#111758188] Add NAT gateway to web security group

---

README.md

Add documentation on failures with many ssh keys

---

manifests/cf-manifest/deployments/030-cf-jobs.yml

Clean up CF manifest system and app domains a bit. Ensure app domain is different from system domain (else you can deploy e.g. `api` called app, which then gets traffic meant for CF api). Add configuration for smoketests.
Deploy or apply against existing evironment. After deployment, `bosh run errand smoke_tests`. They should pass. You can also run tests, `cd manifests/cf-manifest; bundle exec rspec`. They should also pass.

[#111758188] Enable smoketests

---

README.md

Rewrite the Bootstrap Concourse and Deployer Concourse sections of the README so that they're easier to read. See the commit messages for more details. The second to last commit is quite large, but due to restructuring it wasn't easy to break it down any further. If this gets merged then I'll do the same to the BOSH and Cloud Foundry sections.
View the rendered README file in the branch.
Not @dcarley

[#112135729] Simplify README pt1

---

manifests/cf-manifest/deployments/030-cf-jobs.yml

api_worker instances need access to AWS as well, as they are essentially
part of CF API and need to do same tasks as api instances. Moreover,
some tasks (like handling `cf copy-source`) are exclusive to workers and
will fail without IAM role. Thus change instance type to same as API.
`cf copy-source` is used in acceptance tests, so without this PR they fail on that test.

[#109035334] IAM for api_workers as well

---

concourse/scripts/create-microbosh.sh
concourse/scripts/deploy-cloudfoundry.sh
concourse/scripts/destroy-cloudfoundry.sh
concourse/scripts/destroy-microbosh.sh

This variable doesn't appear to be used by the pipeline YAML files. Removing
it will make it simpler to combine the create and destroy scripts.
➜  paas-cf git:(master) ack pipeline_name
concourse/scripts/create-microbosh.sh
18:pipeline_name: ${pipeline}
concourse/scripts/deploy-cloudfoundry.sh
22:pipeline_name: ${pipeline}
concourse/scripts/destroy-cloudfoundry.sh
20:pipeline_name: ${pipeline}
concourse/scripts/destroy-microbosh.sh
18:pipeline_name: ${pipeline}
Ensure that you have a Deployer Concourse with all of the pipelines deployed from `master`. Change to this branch and re-deploy the pipelines:
```
./concourse/scripts/create-microbosh.sh
./concourse/scripts/deploy-cloudfoundry.sh
./concourse/scripts/destroy-cloudfoundry.sh
./concourse/scripts/destroy-microbosh.sh
```
You should …

[#112135729] Remove pipeline_name var from BOSH/CF scripts

---

manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/aws/000-cf-infrastructure.yml

What
----
In #49 we replaced DEA with diego. We don't need anymore the properties
and templates defined in the manifest.
How to test this?
-------------------
Try to redeploy the manifest with bosh, bosh client should report that
there are no be changes to the cluster.
Who?
----
Anyone but @keymon or @timmow

[#111428592] Remove unnused DEA configuration in CF manifest

---

concourse/pipelines/deploy-cloudfoundry.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/900-cf-tests.yml

[#109035334 Implement acceptance tests on the CF deployment](https://www.pivotaltracker.com/story/show/109035334)
What
----
The objective is to implement a set of acceptance tests to ensure that the deployment was successful and that the platform functions as expected. Given that we have started with a vanilla install, we should be able to use the existing CF acceptance tests and we will build on these as we add functionality.
Context
-------
The PR should be reviewed in this context:
* I want to add the required configuration to run the basic acceptance tests.
* I want to add a job that runs the smoke tests after deployment and is triggered
automatically after any successful deployment.
* I want to add a job that runs the acceptance tests after deployment, altough
not triggered …

[#109035334] Implement acceptance and smoke tests

---

manifests/cf-manifest/deployments/040-cf-properties.yml
manifests/cf-manifest/deployments/041-security-groups.yml

https://www.pivotaltracker.com/story/show/112499245
what?
-----
As part of investigating the acceptance tests, we discovered that the
security groups where not working as expected. Actually, we were not
blocking any traffic after migrating to diego.
The reason is some misconfiguration in the garden. The garden release
must be configure to block the traffic by default, and the security groups
will open access as needed.
Context
-------
In this PR we will:
* Group all the security group configuration in one file to simplify the
config management.
* Block all traffic by default in garden
How to test this?
Without the PR, the app containers can connect to any IP in the internal
network. With the PR, only public IPs.
1. Deploy CF as described in the README.md
2. start some …

[#112499245] Setup Garden to block all outgoing traffic to fix security groups.

---

manifests/cf-manifest/deployments/900-cf-tests.yml

https://www.pivotaltracker.com/story/show/112499245
Requisites
----------
The PR #75 and #80  must be merge before this one. After merge, rebase
this branch.
what
----
We want to enable the acceptance tests that work on our current setup.
security groups is one of them
Scope
-----
Enables the seurity group acceptance tests in the acceptance test
errand.
This test requires garden to restrict traffic (PR #80) by default and a
working loggregator. Note that the loggregator might have problems if
the environment is deployed in parallel. Check the comments in the story.
How to test it?
--------------
Deploy CF and run trigger the acceptance_tests in the pipeline.
This test requires garden to restrict traffic (PR #80) by default and a
working loggregator. Note that the loggregator might have …

[#112499245] Enable the security groups acceptance test

---

vagrant/deploy.sh

Concourse lists the pipelines in the side menu in the order they were
added. It also shows the first pipeline in the list when you visit the
root URL.  Given the first pipeline that's normally used is the
create-deployer one, it makes sense for this one to be first in the
list.

Reorder the pipelines in the bootstrap concourse

---

concourse/pipelines/deploy-cloudfoundry.yml
concourse/scripts/bosh_ensure_uploaded.sh
concourse/scripts/bosh_list_releases.rb
concourse/scripts/bosh_list_stemcells.rb

We would like to remove unnecessary downloads of releases and stemcell during every run of **deploy** job.   Pivotal story: [Implement Workaround for caching issue with download of concourse resources](https://www.pivotaltracker.com/story/show/112581575) 
All download tasks are rewritten to call bosh directly and check whether release/stemcell is already uploaded. The helper script is provided to accomplish this. If release is not present, another bosh call triggers download directly on bosh VM so we also skip upload phase. 
Additionally, I have decided to remove bosh-deployment resource as it can't be used in case all releases and stemcells are already uploaded. It is replaced by deployment task. 
- Upload updated pipeline by executing:
```
BRANCH=112581575_skip_release_download …
```

[#112581575] skip release download

---

concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/deploy-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/scripts/deploy-cloudfoundry.sh
concourse/scripts/destroy-cloudfoundry.sh

We prefer to get BOSH password in the pipeline to avoid unnecessary downloads of bosh-secrets.yml to local PC. This PR removes local download and moves password extraction logic to use Concourse resource.  Pivotal card: [Move BOSH password fetch to inside pipeline](https://www.pivotaltracker.com/story/show/112670769)
Please notice that [[#112581575] skip release download](https://github.com/alphagov/paas-cf/pull/82) needs to be merged first.
```
BRANCH=112670769_move_bosh_password_to_pipeline concourse/scripts/deploy-cloudfoundry.sh <env_name>
```
- Trigger the build manually from Concourse GUI
Anyone but @combor

[#112670769] move bosh password fetch to pipeline

---

terraform/concourse/elb.tf

This reverts commit f46ff52b653b80b1ef538207121bfd20192bfde7.
When alphagov/paas-docker-terraform#10 is merged to upgrade Terraform to
0.6.10 then we no longer need this workaround.
alphagov/paas-docker-terraform#10 should be merged first. But if you want to test both together than you can temporarily change all of your pipelines to use the container built from the branch (be sure to undo this later with `git checkout -p`):
```
gsed -ri 's/(docker-terraform)/\1#terraform_0.6.10/' concourse/pipelines/*
```
Deploy the pipelines to the Bootstrap Concourse machine to use this BRANCH:
```
BRANCH=112610295-terraform_elb_sleep ./vagrant/deploy.sh
```
Run both the `create-deployer` and `destroy-deployer` pipelines and confirm that they complete successfully. It's the `concourse-terraform` task …

[#112610295] Revert "Avoid new cert / ELB error"

---

manifests/cf-manifest/deployments/900-cf-tests.yml

https://www.pivotaltracker.com/story/show/112499245
what?
-----
We want to enable all the interesting CAT tests that pass on our current setup. After analysing the tests, we can enable everything but the routing api tests.
Context
-------
In this PR we will:
* Enable the routing tests, but skip the routing API and routing services ones. In latest versions of the acceptance tests, [these tests are moved to other suite](https://github.com/cloudfoundry/cf-acceptance-tests/commit/d7bb879c744295b91425a738c95589e565b6efb7)
* Enable other suites: internet_dependent, logging, operator, and services … 
How to test?
1. Deploy CF as described in the README.md (remember set the `$BRANCH` variable to this branch)
2. After `smoke_tests`, just trigger the `acceptance_tests`
Note that …

[#112499245] Enable rest of optional acceptance tests

---

README.md
concourse/pipelines/create-deployer.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/aws/999-cf-stub.yml
manifests/cf-manifest/spec/base_properties_spec.rb
manifests/cf-manifest/spec/fixtures/terraform/terraform-outputs.yml
terraform/cloudfoundry/dns-records.tf
terraform/cloudfoundry/outputs.tf
terraform/concourse/elb.tf
terraform/dev.tfvars
terraform/globals.tf
terraform/prod.tfvars
terraform/vpc/outputs.tf

In order to prevent apps from potentially overwriting the routes for system components we want apps to be served from a different domain.
This uses the new domain (`cf-apps.paas.alphagov.co.uk`) for hosting apps deployed to Cloudfoundry. This domain has already been created in the trial account, and had DNS delegated.
This PR does not include changing SSL certs used to serve apps (they'll still use the self-signed `*.cf.paas.alphagov.co.uk` cert). This will be addressed in another PR.
As part of this change we've also changed the hostname for the deployer-concourse to `deployer.<env>.cf.paas.alphagov.co.uk` to bring it inline with other components and disambiguate from the bootstrap-concourse.
Deploy a complete environment from this branch, and verify that it all works correctly. Push an …

[#108966132] Use a separate domain for deployed apps.

---

.travis.yml
manifests/cf-manifest/deployments/020-cf-resource-pools.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/040-cf-properties.yml
manifests/cf-manifest/deployments/aws/999-cf-stub.yml
manifests/cf-manifest/spec/fixtures/terraform/terraform-outputs.yml
manifests/cf-manifest/spec/networks_spec.rb
terraform/cloudfoundry/cell-subnet.tf
terraform/cloudfoundry/nat.tf
terraform/cloudfoundry/outputs.tf
terraform/cloudfoundry/variables.tf

This PR adds separation for Diego Cell. It creates new Cell subnet and moves its components from colocated VM to dedicated one. 
- new cell subnet per AZ, ranges from 10.0.20.0 to 10.0.22.0
- separation of rep, garden and rootfs from collocated VM to dedicated one
- new route table association as we need internet to access API and for apps
- extension of tests to include new networks
- Terraform version bump to reflect version in TF container
Use this branch to deploy new CF instance. Run smoke and acceptance tests.
Note that some acceptance tests may fail as they are known to be flaky.
Anyone but @combor and @jimconner

[#112503409] separate subnet for cell

---

concourse/pipelines/destroy-microbosh.yml

The `bosh-terraform-destroy` job in the `destroy-microbosh` pipeline wasn't
being triggered after `bosh-init-delete` had completed. This left you with a
partial environment, until you manually trigger the `bosh-terraform-destroy`
job manually. This was noted in the "pipelines improvements" story and has
surprised me a few times.
We're going to have a story later to look at the `init` and trigger patterns
in all pipelines. This commit just concentrates on making it work, rather
than standardising any of the patterns currently in use.
NB: There is no story for this. I came across this while debugging another issue.
1. Run the `create-microbosh` pipeline.
1. Run the `destroy-microbosh` pipeline.
1. Confirm that all of the jobs (bit boxes) have completed and are green.
Not @dcarley

destroy-microbosh: BOSH delete trigger Terraform

---

manifests/cf-manifest/deployments/000-base-cf-deployment.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml

[Enable parallel job deployment](https://www.pivotaltracker.com/projects/1275640/stories/112501849).
In this PR we:
* Remove per-job bosh update directives and use global settings.
* Set 2 parallel updates per job (using max_in_flight bosh directive). We should update this later based on actual number of instances per job we will have in production.
* Disable serial updates. This enables bosh to deploy jobs in parallel.
* We also disable canaries. This way it's only max_in_flight that controls how many instances of a job are updated in parallel.
* Still deploy consul_z1 job first (both instances in parallel). This is to enable other jobs to cleanly connect to consul immediately when starting deployment. The jobs that need to do this would have to wait for consul server to become available …

Enable parallel job updates

---

manifests/cf-manifest/deployments/aws/000-cf-infrastructure.yml

These are currently r3.xlarge instances, which is massivly overspec for
them now that the cells have been moved to separate machines. While
running the acceptance tests against an environment, the memory stats
look like:
```
total       used       free     shared    buffers     cached
Mem:      31415272     762348   30652924        428      62032     343804
-/+ buffers/cache:     356512   31058760
Swap:     31415100          0   31415100
```
That's 700M of 32Gig. Additionally, when running the tests, the 5min
load average peaked at around 0.5, meaning there's plenty of CPU
headroom.
I considered reducing the size of the cell machines, but decided not to.
When running the tests as above, the memory stats were:
```
total       used       free     shared    buffers     cached
Mem: …
```

[#113158535] Change colocated instances to m3.medium

---

manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/040-cf-properties.yml

[Reconcile etcd config/clusters](https://www.pivotaltracker.com/story/show/112788839)
We have two different types of etcd jobs, which appear to be part of the same cluster but use a different configuration. We should reconcile these into a single cluster of the same configuration.
This PR should be reviewed in the following context:
* I want to
* Add a consul agent to the existing etcd cluster so I can resolve it as `etcd.service.cf.internal`
* I want to apply the correct base configuration to the etcd configuration so it will start up cleanly
* I want to remove the legacy etcd cluster from the co-located machines
* I want to bump the version of etcd to 18 so it's [compatible](https://github.com/cloudfoundry-incubator/diego-cf-compatibility/blob/master/compatibility-v2.csv) with Diego and …

[#112788839] Consolidate etcd clusters

---

README.md
concourse/pipelines/create-deployer.yml
concourse/pipelines/create-microbosh.yml
concourse/pipelines/deploy-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/destroy-deployer.yml
concourse/pipelines/destroy-microbosh.yml
concourse/scripts/pipelines-cloudfoundry.sh
concourse/scripts/pipelines-deployer.sh
concourse/scripts/pipelines-microbosh.sh
manifests/bosh-manifest/deployments/020-compiled-package-cache.yml
manifests/bosh-manifest/reference-bosh-manifest.yml
manifests/bosh-manifest/spec/fixtures/bosh-terraform-outputs.yml
manifests/bosh-manifest/spec/reference_comparison_spec.rb
manifests/cf-manifest/spec/fixtures/terraform/terraform-outputs.yml
terraform/bosh/outputs.tf
terraform/dev.tfvars
terraform/globals.tf
terraform/prod.tfvars
terraform/trial.tfvars
vagrant/Vagrantfile

**What**
We want to use the new AWS Dev account rather than the trial account
This PR should be reviewed in the following context:
* Updating a deployment from master on the trial account with this branch works correctly
* A new deployment suceeeds on the dev account
**How to test this PR**
In the trial account:
Check master out
```
export BRANCH=master
```
Follow the deployment process, or use an existing deployment
Check this branch out
```
export BRANCH=$(git rev-parse --abbrev-ref HEAD)
```
Update the cloud foundry pipelines and check deployment still works sucessfully
In the dev account: 
Alex created some users on the dev accounts on 27/11/2015 - login with these details, and create some access keys.
NB: the concourse url has changed from
``` …
```

[#110662576] Move deployment to new Dev account

---

manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/035-cf-jobs-loggregator.yml
manifests/cf-manifest/deployments/040-cf-properties.yml
manifests/cf-manifest/deployments/aws/000-cf-infrastructure.yml

We observed failures in etcd clustering that were due to a race condition caused by  https://github.com/alphagov/paas-cf/pull/94 and https://github.com/alphagov/paas-cf/pull/93 together.
We now force one etcd node to build before the others. Also, we standardise on DNS resolution via consul to connect to etcd.
Build a new cloud foundry. It should pass smoke tests.
You can also test if the etcd cluster is complete. On an etcd node, run:
```
3bb81497205219e5: name=etcd-z1-0 peerURLs=http://10.0.10.20:7001 clientURLs=http://10.0.10.20:4001
426443662bae1c80: name=etcd-z1-1 peerURLs=http://10.0.10.35:7001 clientURLs=http://10.0.10.35:4001
f2b470f31458c77f: name=etcd-z2-0 peerURLs=http://10.0.11.19:7001 clientURLs=http://10.0.11.19:4001
```
It should return 3 nodes.
Anyone but @saliceti or …

[#113257145] Fix etcd cluster

---

concourse/pipelines/autodelete-cloudfoundry.yml

This PR makes deployment auto-deletion more robust in two ways:
* By deterministically delaying the deletion based on the environment name we ensure that fewer environments will not be auto-deleting at the same time, thus making us less likely to hit the AWS per-account rate limit.
* By using `--force` we cause bosh to attempt to remove the deployment even when some conditions are not met.
Run the `autodelete-cloudfoundry` pipeline on a deployed environment - you should see `Sleeping for X seconds before deletion..` appear in the log, and the deletion will proceed X many seconds later.
Not @jonty or @timmow, who thinks this story was too easy and would like harder ones.

[#112876059] Deployment deletion failures

---

concourse/pipelines/deploy-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/scripts/pipelines-cloudfoundry.sh

It's important that every terraform run uses the latest state file so
that it has an accurate reflection of what's been created etc.
Previously, the `cf.tfstate` used in the deploy-cloudfoundry pipeline was
pinned to the version that has passed the `init` step. This meant that
if a terraform run failed for any reason (eg AWS rate limit), and the
job was restarted, it would not use the updated statefile that included
the partial changes made in the previous run.
This changes the pipeline to use a non-pinned version of the statefile
to ensure it always uses the latest.
It also stops the `init` job from `put`ing the resource (leaving
`s3init.sh` to do the writing). This makes this pipeline consistent with
the others.
Deploy cloudfoundry using this pipeline, and verify that it works. Trigger …

Fix concourse terraform state version pinning.

---

acceptance-tests/README.md
acceptance-tests/example_apps/static_app/index.html
acceptance-tests/generate_test_config.rb
acceptance-tests/run_tests.sh
acceptance-tests/src/acceptance/Godeps/Godeps.json
acceptance-tests/src/acceptance/Godeps/Readme
acceptance-tests/src/acceptance/init_test.go
acceptance-tests/src/acceptance/simple_app_test.go
concourse/pipelines/deploy-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
terraform/cloudfoundry/security-groups.tf
terraform/cloudfoundry/variables.tf

We need to put in place a framework to run our own set of acceptance tests and fit it into the pipeline for deploying an environment. These are in addition to the upstream acceptance-tests.
These are implemented using [ginkgo](http://onsi.github.io/ginkgo/) so that we can reuse the [upstream test helpers](https://github.com/cloudfoundry-incubator/cf-test-helpers).
At the moment, the test only include a POC test that pushed a simple static app, and verifies that it works. This test can be removed once we've added some real tests here.
Deploy cloudfoundry from this branch and verify that the deployment completes successfully, and that these acceptance tests are triggered, and pass.
Anyone but @actionjack and myself.

[#112503901] Implement Custom Acceptance Test Framework

---

acceptance-tests/generate_test_config.rb
concourse/pipelines/deploy-cloudfoundry.yml
concourse/scripts/generate-cf-certs.sh
manifests/cf-manifest/deployments/900-cf-tests.yml

Replace hardcoded domain name used for router certificate generation with dynamic names based upon cf_root_domain and cf_apps_domain terraform variables.
In order to simplify the concourse pipelines, certificates are now all stored within a single tarball which is extracted by subsequent pipeline stages.
* Deploy an environment as normal by following the instructions in the README.md 
* Confirm that smoke tests complete successfully during deployment.
* Try pushing an app to be extra-sure that things are OK.
* Examine the certificate details for https://api.<env>.dev.paas.alphagov.co.uk and confirm that both cf_root_domain and cf_apps_domain are listed as subject-alternative-name fields within the certificate.
Anyone on the team except @alext or myself

[#113432925] Ensure correct domain is used in Generated SSL Certs.

---

manifests/bosh-manifest/deployments/010-bosh-template.yml
manifests/bosh-manifest/deployments/aws/010-bosh-aws-cpi.yml
manifests/bosh-manifest/deployments/aws/090-bosh-aws-stub.yml
manifests/bosh-manifest/reference-bosh-manifest.yml
manifests/concourse-base.yml

[Follow up PR for 107477038 - Rate Limit exceeded on AWS when running BOSH](https://www.pivotaltracker.com/story/show/112411703)
**Acceptance Criteria**
We have upgrade to latest bosh release, and test that we are not hitting rate limit.
This PR should be reviewed in the following context:
* I want to:
* Use a newer version of the [bosh-aws-cpi](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/releases/tag/v44) release that exposes the `AWS` `max_retries` option
* Use a newer version of the [bosh release](https://bosh.io/releases/github.com/cloudfoundry/bosh?version=253) release that has  v2.1.1 (tag v44) of bosh-aws-release gem that exposes the `AWS` `max_retries` option
* Set max retries so that the cloud provider and bosh-init will both try 8 times before failing
* Update …

[#112411703] Fix Rate Limit exceeded error on AWS when running BOSH

---

terraform/trial.tfvars
vagrant/Vagrantfile

We're no longer deploying into this account, so these are no longer
needed.

[#113352221] Remove trial AWS account details.

---

README.md
concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/bosh-cli/bosh-cli.yml
concourse/pipelines/deploy-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/scripts/bosh-cli.sh
concourse/scripts/bosh_ensure_uploaded.sh
concourse/scripts/bosh_login.sh
terraform/concourse/elb.tf

We want to be able to easily use bosh cli commands (including `bosh ssh`) against our deployed µBOSH.
This adds a script that pushes a one-off task to concourse that sets up bosh credentials, target and deployment. It then intercepts (hijacks) that container to provide an interactive session with the bosh CLI available.
We've had to increase the `idle_timeout` for the concourse ELB to 600 seconds to prevent sessions being dropped after 60 seconds of inactivity.
This also updates all the pipelines that use the bosh CLI to use the new docker container instead of using the bosh deployment resource container in a way that wasn't intended.
Re-run the create-deployer pipeline to apply the ELB timeout change. Deploy cloudfoundry.
Run the bosh cli script:
```
./concourse/scripts/bosh-cli.sh …
```

[#112908839] Workflow for accessing Bosh using CLI

---

concourse/pipelines/autodelete-cloudfoundry.yml

The delete task was missing the paas-cf input, so couldn't find the
bosh-login script. This was missed in d282c21.

Fix autodelete pipeline.

---

manifests/cf-manifest/deployments/900-cf-tests.yml

We found the test that [allows previously-blocked ip traffic after applying a security group, and re-blocks it when the group is removed](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/security_groups/running_security_groups_test.go#L80) to fail sometimes in unpredictable ways.
We are uncertain what is the root cause of those failures and thus we decided to upgrade CF release to check whether it will improve test stability. In the time being this test will remain disabled until we will be sure it can be enabled again.
Additionaly, [adding a wildcard route to a domain](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/wildcard_routes_test.go#L82) test fails as it can't [verify SSL certificate for multilevel …

[##113369495] Disable failing acceptance tests

---

concourse/pipelines/deploy-cloudfoundry.yml

We have noticed that pipeline triggering mechanism is not consistent
across deploy pipeline and that terraform job is not triggering
generate-cf-certs job. In this commit we add pipeline-trigger semver
resource across entire pipeline to fix this problem.
Please note that this update has a side effect of triggering every job
that received pipeline-trigger during pipeline upload. It will happen
only for the first time. New trigger
resource is checking for new version and finds it in 'init' job so it
starts.
We have noticed that generate-cf-certs is missing serial groups
parameter that ensures serial execution of jobs in 'deploy' group. That
caused generate-cf-certs job to run in parallel with other jobs in some
edge case circumstances.
1. Ensure that you have a Deployer Concourse and have …

[#114188075] Fix triggers and serial in deploy-cloudfoundry pipeline

---

manifests/cf-manifest/deployments/050-logsearch.yml
terraform/cloudfoundry/network_acls_cf_in.tf

[Log aggregation platform](https://www.pivotaltracker.com/n/projects/1275640/stories/113996323)
Add default logsearch deployment to our CF. We have decided to make this a part of main CF deployment for the sake of simplicity. Otherwise we'd have to update concourse pipelines and template generation scripts to deploy multiple releases, which was out of scope of this story.
Deploy or update your existing deployment. Create ssh tunnel via deployer concourse to kibana:
`ssh -L 5601:10.0.16.49:5601 -i session/id_rsa vcap@$DEPLOYER_CONCOURSE`. You should be able to browse logs and see them appearing in real time.
The [Scarlet Pimpernel](https://en.wikipedia.org/wiki/The_Scarlet_Pimpernel) because _They seek him here, they seek him there_ if he can not be found any member of the core team can …

[#113996323] Add Logsearch

---

concourse/pipelines/deploy-cloudfoundry.yml
concourse/scripts/pipelines-cloudfoundry.sh

This will cause builds to automatically trigger from paas-cf if the environment variable `ENABLE_AUTO_DEPLOY=1` is set. We can be sure that the tests have already passed as we have master protection turned on, so the Travis build must have already passed.
Deploy your development environment on this branch, then `fly get-pipeline deploy-cloudfoundry`. The jobs section should look like this:
````
jobs:
- name: init
serial_groups: [ deploy ]
serial: true
plan:
- get: paas-cf
trigger: false
- task: init
config:
...
````
Specifically you're looking for the `trigger: false` on `paas-cf`.
After this PR is merged the `ci` pipelines need to be updated using `./concourse/scripts/pipelines-cloudfoundry.sh` with `ENABLE_AUTO_DEPLOY=1` set.
Not @jonty.

[#113265403] Optionally trigger builds from paas-cf master

---

manifests/cf-manifest/deployments/020-cf-resource-pools.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/900-cf-tests.yml
manifests/cf-manifest/deployments/aws/000-cf-infrastructure.yml
manifests/cf-manifest/deployments/aws/999-cf-stub.yml
manifests/cf-manifest/spec/fixtures/terraform/terraform-outputs.yml
manifests/cf-manifest/spec/networks_spec.rb
terraform/cloudfoundry/outputs.tf
terraform/globals.tf

This adds subnets in a 3rd AZ, and configures etcd and consul to be deployed across all 3 zones.
It's necessary to run a complete deployment because this is adding new subnets etc. Run all 3 pipelines in order - create-deployer, create-microbosh and deploy-cloudfoundry. Verify that the deployment works. Verify that the etcd and consul clusters are healthy, and are indeed spread across all 3 availability zones:
* etcd: `/var/vcap/packages/etcd/etcdctl member list` (on one of the etcd servers)
* consul: `/var/vcap/packages/consul/bin/consul members | grep server` (on one of the consul servers)
We have seen issues with the etcd cluster not being healthy after upgrading an existing deployment resulting on the loggregator_trafficcontroller jobs failing with an error contacting etcd. This will …

[#1106592863] Deploy etcd and consul across 3 availability zones

---

concourse/pipelines/create-deployer.yml
concourse/pipelines/create-microbosh.yml
concourse/pipelines/deploy-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/destroy-deployer.yml
concourse/pipelines/destroy-microbosh.yml
terraform/cloudfoundry/security-groups.tf

Terraform currently throws an error with this specific combination of
interpolation functions when the EIPs' public IPs can't be known ahead of
time (ie when they're also being created in the same terraform run).
Splitting these into separate ingress blocks avoids runing into this
issue.  See hashicorp/terraform#5301 for more details.
This also includes @saliceti's change to use the new terraform container. This is so that I can upgrade this to use terraform 0.6.12. On earlier versions terraform will update the security group on every run when it's configured with multiple ingress blocks with matching port ranges. 
Run the cloudfoundry terraform job against a clean environment (ie either a brand new deployment, or one that's had the cloudfoundry terraform destroy job run), and verify that …

[#113824903] Work around terraform diffs bug

---

terraform/cloudfoundry/network_acls_cell_in.tf
terraform/cloudfoundry/network_acls_cell_out.tf
terraform/cloudfoundry/network_acls_cf_in.tf
terraform/cloudfoundry/network_acls_cf_out.tf

The mapping from `-1` to `all` is broken in terraform acl rules and only works one-way. This means that whenever terraform polls AWS for changes it finds that `-1` (aws) != `all` (statefile). Changing this to `all` in our configuration stops this from occurring.
Open terraform issue is here:
https://github.com/hashicorp/terraform/issues/5226
Redeploy a platform, the network acl's should NOT be destroyed and recreated. Do it a couple of times to be sure.
If the PR functions the apply should look like this:
`
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
`
Anybody except @actionjack and @jonty, who have gazed inside terraform and will never be the same again.

[#113910983] Prevent network ACL's flapping

---

concourse/pipelines/create-deployer.yml

Use the same paas-cf version as was used in vpc terraform step.
This is because expunge vagrant step is directly related to vpc step, as it is just removing vagrant IP address from SGs, which was added there in the vpc job.
* Spin up concourse lite, it can be an existing environment
* Pause the `concourse-prepare-deploy` job
* Start the pipeline
* Make a change in terraform that will break it, eg syntax error
* Push to the branch
* Unpause the job
* `expunge-vagrant` should be able to run because it is pinned to paas-cf with the working terraform
Anyone but @mtekel or me

[#114193485] Pin expunge vagrant to paas-cf version

---

Makefile

We want our Makefile to support a target per environment so for instance it would be possible to do `make dev` to upload DEV pipeline. Additionally we want help to be available as a default target. 
Check whether prod,stage,ci and dev targets deploy pipelines with following config:
- Prod
- multi AZ
- AWS account PROD
- Staging
- multi AZ
- AWS account  STG
- Ci
- AWS account CI
- auto trigger on paas-cf
- Dev
- AWS account DEV
- autodelete
Anyone but @actionjack or @combor

[#114080971] New makefile targets per environment 

---

manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/050-logsearch.yml

[Ensure all components have consolidated logging](https://www.pivotaltracker.com/story/show/113996483)
Acceptance criteria:
if it logs and it is a system component
then its logs should appear in logsearch
or there should be a story to implement the logs
After reviewing our logsearch implementation we found that we are not logging all events most notably we are missing the all the logs under `/var/vcap/*/*.log` 
This PR 
Installs and configures [logsearch-shipper-boshrelease](https://github.com/logsearch/logsearch-shipper-boshrelease)
to ensure all the logs under `/var/vcap/*/*.log` are sent to logsearch
ingestor. This commit is fairly large because it is non-breaking.
I've drafted this PR to be reviewed in the following context:
* I would like to:
* Install the logsearch-shipper bosh …

[#113996483] Ensure all components have consolidated logging

---

concourse/pipelines/deploy-cloudfoundry.yml

what
----
Continuation of #127
As we run the smoke tests and acceptance tests as tasks in concourse,
we don't need to start a errand, so we don't need to login in bosh,
so we don't need bosh-secrets in these tasks anymore.
How to tests
------------
Simply run the smoke and acceptance tests
Who?
----

[#114186797] Do not get `bosh-secrets` in smoke/acceptance tests

---

tests/bosh-template-renderer/render_lib.rb
tests/bosh-template-renderer/spec/render_lib_spec.rb

What
----
When rendering a template, check if the manifest value is nil, not if it
evaluates false. If not, we cannot define 'false' as a value in the
manifest.
This fixes a minor bug.
How to test
-----------
A test has been added to the code. Do `make test`
Who?
----

[#114186797]  template render: use default only if value == nil

---

concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/create-microbosh.yml
concourse/pipelines/deploy-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/destroy-microbosh.yml
concourse/scripts/pipelines-cloudfoundry.sh
manifests/concourse-base.yml
terraform/concourse/outputs.tf

[Upgrade Concourse](https://www.pivotaltracker.com/n/projects/1275640/stories/114385219)
This PR updates deployer concourse to version 0.74 (this includes updates to stemcell and garden linux). In the new concourse version, each task has to have platform defined. Moreover, you can't input whole task any more, but have to define task outputs explicitly. This PR also contains minimal changes to pipelines to satisfy these new requirements. The pipeline update commits have been split into logical chunks, so that it is not a single huge commit: update bosh pipelines, update CF delete pipelines and update main CF pipeline.
Switch to this branch, apply against your existing environment (update works fine and preserves all your changes/pipelines from previous concourse). Or you can deploy new. …

[#114385219] Update deployer concourse

---

Makefile
concourse/pipelines/failure-testing.yml
concourse/scripts/pipelines-failure-testing.sh
concourse/tasks/generate-test-config.yml
concourse/tasks/get-instance-id.yml
concourse/tasks/kill-instance.yml
concourse/tasks/recover.yml
concourse/tasks/run-tests.yml

[Automated failure testing for key components](https://www.pivotaltracker.com/story/show/114233261)
Acceptance criteria:
- Should remove component one by one
- Should test the most essential functions still work
- Tests should be green at the end of the story
- If there are important components that don't produce green tests if killed, then separate stories to fix these should be spun off
This PR creates a separate failure testing pipeline that will delete core component vm's and test if the service still operates and passes the smoke tests.
I've drafted this PR to be reviewed in the following context:
* I would like to:
* Create a `concourse` pipeline that terminates the following job nodes and runs smoketests:
*  cloud-controller
*  colocated
*  nats
*  router
*  etcd
*  consul
*  cell …

[#114233261] Automated failure testing for key components

---

manifests/cf-manifest/deployments/900-cf-tests.yml

These are no longer needed now that we're running these tests in
concourse, and not in an errand. Left behind after #127.
Deploy this branch, verify that the smoke and acceptance tests still run.

[#114186797] Remove smoke/acceptance test errand defintions.

---

concourse/scripts/bosh-cli.sh

The pipeline and task that this takes inputs from was renamed when the BOSH
and CF pipelines were merged in 6849a99^...9196f4f which caused this to
error:
➜  paas-cf git:(master) ./concourse/scripts/bosh-cli.sh
error: build inputs not found
It's worth noting that it still won't work correctly because the version of
`fly` that is downloaded from the Bootstrap Concourse is older than the
Deployer Concourse is running after the upgrade in f72219d. It will hang with:
Logged in as `admin'
Target set to `my-bosh'
Deployment set to `/tmp/build/e55deab7/cf-manifest-with-uuid.yml'
succeeded
1: build id: 76, type: , name:
2: build id: 76, type: , name:
3: build id: 76, type: , name:
4: build id: 76, type: , name:
There is a story currently in play to ensure that we use the right version of
`fly` …

[#114854977] Update merged pipeline/task name for bosh-cli

---

manifests/cf-manifest/deployments/050-logsearch.yml
manifests/cf-manifest/spec/fixtures/terraform/terraform-outputs.yml
terraform/cloudfoundry/network_acls_cf_in.tf
terraform/cloudfoundry/outputs.tf
terraform/cloudfoundry/routers.tf
terraform/cloudfoundry/security-groups.tf

The full write-up is available [on pivotal](https://www.pivotaltracker.com/projects/1275640/stories/113996375).
This PR ensures that we have one instance of each Logsearch component in both Z1 and Z2 with ELBs to balance across each of the relevant services. It also splits ES across Z1, Z2, and Z3, with one master and one data node in each zone.
Spin up the cluster, then load kibana on `http://kibana.[$ENV].dev.paas.alphagov.co.uk`. You'll need to add a Kibana filter of `*`, then hit the Discover button. You should see data rolling in.
Head to the EC2 dashboard and kill an Ingestor node, you should still see data coming in. Do the same for a Kibana node and an Elasticsearch node. Everything should keep working.
If you kill a Parser node you'll still be getting data, but 50% of it will be …

[#113996375] HA for Logsearch

---

concourse/pipelines/create-bosh-cloudfoundry.yml

What?
-----
The bosh releases for graphite and grafana had wrong urls merged in #139.
We want them to point to the alphagov github forks.
How to test?
------------
Check that the resources point to the right repo and are able to pull the code
Who?
----

[#113749465] Fix urls of the graphite and grafana bosh releases

---

concourse/pipelines/create-deployer.yml
concourse/pipelines/destroy-deployer.yml

https://github.com/alphagov/paas-cf/pull/142 renamed the concourse manifest.
The related bosh-init state file is named after the manifest so it should have been renamed too.
Because of this the right state file wasn't uploaded and bosh-init would not be able to identify the deployed VM.
Also, it caused the CPI to be recompiled every time.
* create a new concourse deployer
* the CPI shouldn't be recompiled
* re-run the `create-deployer` pipeline
* bosh-init should identify the concourse deployed above and not try to redeploy it
Anyone but me

[#113159997] Fix concourse-deployer bosh-init state

---

terraform/cloudfoundry/network_acls_cf_in.tf

What?
-----
We have several rules to enable different traffic from infra to CF,
mainly to allow create SSH tunnels to access some internal services
(syslog, kibana, graphite).
Recently we merged two PR which define conflicting ACL numbers:
118_ingestor_syslog and 118_graphite both had the same ACL rule
number.
Re-numbering one, e.g. from 118_graphite to 119_graphite, will fix the
conflict, but we will have other error: `The maximum number of network
acl entries has been reached`
Finally we decided to simply allow all traffic from the infra network,
as some of the rules open wide ranges of ports to workaround the
previously described issues and the infra network has machines with
broad permissions to change AWS objects (bosh and concourse). We
also decided replace ACLs with security groups …

[#115403711] ACLs: allow all from infra to cf subnets

---

manifests/bosh-manifest/deployments/aws/000-bosh-infrastructure.yml
manifests/bosh-manifest/reference-bosh-manifest.yml
manifests/bosh-manifest/scripts/generate-bosh-secrets.rb
manifests/bosh-manifest/spec/fixtures/bosh-secrets.yml
manifests/concourse-manifest/concourse-base.yml
manifests/concourse-manifest/scripts/generate-concourse-secrets.rb

[Use non-default vcap passwords for Deployer Concourse and BOSH](https://www.pivotaltracker.com/story/show/113159679)
**Acceptance critera**
As a pipeline improvement you should not be able to SSH to the Deployer Concourse or BOSH machines with the default user and password.
This PR has been written in the following context:
* I would like to:
* Create and use a new Concourse VCAP password
* Create and use a new BOSH VCAP password
* Deploy a new environment and `ssh` to the deployer conconcourse and use su to log into the super user account using the passwords in defined in `bosh-secrets.yml` & `concourse-secrets.yml` in your s3 state bucket
[Whosoever holds the merge button PR, if he be worthy, shall possess the power of Github Merger](http://marvel.wikia.com/wiki/Mjolnir), except …

[#113159679] Use non-default vcap passwords for Deployer Concourse and BOSH

---

manifests/concourse-manifest/spec/fixtures/generated-concourse-secrets.yml

What?
-----
After merging #144 the build is failing because concourse manifest tests
fixtures are not including the recently added variable secrets.concourse_vcap_password,
which was added in a PR request merged just before.
This PR adds that value
How to test
-----------
`make test` and travis passes
Who?
----

[#113159997] Add the variable concourse_vcap_password to test

---

manifests/cf-manifest/scripts/create-cf-dbs.sh

Enable updating of RDS passwords, so that we can rotate these secrets. Previously 'api' and 'uaa' roles were only created once and never changed aftewards, which skipped updating passwords if you have changed them in secrets.
Deploy. Update `cf_db_api_password` and `cf_db_uaa_password` secrets (edit cf-secrets.yml, upload to bucket, apply - only UAA and CC jobs (cc, worker, clock) should be updated). Run smoke and acceptance tests. All should keep working.

[#114308825] Enable RDS secret rotation

---

Makefile
README.md
concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/create-deployer.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/destroy-deployer.yml
concourse/pipelines/destroy-microbosh.yml
concourse/pipelines/failure-testing.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/scripts/pipelines-deployer.sh
concourse/scripts/pipelines-failure-testing.sh

Story: [Enable build from tag option](https://www.pivotaltracker.com/story/show/115403129)
Adds the tag_filter option on the paas-cf git resource in all the pipelines and creates predefined filters for staging and production.
This is controlled via make commands or can be set via the variable `$PAAS_CF_TAG_FILTER`
* Build an environment, including bootstrap with different values for variable `$PAAS_CF_TAG_FILTER`
* Empty variable means no filter and all commits will pass
* To test for staging and prod, you can execute the targets `set_stage_tag_filter` or `set_prod_tag_filter` within the `dev` target.
* Push tags ([annotated tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging#Annotated-Tags) preferred). Patterns are [glob(7)](http://man7.org/linux/man-pages/man7/glob.7.html) …

[#115403129] Build from tag in staging and production

---

manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/spec/jobs_spec.rb

Enable updating of NATS password, so that we can rotate this secret. Do this by ensuring that the NATS jobs get updated (and deployed) concurrently with ETCD. This lets ETCD jobs connect to NATS using the new password. Otherwise they get stuck waiting for NATS to be updated, but which was configured to update after ETCD has finished updating.
Deploy. Update `nats_password` (edit cf-secrets.yml, upload to bucket, apply). Run smoke and acceptance tests. All should keep working.

[#114308825] Enable NATS password rotation

---

.travis.yml

We upgraded terraform in our concourse containers to 0.6.12 a while ago.
We should therefore be using the same version in Travis.
Verify that the Travis build downloads 0.6.12, and passes

Bump terraform in Travis.

---

Makefile
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/create-deployer.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/destroy-deployer.yml
concourse/scripts/environment.sh
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/scripts/pipelines-deployer.sh
manifests/cf-manifest/spec/fixtures/terraform/terraform-outputs.yml
terraform/ci.tfvars
terraform/cloudfoundry/dns-records.tf
terraform/cloudfoundry/outputs.tf
terraform/cloudfoundry/variables.tf
terraform/concourse/elb.tf
terraform/concourse/variables.tf
terraform/dev.tfvars
terraform/globals.tf
terraform/prod.tfvars
terraform/stage.tfvars
terraform/vpc/outputs.tf

[Story link: https://www.pivotaltracker.com/story/show/115318745](https://www.pivotaltracker.com/story/show/115318745)
We want to be able to deploy CF environment without a specific development name.
In staging and production we don't have a need for the "environment name" because there will only be one environment under that "domain name". We need to optionally omit that "thing" from the naming, so that we can create DNS entries such as:
- api.cloud.service.gov.uk
- api.staging.cloudpipeline.digital
And not:
- api.production.cloud.service.gov.uk
- api.staging.staging.cloudpipeline.digital
```
BRANCH=no-env-name-115318745 make dev
```
Deploy BOSH and CF (smoke test should pass ) and test destruction as well.
If you are not following master branch closely and your env is pre …

[#115318745] Ability to deploy without environment name

---

manifests/cf-manifest/deployments/040-cf-properties.yml

The logs from cloud_controller_ng are nedlessly verbose as they contain every single SQL query performed against the ccdb - We wish to make the logs less verbose as they are currently very difficult to search through when necessary.
There are two parameters within the manifest which control logging from the cloud_controller - `db_logging_level` sets the logging level at which all db query messages will be regsitered, whereas `logging_level` defines the level at which logs will be emitted from cloud_controller_ng and fed into syslog. The distinction between these two logging values is poorly documented, but important to understand - If `db_logging_level` is set to a value of `error` then the totallity of the SQL query logs will be emitted when logging_level is set to a value equal or …

[#115403965] Disable debug logging for Cloud Controller 

---

Makefile
concourse/scripts/pipelines-bosh-cloudfoundry.sh
vagrant/Vagrantfile

There were a few small changes necessary to allow deploying to staging:
* We needed to populate the subnet and security group for the bootstrap concourse in the `Vagrantfile`
* We needed to disable the creation of the prod tags - we're not ready for this yet, there are stories to implement this in the backlog.
While doing this, I noticed that `DISABLE_AUTODELETE` had not been enabled for production. I've therefore updated this flag so that autodelete defaults to disabled unless explicitly enabled, and updated the Makefile so that it's enabled for dev. This felt safer, and less likely that autodelete would accidentally be enabled in a production environment.
There's not much review that can be done here beyond verifying that the changes look good, and that the pipeline scripts still setup …

[#113266439] Updates to allow staging deployment

---

concourse/pipelines/destroy-microbosh.yml
manifests/bosh-manifest/deployments/010-bosh-template.yml
manifests/bosh-manifest/reference-bosh-manifest.yml

https://www.pivotaltracker.com/story/show/115414833
Bosh doesn't delete persistent disks imediately when deleting the
corresponding VM, instead there's a scheduled job that deletes them N
days after their VM was deleted (5 days by default).
This PR does 2 things to prevent this.
* It sets the `max_orphaned_age_in_days` parameter to 0, which means bosh will clean them up within 30 mins (the cleanup job runs every 30 mins by default)
* It adds a task to run a `bosh cleanup --all` to the `destroy-microbosh` pipeline to ensure that all orphaned disks are cleaned up before bosh is destroyed.
Deploy from this branch. Then delete the CF deployment. Note that there are 14 unused volumes in the EC2 console. Verify that these are automatically removed within 30 mins (the cleanup job runs on the …

[#115414833] Ensure orphaned volumes aren't left behind in EC2

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/deployments/aws/055-graphite-stub.yml
manifests/cf-manifest/spec/fixtures/terraform/terraform-outputs.yml
terraform/cloudfoundry/dns-records.tf
terraform/cloudfoundry/network_acls_cf_in.tf
terraform/cloudfoundry/outputs.tf
terraform/cloudfoundry/routers.tf
terraform/cloudfoundry/security-groups.tf

[ELB for access to metrics](https://www.pivotaltracker.com/story/show/115251665)
## What
Currently to access metrics we are using SSH tunnels. We should change this to allow access via ELB over HTTPS and limited to whitelisted IP ranges.
This PR has been written with the following narrative:
* I would like to:
* I create a new security group for:
* Grafana and;
* Graphite
* Create a new ELB for 
* Grafana listening on port 443 and forwarding to port 3000 on all registered grafana nodes;
* Graphite listening on port 3001 and forwarding to port 3001 on all registered grafana/graphite nodes;
* Create Terraform outputs for graphana so I can use them in cloud foundry manifests
* Fix ACL port range on rule 118 to allow ELB's to talk to grafana and graphite node.
* Create new resources for …

[#115251665] ELB for access to metrics

---

README.md
doc/non_dev_deployments.md

There are a few differences when deploying to non-dev accounts. This
pulls these details out into a separate document.
Check that the new docs are clear, and cover the necessary details.

[#115858399] Document steps to set up a ci, staging or prod environment

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/deployments/050-logsearch.yml
manifests/cf-manifest/spec/fixtures/terraform/terraform-outputs.yml
terraform/cloudfoundry/dns-records.tf
terraform/cloudfoundry/outputs.tf
terraform/cloudfoundry/routers.tf
terraform/cloudfoundry/security-groups.tf

Story: [ELB for access to logs](https://www.pivotaltracker.com/story/show/115320097)
We want to be able to access Logsearch via its web interface (Kibana), without the need for SSH tunneling. For this we provision an ELB and provide it with a self-signed certificate. 
An extension to the IAM policy allowing the uploading of the certificate has already been merged as a result of PR 25 in the aws-account-wide-terraform repository. 
There is an intermediate HAProxy because there is an intention to set up authentication for access to Kibana. This is already provided in the latest Logsearch releases. 
- Deploy CF using branch `115320097-elb-access-to-logs-rebase`. 
- Check you can access Kibana on https://logsearch.[deploy_env].dev.cloudpipeline.digital
- View the certificate and check the …

[#115320097] ELB for access to logs

---

Makefile
README.md
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/bosh-cli.sh

This is a fix for `bosh-cli.sh` as https://github.com/alphagov/paas-cf/pull/159 introduced SYSTEM_DNS_ZONE_NAME variable. This var is set only by running `make` so we had to move bosh-cli.sh execution to Makefile. Additionally we re-arranged all targets so it's now possible to execute `make $ENV bootstrap`.  Read the updated README if you want more details. 
Check if `make dev bosh-cli` works properly and connects to Concourse container. Also, run create-bosh-cloudfoundry pipeline and make sure that test-bosh-cli job succeeds .
Not @jimconner or @combor

[#115845521] Move bosh-cli to Makefile

---

Makefile

As we have changed bosh-cli behaviour in previous PR we need to modify
Makefile to behave accordingly.
run `make dev bosh-cli`
not @jimconner or @combor

[#115845521] Remove $DEPLOY_ENV from bosh-cli execution in Makefile

---

concourse/scripts/self-update-pipeline.sh

What?
-----
After #165 you must pass the target `pipelines` to update the pipelines,
but the `self-update-pipeline.sh` script was not updated.
Scope
-----
Just add the right target to the script
How to test?
------------
Self update should work as described in #156. See that PR for instructions
to test this.
Who?
----

[#115845521] Add target pipelines to self-update-pipelines.sh

---

Makefile
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/tag-release.sh

When the staging environment completes deployment and all acceptance tests correctly, we want to tag that build with a prod-x.x.x tag, where x.x.x matches the version number of the stage-x.x.x tag which triggered the build in the staging environment.
* Because this uses the AWS_ACCOUNT environment variable to ensure that the tag bumping only happens when running on the stage platform, it is necessary to test on the staging platform (or tweak your own environment so that it pretends that AWS_ACCOUNT is set to staging)
* Modify your Makefile and set SELF_UPDATE_PIPELINE=false in the set_env_class_prod section
* Optionally (if you're impatient) modify the acceptance tests job to perform a quick operation such as `/bin/true` before you push the pipelines.
* Destroy existing staging pipeline. …

[#115869215] Create tags for production. 

---

manifests/cf-manifest/deployments/900-cf-tests.yml
terraform/cloudfoundry/routers.tf
terraform/cloudfoundry/security-groups.tf
tests/acceptance-tests/generate_test_config.rb
tests/acceptance-tests/src/acceptance/http_closed_test.go

[Move public facing TLS terminations to ELBs](https://www.pivotaltracker.com/n/projects/1275640/stories/115709073)
Close port 80 as a part of leaving only secure endpoints open. This is 1st PR for the story.
Apply to existing environment or build new. All tests should pass. You should not be able to connect to port 80 on any CF or app interfaces.
not @mtekel

[#115709073] close port 80

---

doc/non_dev_deployments.md

What?
----
We decided to name the production DEPLOY_ENV variable as 'prod',
instead of 'production', to keep consistency.
Who?
---

[#113428783] Docs refer production DEPLOY_ENV as 'prod'

---

Makefile
README.md
concourse/scripts/environment.sh

Story: [Basic Information listing URLs for Metrics and Visualisations](https://www.pivotaltracker.com/story/show/115251811)
Display system URLs to simplify use of each environment. It works by adding variables to `environment.sh` and create a make target to call it.
* Run `make dev env`
* Check the new URLs
Anyone but @HenryTK or myself

[#115251811] Display system URLs

---

Makefile
README.md
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/create-deployer.yml
concourse/scripts/create_pool_lock.sh
concourse/scripts/pipelines-bosh-cloudfoundry.sh
requirements.txt
terraform/concourse/codecommit.tf
terraform/concourse/git_ssh_key_id
terraform/concourse/outputs.tf
terraform/concourse/provider.tf
terraform/concourse/variables.tf

[#115624569 Implement locking for pipelines](https://www.pivotaltracker.com/story/show/115624569)
What?
----
We want to implement logic to lock the pipeline to prevent double executions in our deployments.
We decided
* to use [the existing pool resource](https://github.com/concourse/pool-resource) which
uses git as a backend.
* Use codecommit to create one git repo per user
* Create one IAM git user to access that repo and upload one generated SSH key.
* use IAM groups to grant access to the codecommit repository
Dependencies
--------
This PR depends in these other PR and changes:
* `aws-account-wide-terraform/26` (already merged and applied to dev account)
* https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/42 needs be merged and the container generated. After that, update …

[#115624569] Implement locking for pipelines with pool resources

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/create-deployer.yml
terraform/concourse/codecommit.tf
terraform/concourse/variables.tf

[#115624569 Implement locking for pipelines](https://www.pivotaltracker.com/story/show/115624569)
What?
----
We did not catch this issue in the PR #173.
Terraform codecommit resource[1] has a bug managing the default_branch
property: https://github.com/hashicorp/terraform/issues/5641
Although this property is optional, terraform will try to manage it.
If defined, codecommit will fail during creation:
```
BranchDoesNotExistException: refs/heads/master does not exist
```
Meanwhile if default_branch is defined, codecommit it will fail as soon
as a branch is pushed to the repository. The reason is that AWS enforces
having at least one branch as default branch, failing when terraform is
trying to set it empty:
```
* aws_codecommit_repository.concourse-pool: Error Updating Default
* Branch for …
```

[#115624569] Workaround terraform codecommit issue with default_branch property

---

README.md

Corrects anchor links to the section about MicroBOSH in the README.
View [README](https://github.com/andrewgarner/paas-cf/blob/fix-microbosh-readme-anchors/README.md) file and verify anchor links to MicroBOSH work from the [Overview](https://github.com/andrewgarner/paas-cf/blob/fix-microbosh-readme-anchors/README.md#overview) section and [Deployer Concourse](https://github.com/andrewgarner/paas-cf/blob/fix-microbosh-readme-anchors/README.md#deployer-concourse) sections.
Anyone.

Fix MicroBOSH README anchors

---

concourse/scripts/pipelines-bosh-cloudfoundry.sh

Different operating systems have different implementations of the mktemp command. Some do not allow you to call mktemp without specifying the prefix. We want to explicitly pass the prefix whenever we call mktemp.
Run `concourse/scripts/pipelines-bosh-cloudfoundry.sh` and check it works
Anyone but @saliceti or me. Preferably a Mac user.

[#116047559] Explicitly define prefix when using mktemp

---

concourse/pipelines/create-deployer.yml

I added this in error in 5fc0230.
Jobs that run terraform must never pin the tfstate inputs. It's
important that they always run with the latest tfstate file, otherwise
they won't have an accurate picture of what actually exists in AWS.
Verify that the bootstrap pipeline works.

Fix erroneous tfstate pinning in bootstrap pipeline

---

.travis.yml
Makefile

Now that the makefile is structured so that we always do `make <env> <action>`, there's no need for the environment setup to be in separate targets, it can be in the env targets themselves.
Verify that the makefile still works (eg verify that `make <env> showenv` outputs the expected values etc).

Remove unnecessary set_env_class_* Makefile targets

---

concourse/pipelines/destroy-cloudfoundry.yml

This appears to have been broken since we added ELB's with certificates on them for metrics etc, but nobody noticed as we rarely totally destroy cf environments.
Run the destroy pipeline. It should succeed.
Not @jonty or @timmow.

Fix CF destroy by unpacking certificates for tf

---

Makefile
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/tasks/smoke-tests-config.yml
concourse/pipelines/tasks/smoke-tests-run.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/scripts/smoke_tests_email.sh

We want to be able to run smoke tests continually in CI, Staging, and Production and be informed via email if any tests fail. We have left the existing smoke tests job in place as this is part of the end-to-end pipeline. We have moved the two tasks from the smoke-tests job to external task files in `paas-cf/concourse/pipelines/tasks` to avoid duplication of source code. 
To disable the continuous smoke tests in development we interpolate a boolean as the `trigger` value of the timer resource. 
To simplify the usage of AWS Simple Email Service we have used the AWS CLI tool. We did not use the email resource type as it does not support instance profiles. 
You can change the email recipient in `concourse/scripts/smoke_tests_email.sh` to avoid spamming the team during tests. You need to log …

[#116047559] Notification when system unusable

---

concourse/chrome_plugin/README.md
concourse/chrome_plugin/manifest.json
concourse/chrome_plugin/src/inject/inject.js

This is the terrible chrome plugin we've got deployed on the concourse monitoring screens to remove all the non-essential information.
1. Install the plugin in chrome, then load a concourse web interface.
2. Observe that there is less concourse interface.
3. Uninstall the chrome plugin.
Not @jonty.

Add chrome plugin used on concourse monitors

---

.travis.yml
manifests/concourse-manifest/concourse-base.yml

Enable `publicly_viewable` for the deployer-concourse so that we can put the pipelines on the big screen without having to have it logged in. This concourse is still locked down by IP.
This allows read-only access to the concourse UI, but not to the output
of job runs (unless the job itself is defined as public). See
http://bosh.io/jobs/atc?source=github.com/concourse/concourse&version=0.74.0#p=atc.publicly_viewable
for more details.
This also includes a commit to make the Travis `before_install` tasks fail with better errors. 
Run the create-deployer pipeline from this branch. Verify that the deployer-concourse can be accessed in read-only mode without any auth.

[#116603765] Enable concourse public read-only access

---

concourse/pipelines/destroy-deployer.yml

The concourse terraform destroy was failing because it requires the
git_rsa_id_pub variable to be set. It doesn't actually matter what this
is set to because we're destroying.
Run the destroy-deployer pipeline and verify that it doesn't error with "Required variable not set: git_rsa_id_pub".  It may error with another error about IAM permissions that needs to be fixed in the IAM policies.

Fix missing git_rsa_id_pub in destroy-deployer pipeline

---

concourse/scripts/tag-release.sh

[#117131037 Fixing the build: Double tags in stage](https://www.pivotaltracker.com/story/show/117131037)
What
----
It seems that CI run twice and created a double tag of stage. Then staging tag-release failed because the script does not handle well two tags.
Scope
-----
In this PR we add code so that
- Not fail if there are two tags poiting to HEAD
- Do not allow double tagging
Additionally, to help testing I added code to optionally disable git push
How to test
-----------
As we lack of a proper unit testing for this script, you can use this
minimum Dockerfile.
```
cat <<EOF > Dockerfile
FROM governmentpaas/git-ssh
WORKDIR /tmp
RUN mkdir -p /tmp/paas-cf
RUN cd /tmp/paas-cf && \
git init && \
git commit --allow-empty -m "First commit" && \
git tag previous-0.0.1 && \
git tag …
```

[#117131037] Fixing the build: Double tags in stage

---

doc/non_dev_deployments.md

The cred-store paths were missing the `AWS_ACCOUNT` component. This
updates the docs to match the paths used in the `Makefile`.
Verify that the cred-store paths in the docs match the paths used in the `Makefile`

Fix external SSL cert docs.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/extract_quota_settings.rb
manifests/cf-manifest/deployments/040-cf-properties.yml

We only want to allocate 2GB of "Freemium" memory in the default quota. We also limit usage to 10 basic (free) services. Because BOSH can't update values directly from manifest changes (https://github.com/cloudfoundry/bosh/issues/1201), add a step in post-deploy job to use cf-cli to update quotas. Add a small script to help extract quota settings from manifest.
Deploy. View quotas (`cf quotas`) and verify default has been updated to new values. Try exceeding it - you should not be able to.
not @mtekel

[#117020631] Reduce default quota to 2GB

---

concourse/scripts/tag-release.sh

[#117515045 Fix the Build : Tags](https://www.pivotaltracker.com/story/show/117515045)
What
---
We found the following problem in tag-release:
1. The git resource ALWAYS clone the full repo, downloading all latest tags
2. Then it checks-out the required ref, tag or commit
4. But when promoting a tag, tag-release.sh queries for all the tags that
**CONTAIN** the current HEAD, so any new tag in new commits in master
will match and their version promoted.
The solution is simply query for the tags to point-at the current HEAD
Note that we were checking if the current commit was already included in any other previous tag with the destination prefix to avoid tagging twice. In this check we also use `--contains`, but it should be `--points-at`.
Note we are not checking if the destination tag …

[#117515045] Use points-at to find tags pointing to HEAD

---

README.md

As suggested by Toby in #153. I've refactored the instructions so that:
- We link to the downloads section in the README which is a bit simpler than
the release page (the version probably doesn't matter too much at the
moment).
- Use the recently added `showenv` make target for getting the URL
- Describe where the admin password can be found
- Link to a page about `cf login` rather than describing everything here
I did experiment with adding a `cf-login` make target and script, which
fetches the password automatically, but I'm not sure whether it's too
opinionated and it's not very easy to test it in the same way we do
`bosh-cli`.
Test the instructions in the new section of the README.
Not @dcarley

README: Document how to access CloudFoundry

---

README.md

This was broken when we combined the BOSH and CloudFoundry pipelines. I
don't think it's worth listing them as separate bullet points when they
point to the same section.
View the rendered page and see if it makes sense.
Not @dcarley

README: Fix CF link in overview section

---

README.md
terraform/scripts/set-up-pingdom.sh

We want Terraform state files for Pingdom to have a descriptive name so it is clear in AWS Console S3 bucket what the file is for. The previous file name would have just been ${MAKEFILE_ENV_TARGET}.tfstate, so `pingdom-` has been added to the start.
Also, we want to make sure developers have the correct AWS credentials when running the script, so the README has been updated.
* Run shellcheck on `terraform/scripts/set-up-pingdom.sh`.
* Run `make dev pingdom` and make sure the script runs successfully and Terraform / AWS CLI does not complain.
* Run the script again and it should say nothing has been updated.
Anybody except @henrytk @timmow or @jimconner

[#116104189] Renamed Pingdom Terraform state file and updated README

---

manifests/cf-manifest/deployments/040-cf-properties.yml
manifests/cf-manifest/deployments/900-cf-tests.yml
tests/acceptance-tests/src/acceptance/custom_buildpacks_test.go

As a PaaS Ops Engineer responsible for the security and supportability of the platform, I want to ensure we are dealing with a known set of buildpacks, in order to reduce the complexity of supporting the platform.
This feature is disabled by changing  the manifest property of CF Cloud Controller    [`cc.disable_custom_buildpacks`]( https://bosh.io/jobs/cloud_controller_worker?source=github.com/cloudfoundry/cf-release&version=228#p=cc.disable_custom_buildpacks) to `true`.
It will prevent users uploading  their own buildpacks so they only use the trusted provided ones. The cf cli will report an error to the user:
```
$ cf push my-new-app -b https://github.com/keymon/ruby-buildpack
Updating app my-new-app in org admin / space admin as admin...
FAILED
Server error, status code: 400, error …
```

[#108444338] Disable custom buildpacks

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/tasks/smoke-tests-run.yml
concourse/scripts/import_bosh_ca.sh
concourse/tasks/run-tests.yml

Enable SSL validation for all `cf login` commands in the pipeline. Also includes some refactoring to make the installation of the BOSH CA easier. More detail in the commits.
1. Checkout the branch: `git co cf_login_ssl_validation`
1. Deploy the pipelines from the branch: `BRANCH=$(git rev-parse --abbrev-ref HEAD) make dev pipelines`
1. Run the whole CF pipeline and confirm that it completes green.
Not @dcarley.
No story ID. I'm invoking Tech Lead gardening privileges.

Enable SSL validation for `cf login`

---

manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/spec/jobs_spec.rb

Ensure that the etcd cluster is upgraded in a way that maintains the cluster health. This problem was discovered while reviewing #207.
Without this, when upgrading the cluster (eg for a stemcell version
change), the first node will be upgraded, then the other 2 will be
upgraded in parallel, resulting in the cluster losing quorum. This then
requires manual intervention to recover from.
Deploy a change that will cause all 3 etcd machines to be re-created (eg a stemcell version bump). Verify that they update cleanly, and that the cluster is healthy afterwards (run `/var/vcap/packages/etcd/etcdctl cluster-health` on one of the nodes).

Ensure etcd cluster is updated serially

---

.travis.yml

Installing shellcheck from debian sid is no longer working, and
resulting in dependency errors (eg https://travis-ci.org/alphagov/paas-cf/builds/124150110).
This adds a shellcheck linux binary to the repo, and updates Travis to
use it. This binary is extracted from the ubuntu wily package version 0.3.7-1.
Verify that the Travis build now passes

[#117909253] Add shellcheck binary to the repo.

---

Makefile
concourse/pipelines/create-deployer.yml
concourse/scripts/pipecleaner.py

Pipecleaner is a small tool I wrote to help spot concourse pipeline errors quickly before we actually run them in concourse. It was written during another story to help with refactoring pipelines and made the whole process substantially faster.
It can check for the following issues:
* Resources being used in a job that have not been defined in the `resources:` block. (Fatal)
* Resources that have been defined in the `resources:` block and are not used in the pipeline. (Warning)
* Resources being used in an `input:` block that have not been `get:`-ted. (Fatal)
* Resources that have been `get:`-ted and are not used in the job. (Warning)
* `output:`s that are not used later in the job. (Warning)
By default it will exit with a nonzero exit code for any Fatal errors, and will exit with a …

Concourse pipeline linting

---

manifests/cf-manifest/deployments/aws/000-cf-infrastructure.yml

Assign bosh-director IAM profile to compilation VMs so that they can 'put' compiled blobs into the compiled package cache.
Compilation VMs store their compiled blobs directly in S3, rather than
passing them back through the director - These 'put' operations were previously failing
as the iam profile applied to these VMs did not allow for 'put' operations.
The compilation VMs are effectively an extension of the bosh-director
machine to allow for parallel compilation, so applying the same
bosh-director iam profile does not seem an unreasonable approach.
Using the bosh-director iam role will allow them to put objects
into the compiled package cache bucket.
Check that the code looks good. 
Deploy a new version of CF, or deploy into an environment where the packages have not already been …

[#115869119] Compilation VMs require write access to S3

---

concourse/pipelines/create-bosh-cloudfoundry.yml

The cf and bosh terraform jobs have run in parallel since #213 was
merged. This suggests that the cf-terraform job doesn't depend on the
outputs from bosh-terraform. Reading the code confirms this - there are
no variables in the cf-terraform that match the names of outputs in
bosh-terraform. Additionally the cf-terraform destroy job doesn't rely
on the bosh-ftstate file.
This PR therefore removes the bosh tfstate from the cf-terraform job.
In addition, I've also pinned the bosh-secrets used in the bosh-terraform job to the output of generate-secrets to make this dependency clear
Run the create pipeline for a new environment and verify that it works.

[#115869119] Remove cf-terraform bosh-ftstate dependency

---

manifests/bosh-manifest/deployments/010-bosh-template.yml
manifests/bosh-manifest/deployments/aws/000-bosh-infrastructure.yml
manifests/bosh-manifest/reference-bosh-manifest.yml
manifests/cf-manifest/deployments/000-base-cf-deployment.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/040-cf-properties.yml
manifests/cf-manifest/deployments/900-cf-tests.yml
manifests/cf-manifest/deployments/aws/000-cf-infrastructure.yml
manifests/cf-manifest/spec/jobs_spec.rb

Story: [Upgrade to CF -N](https://www.pivotaltracker.com/story/show/116983391)
We upgrade CF, diego, stemcell, bosh. This required adjustments to CF configuration and tests properties.
This version works with cf version 6.16.1. There are containers ready in docker hub. To use them: 
* open `create-bosh-cloudfoundry.yml`
* replace `docker:///governmentpaas/cf-acceptance-tests` with `docker:///governmentpaas/cf-acceptance-tests#116983391_upgrade_cf_to_v233`
* replace `docker:///governmentpaas/cf-cli` with `docker:///governmentpaas/cf-cli#116983391_upgrade_cf_to_v233`
Run on top of existing deployment or create a new deployment. Everything should succeed.
Merge PRs on `paas-docker-cloudfoundry-tools` to update `cf-cli` and `cf-acceptance-tests` images.
Anyone but @jimconner @HenryTK or …

[#116983391] Upgrade CF to v233

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/deployments/000-base-cf-deployment.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml
tests/acceptance-tests/src/acceptance/http_strict_transport_security_test.go
tests/example-apps/strict-transport-security-app/index.php

[#115931361 Ensure correct HSTS headers are being served](https://www.pivotaltracker.com/story/show/115931361)
What?
----
We want to serve [HSTS headers](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) for all HTTPS requests to the apps domains, but it will safeguard existing users from being MITMed over insecure connections and it will improve the user experience when they click on a hostname that doesn't have a protocol.
We want to leave open the option of able to override these headers from the tenant application if they wish.
We decided to use haproxy in front of the gorouter to do the job for the time being, using a custom release as the [current haproxy job from `cf-release`](https://github.com/cloudfoundry/cf-release/tree/master/jobs/haproxy/) does not support adding …

[#115931361] Add haproxy in front of gorouter to add HSTS headers (and SSL termination)

---

manifests/concourse-manifest/concourse-base.yml

[Fix caching for Concourse resources](https://www.pivotaltracker.com/n/projects/1275640/stories/112582239)
Deploy/apply. When you run pipeline and the resource (e.g. paas-cf) is used for the 2nd time, in the resource logs, you should see `using version of resource found in cache` instead of resource being retrieved again (e.g. `Cloning into '/tmp/build/get'...` in case of paas-cf)
**Note**: if you want to save one concourse re-deploy, then you can merge together with https://github.com/alphagov/paas-cf/pull/222
not @mtekel

[#112582239] Enable caching on Deployer Concourse

---

concourse/scripts/spec/fixtures/val_from_yaml.yml
concourse/scripts/spec/val_from_yaml_spec.rb
concourse/scripts/val_from_yaml.rb

Refactor the existing tests for `val_from_yaml` to use the command line
interface instead of the underlying Ruby object.
This matches how we use the script in our Concourse pipelines, it exercises
more of the code, and allows us to make assertions about the standard output
and exit codes.
.. then ..
Return a non-zero exit code when the script is unable to find the user
provided key in the YAML document. This decreases the chance of another
script silently using an empty value, such as a password.
- Look at the code changes and confirm that they make sense.
- Confirm that the Travis CI build completes successfully.
Not @dcarley

var_from_yaml: Test CLI and return non-zero exit code on errors

---

concourse/pipelines/create-bosh-cloudfoundry.yml

Remove the branch config because it has been merged in
paas-aws-broker-boshrelease.
We missed this step in previous PR #224

[#117512347] Pull master from aws-broker-boshrelease

---

concourse/scripts/smoke_tests_email.sh

Story: [FIX THE BUILD : Staging](https://www.pivotaltracker.com/story/show/118389245)
The continuous smoke tests were failing in staging but we were not notified because of an error in the alert email task. This is a quick fix that removes the smoke test log and commit message from the email so we can at least be notified.
Switch on the alert email with `ALERT_EMAIL_ADDRESS` variable, make the smoke test fail and check you receive the email.

[#118389245] Remove logs from alert email

---

README.md
scripts/create-tenant.sh

[#117706115 Automated Organisation and Org Manager Creation](https://www.pivotaltracker.com/story/show/117706115)
What
----
We want to provide a automated script to create organisations, org managers
and email the password.
Context
-------
We added ./scripts/create-tenant.sh script
./scripts/create-tenant.sh will create a user and organisation in the CF
API where you are currently logged in and send an email to the user
if the password changes.
The script will leverage the cf client to create the organisation, space
and user, and use AWS cli with SES to send emails.
How to test
-----------
Prerequisites:
1. You must have installed the latest AWS client and CF client.
2. You must have your AWS credentials exported and login into CF with an admin user.
3. Your email account must be verified …

[#117706115] Automated Organisation and Org Manager Creation

---

tests/bosh-template-renderer/render.rb
tests/bosh-template-renderer/render_lib.rb
tests/bosh-template-renderer/spec/render_lib_spec.rb

Story: [Make Concourse 1.1 work with bosh-init](https://www.pivotaltracker.com/story/show/118552679)
bosh renderer was only considering global properties. But some
manifests (like our concourse manifest) don't provide global
properties but use properties under the jobs.
This now considers both, with the job ones taking priority.
Test with the concourse manifest for example.
* retrieve the concourse manifest from S3
* get https://github.com/alphagov/paas-concourse and checkout our current version (v0.74.0)
* This should render the template:
```
$./render.rb [...]/paas-concourse/jobs/atc/templates/atc_ctl.erb [...]/paas-concourse/jobs/atc/spec concourse-manifest.yml concourse
```
* run the tests with `make test`
Anyone but @HenryTK or myself

[#118552679] bosh renderer can read properties under jobs

---

Makefile

Commit verification currently doesn't work when combined with a
tag_filter.
This disables commit verification in staging and prod to unblock the
builds while this is fixed. It remains enabled in CI because CI doesn't use a tag_filter.
Verify that the changes look sensible.

[#117704989] Disable commit verification in staging and prod.

---

Makefile
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
manifests/cf-manifest/scripts/generate-cf-certs.sh
terraform/cf-certs/outputs.tf
terraform/cf-certs/upload.tf
terraform/cf-certs/variables.tf
terraform/cloudfoundry/cf_api_elb.tf
terraform/cloudfoundry/logsearch_elb.tf
terraform/cloudfoundry/metrics_elb.tf
terraform/cloudfoundry/router_elb.tf
terraform/cloudfoundry/variables.tf
terraform/scripts/manually-upload-certs.sh

**🚨 For review only.  DO NOT MERGE YET.** Please review and indicate in the comments whether it's good to merge.  I'll then merge and deploy myself.
When we came to buy real certs for production and staging, it wasn't
feasible to get a single cert that covered multiple wildcard domains.
We've therefore had to get separate certs for the system and apps
domains.
This updates the pipelines to use separate certs for the system and apps domains. It also updates the dev/ci cert generation to generate separate certs for these.
This PR also updates the metrics ELB to use the system domain cert, instead of a separately generated one.
Note: Due to the certs and ELBs being managed in separate terraform runs, it's not possible for this to apply cleanly to an existing environment, so it has to be …

[#118089721] Split apps and system domain external certs

---

Makefile
README.md

In the recent days I found myself needing to get concourse IP way too often. I have realized that other team members might have to do the same. Enhance environment script to show CONCOURSE_IP as well.
run `make <environment> showenv` and check that the output now also contains CONCOURSE_IP
not @mtekel

Add CONCOURSE_IP to show environment script

---

Makefile

CI is using self-generated certs, so it should not be set to skip the
upload of these generated certs.
Verify that the change looks sensible.

[#118089721] CI does not use manually uploaded certs.

---

manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/040-cf-properties.yml

base_job_templates meta is used to define templates for diego jobs.
After rendering, these templates are present in the diego jobs. The
base_job_templates tree (which is on top level with properties,
compilation, releases etc.) has no purpose anymore and is essentially
"dead yaml". Prune it like we prune other scaffolding.
Apply against existing environment. Check that there are no changes in the deploy job.
not @mtekel

Prune base_job_templates from cf manifest

---

terraform/scripts/manually-upload-certs.sh

Fixed a typo in manually-upload-certs.sh. The file in the cred store has a `.` not an `_` in it.
Modify the `manually-upload-certs.sh` script as follows:
* Change the `terraform apply` to `terraform plan`.
* Comment out the `aws s3` upload on line 37.
Run the script against staging (setup AWS creds, set DEPLOY_ENV to staging, and run `CERT_PASSWORD_STORE_DIR=/path/to/credentials-high make staging manually_upload_certs`), and verify that it works.
Anyone with access to credentials-high but myself.

[#118089721] Fix typo in manually-upload-certs.sh

---

.travis.yml

Upgrade to Terraform 0.6.15 in order to match alphagov/paas-docker-cloudfoundry-tools#49
Check that the Travis build passes for this PR. This can be merged before the referenced PR.
Not @dcarley.

[#116230113] Travis: Upgrade to Terraform 0.6.15

---

concourse/pipelines/create-deployer.yml
terraform/concourse/codecommit.tf
terraform/concourse/variables.tf

**NOTICE: alphagov/paas-docker-cloudfoundry-tools#49 needs to be merged first**
This reverts commit 15367aeb79f73e5c0b3cc83d81f9787d1ee1ea40.
This has been fixed upstream in Terraform 0.6.15 which we're upgrading to in
the PR: alphagov/paas-docker-cloudfoundry-tools#49
The output file is passed between two tasks, rather than into an s3
resource, so we don't need to do any other cleanup.
You need to run the `create-deployer` pipeline twice:
1. first without the codecommit repo (or branch) already there
1. then with the codecommit repo (or branch) already there
I did manage to test this on an existing environment, but it was a lot of hassle because:
- it seems we don't have permissions to delete codecommit repos using our ordinary credentials so you have to hijack an `awscli` container on …

[#116230113] Revert "Workaround terraform codecommit issue"

---

Makefile

> Comes from PR #233 and story [#117704989](https://www.pivotaltracker.com/story/show/117704989)
What
------
Commit verification was not working when combined with a tag_filter.
After merging this https://github.com/alphagov/paas-git-resource/pull/2 we allow
it to start working. The associated container has been built automatically
and all the concourse installation pulled the image automatically.
This re-enables commit verification in staging and prod
How to review
-------------
Verify that the changes look sensible, merge it, wait until it passes staging and prod.
Who can review
--------------

[#117704989] Re-enable commit signature verification in staging and prod

---

Gemfile
Gemfile.lock
Makefile
concourse/scripts/spec/support/script_testing_helpers.rb
concourse/scripts/val_from_yaml.rb
manifests/bosh-manifest/spec/support/manifest_helpers.rb
manifests/cf-manifest/spec/support/manifest_helpers.rb
manifests/concourse-manifest/spec/reference_comparison_spec.rb
manifests/concourse-manifest/spec/support/manifest_helpers.rb
scripts/merge_pr.rb
tests/bosh-template-renderer/spec/render_lib_spec.rb

There's no story ID, but I looked at this while originally reviewing #202.
Rubocop is a static code analysis tool for Ruby. It comes with a bunch of
checks, called "cops". Some of them, such as the "style" cop, are very
opinionated and have limited value.
However I've found the "lint" cop very useful for catching unintended
behaviour in previous projects. It is described as:
> Lint cops check for possible errors and very bad practices in your code.
> RuboCop implements in a portable way all built-in MRI lint checks (ruby
> -wc) and adds a lot of extra lint checks of its own.
We now have enough Ruby code, by way of scripts or tests, that this is worth
adding. By adding it to the `test` make target it will be run by Travis CI
(and locally) alongside our other tests.
See the individual …

Add Rubocop lint checks

---

tests/acceptance-tests/src/acceptance/http_closed_test.go

The test that checks whether TCP connection to http port is possible panics if connection succeeds:
```  
•! Panic [18.896 seconds]
Http is closed
/Users/piotrkomborski/go/src/github.com/alphagov/paas-cf/tests/acceptance-tests/src/acceptance/http_closed_test.go:44
for apps [It]
/Users/piotrkomborski/go/src/github.com/alphagov/paas-cf/tests/acceptance-tests/src/acceptance/http_closed_test.go:35
Test Panicked
interface conversion: interface is nil, not net.Error
/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443
Full Stack Trace
/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/alphagov/paas-cf/tests/acceptance-tests/src/acceptance_test.glob.func2.1()
/Users/piotrkomborski/go/src/github.com/alphagov/paas-cf/tests/acceptance-tests/src/acceptance/http_close …
```

Fix http is closed tests

---

manifests/cf-manifest/deployments/000-base-cf-deployment.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml
terraform/cloudfoundry/router_elb.tf
tests/acceptance-tests/src/acceptance/http_forwarded_for_test.go
tests/acceptance-tests/src/acceptance/http_forwarded_proto_test.go

[#116309951 X-Forwarded headers available to applications](https://www.pivotaltracker.com/n/projects/1275640/stories/116309951)
What
----
As a tenant deploying an application to the PaaS, I want an X-Forwarded-Proto and X-Forwarded-For headers to be available to my application so that the application can determine whether it is being served externally over HTTPS.
In order to implement this, we need to get the client origin IP from the ELB in front of HAProxy, for that we want to use [ProxyProtocols](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) in [ELB](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html).
Prerequisites
-------------
**Note** This PR depends in this other one: …

[#116309951] Setup ProxyProtocol between ELB and HAProxy to support  X-Forwarded headers

---

Makefile

Add description to merge_pr target so that it becomes visible in make
help (when you do just `make` or `make help`).
type `make` or `make help`. Check that it displays merge_pr target with the description added in this PR.
not @mtekel

Make merge_pr visible in make help

---

tests/acceptance-tests/src/acceptance/Godeps/Godeps.json
tests/acceptance-tests/src/acceptance/http_closed_test.go
tests/performance-tests/src/performance/Godeps/Godeps.json

Our custom acceptance and performance tests currently expose the (now
temporary) admin password in the output on every run.
More recent versions of cf-test-helpers, as used by cf-acceptance-tests and
cf-smoke-tests, now redact the password. By upgrading our test suites we can
benefit from the same thing.
The output now looks like:
[2016-05-06 14:05:36.20 (UTC)]> cf auth admin [REDACTED]
API endpoint: https://api.dcarley.dev.cloudpipeline.digital
Authenticating...
OK
Use 'cf target' to view or set your target org and space
I've taken current HEAD of cf-test-helpers as used by cf-acceptance-tests
(not related to any particular cf-release version):
- cloudfoundry/cf-acceptance-tests@3582729
The complete diff from the previous version is as follows:
- …

[#117705909] Upgrade cf-test-helpers for password redaction 

---

concourse/pipelines/failure-testing.yml
concourse/tasks/get-instance-id.yml
concourse/tasks/recover.yml

https://github.com/alphagov/paas-cf/pull/240 missed required bosh_login.sh change in failure testing pipeline. Right now this script is using two parameters: bosh FQDN and secrets file and failure pipeline still uses only one. This PR corrects this.
Run failure testing pipeline from this branch and check if it passes. 
Not @combor

Fix bosh_login invocation - missing bosh FQDN in failure testing pipeline

---

tests/performance-tests/src/performance/load_test.go
tests/run_tests.sh

There are three related changes:
- Disable verbose mode for our own tests suites so that the output is easier to read
- Ensure that the Vegeta report is still written to the output
- Fix a typo in the `run_tests.sh` script
More detail can be found in the individual commit messages.
1. Deploy the pipelines from this branch
1. Run the `create-bosh-cloudfoundry` pipeline
1. Confirm that all of the test jobs pass
1. Confirm that the custom acceptance and performance tests don't output verbose information
1. Confirm that the Vegeta report is still visible in the performance test job
Not @dcarley. @combor should have a look, because he has some context about the Vegeta output.

Disable verbose output for platform tests

---

concourse/scripts/pipecleaner.py

117705909-ensure-temp-admin-deletion introduces `do` blocks into our pipelines, which causes ordering issues in pipecleaners dependency resolution and spurious fatal errors to be reported.
Until this fix is merged branches with `do` blocks cannot be merged. https://travis-ci.org/alphagov/paas-cf/builds/128887561

[#117705909] Fix concourse `do` blocks in pipecleaner lint

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/failure-testing.yml

Wrap all the tasks including temp. admin creation into a `do` block
to which we assign ensure step which removes the temp. admin. Previously
only last task had ensure step and if there were any issues in any tasks
before the last one (including the admin creation task), the admin user
would not be deleted.
Note that this is not displayed correctly in concourse, see https://github.com/concourse/concourse/issues/434
Apply. You can try canceling jobs as soon as create-temp-user task starts. Ensure task should run even when the job is cancelled by user.
not @mtekel

[#117705909] Make really sure temp. admin gets removed

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/extract_quota_settings.rb
concourse/scripts/spec/extract_quota_settings_spec.rb
manifests/cf-manifest/deployments/040-cf-properties.yml

[#118837127 Create trade-tariff organisation and org manager with quota](https://www.pivotaltracker.com/story/show/118837127)
Create the specific quota for Trade Tariff for 3x environments. Their current deployment is 15G, so we will set the quota to 60G.
We will create the quota named `trade_tariff` and in the future we will create more generic quotas (`big_mem`, `medium`...) as soon as we define our quota model.
We also want to make it easy to add define more quotas in the future.
The quotas are set during deployment, but we have a task in concourse to update them directly from the manifest.yml in consequent deployments. In this PR we:
* Add the new quota for trade tariff
* Add logic to allow define and update multiple quotas,
1. Deploy the environment
2. Run `cf quotas`, it should …

[#118837127] Add trade tariff quota

---

manifests/cf-manifest/deployments/900-cf-tests.yml

The acceptance-tests suite for v233 includes a test for the v3 api which fetches a go buildpack from github. Within the last 48 hours, the go buildpack has been changed in github in a manner which appears to make it incompatible with the version of the tests we're running. Later versions of the acceptance tests have been swtiched to use a ruby buildpack instead of the go buildpack - We need to disable the v3 acceptance tests (which are disabled already in the PR for upgrading to CF 235) to unblock the pipelines.
If you have an existing environment deployed from our current master branch, you will find that the acceptance tests are already failing. Deploying from this branch should fix that problem.
Anyone on the team excecpt for myself or @saliceti .

[#119177161] Turn off V3 API tests, which don't currently work

---

manifests/cf-manifest/deployments/030-cf-jobs.yml

This PR removes hardcoded zone name from metron zone property and replaces
it with empty string. Metron doppler selection is based on preferred zone
prefix that matches zone property value with doppler instance name. If
there is no match, metron forwards logs to randomly picked doppler despite
the zone it is deployed to.
This will also unblock [#119269637](https://www.pivotaltracker.com/story/show/119269637) as zone won't be hardcoded any more.
More details here:
https://github.com/cloudfoundry/loggregator/blob/a4675b0821d40743ff03424456da9b5ce8de6598/src/doppler/dopplerservice/finder.go#L193
Deploy from this branch and do `bosh ssh` to any doppler instance.
Execute as root:
```
tcpdump -i eth0 port 3457 | awk '{print $3}' | grep -v ${doppler_zone}
```
and check if you can see hostnames …

[#119268815] Cross Zone Logging for CF

---

concourse/pipelines/create-bosh-cloudfoundry.yml

What
----
In the continous smoke tests we were creating a user called
`continuous-smoketest-user`. With the random suffix that makes
a user name of 36 chars.
But it turns out that the deployment of applications fails when
using a user with 36, 35 or 34 characters in the name only in prod,
but works on staging and ci.
Longer names seem to work. We still need to investigate the root case
in a different story.
In order to allow the continuous smoke test work on prod, we change
the username to a shorter one.
How to test it
--------------
It has been already applied and tested in prod, [builds ~10246](https://deployer.cloud.service.gov.uk/pipelines/create-bosh-cloudfoundry/jobs/continuous-smoke-tests/builds/10246
Does not require too much testing, just check that makes sense.
Who?
----
Anyone …

[#119382595] Reduce the length of the temp user for smoketests

---

README.md
scripts/create-user.sh

[#118837127 - Create trade-tariff organisation and org manager with quota](https://www.pivotaltracker.com/n/projects/1275640/stories/118837127)
We want to be able to provide documentation for operations staff and users for the CF CLI. This pull request fixes two errors which may cause confusion.
Read the 'Creating Users' section of the README, make sure it still makes sense. Try the commands given to the user in the `scripts/create-user.sh` email and make sure they work.
Anyone but me @saliceti or @keymon

[#118837127] - Fixed errors in documentation for creating users

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/tasks/smoke-tests-run.yml
manifests/cf-manifest/deployments/000-base-cf-deployment.yml
manifests/cf-manifest/deployments/040-cf-properties.yml
manifests/cf-manifest/deployments/055-graphite.yml
manifests/cf-manifest/deployments/900-cf-tests.yml
manifests/cf-manifest/deployments/aws/999-cf-stub.yml
tests/acceptance-tests/apps/print_request_headers/Godeps/Godeps.json

[Story](https://www.pivotaltracker.com/projects/1275640/stories/118272895)
We upgraded:
- ~~BOSH from 255.8 to 256.2~~ Cancelled because of [this issue](https://github.com/cloudfoundry/bosh/issues/1263).  This will be done separately.
- CF from 233 to 235 and its recommended versions of diego, garden, etcd
- ~~Stemcells from 3215 to 3232.2 to get the latest security fixes~~ Cancelled because of time out issues. This will be done separately.
Changes:
- [graphite BOSH release
changes](https://github.com/alphagov/paas-graphite-statsd-boshrelease/pull/5)
were needed to work with the new BOSH
- cf-acceptance, smoke tests and app that our custom acceptance tests use to
print headers all switched to go 1.6
- ~~the new BOSH doesn't use redis~~
- We turned off the V3 suite in cf-acceptance-tests …

[#118272895] - Upgrade CF, stemcells and BOSH

---

Makefile
scripts/find_diverged_forks.py

We want to keep an eye on the repositories we have forked as they quickly diverge from upstream, this tool allows us to do that in an automated fashion.
This requires the python `pygithub` module, which can be installed using `pip install pygithub`.
Running `make find_diverged_forks GITHUB_TOKEN=<personal access token>` will output a list of forks on github belonging to the PaaS team that have diverged from the upstream repository, it will also output any open pull requests belonging to us on those forks.
While the script will run without a personal access token it will quickly run into rate limits due to the size of alphagov and the size of the repositories we have forked, so the makefile makes it mandatory.
You can get a personal access token here:
https://github.com/settings/tokens
The …

[#118830743] Command to check our github forks against upstream

---

README.md
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/destroy-microbosh.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
doc/bosh_failover.md
terraform/bosh/variables.tf

Story: [Process for recreating BOSH on AZ Failure](https://www.pivotaltracker.com/story/show/119090295)
We want to be able to recreate BOSH in another AZ in case of AZ failure and test it can still see the VMs as running.
* Apply on existing pipeline
* Kill BOSH via AWS console
* Upload pipeline with:
```
BOSH_AZ=eu-west-1b make dev pipelines
```
* This should recreate BOSH and test all VMs are in running state. You can check this by doing:
```
make dev bosh-cli
```
or check the output of bosh-tests job.
As the BOSH state file name is changed in this PR, when this is applied to CI, Staging, Prod bosh-init would try to recreate BOSH and fail because of IP conflict. To solve this rename BOSH state file in S3 to `bosh-manifest-state-eu-west-1a.json` in each environment.
Anyone but @combor or …

[#115870117] BOSH failover to other AZ

---

README.md

Having accidentally pressed the big green merge button in Github's web interface, a small and not particularly important change is required to enable a new merge commit to be properly signed.
There was a missing full-stop at the end of the sentence about creating org managers, so I've added the requisite full-stop with this commit/pr.
Check the commit and confrim that the only change is the addition of a full-stop at the end of a sentence.
Anyone on the team.

Added a full-stop at the end of a sentence

---

concourse/tasks/create_admin.yml

Store new user credentials in output immediately after user is created, so that if any of the group additions fail, the ensure task would have access to the username in the outputs.
Apply. Run your pipeline enough times till you get failure from UAA:
```
error response:
{
"error_description": "Incorrect result size: expected 1, actual 0",
"error": "scim",
"message": "Incorrect result size: expected 1, actual 0"
}
```
Check that the delete temp user task ran successfully (previously this would fail).
not @mtekel

[#119903539] Cleanup temp. admin on failure

---

concourse/pipelines/destroy-microbosh.yml

It seems that we missed the update for microbosh-destroy pipeline during implementation of deployment to multiple AZs for bosh. This PR fixes this.
Run microbosh-destroy and make sure if passes. Especially terraform-destroy task shouldn't throw:
```
Errors:
* 1 error(s) occurred:
* Required variable not set: bosh_az
```
not @combor

[#119090295] TF_VAR_bosh_az variable missing in microbosh-destroy pipeline

---

scripts/spec/pull_request_spec.rb

Without this the tests will fail if you have `GITHUB_API_TOKEN` set in
your environment as the test expectations won't match the requests that
are actually made.
Ensure that the Travis build passes.
Set `GITHUB_API_TOKEN` to something in your local environment, and verify that the tests still pass.

Clear environment before running PR specs.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/deployments/060-aws-broker.yml
tests/src/acceptance/rds_broker_test.go

This includes a number of changes to clean up the RDS broker and deployment:
* Removed support for AWS Aurora (alphagov/paas-rds-broker#5)
* Removed some unused jobs from the bosh release (alphagov/paas-aws-broker-boshrelease#6)
* Clarify the broker name. 
On the last point - the broker had been given the same name as the service it provided, which had led to some confusion (especially if we were to enable the mysql services). See the commit for more details
Deploy from this branch and verify that everything works (the custom-acceptance tests pass etc).
Anyone but @HenryTK or myself.

[#118484173] RDS broker cleanup

---

concourse/scripts/bosh_login.sh

What
----
If the random generated password for the bosh admin starts with '-', the
`bosh_login.sh` won't work because it recognises the password with an
option.
Context
-------
To avoid that we add '--' to tell bosh that the following parameters are not options.
Additionally, if the string starts with '-', ruby yaml will quote the string in the cf-secrets.yml with `"`. We need to remote these quotes before passing the password as argument.
How to test
-----------
Check that works by running rerunning the pipeline with cf-deploy, which
executes the `bosh_login.sh`.
I don't think it is necessary test when the password has a `-`
Who?
----

Fix bosh_login.sh when password starts with '-'

---

concourse/pipelines/create-bosh-cloudfoundry.yml

Story: [Process for recreating BOSH on AZ Failure](https://www.pivotaltracker.com/story/show/119090295)
There should be 2 different tests instead of one because they serve different purposes:
* making sure that make <env> bosh-cli works for humans
* making sure that VM agents are connected to BOSH after failover
* Apply to new or existing environment
* There should be 2 different bosh tests now
* You can kill a CF VM to make bosh vms fail
Anyone but me

[#119090295] Separate bosh cli and bosh vms tests

---

concourse/scripts/spec/val_from_yaml_spec.rb
concourse/scripts/val_from_yaml.rb

Write an error message to STDERR when `val_from_yaml` is unable to find a
key in the YAML document. This will make it easier to diagnose typos when
running from within the pipeline. Previously the non-zero exit code would
make the task fail without any output.
For example, when called as we do in the pipeline:
➜  paas-cf git:(master) ✗ TEST=$(./concourse/scripts/val_from_yaml.rb foo manifests/concourse-manifest/concourse-base.yml)
Unable to find key: foo
Confirm that the tests look correct and that they pass in Travis. The changes don't affect the happy path of the code, so it's probably not necessary for you to test the whole thing in a pipeline.
Not @dcarley

val_from_yaml: STDERR msg when unable to find key

---

Gemfile
Gemfile.lock
concourse/pipelines/destroy-microbosh.yml
concourse/scripts/bosh_pre_destroy.rb
concourse/scripts/spec/bosh_pre_destroy_spec.rb

It's possible to run the `destroy-microbosh` pipeline before the
`destroy-cloudfoundry` pipeline. When this happens, all of the Cloud Foundry
VMs and their related EBS volumes are left "orphaned". You have to cleanup
manually using the AWS console, which is tiresome and prone to error.
Prevent this from happening by aborting the `destroy-microbosh` pipeline
before it calls `bosh-init delete` if there are any existing deployments.
The script lists the deployments that you need to delete.
To test this I've used a library called `mimic` to mock the minimal API
responses from BOSH and overridden `BOSH_CONFIG` to point `bosh_cli` at that
fake BOSH.
I looked at using `webmock` as we've used elsewhere, but it only works for
HTTP calls within the same Ruby interpreter and I want to test the …

[#113528323] destroy-microbosh: Abort if any deployments exist

---

manifests/cf-manifest/deployments/900-cf-tests.yml

Story: [Fixing the build: multiple routes test failing](https://www.pivotaltracker.com/story/show/119991023)
The tests are failing because of a probable race condition in
https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/routing/multiple_app_ports_test.go#L44-L69
The issue was filed under:
cloudfoundry/cf-acceptance-tests#118
We disable these tests while we are waiting for the issue to be fixed.
The quickest way to test is to run the acceptance test from its container or locally and tweak the `run` script to skip all the packages but routing and enable verbose.
You should see `Multiple App Ports when app only has single route` but no `Multiple App Ports when app has multiple ports mapped`.
Anyone but @combor or myself.

[#119991023] Disable multiple ports app tests

---

concourse/scripts/fly_sync_and_login.sh

This is a different solution to the problem described and worked around in
bcb785b. We noticed some confusion when upgrading Concourse because the
wrong version of `fly` was used and not replaced because it was <24hrs old.
It's also inconvenient to wait for the file to be re-downloaded each day
when there are no changes.
We can reduce the time that old binaries are used without significantly
increasing the time it takes to run by using HTTP `If-Modified-Since`
headers. I've raised concourse/fly#87 to implement this in `fly` itself, but
in the meantime we can do the same thing using `curl` by passing the `-z`
argument. It will only download the whole file if it either:
1. doesn't exist locally
2. has a later modified time than the file we have locally
I can't see any disadvantage to not …

[#116681747] Download fly based on file modified time

---

manifests/cf-manifest/deployments/000-base-cf-deployment.yml
manifests/cf-manifest/deployments/020-cf-resource-pools.yml
manifests/cf-manifest/deployments/030-cf-jobs.yml
manifests/cf-manifest/deployments/040-cf-properties.yml
manifests/cf-manifest/spec/resource_pools_spec.rb

In order to make the upcoming transition to cloud-config and the Bosh zones features easier we want to remove things from the manifests that aren't used. This therefore makes the following changes:
* Remove NFS job definitions and related properties
* Removed unused ha-proxy and Postgres job definitions
* Remove route_registrar FIXMEs
* Remove unused nginx release
* Remove some unused resource_pools.
See the individual commits for more details.
Note: this doesn't remove the unused Diego job definitions as we're likely to use them instead of the colocated VMs at some point.
Deploy this branch. Due to the way Bosh handles jobs being removed from VMs, it's probably necessary to test both a clean deployment, and an update to an existing deployment.

[#119818859] Manifest cleanup (part 2)

---

concourse/scripts/spec/bosh_pre_destroy_spec.rb

We've seen an intermittent problem with the `bosh_pre_destroy.rb` tests
running in Travis CI whereby BOSH is unable to connect to the fake BOSH
server that's provided by Mimic.
The error is truncated in the test output because Aruba's command timeout kicks
in before BOSH has retried 4 times and printed the traceback. But you can see
it by setting `aruba_config.exit_timeout=60` in `support/configure_aruba.rb`:
1.2) Failure/Error: raise Exception.new("Last command output: " + last_command_started.output)
Exception:
Last command output: [WARNING] cannot access director, trying 4 more times...
[WARNING] cannot access director, trying 3 more times...
[WARNING] cannot access director, trying 2 more times...
[WARNING] cannot access director, trying 1 more times... …

[#113528323] Force IPv4 loopback for bosh_pre_destroy test

---

concourse/scripts/environment.sh

No story ID - I'm invoking Tech Lead privilege. This came up in conversation, but I can't remember who or when.
Stop the Concourse password from being written to STDERR each time something
calls `environment.sh`. This mostly happens on a developer's command line
when uploading pipelines, but also gets written into the task output of
Concourse tasks which call back to Concourse (e.g. self updating pipelines
and bosh-cli tests). Concourse has access to the whole environment so we
should be more protective of its password.
You'll still be able to get the password by running `make <env> showenv` and
it will still be output when running `make <env> bootstrap` which happens
less frequently and doesn't get called by Concourse itself.
1. `git checkout bugfix/dont_echo_concourse_password`
1. …

Don't output Concourse password to STDERR

---

manifests/concourse-manifest/concourse-base.yml

Upgrade the deployer-concourse stemcell to 3232.4. Version 3200 has known vulnerabilities, so we should upgrade.
Run the create-deployer pipeline (in a bootstrap-concourse instance). Verify that the deployer concourse continues to work (probably easiest to run the create-bosh-cloudfoundry pipeline).

[#120118561] Upgrade concourse stemcell to 3232.4

---

manifests/cf-manifest/deployments/040-cf-properties.yml

No story ID - I'm invoking Tech Lead privilege. This was noted in [#119983605](https://www.pivotaltracker.com/story/show/119983605) and [PaaS Improvements](https://docs.google.com/spreadsheets/d/1034dgtWbchumi-xJuTP2n4Iq8KpxF20Vrwgy3txmeBg/edit#gid=520176062).
The default address of "support.cloudfoundry.com" redirects to
"support.run.pivotal.io/home" which is the support portal for Pivotal Web
Services (commercial hosted offering).
Change it to point to our new developer documentation site instead which has
information about how to use our Cloud Foundry service and the email address
for our support ticketing system. I've dropped `/en/latest` of the URL
because it'll redirect automatically and may do some locale magic.
From looking at cf-release and capi-release it seems that this is only …

Set support_address to our developer docs

---

Makefile
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
scripts/lib/mail_credentials_helper.rb
scripts/sync-admin-users.rb

We do not have the same email addresses SES-validated in all environments, preferring addresses that are +tagged with the environment name so they can be easily filtered.
This also removes the default source email address for the mail helper so specifying one is mandatory. It also removes DISABLE_USER_CREATION and uses the presence of an email address in the env var to enable/disable the account creation, matching the behaviour of ALERT_EMAIL_ADDRESS.
Because this is disabled in dev and we'd rather you didn't email all team members this is slightly more manual than usual.
1) Fork this branch.
2) Remove all users except yourself from `config/admin_users.yml` & commit/push the resulting branch.
3) `export NEW_ACCOUNT_EMAIL_ADDRESS=the-multi-cloud-paas-team@digital.cabinet-office.gov.uk`
4) …

Use per-account email addresses for acc creation

---

concourse/pipelines/create-bosh-cloudfoundry.yml

The `tag_filter` option for the git-resource will by default only look for
tags that resolve to commits on the `master` branch, however the tag that we
were giving it resolves to a commit on the `gds_master` branch of
alphagov/os-conf-release.
This caused Concourse to hang in a rather surprising way. The `cf-deploy`
job wasn't triggered automatically, so at first glance it looked like the
pipeline had run successfully. If you triggered the `cf-deploy` job manually
then it got stuck in a "pending" state with a message:
waiting for a suitable set of input versions
Tim found that the reporting for this has improved in later versions of
Concourse:
- https://www.pivotaltracker.com/n/projects/1059262/stories/118715899
It's not clear how we missed this in testing. We can look at that after
we've …

[#120368533] Specify a branch for os-conf-release resource

---

requirements.txt
scripts/find_diverged_forks.py

Related: [#118830743 SPIKE: Investigate if forked code requires updating](https://www.pivotaltracker.com/n/projects/1275640/stories/118830743)
In #268 we added a script `find_diverged_forks.py` to check our forked repositories to their upstream
This script, in cases where the default branch (of either our fork or the origin) is not `master`, will crash as the comparison is invalid. we must use the current default branch to allow tracking of branch renames and reconfigurations.
This also includes some slightly improved formatting, and a requirements.txt addition to simplify installation.
1) Get a personal access token from https://github.com/settings/tokens
2) Run `./scripts/find_diverged_forks.py alphagov --github-token=<YOUR_TOKEN>` - this will check _every_ GDS fork
3) Wait for a really …

[#118830743] Don't crash when master is not the default branch

---

concourse/scripts/spec/tag-release_spec.rb
concourse/scripts/tag-release.sh

Story: https://www.pivotaltracker.com/story/show/120763743
Our pipeline fails if Concourse uses cached git resources that that are not in sync with origin repo. It may happen that previous run of the pipeline created a tag already so we want to detect this and skip tag promotion.
Error message from staging pipeline:
```
To git@github.com:alphagov/paas-cf.git
! [rejected]        prod-0.0.101 -> prod-0.0.101 (already exists)
error: failed to push some refs to
'git@github.com:alphagov/paas-cf.git'
hint: Updates were rejected because the tag already exists in the
remote.
```
run `make test` and check if it passes. 
not @keymon or @combor

[#120763743] Fix the tag already exist problem

---

terraform/cloudfoundry/nat.tf

Change `terraform/cloudfoundry/` to use the `nat_gateway_id` argument
instead of `gateway_id` because we're passing the ID of a NAT Gateway rather
than an Internet Gateway.
When creating or updating a `route_table` resource the AWS API will let you
use either argument interchangeably for either type of gateway. However,
when you read it back, it modifies it to the right argument. This causes
Terraform to think that the resource needs updating on every run.
I've started a discussion with upstream in hashicorp/terraform#6551 about
how this could be handled in a more explicit way.
In the meantime this change will stop Terraform from modifying our route
tables on every run of the `cf-terraform` job:
aws_route_table.internet.1: Modifying...
route.28127694.cidr_block: …

[#112234445] Use correct argument for aws_route_table gateway

---

scripts/lib/mail_credentials_helper.rb
scripts/lib/uaa_sync_admin_users.rb
scripts/sync-admin-users.rb

Make all hash lookups where we're getting (not setting) a value use `#fetch`
instead of `#[]` so that an exception is raised if we mis-type the key name
or the object isn't populated as expected. Previously a `nil` object would
be returned and the scripts could fail in a silent or unclear way.
This change highlights one such case, whereby we're using a key name with
the wrong capitalisation, which I'll fix in a following commit. We don't
explicitly test the log function where it occurs, but it now makes the tests
fail because we exercise the code path and get an exception:
Failure/Error: get_logger.info("Deleting admin user #{user_info.fetch("userName")} which is not in the list.")
KeyError:
key not found: "userName"
I haven't changed the `self.ua.all_pages` calls which return the first …

[#118838943] Fix typo in admin sync logging

---

manifests/cf-manifest/manifest/020-cf-properties.yml

Reduce UAA's logging level from the spec default of `DEBUG` to `INFO`. This
will make the logs easier to read and identify errors, as well as reducing
the amount of logs that Logsearch has to parse and store.
There doesn't seem to be much order to the `uaa` property keys. So I've
added the new property to what I think is a vaguely sensible place.
We did the same for CC in 62c0882. UAA is the last component to still log at
debug level, according to the following Logsearch query:
debug AND NOT syslog_sd_params.bosh_template:uaa AND NOT syslog_program:vcap.uaa_ctl*
I've raised an upstream PR to change the default in future:
- cloudfoundry/uaa-release#20
1. Go to logsearch for your environment (URL in `make dev showenv`).
1. Search for `debug` and confirm that UAA is outputting debug logs.
1. …

[#121215337] Change UAA logging level from DEBUG to INFO

---

manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/030-logsearch.yml
manifests/cf-manifest/manifest/040-graphite.yml
manifests/cf-manifest/manifest/050-rds-broker.yml

[Remove BOSH migrated_from property](https://www.pivotaltracker.com/projects/1275640/stories/121055399)
We have now finished migration to cloud_config. No need to keep `migrated_from` in the manifest any more. Clean up cf-manifest to stop BOSH looking for previous jobs on every deploy.
Apply to existing environments. On BOSH deploy, you should see that migrate_from was removed from all jobs that had it. But on actual deployment, there will be no changes applied to CF.
not @mtekel

[#121055399] Remove migrated from

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/cf-manifest/scripts/generate-cf-secrets.rb
manifests/shared/spec/fixtures/cf-secrets.yml
scripts/tag-rds-instances.sh

[Generating secure master password for Postgres Instances](https://www.pivotaltracker.com/n/projects/1275640/stories/118479861)
Deploy against new or existing deployment. In the existing deployment, you can observe in the RDS broker logs that it fails to 'ping' instances with old password and that it does PW update. All tests should pass.
This PR depends on 2 other PRs. It contains temporary commits to use them from branch (before they are merged) so that you can test. Once these PRs are merged, remove these respective temporary commits:
Merge only after above PRs have been merged and temp commits removed. To be really sure, you can test again after removing the temp commits...
not @saliceti or @mtekel or @keymon

[#118479861] Use new, password generating RDS broker

---

concourse/tasks/create_admin.yml

Use uaac curl to work around uaa group add concurrency issue (see https://github.com/cloudfoundry/uaa/issues/372).
Use the suggested atomic endpoint instead of using `uaac` member add functionality.
Deploy. Run pipeline several times and observe that starting all tests concurrently doesn't cause concurrent user addition to fail.
not @mtekel

[#120376951] Workaround UAA race condition for user membership

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml

This upgrades Cloudfoundry to release 237. It also upgrades the related components to the recommended versions for this release:
* diego to 0.1472.0
* etcd to 49
The diego release includes some changes to how the releases are structured:
* the rootfses have been split into a separate release
* the cc-bridge jobs have been extracted into a separate release `capi-release` which is now included as part of the CF release.
See the corresponding commits for more details.
This should be tested by deploying both a clean environment, and an upgrade of an existing environment.
Anyone but myself or @Jonty.

[#120591859] Upgrade cloudfoundry to 237

---

.travis.yml

Upgrade spruce version to 1.5 to match what we use in the pipeline. To be merged after https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/57
Check that the travis tests pass. Meaning, this PR is able to merge.
not @mtekel

[#111700216] Use spruce 1.5 in travis tests

---

concourse/tasks/remove-healthcheck-db.yml

At present the remove-healthcheck-db task in the destroy-cloudfoundry
and autodelete-cloudfoundry pipelines will error if the CF api is
available, but the testers org doesn't exist. This can happen if the
cf-deployment succeeds, but one of the post-deploy tasks fails for some
reason.
This updates the task to check for the exsitence of the testers org
before attempting to delete the healthcheck app and db. If the org isn't
present, the app and db can't exist, so it's safe to just skip the task.
* Use the cf cli to delete the healthcheck app, db and then delete the whole testers org.
* Run the `destroy-cloudfoundry` pipeline (you may want to pause the terraform destroy job if you don't want the dstroy to go this far), and observe it fail.
* Update concourse to use this branch, and re-run. …

[#122187235] Fix delete-deployment when testers org doesn't exist.

---

terraform/bosh/rds.tf

This has better performance than the default (magnetic) storage that
it's currently provisioned with.
This modification will not apply immediately; it will apply during the
configured maintenance window. During this time there will be a few
minutes of downtime. In my dev environment, bosh was unavailable
for 3 minutes while the RDS instance restarter. After that, all was well.
* Using the RDS console to change the maintenance window of your bosh RDS instance to happen in a few minutes time (note: the window is specified in UTC).
* Watch while the change is applied during the maintenance window. Verify that everything is working correctly after the change has completely applied.
Run another deploy to set the maintenance window back to the correct value.
Anyone …

[#122117381] Use gp2 storage for Bosh RDS instance.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/destroy-microbosh.yml

Because the updated state file was only copied into the output directory
after the bosh-init run, if bosh-init errored for any reason, this would
not happen, and the ensure block had no file available to upload.
This refactors the task to use the output dir as the working dir for
bosh-init meaning that the updated state file is always available to the
ensure block.
Given an environment with an existing bosh VM:
* Rename the existing bosh-manifest-state file in your S3 bucket.
* Run the pipeline from this branch.
* Observe bosh-init error when trying to create a new bosh vm due to an IP conflict.
* Verify that the updated state file is uploaded to S3
* Restore the original state file.
* Run the pipeline again, and verify that it succeeds.

[#122188819] Fix capture of bosh-init state on error.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/030-logsearch.yml
manifests/cf-manifest/manifest/040-graphite.yml
manifests/cf-manifest/manifest/runtime/runtime.yml

https://www.pivotaltracker.com/projects/1275640/stories/121843167
A Collectd release has been forked from the CloudFoundry Community respositories and applied as an addon in Bosh, making it available on all VMs managed by Bosh. Collectd is configured to send metrics directly to Graphite. Logsearch-shipper has been removed as most of the logs were duplicates of what is already sent by Metron. See commit message for full details.
* Deploy using the branch `collectd_121843167`.
* Check Collectd data is sent to Graphite (get Graphite URL using `make dev showenv`).
Anyone but @Jonty or me

[#121843167] Ensure Collectd is configured on all VMs

---

Makefile
README.md
concourse/scripts/run_job.sh
concourse/scripts/spec/unbind_job_spec.rb
concourse/scripts/unbind_job.rb

[Run specific Pipeline Jobs / Tasks](https://www.pivotaltracker.com/n/projects/1275640/stories/120654489)
Add a makefile target to run pipeline from specific job, ensuring that job is able to pick up latest changes in paas-cf. We do this by adjusting the pipeline by removing 'passed' for paas-cf in the given job.
Run `JOB=myjob make dev run`. Observe that job having it's paas-cf "unbound" from previous jobs and being triggered.

[#120654489] Start from specific job

---

terraform/bosh/rds.tf

When this is not specified, RDS will pick a random window that's
appropriate for the region. There's therefore a chance that this will
conflict with the maintenance window that we're specifying here.
Specifying the backup window avoids the possibility of these
conflicting.
Deploy from this branch, and verify that it applies cleanly.

[#122117381] Set Bosh RDS backup window.

---

concourse/pipelines/create-bosh-cloudfoundry.yml

This reduces the number of loops/bypasses in the pipeline and makes it
easier to see what's flowing where. It generally makes the input pinning
more consistent for several jobs - they're all pinned to the same
previous job if possible.
* Pin cf-terraform inputs to pre-deploy
* Pin post-deploy inputs to cf-deploy
* Pin cf-secrets and cf-manifest for smoke/acceptance tests to
post-deploy.
* Pin cf-secrets in performange-tests to smoke/acceptance tests
Before:
After:
Before:
After:
Check changes look sensible, and the pipeline dependencies are still correct.

Update resource pinning to simplify pipeline.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/020-cf-properties.yml

This was set to 'GDS' in 11318b0 for no real reason that I can remember
(I was working on that story). Having it set to 'GDS' could lead to
confusion as there are likely to be several services deployed to the
PaaS from teams within GDS.
This sets it back to 'admin' which is the cloudfoundry default. The
admin org is also where we deploy some system components like the
graphite nozzle, so seems like a good org to own this.
Note:
Changing the `system_domain_organization` in the manifest doesn't result
in this being applied when deployed to an existing deployment. This
therefore adds a task to remove the old org (and thereby delete the
domain), and add the system domain to the admin org.
I've therefore added a temporary task to the post-deploy jobs to clean this
up.  It should be reverted …

[#122581781] Set system_domain_organization to 'admin'

---

tests/src/availability/healthcheck_availability_during_deployment_test.go

We noticed that there was a data race in the availability tests in this run https://deployer.staging.cloudpipeline.digital/pipelines/create-bosh-cloudfoundry/jobs/availability-tests/builds/11. One of the output lines is:
```
- Duration: 35m4.799999798s, Requests: 21049, Non 200 Requests: 18446744073709551615, Success Rate: 100.00%
```
This fixes the data race by introducing a lock around the metrics instance, and ensuring all metrics are consumed before the final assertion.
Deploy from the `fix_availability_tests_race_with_detector` branch (This branch includes everything on the PR branch, and additionally enables the race detector) and verify that the availability tests pass without any race detector warnings. 

[#119272203] Fix data race in availability tests

---

concourse/pipelines/create-bosh-cloudfoundry.yml

#337 Changes the system domain org back to 'admin', and retuired a temporary task to cleanup the existing state. This is no longer needed now that it's run on production. This reverts commit 1beca4e35a2ed7e466289dcd6930319e253011e9.
Code review. Verify that this reverts the above commit and nothing else.

[#122581781] Revert "Temporary pipeline task to fix system domain org"

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml

Story: https://www.pivotaltracker.com/story/show/121933113
It's a part of zero downtime deployment epic. 
This PR implements custom healthcheck for haproxy to enable connection draining to make sure we don't server any errors during cf-deploy.
Also we split routing-release from main cf-release and use our fork to deliver gorouter fix for early exit when more than one signal is received. More details about that fix in routing-release PR: https://github.com/alphagov/paas-routing-release/pull/1
As a result of above listed changes we increase the availability test success rate threshold to 100% as we expect true zero downtime deployment now  
Not @saliceti , @timmow or @combor

[#121933113] Fix gorouter issue for zero downtime deploy

---

manifests/cf-manifest/manifest/040-graphite.yml

As we are going to create a set of dashboards we want them to be compatible with recent versions of Grafana and avoid upgrade pain in the future.
Deploy from this branch. Go to Grafana - you can check what the URL is with `make dev showenv` and confirm that the version is 3.0.3. You can find it on the bottom of the login screen. 
Not @combor or @saliceti

[#122183539] Upgrade Grafana to the latest tagged version.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/failure-testing.yml
concourse/tasks/generate-test-config.yml
manifests/cf-manifest/cloud-config/020-cf-vm-types.yml
manifests/cf-manifest/cloud-config/050-rds-broker.yml
manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/shared/spec/fixtures/terraform/terraform-outputs.yml
platform-tests/src/acceptance/run_tests.sh
terraform/cloudfoundry/component_security_groups.tf
terraform/cloudfoundry/dns-records.tf
terraform/cloudfoundry/outputs.tf
terraform/cloudfoundry/rds_broker.tf
terraform/cloudfoundry/service_broker_security_groups.tf

[#118909613 - HA Postgres Service Broker](https://www.pivotaltracker.com/story/show/118909613)
To minimise downtime of the RDS broker we have made it highly available. This has been achieved by increasing the instance count to 2 and using an ELB.
In order to put the broker behind an ELB, we've added a healthcheck endpoint to it. [These](https://github.com/alphagov/paas-aws-broker-boshrelease/pull/10) [PRs](https://github.com/alphagov/paas-rds-broker/pull/13) have already been merged, and the broker boshrelease tagged as `0.0.7`.
As part of this work we've reduced the size of the `rds_broker` VMs as they were much larget than they needed to be. See commit "Reduce size of rds_broker VMs to t2.nano" for full details.
Deploy from this branch. Verify that all the tests pass.
Run the …

[#118909613] HA Postgres Service Broker

---

manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml

[Remove collector](https://www.pivotaltracker.com/projects/1275640/stories/115404231)
In our current deployment, collector is not configured to send metrics anywhere (even though it might seem so from logs, but historian has no targets configured). Also remove etcd_metrics_server, as that was sending etcd metrics to NATS for them to be picked up by collector.
Deploy to new/existing env. In existing env observe collector being deleted and etcd upgated. Check that there is no metrics job on etcd servers.
not @mtekel

[#115404231] Remove collector

---

platform-tests/src/availability/healthcheck_availability_during_deployment_test.go
terraform/cloudfoundry/router_elb.tf

This is follow up to https://github.com/alphagov/paas-cf/pull/341 to enable custom haproxy healthcheck which sends specific user-agent to gorouter. 
Please merge it after its parent has been deployed to production.
Apply on top of existing env and check if availability test passes.
Not @saliceti or @combor

[#121933113]  Enable HTTP healthcheck on router ELB

---

manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml

This reverts commit b3092a1da86a3236f93f67a51ba3ed74506bc18f.
As it turns out, ETCD metrics server was also sending metrics to doppler,
meaning they would make it to our graphite nozzle which was adding them
to graphite. Add this component back so that we have ETCD metrics again.
Unfortunately no etcd_metrics_server documentation mentioned this
feature. It was added in this commit:
https://github.com/cloudfoundry-incubator/etcd-metrics-server/commit/0668d4fcbb66105d1c13f6d72ac130792b52cc26
Deploy. Verify that you can see metrics from ETCD in graphite, e.g. `stats.gauges.cfstats.etcd.0.ops.etcd.CreateFail`
not @mtekel

[#124748631] Revert "Remove etcd_metrics_server"

---

manifests/cf-manifest/manifest/050-rds-broker.yml

Fix a bug with the master password reset where it would use the wrong password. See https://github.com/alphagov/paas-rds-broker/pull/14 for details.
Deploy from this branch and verify that the custom acceptance tests still pass.

[#124755971] Fix rdsbroker master password reset

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/manifest/900-cf-tests.yml
manifests/cf-manifest/manifest/env-specific/cf-default.yml
manifests/cf-manifest/manifest/env-specific/cf-prod.yml
manifests/cf-manifest/spec/manifest/base_properties_spec.rb
manifests/cf-manifest/spec/manifest/env_spec.rb
manifests/cf-manifest/spec/manifest/jobs_spec.rb

In order to get the fix for CVE-2016-4468 (UAA SQL Injection). This upgrades to Cloudfoundry release 238.
This includes a release of Diego that supports the Bosh 2.0 zones feature, so I've also combined the cell_z*N* and colocated_z*N* jobs.
While upgrading, we ran into issues where existing deployed apps would stop working. This turned out to be because our diego jobs weren't ordered correctly so that the cells were upgraded before the database migrations had been applied.
This should be tested twice, one as a clean deploy, and once upgrading from current master:
* test that a new deploy from this branch works correctly.
* Given an existing deployment running current master, test that deploying from this branch upgrades CF without downtime.
Anyone but myself or @bleach.

[#123862321] Upgrade to CloudFoundry 238

---

concourse/pipelines/failure-testing.yml

In 70b43c20 we merged the colocated_z* and cell_z* AZ specific jobs into
combined jobs using the new Bosh AZs feature. This change was not also
reflected in the failure testing pipeline, meaning that it was broken.
This fixes that.
Deploy from this branch and verify that the failure testing pipeline works.

[#123862321] Fix failure testing pipeline for merged diego jobs.

---

Gemfile
Gemfile.lock
concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/grafana/user-impact.json
manifests/cf-manifest/manifest/040-graphite.yml
manifests/cf-manifest/scripts/grafana-dashboards-manifest.rb
manifests/cf-manifest/spec/support/manifest_helpers.rb

[#122183539 - Visibility of important platform metrics](https://www.pivotaltracker.com/story/show/122183539)
We want to be able to deploy Grafana with dashboard configuration files (JSON files) supplied via the manifest. This pull request configures Grafana to use Graphite as a datasource, updates the pipeline to generate YAML containing the minified JSON, and adds the dashboard JSON file.
**Note:** review after [pull request 58 on paas-docker-cloudfoundry-tools](https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/58) has been merged and [this FIXME commit](https://github.com/alphagov/paas-cf/pull/351/commits/2287e3ad5cf794e8f4c3ae21faf08109084f00ee) on this repository has been removed.
* Complete the review in [pull request 1 on …

[#122183539] Visibility of important platform metrics

---

scripts/create-user.sh

Change to the welcome email text, reminding user to change password.
This addresses user concern about receiving emails in plain text, found in user research.
See [Include Change Password Instructions in Welcome Mail][1] for
details. There is no point putting the actual command to change
password in the welcome email, because that won't work until user is
logged in, but adding this reminder makes clear that the password that was
included in the email can be changed by the tenant.
Also style fixes to email copy.
Check the email copy makes sense. Check the email is still sent correctly when a the script runs.
Anyone but BH.
[1]: https://www.pivotaltracker.com/story/show/125537351

Add reminder to change password

---

manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/spec/manifest/jobs_spec.rb

We want to switch to using separate VMs for the diego components, as recommended by upstream. From http://cf-dev.70369.x6.nabble.com/cf-dev-How-to-minimize-VMs-used-in-cf-diego-td4216.html:
> Also, as a warning, the Diego team doesn't regularly test the colocated-VM deployment configuration, so it's possible that it may accidentally break in the future (or even that it's broken now!). So I wouldn't recommend its use in a production deployment.
To avoid downtime, we're doing this as a 2 phase approach. This first step, adds the new VMs, but leaves the collocated VMs in place for now. This means that we'll have 4 instances of each component for the moment. Once this has been deployed to prod, we'll do a follow-up PR to remove the collocated VMs.
This PR also cleans up a couple of `FIXME`s, …

[#115884129] Switch to separate diego job distribution

---

manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/spec/manifest/jobs_spec.rb

What
===
Remove `colocated` job, since it has been split into separate jobs for the separate Diego components.
The PR for the split was https://github.com/alphagov/paas-cf/pull/355
This is the last phase of the 2-phase deploy we decided on.
It should only be merged once the first PR has been deployed.
How to review
-----
Deploy from master, then deploy from this branch. Verify that everything still works paying particular attention to the availability tests.
Who can review
-----
Anyone except @alext @HenryTK @benhyland

[#115884129] Diego distribution remove colocated (master)

---

manifests/cf-manifest/manifest/040-graphite.yml

Story: [Fix timeouts starting graphite](https://www.pivotaltracker.com/story/show/126296129)
Graphite upgrade to fix recursive `chown` in the start script that becomes very slow when there are lots of metrics. 
* Review together with https://github.com/alphagov/paas-graphite-statsd-boshrelease/pull/6
* Deploy from this branch and follow the instructions from https://github.com/alphagov/paas-graphite-statsd-boshrelease/pull/6
* After merging https://github.com/alphagov/paas-graphite-statsd-boshrelease/pull/6 :
-  create tag on https://github.com/alphagov/paas-graphite-statsd-boshrelease ( based on commit sha)
- update https://github.com/alphagov/paas-cf/pull/360/commits/1409ca0bb658d15ced486c33d7e573fa346fc81c to include the tag
- remove …

[#126296129] Upgrade graphite to fix start timeout

---

manifests/cf-manifest/grafana/user-impact.json

The LRP metrics come from BBS but BBS has moved from 'colocated' to
'database' VM. The metric name contains the VM name so it must be
updated.
Deploy and load the metrics dashboard, it should show the LRP metrics.

[#115884129] Fix LRP metrics

---

manifests/cf-manifest/grafana/user-impact.json

So that we can see the most recent metrics, rather than the metrics at the
time the tab was last loaded or manually refreshed.
We could have chosen an auto-refresh value of 10s or more, because that's
the max resolution we collect metrics at. Alex and I decided that 10s was
probably too frequent for a large screen that we only look at occasionally
and it *could* generate some load on Graphite. 1m didn't seem frequent
enough. So we went for 30s, which is in the middle.
The value can be changed in your browser if you're viewing the dashboard
locally on your own laptop.
Our dashboard screen will need to be manually refreshed to pick up this
change. It seemed to take a few minutes between the time that BOSH deployed
the change and the updated dashboard was available, possibly because BOSH …

[#126600839] Auto-refresh user-impact dashboard every 30s

---

manifests/cf-manifest/manifest/020-cf-properties.yml

Now that we're creating more orgs we want some standard quota definitions that can be applied to to these orgs.
This PR also removes the `paas_demo` quota as this is identical to the new `small` quota. The quota setting script doesn't delete quotas not present in the manifest (it's create/update only), so this won't actually remove the quota from the deployment. Once this is deployed, the quota for the paas_demo org can be updated to use, and then I'll add a temporary task to clean up this quota.
Deploy against an existing environment from this branch. Verify that the new quotas are created. Verify that the existing `paas_demo` quota isn't removed.

[#126686741] Create some standard quotas

---

concourse/pipelines/failure-testing.yml

Commit b8648a7 removed the colocated job from this pipeline, but failed
to update the following job that depended on it.
Verify that the pipelines can be successfully pushed to concourse (`make dev pipelines`)

Fix failure-testing pipeline.

---

concourse/scripts/spec/bosh_pre_destroy_spec.rb

Start fake BOSH just once for the bosh_pre_destroy test suite.
The motivation for the change is that we have intermittent failures in these
tests, caused by a race condition to do with how the `mimic` http server for faking
http services is started and stopped.
We currently start a new server at the beginning of each test and
stop it at the end of the test.
Normally the error seen is `ECONNRESET` during the check mimic does to ensure the server is started before tests proceed, but we have seen other failure modes as well.
With this change, we start it once at the beginning of the suite, remove all routes at the end of each test, and then shutdown the server at the end of the suite.
We introduce this change now rather than later because the build failed for this
reason during our …

[#126795275] Start fake BOSH once in bosh_pre_destroy tests

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/set_rds_backup_retention.sh
manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
requirements.txt

[#126398487 Enable Backups for Postgres instances](https://www.pivotaltracker.com/n/projects/1275640/stories/126398487)
We want to ensure that RDS instances created by the broker have backups enabled and retained for 7 days.
We also want to change the existing provisioned instances to this default value.
1. Deploy the environment with `master`
2. In AWS console, change the "Maintenance window" of the `healthcheck-db` (search for a `rdsbroker-*` RDS instance in your VPC) to something in the next 20-30 minutes or so. Be aware it is UTC time, so 1h less than London. Check the "Apply immediately" checkbox. 
3. Deploy this branch. The RDS broker instances should be updated and the post-deploy job should update the existing instances.
Check that new instances have the right retention:
1. Try to …

[#126398487] Set RDS Broker backup retention period to 7 days

---

concourse/pipelines/create-bosh-cloudfoundry.yml

[#126686741 Create digitalmarketplace Org and Users](https://www.pivotaltracker.com/n/projects/1275640/stories/126686741)
Now that we have some standard quotas in place (#368), these org-specific quotas are no
longer needed. This cleans them up from existing environments.
I've manually verified that these quotas are not currently in use by anything on production.
Once this has run everywhere, we'll need a follow-up PR to revert this.
Run the deploy against an existing environment that has the `paas_demo` and/or `trade_tariff` quotas defined. Verify that the quotas get removed. Verify that a second run of the cf-deploy job doesn't error.

[#126686741] Remove unneeded org-specific quotas.

---

Gemfile.lock
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/kibana_set_utc.rb
concourse/scripts/spec/kibana_set_utc_spec.rb
rubocop.yml

Story: [Set logsearch timezone to UTC](https://www.pivotaltracker.com/story/show/121043905)
Change kibana settings to display log timestamps in UTC instead of the browser's local timezone (e.g. BST). This will make it easier to correlate with other logs and incident reports.
Apply on top of master branch and:
- go to Kibana ( you can find the URL from `showenv` make target )
- go to settings
- go to advance settings 
- check if `dateFormat:tz` is set to UTC
- search logs in Kibana and select absolute time to be one hour ahead - you should see no logs there  
not @benhyland or @combor

[#121043905] Set kibana timezone to UTC

---

concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/create-deployer.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/destroy-deployer.yml
concourse/pipelines/destroy-microbosh.yml
concourse/pipelines/failure-testing.yml
concourse/scripts/bosh-cli.sh
concourse/scripts/self-update-pipeline.sh
concourse/tasks/create_admin.yml
concourse/tasks/delete_admin.yml
concourse/tasks/generate-test-config.yml
concourse/tasks/get-cf-cli-config.yml
concourse/tasks/get-instance-id.yml
concourse/tasks/kill-instance.yml
concourse/tasks/recover.yml
concourse/tasks/remove-healthcheck-db.yml
concourse/tasks/smoke-tests-config.yml
concourse/tasks/smoke-tests-run.yml
manifests/concourse-manifest/concourse-base.yml
manifests/concourse-manifest/spec/reference_comparison_spec.rb

[Upgrade Deployer Concourse](https://www.pivotaltracker.com/n/projects/1275640/stories/117991263)
Run bootstrap pipeline & watch it upgrade your concourse. Run your new concourse to confirm all still works fine. A good test is to run pipeline against existing environment and observe if anything is being changed.
Before you merge check if any other PRs have been merged since this PR was opened. If so, check if any changes to pipelines use/introduce `image:` definition of container. If so, rebase on master and convert this to `image_resource` like the rest of container specifications in the pipelines. Note that bootstrap create/destroy and auto-delete pipelines should still use `image:` as they are meant for older bootstrap concourse.
This PR depends on …

[#117991263] upgrade concourse to 1.5.1

---

concourse/pipelines/create-bosh-cloudfoundry.yml

This was erroneously changed from 2.2 to 2.2-slim in e36570f.
This script needs to use the fat container because it needs a compiler
to be able to do a bundle install. The slim container doesn't include a
compiler etc.
Code review.
Verify that a bundle install works for the script directory using the ruby:2.2 container:
```sh
docker run --rm -t -i -v $(pwd):/paas-cf ruby:2.2 sh -c 'cd /paas-cf/scripts && bundle install'
```
Anyone but @combor or myself

[#117991263] Fix sync_admin_users container version.

---

concourse/pipelines/create-bosh-cloudfoundry.yml

Otherwise the pipeline fails with `failed to read request: json: cannot unmarshal number into Go value of type string`.
This is because the YAML parser is automagically inferring the type of
the value as a number, which then gets sent in the JSON to the
image_resource container leading to this error.
Code review
`make def pipelines`, and then run the cf-deploy job. Verify that the sync_admin_users task doesn't error with the above error.

Specify container version as a string.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/create-deployer.yml
concourse/pipelines/destroy-deployer.yml
concourse/pipelines/destroy-microbosh.yml

Concourses have now all been upgraded and we can use bosh-init from master once we merge https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/60.
Run the pipeline, hijack the bosh-init container and check which version is it running.
not @mtekel

[#117991263] Use bosh-init from master

---

scripts/Gemfile
scripts/Gemfile.lock

`paas-cf/scripts/Gemfile` was forked from `paas-cf/Gemfile` in d271b43
because at the time `bosh_cli` and `cf-uaac` couldn't be loaded at the same
time due to cloudfoundry/cf-uaac#24. This has now been released but changing
it will require more changes to dependencies and testing.
Some of the dependencies that were copied are not needed by `scripts/`, at
either test-time in Travis or run-time in the pipeline. Removing them will
mean less dependencies to manage and a small speed improvement to how fast
the Travis tests and `sync-admin-users` task take to run.
NB: The referenced story has not been started. I noticed this was slowing me down slightly when working on something else.
Foremost:
1. Check that the Travis build still passes.
I have tested that `sync-admin-users` still works. If …

[#120829637] Remove some dependencies from scripts/Gemfile

---

manifests/cf-manifest/grafana/vm-resource-usage.json

This is useful to see the CPU/memory usage of individual VMs. I've found this useful when trying to see what VMs are doing, and make judgements on sizing etc.
Deploy from this branch. Check the new dashboard is in grafana, and looks good.

Add VM Resource Usage Grafana dashboard.

---

concourse/pipelines/create-bosh-cloudfoundry.yml

Acceptance tests currently `cat` generated config. It contains sensitive credentials. Don't display it.
Apply. Run acceptance tests, check that they don't cat the rendered config any more.
you

[#127281697] Hide credentials when configuring acceptance tests

---

README.md
manifests/concourse-manifest/concourse-base.yml

We've been running into issues where the concourse machine will grind to a halt. Investigation lead to baggageclaim running into 'no space left on device' errors form it's loopback mounted volumes filesystem. This was created as a sparse file set to the full size of the `/var/vcap/data` filesystem. This causes problems because this filesystem is also used by other things (bosh packages and jobs, garden's graph and depot, logs etc). When this volume starts to get full, this can lead to errors when the btrfs driver gets a `no space left on device` error when writing to the sparse image file. This in turn causes a kernel error, and the loopback filesystem gets remounted read-only.
This PR does a few things to address this:
* Increase the ephemeral disk size to give more headroom
* Pull in a …

[#127256345] Fix issues with concourse running out of disk space

---

manifests/cf-manifest/grafana/vm-resource-usage.json

Add a swap graph to the VM Resource Usage dashboard. This can be useful to see when a machine is stressed.
Upload this dashboard to grafana and verify that it works, and looks sensible.

Add swap to VM Resource Usage grafana dashboard

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml

Story: https://www.pivotaltracker.com/story/show/127260745
This PR brings custom version of REP via bosh-release that was compiled against patched version of locket library and fixed cloudfoundry/diego-release#177 issue. You will be testing this together with https://github.com/alphagov/paas-rep-boshrelease/pull/1
- review https://github.com/alphagov/paas-rep-boshrelease/pull/1 first
- upload and deploy pipeline
- check if rep release was created and deployed
- check if availability test passes
- now you can change the stemcell for consul VMS
- create wip branch based on this one
- cherry-pick https://github.com/alphagov/paas-cf/commit/589c546430f93aeb97fba67653807f8c25349ab7 and deploy
- before merging remove https://github.com/alphagov/paas-cf/pull/395/commits/1841608e645a06ab36709d6ecfb …

[#127260745] Replace REP from diego-release with our own custom one

---

.gitignore
terraform/scripts/set-up-pingdom.sh

Story: [Email Alerts from Pingdom](https://www.pivotaltracker.com/story/show/120100877)
Previously we used to download the state file from the bucket, reupload it after terraform run, then delete the local copy.
b01f941 changed this to use terraform built-in S3 storage. Unfortunately it still kept a local copy of the state file, and this confused terraform when we applied changes to different environments.
This PR deletes the local copy to avoid this issue and reverts the gitgnore change related to the state file.
* In case of an issue, a terraform pingdom run in one environment was reconfiguring alerts from the previous environment.
* Run `make <env> pingdom` successively in different environments for example dev, ci, staging. It shouldn't do anything. 
Anyone but me

[#120100877] Fix terraform state issue

---

terraform/pingdom/pingdom.tf

So that Terraform doesn't attempt to set the URL on every run:
Initialized blank state with remote state enabled!
Remote state configured and pulled.
pingdom_check.paas_http_healthcheck: Refreshing state... (ID: 2247550)
pingdom_check.paas_db_healthcheck: Refreshing state... (ID: 2247551)
pingdom_check.paas_http_healthcheck: Modifying...
url: "/" => ""
pingdom_check.paas_http_healthcheck: Modifications complete
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
This happens because the Pingdom API has a default by the Terraform provider
doesn't. Longer term I hope to fix the upstream provider as discussed in
russellcardullo/terraform-provider-pingdom#4, but shorter term this change
will make it easier to see whether Terraform is making real changes.
1. Export AWS keys for the CI …

[#120100877] Set check URL for Pingdom HTTPS check

---

terraform/pingdom/pingdom.tf

This feature is useful to determine whether something needs to be
investigated urgently or how long it was down for.
I believe it was previously configured for all of our checks, by default,
but was disabled either when we changed the contact notification settings in
7024837 or recreated the checks as part of deploying that change.
Managing the attribute explicitly will make sure it is always enabled.
1. Export AWS keys for the CI account.
1. Set the environment name for CI: `export DEPLOY_ENV=master`
1. Deploy: `make ci pingdom`
1. Confirm that it only changes the `notifywhenbackup` attribute.
1. Log into Pingdom (user and pass in credentials store).
1. Confirm that the "Alert when back up" checkbox is ticked for both CI checks.
Please apply to staging and production after merging.
Not …

[#120100877] Pingdom send alerts when back up

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/030-logsearch.yml

Cloudfoundry component logs can be parsed and structured before sending them to elasticsearch in logsearch, specially the "structured" log messages (json). That will ease a lot troubleshooting, analyse, and correlate the log messages in kibana.
logsearch used to provide logsearch-for-cloudfoundry [which has been moved to cloudfoundry-community](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry). Since then, it had a lot of contributions and the code seem to have improved a lot, with better testing (even travis) and better code structure and documentation
We add the logsearch-for-cloudfoundry filters to our logsearch parsers.
* We won't install the kibana dashboards or type indexes
* We won't setup the firehose
* Upgrade logsearch (currently we have v200.0.0, the latest …

[#124841811] setup logsearch-for-cloudfoundry filters

---

manifests/bosh-manifest/reference-bosh-manifest.yml
manifests/shared/deployments/collectd.yml

VMs that host containers, such as Concourse and Diego cells, create and
destroy virtual network interfaces very frequently. With collectd's default
configuration of the `interface` plugin this results in Graphite/Carbon
allocating storage for a new Whisper file every time a container is started.
These metrics aren't useful because we can't tell what container each
randomly-generated interface name belonged to. They consume a lot of space
on disk, even with automatic pruning of stale metrics after 10 days. Current
usage on prod:
bosh_zczgqkgrr@91b8d5a4-55ee-4a6e-ac9f-27f6a2b945f9:~$ du -csh /var/vcap/store/graphite/storage/whisper/collectd/{concourse,cell}_*/interface
61G     /var/vcap/store/graphite/storage/whisper/collectd/concourse_collectd_0/interface
10G …

[#127558109] collectd: Only get interface metrics for lo0/eth0

---

Makefile
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh

Disable healthcheck DB on DEV
This commit disables provisioning of healthcheck DB on DEV environments to
save space,time and money :). It keeps it enabled on non-dev envs.
Changes consists of default setting in Makefile, that is passed via
pipeline upload script and new condition in deploy-healthcheck to test it.
Deploy pipeline - during running of post-deploy.deploy-healthcheck note the new order of operations doesn't include provisioning a `healthcheck-db` service.
Cannot be reviewed by @combor or @richardc

[120765225] Disable healthcheck DB on DEV

---

manifests/concourse-manifest/concourse-base.yml

This reverts commit bbeddf48a80b49d26ce6c86930d90d99a03c09f0
This was changed to reduce the number of containers in flight at a point
when concourse was creating a large number of them due to issues with
how image_resource worked. As of 1.5.1, this problem has been
significantly reduced, so this is no longer necessary.
We are currently seeing issues with concourse not releasing volumes,
resulting in baggagclaim's volumes filesystem filling up, leading to
errors, and high resource usage. I have a hypothesis that there's
something within concourse that breaks if garden reaps idle containers
in less than the default time (5mins).
I've tested reverting this setting on my dev environment to see if it
helps, and the problem isn't occurring there. This is not conclusive as
the problem appears to …

[#127256345] Revert "Reduce container grace to 1m"

---

Makefile
README.md
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/tasks/create_admin.yml
concourse/tasks/delete_admin.yml

[#123510111 Stop running cf-acceptance-tests in staging and production](https://www.pivotaltracker.com/story/show/123510111)
What
====
We want to disable the execution of acceptance tests in staging and prod, and allow disable it in any other environment providing a flag.
The reason is that running the tests in prod/staging do not provide so much value, and some of the acceptance tests are not safe to run in production, as they occasionally fail in an unsafe way.
Context
-------
We add a new environment variable `ENABLE_CF_ACCEPTANCE_TESTS` which is by default `true`, but `false` for prod and staging. The operator can optionally enable this variable if required.
This will only stop the tests from running, but we will continue configuring the jobs in concourse, and even execute all the …

[#123510111] Do not run Acceptance Test in prod and staging

---

terraform/cloudfoundry/cf_api_elb.tf
terraform/cloudfoundry/elb_access_log_bucket.tf
terraform/cloudfoundry/policies/elb_access_log_bucket.json.tpl
terraform/cloudfoundry/router_elb.tf
terraform/globals.tf

What
====
We want to enable access log shipping in the ELBs to be able to troubleshoot and track any access. The logs will be ship to a S3 bucket and stored for up to 30 days (same as logsearch).
Out of scope: ingest the logs in logsearch.
Dependencies
----------
https://github.gds/government-paas/aws-account-wide-terraform/pull/52 must be merged and applied first to allow the deployer to create the bucket.
Once merged, remove the WIP commit that workarounds the lack of permissions.
How to review?
------------
1. Check the commits and review that make sense.
2. Deploy up to the cf-terraform job.
3. Check that the new bucket is created. You can wait some minutes and check that there are logs being generated for each ELB.
4. Check that the expiration lifecycle is defined, by downloading the …

[#125830841] Create bucket and enable ELB access log shipping for CF API and router

---

terraform/cloudfoundry/elb_access_log_bucket.tf
terraform/globals.tf

From comment in [#125830841 Enable ELB Logs](https://www.pivotaltracker.com/n/projects/1275640/stories/125830841/comments/146017503)
What
----
> We've hit a conflict for the bucket name in production. The bucket name prod-elb-access-log has already been taken. We'll need to add a prefix, or some up with another way of avoiding this.
S3 bucket names are global and shared across all AWS users. This can cause trouble, as the name for some buckets might have been already used by other users. This was the case for `prod-elb-access-log`.
To avoid this, we add a prefix to the ELB access log bucket to "ensure" uniqueness and avoid collision with other 3rd parties names.
We create a variable `assets_prefix` to be used in any other place.
How to review
--------------
Apply this change. The new …

[#125830841] Add prefix for ELB access log bucket

---

platform-tests/run_tests.sh
platform-tests/src/acceptance/run_tests.sh
platform-tests/src/performance/run_tests.sh

The availability tests have vendored dependenvies, so there's no need to
run `godep restore`. Not doing this will reduce the startup time for
this suite.
`godep restore` was previously run in the global `run_tests.sh` script.
This moves it into the run scripts for the individual suites that need it.
Run the pipeline, and verify that all the tests start successfully.

Avoid unnecessary godep restore in platform-tests

---

Gemfile.lock
manifests/bosh-manifest/deployments/010-bosh-template.yml
manifests/bosh-manifest/deployments/aws/090-bosh-aws-stub.yml
manifests/bosh-manifest/spec/properties_spec.rb
platform-tests/bosh-template-renderer/render_lib.rb

What
===
We are not sure if we want to use the features covered by Bosh Resurrector. Meanwhile we do [Spike to determine if we want to use it](https://www.pivotaltracker.com/n/projects/1275640/stories/119516757), we will disable the feature.
But the feature was broken because an incorrect password, so we will fix it before disable it.
How to test?
-------
You can check that the new manifest will disable the resurrector because the property `director.hm.resurrector_enabled` is set to `true`:
```
aws s3 cp s3://hector-state/bosh-manifest.yml /tmp
./platform-tests/bosh-template-renderer/render.rb ~/workspace/bosh/release/jobs/health_monitor/templates/health_monitor.yml.erb ~/workspace/bosh/release/jobs/health_monitor/spec /tmp/bosh-manifest.yml bosh | json_pp
``` 
Change the value to see the …

[#121566765] Fix and disable bosh resurrector

---

manifests/concourse-manifest/concourse-base.yml

https://www.pivotaltracker.com/story/show/128217001
What
----
We were using c4.large: 2x CPU, 3.5GB, ~$0.105 per Hour.
But we are having trouble with concourse consuming too much memory
and eventually collapses.
m4.large 2x CPU and 8GB is $0.12 per Hour, so it is a worth it to
upgrade.
How to review
----------
Deploy concourse as described in readme. Check VM type.
Who?
----

[#128217001] Scale up the instance type of concourse

---

Makefile
README.md

We have a length restriction and a restriction on characters
used in the DEPLOY_ENV variable, because we use this
variable to construct values used in AWS which themselves
have those restrictions.
To be more humane, we detect these cases and apologise to the
user with the unlucky name :/
We also remove the mention in the readme - it's better for
the makefile to be self-documenting since then we don't get out
of sync with the docs.
Run `make check-env-vars` and play with your `DEPLOY_ENV`
var length and character composition,
It would be good to get this reviewed by someone with a non-bash shell.
Anyone except @benhyland or @paroxp

[#128084861] Add a max length check for DEPLOY_ENV to the makefile

---

manifests/concourse-manifest/concourse-base.yml

https://www.pivotaltracker.com/story/show/128217001
What?
===
The new stemcell with kernel 4.4 will bring several performance improvements,  specially in the btrfs driver.
In the concourse channel the recommend upgrade, and they claim that they were running it for a while without issues.
Note that this image had issues with garden-linux, but not with garden-runc
How to review?
-----------
Deploy concourse. SSH and check the kernel version
Who?
---
anyone but @keymon

[#128217001] Upgrade to stemcell 3262.5 with kernel 4.4

---

terraform/cloudfoundry/cf_api_elb.tf

[#128311015 Change healthcheck of UAA elb to HTTP  /healthz](https://www.pivotaltracker.com/story/show/128311015)
What
====
UAA ELB is configured as a HTTPS-HTTPS ELB, but the healthcheck is simply checking the TCP port 8080. Using TCP is not really checking the service and the healthcheck access is not being logged by the UAA service. We were having some issues in the ELB with instances being mark as unhealthy, but there are no logs of the healthchecks.
UAA provides an endpoint `/healthz`[1], that is being used by monit[2][3] and which we can use from the ELB.
Note that although monit uses 8989, that is only accessible locally, to access from the ELB we must use the public port 8080.
[1] https://github.com/cloudfoundry/uaa/blob/616e8bcc58f9bc16f9d9ec806da1b0bf0f5dae85/server/src/main/java …

[#128311015] Use HTTP healthcheck for UAA ELB

---

concourse/pipelines/create-bosh-cloudfoundry.yml

Currently we're `cat`ing the bosh manifest to STDOUT during the pipeline, which means we're accidentally logging all the credentials in the concourse logs. Which is bad.
This removes the :crying_cat_face:
After this is deployed we need to rotate all bosh credentials.
Run the pipeline, observe that you no longer have a bosh manifest scrolling up your screen during the `render-bosh-manifest` task.
Anyone but @jonty.

[#127339659] Stop `cat`ing bosh manifest in pipeline

---

manifests/cf-manifest/grafana/vm-resource-usage.json

The title and axis label of the SPU graph still referred to jiffies and time. 
In d64ddcf and d135733 we switched to storing rates of jiffies and displaying
in grafana as the sum of the percentage use across all cores. For example, on
a 2 core machine the usage will be between 0 and 200%.
This commit tries to make this clear in the VM resource usage dashboard CPU
graph.
- Either apply this to a dev environment OR take a copy of `manifests/cf-manifest/grafana/vm-resource-usage.json`, change the title and upload it to a grafana using the UI. 
- Check that the new title and axes label make sense
- Delete any temporary dashboard you created

[#127161593] Retitle CPU graphs

---

concourse/scripts/pipecleaner.py

[#126965751 Test users not removed from CC DB.](https://www.pivotaltracker.com/story/show/126965751)
What?
-----
Currently the script to lint concourse pipelines, pipecleaner.py, uses a color code to report the warnings (yellow) or errors (red).
This is not so intuitive, and also in the [travis output there are no colors, making it difficult to identify the root cause of the failure.](https://travis-ci.org/alphagov/paas-cf/builds/152994177#L751)
We add a text "WARNING" or "ERROR" in each case, keeping the colors, to make it more explicit.
How to test it?
-------------
Run `make dev lint_concourse DEPLOY_ENV=hector`. You can add an error in the pipelines to see the ERROR message
Who?
---
Anyone but @richardc or @keymon

[#126965751] Make errors from pipecleaner more explicit

---

manifests/shared/lib/secret_generator.rb
manifests/shared/spec/secret_generator_spec.rb

This allows the secret generator to handle two cases we ran into while attempting to rotate passwords as part of [#146888305](https://www.pivotaltracker.com/n/projects/1275640/stories/127339659/comments/146888305):
1) Secrets that have a key but no value are not generated, so the following will result in no new secrets being generated:
````
---
secrets:
preserved_secret: yay
will_not_be_generated:
````
2) A yaml file with a `secrets:` key but no values defined in it will result in the SecretGenerator crashing as it expects a Hash:
````
---
secrets:
````
In `manifests/shared` run `rspec` and observe the tests passing.
Not @jonty.

[#146888305] Generate secrets when they are missing

---

concourse/scripts/tag_release_test.go

What?
-----
Similar to #388
This script sometimes takes more than Eventually's default timeout of 1sec to return when running in travis. Probably git operations are too heavy for the container based travis build.
This happened in travis several times[1]. Dan was able to reproduce it by running `ginkgo --untilItFails`, but I couldn't.
I set the timeout to 3 as I don't mind wait one second extra in the rare case it timeouts and it is a nice number.
The failure looked like this:
```
• Failure in Spec Setup (BeforeEach) [2.847 seconds]
TagRelease
/home/travis/build/alphagov/paas-cf/concourse/scripts/tag_release_test.go:147
when there are multiple 'previous-*' tags to be promoted
/home/travis/build/alphagov/paas-cf/concourse/scripts/tag_release_test.go:146
and the before last tag of …
```

[#127449817] Increase timeout for tag_release tests

---

manifests/cf-manifest/cloud-config/025-cf-disk-types.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/030-logsearch.yml
manifests/cf-manifest/spec/integration/integration_spec.rb

[#121604537 - Move EBS volumes to SSD storage where appropriate](https://www.pivotaltracker.com/n/projects/1275640)
We want the etcd and consul VMs to use gp2 solid state drives, instead of the standard drives, to achieve [greater I/O performance](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-io-characteristics.html) and to be more consistent with the other VMs in our deployment. 
Create disk type definitions and reference them in the jobs. This will cause Bosh to migrate the persistent disks to gp2.
* Deploy from master
* Deploy from this branch and ensure all tests pass (particularly availability tests).
* If you want to be really thorough you could check in the AWS console that all persistent disks have been added.
Anyone but me.

[#121604537] Move EBS volumes to SSD

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/tasks/delete_admin.yml

[#126965751](https://www.pivotaltracker.com/n/projects/1275640/stories/126965751) Test users not removed from CC DB
This series reworks the existing delete_admin task to be implemented in terms of `cf remove-user` rather than `uaac remove user` to prevent test admin users leaking, and then adds and additional task to the `cf-deploy` job to cleanup existing leaked users.
Before deployment log into a developement environment with the `cf` tool and capture existing users with `cf curl /v2/users?results-per-page=1000 > users.json` (you may need to specify a larger value for results-per-page if this pages)
Deploy and run the pipeline.  After running repeat the `cf curl /v2/users?results-per-page=1000 > new_users.json`
Confirm that there are fewer/no users with a null username.
```
cat …
```

126965751 Test users not removed from CC DB

---

manifests/bosh-manifest/scripts/generate-bosh-secrets.rb
manifests/cf-manifest/scripts/generate-cf-secrets.rb
manifests/concourse-manifest/scripts/generate-concourse-secrets.rb

In the secret generates, we should have each secret definition on a line by itself to make it easier to read. The rubocop autocorrect went a bit OTT on these (in e24e653), which made
them a little harder to read.
Review the changes and marvel at the magnificence of the new version.

Re-tidy secret-generators after lint auto-correct

---

scripts/common.sh
scripts/create-user.sh
scripts/rotate-user-password.sh

[#128762469](https://www.pivotaltracker.com/n/projects/1275640/stories/128762469)
We want an automated, repeatable, and standardised way of rotating a Cloud Foundry user's password and emailing it to them when they are unable to log in.
Common functions have been taken from the `create-user.sh` script, so they have been split into a separate file.
Run the script without arguments to see its documentation.
There may be an advantage of testing this with a non-Mac user. In theory this should be tested in all environments, but production is the only likely place this script will need to be used.
* Choose an email address you have access to, it will be used for a test user.
* For the dev environment you will need to run `aws ses verify-email-identity --email-address` and pass the email address …

[#128762469] Automate the rotation of a user's password

---

concourse/pipelines/create-bosh-cloudfoundry.yml

Improves startup time of continuous smoke tests. Requested in the paas-improvements spreadsheet, implemented during support.
Run the pipeline and observe it completes.
Someone other than @jonty.

Aggregate the gets in continuous smoke tests

---

platform-tests/src/acceptance/rds_broker_test.go

While RDS instances take <10mins to create once the creation starts, we're seeing the creation itself not start for quite some time after it's requested. This is leading to the the tests failing and orphaned RDS instances being left behind.
Doubling the creation time should hopefully avoid this problem, but we should also query this with AWS themselves as we're frequently seeing extended creation times.
Run the pipeline, observe the custom acceptance tests passing.
Not me, guv.

[#128492081] Increase the RDS creation timeout

---

concourse/pipelines/create-deployer.yml
manifests/concourse-manifest/concourse-base.yml
manifests/concourse-manifest/spec/fixtures/concourse-terraform-outputs.yml
manifests/concourse-manifest/spec/fixtures/vpc-terraform-outputs.yml
terraform/concourse/outputs.tf
terraform/concourse/ssh-key-pair.tf

[Rotate credentials](https://www.pivotaltracker.com/n/projects/1275640/stories/128160309)
Generate and use a separate, concourse only ssh key for deployer concourse. This improves security and our ability to rotate credentials specific only to concourse, instead of having to rotate shared SSH key, which in practice means additional re-deployment of bosh and every VM deployed by it.
Run bootstrap concourse pipeline. Observe new key being generated, uploaded and concourse being re-deployed using this key. In AWS you can check the keypair name for rebuilt concourse instance. Try ssh-ing to concourse using new key.
As a part of the rotate credentials story we also want to change concourse ATC passwords. These also require re-deployment of concourse. It is possible to do this change together …

[#128160309] Concourse only ssh key

---

manifests/shared/spec/secret_generator_spec.rb

Change the test description to make it clearer that existing passwords which
are no longer "requested" will be removed from the output. This is based on
a discussion with Alex when reviewing #442, where I asked if we needed to do
this manually and he pointed out that the code already does it.
1. Confirm that the change and commit message makes sense.
1. Confirm that Travis build passes.
Not @dcarley

secret_generator: s/ignores/removes/ in test desc

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/bosh-manifest/deployments/015-cloud_provider.yml
manifests/bosh-manifest/deployments/aws/030-bosh-rds.yml
manifests/bosh-manifest/deployments/aws/090-bosh-aws-stub.yml
manifests/bosh-manifest/spec/fixtures/bosh-terraform-outputs.yml
manifests/bosh-manifest/spec/fixtures/vpc-terraform-outputs.yml
terraform/bosh/outputs.tf
terraform/bosh/ssh-key-pair.tf

[Rotate credentials](https://www.pivotaltracker.com/n/projects/1275640/stories/128160309)
Run `create-bosh-cloudfoundry` pipeline. Observe new key being generated, uploaded to AWS by terraform and applied on BOSH server (which due to how bosh-init works will cause re-deployment). After deploying, you can check in AWS what key is BOSH using & compare that to key used by bosh deployed VMs.
Compared to https://github.com/alphagov/paas-cf/pull/437 , I have used (a different) mechanism of setting and getting the keys which is used in `create-bosh-cloudfoundry` pipeline, with a slight modification:
* use s3init to initialize empty files (so that we can `get` something instead of being blocked)
* use s3iam resource to `get` and `put` keys
* (new) only `put` keys when new ones are generated. This …

[#128160309] Bosh only ssh key

---

concourse/pipelines/create-bosh-cloudfoundry.yml

This reverts commit c39578ee7261336fb0f5b30c59af46bcf4e8b7fd.
The script is no longer needed now that: it has run in all persistent
environments (including production) and we have changed the tests in 7b63a98
to no longer leave these users behind.
Furthermore we had some concerns about the safety of running this long term,
as it is deleting users and we don't have any tests around it.
1. Deploy the pipelines from this branch.
1. Run the `cf-deploy` job (you can speed it up with `make run JOB=cf-deploy`).
1. Confirm that there isn't a `purge-unnamed-users` task within that job.
Not @dcarley

[#128845965] Revert "Cleanup users with no username"

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/create-deployer.yml
manifests/bosh-manifest/spec/fixtures/bosh-terraform-outputs.yml
manifests/bosh-manifest/spec/fixtures/vpc-terraform-outputs.yml
manifests/bosh-manifest/spec/support/manifest_helpers.rb
terraform/bosh/outputs.tf
terraform/bosh/ssh-key-pairs.tf
terraform/vpc/outputs.tf
terraform/vpc/ssh-key-pair.tf

Because we have now separate keys for concourse (#437) and BOSH (#441) we can move "deployment ssh key" generation to create-bosh-cf pipeline.
This is the key that BOSH uses for all the VMs it deploys. The key has thus be already available for BOSH creation, therefore we move it from VPC terraform (and outputs) to BOSH terraform. We generate it at the same time we generate other deployment credentials.
Advantage of having this key generated in `create-bosh-cloudfoundry` pipeline is that you don't have to start deployer concourse in order to generate new keys. Also, this key is not used by concourse any more (#437), meaning we don't have to handle it during the bootstrap already.
Run bootstrap pipeline first. Observe key being removed from AWS, as it is removed from VPC terraform. Then run …

[#128160309] Generate deployment key in deployer concourse

---

concourse/pipelines/destroy-microbosh.yml

After separating SSH keys for Concourse and bosh:
https://github.com/alphagov/paas-cf/pull/441
https://github.com/alphagov/paas-cf/pull/437
destroy pipeline is missing those keys during terraform destroy phase.
Run destroy pipeline and check if it works.
Not @combor

[#128160309] Fix missing ssh key input for terraform-destroy

---

Makefile
README.md

#437 changed the deployer concourse to use its own ssh key. We
therefore need to update the Makefile to filter by the correct key name,
and update the instructions to fetch the correct key from S3, otherwise
access won't work.
Verify that you can ssh to the deployer-concourse using the updated instructions/Makefile.

[#128160309] Fix SSH to deployer concourse.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/cf_push_on_git_change.sh

Deploying the nozzle on every run means we lose some stats from the firehose while deployments are in progress.
This deploys the graphite-nozzle with the current nozzle git shorthash in the name. If the current version is missing from the cf deployment it is pushed, and all older versions are removed.
Carried out as a support task, taken from the PaaS Improvements doc.
Run the pipeline. The graphite-nozzle app should not be pushed or restarted.
Not @jonty.

Only deploy the graphite nozzle if missing/changed

---

concourse/pipelines/create-bosh-cloudfoundry.yml

Without bootstrapping the ssh-key and ssh-key.pub, pipeline won't progress beyond init job, as next job needs to get these keys via S3 resource, which blocks until there are keys in the bucket...
Should have been part of #443. 
delete your deployment keys by e.g. deleting your deployment, or by hand from s3 bucket. Run pipeline from start and observe they keys being initialized in the init job.
not @mtekel

[#128160309] Init deployments ssh-keys

---

concourse/pipelines/destroy-microbosh.yml

Simplify #450 : For destroy, TF doesn't really need the actual key to be present, as it never checks its contents against AWS. It is enough that empty file is present. This is similar to what we do in destroy-deployer pipeline (#455).
Run destroy microbosh pipeline. Check that TF completes successfully.
not @mtekel

[#128160309] Simplify key presence requirement for bosh destroy

---

concourse/pipelines/destroy-deployer.yml

Almost like in https://github.com/alphagov/paas-cf/pull/450, unblock TF destroy. It is good enough to touch the file, as TF is not checking contents against what's in AWS before destroying.
Run destroy-deployer pipeline in your bootstrap concourse. Check that `destroy-contourse` job succeeds.
not @mtekel

[#128160309] Concourse-destroy: touch concourse ssh key

---

manifests/cf-manifest/cloud-config/020-cf-vm-types.yml

We're currently using `m3.medium` for both "small" and "medium" VM types. Reducing the "small" VM's to being `t2.small` saves 62% of the cost per VM.
Carried out during support, task taken from the PaaS Improvements doc.
* Deploy in an environment
* Observe all the m3.medium's being replaced with t2.small instances
* Check the platform still functions
Not @jonty.

Make the "small" VM type actually use t2.small

---

manifests/cf-manifest/cloud-config/040-graphite.yml

Reduce graphite instance ephemeral disk and instance size. There's only 0,5G usage on ephemeral disk, reduce from 64G to 10. The instance is using about 7% cpu, reduce from m3.large to t2.medium. 
Deploy. Observe graphite being updated. Update preserves all the metrics, but creates about 3 minute gap (which is how long the update takes).
not @mtekel

Adjust graphite instance

---

doc/pingdom.md
terraform/providers/.terraformrc
terraform/scripts/set-up-pingdom.sh

The `.terraformrc` config file was overlooked in a previous PR
(https://github.com/alphagov/paas-cf/pull/448), and doesn't currently point
to the correct location to find the provider plugin binary.
Happily, terraform finds the binary anyway since it has been placed
in what will be terraform's working directory earlier in the script.
For the plugin discovery logic see https://github.com/hashicorp/terraform/blob/10cc8b8c63f0e780c022c2e9b25e954bf7a7bca8/config.go#L80
We remove the file, and adjust the script and readme so they no longer refer to it.
The part of the review advice related to Pingdom in https://github.com/alphagov/paas-cf/pull/448
should still work.
Probably best for @alext or @saliceti to take a look, but in the end anyone but @benhyland.

Remove `.terraformrc` config file

---

manifests/bosh-manifest/deployments/010-bosh-template.yml
manifests/bosh-manifest/deployments/015-cloud_provider.yml
manifests/bosh-manifest/deployments/020-compiled-package-cache.yml
manifests/bosh-manifest/deployments/aws/000-bosh-infrastructure.yml
manifests/bosh-manifest/deployments/aws/010-bosh-aws-cpi.yml
manifests/bosh-manifest/deployments/aws/030-bosh-rds.yml
manifests/bosh-manifest/deployments/aws/090-bosh-aws-stub.yml
manifests/bosh-manifest/spec/properties_spec.rb

Over time we have accumulated various leftover properties. Many of them are not used any more. Others are set to default values for no specific reasons. This can create confusion when debugging problems and looking at those properties assuming they are significant. I have created a lot of smaller commits to explain why we can remove each given property. 
Also, this is a prequel to [Single file for BOSH manifest](https://www.pivotaltracker.com/n/projects/1275640/stories/128858813)
Completely delete your CF deployment. Do `bosh cleanup --all` repeatedly until everything (packages, jobs, stemcells) have been cleaned up. Do a fresh deployment of CF (run the deploy-bosh-cf pipeline). Observe BOSH server being re-deployed and CF deployment and tests succeeding.
not @mtekel

Cleanup bosh properties

---

Makefile

In 88f7e59 the maximum length of the DEPLOY_ENV variable was declared
as being 15 characters, however the derived name of the
aws_elb.logsearch_es-master enforces a hard limit of 32 characters,
leading to an error when terraforming the environment.
~~~
* aws_elb.logsearch_es_master: "name" cannot be longer than 32 characters: "richardc-sept-logsearch-es-master"
~~~
Working backwards from this limit, this actually leaves us 12
characters to work with when naming our development environments, assuming this is the longest derived substring.
~~~
irb(main):001:0> "richardc-sept-logsearch-es-master".size
=> 33
irb(main):002:0> "richardc-sept".size
=> 13
~~~
Checkout this branch, ensure we get an error at 13 characters supplied for DEPLOY_ENV
~~~
$ DEPLOY_ENV=1234567890123 make dev showenv > …

Reduce maximum DEPLOY_ENV string length

---

scripts/create-user.sh

When using the cf CLI to create an org or space, it automatically
assigns the user making the request roles in the created org/space.
In our use-case, we don't want this, so this PR adds steps to remove
these roles immediately after they've been created.
Note: only tangentially related to the above story, but this saves having to do it manually each time.
* Comment out the last line of the script (`send_email`).
* `cf login` to your dev environment.
* Run the script to create a new org and user.
* Verify that your admin user does not have any roles in the new org and space.

[#129441797] Fix role assignments in create_user.sh

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/manifest/040-graphite.yml

[#118275583 Upgrade to CF v240](https://www.pivotaltracker.com/story/show/118275583)
What
====
We want to upgrade to CF v240 as part of our regular upgrades.
We chose v240 because:
* It has > 3 weeks
* v241 seems to new and has more changes
Additionally, we have decided to upgrade to Diego 0.1482.0 instead of the  suggested version from CF v240, 0.1481.0. The reason is that 0.1482.0 includes a [required patch for rep](https://github.com/alphagov/paas-cf/pull/395), and using this release will prevent us from using a custom release to use a patched version of rep.
Finally we upgrade the stemcell to the lates version 3262.9 to benefit from bugfixes and fixed CVEs.
See more notes about all the changes included in this PR in a comment below.
Changes that affect tenants …

[#118275583] Upgrade to CF v240

---

doc/pingdom.md
terraform/scripts/set-up-pingdom.sh

We updated our fork and released new binaries.
Update the pingdom setup script to use the new release, and improve
the docs that describe the build and release process for the fork.
For some healthy CF deploy, follow the instructions in `pingdom.md` to set up pingdom checks.
Note the the healthcheck app is deployed in `post-deploy` not `deploy-cf`.
Confirm the check appears as expected, e.g. in the webui https://my.pingdom.com - credentials are in `paas-pass`.
Remove the new checks when you are finished.
Check that the documentation changes make sense.
Anyone but @benhyland

[#127464417] Use latest release of paas-terraform-provider-pingdom

---

Makefile

On OSX, the embedded `echo -n $(DEPLOY_ENV)` actually echoes "-n FOO\n"
expanding the character count of the counted thing by 3 bytes.
This makefile seems to reproduce some of the oddness:
~~~
$ cat foo.mk
FOO="foo"
WEIRD=$(shell echo -- $$(echo -n $(FOO)))
all:
@echo $(WEIRD)
$ make -f foo.mk
-- -n foo
~~~
Here we bypass the weirdness by using printf instead of echo, which
seems more portable.
On OSX and more interestingly linux
`make dev showenv DEPLOY_ENV=123456789`
This should no longer error.
Not @richardc   Ideally a linux-haver

Fix DEPLOY_ENV checking on OSX

---

concourse/scripts/pipecleaner.py

Try blocks are currently being skipped over as pipecleaner doesn't know to flatten them, leading to erroneous warnings when fetches are performed in them.
Run `make lint_concourse` in `master`, observe the warnings being the following:
````
$ make lint_concourse
cd .. && python paas-cf/concourse/scripts/pipecleaner.py paas-cf/concourse/pipelines/*.yml
==  paas-cf/concourse/pipelines/create-bosh-cloudfoundry.yml  ==
WARNING * Unused Output: job='generate-secrets', resource='generated-ssh-private-key'
WARNING * Unused Output: job='generate-secrets', resource='generated-ssh-public-key'
WARNING * Unused Output: job='generate-secrets', resource='generated-bosh-ssh-public-key'
WARNING * Unused Output: job='generate-secrets', resource='generated-bosh-ssh-private-key'
WARNING * Unused Output: …
```

Flatten try blocks when linting manifests

---

scripts/lib/uaa_sync_admin_users.rb

Story: [Fix the build: User not found in sync-admin-users](https://www.pivotaltracker.com/story/show/130089419)
This should fix the cause of [this build failure](https://deployer.staging.cloudpipeline.digital/pipelines/create-bosh-cloudfoundry/jobs/cf-deploy/builds/220). The script gets a list of users and determine which ones it should remove. When it tries to remove the user, it may have already been deleted by another process. In the case above, the user was created and deleted by [this continuous smoke test](https://deployer.staging.cloudpipeline.digital/pipelines/create-bosh-cloudfoundry/jobs/continuous-smoke-tests/builds/41032). As the code raised an exception, this would break the build.
It is safe to ignore as we would have deleted the user anyway. Now we only log a message and …

[#130089419] Work around race condition in sync_admin_users

---

Makefile
terraform/scripts/ensure_terraform_version.sh
terraform/scripts/set-up-pingdom.sh

This updates the pingdom terraform job to use terraform 0.7.3. This means that all our terraform jobs will use the same version, which will avoid confusion.
Export CI AWS key variables.
With an old terraform installed, run `make ci pingdom ACTION=plan`, and verify you get a hepful message indicating that your terraform is too old.
Install terraform 0.7.3
Run `make ci pingdom ACTION=plan`, and verify that there are no changes.
After merging, run with `ACTION=apply` against ci, staging and prod to update the state files to the new format.

[#130003999] Update Pingdom terraform to use 0.7.3

---

concourse/scripts/fly_sync_and_login.sh

Story: [Fly login user (operator) experience](https://www.pivotaltracker.com/story/show/130284275)
Currently curl prints download details, even when there is no download:
```
Downloading fly command...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```
This replaces them by a progress bar when there is a download, and an
empty line when there is no download.
* Delete bin/fly
* Run `make dev bosh-cli`. It show show the progress bar
* Run `make dev bosh-cli`. It show show an empty line

[#130284275] Remove curl download details in fly login

---

concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/destroy-microbosh.yml
concourse/pipelines/failure-testing.yml

🚨 **DO NOT MERGE:**
Concourse 2.1.0 has included our pull request to add GPG signature verification into the git resource, therefore we no longer need to use our fork.
Remove the custom resource type from the pipelines used by the deployer Concourse. As stated in the commit message, we will have to keep using the fork in our bootstrap Concourse as the version is fixed in the AMI.
* Create a test branch off of this branch
* Remove `SKIP_COMMIT_VERIFICATION=true` from the dev section of the Makefile (line 89)
* Run the pipeline against a signed commit:
* It can be any signed commit, doesn't have to be a merge commit: `git commit -S -m 'foo'`
* Check the `paas-cf` resource is fetched `in` successfully. You only need to run the pipeline-lock job at the start.
* Run the pipeline against an …

[#129847885] Use native git resource instead of our fork

---

Makefile
concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/failure-testing.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/tasks/terraform_destroy_datadog.yml
manifests/bosh-manifest/deployments/010-bosh-template.yml
manifests/bosh-manifest/deployments/030-trusted_certs.yml
manifests/bosh-manifest/deployments/040-collectd.yml
manifests/bosh-manifest/deployments/050-datadog.yml
manifests/bosh-manifest/spec/properties_spec.rb
manifests/bosh-manifest/spec/shared_config_spec.rb
manifests/bosh-manifest/spec/support/manifest_helpers.rb
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/030-logsearch.yml
manifests/cf-manifest/manifest/040-graphite.yml
manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/cf-manifest/runtime-config/runtime-config-base.yml
manifests/cf-manifest/spec/manifest/jobs_spec.rb
manifests/cf-manifest/spec/support/manifest_helpers.rb
manifests/shared/deployments/datadog.yml
terraform/cloudfoundry/datadog.tf
terraform/datadog/datadog.tf

Story: https://www.pivotaltracker.com/story/show/128932735
This PR brings initial support for Datadog agent on (almost) all out VMs.
Concourse VM has a separate story as this requires significant manifest changes.
- We add tags on on VMs so we can easily find them in Datadog UI.
- We had to disable Dogstatsd due to port conflict
- new terraform job provisions basic router alert 
Test together with https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/1
Deploy `create-bosh-cloudfoundry` pipeline from this branch with `ENABLE_DATADOG=true`
Check if tests pass and if router alert works.
Merge https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/1, put a tag on `paas-datadog-agent-boshrelease` and update https://github.com/alphagov/paas-cf/blob/749ec4f581bfdf77346d187e4357 …

[#128932735] Initial implementation of Datadog

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/040-graphite.yml

Story: https://www.pivotaltracker.com/story/show/129706079
As new release of Grafana is out and it contains our fixes:
https://github.com/vito/grafana-boshrelease/commit/1fa3e221fde4369cad33ab612b18f35766a3a28e so we can stop using our fork and fall back to official bosh.io releases.
Deploy from this branch, check if Grafana works ( displays dashboards ) and if version is 3.0.3 ( you can find thin on login screen )
not @paroxp or @combor

[#129706079] Use upstream grafana

---

concourse/pipelines/create-deployer.yml
concourse/scripts/pipelines-deployer.sh
manifests/concourse-manifest/concourse-base.yml
manifests/concourse-manifest/spec/fixtures/vpc-terraform-outputs.yml
manifests/concourse-manifest/spec/support/manifest_helpers.rb

[Add datadog to concourse](https://www.pivotaltracker.com/n/projects/1275640/stories/130186203). This is now possible thanks to https://github.com/alphagov/paas-cf/pull/482. Use same approach and shared files as in #481 
Run bootstrap pipeline. Then `make dev ssh_concourse`, sudo su and monit summary. Datadog agent should be present and running. Depending if you did `export ENABLE_DATADOG=true` before creating bootstrap pipelines (make dev bootstrap), the agent would either be "disabled" - logging 403s in the forwarder log (/var/vcap/sys/log/datadog-agent/forwarder.log) or sending metrics to our trial account in datadog, where you should be able to see a host with `concourse` tag (+aws account type + your envirnment name tags).
not @mtekel or @combor or @paroxp

[#130186203] add datadog to concourse

---

concourse/pipelines/create-bosh-cloudfoundry.yml

When we run self update pipelines in the `init` job, even though that job might get updated by itself, it will not run again. This means that if there are any new resources to bootstrap in this job, they would not get bootstrapped and the remainder of the pipeline can get stuck waiting on these forever.
Move self update to lock. Self update after you have acquired lock and before triggering remaining jobs. This way if init job gets updated it will run in its latest instance and bootstrap all the things it really needs to.
`make dev pipelines` or run pipeline and let self update pipelines that's currently in init do the update for you. Run the lock job and check that it updates pipeline after lock and before triggering the rest of the jobs.
not @mtekel

Self update pipelines before init

---

concourse/scripts/run_job.sh

The API endpoints in concourse have changed with the introduction of
teams[1]. The `fly` command has also gained a `trigger-job` command, so
let's use it. This will insulate us against future changes to the API
layout.
[1] http://concourse.ci/downloads.html#v200
Use the `run_job` make task and observe that it now works again.

[#129847885] Fix run_job make target for new concourse.

---

Makefile
concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/concourse-lite-self-terminate.yml
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/create-deployer.yml
concourse/pipelines/failure-testing.yml
concourse/scripts/pipecleaner.py
concourse/scripts/pipecleaner_test.go
concourse/scripts/spec/fixtures/pipecleaner_shellcheck.yml
concourse/scripts/spec/fixtures/pipecleaner_shellcheck_params.yml
concourse/tasks/create_admin.yml
concourse/tasks/delete_admin.yml

Here we add a new class of check to pipecleaner `shellcheck`
When enabled (and it is enabled by default) when linting we look for
tasks where the run property looks like it is an inline shell script,
and invoke `shellcheck` over it to see if the script looks valid.
When an issue is found, it will be reported like so:
==  spec/fixtures/pipecleaner_shellcheck.yml  ==
WARNING * Shellcheck: job='shellcheck', task='bad-compare', ~='
In - line 2:
if [ "red" == "blue" ]; then
^-- SC2039: In POSIX sh, == in place of = is undefined.
^-- SC2050: This expression is constant. Did you forget the $ on a variable?
'
We also add a ginkgo test for pipecleaner.py, with a test fixture of a
pipeline with an error we know shellcheck will pick up on.
There's some minor refactoring of pipecleaner here to reduce …

Add shellcheck to pipecleaner

---

manifests/cf-manifest/manifest/050-rds-broker.yml

[#124720541 Not all logs shipped to kibana/logsearch](https://www.pivotaltracker.com/story/show/124720541)
What
----
We want all the logs from RDS broker in syslog, to forward then to loggregator using metron_agent.
Version of the aws-broker-release [0.0.9 will forward all the logs to syslog](https://github.com/alphagov/paas-aws-broker-boshrelease/pull/12)
How to review
------------
Deploy this, and check that rds-broker logs the messages to syslog as in https://github.com/alphagov/paas-aws-broker-boshrelease/pull/12
Who?
---

[#124720541] Bump aws-broker-release to 0.0.9

---

.travis.yml
Makefile
README.md
concourse/scripts/lib/datadog.sh
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/scripts/pipelines-deployer.sh
doc/datadog.md
scripts/upload-datadog-secrets.sh

https://www.pivotaltracker.com/story/show/130379909
This moves Datadog API and App keys into the state bucket and adds a Makefile target for populating the state bucket from the credentials repo.
1. Deploy an environment, login to datadog, observe that nothing is showing up there.
2. Create a datadog API key and an app key, and place them in `~/.paas-pass/datadog/dev/datadog_api_key.gpg` and `~/.paas-pass/datadog/dev/datadog_app_key.gpg`
3. Run `make dev upload-datadog-secrets`, observe that these credentials have been inserted into your environment s3 state bucket as `datadog-secrets.yml`
4. Redeploy your pipelines, then redeploy the environment
5. Type your environment name into "filter" on https://app.datadoghq.com/infrastructure/map and observe that all your hosts are monitored
Not …

[#130379909] Refactor Datadog credential storage

---

concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/030-logsearch.yml
manifests/cf-manifest/manifest/800-logsearch.yml
manifests/cf-manifest/spec/manifest/base_properties_spec.rb
manifests/cf-manifest/spec/manifest/jobs_spec.rb

[Make sure ingestor vms have completely restarted before we launch other vms](https://www.pivotaltracker.com/n/projects/1275640/stories/130730169)
This PR
* Improves safety of deployment by
* Setting global update max-in-fligh to 1
* Updating diego database before other diego components
* Improves cleanness of manifests by removing custom logsearch update settings that had in practice the same effect as global settings
* Improves deployment speed by creating only one parallel deployment group
* Mostly alleviates metron agent restart failed issue (by ~90%). See story for more details.
Last point will require further PRs to fully fix.
Apply to your existing environment. Make it deploy all the CF VMs by either having your environment built from branch that e.g. has different stemcell, or no …

[#130730169] Fix vm update settings

---

concourse/pipelines/create-bosh-cloudfoundry.yml

Ruby slim container no longer has `curl` included: https://github.com/docker-library/ruby/commit/281978ef87397763e377774740d82c8d87674ae9#diff-a68c083598cb36cf70eaaead1ae18581L25. 
This breaks test-bosh-cli task.
Non-slim container still has curl.
Run the pipeline and check if `bosh-tests` job passes. 
Not @combor

[SUPPORT TASK] Use non-slim ruby container for bosh-cli test

---

concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/scripts/lib/datadog.sh
concourse/tasks/terraform_destroy_datadog.yml

We now have real datadog keys available for our environments, so we can get rid of "disabled" workaround. This PR also adds functionality to clean up datadog checks after datadog is disabled - when you run deploy pipeline again and when you run autodelete/destroy pipelines.
Upload dev datadog keys to your dev env (`make dev upload-datadog-secrets`). Deploy with datadog enabled (`DEPLOY_DATADOG_AGENT=true make dev pipelines`). Run the deploy pipeline. Then disable datadog & upload your pipeline (`make dev pipelines`). Run deploy pipeline again & verify that terraform does clean up previously created checks. Then also check in autodelete/destroy pipelines that terraform tasks there run cleanup. You can do so by e.g. running these pipelines. (hint: edit your pipelines locally, place `exit 0` …

[#130182525] Control datadog terraform

---

manifests/shared/deployments/datadog.yml

Dadatog.yml is always included in the cf-manifest. This is because we
always define tags and other datadog properties and we grab from shared
datadog.yml file. In case we don't want to enable datadog and the api
key is missing for the environment, spruce rendering would fail as
there was no value defined for the api key.
Define default for this value.
This is an unspotted leftover from #503 
Deploy in dev environment where you have no keys in the bucket. Run generate-cf-config job. It should succeed.
not @mtekel

[#130182525] Define default value for datadog api key

---

manifests/cf-manifest/grafana/vm-resource-usage.json

Making the fill colour much stronger makes it much easier to see which
section of the stack correlated to which metric.
Before: 
After:
Deploy these dashboards, and be amazed at the improvement.

Improve display of stacked graphs on VM dashboard.

---

manifests/concourse-manifest/concourse-base.yml

This release fixes the problem with disk space that we had a lot of
trouble with:
> "BOSH-deployed workers will now be named after a frankenguid taking
parts from the BOSH instance ID and their hostname. This is to make it
so you can correlate the worker to the BOSH instance, while also
guaranteeing that when the worker is recreated it comes back under a new
name."
As we use bosh-init to deploy Concourse the name was always "unknown".
> "the issue is that it comes back with the same name every time
to concourse, a worker coming back with the same name means all the
volumes that were previously on it should still be there
so it probably gets confused when it sees the imported volume for it in
the db and then it's not there"
Release notes promises big improvements to resources candidate …

[SUPPORT TASK] Concourse 2.2.1 upgrade

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/common/metron.yml
manifests/cf-manifest/common/releases.yml
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/manifest/040-graphite.yml
manifests/cf-manifest/runtime-config/runtime-config-base.yml
manifests/cf-manifest/spec/runtime-config/metron_agent_as_addon_spec.rb
manifests/cf-manifest/spec/runtime-config/shared_config_spec.rb
manifests/cf-manifest/spec/support/manifest_helpers.rb

[#124720541 Not all logs shipped to kibana/logsearch](https://www.pivotaltracker.com/story/show/124720541)
What
===
We want to get all the logs from all the machines in loggregator. Metron agent configures syslog to forward all the local logs, so we decided to install it in all the VMs.
To do so, we will add it as an addon.
To configure it as a addon, we had to refactor the manifest:
* We need to pass the terraform outputs to the runtime-config.yml  generation, so we can pass the environment config.
* We need to move some common config, like dropsonde_incoming_port to  a `common/metron.yml` file
* We need to move the definition of the cf release to  `common/releases.yml`
How to test?
===========
Travis should pass.
Deploy, it should pass the tests.
Verify that metron agent is running on …

[#124720541] Configure metron_agent as a runtime-config addon

---

Makefile
manifests/cf-manifest/cloud-config/010-cf-networks.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/env-specific/cf-prod.yml
manifests/shared/spec/fixtures/terraform/terraform-outputs.yml
scripts/show-cf-memory-usage.rb
terraform/cloudfoundry/outputs.tf

https://www.pivotaltracker.com/story/show/130921001
Currently if we lose a zone we won't have enough capacity to support all deployed instances of apps on the platform. This adds two more cells in zone 3, thus meeting our requirement of being able to support all currently deployed apps on zone failure and lessening our reliance on z1 & z2.
This also adds a new makefile target that invokes @saliceti's script to show current cluster memory usage.
* Edit `paas-cf/manifests/cf-manifest/manifest/env-specific/cf-default.yml` and increase the number of instances to 6 so that your development environment matches the new production configuration.
* Temporarily commit and deploy this to an environment.
* Log in to the AWS console and verify that your environment now has 6 cells spread across three …

[#130921001] Add two new cells in zone 3, for a total of 6.

---

terraform/cloudfoundry/router_elb.tf
terraform/cloudfoundry/security-groups-pingdom.tf

This is temporary fix to allow provisioning of more security groups to
allow more than 96 pingdom IPs ( 32 per group ) to access our
infrastructure. Right now pingdom reports 108 IPs  and some of them (for instance Amsterdam and Düsseldorf ) can't access `/db` on healthcheck app failing the check. 
Run the pipeline and check if `cf-terraform` created `aws_security_group.pingdom-probes-3`
Not @combor

[SUPPORT] Fix CI healthcheck DB problem.

---

concourse/tasks/remove-healthcheck-db.yml

If the API is up, it's still possible that you may not be able to login,
say if UAA is down.
Here we allow the `cf login` to fail also.
Turn off UAA then delete a deployment.
Not @richardc

Allow login to fail during `remove-healthcheck-db`

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml

This PR brings fix for [CVE-2016-6651 Privilege Escalation in UAA](https://pivotal.io/security/cve-2016-6651). It updates UAA to the latest version from 3.4.X branch that has the fix.
https://github.com/cloudfoundry/uaa/releases/tag/3.4.5
Run the pipeline from this branch and check if all tests are passing.
Run
```
cf login -a https://api.$DEPLOY_ENV.dev.cloudpipeline.digital --skip-ssl-validation
cf create-user test test
```
Now you can test if vulnerability is fixed:
```
curl -k -H 'Accept:application/json' -H 'Authorization:Basic Y2Y6' \
-H 'Content-Type:application/x-www-form-urlencoded' \
-X POST "https://login.$DEPLOY_ENV.dev.cloudpipeline.digital/oauth/token" \
--data-binary "grant_type=password&password=test&scope=&username=test&external_scopes=cloud_controller.detect_vuln" \
| …
```

[SECURITY FIX] CVE-2016-6651 uaa update

---

manifests/concourse-manifest/concourse-base.yml
manifests/concourse-manifest/extensions/datadog.yml
terraform/datadog/concourse-jobs.tf

Send concourse metrics to datadog and create a simple graph that shows time difference in job runtime for each job.
Upload datadog secrets to your dev environmnent if you haven't done so already (`make dev upload-datadog-secrets`) then `DEPLOY_DATADOG_AGENT=true make dev bootstrap`, apply bootstrap pipeline.
Run pipeline on your concourse several time (this is to get some metrics). Log in to datadog. You should see metrics starting with `<env_name>_concourse.`. Created graph (" <env> job runtime difference") should show differences in run times of your jobs.
not @mtekel or @saliceti

[#130814387] Metrics for concourse

---

concourse/pipelines/create-bosh-cloudfoundry.yml
terraform/datadog/datadog.tf

Measure how long the pipeline run took. Ignore time initial lock spent waiting. Send metric to datadog & create a graph for them.
* Upload datadog credentials to your environment
```
DEPLOY_ENV=test123 make dev upload-datadog-secrets
```
* Apply to your environment with `DEPLOY_DATADOG_AGENT=true`
* Check metric being sent to datadog. Run pipeline several times (hint: you can put `exit 0` in the beginning of custom acceptance tests to skip them) and observe metric being sent on every run.
* Check the timeboard "[env] - Concourse timeboard is present in datadog and has data
not @mtekel or @saliceti

[#130814387] Measure pipeline runtime

---

manifests/cf-manifest/grafana/cell-memory-usage.json

As part of [120268263](https://www.pivotaltracker.com/n/projects/1275640/stories/120268263) we want to have visibility over how much memory is currently in use in the cell cluster, how much we have available in total, and how much we'll have after losing a cell and losing an AZ.
This PR introduces a new default grafana dashboard that shows all of these metrics.
*Note:* We currently have no way of passing the number of zones into the manifest at build time so the scale factor representing the number of zones after a failure (2) is currently [hardcoded in this template](https://github.com/alphagov/paas-cf/pull/514/files#diff-a013cd33b85234fd1ce5f574c7a8196cR30) as "0.6666" for the AZ failure graph. We need to revisit this if we introduce another zone.
Alter your …

Add cell memory usage dashboard

---

Makefile
concourse/scripts/environment.sh

This will automatically decrypt and load the Concourse ATC password from our credentials when running against production environments rather than requiring the user to manually do it.
1. `unset CONCOURSE_ATC_PASSWORD` to be sure you have a clean environment.
2. `make prod showenv`, or `make ci showenv`, or get super fancy with a `make prod bosh-cli`.
3. Observe that it just worked.
4. Run `env | grep CONCOURSE_ATC_PASSWORD` and get nothing returned.
Someone else.

Auto-decrypt Concourse ATC password in prod envs

---

concourse/scripts/environment.sh

https://github.com/alphagov/paas-cf/pull/515 accidentially broke environment.sh in dev mode, as we don't set the DECRYPT_CONCOURSE_ATC_PASSWORD variable and there was no default.
Run `make dev showenv` and it should not error.
Not @jonty, who is very sorry.

Fix dev mode, which doesn't specify this variable

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/concourse-manifest/concourse-base.yml
manifests/concourse-manifest/extensions/datadog.yml
terraform/datadog/concourse-jobs.tf
terraform/datadog/datadog.tf

Story: [Improve Visibility of Continuous Smoke Tests](https://www.pivotaltracker.com/story/show/120590777)
This has impacted me as the datadog terraform run failed for me because I have a hyphen in my environment name (`colin-sept`). We've noticed riemann actually converts hyphens to underscores automatically when it sends metrics to datadog. This does the same for our metrics, and change the queries accordingly.
* Build an environment with hyphen(s) in the name
* It should not break in `datadog-terraform-apply`
* The dashboards should work in datadog
Anyone but @paroxp or myself

[#120590777] Fix datadog hyphen bug

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/scripts/generate-cf-secrets.rb
manifests/cf-manifest/spec/support/manifest_helpers.rb
manifests/cf-manifest/stubs/datadog-nozzle.yml
manifests/shared/spec/fixtures/cf-secrets.yml

[#131355143 Add metron metrics to datadog](https://www.pivotaltracker.com/story/show/131355143)
What?
----
We want to get the metrics from the metron agents into datadog. We will use the [datadog nozzle](https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle) for this.
Deploying it in dedicated VMs for nozzles, not as apps in CF, to reduce the dependencies of the monitoring on the platform itself.
We want to make this optional, enabled by `ENABLE_DATADOG` feature.
Dependencies
-----------
The PR #519 must be merged first, and then rebase this PR.
You can test both together.
How to test
-----------
You can start testing only the job `cf-generate-config` and confirm that enable/disable the setting changes the right parts of the manifest:
```
export DEPLOY_ENV=...
make dev …
```

[#131355143] Install datadog nozzle in a dedicated VM

---

concourse/scripts/smoke_tests_email.sh

The link to the continuous smoke tests was broken when the concourse upgrade added teams.
Check that the link is now correct for a deployed concourse.
You! A friend! The person next to you! (As long as it isn't me)

Fix the concourse link in smoke test emails

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/destroy-deployer.yml
concourse/scripts/pipecleaner.py
concourse/scripts/pipecleaner_test.go
concourse/tasks/terraform_destroy_datadog.yml

This resolves all the remaining shellcheck errors that pipecleaner finds in the concourse pipelines and then makes shellcheck warnings fatal, as we aim for shellcheck zero.
This also fixes the deployer destroy pipeline which was broken when we refactored SSH key handling - the bug was spotted by shellcheck.
1. Run the pipeline and ensure the tests pass, ideally in a fresh environment.
You.

Pipeline shellcheck fixes

---

Makefile
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipecleaner.py
concourse/scripts/pipecleaner_test.go
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/tasks/smoke-tests-run.yml

Add few more fixes for issues discovered during review of #518 . Most importantly, there should be no more errors or warnings from shellcheck after this, making it much easier to spot any new issues. To enforce that, we enable `--fatal-warnings` for pipecleaner.
Make sure you have shellcheck 0.4.4.
* `make lint_concourse` should return no errors. 
* `make lint_shellcheck` should return no errors.
* bosh manifest generation in the pipeline should not be changed. You can test by temporarily removing your original bosh-ca from bucket & running pipeline again from init. Make sure generate-secrets picks the version of bosh-ca uploaded in init and not the cached one. You don't need to run your pipeline any further than this task. You can then compare generated bosh-ca tarball to the one you had …

More shellcheck fixes

---

manifests/bosh-manifest/deployments/010-bosh-template.yml
manifests/concourse-manifest/concourse-base.yml
manifests/concourse-manifest/extensions/datadog-agent.yml
terraform/datadog/concourse-jobs.tf

[#131426461 Improve concourse metrics naming](https://www.pivotaltracker.com/n/projects/1275640/stories/131426461)
What?
-----
We are using concourse riemann reporting function to get metrics from concourse, as per the PR #511.
But we want to tag the metrics from concourse with a specific tag that refers environment, and keep the same names for the metrics. 
We will extend concourse release to add additional custom tags, but as currently concourse sends the deployment name as a tag[1], we will use that. Later, if our custom tags PR is merged upstream, we can add additional tags as desired, but we won't revert this change.
Additionally, in the CF manifest we also use the environment name as deployment name[2], so this commit will add homogeneity.
The change of the deployment name does not …

[#131426461] Use meta.environment for concourse & bosh deployment name and change concourse datadog metrics prefix

---

concourse/pipelines/create-bosh-cloudfoundry.yml
terraform/datadog/concourse-jobs.tf
terraform/datadog/datadog.tf

Story: [Improve concourse metrics naming](https://www.pivotaltracker.com/story/show/131426461)
The environment name is passed as a tag as `bosh-deployment` by #525. We can add `environment` for the metrics we push so we don't need to add the environment name in the metric name and we keep consistency.
As a consequence, we don't have to remove hyphens as it is fine to have hyphens in tags. We also put the concourse graphs in the same dashboard.
#525 should be merged first
* Deploy Concourse and run the CF pipeline
* Observe the metrics and dashboards make sense
Anyone but @paroxp or @keymon or @saliceti

[#131426461] Improve concourse metrics naming

---

concourse/scripts/pipecleaner.py

We recently changed shellcheck errors to be fatal in pipecleaner, but missed the documentation. This commit fixes it.
Check that it really does say "Fatal" instead of "Warning" for shellcheck errors now.
You!

Shellcheck errors are now fatal in pipecleaner

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/shared/deployments/datadog-agent.yml

[#122200041 Gather metrics to check health of go router in datadog](https://www.pivotaltracker.com/n/projects/1275640/stories/122200041)
We want to gather metrics about gorouter to implement checks in datadog. We will use the datadog nozzle #520 and also integrations from the agent.
We in this PR add a [new version of the datadog-agent](https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/5) and the [`datadog-for-cloudfoundry/datadog-router` job to the router job templates](https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/1)
The  https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/5 and https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/1 should be merged first and updated accordingly.
It would be convenient to get …

[#122200041] gorouter component monitoring

---

manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/spec/manifest/base_properties_spec.rb

[#131355143 Add metron metrics to datadog](https://www.pivotaltracker.com/story/show/131355143)
What?
----
In #520 we accidentally added a duplicated definition of datadog-nozzle UAA client.
This PR removes the duplication, and adds some checks to config that the required clients are present in the manifest definition.
How to review?
--------------
Sanity check. Travis should pass.
Who?
----
I suggest @mtekel, but anyone.

[#131355143] Remove duplicated uaa.client for datadog nozzle

---

concourse/pipelines/create-bosh-cloudfoundry.yml

For some reason we were still deploying from upgrade_go branch.
But we have since fast forwarded gds_master to bring in updates from
upstream and also to hide credentials in log outputs, see
https://github.com/alphagov/paas-graphite-nozzle/pull/4
https://github.com/alphagov/paas-graphite-nozzle/pull/3
Deploy by running pipeline (cf-deploy job is enough). Check that nozzle is deployed from `gds_master` branch.
not @mtekel

[#131797171] Use datadog nozzle from gds_master

---

manifests/cf-manifest/manifest/020-cf-properties.yml

For some reason, these variables were present but not set. When going through spruce they get set to 'null'. This means that default value is being used for these properties. And this also means that there is no reason to include these properties in the manifest if we don't intend to set them to any value.
all cf-manifest tests should pass. When you generate manifest via spruce (both generation for tests but also for pipeline), the removed properties should not be present vs their value set to `null` previously. You can e.g. run generate-cf-config job in deploy-bosh-cloudfoundry pipeline and compare the generated manifest to previous version.
not @mtekel

Remove null router variables

---

manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/040-graphite.yml
manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/cf-manifest/manifest/800-logsearch.yml
manifests/cf-manifest/spec/manifest/jobs_spec.rb
manifests/cf-manifest/stubs/datadog-nozzle.yml

[#131635247 Metron error messages in logs](https://www.pivotaltracker.com/story/show/131635247)
What?
=====
Install consul_agent in all VMs
We have setup metron_agent in all VMs as a addon in #495.
Metron agent requires connect to etcd to discover the dopplers, and it is currently setup to discover the etcd by using `etcd.service.cf.internal` that is served by consul.
We did not setup the consul_agent in all the VMs, so the ones missing it had metron_agent installed, but unable to resolv etcd and, in consequence, discover the dopplers. Because that, the metron_agents were logging constantly the following error:
```
{
"file" : "/var/vcap/data/compile/metron_agent/loggregator/src/doppler/dopplerservice/finder.go",
"timestamp" : 1475669685.3659,
"source" : "metron",
"line" : 139,
"log_level" …
```

[#131635247] Install consul_agent in all VMs

---

manifests/cf-manifest/cloud-config/030-logsearch.yml

[#131981965 Support: troubleshoot issues in logsearch/elasticsearch cluster](https://www.pivotaltracker.com/story/show/131981965)
This PR is a result of ES troubleshooting. 
We found out that all disks are almost full on all Elasticsearch VMs and ES process refuses to assign shards to any host that reached more than 90% of disk space used. As the volume of logs increases and we do more searches and indexing we need more memory and more CPUs to cope with the load. This PR updates ES VMs to m4.large that has 8GB of memory, 2 CPUs and increases disk space to 200GB. 
- Deploy on top of existing environment. 
- check if you can still use Kibana
- check if you can access logs that were indexed before migration disks 
not @combor

[#131981965] Add more disk&memory to ES vm types

---

manifests/concourse-manifest/extensions/datadog-agent.yml

This PR updates Rieman to our custom release build on top of Rieman `master` branch.  It brings batch processing of events that is fixing Rieman problem with getting stuck after 15-30 mins of forwarding to Datadog. Also, it should improve performance and reduce latency of forwarding. 
Review changes on our fork of Rieman bosh release: https://github.com/xoebus/riemann-boshrelease/compare/master...alphagov:feature/events_batch_processing?expand=1
Rieman jar was created manually according to instructions from docs: http://riemann.io/howto.html#work-with-the-riemann-source
than on paas-cf:
```
make dev bootstrap
```
Check if `concourse.*` metrics are being send from your env. You can wait for half an hour to ensure that Rieman doesn't stop sending them.
Not @mtekel or @combor

[#131890677] Update Rieman to custom release

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/failure-testing.yml
concourse/tasks/custom-acceptance-tests-run.yml
manifests/cf-manifest/manifest/050-rds-broker.yml
platform-tests/src/acceptance/Godeps/Godeps.json
platform-tests/src/acceptance/rds_broker_test.go
platform-tests/src/acceptance/run_tests.sh

We have updated the broker to create a final snapshot of a database instance
upon its deletion. We have added custom acceptance tests to check for this creation and assert a user can override this behaviour when provisioning a database instance, and by using `cf update-service`.
We had to fix some of the configuration, as it was misplaced. We've enabled the `allow_user_provision_parameters`, allowing to pass some parameters into the command line on execution. We've created our own helper and prepared a set of tests, checking the setup while the pipeline is being run.
The review of this pull request is dependent on the merging of [pull request 13](https://github.com/alphagov/paas-aws-broker-boshrelease/pull/13) in the paas-aws-broker-boshrelease repository. Only once that pull request is …

[#127970229] Enable RDS Broker to Create Final Snapshot

---

manifests/concourse-manifest/concourse-base.yml

[#132001409 Upgrade stemcell for concourse to 3263 series](https://www.pivotaltracker.com/story/show/132001409)
What?
----
The stemcell 3263 series are based on 3262, but they use the kernel 4.4.[1]
This kernel contains multiple changes and optimisations for btrfs, which concourse relies on massively. We are experiencing some bottlenecks in the volume management in concourse, and it is recommended to use this kernel version.
The concourse development team did recommend several times upgrade to 4.4 for performance. I [confirmed it](https://concourseci.slack.com/archives/general/p1476117654007234).
[1] https://github.com/cloudfoundry/bosh/releases for latest stemcell
[2] https://www.phoronix.com/scan.php?page=news_item&px=Linux-4.4-Btrfs-Improvements
How to test?
-----------
Install the new …

[#132001409] Use stemcell 3263.5 with kernel 4.4 for concourse

---

terraform/datadog/concourse-jobs.tf

[Improve Visibility of Continuous Smoke Tests](https://www.pivotaltracker.com/n/projects/1275640/stories/120590777)
Add a graph with continuous smoke test successes and failures into concourse job runtime dashboard.
Run pipeline. Most importantly datadog terraform part which is in `cf-deploy` job. Go to datadog and observe new and strongly visible bar graph with continuous smoke tests successes and failures. If its empty then try running some continuous smoke tests. You can fail some of them to see the difference in the graph.
not @combor or @mtekel

[#120590777] Add Continuous Smoke Tests to concourse jobs dasboard

---

concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
terraform/datadog/cell.tf
terraform/datadog/datadog.tf

[Add datadog check of cell memory usage](https://www.pivotaltracker.com/n/projects/1275640/stories/131355243)
Create a monitor which check total available memory on cells. Alert if less than 50% is free.
Deploy. Check that the new monitor is correctly created. Try triggering the alert by using a lot of memory on cells. You can try running e.g. `ruby -e 'foo = "123234314234" * 2000000000; sleep' &` on a cell VM directly. Or deploy lots of apps to CF, but which have to really consume memory (it doesn't matter what quota you assign to the app, only real memory consumption is counted).
See https://github.com/alphagov/paas-team-manual/pull/68 for information about alerting google groups - you need to to subscribe to receive alerts.
not @mtekel or @richardc

[#131355243] Datadog: Add monitor for cell memory

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/git_check_tag.sh

[#132060265 Support: Wrong version of aws-broker deployed in CI](https://www.pivotaltracker.com/story/show/132060265)
What?
-----
How git-resource and concourse works, and how we implemented the build and upload of bosh-releases, it can happen that we build an older version of the bosh-release and upload it with the wrong version number.
The reason is that regardless the tag-filter configured in the git resource, the versions previously reported  still valid versions for concourse, and likely cached.
If the new version defined in the tag filter is not discovered (e.g. we forgot to add the tag or there was a typo) Concourse might checkout the latest valid version, but not the one defined in `tag-filter`.
We cannot add a safe-check in the git-resource, as the `get` might not be executed …

[#132060265] Check the git tag of the boshreleases prior upload

---

concourse/scripts/tag_release_test.go

What?
-----
Similar to #388 and #435
This script sometimes takes more than Eventually's default timeout of 1sec to
return when running in travis. Probably git operations are too heavy for
the container based travis build.
This happened in travis several times[1]. Dan was able to reproduce it
by running `ginkgo --untilItFails`, but I couldn't.
I set the timeout to 30. Even with 3 seconds it timeouts sometimes, and it is
not really important to add more time if it eventually timeouts in a reasonable
time.
The failure looked like this:
``` 
• Failure in Spec Setup (BeforeEach) [3.847 seconds]
TagRelease
/home/travis/build/alphagov/paas-cf/concourse/scripts/tag_release_test.go:147
when there are multiple 'previous-*' tags to be promoted …
```

[#127449817] Increase timeout for tag_release tests to 30s

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
terraform/datadog/nats.tf

Story: [Check health of nats component](https://www.pivotaltracker.com/story/show/131355575)
This covers the most critical:
* NATS process
* NATS stream forwarder process
* NATS server TCP port
* NATS cluster management TCP port
It depends on PR https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/3
* Deploy with `ENABLE_DATADOG=true`
* Verify the NATS monitors have been created in Datadog
* Connect to a NATS host, stop or kill NATS processes, stop datadog agent... and check the monitors are failing
* When ready, merge PR https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/3
* Create and push tag `0.0.3` on paas-datadog-for-cloudfoundry-boshrelease master
* Remove commit 7d3240807b6c4c96133c0958c7e3a7df3565ccd9 in this branch
* Commit new …

[#131355575] Check NATS health

---

manifests/bosh-manifest/extensions/datadog-agent.yml
manifests/bosh-manifest/spec/fixtures/bosh-terraform-outputs.yml
manifests/bosh-manifest/spec/properties_spec.rb
manifests/concourse-manifest/extensions/datadog-agent.yml
manifests/concourse-manifest/spec/fixtures/vpc-terraform-outputs.yml
manifests/concourse-manifest/spec/manifest_generation_spec.rb
manifests/shared/deployments/datadog-agent.yml
terraform/bosh/outputs.tf
terraform/globals.tf

[#132146447 Set human-readable hostname in Datadog](https://www.pivotaltracker.com/story/show/132146447)
What?
-----
The host names of our virtual machines are Bosh UUIDs in Datadog, which is not very user friendly and makes metrics hard to find and read.
This PR was merged upstream [1] which adds tags to identify the bosh job and index, which we can use in our checks and graphs. This PR is merged back to our fork [2].
We add these changes to the manifest.
[1] https://github.com/onemedical/datadog-agent-boshrelease/pull/8
[2] https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/7
Dependencies
-------------
https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/7 should be reviewed and merged first, a new release generated and uploaded and the commits of this PR point …

[#132146447]  Upgrade datadog agent and enable bosh tags

---

terraform/datadog/general.tf

[Monitor disk space usage](https://www.pivotaltracker.com/n/projects/1275640/stories/130899659)
Alert when any VM in the given environment uses more than 85% of disk, warn at 75% of usage. This excludes concourse which after deployment uses 90% of the stemcell root disk because bosh init places about 1GB of package cache there. Thus concourse gets own check with 97% critical and 95% warn thresholds.
We use same google groups that were created for #541 to send alerts to. We also depend on addition of aws_account TF variable in that PR. This PR might need re-basing after #541 is merged. For now, we include it in this PR so that you can review directly and that travis passes tests.
Deploy. Verify monitors are created with correct thresholds, messages and alert group emails. Try filling disk …

[#130899659] Monitor disk space

---

misc/chrome_plugins/clean_concourse_pipeline/src/inject.user.js

At present, there's some unnecessary padding at the top of the pipeline
display causing the scrollbars to appear etc.
This cleans thing up by allowing the main content block to use the full
space. As part of this, the enviuronment label has been moved to the
bottom, and floated on top to avoid it conflicting with the actual
pipeline elements - there's generally more room at the bottom of the
screen due to how the pipelines are layed out.
* Add the plugin to your browser as described in the [README](../blob/master/misc/chrome_plugins/clean_concourse_pipeline/README.md). 
* Verify that the pipeline displays correctly, and the scrollbars don't appear.

Improve space usage of concourse cleaner chrome plugin.

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml

Story: [Check health of nats component](https://www.pivotaltracker.com/story/show/131355575)
https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/3 implemented checks for NATS and NATS stream forwarder. Unfortunately the NATS stream forwarder process check was checking for 'ruby' or 'nats_stream_forwarder.rb', and not 'ruby' and 'nats_stream_forwarder.rb'. The check now looks for the full string and doesn't give false positive.
This depends on https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/4.
* Deploy with `ENABLE_DATADOG=true`
* Logon one of the NATS servers
* Start any ruby process, for example: `ruby -e "sleep 10000" &`
* Stop NATS stream forwarder: `monit stop nats_stream_forwarder`
* The monitor should fail in datadog
* Merge …

[#131355575] Fix NATS stream forwarder process check

---

Makefile
concourse/pipelines/create-deployer.yml
concourse/scripts/pipelines-deployer.sh
manifests/concourse-manifest/concourse-base.yml
manifests/concourse-manifest/scripts/generate-concourse-secrets.rb
manifests/concourse-manifest/spec/fixtures/generated-concourse-secrets.yml
manifests/concourse-manifest/spec/support/manifest_helpers.rb
terraform/concourse/elb.tf

[Make it more difficult to run actions manually on Production Concourse](https://www.pivotaltracker.com/n/projects/1275640/stories/130844201)
To make our concourses more distinctive in order to avoid operator accidentally operating on different environments:
* add team with aws account specific name
* set login timeout to 5 minutes on prod
Note that this PR does not migrate the pipelines to the new team yet. We'll implement that later if we see the need.
`make dev bootstrap`. Deploy. See team being created. Go to your concourse and try logging in using the new team. Password and user are the same (admin/usual PW). To test 5m timeout, edit pipeline & change the condition to check against 'dev' instead of 'prod' [here](https://github.com/alphagov/paas-cf/commit/6e80e34acc555b151ec3ed836dfd07 …

[#130844201] More distinctive concourses

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/kibana_set_utc.rb
concourse/scripts/kibana_set_utc_test.go
manifests/cf-manifest/manifest/800-logsearch.yml
terraform/cloudfoundry/logsearch_elb.tf

This is the minimal set of changes needed to upgrade our existing Logsearch install from v200 to v203. We took the approach of modifying our existing manifests to accommodate upstream changes rather than outright replacing them because we have previously heavily customised the Logsearch install to make it highly available.
Notable things:
* We no longer install HAProxy on the Kibana VM as it was totally unnecessary in our deployment with ELB's. As a result we needed to change the Kibana ELB port to correctly address Kibana itself rather than the HAProxy port.
* There may be a better way to set the Kibana timezone, however we chose not to implement it. Future versions of us may wish to look at: https://github.com/alphagov/paas-logsearch-for-cloudfoundry/blob/master/src/logsearch-config/src/ …

[#127564379] Upgrade Logsearch to v203

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml

[#132649921 Respond to CVE 2016-6655: Utility script command injection](https://www.pivotaltracker.com/story/show/132649921)
What?
-----
Use patched version of gorouter v0.136.0-gds1
Temporary fix for CVE 2016-6655 [1]. This is a temporary fix to address the issue for gorouter while we work on upgrading CF.
[1]https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/42YUJU2N27HBPFVMZR2QM7JI6YSEKORR/
How to review
-------------
Deploy it, tests should pass. Check that this command on router/{0,1} does not return a process in the gorouter group:
```
ps -feax | grep -B5 -e "system(lineWithDate)"
```
Who?
---
Anyone but @alext or @keymon

[#132649921] Use patched gorouter with hotfix for logging CVE

---

manifests/cf-manifest/manifest/020-cf-properties.yml
platform-tests/src/acceptance/http_strict_transport_security_test.go
terraform/cloudfoundry/dns-records.tf

Story: [Fix credential leakage in aws-account-wide-terraform](https://www.pivotaltracker.com/story/show/132170169) 
We want to stop using the AWS API Gateway as it introduced the need to use the `aws_api_gateway_domain_name` resource in Terraform, which does not obfuscate sensitive fields, such as the certificate private key. However, we still need to serve valid HSTS headers from the apex domain (`cloudapps.digital`). We add the necessary HSTS header directives to the existing HSTS configuration in the manifest.
To be reviewed in conjunction with https://github.gds/government-paas/aws-account-wide-terraform/pull/63, which must be deployed to staging and production first.
* Use `curl` to get the headers for the healthcheck application and the apex domain:
```
$ …
```

[#132170169] Configure apex domain to serve HSTS preload headers

---

manifests/bosh-manifest/deployments/010-bosh-template.yml
manifests/bosh-manifest/scripts/generate-bosh-secrets.rb
manifests/bosh-manifest/spec/fixtures/bosh-secrets.yml

Story: https://www.pivotaltracker.com/story/show/119717141
This is BOSH upgrade to the v257.14. Release notes:
https://github.com/cloudfoundry/bosh/releases/tag/stable-3262.14
Apart from [Redis removal](https://github.com/cloudfoundry/bosh/releases/tag/stable-3232) there are no other manifest changes mentioned neither by BOSH release notes nor by CF release notes. 
We bumped the version to the latest stable version as there are no recommendations in cf-release notes. Recommended stemcell version is 3262.X family - we are using 3262.9. 
- apply this on top of existing env
- deploy env from scratch
- autodele pipeline
- all should work, no test failures
not @combor or @paroxp

[#119717141] BOSH version bump

---

manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
platform-tests/src/acceptance/rds_broker_test.go

[Pivotal story](https://www.pivotaltracker.com/story/show/128397007)
In order to meet user needs, we'd like to allow them to have a choice of
two additional RDS Postgres instance sizes.
We've added the `db.t2.small` and `db.m4.2xlarge`, along with
appropriate description and metadata. Extended and amended two sets of
tests, in order to cover the new instance choices.
We have also covered a common request of mentioning the actual instance
name, in the description.
- Deploy the changes
- Run `cf marketplace -s postgres`
- You should see, four additional plans, `S-dedicated-9.5` and `L-dedicated-9.5` along, with their HA version.
- Attempt to create one of the new instances.
- Check if the correct instance has been initialised.
Neither @paroxp nor @Jonty

Add small and large instance sizes

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/040-graphite.yml
manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/cf-manifest/manifest/800-logsearch.yml
manifests/cf-manifest/stubs/datadog-nozzle.yml
terraform/datadog/consul.tf

Story: [Check Consul cluster and agents](https://www.pivotaltracker.com/story/show/131377245)
This covers the most critical:
* Consul process
* Consul server
It depends on PR https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/5
* Deploy with `ENABLE_DATADOG=true`
* Verify the Consul monitors have been created in Datadog
* Connect to a Consul host, stop or kill Consul processes, stop datadog agent... and check the monitors are failing
* When ready, merge PR https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/5
* Create and push tag `0.0.5` on `paas-datadog-for-cloudfoundry-boshrelease` master
* Remove commit 2a99f98d36b82ac4835cc7ed0ac1e8cdc486d6cb in this branch
* Merge this PR
Not @combor or @paroxp

[#131377245] Add consul checks

---

README.md
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/scripts/pipelines-deployer.sh

Don't deploy failure-testing pipeline by default. We rarely run this pipeline and
* it consumes concourse resources for version checks
* it is a bit dangerous to be run on prod/staging, but is still present on that concourse...
`make dev pipelines`. If you had it uploaded before, observe it being removed. To enable it, follow instructions in readme.
not me

No failure-testing pipeline by default

---

concourse/pipelines/create-bosh-cloudfoundry.yml

This way we can remove previous releases/packages/stemcells immediately after they stop being used. This is also important for long running environments where we would not run cleanup otherwise and only accumulate previous versions forever, which can also potentially impact BOSH performance and reliability.
Apply this PR. Run deploy job. Observe it running bosh cleanup task.
not @mtekel

Run bosh cleanup after deploy

---

platform-tests/src/acceptance/python_buildpack_test.go

[#132651425 Full fix for CVE 2016-6655: Utility script command injection (aka Upgrade to CF 245)](https://www.pivotaltracker.com/n/projects/1275640/stories/132651425)
What
----
The Python apps take longer to stage. We found out that the current
`cf start` for the python buildpack test is timing out, specially
when running the test.
That is very likely due the multiple nodes causing load on the platform.
To reduce the number of failures, we will increase the timeout by using
CF_PUSH_TIMEOUT (2 minutes) instead of DEFAULT_TIMEOUT*2 (1 minute) in
the `cf start` of the python app.
How to test?
-----------
Run the pipelines and the tests
Who
---

[#132651425] Change timeout for test python_buildpack Procfile

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml

[#132909443 Respond to CVE-2016-5195 kernel vulnerabilty](https://www.pivotaltracker.com/story/show/132909443)
What
-----
We want to upgrade to a newer stemcell which includes the patch for CVE-2016-5195 [1]. The CF bosh team has recently release a patched version of the stemcell[2], despite being reticent at the beginning
[1] http://dirtycow.ninja/
[2] https://cloudfoundry.slack.com/archives/bosh/p1477113219004741
How to test
-----------
Deploy this branch, should deploy and pass the tests.
References
----------
Related code in #559 and #557, but they are not dependencies.
If #557 is merge, we should rebase, ofc
Who?
---

[#132909443] Upgrade to stemcell 3262.x to fix CVE-2016-5195

---

Makefile
README.md
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/tasks/create_admin.yml
concourse/tasks/custom-acceptance-tests-run.yml
concourse/tasks/delete_admin.yml

Improve dev pipeline execution by disabling pipeline locking by default and making disabling custom acceptance test optional via env. variable. Also refactor variable names, where VERB_something still meant yes/true if the variable was undefined previously. This doesn't fix all variables yet.
1. `make dev pipelines`. Go for lunch (acceptance tests take 1h+). Check that pipeline didn't lock and unlock, acceptance and custom acceptance tests ran and healthcheck DB was not deployed.
2. Remove defaults from makefile:
```
--- a/Makefile
+++ b/Makefile
@@ -94,10 +94,8 @@ dev: globals check-env-vars ## Set Environment to DEV
$(eval export APPS_DNS_ZONE_NAME=${DEPLOY_ENV}.dev.cloudpipelineapps.digital)
$(eval export SKIP_COMMIT_VERIFICATION=true)
$(eval export …
```

[#133085655] Faster dev pipeline execution - no locking

---

terraform/datadog/consul.tf
terraform/datadog/nats.tf
terraform/datadog/router.tf

[#133085073 Use new mailing lists for datadog alerting](https://www.pivotaltracker.com/story/show/133085073)
What
-----
Currently some monitoring alert emails go to the team list and:
* cause noise for people looking out for prod alerts
* annoy people who are subscribed to the team list who can't do anything about the alerts
We got dedicated maillists for that in @govpaas-alerting-%s@digital.cabinet-office.gov.uk
But some alerts are misconfigured.
How to test?
------------
* Check it makes sense.
* Check syntax
I do not recomment to apply it as that means redeploy everything, I think it is safe to merge a check the configuration in CI, staging and prod.
Who?
----

[#133085073] Use govpaas-alerting-* mail lists for all alerts

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/020-cf-properties.yml

v78 fixes issue with ETCD network debugging being turned on all the time and being undisableable. This is a new property/functionality that was not present in previous ETCD release we were using in cf v240. Because of a bug in v75, it produces extreme amount of logs, quadrupling total amount of all logs from whole platform. Latest ETCD release contains fix for that and only runs this functionality for 5 minutes from just before ETCD restart.
We currently have v75 deployed which is spamming logsearch with these messages and disks are filling quickly (capacity is not planned for 4x log volume).
Deploy. Go to logsearch and check that `etcd-network-diagnostics` components stops sending messages 5 mins after ETCD restart. If it doesn't check if there isn't hanging previous instance of the …

[#131634733] Upgrade ETCD to v78

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
platform-tests/src/acceptance/rds_broker_test.go

This adds a new 'Free' service plan to the RDS broker. This plan is using the smallest available RDS instance with the smallest allowed storage allocation, and all snapshotting disabled. It's intended to be used for experimentation etc.
As part of this, I've also made the following changes:
* Updated the postgres version to 9.5.4 (from 9.5.2). (See commit message for details).
* Updated the acceptance tests to use this plan where possible (the snapshot related tests need to use one of the plans with snapshots available).
* Updated the healthcheck-db to use this Free plan (this includes a commit to re-create existing instances with the old plan that can be reverted once this has run everywhere).
To test the updates to the healthcheck-db, you'll need an environment deployed form master with …

[#133184695] Create a 'Free' RDS broker service plan.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml

[#133003305 Upgrade to stemcells with kernel 4.4 and garden-linux to garden-runc](https://www.pivotaltracker.com/story/show/133003305)
and
[#132909443 Respond to CVE-2016-5195 kernel vulnerability (AKA upgrade to stemcell 3263 and garden-runc)](https://www.pivotaltracker.com/story/show/132909443)
What?
-----
In the story #132909443 we apply the patch for [a vulnerability that allows escalation of privileges CVE-2016-5195 (aka dirtycow)](http://dirtycow.ninja/) in the linux kernel that has been reported recently. Our systems are affected, but specially worrying are the cells and the containers running on it.
Despite being reticent, Cloud Foundry community included a [patched version in a older series with 3.3](https://cloudfoundry.slack.com/archives/bosh/p1477113219004741) on 3262.22. That …

[#133003305] Upgrade stemcell 3263 and migrate to garden-runc

---

concourse/pipelines/create-bosh-cloudfoundry.yml

In #569 we switched the healthcheck DB to use the new Free plan. This required a temporary script to do this. Now that this has run everywhere, it can be removed.
Verify that the healthcheck DB is using the Free plan in all persistent environments. Verify that this revert looks sensible.
This reverts commit fccc839907ec9ed07cd23a3e6cee418d7b004864.

[#133184695] Revert "Update plan of existing healthcheck instances"

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml

[#132082633 - Router HAProxy restarts rsyslog without reason](https://www.pivotaltracker.com/n/projects/1275640/stories/132082633)
We want to reduce the number of unnecessary restarts of rsyslog, as the amount of time it takes to restart has been known to cause deployment failures.
This pull request changes our version of the HAProxy release to 0.0.5. This version changes the start script so it only restarts rsyslog if the configuration changes.
* Check tests pass
Anyone but me

[#132082633] Use version 0.0.5 of paas-haproxy-release

---

manifests/bosh-manifest/bosh-manifest.yml

[#132681767 Upgrade BOSH #2: stemcell, CPI and new features](https://www.pivotaltracker.com/story/show/132681767)
What
----
We upgraded bosh release, and later the CF stemcell. Now we want to upgrade the stemcell for bosh.
~~We also upgrade the stemcell of concourse, to keep consistency.~~
The change basically changes from the kernel 3.3 to 4.4
~~In the case of concourse, the change is only minor bugs.~~
Dependencies
I suggest to merge #565 first, but it is not really required.
How to review
-------------
* Check that the change makes sense (urls, hash)
* Optionally deploy the environment and check that bosh is working (e.g. run all the pipeline). ~~The same for concourse.~~
~~I do not think it is required to redeploy concourse in all the environments after this is …

[#132681767] Upgrade stemcells for bosh to 3263.8

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/bosh-manifest/bosh-manifest.yml
manifests/bosh-manifest/spec/properties_spec.rb
manifests/cf-manifest/cloud-config/000-base-cloud-config.yml
manifests/cf-manifest/cloud-config/020-cf-vm-types.yml
manifests/cf-manifest/cloud-config/030-logsearch.yml
manifests/cf-manifest/common/metron.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/runtime-config/runtime-config-base.yml
manifests/cf-manifest/spec/cloud-config/vm_types_spec.rb
manifests/cf-manifest/spec/support/manifest_helpers.rb
manifests/concourse-manifest/concourse-base.yml

[#132681767 Upgrade BOSH #2: stemcell, CPI and new features](https://www.pivotaltracker.com/story/show/132681767)
What?
-----
We have upgraded bosh in #551 but left some things out of scope. We want to continue with the upgrade now.
We upgrade and change:
* Bosh release one version more, to v258
* CPI release
* enable the event recording
* reserve on worker for status tasks
* implement arp flushing
* add some ephemeral disk to the cells
It also includes #568, which has been merged under request of @mtekel 
Dependencies
------------
This can be reviewed with #568 and https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/76
This changes the runtime-config for the metron agent, so it either needs to be rebased after merging #561 or #561 must be rebased and remove these changes.
How …

[#132681767] Upgrade bosh #2: bosh release, cpi and enable some features

---

manifests/cf-manifest/manifest/050-rds-broker.yml

[#132312331](https://www.pivotaltracker.com/story/show/132312331) Update dependencies of rds-broker
This updates the version of paas-aws-broker-boshrelease to a version that includes the changes to paas-rds-broker https://github.com/alphagov/paas-rds-broker/pull/18
Note this is a [TMP] commit, it will need to be reworked with a good reference once https://github.com/alphagov/paas-aws-broker-boshrelease/pull/14 is merged and tagged
Run through a development environment.
- aws-rds-broker should be redeployed
- Acceptance tests should continue to pass.
Not @richardc

[#132312331] Update aws-broker-release

---

Makefile
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
terraform/datadog/cve-notifier.tf

Story: [Ensure we are notified quickly about CF security patches (CVEs)](https://www.pivotaltracker.com/story/show/127345741)
This deploys the cve-notifier application to the platform so we can be notified of new CVEs.
Depends on PR: https://github.com/alphagov/paas-cve-notifier/pull/1
- Access the [CVEs dashboard](https://app.datadoghq.com/screen/131796/published-cves)
- Deploy to your environment
- Access the [CVEs dashboard](https://app.datadoghq.com/screen/131796/published-cves). There should be test CVEs now.
- Delete the app
- It should trigger monitor cve-notifier
- Delete TEMP commits in this branch and in  paas-cve-notifier PR
- Merge paas-cve-notifier PR
- Merge this PR
- Rerun your pipeline from master, it should delete the monitor (or delete manually)
Not @paroxp or me

[#127345741] CVE notifer

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml

[#133431043 Clean-up stemcell+release from upgrade stemcell and garden-run](https://www.pivotaltracker.com/n/projects/1275640/stories/133431043)
What?
-----
After #565 has been deployed and it run on prod without issues for a while, we can remove the references to the old garden-linux, the stemcell 3262 and the temporary job cell_3_3.
How to test?
------------
Nothing really, simply check it makes sense.
Who?
----

[#133431043] Remove old garden-linux release, stemcell and cell_3_3 job

---

manifests/cf-manifest/manifest/env-specific/cf-prod.yml

We have recently added new organizations and increased quotas for existing ones. Our total reserved memory is 322. To be able to provide 50% of that when a zone fails, we need 6 cells. That means 9 in total.
Create a branch from this branch. `mv manifests/cf-manifest/manifest/env-specific/cf-prod.yml manifests/cf-manifest/manifest/env-specific/cf-default.yml`, push. Deploy to your dev environment. Verify that you have 9 cells, 3 in each zone.
not @mtekel

[#133085245] Increase prod cell capacity

---

manifests/cf-manifest/manifest/050-rds-broker.yml

[#132312331 Update dependencies of rds-broker](https://www.pivotaltracker.com/story/show/132312331)
What?
-----
This reverts commit e14bd50514f690975cffc3b2253ad27a75e25235, reversing
changes made to 090464428c0cd37a21040bf5954a395d5205960f.
We discovered that the upgrade breaks the asynchronous deletion and we must revert.
Who?
----

[#132312331] Revert "Merge pull request #574 from alphagov/feature/132312331_merge_rds-broker-pr"

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/050-rds-broker.yml

This updates to the latest release of rds-broker. This is actually a
no-op change because there were some changes introduced to the
rds-broker[1] that were then reverted[2]. It's worth updating so that
the pipeline is up to date, making future changes easier.
This also changes the way we consume the release. We were previously
building a dev release in the pipeline from the git sources. This is
somewhat inefficient, and also has issues with the way that the version
is pinned in the git resource, especially when we have to go back a
version. Building a release once and uploading to a git release makes
this much simpler, and also means that we consume the release in the
same way as 3rd-party releases that are published to bosh.io.
[1]https://github.com/alphagov/paas-rds-broker/pull/18 …

[#132312331] Use latest aws-broker release from Github release.

---

concourse/scripts/fly_sync_and_login.sh

What?
----
Our fly_sync_and_login.sh file will download the fly command from the
fly server if the local file is older than the one in the server.
But if the file has been locally updated with a different version more
recently, for example because one environment has a different concourse
version, the curl command will not update the binary.
But concourse fly command provides a `fly sync` that will update the
binary if there is version mistmatch. We can execute this fly sync
command just after login.
How to test?
-----------
Download a different version of the fly command, for instance 2.4.0 from
the concourse ci itself:
```
curl 'https://ci.concourse.ci/api/v1/cli?arch=amd64&platform=linux' -O bin/fly && chmod +x bin/fly
```
run bosh-cli and check that gets updated
```
make dev bosh-cli …
```

[#support] Perform a fly sync after login

---

concourse/pipelines/create-bosh-cloudfoundry.yml
terraform/datadog/cve-notifier.tf
terraform/datadog/variables.tf

Story: [SPIKE: Ensure we are notified quickly about CF security patches (CVEs)](https://www.pivotaltracker.com/story/show/127345741)
The solution required a few improvements: enable/disable the app monitoring according to the environments and better tagging to identify the checks.
Depends on https://github.com/alphagov/paas-cve-notifier/pull/2
Review along https://github.com/alphagov/paas-cve-notifier/pull/2
* Deploy CF. The TEMP commits will enable datadog just for creating the monitor and deploy the cve-notifier app, so you don't have to redeploy bosh.
* It should create a new `<env> cve-notifier` monitor and it should become green
* Remove the TEMP commits and redeploy. It should remove the monitor. You should delete the app.
* Merge https://github.com/alphagov/paas-cve-notifier/pull/2 …

[#127345741] CVE notifier improvements

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/pipelines/failure-testing.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/tasks/custom-acceptance-tests-run.yml
concourse/tasks/smoke-tests-config.yml
concourse/tasks/smoke-tests-run.yml
concourse/tasks/upload-test-artifacts.yml
manifests/cf-manifest/manifest/900-cf-tests.yml
platform-tests/generate_test_config.rb
platform-tests/src/acceptance/init_test.go
terraform/cloudfoundry/buckets.tf

[#121483833 - Capture api calls made in pipeline tests](https://www.pivotaltracker.com/story/show/121483833)
We want to be able to capture the CF_TRACE output during Cloud Foundry tests in the pipeline, because it provides useful debugging information when investigating failed tests. We do not want to output this to the pipeline, as we cannot be certain it is free of secrets, so we will store it in a bucket.
* Check the `upload-test-artifacts` task succeeds for the following jobs:
* acceptance-tests
* custom-acceptance-tests
* smoke-tests
* Check the bucket `gds-paas-$DEPLOY_ENV-test-artifacts` for three files, which should be TAR files from the jobs listed above.
* Make one of the tests fail and check it still uploads the file.
* If you are really curious you …

[#121483833] Capture API calls during pipeline tests

---

manifests/cf-manifest/runtime-config/runtime-config-base.yml
manifests/shared/deployments/syslog.yml

[#131975557 Alternate solution to configure syslog forwarding without metron agent](https://www.pivotaltracker.com/story/show/131975557)
What?
-----
After merging #570 and #561, we have broken the log forwarding to logsearch.
See the story and commits for details.
We fix the issues in this PR
Dependencies
------------
https://github.com/alphagov/paas-syslog-release/pull/1 should be merged first, the code tagged, a new release built and the commit in this PR updated.
Both can be tested together.
How to review?
--------------
* Deploy.
* Check that the logs are being sent to loggregator and parsed properly
* Check that in the VMs:
* the `/etc/rsyslog.d/rsyslog.conf` using the template format with `[job=jobname index=X]`
* the `/var/vcap/jobs/cleanup_syslog_forwarding/bin/cleanup_syslog_forwa …

[#131975557] Fix rsyslog log forwarding and parsing

---

concourse/tasks/upload-test-artifacts.yml

[#121483833 - Capture api calls made in pipeline tests](https://www.pivotaltracker.com/story/show/121483833)
What?
-----
In #582 we added logic to "Capture API calls during pipeline tests"
But in the upload tests artifacts task, the tar command would fail if the previous tests did not generate any test artifacts with the api calls:
Archiving test artifacts...
tar: *: No such file or directory
tar: error exit delayed from previous errors
This can happen if the acceptance tests are disabled, like in staging&prod. e.g: https://deployer.staging.cloudpipeline.digital/teams/main/pipelines/create-bosh-cloudfoundry/jobs/acceptance-tests/builds/279
To avoid that, we add some logic to skip the upload if there are no file in the artifacts directory.
How to test?
-----------
Run the acceptance-tests …

[#121483833] Upload test artifacts skips when there is none

---

terraform/cloudfoundry/buckets.tf

As a requirement for being able to [restore blobstore buckets to a point-in-time](https://www.pivotaltracker.com/n/projects/1275640/stories/130195859) and to be able to enable replication later, we need to enable bucket versioning. We also add a lifecycle that mirrors backup settings for the CC DB.
Run `cf-terraform` job, e.g. `JOB=cf-terraform make dev run_job`.
* If you had existing environment, then verify that the job applies changes to the blobstore buckets.
* If you deployed from scratch from this branch, verify that the job doesn't apply any changes.
Finally, verify directly in S3 that the versioning and lifecycle are configured for blobstore buckets.

[#130195859] Enable versioning for CF blobstore buckets

---

manifests/bosh-manifest/extensions/datadog-agent.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/040-graphite.yml
manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/cf-manifest/manifest/800-logsearch.yml
manifests/cf-manifest/spec/manifest/jobs_spec.rb
manifests/cf-manifest/spec/runtime-config/shared_config_spec.rb
manifests/cf-manifest/stubs/datadog-nozzle.yml
manifests/concourse-manifest/extensions/datadog-agent.yml
manifests/shared/deployments/datadog-agent.yml
terraform/datadog/cell.tf
terraform/datadog/concourse-jobs.tf
terraform/datadog/consul.tf
terraform/datadog/cve-notifier.tf
terraform/datadog/general.tf
terraform/datadog/nats.tf
terraform/datadog/router.tf

With the new features in datadog agent, we don't need to create a `job` tag adhoc, as `bosh-job` is provided to us by the datadog bosh-release: https://github.com/onemedical/datadog-agent-boshrelease/pull/8.
We have refactored all the graphs and monitors, to use the new tag `bosh-job` and `bosh-deployment` instead.
Note: This does not apply for the metrics reported by datadog-nozzle, which will be tagged with `deployment` and `job` instead.
The datadog agent sets the bosh-job tag automatically. We're removing the specific tags added to each one of the jobs, as they have been deprecated.
As `environment` and `bosh-deployment` were actually the same concept, for consistency, we will delete `environment` and  use only `bosh-deployment`.
Test that the tags are defined globally in the runtime …

[#132160889] Replace datadog tag naming 

---

Makefile
concourse/scripts/shake_concourse_volumes.sh
scripts/ssh.sh

[#133748125  Automate execution of clear volumes procedure of concourse](https://www.pivotaltracker.com/story/show/133748125)
What?
----
We want to automate the procedure to restart and clear all the volumes in concourse. We run this often enough to automate it.
For several versions of concourse, we had multiple problems mostly related to baggageclaim volumes[1][2][3][4]
The development team in concourse says being working on it and refactoring the logic related to volume management.
Meanwhile the problem is not completely fixed, we found that the procedure commented here: https://github.com/concourse/concourse/issues/565#issuecomment-237845601 helps a lot. Basically it will:
* stop concourse services and workers.
* kill all containers.
* clear container network.
* clean up the volumes …

[#133748125] make target to restart concourse and clear volumes

---

README.md
doc/datadog.md

If you don't have dev keys (or have expired ones) in your environment when enabling datadog you will get strange errors due to a terraform bug and a datadog bug. This clarifies the documentation to ensure you won't forget to publish keys.
Check that the procedure described makes sense.
You! Certainly not @jonty.

Clarify documentation for datadog dev proceedure

---

manifests/cf-manifest/runtime-config/runtime-config-base.yml

[#133741599 Remove syslog cleanup job](https://www.pivotaltracker.com/story/show/133741599)
[#131975557 Alternate solution to configure syslog forwarding without metron agent](https://www.pivotaltracker.com/story/show/131975557)
What?
-----
in #561 and 561cb6b we had to add a addon to remove the rsyslog config
file created by metron_agent.
The change has been deployed in all the environments, so we can remove
this cleanup job.
How to review
-----------
Check that makes sense.
Who?
---

WIP: [#133741599] Remove the cleanup_syslog_forwarding addon

---

concourse/pipelines/create-bosh-cloudfoundry.yml

Story: [Create Dashboard based on Datadog Monitoring](https://www.pivotaltracker.com/story/show/132736941)
When deployed to production the paas-dashboard app was crashing as it uses slightly more memory than the allocated 100MB.
We increase it to 256MB to avoid this.
* Deploy with `ENABLE_PAAS_DASHBOARD=true`
* Check the app `paas-dashboard` in org admin space admin has 256MB allocated
Not me

[#132736941] Increase memory allocated to paas-dashboard

---

manifests/concourse-manifest/concourse-base.yml

[#133513945 Upgrade concourse 2.4.0](https://www.pivotaltracker.com/story/show/133513945)
What?
-----
We want to upgrade concourse to keep the latest version for support and because they claim if fixes issues managing volumes.
No changes in the config but some additional features and bugfixes.
To highlight:
>   feature
>
> Baggageclaim will now be more durable to corrupt volumes. Previously
> a borked metadata file would effectively wedge the Baggageclaim API,
> making the worker unrecoverable. You would see an error like "failed
> to list volumes" in your builds. Baggageclaim will now pretend these
> volumes don't exist in the API, and reap them from the disk.
[1] https://concourse.ci/downloads.html#v240
I also use the same version of stemcell than CF and bosh.
How to test?
----------- …

Upgrade to concourse 2.4.0

---

platform-tests/src/acceptance/http_closed_test.go
platform-tests/src/acceptance/rds_broker_test.go

Currently we run several tests in parallel, and the load might make the operation last longer, so the test fails due timeout. It already happened several times in our CI environment
We use in most cases CF_PUSH_TIMEOUT (2m) for `cf push` or `cf start` currently 2m, instead of `DEFAULT_TIMEOUT` (30s) in the rest of operations.
In this PR we apply it to all the cases.
Double check that makes sense. I think it is quite safe to merge.

Use CF_PUSH_TIMEOUT for any `cf push` or `cf start` in our tests.

---

manifests/cf-manifest/runtime-config/runtime-config-base.yml

Story: [Fix rsyslog high cpu usage & getting stuck on restart](https://www.pivotaltracker.com/story/show/133106357)
There is an issue in our configuration when sending logs via RELP protocol from syslog to logstash via an ELB. If the ingestor is temporarily disconnected, the messages aren't logged anymore. Rsyslog tries to reconnect, opens many connections and consumes a lot of CPU.
We may investigate the root cause but in the meantime, we revert to the default TCP configuration because it doesn't show this behaviour.
* Deploy
* SSH to `cell/0` for example
* Observe rsyslog is not connected to the ingestor ELB via RELP: `netstat -an | grep :2514`
* Observe rsyslog is connected to the ingestor ELB via TCP: `netstat -an | grep :5514`
* In AWS console, locate the ingestor ELB and remove the …

[#133106357] Switch rsyslog from RELP to TCP

---

concourse/pipelines/create-bosh-cloudfoundry.yml

[#131975557 Alternate solution to configure syslog forwarding without metron agent](https://www.pivotaltracker.com/story/show/131975557)
What?
-----
In #561 and #585 we added some logic to remove the old rsyslog config created by metron_agent. But this solution did not work completely due some reason, and some VMs keeped the old file.
As it is quite slow and tedious the approach of creating an adhoc task to delete the file, we will use a concourse task that runs a `bosh ssh` on all the VMs.
This is simplier, quicker to develop and review, and easier to test and later remove. I also prevent unnecesary bosh deployments and restart of services after removing the task.
Currently this task will do bosh ssh on each VM, check if the file `/etc/rsyslog.d/00-syslog_forwarder.conf` is present, and …

[#131975557] Add adhoc bosh ssh task to clean old rsyslog conf

---

manifests/shared/lib/secret_generator.rb
manifests/shared/spec/secret_generator_spec.rb

We've recently hit an issue with a generated password that started with
a - tripping up one of the CLI tools we use (`cf create-service-broker`).
This therefore changes the password generation scheme we use to use hex
instead. It also increases the length from 12 to 18 chars so that the
generated passwords continue to represent the same number of random
bytes.
Note: because passwords are only generated when missing, this won't affect any existing passwords, only new ones.
Code review.
Run the pipeline as far as generate-secrets.
* Existing passwords should be unchanged.
* New passwords should now be 18 chars of hex.
Not me.

[#133855001] Avoid - and _ in generated passwords.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
tools/paas_dashboard/Gemfile
tools/paas_dashboard/Gemfile.lock
tools/paas_dashboard/Procfile
tools/paas_dashboard/dashboards/paas-overview.erb
tools/paas_dashboard/manifest.yml
tools/paas_dashboard/widgets/health/health.html
tools/paas_dashboard/widgets/health/health.scss

We want to use a vertical split view to show this dashboard on our big
screens. This updates the Smashing Datadog dashboard to arrange the 3 boxes
vertically. It also updates the sizes to be dynamic based on the window
size. In order to get the fonts sized accordingly, I've had to use the
[viewport-percentage units](https://drafts.csswg.org/css-values/#viewport-relative-lengths). This is the best that's possible with pure
CSS, but they will need updating if we add/remove rows.
This also includes a couple of other small fixes/improvements. See individual commits for details.
Push the dashboard to a CF instance.
* `cf login`, and target a suitable space.
* Push the app:
```sh
cd tools/paas_dashboard
cf push testing-dashboard --no-start
cf set-env testing-dashboard DD_APP_KEY "$(paas-pass …
```

[#132736941] Layout Datadog dashboard vertically

---

concourse/pipelines/create-bosh-cloudfoundry.yml

[#133741599 Remove syslog cleanup job](https://www.pivotaltracker.com/story/show/133741599)
Dependencies
------------------
Wait for #598 to be deployed in prod!
What?
-----
Continuation of #593
We added an adhoc task to remove a spurios rsyslog config from the metron_agent.
The previous approach from #561 and 561cb6b to add a addon to remove
the rsyslog config file created by metron_agent did not work.
This reverts commit 82c8fc8743fe6145561bab96d1a60045a7f9ecde. The job has run in all the environments, deleting the undesired config and restarting rsyslog.
How to review?
---------------
check that makes sense
Who?
----

[#133741599] Revert "Add adhoc bosh ssh task to clean old rsyslog conf"

---

doc/non_dev_deployments.md
manifests/cf-manifest/scripts/generate-cf-certs.sh

This process is somewhat gnarly due to limitations in terraform and the
way we've had to split things up.
Having said that, it's still valuable to have this documented until we
can come up with another approach (possibly not using terraform for this
specific bit).
This PR also includes the removal of a shellcheck disable that's no longer needed now that we've upgraded shellcheck.
Read the new docs, and verify they make sense.
Verify Travis passes.
Anyone buy @henrytk or myself.

[#132331007] Document how to rotate the manually uploaded certs.

---

misc/chrome_plugins/clean_concourse_pipeline/src/inject.user.js

[#133513945 Upgrade concourse 2.4.0](https://www.pivotaltracker.com/story/show/133513945)
What?
----
This plugin assumes that all the elements are present and the page
rendered after 10ms, and if not, it fails because it cannot find the
right DOM elements.
The new version of concourse 2.4.0 takes longer to completely render in
the dashboard screen, specially when we have 3 frames as we do. Because
that the script does not work in our dashboard.
In this commit we workaround this issue by delaying the execution of
the script much more longer, up to 2000ms or 2s.
A more elegant solution should be waiting/polling until all elements are
present and then apply the changes. But as this is a simple script for
our dashboards it is not so relevant.
How to test?
------------
I applied this to the …

[#133513945] Increase delay of clean_concourse plugin to 2s [ci skip]

---

concourse/scripts/environment.sh

Also show grafana password when we do 'make <env> showenv'. This is for convenience so that we don't need to retrieve the password in a separate step.
Type `make <env_type> showenv`. See grafana password.
not @mtekel

Add grafana password into showenv

---

Makefile
concourse/scripts/environment.sh

We do call the environment script in our pipeline and we run it in a container that does not have 'aws' tool installed - or even keys configured. Add same condition that we use for ATC password and adjust the relevant task in the pipeline to skip trying to retrieve grafana password
Run bosh-cli tests task and make sure it passes.
not @mtekel

Fix issues created by displaying grafana PW

---

.travis.yml
concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/bosh-manifest/bosh-manifest.yml
manifests/bosh-manifest/spec/support/manifest_helpers.rb
manifests/cf-manifest/spec/support/manifest_helpers.rb
manifests/concourse-manifest/spec/support/manifest_helpers.rb
manifests/shared/deployments/datadog-agent.yml
scripts/job_instances.rb
scripts/lib/job_instances_lib.rb
scripts/spec/job_instances_spec.rb
terraform/datadog/bosh-jobs.tf
terraform/datadog/variables.tf

[#133751193 Enable datadog BOSH healthmonitor integration](https://www.pivotaltracker.com/story/show/133751193)
NOTE: This is WIP because we are not sure about the cost of adding the metrics in datadog.
What?
----
[The BOSH health monitor runs on the director VM and receives heartbeats every minute from all bosh agents via the Bosh NATS bus](https://bosh.io/docs/monitoring.html). The heartbeats contain system metrics (CPU, Memory, load, etc) and if all the monit services are running on the VM `bosh.healthmonitor.system.healthy` .
We are mainly interested in this `bosh.healthmonitor.system.healthy` metric, and we will ignore the other metrics that are already being sent by the datadog agents on each VM.
[Bosh health_manager can be configured to send the metrics to …

[#133751193] Enable datadog BOSH healthmonitor integration and add some monitors on healthy metric]

---

concourse/scripts/pipelines-bosh-cloudfoundry.sh

When you set "ENABLE_DATADOG" to true, you declare your intention to deploy monitoring. For that to work, you also have to have datadog keys available in your bucket (done with `make upload-datadog-secrets`). If you forgot about this, everything will work fine and deploy. Except no metrics will be
sent. So you have to investigate, figure out and then deploy everything again. Which can take couple of hours at least...
Stop deployment when datadog is enabled, but no keys are retrievable.
This has happened to me once and to @henrytk at least once as well. And it took half day to fix. Let's add this check so that we don't lose any more time.
1. With `datadog-secrets.yml` missing in your bucket, try `ENABLE_DATADOG=true make dev pipelines`. It should fail with 
```
Datadog enabled but could …
```

Prevent datadog deployment with missing keys

---

manifests/bosh-manifest/bosh-manifest.yml
manifests/bosh-manifest/extensions/datadog-agent.yml

[#133751193 Enable datadog BOSH healthmonitor integration](https://www.pivotaltracker.com/story/show/133751193)
In #607 we have introduced a "fixed" portion of hm config which references meta.datadog, but which is only added in datadog extension yml - which is not merged in when datadog is disabled. This then breaks rendering of manifest. Move datadog monitor config into extension file to fix this.
Run generate-bosh-config with datadog enabled and with datadog disabled. It should work correctly in both cases.
not @mtekel

[#133751193] Fix BOSH manifest rendering without datadog

---

scripts/create-user.sh

We've ran into an issue, where the script failed with the message requesting correct AWS credentials, whilst not being logged in.
In order to avoid the confusion, we've placed an extra check just before the AWS check which should failover nicely.
Attempt to run the script, whilst being logged out.
Not @paroxp

Correct failover when not logged into CF CLI

---

concourse/scripts/pipecleaner.py

When shellchecking scripts in the pipelines, pipecleaner inserts dummy
`export` statements for each of the `PARAMS` from the pipeline to prevent
shellcheck complaining about undefined variables. Because these were set
to the static string 'DUMMY', shellcheck wouldn't complain if they were
used unquoted in the scripts because it assumed their value was safe.
Inserting a call to `date` in these prevents shellcheck from assuming
they're safe.
Code review.

[pipecleaner] Don't assume dummy variables are safe.

---

vagrant/Vagrantfile

We've been running into the following error fairly regularly when
creating bootstrap instances:
```
InsufficientInstanceCapacity => We currently do not have sufficient
m3.large capacity in the Availability Zone you requested (us-east-1e).
Our system will be working on provisioning additional capacity. You can
currently get m3.large capacity by not specifying an Availability Zone
in your request or choosing us-east-1b, us-east-1c, us-east-1a.
```
Using a different AZ (which is determined by the subnet being used)
normally avoids this, which suggests that the capacity problems are
limited to a single AZ.
This PR also removes the IP ranges from the comments, as they're not useful.
Spin up a bootstrap concourse in dev. Verify this works without issue.
I don't think it'll be possible to know …

Change dev bootstrap AZ to avoid capacity issues.

---

manifests/cf-manifest/manifest/050-rds-broker.yml

In https://github.com/alphagov/paas-rds-broker-boshrelease/pull/16 we
renamed the broker boshrelease from aws-broker to rds-broker. As part of
this we also renamed the github repo. This should not have been a
problem because Github [automatically sets up redirects](https://help.github.com/articles/renaming-a-repository/) when you do
this. However, these redirects are a 301 Moved Permanently redirect,
and the bosh director only currently follows 302 redirects (see https://github.com/cloudfoundry/bosh/pull/1523 for
details)
It should be enough to verify that downloading from the new URL does not involve any 301 redirects, and that the resulting file has the correct SHA1 sum.

[#130188061] Fix aws-broker download URL

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/900-cf-tests.yml
manifests/concourse-manifest/concourse-base.yml

We want to speed up acceptance tests by enabling higher parallelisation.
The most stable configuration with huge reduction of tests run time was achieved with m4.xlarge VM type and 10 test nodes. Also we introduce 90 sec sleep time for `acceptance-tests` to spread initial load over time. Such config allows us to finish all tests suites in ~20 mins.
All test results and more reasoning: https://www.pivotaltracker.com/story/show/134551329 
Read, run bootstrap to re-provision concourse and run the CF deploy pipeline twice.
Second run of `acceptance-tests` should take ~20min.  
Not @saliceti or @combor

[#134551329] Parallelise acceptance tests

---

manifests/shared/lib/secret_generator.rb
manifests/shared/spec/secret_generator_spec.rb

We've run into yet another problem with how these passwords are being
represented in YAML. In this case, the password generated was a hex
string like '12345678e123'. The ruby YAML library output this unquoted.
The Go YAML library (as used in spruce) interpreted this as a number
with an exponent. After this has been through spruce, it comes out as
'.inf' (presumably because it gets stored in a float32 somewhere along
the way, and this value is larger than the max value that can fit in an
IEEE single precision floating point number). JSON doesn't allow
Infinity, so this causes an error in bosh when it tries to serialise the
manifest into its database.
Digging further, the YAML spec is unclear on how these are supposed to
be represented and matched. It says "These may be matched against a …

Add a static prefix 'p' to all generated passwords.

---

manifests/cf-manifest/manifest/050-rds-broker.yml

Now that we have the build concourse building these releases, we should update the pipeline to consume them instead of the existing temporary solution.
Note: as part of the work to move it to the build concourse, we also
renamed the boshrelease to match the broker.
Deploy. Verify it downloads the release successfully from the new location.

[#130188061] Use rds-broker boshrelease from the build concourse.

---

README.md
scripts/bosh-lite.sh
terraform/bosh-lite/README.md
terraform/bosh-lite/bosh-lite_aws.tf
terraform/bosh-lite/bosh-lite_security_groups.tf
terraform/bosh-lite/bosh-lite_ssh_key_pair.tf
terraform/bosh-lite/bosh-lite_subnet.tf
terraform/bosh-lite/bosh-lite_variables.tf
terraform/bosh-lite/bosh-lite_vpc.tf
terraform/bosh-lite/globals.tf

[#134910533 Make it easy to start a bosh-lite instance for local development](https://www.pivotaltracker.com/story/show/134910533)
Dependencies
------------
You need the VPC, subnet and SG to run this from: https://github.gds/government-paas/aws-account-wide-terraform/pull/67
What?
-----
We want to provide a easy way for the development team to setup a AWS bosh-lite instance.
The script allows to create and manage a bosh-lite instance on AWS[1][2]
This script features:
* create all the requirements: VPC, subnet, security groups, key pairs, etc. using terraform. The state is stored in the vagrant directory of bosh-lite.
* Deploys bosh-lite using vagrant on AWS.
* Updates the admin password to a random generated password.
* Provides info about the instance: public & private IPs, passwords. …

[#134910533] Add script to manage a bosh-lite instance

---

scripts/common.sh
scripts/create-user.sh
scripts/reset-org.py
scripts/reset-user-testing.sh
scripts/rotate-user-password.sh

[#130821719 Automate reset of User Research organisation after Lab Session](https://www.pivotaltracker.com/story/show/130821719)
Introduce a script to wipe and recreate the `paas_user_research` org
and to reset the passwords of the user testing users.
This will be run manually after each user research session, to ensure that the next session starts with a clean environment.
See https://www.pivotaltracker.com/story/show/130821719 and https://github.com/alphagov/paas-team-manual/pull/75
Either:
- review code and story summary and trust us that it works, or
- create an org in dev with some apps, services, and users, and run the script with appropriate modifications to see it for yourself, or
- ask @benhyland or @alext for a walkthrough
Anyone but @benhyland and @alext

[#130821719] User research org cleanup script

---

concourse/scripts/pipelines-bosh-cloudfoundry.sh

https://github.com/alphagov/paas-cf/pull/608 was played allowed verification of datadog keys when 
datadog is enabled. However, there was a problem as we wouldn't be able to delete datadog resources when we decide to disable datadog.
This now reads keys all the time, allowing deletion.
* code review should be fine
* else: build an environment with datadog enabled, rebuild with datadog disabled. It should delete what was created in datadog
Anyone but me

Read datadog secrets even when datadog is disabled

---

terraform/bosh/rds.tf
terraform/cloudfoundry/cf_rds.tf

Story: [Upgrade RDS instance versions](https://www.pivotaltracker.com/story/show/135224045)
We are not sure how the next upgrade will impact us and we are planning a major upgrade anyway in #135224045. This removes the unknown for now and we will decide if we want to re-enable it or not in that story.
* Deploy
* Check in the AWS console that the setting `Auto Minor Version Upgrade` is set to `No` for both BOSH and CF RDS instances
Anyone but me

[#135224045] Disable RDS auto minor version upgrade

---

manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/manifest/900-cf-tests.yml

What?
-----
The acceptance tests started failing due the java-buildpack using a newer minor version for tomcat (from 8.0.38 to 8.0.39), which changed the behaviour with special chars in the request. See #624 for details.
In this PR we want to use the java-offline-buildpack, which pins all the versions of the dependencies instead of allowing minor upgrades. This will allow us to better control the upgrades.
The commit will enable again the test.
We also simplify the buildpack a little bit.
How to test?
------------
* Code review
* The pipeline should pass. Trust us, let it run in CI ;)
Who?
---
Anyone but @keymon or @combor

[#135207089] Use java offline buildpack

---

Makefile
manifests/cf-manifest/manifest/800-logsearch.yml
manifests/cf-manifest/scripts/generate-cf-secrets.rb
manifests/shared/spec/fixtures/cf-secrets.yml
scripts/show-cf-secrets.sh
terraform/cloudfoundry/logsearch_elb.tf

https://www.pivotaltracker.com/story/show/115429827
Use HAProxy from the logsearch release to put http basic auth in front of Kibana.
- Deploy the branch
- Run `make dev showenv`, notice that `KIBANA_ADMIN_PASSWORD` is shown
- Visit the logsearch URL
- Verify that http basic auth is required, and that the creds `admin`/`<KIBANA_ADMIN_PASSWORD>` give access
not @benhyland

[#115429827] Enable basic auth for kibana

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
terraform/datadog/cell.tf
terraform/datadog/consul.tf
terraform/datadog/general.tf
terraform/datadog/nats.tf
terraform/datadog/router.tf

[Datadog: don't false alarm during deployment](https://www.pivotaltracker.com/n/projects/1275640/stories/133247209)
Reconfigure datadog checks so that we don't get false positives (alerts, no_data notifications) during BOSH deployments (when you e.g. rotate a stemcell).
Deploy environment with datadog enabled. Apply this branch. Then bump stemcell (e.g. change the number to 3263.10 in `manifests/cf-manifest/manifest/000-base-cf-deployment.yml` - you'll need to commit. To test that, create a branch from this branch and commit there, or you can add a temporary commit into this branch). Apply. There should be no false positive alerts.
Note that we have tested stemcell bump (to 3236.10) several times during development, with passing acceptance and custom acceptance tests. I think we could …

[#133247209] Datadog: don't false alarm during deployment

---

manifests/cf-manifest/cloud-config/020-cf-vm-types.yml
manifests/cf-manifest/cloud-config/021-cf-vm-extensions.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/manifest/900-cf-tests.yml
platform-tests/src/acceptance/cf_ssh_test.go

We'd like to enable the ssh functionality for our CF. The flag has been switched, and the tests are being corrected.
This also enables the upstream ssh tests in cf-acceptance-tests.
We've updated the `ssh-proxy oauth` config to match docs. This looks to have changed in newer releases since this was initially implemented. This scope is what the [documentation](http://docs.cloudfoundry.org/running/config-ssh.html#cf-manifest) says should be set.
We use `vm_extensions` to specify `access` VM ELB. This avoids the need to have an extra vm_type just to add the VMs to an ELB.
We make the `access` use a small VM. It's only proxying SSH connections, so doesn't need to be very big. Some crude load testing shows that this VM size is plenty (we managed to get a peak load average or 0.2)
- Run the …

[#127792523] Enable SSH for CF

---

manifests/cf-manifest/cloud-config/020-cf-vm-types.yml

Use new r4 instance type for cells instead of current r3.
We get:
* a bit more CPU performance
* faster memory and more cache (java apps seem to like this)
* quite faster network
* 20% cost savings
The cost savings are considerable as we run many of these VMs in prod and they are not the cheapest.
Total savings for all environments are ~$12K/year or 1k per month...
Deploy. Check that availability tests pass during VM upgrade. If you are paranoid, run the acceptance and custom acceptance tests (adds 20 mins to review time).
not @mtekel

Upgrade cells to new r4 instance type

---

Makefile
scripts/show-cf-secrets.sh

The `^^` uppercasing variable substitution is only available in bash 4+.
OS X still ships with bash 3.2. Changing this to use `tr` is less elegant,
but more portable.
This PR also adds `uaa_admin_password` to the list of variables returned.
This is used to login to dev deployments, and so is useful to have present here.
Verify that `make dev showenv` works without error.
Anyone running bash 3.2.

Fix showenv on old bash, and include uaa_admin_password

---

scripts/create-user.sh
scripts/rotate-user-password.sh

This was a copy/paste error from the rotate-user-password.sh script,
which uses USERNAME instead of EMAIL.
This also updates the printing of password to avoid any possible confusion around quotes and .
Test that you can create users in a dev deployment using the `--no-email` flag. eg:
```sh
./scripts/create_user.sh -o foo -e foo@example.com --no-email
```

[#130821719] Fix create_user.sh with the --no-email flag

---

manifests/cf-manifest/manifest/020-cf-properties.yml

The elastic search disk capacity has recently ben increased (https://github.com/alphagov/paas-cf/pull/627) but this is not enough as the quantity of logs always increases little by little. Now the disk space used on elastic search VMs is around 75% and causes frequent warnings.
Garden currently is set to default `info` log level. This includes a lot of debug like messages and this represents more than half the total quantity of logs.
By setting `error` we will reduce drastically the quantity of logs emitted.
- Check in kibana that there is a lot of logs emitted by garden and their relative usefulness
- Deploy with the branch
- Check garden logs are now minimal
Anyone but me

Set garden log_level to error

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/800-logsearch.yml
manifests/cf-manifest/spec/manifest/base_properties_spec.rb
manifests/cf-manifest/spec/manifest/logsearch_spec.rb
platform-tests/src/acceptance/s3_retention_test.go

We want to be sure that when a user stops using the service, their personal data is removed, and that any records of their actions/personal data in logs is automatically (programmatically) purged to facilitate a maximum 2-year retention period.
This PR adds tests around our retention period settings to ensure that when we change them such changes are reflected in our Privacy Policy document. 
Run the pipelene and check if deployment is no-op and all tests pass. 
not @combor or @keymon

[#122026001] Ensure that personal data is deleted as described in our policy 

---

scripts/cf_admin_login_dev.sh

In development we need to login as the cf admin user, which has an
autogenerated password which needs to be pulled out of the state bucket.
This script simplifies this process.
This is deliberately restricted to operate on dev only because we
should be using our individual user accounts in other environments.
* Verify that the script correctly logs you into a dev CF deployment.
* Verify that it fails with a helpful error when using AWS keys for a different account.

Add script to handle cf admin login in dev.

---

concourse/pipelines/create-bosh-cloudfoundry.yml
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
terraform/datadog/cell.tf

[#131375099 Check health of cell components](https://www.pivotaltracker.com/story/show/131375099)
What?
----
We want to monitor the processes rep and garden in the cells. In https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/6 we added the required checks to the host:
In this PR we use the new datadog-for-cloudfoundry release (we switch to final tar releases) and configure the monitors:
* Check if the processes rep and garden are running
* check if the rep service endpoint is responding in > 50% of the hosts
* Check if the garden debug endpoing is reponding in > 50% of the hosts.
Note that in the case of garden-runc the process is currently called guardian. Also, we only monitor the debug port of garden because the service socket is a unix socket that datadog does …

[#131375099] Add monitors for the Cell rep and garden services

---

terraform/cloudfoundry/cf_api_elb.tf
terraform/cloudfoundry/logsearch_elb.tf
terraform/cloudfoundry/metrics_elb.tf
terraform/cloudfoundry/router_elb.tf
terraform/concourse/elb.tf
terraform/globals.tf

Story: https://www.pivotaltracker.com/story/show/133036569
The default behaviour of Terraform is for the ELBs to get the
AWS default security policy at the time that the ELB is created. This
has led to our long-lived deployments having an older security policy,
which raises warnings in Trusted Advisor etc.
This therefore updates all ELBs that terminate SSL to use the latest
built-in AWS policy (2016-08).
Code sanity check. 
Run the pipeline and check if `cf-terraform` job applied new policies. 
Run bootstrap and check if Concourse ELB has been updated. 
Not @alext or @combor

[#133036569] Migrate to new ELB security policies

---

terraform/cloudfoundry/cf_api_elb.tf
terraform/cloudfoundry/logsearch_elb.tf
terraform/cloudfoundry/metrics_elb.tf
terraform/cloudfoundry/router_elb.tf
terraform/concourse/elb.tf
terraform/globals.tf

This has thrown errors for ELBs created prior to the change because the
policy needs to be attached to the ELB before it can be added to a
listener.
This reverts commit 2e96ba43717342b508de302f4515c2568704c282 (PR #647)
Verify that this does indeed revert the mentioned PR.

[#133036569] Revert "Specify ELB security policy for all ELBs"

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml

Upgrade CF to fix USN-3151-2
We're applying it first to the CF installation, which is at greater risk of being exploited, given it has local users.
https://www.cloudfoundry.org/usn-3151-2/
https://www.ubuntu.com/usn/usn-3151-2/
We agreed at standup that we will only code review and apply directly to CI.
Check that #649 has been merged first to unblock the pipeline.

Upgrade CF to stemcell 3263.12

---

terraform/cloudfoundry/cf_api_elb.tf
terraform/cloudfoundry/logsearch_elb.tf
terraform/cloudfoundry/metrics_elb.tf
terraform/cloudfoundry/router_elb.tf
terraform/concourse/elb.tf
terraform/globals.tf

The default behaviour if this is unspecified is for the ELBs to get the
AWS default security policy at the time that the ELB is created. This
has led to our long-lived deployments having an older security policy,
which raises warnings in Trusted Advisor etc.
This therefore updates all ELBs that terminate SSL to use the latest
built-in AWS policy (2016-08).
We previously attempted this in #647, but had to revert. This was due
to a misunderstanding about how these policies work. An ELB has one or
more policies defined for it. Each SSL listener then has one of these
policies attached to it. The previous commit failed because we were
attempting to attach a policy to the listeners that didn't exist on the
ELB.
To test this properly, it's necessary to have an ELB configured with an old policy …

[#133036569] Set ELB security policies (take 2)

---

manifests/bosh-manifest/bosh-manifest.yml
manifests/concourse-manifest/concourse-base.yml

[Apply USN-3151-2 everywhere](https://www.pivotaltracker.com/n/projects/1275640/stories/135801295).
To apply the security fix, we need to upgrade stemcell used by concourse and BOSH. We have decided to upgrade to the same version as CF uses currently.
Apply. You can either watch (and trust) the output from bosh-init, which should say `Uploading stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3263.12'...` or ssh to bosh/concourse (`make dev ssh_bosh`/`make dev ssh_concourse`) and watch logs of bosh agent, which reports which stemcell it thinks the VM is running - and trust this information. Logs are located in `/var/vcap/bosh/logs` and it should look like `[App] 2016/12/09 11:35:15 INFO - Running on stemcell version '3263.12' (git: 41edff6464246431d6440b2446bb9cc5f872167f+)`
not @mtekel

[#135801295] Upgrade stemcell for BOSH and Concourse

---

tools/paas_dashboard/README.md
tools/paas_dashboard/dashboards/paas-overview.erb

Link to triggered monitors, rather than the managed monitors, so I can quickly see a list of things making an environment not be green.
Add instructions for running the dashboard locally because I wanted to do that to make this change.
- Follow the links and make sure they link to the right places
- Test the instructions for running locally
Not me

Make dashboard link to triggered alerts

---

terraform/cloudfoundry/metrics_elb.tf

The destroy failed because both listeners were referencing the same policy.
Destroying the first resource failed because it attempted to delete the
policy as well as the attachment, but the policy was still in use by the
other listener.
Using a policy per listener avoids this conflict.
Deploy from this branch as far as cf-terraform. Run the destroy-cloudfoundry pipeline, and verify it succeeds.

[#133036569] Fix TF destroy for Metrics ELB.

---

manifests/cf-manifest/spec/manifest/base_properties_spec.rb
manifests/cf-manifest/spec/manifest/logsearch_spec.rb

This is follow up for: https://www.pivotaltracker.com/story/show/122026001/comments/157906483
As we agreed that we are not going to mention our current retention
period in Privacy Policy it would be confusing to leave such info in
tests. Instead tests mention that we expect to have retention period set
to N days.
Check if changes are sane. This should be no-op deployment so we can leave it for CI Concourse to test. 
not @combor

[#122026001] Remove Privacy Policy info from tests

---

tools/paas_dashboard/jobs/datadog.rb
tools/paas_dashboard/widgets/health/health.html

https://www.pivotaltracker.com/story/show/134267945
We want to handle the situatoin where our dashboard gets an error from the datadog api,
but still displays green on the dashboard.
We will
- display the last recorded event, rather than setting all error counts to 0
- after 15mins of not being able to see good data, display an error condition
We set the `silent` flag false on the dogapi client, so that it throws
an error we can handle when it can't get a good response from datadog.
We handle that error by testing whether the last good event is stale
- if it is, we emit an error, if not, we display the old data for a
while in case the error is transient.
Start the dashboard locally, see the readme for how.
Wait 20secs, stop the dashboard.
Observe recent events appear in the local …

[#134267945] Error handling for smashing dashboard

---

scripts/reset-org.py
scripts/reset-user-testing.sh

We'd switched on some `nargs=*` for argparse without correcting the
wrapping bash script.
Presumably this is the first time we ran the org cleanup via that
script in its current form, since the last user research session went OK.
Review by @henrytk

Fix mistaken args in user research cleanup script

---

Makefile
scripts/create_sts_token.sh
scripts/validate_aws_credentials.sh

In [another PR](https://github.gds/government-paas/aws-account-wide-terraform/pull/68) we enforce users to have MFA enabled using an IAM policy that blocks all access to AWS if a token has not been registered. Because regular AWS keys are not MFA'd, any request made using them will be blocked by the policy.
The solution to this is to move to [security tokens](http://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html) which are MFA'd, and are issued using the regular AWS keys. These tokens are time-limited with a maximum lifetime of 36 hours, however we set the expiry to 12 hours so they last a working day.
This PR introduces tooling that both checks you have valid keys before running Make tasks, and tooling to issue & cache tokens.
We acknowledge that the interaction with this …

[#126126973] Tooling to use STS tokens once we enforce MFA

---

Makefile

This check is useful in dev, but breaks permanent envs since
self-update-pipelines runs the make target directly.
We can figure out how to gracefully run this check in dev only
some other time.

Remove aws cred check from pipelines make target

---

Makefile

Remove the usage of the `check-aws-credentials` task, as it breaks more things than it should.
Run your everyday routine and see if you're not bothered by some error message contained in `scripts/validate_aws_credentials.sh`.
No more task usage occurrences should appear.
Not @paroxp

Remove usage of the check aws credentials task

---

scripts/reset-user-testing.sh

**Note:** Re-opened based on https://github.com/alphagov/paas-cf/pull/665 from @keymon , which was targeted against a branch which no longer exists.
Allow override the hardcoded values, so at least is easier to run this script in a development environment without issues.
For example:
for i in `seq 1 6`; do ./scripts/create-user.sh -o paas_user_research -e hector.rivas.gandara+$i@digital.cabinet-office.gov.uk; done
DEPLOY_ENV=hector TARGET_EMAIL_USER=hector.rivas.gandara TARGET_ENVIRONMENT=dev TARGET_ENVIRONMENT_API=api.hector.dev.cloudpipeline.digital scripts/reset-user-testing.sh

Allow override values in reset-user-testing.sh

---

concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
terraform/datadog/cloud_controller.tf

[#134345035 Monitor cloud controller job](https://www.pivotaltracker.com/story/show/134345035)
What?
-----
We want to monitor elementary health metrics of the cloud controller to help us diagnose the issues and warn us in advance if there are problems with platform. This story is about monitoring on the VM directly, there are other stories to monitor API on high level (e.g. externally).
This PR uses the feature from https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/7 to implement datadog monitors for the Cloud Controller API main process and workers and the CC HTTP endpoint.
We add some monitors for the Cloud Controller metrics from the CF datadog
nozzle:
* `cf.cc.failed_job_count.total`: alert if there were an increase of more than 5 errors in the last 30m.
* …

[#134345035] Add Cloud Controller process checks and monitors

---

manifests/cf-manifest/manifest/010-cf-jobs.yml
terraform/datadog/route-emitter.tf

[#131375807 Check health of route emitter component](https://www.pivotaltracker.com/story/show/131375807)
What?
----
We want to monitor the route_emitter as we do with other processes.
There are also [several metrics from the CF Datadog nozzle](https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/8). After testing we decided to monitor:
* The process is running
* The process opens the debug port.
* The consul lock is held:
* Local check in each route_emitter, querying http://localhost:8500/v1/kv/v1/locks/route_emitter_lock
* The metric sent by CF Nozzle: `cf.route_emitter.LockHeld.v1-locks-route_emitter_lock`
* ~~The gorouter and the route_emitter total routes match~~
* ~~We need to take into account LRPs that are not running. They are in route-emitter but not in …

[#131375807] Add Route Emitter process and metrics checks and monitors

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml

Story: [Upgrade cflinuxfs2 stack](https://www.pivotaltracker.com/story/show/136187337)
Update to the latest version and address the following vulnerabilities:
* https://www.cloudfoundry.org/usn-3123-1/
* https://www.cloudfoundry.org/usn-3134-1/
* Deploy and make sure acceptance tests pass
* Get someone to review and send the email to tenants: https://hackmd.io/EYdgDAhgpgJgnHAtADgIyoGaICyoMxbBwBMeieeCIAbMgMbUCsjMQA==
Not me

[#136187337] Update cflinuxfs2 stack to 1.94

---

concourse/pipelines/destroy-deployer.yml

As part of the process for migrating to paas-bootstrap we need to
destroy the concourse instance, but not run the concourse terraform
destroy. Splitting this job into 2 separate jobs will allow us to
accomplish this by pausing the destroy-terraform job.
Code review.
Fire up a bootstrap-concourse and check the pipeline looks correct.
Anyone but @dcarley or myself.

[#131876783] Split destroy-concourse job in destroy pipeline.

---

manifests/cf-manifest/manifest/020-cf-properties.yml

[#136189211 Increase number of api workers ](https://www.pivotaltracker.com/story/show/136189211)
What?
Datadog is alerting about high number of jobs in the CF api queue[1] while  the tests run. It seems that after increase the paralelism #614 in the tests the load on the API increased.
Checking the CPU and load of the APIs, we found that currently the load on the CC worker VMs is:
* api: ~50% CPU and ~0.5 load during tests
*  api workers: ~25-30% CPU and ~0.3 load.
Currently we run:
* api: 1 main process, 2 workers
* api_worker: 1 workers
In this PR we increase this to:
* api: 1 main process, 3 workers
* api_worker: 3 workers
[1] https://app.datadoghq.com/event/event?id=3649877123650295918 both in CI as in staging.
How to review?
-------------
Check that the changes make sense. …

[#136189211] Increase number of CC workers to 3 per VM

---

concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh
manifests/cf-manifest/manifest/000-base-cf-deployment.yml

Currently we capture the access log of the HAProxy in front of our gorouters.
Today I was troubleshooting some spike in the request latency, and I wanted to check the access log from the HAProxy in logsearch. But I found out that I could not correlate the requests with the applications because the log messages do not include the Host header.
That is valuable information, but in order to identify for which application each request is, we need to log the Host header.
We will use the paas-haproxy bosh release PR in https://github.com/alphagov/paas-haproxy-release/pull/7
We also migrate this bosh release to the PR based builds (see https://www.pivotaltracker.com/story/show/132745311)
Dependencies
-----------
Depends on https://github.com/alphagov/paas-haproxy-release/pull/7 which should be …

[#SUPPORT] Add the Host header to the HAProxy logs

---

tools/paas_dashboard/README.md

Small typo in the link to the paas dashboard. Also changed it to a link
so when viewing in web interface it is clickable

Fix link to paas-dashboard

---

terraform/ci.tfvars
terraform/datadog/router.tf
terraform/staging.tfvars

What?
-----
The `router_routes_drop` monitor get easily triggered when running the tests in environments with little routes, like ci or staging.
We do not need to monitor this on those environments, but it is still useful in prod. We can also keep it in dev for testing/development.
> Note: as we add `count`, it will actually recreate the monitor in prod, because the ID changes (add a .0 suffix). That is fine and expected.
How to test?
------------
You can apply these monitors in dev like this:
```
PAAS_CF_DIR=$(pwd)
mkdir /tmp/testing_tf
cd /tmp/testing_tf
ln -s ${PAAS_CF_DIR}/terraform/datadog/{datadog.tf,variables.tf,router.tf} .
terraform apply -var datadog_api_key=$(paas-pass datadog/dev/datadog_api_key) -var datadog_app_key=$(paas-pass datadog/dev/datadog_app_key) -var …
```

[#SUPPORT] Only enable routes drop monitor in dev and prod

---

scripts/create-user.sh

When creating a user with the email address firstname.o'lastname@domain
this script would previously report that the email address was invalid.
Since I wanted to create such a user I needed to make the script accept email addresses with apostrophes in them.
Ask a friendly colleague with an apostrophe in their email address if they mind getting a bunch of emails and test against your development environment.

Allow apostrophes in tenant email addresses

---

terraform/datadog/cloud_controller.tf

What?
----
Since we increased the number of jobs in parallel in the tests in #614, the CC queue length monitor gets triggered often, specially in CI and staging.
But that monitor is too sensitive, as it gets triggered if any value in the last 30 minutes is more that 6 or 10. We change this to alert when the average on the last 30 minutes, making the monitor resilient to spikes. We will still detect if jobs get stuck for too long.
I also increase the warning to 7 because some of the lastest runs of acceptance tests in CI got an average in 30m above 6.
How to review?
----------
Check that makes sense. Optionally follow the steps in #677 to test only the monitors.
Who?
----

[#SUPPORT] CC queue length monitors the avg in last 30m

---

manifests/bosh-manifest/bosh-manifest.yml
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/concourse-manifest/concourse-base.yml

What 
----
[Response to USN-3156-1](https://www.pivotaltracker.com/story/show/136504507)
This contains a fix for [USN-3156-1][1]. The fix was present in the
3263.13 stemcell release, but there seems to be no reason not to update
to the latest stemcell
[1] https://www.ubuntu.com/usn/usn-3156-1/
How to review
-------------
* Check that the change makes sense (urls, hash)
* redeploy concourse and redeploy the environment and check that the changes apply and acceptance tests pass
Who can review
-------------
Anyone but me

[#136504507] Upgrade stemcells to 3263.14

---

concourse/scripts/pipelines-bosh-cloudfoundry.sh

We upload the Pivotal tracker API token to S3 when we deploy
rubbernecker. But when we don't deploy it, the pipeline would wait
forever for a token even if we don't need it.
This quick fix uploads a fake token.
Code review
Not me

[#136340183] Rubbernecker fake token fix

---

Makefile
concourse/pipelines/create-bosh-cloudfoundry.yml
concourse/scripts/pipelines-bosh-cloudfoundry.sh

Story: [Productionnecker](https://www.pivotaltracker.com/story/show/136340183)
The previous behaviour broke in production as the token was never
uploaded to the bucket and the deploy rubbernecker task would wait
forever.
We now use the same approach as for the datadog secrets: the token is
uploaded manually via a make command then retrieved and set as a
pipeline parameter.
* Code review or:
* Standard deploy. It shouldn't deploy rubbernecker
* Upload pivotal tracker token: `make dev upload-tracker-token`
* Deploy with `DEPLOY_RUBBERNECKER=true`. It should deploy it.
Not me

[#136340183] Change tracker token management

---

manifests/cf-manifest/spec/runtime-config/shared_config_spec.rb
manifests/shared/deployments/datadog-agent.yml

[#131876783 Migrate paas-cf to paas-bootstrap](https://www.pivotaltracker.com/story/show/131876783)
What?
----
We have the plan to split the different deployments (concourse, CF, etc), using the same bosh. This means that we cannot identify each specific environment base on the bosh-deployment tag, as we were doing previously because it was set with the value $DEPLOY_ENV.
Specifically, when migrating to paas-bootstrap, the the deployment of concourse is "concourse" for all the environments. Because that we cannot identify the concourse VM per environment and the monitor do not work anymore.
To solve this, we add the tag `deploy_env`. This will allow us to filter by deploy_env without relying on the bosh   deployment name.
More info: …

[#131876783] Add deploy_env as a tag for datadog

---

concourse/pipelines/create-cloudfoundry.yml
terraform/datadog/cell.tf
terraform/datadog/cloud_controller.tf
terraform/datadog/concourse.tf
terraform/datadog/consul.tf
terraform/datadog/general.tf
terraform/datadog/nats.tf
terraform/datadog/route-emitter.tf
terraform/datadog/router.tf

[#131876783 Migrate paas-cf to paas-bootstrap](https://www.pivotaltracker.com/story/show/131876783)
What?
----
With the migration to paas-bootstrap we want to manage multiple deployments from the same bosh. That prevents us from using bosh-deployment tag to uniquely identify the environment.
We added instead the tag deploy_env which identifies the environment.
In this commit we stop using the bosh-deployment tag, and we use deploy_env.
The metrics from the datadog agent will have the tag from the changes done in [1] and the concourse ones from [2]
[1] https://github.com/alphagov/paas-cf/pull/696y
[2] https://github.com/alphagov/paas-bootstrap/pull/8
Dependencies
------------
It is convenient that https://github.com/alphagov/paas-cf/pull/696 has been deployed some time before in all …

 [#131876783] Use deploy_env instead of bosh-deployment

---

manifests/cf-manifest/grafana/user-impact.json

What?
-----
In the grafana dashboard we plot the 90 percentile of the both routers, so we can spot deviations in the response time.
But that graph has several problems that make it not useful:
* The metric is calculated and generated every 10 seconds, but we plot a total of 12 hours. The graph is really spiky and noisy.
* Sometimes there are very little requests and some really slow but expected requests happen, that appear in the graph. For instance, the /events in a dashing dashboard which takes 900s. As we plot linearly, that causes the graph to get out of scale.
* We don't plot the maximum request time, only 90 percentile.
In this commit we propose the following changes:
* summarise all routers using max. The intention of the graph is highlight an issue, if one router is misbehaving, …

[#SUPPORT] Plot summarised router response times

---

manifests/cf-manifest/grafana/user-impact.json

What?
----
In the grafana dashboard we plot the tenant's app and CC requests rate and 4xx and 5xx rate, so we can understand the normal traffic rate and spot rise in errors.
The metric is generated with a resolution of 10s, but we plot a total of 12 hours. Because that the graph is really spiky and noisy.
A solution would summarise the metric in a 1 minute window, creating a more smooth and easy to read metric.
In the case of app requests, to do so, we use the count of requests instead of the rate. We sum the values from all the gorouters, and then summarise in 1m window using sum. Finally we scale to seconds, as the metric is reported every 10s.
Screenshoot before
and
Screenshoot after
----------------
and 
How to test
-----------
Go to any grafana and import the file …

[#SUPPORT] Plot summarised app requests rate

---

terraform/datadog/general.tf

We have previously removed concourse specific monitor in
b2f63b7f2befd0a1063c24cb5d44e3dc97d070b7 but forgot to remove condition to
exclude concourse from generic disk monitor. Remove that exclusion to cover
concourse disks as well
Deploy. Check disk monitor covers concourse disks as well.
not @mtekel

[#136433665] DATADOG: monitor concourse disk

---

terraform/datadog/cloud_controller.tf

Since increasing the parallelisation of our acceptance tests we have
seen higher spikes in the `cf.cc.job_queue_length.total` metric, resulting
in our monitor for CI being triggered (staging and production do not
currently run the acceptance tests).
We increase the thresholds to eliminate these false alerts. Some minor
investigation was done[1] to make sure the relevant components (api,
cells) are coping with the increased load and the alerts really are
false.
[1] https://www.pivotaltracker.com/story/show/137092871
The code review required is almost nil. However, the real test is that we don't get false alerts during deployments. I recommend waiting for several deploys to happen and for us to retrospectively look over Datadog to ensure the monitors weren't triggered.
Anyone but me.

[#137092871] Increase thresholds for job queue length monitor

---

terraform/datadog/cloud_controller.tf

This value should have matched the critical threshold. Datadog will
refuse to update the monitor, but provides no useful information on
why it fails.
To be reviewed as https://github.com/alphagov/paas-cf/pull/706
@keymon

Bugfix: update monitor query

---

README.md
concourse/pipelines/create-cloudfoundry.yml
concourse/scripts/environment.sh
concourse/scripts/pipelines-bosh-cloudfoundry.sh
concourse/scripts/self-update-pipeline.sh

Story: [Ensure all AWS IAM accounts have MFA enabled](https://www.pivotaltracker.com/story/show/126126973)
This PR brings adjustments required to be compliant with changes introduced in https://github.com/alphagov/paas-bootstrap/pull/16. It changes the way how CONCOURSE_ATC_PASSWORD is fetched. Now we get it from `concourse-sectrets.yml` from S3 bucket. Also, it unifies the way we get ATC password in create CF pipeline ( where possible )
- make sure `make dev showenv` displays correct ATC password
- run pipeline to check if all jobs are OK
Not @combor or @saliceti 
You can review it now and don't have to wait for https://github.com/alphagov/paas-bootstrap/pull/16 to be merged.

[#126126973] Fixes for require mfa

---

Makefile
concourse/scripts/environment.sh

Story: [Ensure all AWS IAM accounts have MFA enabled](https://www.pivotaltracker.com/story/show/126126973)
The concourse password is now stored exclusively in S3. We shouldn't try
to read it from GPG anymore.
Code review
Not me

[#126126973] Remove concourse password gpg decrypt

---

scripts/create_sts_token.sh

There's nothing about the generated credentials that is specific to a given
`DEPLOY_ENV`, so there's no need to base the generated files on it.
Additionally, `DEPLOY_ENV` doesn't make sense in contexts that are wider
than a given deployment (eg account-wide terraform). This therefore removes
the use of `DEPLOY_ENV` from the script.
A second commit also improves the error handling (a Ctrl-C would leave an incomplete token file behind).
Code review. Verify that the script still works.
Verify that the corresponding documentation change (https://github.com/alphagov/paas-team-manual/pull/85) also is correct.

Don't require DEPLOY_ENV in create_sts_token.sh

---

manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/scripts/generate-cf-secrets.rb
manifests/shared/spec/fixtures/cf-secrets.yml

This is the first step of BBS encryption key rotation. It replaces the hardcoded passphrase with generated one. Old pass is not removed as in this phase it will be used to decrypt already encrypted data. New one will be than used to re-encrypt everything and put back in ETCD. There will we a follow up PR to remove old pass after this change is deployed to all environments. 
- code sanity check
- deploy and wait for acceptance tests to pass 
not @combor

[#136351753] Rotate BBS encryption key

---

manifests/cf-manifest/manifest/020-cf-properties.yml

This is follow up to https://github.com/alphagov/paas-cf/pull/710 which has to be applied first to all environments. 
Hardcoded BBS pass phrase can be now removed from cf-manifest as we use generated one.  
More details in: https://www.pivotaltracker.com/story/show/136351753
- code sanity check
- run pipeline and wait for acceptance tests to pass.
Not @combor

[#136351753] Remove hardcoded BBS pass

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml

8e06c54 should not have been merged to master as it points to a development release. This commit updates it to point to the final datadog boshrelease.
Check the release URL is valid & hash is correct, if you must.
Not @jonty.

Update accidental dev datadog boshrelease pointer.

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/020-cf-properties.yml

Story: [How do encrypt traffic between the elb and gorouter using haproxy](https://www.pivotaltracker.com/story/show/136783629)
As part of DIT onboarding, we want to encrypt all communications. This PR enables SSL on HAProxy.
The following PR https://github.com/alphagov/paas-cf/pull/715 will change the backend port on the ELB to use this SSL port. It was separated in 2 PRs to create minimal downtime.
Depends on https://github.com/alphagov/paas-haproxy-release/pull/8
* Deploy
* Make sure all tests pass
* Merge https://github.com/alphagov/paas-haproxy-release/pull/8
* Copy the output from the `build-final-release` job at https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-haproxy
* Update commit `[TEMP] Use haproxy release with SSL` with the final release
* Merge
Not …

[#136783629] SSL between router ELB and HAProxy

---

terraform/cloudfoundry/router_elb.tf

Story: [How do encrypt traffic between the elb and gorouter using haproxy](https://www.pivotaltracker.com/story/show/136783629)
As part of DIT onboarding, we want to encrypt all communications.
This PR follows https://github.com/alphagov/paas-cf/pull/713 and changes the backend port on the ELB to use this HAProxy SSL port.
* Rebase `136783629_enable_ssl_haproxy_2` on `136783629_enable_ssl_haproxy` branch in a temporary branch
* Deploy from the temporary branch
* Make sure there is no unencrypted traffic between ELB and HAProxy (port 443)
* Make sure all tests pass
* Merge https://github.com/alphagov/paas-cf/pull/713
* Rebase `136783629_enable_ssl_haproxy_2` on `master`
* Merge
Not @keymon or me

[#136783629] Send router ELB traffic to HAProxy SSL port #2

---

manifests/cf-manifest/manifest/020-cf-properties.yml

Great! It looks like IPSec has been deployed in `ci`, `staging` and `prod`, right?
As a follow up to #684, we'd like to require the use of IPSec between the enabled nodes.
In the previous PR, IPSec level has been set to `use`, which means we can avoid any downtime. It is recommended to be set to `require`, hence this PR.
Level `require`, forces the traffic to use IPSec but it also drops any connection not using it.
- **Make sure you're happy with the IPSec being already successfully deployed to all the environments.**
Anyone but @combor or @paroxp

[#131802383] Make sure we require the IPSec at all times

---

terraform/datadog/cve.tf
terraform/datadog/variables.tf
terraform/prod.tfvars

Story: [Review & improve CF CVE notifications](https://www.pivotaltracker.com/story/show/136550911)
Reintroduce the datadog CVE monitor, based on the RSS feed from cloudfoundry.
This branch has `[TEMP]` commits to help with review. Update if required and delete after testing.
* Update email in commit `[TEMP] Send to test email address`
* Deploy (no need to enable datadog)
* Send a test event:
```
$ export DD_API_KEY=$(gov-pass datadog/dev/datadog_api_key)
$ curl  -X POST -H "Content-type: application/json" \
-d '{
"title": "CVE-2016-1234: Cloud Foundry is not so secure",
"text": "Bla bla bla bla bla",
"priority": "normal",
"tags": ["service:pivotal"],
"alert_type": "info",
"source_type_name": "feed"
}' \
"https://app.datadoghq.com/api/v1/events?api_key=${DD_API_KEY}"
```
* Take note of …

[#136550911] Reintroduce CVE monitor

---

manifests/cf-manifest/manifest/050-rds-broker.yml
manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
platform-tests/src/acceptance/rds_broker_test.go

[#136725001 Enable at rest encryption for broker created RDS DB instances](https://www.pivotaltracker.com/n/projects/1275640/stories/136725001)
What?
-----
We want provide the option of provision DBs with Storage Encription enabled. This is a requirement for DIT onboarding.
At rest encryption has been mentioned as a good thing to turn on by our AWS account manager.
As explained in the ADR: https://github.com/alphagov/paas-team-manual/pull/88 , we decided to provide additional explicit plans with Encryption enabled, and keep the old ones. We will add logic in the broker to prevent updates between plans with or without encryption. We only add to the HA plans, as removing plans later is painful.
In this PR we add two plans based on the Medium and Large HA plans.
We upgrade the RDS broker to …

[#136725001] Add plans with Storage Encryption enabled

---

scripts/create-user.sh
scripts/rotate-user-password.sh

When we create a user or rotate their password, we want to send email from
the support address, so that when they respond, it goes to support and there
is someone to deal with it.
You can try creating users or rotating some passwords. Either create a dummy user or you can even rotate your own PW. **NEVER rotate PWs of other people** unless requested! Or you can trust me. You can also check that the support address is now verified: `aws ses get-identity-verification-attributes --identities gov-uk-paas-support@digital.cabinet-office.gov.uk`
not @mtekel

Change user facing email address in user scripts

---

manifests/cf-manifest/spec/cloud-config/compilation_spec.rb
manifests/cf-manifest/spec/cloud-config/networks_spec.rb
manifests/cf-manifest/spec/cloud-config/vm_types_spec.rb
manifests/cf-manifest/spec/integration/integration_spec.rb
manifests/cf-manifest/spec/manifest/secret_generation_spec.rb
manifests/cf-manifest/spec/support/manifest_helpers.rb

This is a follow-up to #724:
Now that we're generating the secrets for the tests, there's no need to separately generate them for the yaml lint check.
I've taken the opportunity to separate the cloud-config from the manifest in the tests to make it clearer what comes from where.
Code review. Verify tests pass in travis.

[#137698283] CF manifest tests cleanup

---

concourse/pipelines/create-cloudfoundry.yml

[Restrict graphite access to the graphite-nozzle app only](https://www.pivotaltracker.com/n/projects/1275640/stories/119089085)
Make graphite nozzle SG available only to admin/admin org/space, where the graphite nozzle lives.
Checkout branch. Make dev pipelines. If you are on recent master, just run cf-deploy job: `JOB=cf-deploy make dev run_job`. Observe graphite-nozzle SG being added only to admin/admin org/space and removed from globals. Run the job again to confirm it's idempotent. Confirm you still get CF metrics by e.g. going to graphite or grafana and viewing any cf metric.
Create a test user `cf create-user test testtest`. Make them admin of e.g. testers. Log in as this user. Verify that you can't see graphite-nozzle SG.
not @mtekel

[#119089085] Private graphite SG

---

concourse/pipelines/create-cloudfoundry.yml

After #727 is merged and applied, we no longer need to keep unbinding the graphite nozzle sg. This PR fixes that.
Checkout, make dev pipelines, run cf-deploy job, observe that graphite-nozzle group is no longer being removed from global running and staging SGs.
not @mtekel

[#119089085] Stop graphite nozzle sg cleanup

---

manifests/cf-manifest/cloud-config/021-cf-vm-extensions.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/scripts/create-cf-dbs.sh
manifests/cf-manifest/scripts/generate-cf-secrets.rb

Story: [Migrate Diego to use a Relational Datastore](https://www.pivotaltracker.com/story/show/136100681)
Create a new RDS DB for BBS and configure BBS to use it.
Triggers the data from ETCD to be migrated to the DB.
* Deploy from master
* Deploy from the branch
* The migration takes a few minutes when the database VM is being updated
* Check for `bbs.migration-manager.finished-migrations` in BBS log. If you use logsearch, look for `migrations`.
* Check for lrps in BBS DB ([see comment](https://github.com/alphagov/paas-cf/pull/721#issuecomment-273091264) on where to run this from):
`psql -d bbs -h "${db_address}" -U bbs -W -c 'select * from actual_lrps '`
* Check via `cfdot` by `bosh ssh database/0` and running `source /var/vcap/jobs/cfdot/bin/setup && cfdot desired-lrps`
* Check all …

[#136100681] Add Postgres DB for BBS

---

manifests/cf-manifest/manifest/020-cf-properties.yml

⚠️  Depends on PR https://github.com/alphagov/paas-cf/pull/721 ⚠️ 
Story: [Migrate Diego to use a Relational Datastore](https://www.pivotaltracker.com/story/show/136100681)
BBS has now migrated to postgres, we don't need ETCD anymore.
* After https://github.com/alphagov/paas-cf/pull/721 is merged, rebase this branch on master
* Deploy from master
* Make sure all tests pass
Not @combor or me

[#136100681] Remove ETCD configuration for BBS

---

terraform/bosh-lite/bosh-lite_security_groups.tf
terraform/cloudfoundry/logsearch.tf
terraform/cloudfoundry/security-groups.tf
terraform/globals.tf
terraform/prod.tfvars
terraform/staging.tfvars

Add Notify's egress IPs to the API whitelist so they can gather metrics (Deskpro #3271).
I've taken the opportunity to refactor our CIDR lists to use terraform arrays (thanks to suggestion from @keymon), which makes them much clearer.
Code review - verify that the updated list contains the same data as the original list + the 6 new notify IPs.
I've added a `[TMP]` commit to ease testing the new syntax in dev. Deploy to dev and verify that the security group rules look correct.
Remove the `[TMP]` commit before merging.

[Support] Whitelist notify IPs

---

terraform/cloudfoundry/cf_rds.tf

This is currently using 9.4.5, and will be forcibly upgraded by Amazon at the beginning of February if not upgraded before then. This therefore upgrades to 9.5.4 ahead of this.
Use a temporary commit to set `apply_immediately = true` for this instance. Run the pipeline and verify that the changes apply successfully.
I have tested this with a multi-AZ instance, and didn't observe any downtime in the availability tests.
🚨 Note: This should only be merged on a **Monday, Thursday or Friday** due to the way the maintenance windows are staggered (see #732).

[#135224045] Upgrade CF RDS instance to 9.5.4

---

manifests/cf-manifest/manifest/010-cf-jobs.yml
terraform/datadog/cell.tf

[#135948443 Upgrade CF from v245 to v250](https://www.pivotaltracker.com/story/show/135948443)
What?
----
Fix some lose ends in the CF upgrade. We did not spot them until reaching CI because we did not test the integration with datadog :(.
So far this PR will:
* Restore metron_agent in CC vms
* Remove an obsolete monitor for garden
How to review?
-------------
Code review should be enough.
Dependencies
------------
We will do another PR in datadog-for-cloudfoundry to remove the check on the debug endpoint of garden
Who?
---

[#135948443] Lose ends in upgrade to cf-release v250

---

concourse/pipelines/create-cloudfoundry.yml
concourse/pipelines/failure-testing.yml

[#135948443 Upgrade CF from v245 to v250](https://www.pivotaltracker.com/story/show/135948443)
What?
-----
Pin cf-release with paas-cf from cf-deploy
Note: this commit is aligned with the change to pin the `get`
of cf-release in the commit 3f623b1
Although it is not directly being used by the cf-deploy job, we pin the
version of cf-release using the `get.version` syntax[1] in that job.
We must define it as a input to prevent the pipechecker from failing:
```
==  paas-cf/concourse/pipelines/create-cloudfoundry.yml  ==
WARNING * Unused Fetch: job='cf-deploy', resource='cf-release'
make: *** [lint_concourse] Error 20
```
With this commit we maintain the consistency of the deployed paas-cf with
the deployed version of cf-release using the `passed` tag based on the
version pulled during the …

[#135948443]  Pin cf-release with paas-cf from cf-deploy

---

manifests/cf-manifest/manifest/020-cf-properties.yml

If this is too low we risk triggering a deadlock in bbs due to a bug in
bbs itself. We believe the bug is the on fixed in
https://github.com/cloudfoundry/bbs/commit/b33de3b07ed47077b6afbb3ad1a8331cee4c8b85.
At the time of writing, this has not yet been released.
Code review.

Bump bbs database max_open_connections to 40

---

manifests/cf-manifest/manifest/020-cf-properties.yml

We previously bumped this to 40 in 5b77529 to avoid triggering a
deadlock in bbs caused by [1]. This has proved insufficient as are still
seeing occasional deadlocks. Even with the limit set to 150, I've still
managed to trigger the deadlock in a dev environment by rapidly scaling
an app up to a large number of instances (`cf scale debug-app -i 400`
for example). It's still worth increasing the limit though as it will
reduce the likelyhood of these occurrences.
The RDS instance has max_connections set to 198, so setting the limit
for bbs to 150 still leaves headroom for the other components that use
this instance. We've observed the other components (cloudcontroller and
uaa) typically using c. 30 connections.
[1]https://github.com/cloudfoundry/bbs/commit/b33de3b07ed47077b6afbb3ad1a8331cee4 …

[#135948443] Increase BBS DB max_connections to 150.

---

concourse/pipelines/create-cloudfoundry.yml
concourse/tasks/custom-acceptance-tests-run.yml
concourse/tasks/smoke-tests-run.yml

We don't pin our container versions, so in https://github.com/alphagov/paas-cf/pull/735 we had to merge a temporary commit to avoid breaking deployments in our persistent environments when https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/83 gets merged.
Merge order:
* https://github.com/alphagov/paas-cf/pull/735 and wait until it is deployed in all environments.
* https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/83
* rebase and merge this pull request.
Review by pinning the latest cf-acceptance-tests and running the pipeline, but you shouldn't have to if you have high confidence the thing pinned in https://github.com/alphagov/paas-cf/pull/735 is the same thing as currently on paas-docker-cloudfoundry-tools master (in Docker Hub).
Anyone but me or @keymon

 [#135948443] Revert pinning of CATS container

---

terraform/cloudfoundry/cf_rds.tf

🚨  **DO NOT MERGE** until the upgrade has applied to all environments - production is scheduled to be applied between 4-5am on Thursday 26th, and any pending dev environments will be applied the following Monday (30th)
The parameter group had to be left in place from the upgrade (#734)
because the upgrade wasn't applied immediately, instead it was applied
in the defined maintenance window for the instance.
Now that the upgrade has been applied, the old parameter group can be
removed.
Similarly, we no longer need to set allow_major_version_upgrade because
the upgrade has completed.
Code review.
Verify these changes apply cleanly to a deployed environment.
Verify the upgrade has applied to all environments.

[#135224045] Cleanup FIXMEs from CF RDS upgrade.

---

manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/spec/manifest/base_properties_spec.rb

The package was renamed in CF v246[1]. This omission wasn't an obvious
problem for existing deployments because the buildpack had already been
uploaded, however for a clean deployment the java buildpack would be
missing. For existing deployments it means that the buildpack wouldn't have
been updated from the previous version.
[1]https://github.com/cloudfoundry/cf-release/commit/72222a8
Do a fresh deploy from master and verify that the java buildpack is present.
Anyone but myself or @combor

[#135948443] Fix name of java buildpack.

---

doc/datadog.md

Replace the sentence, which says what to do if you have self-update
pipelines disabled but not what to do if you don't, with a command to
also disable self-update pipelines.
Because I copied the command without reading the preceding sentence, so
self-update pipeline overwrote my changes and I was left momentarily
confused.
Text review only should be sufficient.
Not @dcarley

[docs] Change self-update instructions for DataDog in dev

---

concourse/pipelines/create-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml

This reverts commit d7501a5d42c67562582962f930f12089c6da7f8a. added in #744
Strangely the commit was included because github did not detect the
changes from the `git push --force` and the `make merge_pr` got the
previous commit from the API.
We noticed that in https://status.github.com/ mean hook was too high
in that moment, 7.8s
We should wait before running merge_pr after a git push -f

[#138486833] Revert "TMP - test terraform update"

---

terraform/cloudfoundry/elbs.tf

Story: [#136052751 Reduce ELB idle timeout (to reduce 504 errors)](https://www.pivotaltracker.com/story/show/136052751)
From time to time requests fail on the UAA ELB with a 504 error. In most cases this was caused by an unhealthy backend, but some cases were not explained. This was investigated in [#123760561](https://www.pivotaltracker.com/story/show/123760561) and the AWS support ticket 1861267451 was raised.
The problem may happen when ELB maintains connections to the backend because the backend uses HTTP keepalive, and the idle timeout on the ELB is higher than the backend keepalive timeout. This is explained in:
https://hardwarehacks.org/blogs/devops/2015/12/29/1451416941200.html
We have reasonable understanding of what is going on on UAA: the ELB backend here is tomcat, configured …

[#136052751] Adjust UAA ELB timeout

---

scripts/create-user.sh

As a part of improve incident communications story we've decided to
notify operator that every user should be a member of GOV.UK PaaS
Announce. As a first step before implementing automation for this task
we will would like to add notification that will be displayed after user
account was successfully created.
Also it includes a small fix to correctly detect if user account already exists. 
- run it on your dev env and check if it notification is displayed and makes sense 
Not @combor

[#136435555] Add user to mailing list notification

---

.travis.yml

We added `set -e` before each `before_install` block in c1a5aa0 to make the
build fail fast if it was unable to install any of the dependencies.
There appears to have been a change to Travis today that now causes the
build to fail if `set -e` is used in `before_install`. From some previous
issues it looks like it causes it to be set globally for all of Travis's own
scripts that run within the build and has never been fully supported:
- https://github.com/travis-ci/travis-ci/issues/3586#issuecomment-274585174
- https://github.com/travis-ci/travis-ci/issues/891#issuecomment-32318632
We would still like the build to fail fast if it's unable to install the
dependencies. So it seems that the compromise is to unset it after each
command block until the following feature is implemented:
- …

Travis: set +e after each before_install

---

Gemfile
Gemfile.lock
concourse/pipelines/create-cloudfoundry.yml
concourse/scripts/update_monitor_options.rb
concourse/scripts/update_monitor_options_test.go
terraform/datadog/concourse.tf
terraform/datadog/variables.tf
terraform/prod.tfvars

[Set up smoke test alerts to PagerDuty using datadog](https://www.pivotaltracker.com/n/projects/1275640/stories/137701781)
Create a monitor that notifies via pagerduty if >= 3 continuous smoke tests failures in 15m or no_data for 15m.
Deploy with datadog enabled. Put yourself on [schedule](https://gds-paas.pagerduty.com/schedules#PEQKA3V) in pagerduty. Run continuous smoke tests. Make them fail 3 times in 15 min window (you can e.g. stop cloud controllers). You should get notification based on the preferences you set-up in PagerDuty. Stop running tests for 15 mins - you should get no_data notification. Note that if you test out of "office hours (9 - 17oo), then this will be marked as low priority and based on your notification settings you might not be notified. Before merging, remove …

[#137701781] Set up smoke test alerts to PagerDuty using datadog

---

terraform/datadog/auctioneer.tf
terraform/datadog/bbs.tf
terraform/datadog/etcd.tf
terraform/datadog/nsync.tf
terraform/datadog/route-emitter.tf
terraform/datadog/tps.tf

[#130660899 Monitor that single instance services are single instance (forever alone)](https://www.pivotaltracker.com/story/show/130660899)
What?
----
We want to monitor all the single-instance services from Diego as we do with route-emitter in #662.
We will add monitors only for the services: bbs, nsync, tps and auctioneer, for the lock flag in consul.
We also add monitor the etcd flag `cf.etc.IsLeader`.
We finally improve the query a little bit by using max/min depending if we are checkign the upper or lower value. See commits.
How to review?
-------------
Code review
You can deploy the changes only in CI by doing:
```
cd paas-cf/terraform/datadog
mkdir tmp
cd tmp
ln -s ../auctioneer.tf ../bbs.tf ../datadog.tf ../etcd.tf ../nsync.tf ../tps.tf ../variables.tf .
terraform apply -var …
```

[#130660899] Add monitors for diego single-instance service locks and for etcd

---

manifests/cf-manifest/manifest/800-logsearch.yml

Due to huge volume of logs to parse we went out of cpu credits on
parser VMs. This slowed down logstash considerably and resulted in
almost no log ingestion to elasticsearch.  To avoid such situation in
the future we would like to use a VM type that is not burstable.
medium type is EC2 m3.medium VM. 
Deploy and check if you are getting logs in Elasticsearch ( by checking in Kibana )
Not @combor

[SUPPORT] Change parser VM type to medium

---

concourse/pipelines/create-cloudfoundry.yml

Fix generate-git-keys task
ssh-keygen is present in the git-ssh container. We use that in other tasks
that also need ssh-keygen. Use this image instead of awscli, which was
missing ssh-keygen.
Task generate-git-keys should work now. This is in 'operator' tab. Without this PR, it fails with `sh: ssh-keygen: not found`
not @mtekel

Fix generate-git-keys task

---

Makefile
concourse/pipelines/create-cloudfoundry.yml
terraform/cf-certs/outputs.tf
terraform/cf-certs/upload.tf
terraform/cloudfront/cloudfront_distribution/distribution.tf
terraform/cloudfront/cloudfront_distribution/variables.tf
terraform/cloudfront/globals.tf
terraform/cloudfront/instances.tf
terraform/scripts/lint.sh
terraform/scripts/set-up-cdn-instances.sh

We would like to create a CDN for the PaaS Documentation and the Product Page and be able to access it, from the new subdomain.
This change, should allow any user with an access, create CloudFront Distributions. The CNAME record, will be created as part of the system domain name, for each distribution.
1. Run `create-cloudfoundry` pipeline from this branch
1. Run `ACTION=plan make dev setup_cdn_instances`
1. Experience no errors from the above
1. Run `ACTION=apply make dev setup_cdn_instances`
1. Experience no errors from the above
1. Wait... This may take a while. I suggest logging into AWS Console and monitoring CloudFront Distributions
1. Visiting `docs.${DEPLOY_ENV}.dev.cloudpipeline.digital` should result in `paas-tech-docs`
1. Visiting `www.${DEPLOY_ENV}.dev.cloudpipeline.digital` …

[#136353673] Add ability to create CDNs programmatically

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
terraform/datadog/consul.tf

[#130660899 Monitor that single instance services are single instance (forever alone)](https://www.pivotaltracker.com/story/show/130660899)
What?
-----
We want to be able to start monitoring consul in datadog
*  get events from the leader election in datadog so that we can correlate incidents.
* monitor if there is a leader
In https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/12 we enable datadog integration.
This commit upgrades this release so the integration would start working.
> **Note**: Initially we wanted to add a monitor to check that there is exactly one leader elected, but the consul integration does not offer any good metric for that. Instead we added a check and a monitor to check that there is at least one leader.
Dependencies
------------
Merge this …

[#130660899] Upgrade datadog-for-cloudfoundry to enable consul integration and check for consul leader

---

concourse/pipelines/create-cloudfoundry.yml

The certs have now been updated, and the old ones cleaned up in all
long-lived environments, so this is no longer needed.
This reverts commit 5fa517c5aabc46289ff7af4a43c7f29c2c14ae9f.
Code review. 
Anyone but myself or @paroxp.

[#136353673] Revert "Allow the pipeline to fail"

---

terraform/cloudfront/cloudfront_distribution/distribution.tf

We have decided, it may be unreasonable to have a 60 minute delay, before CloudFront is going to check for the changes.
This has been justified with the scenario: During user testing lab, we may want to quickly run an update on the docs and expect it to appear fairly quickly online, for the users to look up.
This has been changed to 5s as agreed with Ben, @dcarley, @alext and @mtekel. It may be worth, keeping an eye on this change.
Code review, should be sufficient test.
After the change is applied, the manual `ACTION=apply make prod setup_cdn_instances` will need to be ran.
Anyone but @paroxp.

[#136353673] Reduce the default TTL for CloudFront instances

---

Makefile
concourse/pipelines/create-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/failure-testing.yml
concourse/scripts/pipelines-cloudfoundry.sh
concourse/scripts/self-update-pipeline.sh
terraform/ci.tfvars
terraform/dev.tfvars
terraform/pingdom/pingdom.tf
terraform/prod.tfvars
terraform/scripts/set-up-pingdom.sh
terraform/staging.tfvars

[Set up Pingdom alerts to PagerDuty](https://www.pivotaltracker.com/n/projects/1275640/stories/137700569)
New contacts in pingdom have been created which point to new services created in pagerduty for pingdom alerts - one for in-hours notifications only and one for 24/7. This PR configures pagerduty notifications for CI/Staging (in-hours) and prod (24/7).
Locally edit dev tfvars file. Copy pingdom contact ids from ci/staging tfvars files. This will enable in-hours pager duty notifications for dev when you create pingdom checks.
Override in-hours schedule to your name. `ACTION=apply make dev pingdom`. Stop your healthcheck app. Wait. Get notified by pagerduty - the way you configured your notification options in PD. 
Don't forget to clean up the override in PD (it's in the right column of …

[#137700569] Set up Pingdom alerts to PagerDuty

---

concourse/scripts/self-update-pipeline.sh

We removed MAKEFILE_ENV_TARGET and replaced it with AWS_ACCOUNT, but that
one is only available _after_ successfull self update. Fix the script to
take the old variable still.
Try to run self update pipelines job. It should succeed.
not @mtekel

[#137700569] Fix self-update pipelines

---

.travis.yml
Makefile
terraform/scripts/lint.sh

[Fix `make lint_terraform`](https://www.pivotaltracker.com/n/projects/1275640/stories/139291295)
We now have TF 0.8.5 and a new version of provider built for this TF. Use that for lint checks.
`make lint_terraform` should succeed.
not @mtekel or @saliceti

[#139291295] fix lint_terraform

---

concourse/pipelines/autodelete-cloudfoundry.yml

Autodelete will often fail if the environment was deployed from a branch that has been merged, meaning the remote branch no longer exists. This pins the autodelete branch to master to avoid this.
90% of the time the branch is now part of master and the operations carried out are quite simple, so this should cause no problems.
Code review.
Anyone!

Prevent failures by pinning autodelete to master

---

terraform/ci.tfvars
terraform/datadog/concourse.tf
terraform/datadog/variables.tf
terraform/dev.tfvars
terraform/prod.tfvars
terraform/staging.tfvars

Stories:
* [Configure schedules and escalation policies for PagerDuty](https://www.pivotaltracker.com/story/show/135953741)
* [Send smoke test and Pingdom alerts from CI and staging to the in-hours support person using PagerDuty](https://www.pivotaltracker.com/story/show/139005729)
Create explicit variables for alerting in and out of hours. They can be set differently for each environment. We currently set email notification for dev, in hours pagerduty only in ci and staging, in hours and out of hours pagerduty in production.
* There is a "[TEMP]" commit to create datadog monitors even if you don't have datadog enabled
* Apply to your environment, the monitors should be created
* Change values in `dev.tfvars`, the notifications should change
* You can double check the pagerduty service …

[#135953741] Datadog pagerduty integration

---

concourse/tasks/terraform_destroy_datadog.yml

Story: [Configure schedules and escalation policies for PagerDuty](https://www.pivotaltracker.com/story/show/135953741)
In https://github.com/alphagov/paas-cf/pull/765 new variables were added to env.tfvars files and used in datadog terraform. The destroy task wasn't reading the env.tfvars files so the task was hanging.
The env.tfvars are now read in the destroy task.
Run the destroy-cloudfoundry pipeline, it shouldn't hang at task datadog-TF-destroy
Should you want to keep your environment, you can comment the delete-deployment and pause the the terraform-desrtoy job.
Not me

[#135953741] Fix terraform destroy bug

---

concourse/pipelines/create-cloudfoundry.yml

Same problem as in 5693f800ea6190271a27dc0b0d382932ecbef39b but now in
create pipeline.
New variables were added to env.tfvars files and used in datadog
terraform. The destroy task wasn't reading the env.tfvars files so the
task was hanging.
The env.tfvars are now read in the destroy task.
Upload you datadog keys but set `ENABLE_DATADOG` to false. The `datadog-terraform-apply` task in `cf-deploy` job should not hang. 
Not @combor

[#135953741] Fix terraform destroy bug #2

---

scripts/create-user.sh

[Remove user that ran create-user script from organisation](https://www.pivotaltracker.com/n/projects/1275640/stories/126115903)
Also check if user exists for reset password.
* Reset pw: try to reset password of an user that doesn't exist, e.g. `/scripts/create-user.sh -r -e dummy@user.org -o admin`
* User cleanup: create a dummy user in some test org and then list all the users in that org. You should not be among the list:
```
/scripts/create-user.sh -e dummy@user.org -o dummy-org
cf org-users -a dummy-org
```
not @mtekel

[#126115903] Remove user that ran create-user script from organisation

---

manifests/cf-manifest/manifest/020-cf-properties.yml
scripts/create-user.sh
scripts/rotate-user-password.sh

We've moved our documentation off Readthedocs and onto the PaaS, this updates the documentation links in the API and in emails we send to tenants.
Check the new links refer to the same documentation as the old links, but on the new server.
Anyone!

Switch documentation URL's to the new docs

---

terraform/prod.tfvars

[Create  DWP Bereavement Payment Support Org and Users](https://www.pivotaltracker.com/n/projects/1275640/stories/139666419)
Whitelist DWP Bereavement Payment Support IP so that they can connect an operate their dwp-bereavementpaymentsupport org.
Check that the whitelisted IP matches the one in the story. Check that it belongs to DWP (tip: use `whois`).
not @mtekel

[#139666419] Whitelist DWP Bereavement Payment Support IP

---

concourse/pipelines/create-cloudfoundry.yml

This will ensure that there is no downtime when we deploy the healthcheck
app - which happens during every run of the pipeline. It will enable us to
merge the `post-deploy` job into `cf-deploy` because it will now be safe to
run in parallel with `availability-tests`.
Although it hasn't been a problem to date, it will also prevent us from
getting false-positive alerts from Pingdom (which monitors this app) and may
allow us to reduce the threshold for alerts.
- see the individual commit messages for more information
- test without the healthcheck database
- deploy from `master` to ensure that you have a running environment (not deleted overnight)
- deploy the pipeline from a branch
- run it all the way through
- confirm that the availability-tests pass
- test with the healthcheck database
- …

[#121934253] Use blue-green-deploy plugin for healthcheck app

---

manifests/cf-manifest/cloud-config/040-graphite.yml

Graphite is currently IOPs starved. Current volume is 200GB, which
guarantees 600 IOPs only. This is not enough, as we are having more
apps, hosts and other sources of metrics in prod. IO starvation leads
to not all metrics being always written to disk, which leaves gaps in
graphs. Also, display of our user impact dashboard is affected, as there
is not enough IO available to retrieve all the stats in time, which leaves
blank graphs in grafana.
Double IOPs to 1200 by doubling size of the volume. This is still cheaper
than switching to provisioned IOPs, which at 1200 IO and 40GB only size is
more than twice the cost. The actual data usage is currently at 14GB...
Code review. You can apply to your environment - you should see graphite disk being upgraded. Upgrade should preserve all the …

[support] Double graphite EBS IOPs

---

manifests/cf-manifest/manifest/900-cf-tests.yml

As of our upgrade to v251, we have announced support of cf tasks.
Do run acceptance tests to keep verifying that the functionality
still works correctly over time.
Note that the tests can still pass even if task_creation feature
flag is disabled as tests run with user that has admin privileges,
which can run tasks even if they are disabled.
Run. Acceptance tests should pass.
not @mtekel

Enable cf tasks acceptance tests

---

.travis.yml

As we use this version in the spruce container we need to synchronise
version in travis. This is a follow up to external PR: https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/90
- check if travis tests have passed
Not @combor

Update spruce to v 1.8.9

---

concourse/pipelines/create-cloudfoundry.yml
manifests/cf-manifest/manifest/800-logsearch.yml
terraform/cloudfoundry/logsearch.tf
terraform/cloudfoundry/rds_broker.tf
terraform/cloudfoundry/security-groups.tf

In order for our Trusted Advisor to report when and what we desire, we would like to fix some issues we're currently facing.
Two issues targeted in this PR are: 
- the RDS Broker could use HTTPS connection
- the logsearch-ingestor could use ssl connection
In order to prevent downtime, we're adding an extra listener, which then will be removed in another PR.
This changes need to be applied in strict order to avoid downtime for log forwarding:
1. Review and apply this PR. It will create new secure ELB listeners for rds-broker and ingestor 
2. Review and apply ( on bootstrap ) https://github.com/alphagov/paas-bootstrap/pull/46. It will change bosh runtime config to point rsyslog to new listener and use SSL
3. Review and apply https://github.com/alphagov/paas-cf/pull/782. It will remove old …

[#134350583] Fix RDS Broker and syslog trusted advisor warnings

---

manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/manifest/900-cf-tests.yml
manifests/cf-manifest/scripts/generate-cf-secrets.rb
manifests/cf-manifest/spec/manifest/base_properties_spec.rb

This will enable tenants to add an authentication layer in front of an app without having to modify the app itself.
- Push the [cf_basic_auth_route_service](https://github.com/alext/cf_basic_auth_route_service) app to CF (setting the AUTH_USERNAME,  AUTH_PASSWORD and SKIP_SSL_VALIDATION env vars).
- Define a user-provided-service for it:
```
cf create-user-provided-service my-auth -r https://basic-auth-route-service.${DEPLOY_ENV}.dev.cloudpipelineapps.digital
```
- Bind it to the route for an app:
```
cf bind-route-service ${DEPLOY_ENV}.dev.cloudpipelineapps.digital my-auth --hostname my-app-route
```
- Check if your app has basic auth now
Not @combor

[#139706089] Enable route services

---

concourse/pipelines/create-cloudfoundry.yml
manifests/cf-manifest/manifest/800-logsearch.yml
terraform/cloudfoundry/logsearch.tf
terraform/cloudfoundry/rds_broker.tf
terraform/cloudfoundry/security-groups.tf

This needs to be rebased after https://github.com/alphagov/paas-cf/pull/776 is merged.
As we have moved to https for cloud controller to rds broker
communication we can now remove old listener and related security rule.
This needs to be applied after https://github.com/alphagov/paas-cf/pull/776. Check the sequence in the master PR.
Run deployment from this branch and make sure you still can interact with rds-broker. For instance execute `cf create-service` command.
Not @paroxp or @combor

[#134350583] Cleanup of rds listener 

---

terraform/cloudfoundry/logsearch.tf

As we use SSL protected ELB for syslog forwarder we can remove old
unused one.
This needs to be applied after https://github.com/alphagov/paas-cf/pull/782 as it required all rsyslog forwarders to use SSL protected listener.
Run deployment from this branch and make sure you still can see logs in Kibana. 
Not @paroxp or @combor

[#134350583] Cleanup of old ingestor elb 

---

manifests/cf-manifest/manifest/050-rds-broker.yml

[#139361587 rds-broker: Able to create a instance from the latest snapshot of other instance](https://www.pivotaltracker.com/story/show/139361587)
We want to provide the user logic to be able to restore the latest snapshot of any existing service instance.
We implemented that feature in https://github.com/alphagov/paas-rds-broker/pull/35
It adds an additional parameter to be passed during provisioning: `restore_from_latest_snapshot_of`. The user must pass the GUID of an existing postgres service, which can find out using `cf service mydb --guid`.
This PR depends on https://github.com/alphagov/paas-rds-broker/pull/35 and https://github.com/alphagov/paas-rds-broker-boshrelease/pull/29
You can test this PR by itself, but once all 3 have been reviewed, you must merge and update the others in …

[#139361587] Update rds-broker to support restore from latest snapshot

---

concourse/pipelines/create-cloudfoundry.yml
concourse/resources/bosh-secrets-deleter.yml
concourse/resources/cf-secrets-deleter.yml

This is a first batch of changes to implement password rotation pipelines.
There are two of them in the `operator` group. 
- reset cloudfoundry passwords - rotates all but grafana password
- reset bosh passwords - rotates all but NATS password
Grafana changes will come in a next PR as we decided to improve grafana release to implement password rotation via deployment manifest.
We found rotation of NATS particularly difficult so we agreed to put it out of scope. See https://www.pivotaltracker.com/n/projects/1275640/stories/127339659 for more details.   
- deploy your `create` pipeline
- run `reset-cloudfoundry-passwords` and again `create` pipeline to test if creds are rotated
- run `reset-bosh-passwords` and next `bootstrap` pipeline to test bosh creds rotation 
Not @combor

[#130020741] Password rotation pipeline 

---

Makefile
scripts/validate_aws_credentials.sh

Add default env. names for staging and prod.
This means you don't have to re-export DEPLOY_ENV every time you switch from
your dev to work on ci, staging or prod. In our current version of scripts,
you have to provide correct DEPLOY_ENV name, as that is used to access
environment's bucket and if it's wrong, showenv will fail, failing any
subsequent steps.
The error that you get when DEPLOY_ENV is wrong:
```
/usr/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): mapping values are not allowed in this context at line 1 column 79 (Psych::SyntaxError)
from /usr/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
from /usr/lib/ruby/2.2.0/psych.rb:318:in `parse'
from /usr/lib/ruby/2.2.0/psych.rb:245:in `load'
from concourse/scripts/val_from_yaml.rb:10:in `load_yaml'
from …
```

[support] Add default env. names for ci, staging and prod

---

platform-tests/src/acceptance/http_forwarded_for_test.go

The test for XFF headers started failing this morning because the egress IP
returned by `canhazip.com` didn't match what the app was reporting:
X-Forwarded headers
/tmp/build/3151afb2/paas-cf/platform-tests/src/acceptance/http_forwarded_for_test.go:71
should append real egress IP to existing X-Forwarded-For request header
[It]
/tmp/build/3151afb2/paas-cf/platform-tests/src/acceptance/http_forwarded_for_test.go:70
Expected
<[]string | len:3, cap:3>: ["1.2.3.4", "52.51.7.62", "127.0.0.1"]
to consist of
<[]interface {} | len:3, cap:3>: ["1.2.3.4", "162.158.38.21", "127.0.0.1"]
/tmp/build/3151afb2/paas-cf/platform-tests/src/acceptance/http_forwarded_for_test.go:69
It looks like `canhazip.com` is broken as of this morning; it's returning an
IP that belongs to CloudFlare instead of the IP of …

[bugfix] platform-tests: canhazip.com -> icanhazip.com

---

terraform/cloudfront/cloudfront_redirect/distribution.tf
terraform/cloudfront/cloudfront_redirect/variables.tf
terraform/cloudfront/instances.tf

[#139296467 Redirect from cloud.service.gov.uk (no www prefix)](https://www.pivotaltracker.com/story/show/139296467)
What?
-----
Set it up so that if users try to navigate to `cloud.service.gov.uk` in their browsers, they will be redirected to `https://www.cloud.service.gov.uk`
We use a configuration based on Cloudfront + API Gateway to redirect to the www.${apex} domain from the APEX system domain.
Limitation: Any other path will return a 403 error. In order to make API Gateway work with any path, we must use proxy mode and send the request to a Lambda function or similar.
Dependencies
------------
This supersedes the PRs https://github.com/alphagov/paas-cf/pull/791 and https://github.com/alphagov/paas-product-page/pull/2
How to review?
------------
* Code review
* Deploy from master …

[#139296467] Add redirection to add www to the system domain

---

terraform/prod.tfvars

[#136353551](https://www.pivotaltracker.com/story/show/136353551)
We are going to use the build Concourse in CI to automatically push
apps, such as the tech docs, to our production platform. We need
to allow it to communicate with the API until the API is opened up
to the public. The IP is an Elastic IP, so it will be stable over
time.
Check the IP of the build Concourse in CI matches the one provided in this pull request.
You can try adding a similar patch to your dev.tfvars and see if it deploys, but that may be overkill.
Anyone but me or @saliceti

[#136353551] Allow our own build Concourse to push apps

---

Makefile
concourse/pipelines/create-cloudfoundry.yml
concourse/scripts/pipelines-cloudfoundry.sh
platform-tests/example-apps/healthcheck/manifest.yml

Prior to our BBS incident, we'd like to test against a large number of instances running to establish if our deployment is unaffected.
We would like to test that the subsequent deployments still work when there are many app instances running.
- Review the code
- Run `make dev pipelines` from this branch
- Run `create-cloudfoundry` pipeline
- Expect it to succeed
**Optionally**
- Create separate branch
- Modify the `platform-tests/example-apps/healthcheck/manifest.yml` and remove the `disk_quota` or set it to `1G`
- Run `make dev pipelines` from new branch
- Run `create-cloudfoundry` pipeline
- Expect it to fail
Not @paroxp

[#139003315] Test subsequent deployments while under big load

---

manifests/cf-manifest/manifest/050-rds-broker.yml

[#139361587 rds-broker: Able to create a instance from the latest snapshot of other instance](https://www.pivotaltracker.com/n/projects/1275640/stories/139361587)
What?
----
Update the broker to get the changes implemeented in:
- https://github.com/alphagov/paas-rds-broker/pull/36
- https://github.com/alphagov/paas-rds-broker-boshrelease/pull/30
Update this PR once the other is merged.
Who?
---

[#139361587]  Update rds-broker to fix bug in restore snapshot

---

concourse/pipelines/create-cloudfoundry.yml

We want to have different behavior of AWS credentials check based on if the
script runs inside concourse pipeline, which is a server that uses IAM role
and when it runs on the command line in your laptops, in which case we use
STS tokens + temporary credentials. In order to introduce this logic, we
need to first add variable in self-update-pipelines where we store the
information for the script to not do STS related credentials check, but skip
them instead.
This is a pre-quel to #798
Check that it makes sense in the context of #798
not @mtekel
that can't review, because they worked on it.

Prepare for aws credentials validation

---

concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/failure-testing.yml

Failure testing and destroy pipelines also call self update. Add the
SKIP_AWS_CREDENTIAL_VALIDATION flag there as well.
This is a requirement for #798
Check that it makes sense in context of #798
not @mtekel

Prepare for aws credentials validation 2

---

Makefile
scripts/validate_aws_credentials.sh

We are using IAM profile on concourse for AWS credentials. We thus want to
skip STS token and user credential validation that we normally want to run
when running make locally.
Deploy this branch to your concourse. Run self update pipelines task (in the 1st pipeline-lock job). It should pass.
not @mtekel

Skip AWS cred. validation in self-update pipelines

---

manifests/cf-manifest/manifest/040-graphite.yml

This is a follow up to https://github.com/alphagov/paas-cf/pull/789 that updates Grafana to v 4.1.2 to make use of newly provided `grafana-cli` admin command.
The `grafana-cli admin` allows to change admin user password via cli.
This will let us to set new password in the manifest and rotate it during deployment.
**This is master PR for set of PRs related to grafana update. PRs need to be merged in the sequence listed below**:
- https://github.gds/government-paas/aws-account-wide-terraform/pull/83
- https://github.com/alphagov/paas-release-ci/pull/12
- https://github.com/alphagov/paas-grafana-boshrelease/pull/1
- this PR
Not @combor

[#130020741] Update grafana to v 4.1.2

---

scripts/show-cf-memory-usage.rb

In order to help decide whether we need to increase capacity when adding an org, this adds a line to the `show-cf-memory-usage` task to show the total cell memory required to meet the [ADR017](https://government-paas-team-manual.readthedocs.io/en/latest/architecture_decision_records/ADR017-cell-capacity-assignment/) requirement.
While working on this, I've removed the "Memory actually used by apps:" line because it was incorrect, and wasn't reporting what we thought it was. See the commit message for details.
Code review
Run the task from this branch. Verify the new output makes sense and agrees with the ADR.

Include ADR017 threshold in show-cf-memory-usage task

---

terraform/datadog/concourse.tf

[#140395801](https://www.pivotaltracker.com/story/show/140395801)
We received notifications out-of-hours for smoke tests running for 12 minutes. We were not expecting to receive notifications for breaching the warning threshold. This adds [message template variables](http://docs.datadoghq.com/monitoring/#message-template-variables) which alert to the 24x7 endpoint for critical alerts, and the in-hours endpoint for warnings. We also alert out-of-hours for no-data, because we need assurance the smoke tests are actually running.
I have already done the bootstrapping of Concourse and deploying, both with Datadog enabled, in order to test this sends notifications under the right circumstances (alert, warning, and no-data), so I don't blame you if you don't want to repeat that whole process. …

[#140395801] Reduce false positives for out-of-hours support

---

terraform/datadog/cloud_controller.tf

The cloud controller monitors based on metric change are most of the time in "No data" state even if the metric is sent every 30s. Datadog has confirmed it's a bug and is currently investigating.
They show as warnings on the dashboard. This is distracting and may hide real issues.
To work around the problem, we replace the dashboard visual notification by in hours pagerduty alerting.
You can enable the monitors without deploying the everything by running only the teraform bit. This can be achieved by a command such as (replace appropriately):
```
export TF_VAR_aws_account=dev
export TF_VAR_datadog_api_key=$(gov-pass datadog/dev/datadog_api_key)
export TF_VAR_datadog_app_key=$(gov-pass datadog/dev/datadog_app_key)
export TF_VAR_datadog_notification_24x7=colin.saliceti@digital.cabinet-office …
```

Silence no data monitors

---

manifests/cf-manifest/manifest/050-rds-broker.yml

[#139361587 rds-broker: Able to create a instance from the latest snapshot of other instance](https://www.pivotaltracker.com/story/show/139361587)
What?
----
We were using the wrong field to short the snapshots of an instance. We   should use `SnapshotCreateTime`, not `InstanceCreateTime` that is the date of the creation of the instance.
Because this, we are actually restoring the oldest because AWS API seems to return ordered by from oldest to newest.
How to review?
------------
Review with https://github.com/alphagov/paas-rds-broker/pull/40 and https://github.com/alphagov/paas-rds-broker-boshrelease/pull/34
You can review following the steps described in https://github.com/alphagov/paas-cf/pull/784, but creating 2x snapshots instead of one.
Then check that the Tag "Restored Snapshot …

[#139361587] rds-broker with bugfix getting latest snapshot

---

manifests/cf-manifest/manifest/020-cf-properties.yml

This reverts commit c292aad01133c3cb79117e1aca4bbd11e22bcf1d.
The workers are constantly polling the RDS CC DB. This causes significant CPU usage and we have run out of credits. The impact is that services connecting to the databases in that instance are
slower (api, uaa, bbs). This has already been reported by some users.
We now revert to the default. This is safe as this commit hadn't made an improvement.
Code review
Not me

Revert "Increase number of CC workers to 3 per VM"

---

terraform/cloudfoundry/cf_rds.tf

What?
------
We ran out of CPU credits in the CF RDS instance because of unexpectedly
high CPU usage. This caused CPU usage to be capped at 20% and it made
the system slow. We noticed most CPU was consumed by cloud controller
workers. They constantly poll the DB for new jobs to execute. We reduced
the number by reverting [1]
We change the instance type to a type that is not credit based.
[1]  https://github.com/alphagov/paas-cf/pull/817
How to review?
--------------
Code review
After merge
-----------
We suggest that the change is done manually with "apply immediatelly" in prod. We have already tested that the upgrade with no impact for the end user, as RDS will be upgraded in a HA way, but we want to babysit the upgrade anyway.
Who?
----

[#141300765] Increase CF DB instance type 

---

manifests/cf-manifest/manifest/env-specific/cf-prod.yml

We're currently exceeding the limit defined in [ADR017](https://government-paas-team-manual.readthedocs.io/en/latest/architecture_decision_records/ADR017-cell-capacity-assignment/). With 9 cells,
the total memory provided is 269G. The amount we need depends on
whether we include the Smoke tests and acceptance tests. The numbers are
as follows:
- Not including smoke tests: 268G
- Including smoke tests: 276G
- Including smoke tests and custom acc tests: 291G
Given the smoke tests are running continually, this usage should be
included in the total, hence the need to increase the cell count.
Code review.

[#141476575] Increase prod cell count to 12.

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
terraform/datadog/bbs.tf

This is set of PRs to deploy BBS monitoring solution. It adds new `cf.bbs.Healthy` and `cf.bbs.ResponseTime` metrics. 
It consists of:
- https://github.com/alphagov/paas-bootstrap/pull/55 - WHICH MUST BE DEPLOYED FIRST
- https://github.com/alphagov/paas-datadog-bbs-integration/pull/1 - Provides BBS check and tests.
- https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/13 - Integrates BBS check into BOSH release and provides default config
- https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/13 - Implements new mechanism to copy custom checks into datadog agent directory
- This PR
- deploy from this branch and check if `cf.bbs.Healthy` and `cf.bbs.ResponseTime` are available in DD for your env. Check if monitor works
- Review and merge …

[#139196683] Monitor BBS health

---

scripts/show-cf-memory-usage.rb

So that we can easily see the quotas assigned to each org at a glance.
Run the task against an environment (eg `make dev show-cf-memory-usage`) and check the output looks sensible.

Include org quota in show-cf-memory-usage

---

tools/paas_dashboard/jobs/datadog.rb

I'm using the "mute for N hours" button in DataDog to silence some alerts
that we know are currently false-positives. I'd like them to be omitted from
the dashboard so that I can concentrate on real alerts.
I had to look at the [API docs][0] to implement this. It seems that
`options.silenced` will contain a hash of `scope: timestamp` when a monitor
is muted/silenced. I'm omitting the monitor if the hash contains *anything*
because:
- I don't think the scope matters because the dashboard currently collapses
triggered monitors of the same type, e.g. it tells us we have one warning
if two hosts have alerts for disk space.
- I don't think we need to compare the timestamp because the `silenced` will
be removed from the API results when the mute period expires.
[0]: …

[support] Omit silenced monitors from DataDog dashboard

---

manifests/cf-manifest/manifest/020-cf-properties.yml

Registers requested a quota change to their "trial" organisation because
they have hit the memory limit of the `default` quota by using a handful of
Rails applications each with two instances of 256M (which doesn't seem
unreasonable):
- https://gaap.deskpro.com/agent/#app.tickets,inbox:agent,t.o:4199,vis:7
Following a discussion with @alext, @jollery, and @bleach, we agreed that it
would be cheaper (in terms of total potential cost to us) to give "trial"
orgs more memory on the `default` quota rather than move them to the `small`
quota which allows for paid service plans.
I'm in favour of modifying the existing quota rather than introducing
another quota for "trial" users, because it requires less effort now to deploy
and less effort in the future to determine which quota an org should be …

[support] Change default quota from 2G to 5G memory

---

concourse/pipelines/create-cloudfoundry.yml
manifests/cf-manifest/manifest/900-cf-tests.yml

[Turn on Docker support as experimental](https://www.pivotaltracker.com/n/projects/1275640/stories/140834345)
1. Check that diego_docker feature is disabled: `cf feature-flags`
2. Deploy. Acceptance tests should pass.
3. Check that diego_docker feature is enabled.
4. Disable feature by hand: `cf disable-feature-flag diego_docker`.
5. Run acceptance tests. They should fail.
not @mtekel

[#140834345] Enable docker image support 

---

concourse/pipelines/create-cloudfoundry.yml

[#139179971 Upgrade CF to >= v252](https://www.pivotaltracker.com/story/show/139179971)
What?
-----
We are experimenting failures[1] running the acceptance tests after
upgrading the cf client to 6.25.0 [2]
In this commit we use a tagged container with the previous version
v6.21.1. [3][4] We must revert this after merging [5]
[1] https://deployer.master.ci.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/acceptance-tests/builds/472
[2] https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/91
[3] https://github.com/alphagov/paas-docker-cloudfoundry-tools/tree/cf_6_21_1
[4] https://hub.docker.com/r/governmentpaas/cf-acceptance-tests/builds/bm4heywjrlwtjazox8sqazk/
[5] https://github.com/alphagov/paas-cf/pull/829
Dependencies
---------------
Add a revert to …

[#139179971] Pin the version of cf-acceptance-tests container

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml

Reduce the amount of logs generated by racoon which are filling up our
logsearch cluster. Depends on alphagov/paas-ipsec-release#2
1. Observe the vast amount of logs from racoon on the `cell` VMs, either:
- in logsearch with query `@source.component:racoon`, but I had problems in my dev environment
- in `/var/log/syslog` on the VM itself
1. Deploy from this branch
1. Observe the vast reduction in logs from racoon in the same places as previous
Not @dcarley

[#141394313] Upgrade ipsec release to disable stats logging

---

tools/paas_dashboard/jobs/datadog.rb
tools/paas_dashboard/widgets/health/health.coffee
tools/paas_dashboard/widgets/health/health.html
tools/paas_dashboard/widgets/health/health.scss

A "no data" alert isn't necessarily as serious as a "warning". They normally
indicate that the monitoring isn't working correctly, which may be hiding
more serious problems, but aren't the same as a known alert.
I choose "unknown" as the dashboard label because "no data" could possibly
be confused with the dashboard no updating from the DataDog API.
This is particularly of interest to me at the moment while I'm on support
because we're investigating a problem with a handful of monitors that are
reporting "no data". I have been muting the affected monitors and dc41a8e
prevents them from showing on the dashboard, but because they come and go I
haven't been able to mute all of them, and I'm still getting distracted from
real alerts.
1. Checkout the branch: `git checkout …

[support] dashboard: Separate no data alerts from warnings

---

terraform/datadog/bbs.tf

Before the tag didn't seem to be available on the metric (probably because of issues fixed by https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/10).
The tag is now present, so we can use like we do in all other monitors.
Deploy. See TF apply change to monitor. Check the monitor - the state should not change. Stop your dev bbs servers to trigger the monitor to verify it still works.
not @mtekel

[#139196683] Use deploy_env tag in bbs monitor definition

---

terraform/datadog/cell.tf

These descriptions are misleading because the presence of the `rep` or
`guardian` processes shouldn't be affected by the routers. I think they may
have been copy/pastad from another monitor by accident.
Code review only.
Not @dcarley

[support] Remove "router state" messages from cell monitors

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml

Story: [Upgrade CF to >= v252](https://www.pivotaltracker.com/story/show/139179971)
Depends on: https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/17
The monitor was broken since CF upgrade to v253 as the garden process name has changed from 'garden' to 'gdn'.
We now deploy the new version of datadog-for-cloudfoundry which has the updated monitor.
Code review is probably sufficient as the change is small and the impact is not critical.
For full review:
* Deploy with datadog enabled
* Check the garden monitor is green
* Update release definition in the [TEMP] commit once
https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/17
is merged
Not me

[#139179971] Fix garden monitor

---

concourse/pipelines/create-cloudfoundry.yml
concourse/scripts/lib/google-oauth.sh
manifests/cf-manifest/manifest/020-cf-properties.yml
manifests/cf-manifest/stubs/oauth.yml

This implements a condition that checks if creation of admin users is
enabled and adds one more stub to the spruce command.
Oauth config has been moved to separate file to include it only when we
want to create admins.
Deploy on dev and check if it finishes OK
Not @combor

[#136027405] Fix dev oauth property

---

terraform/prod.tfvars

As part of the #142128979, we'd like to add the DWP Carer's Allowance IP to our whitelist. This should be followed by creation of the organisation and users, for them to try out the PaaS.
Make sure the correct IP address has been added.
Not @paroxp

[#142128979] Add DWP Carer's Allowance IP to the whitelist

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml

Currently we run the Consul server checks on all VMs, because the datadog-consul job in the datadog-for-cloudfoundry release couples the two together. They have been split into datadog-consul-agent-client and datadog-consul-agent-server jobs in the release as part of https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/18. We leave the client checks on all VMs, but only include the server check for the VMs which are part of the Consul cluster.
First, this pull request must be merged: https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/18 is being reviewed. Once that is done the temporary commit should be replaced with one that points to the final release. The commits may or may not be squashed together, I am not fussy.
The other pull request …

[#141948375] Split Consul client and server checks 

---

manifests/cf-manifest/manifest/050-rds-broker.yml

Update rds-broker for without custom params fix.
NOTE: Update with final release from alphagov/paas-rds-broker-boshrelease#35
Includes:
- https://github.com/alphagov/paas-rds-broker/pull/41
- https://github.com/alphagov/paas-rds-broker/compare/3310e39...01cbfa9
1. Review and merge alphagov/paas-rds-broker#41 and alphagov/paas-rds-broker-boshrelease#35 first
1. Update the manifest with the final release from [build CI](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker?groups=main)
1. Amend the commit message to remove the "wip" and "NOTE"
1. Merge
1. Relax, you have completed the release gauntlet.
Not @dcarley

[#142122527] Update rds-broker for without custom params fix

---

Makefile

DEPLOY_ENV was defined only after SYSTEM_DNS_ZONE_NAME, which meant that had
empty environment name. Move DEPLOY_ENV definition before
SYSTEM_DNS_ZONE_NAME, so that it is defined correctly.
Check that URLs contain `master` when you do `make ci showenv`.
not @mtekel

Fix make ci showenv

---

terraform/datadog/cloud_controller.tf

Apply rollup function, because, as responded by DataDog support:
>The issue on the initial monitors was that during evaluation, the timeshift
that necessarily operates on a change monitor, couldn't find datapoints that
were there if the datapoints were not submitted at the exact timeshift
timestamp of the monitor:
>    Let's say the timeshift was looking for a datapoint at 8:34:25 am , and
you had one at 8:34:23 and one at 8:34:29, you'd artificially get a no data
result.
>Appending the rollup(avg,30) function is correcting that in the way that it
will average the points buckets over a 30 sec timeframe, so you'd always
have data.
Apply to your DD enabled environment. Observe monitors being updated. Observe monitors not having no_data issues any more (give it few hours - but change should …

[#142042903] Fix no_data in failed job and error count monitors

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
platform-tests/src/acceptance/cf_ssh_test.go

Story: [Resolve issues with large database imports](https://www.pivotaltracker.com/story/show/141785699)
Fix the issue reported by Notify that prevents them to upload more than 1GB data via ssh. The issue was reported here: https://github.com/cloudfoundry/diego-ssh/issues/31
A PR was raised upstream to update the crypto library globally in diego-release: https://github.com/cloudfoundry/diego-release/pull/288
For our issue we only need to update the ssh_proxy and file_server jobs.
An acceptance test covers uploads 1.9GB to cover the fix we've made. Another issue prevents us from uploading more than 2GB via `cf` command line: https://github.com/cloudfoundry/cli/issues/1098
We should increase the limit when it's fixed.
* Install [pv](https://linux.die.net/man/1/pv)
* Test ssh against a …

[#141785699] Fix ssh upload

---

tools/paas_dashboard/widgets/health/health.scss

Now that we have a third counter available, we may meet the case where all three will need to be displayed on the dashboard. This will cause some layout disturbances and could be fixed by making the counters smaller on a window below 544 pixels wide.
1. Run the dashboard locally
2. ~Cause many DataDog monitors to fail on one of our environments~ or remove `data-hideif="X | equals 0"` from `widgets/health/health.html` lines `9`, `15` and `21`
3. Check the behaviour on different window widths - You need to refresh every time you set a new window width
Not @paroxp

Fix the counters on window with certain width

---

manifests/cf-manifest/stubs/oauth.yml
scripts/lib/mail_credentials_helper.rb
terraform/cloudfoundry/elbs.tf

Fix some problems that we found after merging the original PR
CF v253 introduced a UAA change that appears to require a new `tokenKeyUrl` property to be set to allow Google's signatures to be validated. A [bug](https://github.com/cloudfoundry/uaa/issues/565) exists for this upstream.
The user visits login.domain/passcode to get a one-time code to use in the CLI, they then get redirected to /login, visit google to login and then return to access the passcode page.
This requires sticky sessions to be enabled on the UAA load balancer because the the URL that a user was intending to visit is saved in a server side session and there does not seem to be a way of sharing the sessions between UAA instances.
The expectation from the UAA team seems be to that it will be deployed behind gorouter, …

Fix admin users login with OpenID connect 

---

manifests/cf-manifest/manifest/env-specific/cf-default.yml

Due to performance problems during acceptance tests execution we decided
to increase number of cells on CI and STAGING environments to cope with
the load and allow tests to finish undisrupted. During
investigation with Pivotal we have discovered that metron is dropping
messages and UDP packed are being dropped by kernel as the load on cells
was extremely high.
Sanity check
Not @combor

[#142302879] Increase default number of cells

---

terraform/datadog/uaa.tf

Story: [Create alerts for anomalous UAA behaviour](https://www.pivotaltracker.com/story/show/134579301)
Add 2 monitors based on UAA failed login metrics.
The monitors require 2 weeks of data, it is recommended to test in CI by creating the monitors and testing login there.
```
$ export TF_VAR_env=master
$ export TF_VAR_datadog_api_key=$(gov-pass datadog/dev/datadog_api_key)
$ export TF_VAR_datadog_app_key=$(gov-pass datadog/dev/datadog_app_key)
$ cd terraform/datadog
$ terraform apply -var-file=../ci.tfvars -target=datadog_monitor.login_with_wrong_password -target=datadog_monitor.user_not_found
```
Make many failed login attempts, watch the monitor fail and recover. You can tweak the threshold and time to make it fail faster.
```
$ while true; do echo "" | cf login -a …
```

[#134579301] UAA failed login monitors

---

manifests/cf-manifest/env-specific/cf-ci.yml

The story to change disk sizes in production clashed with the addition
of our first CI-specific manifest configuration. The CI manifest config
file was moved, but the elasticsearch_master disk configuration was
not added. This adds it.
See https://github.com/alphagov/paas-cf/pull/858
@paroxp preferably.

Bugfix: add elasticsearch_master disk size for CI

---

concourse/pipelines/create-cloudfoundry.yml
terraform/cloudfoundry/nat.tf
terraform/cloudfoundry/vpc_peering.tf
terraform/globals.tf
terraform/prod.vpc_peering.json
terraform/scripts/generate_vpc_peering_manifest.rb
terraform/scripts/generate_vpc_peering_tfvars.rb

This introduces VPC peering infrastructure to allow tenants access to their own VPC so they can expose services we don't have as brokers to their applications.
This also introduces the live configuration for DIT's VPC peering. Once this has been merged and deployed they should be notified that they need to accept the peering request and add the route.
It does this by having a per-environment json definition of the VPCs to peer with, along with who they belong to and what ranges to route. This json definition is then parsed during the pipeline and both a `tfvars` file is generated so that the VPC peering can be established & routing configured, and a CF manifest file is generated to configure a CF security group that can be bound to an organisation.
The workflow is as follows:
* We give a …

[#142066597] VPC peering

---

concourse/pipelines/create-cloudfoundry.yml
terraform/cloudfoundry/nat.tf

Use `aws_route` resources for the `internet` route table 
Terraform doesn't allow mixing routes defined inline in an
`aws_route_table` resource with separate `aws_route` resources[1]. We
need to start using the latter to add routes for the VPC peering, so we
need to migrate this.
This is non-straightforward because if we remove the inline `route`
statement, terraform won't remove the routes, which means that when it
attempts to create the replacement `aws_route` resource, it gets a
conflict. This is solved by modifying the tfstate file before
running terraform.
[1]https://www.terraform.io/docs/providers/aws/r/route_table.html
**Note:** depending on timings, we may include this in the VPC peering PR on Monday, but this would still benefit from a separate review.
Run this branch, and verify …

[#142066597] Extract aws_route terraform resources

---

manifests/cf-manifest/manifest/900-cf-tests.yml

To be on a safe side with acceptance tests we have decided to reduce
ginkgo nodes to 5 to decrease the load on cells and reduce possibility
to lose logs.
Sanity check
Not @combor

[#142302879] Reduce ginkgo nodes to 5

---

manifests/cf-manifest/manifest/020-cf-properties.yml

Those properties were deprecated some time ago and are not present in
v79 of metron spec:
https://github.com/cloudfoundry/loggregator/blob/v79/jobs/metron_agent/spec
Cleaning them as leftovers.
OK, I lied. This is actually just an excuse to deploy https://github.com/alphagov/paas-graphite-nozzle/pull/5 as we don't have any other trigger mechanism at the moment. 
Sanity check
Not @combor

[#142854167] Remove deprecated metron_agent properties

---

Makefile
terraform/scripts/generate_vpc_peering_manifest.rb
terraform/scripts/generate_vpc_peering_test.go
terraform/scripts/generate_vpc_peering_tfvars.rb
terraform/scripts/scripts_suite_test.go

These tests are mostly designed to spot incorrect .json VPC peer configurations, but they also minimally validate that the generators are working as expected.
* Code review.
* Run the tests.
* Twiddle the `prod.vpc_peering.json` until each of them breaks, or create a new one that is interestingly broken.
Not @jonty.

[#141777063] Tests for VPC peering config generation

---

concourse/pipelines/create-cloudfoundry.yml

This was added as part of #861 to allow migrating to a separate `aws_route` resource. Now that this has been applied in all environments, it can be reverted.
This reverts commit d35d69bf5ecb7af92d5b3d8b16f6a5ba3a5b8abf.
Code review - verify that it does indeed revert the above commit.

[#142066597] Revert "Modify cf.tfstate to extract aws_route resources."

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml

Story: [Block UAA create_account endpoints](https://www.pivotaltracker.com/story/show/143153295)
Deploy Nginx that will be used in front of UAA to block particular endpoints. The traffic is not routed to it yet. This will be done in PR https://github.com/alphagov/paas-cf/pull/873 to avoid downtime.
Also disable the self service links.
* Deploy
* Open https://login.colin2017.dev.cloudpipeline.digital.  Check the links "Create account" "Reset password" are absent
* SSH to UAA
* Check Nginx proxies successfully to UAA:
```
curl -i --resolve login.colin2017.dev.cloudpipeline.digital:127.0.0.1 https://login.colin2017.dev.cloudpipeline.digital:9443/login -k
```
* Check the endpoints create_account, create_account.do and forgot_password.do return 404:
```
curl -i --resolve …
```

[#143153295] Configure Nginx to block UAA endpoints

---

platform-tests/src/acceptance/account_management_test.go
terraform/cloudfoundry/elbs.tf

Story: https://www.pivotaltracker.com/story/show/134175741
Depends on: https://github.com/alphagov/paas-cf/pull/874 
Rebase this branch on master after above PR is merged.  
Following the change that introduced Nginx in front of UAA to block
create_account endpoints this points external ELB to Nginx proxy and
enables SSL between them.
Deploy and check if acceptance-tests pass
Not @saliceti or @combor

[#143153295] Point UAA ELB to Nginx

---

terraform/prod.tfvars

Lack of quotation made Terraform to fail miserably crying about
```
invalid value "paas-cf/terraform/prod.tfvars" for flag -var-file: Error
parsing paas-cf/terraform/prod.tfvars: At 82:20: literal not terminated
```
Sanity check
Not me

[Support] Fix literal not terminated

---

terraform/prod.tfvars

The duplicated IP caused live incident on PaaS. Terraform failed with:
```
Error applying plan:
3 error(s) occurred:
* aws_security_group.cf_api_elb: Error authorizing security group ingress rules: InvalidParameterValue: The same permission must not appear multiple times
status code: 400, request id: e39509db-3715-490f-a53f-3ce751fdd17e
* aws_security_group.sshproxy: Error authorizing security group ingress rules: InvalidParameterValue: The same permission must not appear multiple times
status code: 400, request id: 7ce7dce5-1c3b-43f6-a659-3901c62f50e4
* aws_security_group.web: Error authorizing security group ingress rules: InvalidParameterValue: The same permission must not appear multiple times
status code: 400, request id: 15047c12-7eee-482c-95d8-421c4ffaabe9
```
It left the security …

[#Support] Remove duplicate IP from whitelist

---

terraform/cloudfoundry/security-groups.tf
terraform/globals.tf
terraform/prod.tfvars

🐝 🐝 **THIS CAN BE REVIEWED, BUT DO NOT MERGE IT UNTIL AFTER EASTER WEEKEND**🐝🐝 
This duplicates the way we have set up access for `web_access_cidrs` for the API, removing the current set of whitelisted addresses and replacing it with 0.0.0.0/0. It also renames the configuration variable from `tenant_cidrs` to `api_access_cidrs` in order to bring it in line with `web_access_cidrs` and make the new purpose clearer.
I have not completely removed the whitelisting code because we still require the ability to toggle access between dev/prod, and I think that renaming things to make them clearer makes the .tfvars configuration easier to understand.
🐝 🐝**THIS CAN BE REVIEWED, BUT DO NOT MERGE IT UNTIL AFTER EASTER WEEKEND**🐝 🐝  
Copy the `api_access_cidrs` block from `prod.tfvars` to your …

Remove the API whitelist

---

terraform/datadog/aws.tf

AWS t2 instance types have burstable CPU performance. They accumulate
"credits" when not doing anything and then can consume the credits when they
want to do CPU intensive work. When the credits run out, the instance will
not be able to do CPU intensive work and will slow down. We want to know
when this happens because it is normally correlates to another problem/alert
and may indicate that we need to change the instance type in future.
There's a lot more information about the implementation in the commit message.
ℹ️  This PR depends on alphagov/paas-team-manual#111 ℹ️ 
⚠️  I've included a WIP commit that makes this easier to test, so you don't need to deploy all of the DataDog features and it uses the metrics from CI where we have the integrations enabled. You **must** rebase this commit …

[#141315433] Monitor CPU credits for t2 instances

---

concourse/pipelines/create-cloudfoundry.yml
manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml
manifests/cf-manifest/manifest/020-cf-properties.yml

Story: [Upgrade CF to version >= 254](https://www.pivotaltracker.com/story/show/142318777)
Upgrade to CF v256. Includes:
* diego-release: v1.12.0
* garden-runc-release: v1.4.0
* cflinuxfs2-rootfs release v1.60.0
* stemcell 3363.19 (latest)
* Upgrade UAA to v30 to cover latest CVEs
Revert of FIXME commits
* Deploy on top of deployment based on master
* Check all tests pass
* Consult guidance in [the team manual](https://government-paas-team-manual.readthedocs.io/en/latest/guides/upgrading_CF,_bosh_and_stemcells/) for a list of other things to check.
Not me or @saliceti

[#142318777] CF upgrade to v256

---

manifests/cf-manifest/manifest/020-cf-properties.yml

Yesterday we manually turned this off on the cells and routers in response
to an incident. We want to codify this change, so that we can unblock other
deployments, and then the correct fix will follow soon after.
When IPsec is re-enabled we will need to change the level to `use` and then
do a subsequent deployment with `require`.
These steps simulate CI and staging:
1. Deploy [dora](https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/dora) to your environment
1. Confirm that querying dora for `/largetext/10` hangs
1. Deploy from branch
1. Confirm that querying dora for `/largetext/10` works
You can simulate production, where IPsec has been disabled, by doing this first and then the steps above:
1. `make dev bosh-cli`
1. `for i in router/0 router/1 cell/0 cell/1 cell/2; …

[#144269245] Temporarily disable IPsec

---

platform-tests/src/availability/healthcheck_availability_during_deployment_test.go

CF upgrades that include stemcell changes can easily take longer than 2
hours to complete. When this happens, the `availability-tests` job in
Concourse will fail prematurely, and we will stop monitoring availability
for the remainder of the deployment until someone manually restarts it.
Ideally we'd have this wait for as long as the `cf-deploy` job is running;
the helper will stop the test as soon as the status changes to `succeeded`
or `failed`. But we *have* to give Ginkgo a timeout otherwise it will
default to 1s and we can't set polling interval without setting timeout. So
I've picked a reasonably high values of 12h instead.
Code review only.
You don't have to make the deploy take 12 hours and wait for it to fail 😄 
Not @dcarley

[#144269245] Increase timeout for availability-tests

---

concourse/pipelines/create-cloudfoundry.yml
concourse/pipelines/failure-testing.yml
concourse/tasks/custom-acceptance-tests-run.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
platform-tests/src/acceptance/response_size_test.go

garden-runc 1.3.0, which was included by the CF upgrade in 46019be, changed
the MTU of Guardian containers to match the host's external network
interface instead of always being 1500:
- cloudfoundry/guardian@af8d612
- cloudfoundry/garden-runc-release@a9b22fd
For our cells on AWS this meant a change from 1500 to 9001:
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network_mtu.html#jumbo_frame_instances
This didn't work well with IPsec, which we use to secure web traffic between
the routers and cells. Requests which generated responses larger than approx
9000 bytes were too large after the IPsec headers were added and never made
it back to the router.
It might have been nice to set this to a value a *bit* smaller than 9000, to
allow for the IPsec overhead, but we can't guarantee the …

[#144269245] Set MTU for Garden containers back to 1500 and add test

---

concourse/pipelines/create-cloudfoundry.yml
terraform/cloudfoundry/cf_rds.tf
terraform/datadog/aws.tf
terraform/datadog/uaa.tf
terraform/datadog/variables.tf

Similar to 1f33b77 for EC2 instances. I omitted this from the first PR
because I thought we didn't have any RDS t2 instances, but BOSH has been
since alphagov/paas-bootstrap@043f3dd.
The use of the `deploy_env` tag depends on alphagov/paas-bootstrap#59
I've used `dbinstanceidentifier` as the group `by` because it's a mandatory
attribute for RDS instances, unlike `dbname` (Terraform's `name` attribute)
or `name` (which comes from a standard AWS tag).
The `!created_by:aws_rds_service_broker` will prevent us from ever being
warned about the performance of tenant database instances which aren't
relevant to the health of our platform. The filter isn't strictly necessary
at the moment because they aren't tagged with `deploy_env`, but it's
possible that they could be in the future.
This is even …

[#141315433] Monitor RDS instances for CPU credits

---

terraform/datadog/aws.tf

The RDS monitor added in d8cfb6d is reporting "no data" in CI despite being
able to find metrics. This might be because the RDS metrics have a
resolution of 5mins compared to 2-3mins for EC2 metrics. We tested disabling
`require_full_window` and the monitor changed to "ok" state.
Although it's seemingly not affected at the moment, I'm applying the same to
the EC2 monitor to be safe. This still seems better than increasing the
window as described in 1f33b77. The other option would be to set "delay
evaluation" but that doesn't seem possible using the Terraform provider or
API.
Code review and check the state of CI after merging.
Ideally @Jonty or @saliceti

[#141315433] Unset require_full_window for CPU credit monitors

---

manifests/cf-manifest/manifest/020-cf-properties.yml

This is a partial revert of f400a1e once the MTU fix in bde67c5 has been
deployed to production. We need to bring IPsec back in `use` mode initially
and then later switch to `require` mode, as described in:
- https://github.com/SAP/ipsec-release#activating-ipsec-without-downtime
1. Confirm that #884 and #887 have been deployed to production 🐝  🐝  🐝 
1. Deploy from `master` to your dev environment
1. Deploy from this branch to your dev environment
1. Confirm that `availability-tests` pass, meaning that the change caused no downtime for applications
Not @dcarley

[#144269245] Re-enable IPsec pt1: use

---

manifests/cf-manifest/manifest/010-cf-jobs.yml

Story: [Add a doppler for availability zone 3](https://www.pivotaltracker.com/story/show/144447591)
We currently have only 2 dopplers and no doppler in zone 3. Metron connects primarily to the same zone so metron agents in zone 3 show this error message:
```
2017/04/27 13:38:14 Failed to lookup hostport: lookup z3.doppler.service.cf.internal on 127.0.0.1:53: no such host
```
As we are suffering from loggregator performance issues, it makes sense to add a doppler in z3
Code review
Not me

[#144447591] Add a doppler server in AZ 3

---

manifests/cf-manifest/manifest/020-cf-properties.yml

Once `use` mode has been deployed to production we can switch back to
`require` mode without downtime, as described in:
- https://github.com/SAP/ipsec-release#activating-ipsec-without-downtime
🐝  🐝  🐝 
TBC. Needs rebasing after #888 has been deployed to production.
🐝  🐝  🐝 
1. Confirm that #888 have been deployed to production 🐝  🐝  🐝 
1. Deploy from `master` to your dev environment
1. Deploy from this branch to your dev environment
1. Confirm that `availability-tests` pass, meaning that the change caused no downtime for applications
Not @dcarley

[#144269245] Re-enable IPsec pt2: require

---

terraform/datadog/etcd.tf

Story: [Make etcd leader monitor less sensitive](https://www.pivotaltracker.com/story/show/144441123)
The "etcd IsLeader count is exactly one" monitor is triggered every time
the leader count is different than one. However, this happens frequently
for a few seconds because of deployments or normal etcd re-elections and
this creates a lot of false alarms.
Now it will alarm if the count is continuously different than 1 on a 1
minute period. This is a short interval but this metric arrives every
20-30s so this should be enough.
* Reproducing etcd election issue is tricky. I suggest code review and:
* Run from paas-cf:
```
TF_VAR_env=<env> TF_VAR_datadog_app_key=$(paas-pass datadog/dev/datadog_app_key) TF_VAR_datadog_api_key=$(paas-pass datadog/dev/datadog_api_key) terraform apply …
```

[#144441123] Reduce false alarms due to etcd monitor

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml

Story: [Fix UAA CVE-2017-4974](https://www.pivotaltracker.com/story/show/144680665)
This release is a bugfix and has minimal changeset compared to v30.
See https://www.cloudfoundry.org/cve-2017-4974/ for details.
* Deploy and let all tests run
Not me

[#144680665] Bump UAA because of CVE 2017-4974

---

scripts/create-user.sh

With version 6.26 of the cli, the output from `cf target` has changed
slightly. The fieldname is now "user" (lowercase) instead of "User".
This was breaking the script.
Instead of just changing this, I've used the `tolower` awk function (as
described [here](https://unix.stackexchange.com/questions/273624/case-insensitive-search-in-awk)) so that it remains compatible with older versions of
the CLI.
Run the script against a dev environment with both version 6.25 and 6.26 of the cf cli (the `--no-email` flag is probably useful for this).

[Support] Fix create-user to work with cf-cli 6.26

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/010-cf-jobs.yml

This updates the stemcell to the latest in the series to pick up fixes for some USNs (see commit for details).
It also updates cflinux2-rootfs for the same reason (again see commit for details)
I've taken this opportunity to switch to the renamed boshrelease for cflinux2. This was [announced on cf-dev](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/XEX6Z2YMTYSPK3I6RQE6TQILKQESUDCB/), and the current release is deprecated, and will be discontinued at some point.
Deploy from this branch and verify all works.
Not me.

[#144763021] Bump stemcell and cflinux2 rootfs to fix USNs

---

platform-tests/src/availability/run_tests.sh

We increased the timeout of the long running `Eventually` block of the
`availability-tests` in 510471b but overlooked that we also have to provide
a timeout to `go test`.
I considered adding a comment to point people at one-or-the-other but it
seems unlikely that we'll need to change these values again.
Code review.
Not @dcarley

[#144269245] Increase `go test` timeout for availability-tests

---

concourse/pipelines/create-cloudfoundry.yml
concourse/tasks/custom-acceptance-tests-run.yml
concourse/tasks/smoke-tests-run.yml
platform-tests/src/acceptance/cf_ssh_test.go
platform-tests/upstream/run_acceptance_tests.sh
platform-tests/upstream/run_smoke_tests.sh

Now that the CF CLI issue has been fixed (with version 6.26) this test
can be increased.
Deploy from this branch and verify that the tests pass.
Note: alphagov/paas-docker-cloudfoundry-tools#92 must not be merged until this has been deployed to production.

[#142400337] Extend cf ssh tests to 10GB

---

concourse/pipelines/create-cloudfoundry.yml
concourse/tasks/custom-acceptance-tests-run.yml
concourse/tasks/smoke-tests-run.yml

This reverts commit bf4bb32f70dfd2534440279813a602e9374839cc.
See #900 for more details on why - we had to pin the acceptance tests container temporarily
Code review
Check the build has completed in dockerhub and the latest container uses the correct version of cf cli
I don't think you need to re run the acceptance tests as I think we can trust the tagged image and image built from master are roughly equivalent
Anyone but me

Revert "Use updated version of cf-cli containers."

---

platform-tests/example-apps/healthcheck/static/index.html
platform-tests/src/acceptance/cf_ssh_test.go
platform-tests/src/acceptance/healthcheck_app_test.go
platform-tests/src/acceptance/init_test.go
terraform/pingdom/pingdom.tf

The existing response body wasn't big enough to trigger the MTU bug that was
fixed by 4dd3c3f. By increasing the size and complexity of the response body
we hope to catch more edge cases like that bug, both in our pipeline tests
which are run after a deployment and our Pingdom checks which run all of the
time.
I've used the book "Alice's Adventures in Wonderland" because:
- at 220kB (on disk) it represents a reasonable sized website
- at 68kB (on disk after gzip) it is guaranteed to still be larger than our
MTU size of 9kB
- the content is free to use from Project Gutenberg
- it contains real HTML
I replaced `index.html` with the file `wget`ed from:
- https://www.gutenberg.org/files/11/11-h/11-h.htm
I considered using only some of the text, but it was easier to use the whole
thing, …

[#144515799] Make healthcheck responses more "real world"

---

concourse/pipelines/autodelete-cloudfoundry.yml
concourse/pipelines/create-cloudfoundry.yml
concourse/pipelines/destroy-cloudfoundry.yml
concourse/pipelines/failure-testing.yml
concourse/tasks/create_admin.yml
concourse/tasks/custom-acceptance-tests-run.yml
concourse/tasks/delete_admin.yml
concourse/tasks/get-instance-id.yml
concourse/tasks/kill-instance.yml
concourse/tasks/recover.yml
concourse/tasks/remove-healthcheck-db.yml
concourse/tasks/smoke-tests-run.yml
concourse/tasks/terraform_destroy_datadog.yml
concourse/tasks/upload-test-artifacts.yml

So that we can control how containers are updated between environments and
prevent forwards/backwards incompatibilities with code in the pipeline.
This will also prevent Concourse from re-downloading all of the containers
each time we merge a change to alphagov/paas-docker-cloudfoundry-tools
because Docker Hub rebuilds everything.
Using the functionality added in:
- alphagov/paas-docker-cloudfoundry-tools#93
1. Eyeball the diff and make sure that it looks sensible
1. Run at least one pipeline and confirm that it still works
Not @dcarley

[#145211537] Pin all governmentpaas containers to a version

---

doc/ssl_certs.md

It moved to a "real" hostname with a real certificate on the evening of
2017-05-11 as described in this announcement:
- https://sites.google.com/a/digital.cabinet-office.gov.uk/gds-internal-it/github-enterprise-change-5-30pm-6pm-11th-may-2017/githubdigitalcabinet-officegovuk
Code review only.
Not @dcarley

[#145266177] Update the URL for GitHub Enterprise

---

scripts/reset-org.py
scripts/reset-user-testing.sh

As `rotate-user-password.sh` has been deprecated in https://github.com/alphagov/paas-cf/commit/ab676558e78bffe476b555dbf20623e4be109904 we need to use `create-user.sh -r` instead.
Sanity check.
Not me

[#support] Replace rotate-user-password with create-user.sh -r

---

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
manifests/cf-manifest/manifest/020-cf-properties.yml
platform-tests/upstream/run_acceptance_tests.sh
platform-tests/upstream/run_smoke_tests.sh

Story: [Upgrade CF to version >= 257](https://www.pivotaltracker.com/story/show/144035107)
Deploys upgraded Cloud Foundry (257). This also includes an upgrade to Diago (1.13.0) and Garden-Runc (1.5.0).
No upgrades to stemcels or buildpacks are required for this release.
This PR keeps the patched version of UAA in and also reverts the large file transfer SSH test workaround.
1. Code review
2. Deploy from the branch
3. Rotate credentials - don't need to go out of `dev` environment
Not @paroxp or me

[#144035107] Upgrade CF to version 257

---

terraform/prod.vpc_peering.json

As requested in DeskPro ticket 5157. They have recreated the VPC in order to
fit subnets from all 3 availability zones into the 172.16.1.0/24 subnet. The
account ID remains the same.
1. Code review, there's no way to test this outside of production
1. Confirm that the details match the ticket: https://gaap.deskpro.com/agent/#app.tickets,inbox:agent,t.o:5157,vis:7
Anyone.

[SUPPORT] Change DIT peering VPC
