alphagov/paas-cf

- README.md
- Vagrantfile
README for paas-cf repository and Vagrantfile that simplifies Vagrant setup.
Basic information about how deployment chain operates and how to set-up your environment to be able to deploy your DEV Cloudfoundry instance.
Proofreading is highly welcome. Also, please follow `USAGE` section to check whether instructions are correct.
Anyone but @combor and @jimconner
> [#109515840] Add readme

- README.md
Update README formating
Basic information about how pipeline operates operates and how to set-up your environment to be able to deploy your DEV Cloudfoundry instance.
Proofreading is highly welcome. Also, please follow `USAGE` section to check whether instructions are correct.
Anyone but @combor and @jimconner   or @keymon
> [#109515840] Add readme (and 2)

- .travis.yml
- concourse/pipelines/create-deployer.yml
- concourse/scripts/deploy-pipeline.sh
- concourse/scripts/s3init.sh
- manifests/concourse-base.yml
- terraform/concourse/outputs.tf
- terraform/concourse/rds.tf
- terraform/concourse/security_group.tf
- terraform/globals.tf
- terraform/vpc/outputs.tf
- terraform/vpc/security-group.tf
Some comments were made on https://github.com/alphagov/paas-cf/pull/4 after it was closed. This PR fixes most of them.
* Formatting issues
* More explicit security groups
* Use spruce built-in `static_ips()` function
* Update Travis configuration
Build a new Concourse built on this branch.
Anyone but @saliceti
> [#109060102] Formatting

- terraform/globals.tf
This will be the source address for connections using the DR VPN.
> Include DR IP in list of office IPs

- concourse/scripts/create-deployer.sh
- concourse/scripts/create-microbosh.sh
- concourse/scripts/deploy-cloudfoundry.sh
- concourse/scripts/deploy-pipeline.sh
- concourse/scripts/destroy-cloudfoundry.sh
- concourse/scripts/destroy-deployer.sh
- concourse/scripts/destroy-microbosh.sh
Refactor the pipeline scripts to reduce duplication and make them more consistent. See individual commits for more details.
Deploy all of the pipelines to the Bootstrap and Deployer Concourse machines. You probably don't need to run them, so long as they are created and un-paused successfully.
```
./vagrant/deploy.sh && \
export FLY_TARGET=$DEPLOY_ENV && \
./concourse/scripts/create-microbosh.sh && \
./concourse/scripts/deploy-cloudfoundry.sh && \
./concourse/scripts/destroy-cloudfoundry.sh && \
./concourse/scripts/destroy-microbosh.sh
```
Anyone but @dcarley
> Refactor pipeline scripts

- README.md
Simplify the README by standardising the sections for each component.
You can either review the:
- complete diff
- individual commits
Either way you should also double check the rendered `README.md` in this branch to confirm that it looks visually correct and that the links work.
Not @dcarley
There may be one remaining PR in this story to refactor the pipeline scripts so that we have a single entry point to deploy the pipelines to either Bootstrap Concourse or Deployer Concourse.
> [#112135729] Simplify README pt2

- concourse/scripts/pipelines-cloudfoundry.sh
- terraform/ci.tfvars
- vagrant/Vagrantfile
To allow us to do deployments here.
This includes both a tfvars file for the DNS zones, and the networking
etc for the bootstrap-concourse in the `Vagrantfile`.
Verify that the details below match the values in the AWS console (will need access to the CI account to do this).
Anyone but me.
> [#112224869] Add config details for CI AWS account

- README.md
In https://github.com/alphagov/paas-cf/pull/129 we have implemented the new way of uploading Concourse pipelines based on Makefile. Now we want to update our documentation to reflect code changes.
Read instructions and decide whether they are sane.
Not myself.
> [#114080971] README adjustments based on new Makefile

- Makefile
- concourse/pipelines/create-bosh-cloudfoundry.yml
- concourse/scripts/pipelines-bosh-cloudfoundry.sh
- concourse/scripts/tag-release.sh
Story: [Create tags for deploying to staging and prod](https://www.pivotaltracker.com/story/show/115318605)
This produces a release tag at the end of the pipeline when all tests have passed so it can be picked up by the next Concourse on the way to prod.
This is controlled by the variable TAG_PREFIX. It is empty in DEV but it can be overriden for testing.
* Update the pipeline with a custom TAG_PREFIX:
```
BRANCH=115318605-create-staging-tags TAG_PREFIX=colin- make dev
```
* To skip acceptance tests, remove 'acceptance-tests' in the following lines:
```
- get: pipeline-trigger
passed: ['post-deploy', 'smoke-tests', 'acceptance-tests', 'custom-acceptance-tests']
trigger: true
- get: paas-cf
passed: ['post-deploy', 'smoke-tests', 'acceptance-tests', 'custom-acceptance-tests']
```
and update …
> [#115318605] Create release tags

- doc/non_dev_deployments.md
Describe the Github deployer keys. 
Read the changes and decide whether they make sense.  
Not @combor or @jimconner
> [#115858399] Add more details about deployer keys

- README.md
**What**
Add instructions to the readme on finding the concourse ip without logging into the console
Read the readme and follow the instructions to try logging into concourse and bosh
I'm not sure if this should be merged or if we should think about moving these
instructions to the makefile, but i'm raising the PR for visibility into the
command I used in case it is useful to others
**Who should review this PR**
Anyone but me
> Update Readme with instructions  on finding the concourse ip

- concourse/pipelines/create-deployer.yml
#211 updated this pipeline so that it would work with newer versions
of concourse and pass the linter. This fix wasn't complete because the
added outputs created empty directories that were no longer being
populated, meaning that later tasks couldn't find the necessary files.
This updates the pipeline to be closer to our styleguide and have output
names that are distinct from the task names. It is then explicit in
what's added to the output directorties.
Run the bootstrap pipeline for a new environment and confirm that it works.
> Fix bootstrap pipeline.

- README.md
> testing merger

- concourse/pipelines/create-bosh-cloudfoundry.yml
- concourse/scripts/pipelines-bosh-cloudfoundry.sh
- manifests/cf-manifest/deployments/060-aws-broker.yml
- manifests/cf-manifest/deployments/aws/060-aws-broker-stub.yml
- manifests/cf-manifest/scripts/generate-cf-secrets.rb
- manifests/cf-manifest/spec/fixtures/cf-secrets.yml
- tests/acceptance-tests/src/acceptance/rds_broker_test.go
[Service Broker Deployed to Production](https://www.pivotaltracker.com/story/show/117512347)
**Note**
https://github.com/alphagov/paas-aws-broker-boshrelease/pull/1 must be merged first before you can test this PR. 
**What**
As a PaaS Engineer I want an initial version of the Service Broker deployed to Production in order to provide a foundation for further work.
This story doesn't include getting the broker to work (except for the /catalog endpoint), but does include forking the broker and deploying it so it shows up on the marketplace
Checkout this branch and update your pipeline to use it. Deploy the cloudfoundry changes
Login to cloudfoundry and check you can run the marketplace command and see the broker
```
cf marketplace
```
**Who should review …
> [#117512347] Service Broker Deployed to Production

- concourse/scripts/import_bosh_ca.sh
- concourse/tasks/create_admin.yml
- concourse/tasks/delete_admin.yml
This fixes currently broken pipeline. Merge this before any other PRs.
Add missing inputs and tar switch to temporary admin tasks. A quick fix for PR merged too early https://github.com/alphagov/paas-cf/pull/244
Deploy. Check all tests run correctly.
not @mtekel
> PIPEFIX: Fix missing inputs for create/delete admin

- README.md
I foolishly forgot to sign PR #265 which has prevented anything from being
deployed to CI. This is a minimal change, which when signed and merged, will
allow deploys to CI again.
1. Merge the PR according to: https://government-paas-team-manual.readthedocs.io/en/latest/team/working_practices/#merging-pull-requests
1. Confirm that it deploys to CI
Not @dcarley
> Remove trailing newline from README

- manifests/cf-manifest/deployments/040-cf-properties.yml
Story: [Increase Quota for paas-demo org](https://www.pivotaltracker.com/story/show/119803023)
Create new paas_demo quota in code so we can aassign it to the paas-demo org.
* Apply on new or existing environment
* `cf quotas` should show the new quota
Anyone but me
> [#119803023] Create paas_demo quota

- manifests/cf-manifest/deployments/030-cf-jobs.yml
- manifests/cf-manifest/deployments/040-cf-properties.yml
As we are verifying SSL certificates everywhere there is no reason to skip verification for internal Diego components.
Deploy from this branch and check if tests pass. 
NOT @combor
> [#111678348] SSL cert verify for internal Diego Communication

- manifests/bosh-manifest/deployments/aws/000-bosh-infrastructure.yml
- manifests/bosh-manifest/reference-bosh-manifest.yml
- manifests/cf-manifest/deployments/aws/000-cf-infrastructure.yml
Story: [Upgrade Stemcells](https://www.pivotaltracker.com/story/show/119717133)
Update CF and BOSH stemcells to 3232.4 to get the latest security fixes.
* Deploy preferably to existing environment as this would simulate prod
* Wait for acceptance tests to pass
* Delete deployment
* Everything should work fine
Anyone but @mtekel or me
> [#119717133] Upgrade CF and BOSH stemcell

- concourse/scripts/spec/set_quotas_from_manifest_spec.rb
This was previously fixed as part of https://github.com/alphagov/paas-cf/pull/283, but due to Github having
issues at the time, a stale branch got merged which didn't include this
update.
Read conversation on https://github.com/alphagov/paas-cf/pull/283 and verify that this change is good.
> Remove unnecessary test setup in quota setting test.

- concourse/pipelines/create-bosh-cloudfoundry.yml
Fix the sync users directory issue from https://github.com/alphagov/paas-cf/pull/289
Same test as https://github.com/alphagov/paas-cf/pull/289
Anyone but me
> [#118838943] Fix user sync scripts directory

- concourse/scripts/bosh_pre_destroy.rb
To help us debug the intermittent test failures in Travis, this dumps
the environment, and the contents of the config file when an exception
is raised.
Code review changes. Verify that the tests still pass.
> Add some debug output on bosh_pre_destroy error.

- concourse/pipelines/create-bosh-cloudfoundry.yml
- concourse/scripts/pipelines-bosh-cloudfoundry.sh
- manifests/cf-manifest/deployments/runtime/runtime.yml
Story: [Reduce MTU of VMs to 1500](https://www.pivotaltracker.com/story/show/120368533)
Add a bosh addon job to set the MTU on the VMs.
This relies on PR https://github.com/alphagov/paas-os-conf-release/pull/2 to be reviewed at the same time. Once the paas-os-conf-release is merged, the [TEMP] commits here must be updated.
* Deploy
* Check the MTU is 1500 where it was 9001 originally on api_z1 for example
```
$ ifconfig |grep MTU
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
```
Anyone but @jimconner or me
> [#120368533] Set MTU via bosh addon

- scripts/create-user.sh
Updated create user script to visit Quick Start Guide
This will allow users to follow through what to do to get up and running on the platform.
Review text change. You can checkout the branch and try running the script to ensure the email arrives ok with the new text.
Anyone but Rory.
> Updated create user script to visit Quick Start Guide

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
- manifests/cf-manifest/manifest/010-cf-jobs.yml
Revert commit that was accidentally pushed directly to master.
Check the commit history.
Anyone but me
> Revert "Change router stemcells to 3232.6"

- manifests/cf-manifest/manifest/040-graphite.yml
Story: [Fix timeouts starting graphite](https://www.pivotaltracker.com/story/show/126296129)
Graphite upgrade to fix recursive `chown` in the carbon start script that becomes very slow when there are lots of metrics. 
* Check that carbon starts quickly even with lots of metrics
* Check carbon and graphite capture and display metrics correctly
Not @saliceti or @combor
> [#126296129] Update graphite-release with carbon fix

- manifests/bosh-manifest/deployments/aws/000-bosh-infrastructure.yml
- manifests/bosh-manifest/reference-bosh-manifest.yml
Story: [Upgrade stemcells](https://www.pivotaltracker.com/story/show/121564477)
This includes security fixes and we should apply them.
The chosen version matches our BOSH version. BOSH and the stemcell are in the same repository and stemcell updates are applied to different BOSH versions in separate branches.
Separate PRs will be made for CF and Concourse.
* Deploy to an existing environment
* Check that all tests pass
> [#121564477] Update bosh stemcell to 3232.13

- manifests/concourse-manifest/concourse-base.yml
Story: [Upgrade stemcells](https://www.pivotaltracker.com/story/show/121564477)
This includes security fixes and we should apply them.
The chosen version matches our BOSH version. BOSH and the stemcell are in the same repository and stemcell updates are applied to different BOSH versions in separate branches.
Separate PRs will be made for CF and BOSH.
* Deploy to an existing environment
* `make dev bootstrap`
* Visit http://localhost:8080/pipelines/create-deployer
* Run `create-deployer` pipeline
* Check the main pipeline in the deployer concourse still runs fine
* Pause the pipelines before recreating the deployer concourse
* Wait for the job to finish CI before recreating staging bootstrap
* Wait for the job to finish staging before recreating prod bootstrap
> [#121564477] Update concourse stemcell to 3232.13

- concourse/pipelines/create-bosh-cloudfoundry.yml
🚨  **Note:** This should not be merged until #380 has been deployed to production.
Cleanup the temporary code to remove the unused quotas.
Code review
> [#126686741] Cleanup FIXMEs removing deprecated quotas.

- concourse/chrome_plugin/src/inject.user.js
Some of the markup has changed with the new version of Concourse, so we need to update this plugin so that the dashboard continues to lack cruft.
* Add the plugin to your browser as described in the [README](concourse/chrome_plugin/README.md). 
* Verify that the legend, and lower-right details are removed.
* Verify that the top navbar is replaced with parts of the hostname.
> [#117991263] Update concourse browser plugin for new version.

- .gitignore
- Makefile
- README.md
- doc/pingdom.md
- terraform/pingdom/pingdom.tf
- terraform/providers/.terraformrc
- terraform/scripts/set-up-pingdom.sh
Story: [Email Alerts from Pingdom](https://www.pivotaltracker.com/story/show/120100877)
We want to be able to set up Pingdom checks that alert us via email.
The resolution is changed to be alerted more quickly in case of downtime.
The pingdom configuration and build is now documented extensively.
* Install the custom provider using the instructions from the [pingdom doc](https://github.com/alphagov/paas-cf/blob/7f0ef19d6437d7594548705bf4a2f5c3c5ae88f2/doc/pingdom.md). Use branches in https://github.com/alphagov/paas-terraform-provider-pingdom/pull/3 and https://github.com/alphagov/paas-go-pingdom/pull/2. Run the make command.
* Connect to pingdom and observe the checks are created and configured correctly
* Delete the checks
Anyone but @HenryTK or myself
> [#120100877] Set up pingdom email alerts

- manifests/cf-manifest/grafana/user-impact.json
- manifests/cf-manifest/grafana/vm-resource-usage.json
- manifests/shared/deployments/collectd.yml
This makes several changes to the User Impact Grafana dashboard in response to our experience of using it. See the commits for details of the individual changes.
Deploy pipeline from this branch (deploy is necessary to apply the collectd change), load up the User Impact dashboard in Grafana, and verify that the [requested changes](https://www.pivotaltracker.com/story/show/127161593) have been made, and look sensible.
Anyone but @combor or myself.
> [#127161593] Make user impact dashboard moar AWESOME!!!

- README.md
Improve readme to add things I forgot and that our scripts sometimes assume one knows.
Check the `./README.md` file still makes sense
Anyone but @benhyland
> Add detail on `aws s3` and `AWS_DEFAULT_REGION` to readme

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-bosh-cloudfoundry.yml
- concourse/pipelines/destroy-cloudfoundry.yml
Missed second commit
Reverts alphagov/paas-cf#458
> Revert "[#123003931] Gate running of availabity tests on healthcheck being deployed"

- Makefile
- concourse/scripts/ssh.sh
Add ssh_concourse target to makefile and a script it points to to ssh to concourse - for convenience.
`make dev ssh_concourse`
not @mtekel
> Makefile: add ssh_concourse target

- Makefile
The output from `gpg --list-keys --with-colons` has changed between gpg
version 1.4 and 2.
1.4:
```
$ gpg --list-keys --with-colons 14491C3B34141441
tru::1:1472766925:1549885469:3:1:5
pub:f:2048:1:14491C3B34141441:2012-09-03:::-:Alex Tomlins <alex.tomlins@digital.cabinet-office.gov.uk>::scESC:
sub:f:2048:1:59F1AEBB3A532D3C:2012-09-03::::::e:
```
2.0:
```
$ gpg --list-keys --with-colons 14491C3B34141441
tru::1:1472807696:1473327764:3:1:5
pub:u:2048:1:14491C3B34141441:1346678456:::u:::scESC:
uid:u::::1346678456::BE7B1C9571B9C159A1FFFF170F999708841F51FA::Alex Tomlins <alex.tomlins@digital.cabinet-office.gov.uk>:
sub:u:2048:1:59F1AEBB3A532D3C:1346678456::::::e:
```
This updates the awk script to detect the gpg version, and when it's gpg
2, look at the uid element in the results. Additionally, …
> Fix list_merge_keys make target for gpg2

- .travis.yml
- concourse/scripts/extract_terraform_state_to_yaml.rb
- concourse/scripts/extract_tf_vars_from_terraform_state.rb
- concourse/scripts/pipelines-bosh-cloudfoundry.sh
- terraform/bosh/outputs.tf
- terraform/cloudfoundry/aws_backing_services.tf
- terraform/cloudfoundry/cell-subnet.tf
- terraform/cloudfoundry/cf-subnet.tf
- terraform/cloudfoundry/elb_access_log_bucket.tf
- terraform/cloudfoundry/rds_broker.tf
- terraform/cloudfoundry/router-subnet.tf
- terraform/concourse/security_group.tf
- terraform/vpc/outputs.tf
- terraform/vpc/security-group.tf
- terraform/vpc/subnet.tf
Adjust pipeline, scripts and TF config to support TF 0.7.3. See https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/69 for TF container upgrade.
Apply from bootstrap, then run create-bosh-cf pipeline. Run all destroy pipelines. After https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/69 is merged, remove TMP commit. Test creating pingdom alerts.
https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/69 updates container in all environments which will break TF for them. Only merge that PR when you're ready to merge this and when there are no other jobs running in the pipelines, as this has to be 1st PR to go through pipelines after container upgrade.
> [#130003999] upgrade terraform to 0.7.3

- Makefile
- README.md
- concourse/scripts/ssh.sh
When providing support for the platform, we often need to create SSH tunnels via the Concourse host to access internal IPs, internal ELBs, or external DNS resolving to internal IPs.
This extends the `ssh.sh` script to allow creation and deletion of SSH tunnels.
Use case: get Elastic search cluster status.
* Export usual environment variables: DEPLOY_ENV, AWS keys, etc
* Create tunnel to known IP:
```
$ make dev tunnel TUNNEL=9200:10.0.16.10:9200
download: s3://master-state/concourse_id_rsa to ../../../../../../../tmp/concourse_id_rsa.9975
Creating tunnel at socket /Users/colin/ssh_tunnel_socket.ctl to 9200:10.0.16.10:9200
Warning: Permanently added '52.49.176.99' (ECDSA) to the list of known hosts.
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and …
```
> [#130267877] Automate creation of SSH tunnels

- doc/pingdom.md
We now use Terraform 0.7.3. Change documentation to reflect that.
Read it. Check it makes sense.
Anyone but me.
> [#130003999] Amend Pingdom documentation

- README.md
This just bit me.
Agree with it. Ideally test that this is true.
Not @jonty.
> Add guidance about disabling acceptance tests

- config/admin_users.yml
Create CF accounts on ci, staging and prod for Rafal.
Verify that this looks right, and that the gpg_key is indeed Rafal's
> [#134275945] Add Rafal to admin_users.yml

- scripts/create-user.sh
We'd like to link to our privacy policy in the email. A new paragraph, has been added into the email content.
Attempt to create new user for your dev environment, `your.name+test123@gds.long.email.com`. You should receive an email, with the following paragraph:
```
...
You can find our privacy policy here:
https://government-paas-developer-docs.readthedocs.io/en/latest/getting_started/privacy/
...
```
Not @paroxp
> [#121413067] Add a privacy policy paragpraph

- tools/paas_dashboard/jobs/datadog.rb
> Fix dashboard to match warn states in monitors

- manifests/cf-manifest/cloud-config/030-logsearch.yml
Story: [Increase elastic search disk space](https://www.pivotaltracker.com/story/show/135207351)
We need to increase the disk space as we are close to filling up the disk.
* code review
Anyone but me
> [#135207351] Increase elastic search disk space

- concourse/pipelines/create-bosh-cloudfoundry.yml
- terraform/datadog/concourse-jobs.tf
Fix for continuous smoke tests and pipeline time graphs.
I recommend code review and manual experiment in a dashboard such as:
https://app.datadoghq.com/dash/189179/master-job-runtime-difference?live=true&page=0&is_auto=false&from_ts=1480089961639&to_ts=1480694761639&tile_size=m
Anyone but me
> Fix concourse graphs

- concourse/pipelines/create-bosh-cloudfoundry.yml
- concourse/scripts/pipelines-bosh-cloudfoundry.sh
- manifests/cf-manifest/manifest/800-logsearch.yml
Story: [Junk logstash mappings being created & breaking Kibana](https://www.pivotaltracker.com/story/show/131722035)
We have an issue with a log message from the auctioneer. It contains:
`"data":{"lrps":{"df03138b-924d-417e-9743-abf81e577a70-7276869e-d03c-4ffd-9f83-18c366a390c3":[1]},...,"request":"/v1/lrps",...}`
Elasticsearch assumes
`auctioneer.data.lrps.df03138b-924d-417e-9743-abf81e577a70-7276869e-d03c-4ffd-9f83-18c366a390c3`
is the name of a field, because it contains an array of integers. So it creates a mapping for each new LRP GUID.
This PR adds a logstash filter that changes the hash to an array containing the GUID strings.
This depends on the code from PR
https://github.com/alphagov/paas-logsearch-for-cloudfoundry/pull/1
* On an existing environment, search for …
> [#127564379] Fix lrps mapping

- platform-tests/src/acceptance/http_forwarded_for_test.go
I was meant to rewrite an existing story for this before I went on leave, but I didn't and I now can't find it. While looking for that story I noticed that we have a new story for our incorrect `X-Forwarded-For` header behaviour (Pivotal ID in subject). These changes should make it easier to do that work in the future. I'm not going to move the card in Pivotal and reviewing other stories should take precedence to reviewing this.
The existing tests for individual indexes of the XFF slice made it quite
hard to understand the complete behaviour. For example, the real egress IP
is the second-to-last element rather than the last element.
They were also susceptible to false-positives because we were checking that
the second element didn't belong to a 10/8 private network, rather than
asserting …
> [#130728371] acceptance-tests: Improve XFF header tests

- concourse/scripts/concourse-lite-self-terminate.sh
- concourse/scripts/deploy-pipeline.sh
- concourse/scripts/lib/datadog.sh
- concourse/scripts/pipelines-bosh-cloudfoundry.sh
- concourse/scripts/pipelines-deployer.sh
As part of the work to migrate to paas-bootstrap, we've done some refactoring of the pipeline scripts. In order to ease the review of the migration itself (which will be fairly large), we've decided to PR these separately.
Code review
Anyone but @dcarley or myself.
> [#131876783] Some pipeline script refactorings

- concourse/pipelines/create-bosh-cloudfoundry.yml
- concourse/scripts/pipelines-bosh-cloudfoundry.sh
- manifests/cf-manifest/runtime-config/runtime-config-base.yml
As the problem with MTU has been fixed by amazon already we can remove this temporary fix and maintain one release less.
This reverts 8edc941 and 9ef009f. More details about MTU problem in referenced commit descriptions.
This also fixes problems with upcoming IPSEC release that we discovered. IPSec adds additional headers and authentication data so increases packet size. Some requests were exceeding MTU and than dropped causing connectivity issues.
[More info can be found here.](http://www.cisco.com/c/en/us/td/docs/interfaces_modules/services_modules/vspa/configuration/guide/ivmsw_book/ivmvpnb.html)
Obtain your ELB A record from AWS console and export it into `ELB` env variable.
```
export ELB="piotr-dev-cf-loggregator-1885377316.eu-west-1.elb.amazonaws.com"
```
Once, your custom ELB has …
> [#131802383] Remove MTU settings

- Makefile
- concourse/pipelines/create-bosh-cloudfoundry.yml
- concourse/scripts/pipelines-bosh-cloudfoundry.sh
Story: [Productionnecker](https://www.pivotaltracker.com/story/show/136340183)
Automate deployment of node.js app rubbernecker from master branch of
repo https://github.com/alphagov/paas-rubbernecker
* Make sure your credentials repo is up-to-date
* Deploy by setting DEPLOY_RUBBERNECKER environment variable to "true"
* Access `https://rubbernecker.<env>.dev.cloudpipelineapps.digital` and check it's ok
* Delete current rubbernecker from production (org paas-demo / space prod). Delete app AND route
Not me
> [#136340183] Deploy rubbernecker app with the pipeline

- doc/non_dev_deployments.md
How to obtain and rotate TLS certs from digicert
[#133198093](https://www.pivotaltracker.com/story/show/133198093)
Document how to rotate TLS keys/certs
Log into digicert and check the instructions make sense. 
It probably doesn't make sense to rotate or obtain any certificates, but you should be able to see enough for review from the web interface
Anyone with access to the high creds store - I think thats @bleach @henrytk @dcarley and @alext
> [#133198093] Document digicert TLS certificate process

- platform-tests/src/availability/healthcheck_availability_during_deployment_test.go
This makes it much easier to correlate any failures with CF logs etc.
Code review. Run availability tests and verify output looks good.
Anyone but myself (and probably @dcarley whose commit I lifted this from)
> [Support] Add timestamp to availability tests.

- terraform/prod.tfvars
Cabinet Office would like to try the PaaS out, with a view to possibly
deploying People Finder on it.
I would leave it for CI concourse to test but if you like you can deploy it on dev 
Not @combor
> [#139005259] Whitelist  Cabinet Office IP

- Makefile
We've upgraded Terraform in the pipelines, so we should ensure we're
using the same version when running the local tasks for consistency.
Try to run one of the local terraform tasks with an older terraform version and verify it errors. eg:
`ACTION=plan make dev pingdom`
> Update tf version check for 0.8.5

- terraform/prod.tfvars
[Create Org and Users for Parliamentary Web Services](https://www.pivotaltracker.com/n/projects/1275640/stories/139371571/comments/162752927)
Add them to production API whitelist so that they can access and manage
their org and spaces. Pivotal story: #139371571
Check that this is the IP mentioned in the story.
not @mtekel
> [#139371571] Whitelist parliamentary web services IP

- terraform/prod.tfvars
Whitelist Digital Marketplace Jenkins IP
Code check. Check that the IP matches one in support case #3635
not @mtekel
> Whitelist Digital Marketplace Jenkins IP

- concourse/scripts/update_monitor_options_test.go
We noticed that Travis can be pretty slow to run tests so we have to
increase session timeout to avoid occasional failures.
Review code changes
Not @combor
> Increase assertion timeout

- concourse/scripts/self-update-pipeline.sh
- manifests/cf-manifest/scripts/generate-cf-certs.sh
Remove FIXMEs that have been fixed to clean up code a bit.
Code review.
not @mtekel
> Cleanup fixed FIXMEs

- README.md
A follow-up to our discussion this morning - we do require real email addresses for users, so that there is someone to respond to our notifications/queries (in case we need to notify/reach user "owner" - if it's e.g. a CI user). Also update outdated email verification instructions.
Proofread.
not @mtekel
> Update user creation in README

- terraform/prod.tfvars
What?
---
As per ticket #3714 [1], add the IP of MOJ to the whitelist to access
the API endpoints.
[1] https://gaap.deskpro.com/agent/#app.tickets,t:3714
How to review
------------
Code review
Who?
----
> [#SUPPORT] Add IP from MOJ digital and technoogy to access

- terraform/prod.tfvars
[#140308141 Create org and users for new tenant prototypes](https://www.pivotaltracker.com/n/projects/1275640/stories/140308141)
What?
-----
We want to allow the new tenant prototypes from a skyscape list of ips
We whitelist the skyscape IPs for the ticket[1]
[1] https://www.pivotaltracker.com/n/projects/1275640/stories/140308141
How to review?
-------------
code review
Who?
---
> [#140308141] Whitelist skyscape IPs for #140308141

- Makefile
This is currently breaking the build because the AWS cred check doesn't work when
run in the pipeline. Reverting this while we work out a fix for this.
This reverts commit e1a9a229ea543a369136d4553b41b7ebd1cf4d6c (part of #730).
Run the pipeline from this branch and verify that the self-update-pipelines task runs correctly.
> Revert "Makefile: refactor environment check"

- terraform/prod.tfvars
Story: https://www.pivotaltracker.com/story/show/140564011
Verify the change is well-formed, and that the IP matches the one requested in the story.
> [#140564011] Whitelist another IP for DIT.

- terraform/prod.tfvars
Add an IP address for mod-dbs-trial to the whitelist
https://gaap.deskpro.com/agent/#app.tickets,t:3858
[#140768615](https://www.pivotaltracker.com/n/projects/1275640)
Check the ip matches that in the deskpro ticket and the changes look like they will work
Anyone but me
> [#140768615] IP whitelist for mod-dbs-trial

- scripts/ssh.sh
Story: [Fix ssh_concourse](https://www.pivotaltracker.com/story/show/140853603)
There was a typo that was not a problem before, but now we check AWS credentials and this was failing.
Try `ssh_concourse` on a non DEV environment
Not me
> [#140853603] Fix CONCOURSE_IP in ssh.sh script

- terraform/prod.tfvars
Story: [Add IP address for Innovision/DIT Horizon](https://www.pivotaltracker.com/story/show/140917515)
Add IP address for Innovision/DIT Horizon to CF API whitelist.
Code review
Not me
> [#140917515] Add Innovision/DIT Horizon IP to whitelist

- terraform/prod.tfvars
Deskpro ticket 3953
Whitelist notify IPs to connect to paas from their private subnet where they can export data and import in paas.
Code review
Not me
> Whitelist notify IPs to export data to paas

- manifests/cf-manifest/manifest/050-rds-broker.yml
[#133533671 Update RDS broker dependencies.](https://www.pivotaltracker.com/story/show/133533671)
What?
----
Include changes from https://github.com/alphagov/paas-rds-broker/pull/39 and https://github.com/alphagov/paas-rds-broker-boshrelease/pull/33
WIP: Update this after PRs are merged
Dependencies
------------
* paas-rds-broker PR (must be reviewed, merged and update this one) https://github.com/alphagov/paas-rds-broker/pull/39
* paas-rds-broker-bosrelease https://github.com/alphagov/paas-rds-broker-boshrelease/pull/33
Who?
----
> WIP: [#133533671]  Upgrade rds-broker with new dependencies

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/pipelines-cloudfoundry.sh
[#140939907 Delete old product page](https://www.pivotaltracker.com/story/show/140939907)
What?
----
Reverts b39fe427606c7c38d08775aeb85bd1b90dd67cfa, not necessary after
merging https://github.com/alphagov/paas-product-page/pull/8
How to review?
-------
Code review
Who?
---
> [#140939907] Remove the deploy of paas-roadmap

- terraform/prod.tfvars
So that they can access the platform.
Verify that the change is well-formed, and that the IPs match those in [the story](https://www.pivotaltracker.com/story/show/141476575)
> [#141476575] Add IPs for BEIS trial.

- terraform/prod.tfvars
https://gaap.deskpro.com/agent/#app.tickets,t:4076
Pay's CI server has changed IP address.
Review for accuracy only.
> [Deskpro #4076] Update Pay CI IP address

- terraform/prod.tfvars
Requested from Deskpro:
- https://gaap.deskpro.com/agent/#app.tickets,inbox:agent,t.o:4193,vis:7
Confirm that the IP matches the DeskPro request and is syntactically valid.
Not @dcarley
> [support] Add new API whitelist IP for mod-dbs-trial

- terraform/prod.tfvars
After the communication on DeskPro, Muhammad requested two additional IP
addresses to be registered on our whitelist.
Please, follow the conversation on DeskPro with ID 4328.
Define if these IPs belong to DWP CA.
Not @paroxp
> [#142128979] Add additional IP addresses for DWP CA

- manifests/cf-manifest/manifest/env-specific/cf-prod.yml
In order to support more load and ensure enough cells are up, we'd like
to add aditional cell to each zone, while adding DWP Carer's Allowance.
Change requested by Dan in #142128979.
Assess the need and sanity of increase.
Not @paroxp
> [#142128979] Increase number of cells

- terraform/cloudfront/instances.tf
We're renaming the application we're hosting. In order to ensure, it shan't go down, we'll deploy it under a new name and route.
The old application will be deleted, upon merging of this commit, therefore we need to ensure CloudFront will be reading from a new route straight away.
Sanity check should be sufficient enough.
Make sure, this is deployed AFTER the new application is up and running.
> [#140832481] Update the product page route

- terraform/prod.tfvars
See DeskPro for full details of their request for a trial account and product manager approval. This is not associated with a Pivotal story.
Check `whois 217.33.141.90` to confirm this is not a dynamic IP, such as those provided by domestic broadband services. Check the Terraform code looks correct. 
Anyone but me.
> Whitelist DWP Overseas Healthcare Service

- doc/vpc_peering.md
Documentation on how to set up VPC peering.
Check it makes sense.
Ideally @alext.
> [#141777063] Quick documentation on how to set up VPC peering

- terraform/prod.tfvars
DIT needs new org and several of new IPs to be unblocked
Ticket: https://gaap.deskpro.com/agent/#app.tickets,inbox:agent,t.o:4741,vis:7
Sanity check
Not me
> Whitelist DIT services

- concourse/pipelines/create-cloudfoundry.yml
- terraform/datadog/aws.tf
This reverts commit a6c877ae3ec3c479968cf3769d7c48fc65861d9b.
It should have been rebased out of the PR before merging.
Code review.
Ideally @Jonty or @saliceti
> [#141315433] Revert "WIP: Test CPU credits monitors in dev"

- terraform/datadog/concourse.tf
This introduces a new monitor tracking the number of btrfs processes running at any one time. When concourse starts to fail the number of processes spikes drastically, so this should allow us to quickly spot when concourse needs shaking before the load average catches up.
🐝 https://github.com/alphagov/paas-bootstrap/pull/60 should be merged and deployed before this, although really it doesn't matter much 🐝
At @alext's suggestion this also tweaks the existing CPU load monitor so that it will trigger within a minute of the load average spiking over the limit.
* Deploy https://github.com/alphagov/paas-bootstrap/pull/60 to your concourse
* Deploy this PR to your cluster (with `ENABLE_DATADOG=true`)
* Check that a `$DEPLOY_ENV concourse excess btrfs processes running` monitor has been created …
> [#144515851] Better concourse thrashing monitoring

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
Due to 3 CVEs we have to update stemcell and cflinux2 versions. Details in commit messages.
Sanity check. You can run pipeline to verify if you have spare time. 
Not @combor
> [#CVE] Stemcell and cflinux2 version bump

- terraform/prod.vpc_peering.json
Details in Deskpro ticket 5766
This is a new VPC they've setup to provision things needed (initially
Redis) by various services they're putting onto the PaaS.
* Code review
* Read Deskpro ticket and verify this matches what's requested.
Not me
> [Support] Setup new VPC peering connection for DIT services

- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/lib/compose.sh
- concourse/scripts/pipelines-cloudfoundry.sh
- scripts/upload-compose-secrets.sh
This pins version of compose-broker. Also it deploys few fixes to prefix broker managed DBs.
- Deploy and check if it works
- merge https://github.com/alphagov/paas-compose-broker/pull/3
- tag `master` from https://github.com/alphagov/paas-compose-broker to `v0.1.0`
- remove the temporary commit 
Not me.
> [#143876117] Pin compose-broker version

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
For https://www.cloudfoundry.org/usn-3334-1/
Code review only. Check that it's the correct stemcell version specified by the USN.
I've tested it in dev, upgrading from the `master` branch, and the `availability-tests` passed.
Anyone.
> [#147669197] Upgrade stemcell for USN-3334-1

- platform-tests/example-apps/healthcheck/Godeps/Godeps.json
- platform-tests/example-apps/healthcheck/db.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/.gitignore
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/.travis.yml
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/AUTHORS
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/README.md
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/connection.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/connection_go18.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/driver.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/dsn.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/infile.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/packets.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/rows.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/statement.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/transaction.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/utils.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/utils_go17.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/utils_go18.go
- platform-tests/example-apps/healthcheck/vendor/github.com/go-sql-driver/mysql/utils_legacy.go
Enable and fix TLS verify for the healtcheck app using the MySQL service.
1. Deploy the branch
1. Check that this command:
curl -k https://healthcheck.${DEPLOY_ENV}.dev.cloudpipelineapps.digital/db\?service\=mysql\&ssl\=true
Returns:
{
"success": true
}
Anyone
> [#147829023] Verify MySQL TLS certificate for healthcheck

- concourse/scripts/kibana_set_utc_test.go
- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
- manifests/cf-manifest/manifest/010-cf-jobs.yml
- manifests/cf-manifest/manifest/020-cf-properties.yml
- manifests/cf-manifest/scripts/create-cf-dbs.sh
- manifests/cf-manifest/scripts/generate-cf-secrets.rb
This is CloudFoundry upgrade to v264. To find more details about changes please read relevant pivotal story: https://www.pivotaltracker.com/story/show/145682111
- Deploy on top of master - wait for acceptance tests to finish.
- Refer to our [team manual](https://government-paas-team-manual.readthedocs.io/en/latest/guides/upgrading_CF,_bosh_and_stemcells/) for complete notes on what needs to be covered.
Not @henrytk or @combor
> [#145682111] CF release v264 update

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
For https://www.cloudfoundry.org/usn-3378-2/
Code review only. Check that it's the correct stemcell version specified by the USN.
I've tested it in dev and the `availability-tests` passed.
@dcarley has also tested in dev, upgrading from a branch
Anyone, but @dcarley might have some context
> Upgrade stemcell for USN-3378-2

- concourse/pipelines/create-cloudfoundry.yml
We left quite a lot FIXMEs after https://github.com/alphagov/paas-cf/pull/991
This PR cleans them up.
Do a sanity check. 
Not @combor
> [#148289089] Remove leftovers after #991

- scripts/usage_reporting/README.md
- scripts/usage_reporting/dump_cf_events.py
- scripts/usage_reporting/event.go
- scripts/usage_reporting/generate_service_events.go
- scripts/usage_reporting/process_events.go
Merge the usage reporting utilities into `master` because we've been using them longer than we originally intended and there are some undesirable consequences of having them on a branch:
- they are hard to locate
- the branch might be mistakenly deleted
- we aren't doing any code review for changes
Do you agree with my rationale?
The last two commits that I added during this story can be code/content reviewed.
Anyone.
> [#150168418] Usage reporting utiliities

- concourse/pipelines/create-cloudfoundry.yml
This was erroneously added in a1935056c and duplicates the same job
further down this file.
Code review. Verify that this job is indeed a duplicate.
Not me.
> Remove duplicated bosh cleanup job from pipeline.

- concourse/scripts/rds_instances.sh
The script will only run successfully if all the databases are in the previous
state (e.g. all stopped when we want to start them). If we compare the current
state to the full RDS instance list it will be able to run successfully in any
situation.
This caused an issue in two scenarios:
- if you're databases are already running the kick-off pipeline will fail
- if only some of your databases were able to start up the kick-off pipeline will fail
It's easier to run the script manually locally: ```./concourse/scripts/rds_instances.sh [start|stop]```
Please test the following scenarios:
- if you're databases are already running the start command should finish quickly
- if you stop one database the start command should start it up and finish
- if you stop a database then the stop command should …
> When starting/stopping the RDS databases we should check against the full database list

- .travis.yml
- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/scripts/pipecleaner.py
- concourse/tasks/create_admin.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/get-instance-id.yml
- concourse/tasks/kill-instance.yml
- concourse/tasks/recover.yml
- concourse/tasks/remove-billing-db.yml
- concourse/tasks/remove-healthcheck-db.yml
- concourse/tasks/terraform_destroy_datadog.yml
- scripts/validate_aws_credentials.sh
We were previously skipping several checks because it was deemed to much
work to fix them all when shellchecking was introduced to the pipelines.
This re-enables these checks and fixes resulting warnings/errors.
Code review is probably enough (may be easiest commit-by-commit)
You could run the pipelines from this branch to test things. I've been running my dev env using this branch for a couple of days now.
Not me.
> [#152067205] Improve shellcheck linting for pipelines

- config/admin_users.yml
Create admin CF account for Sam Crang
Who should now have production access.
Check that I haven't typoed Sam's email address?
Anyone with merge privileges.
> [#152513736] Create admin CF account for Sam Crang

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
This PR updates the stemcell in use to the latest from the 3468 series.
Deploy from this branch on top of current master in your dev environment. Verify that all tests pass
Not @LeePorte
> [#152510403] Update stemcell to 3468.5

- terraform/datadog/cell.tf
Implement alerts in accordance with [ADR021](https://github.com/alphagov/paas-team-manual/pull/156). See the commit messages for more details.
* We've tested applying the monitors on a dev environment, and tested that one does alert. Code review should suffice.
Not @46bit @camelpunch
> [#131354667] Implement alerts for ADR021

- manifests/cf-manifest/env-specific/cf-prod.yml
:bee: **please merge https://github.com/alphagov/paas-cf/pull/1118 first, so alerts are deployed before this change.** :bee: 
Reduce the number of cells by 25%, to begin our path to implementing [ADR021](https://github.com/alphagov/paas-team-manual/pull/156). See the commit messages for more details.
* Check we've reduced the number of cells appropriately to https://github.com/alphagov/paas-team-manual/pull/156.
Not @46bit @camelpunch
> [#131354667] Reduce number of cells by 25% to begin ADR021

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
Upgrade stemcell version. The version we are upgrading to resolves some Kernel related CVEs.
https://www.cloudfoundry.org/usn-3509-2/
See the notes in the Pivotal Tracker story. Make sure the availability tests don't fail (a lot). Make sure the other tests pass.
Anyone.
> [#153551006] Upgrade Stemcells

- concourse/pipelines/create-cloudfoundry.yml
See commit message.
Code review should suffice.
Not @camelpunch @46bit
> [#153091168] Share cloud.service.gov.uk with govuk-paas org

- terraform/cloudfront/cloudfront_distribution/distribution.tf
- terraform/cloudfront/instances.tf
- terraform/scripts/set-up-cdn-instances.sh
See commit message.
* Code review
* These changes need manually applying, but in the Pivotal story we've specified that as an Approval task.
Not @46bit @camelpunch
> [#153091168] Forward Host header from cloud.service.gov.uk CloudFront instances

- README.md
Added a newline at the end of README, as I clicked the button as opposed to running `make merge_pr`
Code review
Not @LeePorte
> Newline added at end of README

- manifests/cf-manifest/manifest/050-rds-broker.yml
Fix incorrect minor versions used in bullet points for MySQL plans. This is to ensure consistency and increase user confidence.
Code review
Not @LeePorte
> [Support] Fix incorrect minor versions used in bullet points

- terraform/prod.vpc_peering.json
This PR adds the newly supplied DiT VPCs to peer with PaaS.
Code review and terraform plan.
Not @LeePorte, ideally @bleach as he has the most context.
> [support] Add new DiT VPCs for peering.

- .gitignore
- .travis.yml
- concourse/init_files/terraform.tfstate.tpl
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/tasks/terraform_destroy_datadog.yml
- terraform/cloudfoundry/outputs.tf
- terraform/cloudfront/backends.tf
- terraform/pingdom/backends.tf
- terraform/scripts/lint.sh
- terraform/scripts/manually-upload-certs.sh
- terraform/scripts/set-up-cdn-instances.sh
- terraform/scripts/set-up-pingdom.sh
- terraform/version_constraint.tf
Upgrade Terraform to the latest stable version.
1. Review the individual commit messages in order.
1. Confirm that Travis tests have passed.
1. Run the pipelines against an existing environment and confirm that all Terraform jobs are noops.
1. Run the pipelines against a new environment and confirm that it provisions OK.
1. Manually run the CDN instance Terraform (`make … setup_cdn_instances ACTION=…`)
1. Manually run the [Upload Certs Terraform](https://github.com/alphagov/paas-cf/blob/master/doc/ssl_certs.md) (can be tested with https://github.com/alphagov/paas-credentials/commit/2a62521fc9ac033de57d99828328517b3a5fc4fd)
1. Manually run the [Pingdom Terraform](https://github.com/alphagov/paas-cf/blob/master/doc/pingdom.md) with alphagov/paas-credentials#103
(we have already performed …
> [#153119879] Upgrade Terraform

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
To fix a regression in the previous version -
https://usn.ubuntu.com/usn/usn-3522-4/
I have tested an upgrade in my dev environment, which was green. Up to reviewer how much additional testing is required.
Not me.
> [#154202936] Bump stemcell to 3468.17

- terraform/prod.vpc_peering.json
Details in DeskPro ticket #9129.
Eyeball it. Make sure it seems sensible. Check route table rules don't overlap.
Anyone.
> Create new VPC peers for DIT

- concourse/pipelines/create-cloudfoundry.yml
Update paas-usage-events-collector to v0.5.0 which includes:
- modified /report endpoint: alphagov/paas-usage-events-collector#7
- new /repair endpoint: alphagov/paas-usage-events-collector#6
Check that the tag exists and contains the right changes.
I haven't tested this in dev and I'm not sure that you should spend your time doing so either.
@keymon because he reviewed the previous PR.
> [#153435158] Update paas-usage-events-collector to v0.5.0

- config/admin_users.yml
So that he can have access to CF prod and staging.
Check I haven't made a Typo.
Not me.
> [#154517370] Add Hector to admin users.

- manifests/cf-manifest/env-specific/cf-default.yml
- manifests/cf-manifest/env-specific/cf-prod.yml
- manifests/cf-manifest/env-specific/cf-staging.yml
Increase Elasticsearch disk size
Alerts are firing in production and usage is still increasing steadily.
This is basically a repeat of 53fbe03e.
Code review 😄 
Anyone.
> [support] Increase Elasticsearch disk size

- concourse/pipelines/create-cloudfoundry.yml
Whilst approving the paas-usage-events-collector rename story, I noticed this FIXME lying around, with a comment asking for it to be reverted. It's a Concourse task that cleans up unused secrets.
Ensure that this is still A Good Idea.
Anyone except @camelpunch.
> Remove an older FIXME

- config/admin_users.yml
They both have received their SC clearance around august/september last
year. They're more than happy to take extra responsibility and we need
them to get more "able" to do things around the platform.
Make sure these are their email addresses.
Each of them perhaps?
> [#154837625][#154838050] Add Chris and Michael to the admin list

- manifests/cf-manifest/env-specific/cf-prod.yml
- manifests/cf-manifest/manifest/800-logsearch.yml
We are increasing the number of parsers as we are seeing large queues of
log messages in production. This should give us a higher throughput and
increase fault tolerance.
Code review
Not @LeePorte or @bandesz
> [SUPPORT] Increase number of parser instances

- manifests/cf-manifest/env-specific/cf-prod.yml
- manifests/cf-manifest/manifest/800-logsearch.yml
Backed out changes to the parser
Code review
Not @LeePorte
> [Support] Reverse Reverse

- manifests/cf-manifest/manifest/070-elasticache-broker.yml
- platform-tests/src/platform/acceptance/init_test.go
- platform-tests/src/platform/acceptance/redis_service_test.go
We want to allow our tenants to set the maxmemory-policy setting when creating or updating Redis instances.
In this change we introduce a new parameter called maxmemory_policy (with underscore to keep it consistent with already existing parameters) which can be passed when creating or updating a redis service.
This change doesn't require a cluster restart in Elasticache.
Parameters are validated by the broker and the values of maxmemory_policy are validated by the AWS API.
We also amended the last operation status message to return with cluster related information to make our tenants happy.
```
status:    update succeeded
message:   ---
status               : available
cluster id           : cf-4zh4ckflsu6fa
engine version       : 3.2.6
maxmemory policy     : volatile-ttl
maintenance …
```
> [#154956796] Allow to set maxmemory-policy for Redis services

- concourse/pipelines/create-cloudfoundry.yml
Update paas-billing to introduce pricing components. See https://github.com/alphagov/paas-billing/pull/15 for details.
Follow the instructions in https://github.com/alphagov/paas-billing/pull/15.
Review and merge the paas-billing PR first.
❗️ Replace the temporary commit with the final version of paas-billing.
Before merging this PR please talk to Chris if we need to update the scripts/*.json files from prod first as this release will delete all the existing formulas from the database. After the PR is released we need to run the scripts/push-pricing.sh scripts probably.
Not me.
> [#154916385] Introduce pricing components

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
This includes a number of kernel changes. Details:
https://www.cloudfoundry.org/blog/usn-3582-2/
I've run this in my dev environment, so code review is probably enough.
Not me.
> [#155653680] Bump stemcell to 3468.25 for USN-3582-2

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
We want to upgrade the stemcell version to >=3541.5, but starting from 3541.2 the /var/vcap permissions are hardened. Most of the files/directories won't be readable by the world or even by the group. This can cause issues when a process running by vcap tries to access a directory/file owned by root.
We won't do the stemcell upgrade in this story but we prepare the datadog releases to work with the new stemcells.
Upgrade the datadog-for-cloudfoundry Bosh release. See https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/13 for details.
❗️ This PR contains a temporary commit which should be replaced when the final datadog-for-cloudfoundry release was built.
Code review first:
* https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/13
* …
> [#155398419] Fix the Datadog Agent

- concourse/pipelines/create-cloudfoundry.yml
We start to collect the billing events from the Compose API. See https://github.com/alphagov/paas-billing/pull/18 for details.
❗️ This PR contains a temporary commit which needs to be updated with the final paas-billing tag.
1. Review https://github.com/alphagov/paas-billing/pull/18 first
1. Deploy CF from this branch and enable the billing app:
```BRANCH=compose_billing_events_154835556 ENABLE_BILLING_APP=true SELF_UPDATE_PIPELINE=false make dev pipelines```
1. Check the billing-app logs to see if it's collecting data without errors. Please check the compose_audit_events and compose_audit_events_cursor tables in the billing db  
1. Review and merge https://github.com/alphagov/paas-billing/pull/18 first
1. Replace the temporary commit in this PR and merge
Not @LeePorte or me.
> [#154835556] Collect Compose billing events

- manifests/cf-manifest/static-ips-and-ports.yml
Part 2, in which we walk the other nats IP to the top of the static range.
- Ensure https://github.com/alphagov/paas-cf/pull/1277 is merged and deployed first
- Rebase this on master. You should be left with one commit.
- Deploy on top of a dev env that had master applied
- Ensure no app availability tests failed
Not @camelpunch, @LeePorte or @bandesz.
> [#155592565] Bosh links phase 2

- terraform/prod.vpc_peering.json
This commit adds the new VPC peerings as requested via support.
Code review and check against the details in ticket 9129
Not @46bit or @LeePorte
> [SUPPORT] Add new VPC peerings for DiT

- config/admin_users.yml
Andras is now cleared for production access. This adds him to the admin users.
Code review
Not @LeePorte
> [#156189879] Add Andras to production

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
- terraform/cloudfoundry/dns-records.tf
Now that we have the route for the API configured we can send traffic to it via the GoRouters.
* deploy on top of https://github.com/alphagov/paas-cf/pull/1286
* make sure it doesn't redeploy any instance groups affected by the change of properties. Only default values were removed, so it should be a no-op.
* make sure all tests pass
* merge https://github.com/alphagov/paas-cf/pull/1286
* rebase on master
Anyone but me.
> [#155856825] Switch DNS from CC ELB to system domain ELB.

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
- manifests/cf-manifest/manifest/operations/030-legacy-stemcells.yml
- manifests/cf-manifest/manifest/operations/040-graphite.yml
- manifests/cf-manifest/manifest/operations/080-logsearch.yml
- manifests/cf-manifest/scripts/generate-manifest.sh
Bump default stemcell to 3541.9 and make a separate 3468 alias to keep logsearch and graphite on that range. Bump 3468 to latest in the range too.
Deploy to dev env.
Anyone but @camelpunch
> [#155653889] Bump stemcell

- concourse/pipelines/create-cloudfoundry.yml
This reverts commit 3d0bce5ef1a10e186e70c65424053f2d53fcb1e0.
The change has been deployed to production now.
Code review. Make sure that I've reverted the right commit and code.
Anyone.
> [#154842336] Revert "Remove old route from the paas-billing app"

- manifests/cf-manifest/manifest/000-base-cf-deployment.yml
- manifests/cf-manifest/manifest/operations/030-legacy-stemcells.yml
This should resolve issues in:
https://www.cloudfoundry.org/blog/usn-3598-1/
```
BRANCH=$(git rev-parse --abbrev-ref HEAD) SELF_UPDATE_PIPELINE=false make dev pipelines
```
Anyone.
> [#156532689] Upgrade stemcell versions

- platform-tests/src/platform/acceptance/cf_push_test.go
- terraform/cloudfoundry/elbs.tf
The follows on from https://github.com/alphagov/paas-cf/pull/1290
We have increased the timeout on the ELB to allow for long CF API operations.
* Deploy on top of master
* Make sure all tests pass
Anyone but me, @46bit or @chrisfarms
> [#155856825] Move Cloud Controller behind GoRouter - Part 1: The Dark ELB Rises

- concourse/pipelines/create-cloudfoundry.yml
What
----
Update deployment to use v.0.24.0 of paas-billing
How to review
-------------
Check the new tag is a valid release
Who can review
--------------
> [#157287692] Bump paas-billing release v0.24.0

- concourse/pipelines/create-cloudfoundry.yml
What
----
This PR updates the pass-billing app to the latest version
How to review
-------------
- Create and kill an app
- Request and see data (tested myself)
**Before merging update the tmp commit with the final version**
Who can review
--------------
Not @LeePorte
> [#156753777]  Update to latest paas-billing

- concourse/pipelines/create-cloudfoundry.yml
What
----
Bump paas-billing to v0.27.0 to bring in the feature that uses
compose scaling events to enhance the billing events.
How to review
-------------
I suspect code review will be enough.
Who can review
--------------
> [#156037804] paas-billing v0.27.0: compose scale events

- concourse/pipelines/create-cloudfoundry.yml
- tools/metrics/gauges_cf.go
What
----
In https://github.com/alphagov/paas-cf/pull/1375 we renamed the
backing services, but we need to update the places where we still
use those names.
This include: healthcheck app, billing and accounts.
We also change the metrics collector tool.
How to review
-------------
Code review
Who can review
--------------
Anyone but me
> [#157470481] Rename service plans according ADR025 (and 2)

- concourse/pipelines/create-cloudfoundry.yml
What
----
This PR updates PaaS-Admin to version 0.2.0 which contains user deletion.
How to review
-------------
Code Review
Who can review
--------------
Not @LeePorte
> Update paas-admin to v0.2.0

- concourse/pipelines/create-cloudfoundry.yml
What
----
These have been run in staging and prod, so are no longer needed.
How to review
-------------
Who can review
--------------
Not me.
> [#156368115] Remove graphite cleanup jobs from pipeline

- manifests/cf-manifest/operations.d/300-upgrade-cflinuxfs2-for-cve-mitigation.yml
What
----
See commit messages.
How to review
-------------
Who can review
--------------
Not @46bit
> [#158385978] [#158385725] Upgrade cflinuxfs2 to mitigate CVEs

- concourse/pipelines/create-cloudfoundry.yml
What
----
Changes to billing and allow org managers to retreive data.
How to review
-------------
- Continue review of alphagov/paas-billing#37
- Remove (or ask to remove) the TMP commit
- Make sure the version is still valid (see build ci)
> [#157307645] Bump paas-billing version

- concourse/pipelines/create-cloudfoundry.yml
What
----
They grow so fast :sob:
We're getting out of date. Let's try to keep up!
How to review
-------------
- See if the version has been tagged yet.
> Bump paas-admin version

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Includes https://github.com/alphagov/paas-rds-metric-collector/pull/3
How to review
-------------
Code review, check it matches https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker-release/jobs/build-final-release/builds/31?
Who can review
--------------
not me
> [#158456560] Bump rds-broker release to add metrics

- README.md
What
----
Forgot to sign commit
How to review
-------------
Check nothing really changed and merge it 
Who can review
--------------
anyone
> forgot to sign commit 

- concourse/pipelines/create-cloudfoundry.yml
What
----
v0.16.0 includes content tweaks to descriptions around roles
How to review
-------------
check tag
Who can review
--------------
not me
> [#156757836] Upgrade to paas-admin v0.16.0

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/scripts/migrate-cf-secrets.rb
- manifests/cf-manifest/scripts/rename-cf-secrets.rb
What
----
This reverts commit 17e70cfeb99feff608304b892d777c304915fe52, reversing
changes made to 395f2ffb6fa5af251ca6fc9e1814b9a3d3009d58.
https://github.com/alphagov/paas-cf/pull/1423
There was a dependency problem in the pipeline. Also, we want to
wait for some days to allow all dev environments to be updated.
How to review
-------------
It is only a revert, no need to review
Who can review
--------------
not me
> [#155463404] Revert "Merge pull request #1423"

- concourse/pipelines/create-cloudfoundry.yml
What
----
This org will now host CodiMD (HackMD), and will need extra memory for
the epic compilation and building of lots of Node dependencies.
How to review
-------------
Note: I have already manually increased the quota in prod.
Who can review
--------------
Anyone but me.
> [#158825291] Increase quota of our govuk-paas org

- terraform/datadog/concourse.tf
What
----
These are just for the continuous smoke tests. We had an issue where
they were erroring, but the existing monitor only checks for failure
states.
These have to be done as two separate checks because of the way Datadog
handles monitors. If you add a condition to alert on no data, then the
absence of metrics with the `build_status:errored` tag will cause the
monitor to persistently stay triggered.
For the no data monitor, we have to assert on some query to be able to
create the monitor, but we really only care about the no data condition.
How to review
-------------
We have tested this with a full deploy, so you may be happy with just code review. However, if you want to fully test:
* Enable datadog for your Concourse:
```
cd paas-bootstrap
ENABLE_DATADOG=true make dev …
```
> [#158873752] Add monitors for smoke test errors and no data

- concourse/pipelines/create-cloudfoundry.yml
What
----
paas-admin v0.19.0 adds the admin-fee to the pricing calculator
How to review
-------------
Check the version looks good
Who can review
--------------
Not me
> [#158947328] Bump pass-admin to v0.19.0

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/lib/aiven.sh
- concourse/scripts/pipelines-cloudfoundry.sh
- config/service-brokers/aiven/config.json
- config/service-brokers/aiven/manifest.yml
- config/service-brokers/compose/catalog.json
- manifests/cf-manifest/operations.d/741-aiven-broker.yml
- platform-tests/example-apps/healthcheck/elasticsearch.go
- platform-tests/src/platform/acceptance/elasticsearch_service_test.go
- scripts/upload-aiven-secrets.sh
What
----
This deploys the Aiven broker and modifies the Compose Elasticsearch acceptance tests to use Aiven instead.
How to review
-------------
* Merge https://github.com/alphagov/paas-aiven-broker/pull/5 and update the temporary commit on this branch.
* Upload the Aiven secrets:
```
make dev upload-aiven-secrets
```
* Deploy from this branch. Make sure the custom acceptance tests pass.
* Merge https://github.com/alphagov/paas-aiven-broker/pull/5 and update the temporary commit on this branch.
* Aiven secrets need to be uploaded for each environment.
Who can review
--------------
Anyone but me or @jpluscplusm
> [#157737884] Deploy Aiven broker

- terraform/datadog/general.tf
What
----
See commit message.
How to review
-------------
I suggest code review and I'll fix any problems in staging.
Who can review
--------------
Who can review.
> Alert on 25+% swap utilisation

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Includes timeout for connecting DBs in the metrics collector
https://github.com/alphagov/paas-rds-metric-collector/pull/8
How to review
-------------
Code review
Who can review
--------------
Anyone
> [#158455575] pin rds-broker to v0.1.41

- concourse/pipelines/create-cloudfoundry.yml
What
----
Most importantly: we've recently made changes to our billing designs.
We've also introduced some acceptance tests.
How to review
-------------
- Make sure the version exists and refers to alphagov/paas-admin#83
> [#158624258] Bump paas-admin version

- manifests/cf-manifest/env-specific/cf-prod.yml
What
----
To keep the capacity needed to survive a AZ failure around
40% free.
How to review
-------------
Code review
Who can review
--------------
not me
> [#159820351] Increase the number of cells to 36

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
New speculative bug in Intel chips, L1TF[1]
Fixed in new stemcells [2]
[1] https://www.intel.com/content/www/us/en/architecture-and-technology/l1tf.html
[2] https://www.cloudfoundry.org/blog/usn-3741-2/
How to review
-------------
Code review
Who can review
--------------
Not me
> [#159889082] Upgrade stemcells to fix new L1TF bug

- concourse/pipelines/create-cloudfoundry.yml
This has been applied in all persistent environments now, so we no
longer need this.
This reverts commit d9da872a907f0ed2423821d7cbf94c821f0cba59.
How to review
-------------
Code review is probably sufficient.
Who can review
--------------
Not me.
> [#157053110] Revert "Remove Kibana admin password from `cf-vars-store.yml`"

- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/lib/compose.sh
- concourse/scripts/pipelines-cloudfoundry.sh
What
----
This PR removes the compose scraper deletion job from the pipeline as it is no longer required.
How to review
-------------
Ensure https://github.com/alphagov/paas-cf/pull/1517 has been deployed to all persistent environments.
Code review
Who can review
--------------
Not @LeePorte
> [#160283000] Remove compose scraper Part 2

- concourse/pipelines/create-cloudfoundry.yml
What
----
We want to include the changes implemented in https://github.com/alphagov/paas-billing/pull/53
How to review
-------------
Check the number is right based on https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-billing
Who can review
--------------
Anyone
> [#159234320] Update paas-billing to include consolidation

- concourse/pipelines/create-cloudfoundry.yml
What
----
Include some optimisations when querying log-cache
https://github.com/alphagov/paas-log-cache-adapter/pull/7
How to review
-------------
Code review
Who can review
--------------
Anyone
> [#159135790] Bump paas-log-cache-adapter

- Makefile
- doc/non_dev_deployments.md
- manifests/cf-manifest/env-specific/cf-staging.yml
- scripts/cf_subshell_scoped_login.sh
> Remove staging in Ireland (eu-west-1)

- concourse/pipelines/create-cloudfoundry.yml
What
----
This version correctly handles deleting service instances which are
non-existent[1].
[1] https://github.com/alphagov/paas-aiven-broker/pull/9
How to review
-------------
Already reviewed. This pull request is for audit.
Who can review
--------------
Me.
> [#159829290] Upgrade Aiven broker to v0.9.0

- config/admin_users.yml
He's now been cleared for prod access.
How to review
-------------
Code review.
Who can review
--------------
Not me.
> [#160682307] Give Richard access to prod/staging envs

- concourse/pipelines/create-cloudfoundry.yml
What
----
Bump pazmin to 0.38
How to review
-------------
Read this diff: https://github.com/alphagov/paas-admin/compare/v0.36.0...v0.38.0
Who can review
--------------
Not me
> [#160415263] Bump pazmin to 0.38

- manifests/cf-manifest/operations.d/260-cf-upgrade-cflinuxfs2.yml
What
----
This resolves [USN-3770-1](https://www.cloudfoundry.org/blog/usn-3770-1/).
How to review
-------------
I've run it through my pipeline and it's fine—I think it should be good to sign and recline.
Who can review
--------------
Anyone.
> [#160788081] Upgrade to latest version of cflinuxfs2

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
Resolves:
- https://www.cloudfoundry.org/blog/usn-3752-2/
- https://www.cloudfoundry.org/blog/usn-3765-1/
- https://www.cloudfoundry.org/blog/usn-3767-1/
How to review
-------------
I've done it in my pipeline. It works for me. Probably just take a look and sign away.
Who can review
--------------
Anyone.
> [#160845699] Upgrade Stemcells

- manifests/cf-manifest/operations.d/260-cf-upgrade-uaa.yml
- platform-tests/src/platform/acceptance/uaa_styling_test.go
What
----
Resolves:
- https://www.cloudfoundry.org/blog/cve-2018-11082/
How to review
-------------
I've run it through my dev environment and my tests are ✅. Should be good to :shipit: .
Who can review
--------------
Let ℙ be the set of all PaaS team members.
`∀x ∈ { ℙ - Sam } : CanReview(x)`
> [#160917846] Upgrade to the latest version of UAA

- manifests/cf-manifest/operations.d/260-cf-upgrade-cflinuxfs2.yml
What
----
Resolves the following CVEs:
- https://www.cloudfoundry.org/blog/usn-3786-1/
- https://www.cloudfoundry.org/blog/usn-3785-1/
How to review
-------------
Deployed fine to my dev environment. Any problems should get caught in staging. Should be fine to just merge.
Who can review
--------------
Anyone.
> Upgrade to latest cflinuxfs2 release

- concourse/pipelines/create-cloudfoundry.yml
What
----
Includes CSRF protection for paas-admin.
How to review
-------------
no need really
Who can review
--------------
Anyone
> Bump paas-admin to v0.41.0

- concourse/pipelines/create-cloudfoundry.yml
- config/billing/config.json
- config/service-brokers/aiven/config.json
What
----
This introduces a new "medium" Elasticsearch plan using Aiven's Business-8 plan (details here: https://aiven.io/elasticsearch#plan-tables).
While doing this, I've also taken the opportunity to move the billing plan data into this repo as it makes sense for it to live here.
How to review
-------------
Code review is probably enough. I've tested this in my dev environment.
Who can review
--------------
Not me.
> [#161212765] Add a medium Elasticsearch plan

- concourse/pipelines/create-cloudfoundry.yml
What
----
This fixes a bug where the filter dropdowns in billing wouldn't have all
the options and removes the CSRF token from the calculator.
How to review
-------------
Sanity check
Who can review
--------------
Anyone (but probably Lee)
> [#161315584] Bump paas-admin to 0.43.0

- scripts/create-org.sh
What
----
These instructions were lost when we removed the user addition from the
script, but they're part of the process so they should still be
documented.
How to review
-------------
Code review
Who can review
--------------
Anyone
> [#SUPPORT] Add some instructions to add the user to the mailing list

- scripts/list-all-users.sh
What
----
Since most of the usernames are emails we can sort them by their
organisation and then by their email slug. This makes more sense as an
order than the seemingly random order UAA spits them out in.
How to review
-------------
* Code review
* Maybe run the script?
Who can review
--------------
Anyone
> [#SUPPORT] Sort users by domain then by name

- concourse/pipelines/create-cloudfoundry.yml
What
----
This changes the phase banner from ALPHA to BETA.
How to review
-------------
See https://github.com/alphagov/paas-admin/pull/107
Who can review
--------------
Anyone
> Bump paas-admin to 0.44

- concourse/pipelines/create-cloudfoundry.yml
What
----
This removes the temporary rotation pipeline added in #1597 
How to review
-------------
Who can review
--------------
Anyone but me.
> [#160556015] Rotation for cc db encryption key - Part 2

- manifests/cf-manifest/env-specific/cf-prod.yml
What
----
We were hitting the rep advertised cell memory limit. This increases the
number of cells to 39.
How to review
-------------
Code review
Who can review
--------------
Not me
> [SUPPORT] Increase the number of cells in Ireland to 39

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
This PR updates the stemcells in use to mitigate [USN-3797-2](https://www.cloudfoundry.org/blog/usn-3797-2/).
How to review
-------------
Code review and compare against  [USN-3797-2](https://www.cloudfoundry.org/blog/usn-3797-2/)
Who can review
--------------
Not me
> [SUPPORT] Update stemcells for CVE USN-3797-2

- README.md
- scripts/create-org.sh
What
----
Create new orgs in London by default.
How to review
-------------
Code review.
Who can review
--------------
Anyone but me.
> [#158973720] London by default

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/scripts/generate-cloud-config.sh
- manifests/cf-manifest/scripts/generate-manifest.sh
- manifests/cf-manifest/spec/manifest/base_properties_spec.rb
- manifests/cf-manifest/spec/support/manifest_helpers.rb
- manifests/prometheus/operations.d/220-monitor-cf-UPSTREAM.yml
- manifests/prometheus/operations.d/221-monitor-cf.yml
- manifests/prometheus/spec/fixtures/prometheus-vars-file.yml
What
----
We want to set up the exporters for CF metrics and everything from the firehose.
How to review
-------------
Deploy. Check in Grafana the dashboards are there. Check in Prometheus the alerts are set up.
Who can review
--------------
Me or @LeePorte
> [#160175656] Prometheus consume CF metrics

- concourse/pipelines/create-cloudfoundry.yml
What
----
This version includes[1] and fixes[2].
[1] https://github.com/alphagov/paas-admin/pull/109
[2] https://github.com/alphagov/paas-admin/issues/110
How to review
-------------
Check the version number is correctly tagged in the repository.
Who can review
--------------
@keymon
> [support] Upgrade paas-admin

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/713-rds-broker-postgres10-plans.yml
- platform-tests/src/platform/acceptance/postgres_service_test.go
What
----
We have tested the postgres 10.5 plans, and we want to make them
available for everybody.
How to review
-------------
* code review
* check custom acceptance tests pass. Run time should remain the same.
Who can review
--------------
Not me
> [#161646704] Make postgres 10 generally available

- concourse/pipelines/create-cloudfoundry.yml
What
----
Use zero-downtime-push to deploy this without downtime.
How to review
-------------
Code review - I've already run this down my pipeline
Who can review
--------------
Not me.
> [#162167030] Make paas-accounts deployment zero-downtime

- terraform/datadog/router.tf
The anchor is all lower-case - fix it.
How to review
-------------
* Code review - verify the team manual link now works
Who can review
--------------
Not me.
> [Support] Fix gorouter latency monitor doc link

- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
The details for these were added in 2f14cfb, but the generate-config.rb
script wasn't run to update the actual config files used. This rectifies
that omission.
How to review
-------------
Code review
Who can review
--------------
Not me.
> Regenerate billing config to include PG10 plans

- concourse/pipelines/create-cloudfoundry.yml
What
----
This version includes bugfix to not charge for staging of apps
without STAGING_STOP event
https://github.com/alphagov/paas-billing/pull/57
How to review
-------------
Code review
Who can review
--------------
not me :)
> Bump paas-billing to 0.47.0

- manifests/prometheus/alerts.d/ec2_cpu_credits.yml
- manifests/prometheus/alerts.d/rds_cpu_credits.yml
- manifests/prometheus/alerts.d/rds_disk_utilisation.yml
What
----
This PR adds the following Prometheus alerts:
- EC2 CPU credits
- RDS CPU credits
- RDS disk utilisation
How to review
-------------
Deploy the changes from this branch and check if the new alerts are correct in Prometheus.
Who can review
--------------
Not me
> [#162303736] Add alerts based on the new cloudwatch-exporter metrics

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
What
----
Respond to
https://www.cloudfoundry.org/blog/cve-2018-15754-uaa-issues-tokens-across-identity-providers-if-users-with-matching-usernames-exist/
https://www.cloudfoundry.org/blog/usn-3839-1/
How to review
-------------
Code review. Did not test, but release notes do not highlight anything,
and we do not use cflinuxfs3 yet.
Staging should catch any issue.
Who can review
--------------
Not me
> [#162574702] Fix CVEs for UAA and cflinuxfs3

- terraform/prod-lon.vpc_peering.json
What
----
DiT have a very edge case use and require a VPC peering setup to be
established in London. This adds the new peering into our terraform.
How to review
-------------
Code review
Who can review
--------------
Not @LeePorte
> [SUPPORT] Add new DiT VPC Peering

- config/billing/config.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
What
----
We updated the Redis plans in #1713 but forgot to rename the tiny plan in the billing config, and also to re-run the generation script to apply the template changes to the config files.
How to review
-------------
Code review should be enough.
Who can review
--------------
Not me.
> [#163250921] Update pricing plans with Redis changes

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
Includes fixes for:
- USN-3864-1 LibTIFF vulnerabilities
- USN-3859-1 libarchive vulnerabilities
- USN-3863-1 APT vulnerability
How to review
-------------
Code review - I've already run this down my dev environment
Who can review
--------------
Not me.
> [#163483158] Upgrade stemcell and cflinuxfs* to fix USNs

- manifests/prometheus/alerts.d/aiven-cost.yml
- manifests/prometheus/alerts.d/elasticache-node-count.yml
- manifests/prometheus/env-specific/default.yml
- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
- manifests/prometheus/env-specific/stg-lon.yml
- terraform/dev.tfvars
- terraform/prod.tfvars
- terraform/staging.tfvars
What
----
This makes 2 tweaks to the alerts:
* Update Aiven cost alert with new threshold (and merge into single alert)
* Parameterise the elasticache node count alert.
How to review
-------------
Code review is probably enough - I've tested this in my dev env.
Who can review
--------------
Not me.
> [Support] Update Aiven threshold, and parameterise elasticache node alert.

- concourse/pipelines/create-cloudfoundry.yml
- platform-tests/example-apps/create-account-holding-page/manifest.yml
- platform-tests/example-apps/healthcheck/manifest.yml
- tools/metrics/manifest.yml
- tools/paas-uaa-assets/manifest.yml
What
----
Update internal PaaS apps to use the cflinuxfs3 stack
How to review
-------------
Redeploy CF in dev, then ensure the apps mentioned in the commits are still functioning as normal
Who can review
--------------
Not @mogds or @AP-Hunt
> [163363939] Update internal PaaS apps to use the cflinuxfs3 stack

- concourse/pipelines/create-cloudfoundry.yml
To pull in the fixes to the link URLs.
How to review
-------------
* Code review.
Who can review
--------------
Not me.
> [#163555458] Bump paas-admin

- scripts/get-all-app-stacks.sh
What
----
A script to get all app stack versions for all organisations and spaces in a cloudfoundry instance
How to review
-------------
Code Review (sorry!)
Log in to cloudfoundry as an admin user, and run the script - check that the data that is returned is correct and exhaustive (all orgs, spaces and apps should be included).
Who can review
--------------
> [#163520707] A script to get all app stack versions

- config/admin_users.yml
He's now ready for prod access.
How to review
-------------
Code review
Who can review
--------------
Not me.
> [#163819803] Give Tom access to prod/staging CF envs.

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We want to have a number of cells that is divisible by the number of
availability zones (i.e. 3).
How to review
-------------
* Code review
Who can review
--------------
> Increase scale in London to 12 (divisible by 3)

- concourse/pipelines/create-cloudfoundry.yml
What
----
Currently we have an issue with one of the event sql statements in use. By adding the logging as a proxy for metrics we hope to narrow it down to the specific statement that is causing the issue.
How to review
-------------
Merge https://github.com/alphagov/paas-billing/pull/61 first and then code review
Who can review
--------------
@richardTowers
> [#163651298] Deploy paas-billing with more logging

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
Includes fixes for the following:
* https://www.cloudfoundry.org/blog/usn-3871-4/
* https://www.cloudfoundry.org/blog/usn-3884-1/
* https://www.cloudfoundry.org/blog/usn-3885-1/
* https://www.cloudfoundry.org/blog/usn-3882-1/
How to review
-------------
Code review is probably enough - verify I've copies the checksums correctly.
Who can review
--------------
Not me.
> [#164046764] Bump stemcell and  cflinuxfs to fix some USNs

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are currently triggering / hovering close to triggering the alarm in London for the available memory on cells. This combined with the update that DiT are migrating their remaining services this week has given rise to adding some more prod cells in London.
How to review
-------------
Code review
Who can review
--------------
anyone
> [support] Add some more cells in London

- concourse/pipelines/create-cloudfoundry.yml
What
----
Update paas-admin to the latest version, containing the fix for billing_manager permissions being unintentionally removed.
How to review
-------------
Code review - ensure the tag does is the same as was tagged in [build #54](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-admin/jobs/tag-releases/builds/54)
Who can review
--------------
Not Me
> [#163084536] Update version of paas-admin

- concourse/pipelines/create-cloudfoundry.yml
What
----
This is currently causing conflicts on second runs of the pipeline as it has already been enabled for the admin org
How to review
-------------
deploy a current master in dev, try and run the pipeline a second time, this will fail, then deploy this branch on top and it will pass.
Who can review
--------------
anyone
> [support] Place S3 service access in a conditional block

- config/billing/config.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/billing/pricing_data.yml
- config/service-brokers/aiven/config.json
What
----
DiT have requested a larger Elasticsearch plan as they are currently filling up the medium sized plan. This adds the plan and updates the billing information so that it is available to be billed.
How to review
-------------
Code review
Who can review
--------------
Anyone
> [support] Add larger Elasticsearch Plan

- manifests/cf-manifest/spec/manifest/env_spec.rb
- manifests/cf-manifest/spec/manifest/vpc_peering_spec.rb
- manifests/cf-manifest/spec/support/manifest_helpers.rb
- manifests/cloud-config/spec/spec_helper.rb
- manifests/cloud-config/spec/support/cloud_config_helpers.rb
- manifests/prometheus/spec/support/manifest_helpers.rb
What
----
As a follow-up to #1749, this codifies the fact that the number of cells needs to be equal in each AZ into a unit test so that we don't rely on institutional memory for this fact.
I've also done a bit of refactoring of the test helpers while I was there. 
How to review
-------------
* Code review. Verify the tests pass in Travis.
Who can review
--------------
Not me.
> [Support] Test that we have an equal number of cell per AZ

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are hitting the limits of the current number of API servers in the London region.
This will solve the limits and give us some headroom for growth.
How to review
-------------
Code review
Who can review
--------------
anyone
> [support] Scale up API instances in London

- manifests/cf-manifest/env-specific/prod-lon.yml
We're seeing increased load on the API, so this adds another one to help
cope with it.
How to review
-------------
Code review - check I can successfully add 1 to a number.
Who can review
--------------
Not me.
> [Support] Increase the number of API VMs in London to 4

- concourse/pipelines/create-cloudfoundry.yml
What
----
Bumps paas-admin to v0.55.0
How to review
-------------
Check that the tag is right
Who can review
--------------
Not I
> Bumps paas-admin to v0.55.0

- config/billing/config.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
What
----
The previous change appears to have been done incorrectly - it has messed up billing in previous months.
This attempts to resolve that by reintroducing the previous calculation for all months up to 03/19 and a new plan to take effect from now on.
How to review
-------------
1. Apply this branch to an environment
1. Stop billing collector
1. Delete February's billing consolidation
1. Restart billing collector
1. Ensure app billing is not £0 for everything
Who can review
--------------
> [#164467168] Fix billing

- manifests/prometheus/alerts.d/aws-elb-unhealthy-nodes.yml
- manifests/prometheus/alerts.d/concourse-smoketests-failures.yml
- manifests/prometheus/alerts.d/uaa-failed-login-user-not-found.yml
- manifests/prometheus/alerts.d/uaa-failed-login-wrong-password.yml
- manifests/prometheus/spec/alerts/concourse-smoketests-failures.test.yml
What
----
Remove PagerDuty notification from concourse smoketest warning as this was missed on a previous PR
How to review
-------------
code review
Who can review
--------------
Nor me
> [#163521947] Remove PagerDuty notification form concourse smoketest warning

- concourse/pipelines/create-cloudfoundry.yml
This cleans up some temporary tasks in the pipeline that have run everywhere.
How to review
-------------
* Code review
* Maybe run this down a dev env to be sure it's all good.
Who can review
--------------
Not me.
> Cleanup some FIXMEs in the pipeline

- concourse/pipelines/create-cloudfoundry.yml
What
----
Changes:
* Wait between CF API calls if an error is encountered.
* Remove duplicated collection of services and service plans
How to review
-------------
1. Review https://github.com/alphagov/paas-billing/pull/63
I deployed it to my dev env and validated that e.g. a new org was still picked up.
Who can review
--------------
Not me.
> [#164425492] Update paas-billing to the latest version

- manifests/cf-manifest/env-specific/prod.yml
What
----
We're quite a bit over-scaled in Ireland at the moment. We can probably
remove about 15 cells ultimately, but we're scared about doing that in
one release, so we're dipping our toes in with 3 instances to get
started.
How to review
-------------
* Code review
Who can review
--------------
* Not @richardtowers
> [#164697880] Remove 3 cells in Ireland

- concourse/pipelines/create-cloudfoundry.yml
What
----
Fixes a few broken links to the docs.
How to review
-------------
Code review
Who can review
--------------
Not me.
> [#164798010] Bump paas-admin to v0.57.0

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
To address:
https://www.cloudfoundry.org/blog/usn-3906-1/
https://www.cloudfoundry.org/blog/usn-3899-1/
https://www.cloudfoundry.org/blog/usn-3891-1/
https://www.cloudfoundry.org/blog/usn-3901-2/
How to review
-------------
* Read the blogs above
* Check that this has run through a dev pipeline succesfually (currently
running through
https://deployer.towers.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry
, although there are some issues with paas-admin in that environment so
you might want to use your own too.
* Review https://github.com/alphagov/paas-bootstrap/pull/261
Who can review
--------------
* Not @richardtowers
> [#164827408][CVE] USN-3901-2: Bump stemcells and cflinuxfs{2,3}

- manifests/cf-manifest/env-specific/prod.yml
What
--------------
As more tenants have migrated over to London we have a surplus of cells in Ireland, this commit removes another 3. Further reductions will take place over successive PRs.
How to review
-------------
Code review alongside [User impact dashboard](https://grafana-1.cloud.service.gov.uk/d/paas-user-impact/user-impact-prod?refresh=5s&orgId=1)
Who can review
--------------
anyone
> [SUPPORT] Reduce the number of cells in Ireland

- manifests/cf-manifest/env-specific/prod.yml
What
--------------
As more tenants have migrated over to London we have a surplus of cells in Ireland, this commit removes another 3. Further reductions will take place over successive PRs.
How to review
-------------
Code review alongside [User impact dashboard](https://grafana-1.cloud.service.gov.uk/d/paas-user-impact/user-impact-prod?refresh=5s&orgId=1)
Who can review
--------------
anyone
> [SUPPORT] Reduce the number of cells to 27 in Ireland

- manifests/cf-manifest/env-specific/stg-lon.yml
What
----
Adds a cc rate limit value for staging, which matches the default.
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
---
:(
> Add hourly rate limit for staging

- concourse/pipelines/create-cloudfoundry.yml
What
----
Includes the database migration SQL for adding `quota_definition_guid` column.
How to review
-------------
- Deploy to dev env
Who can review
--------------
Not me
> [#164763735] Bump paas-billing release

- concourse/pipelines/create-cloudfoundry.yml
What
----
Enables strict null checks and updates orgQuota (https://github.com/alphagov/paas-admin/pull/126)
Who can review
--------------
Not me
> [#164763735] Bump paas-admin release

- manifests/cf-manifest/operations.d/320-cc-set-api-limits.yml
What
----
Bump the CC unauthenticated rate limit
How to review
-------------
Code review (read the commit messages)
Who can review
--------------
Not @tlwr
> Support: Increase CC unauthenticated rate limit to 1800

- concourse/pipelines/create-cloudfoundry.yml
What
----
s3 in calculator
better logging
faster reports
a11y ireland
How to review
-------------
[diff](https://github.com/alphagov/paas-admin/compare/v0.61.0...v0.76.0)
Who can review
--------------
not @tlwr
> Bump paas-admin to 76

- concourse/pipelines/create-cloudfoundry.yml
What
----
Bump paas-admin to v0.82.0
How to review
-------------
1. Code review
Who can review
--------------
Anyone but @AP-Hunt
> Bump paas-admin to 0.82.0

- manifests/cf-manifest/operations.d/750-s3-broker.yml
What
----
Bumps version of S3 broker
How to review
-------------
Code review
Run it down the pipeline
Who can review
--------------
Whoever is reviewing the [paas-s3-broker PR](https://github.com/alphagov/paas-s3-broker/pull/8)
> [#165345969] Bump s3 broker version

- manifests/cf-manifest/operations.d/750-s3-broker.yml
What
----
Adds a `chargeable_entity` and `tenant` tag to buckets
How to review
-------------
Code Review
Who can review
--------------
Not me
> [#165411774] Bump S3 broker to 0.1.3

- concourse/pipelines/create-cloudfoundry.yml
What
----
Release an important temporary fix: https://github.com/alphagov/paas-billing/pull/75
How to review
-------------
Check the version number.
Who can review
--------------
Not @46bit
> Upgrade to paas-billing v0.58.0

- concourse/pipelines/create-cloudfoundry.yml
What
----
Bump paas-admin to fix acceptance tests
Who can review
--------------
@AP-Hunt
> Bump paas-admin to include acceptance test fixes

- concourse/pipelines/create-cloudfoundry.yml
What
----
Enables the `aws-s3-bucket` service's `default` plan for everyone on the GOV.UK PaaS! 🎉
How to review
-------------
Code review. This change worked in my `miki` dev environment.
Who can review
--------------
Not @46bit
> [#165677471] Enable S3 for everyone!

- concourse/pipelines/create-cloudfoundry.yml
What
----
Increases Default Init and Refresh timeouts 
https://github.com/alphagov/paas-billing/pull/79
How to review
-------------
Code review
Who can review
--------------
Not me
> Bump PaaS-Billing Release

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
See https://github.com/alphagov/paas-bootstrap/pull/279
> Add colocated-with-web tag to web colocated worker

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/pipelines-cloudfoundry.sh
- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/env-specific/stg-lon.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
**Before merging: update the wip commit with the final build**
What
----
- Updates the paas-uaa-customized-boshrelease with changes added via https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/3
- Adds an `aws_region_name` property required by the above
How to review
-------------
- Review and merge https://github.com/alphagov/paas-admin/pull/232
- Update the paas-admin tag
- Review https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/3
- Merge the paas-uaa-customized-boshrelease PR
- Update the wip commit with the final build release
Who can review
--------------
Not me
> [#165561646] Style login page with GOV.UK frontend 

- concourse/scripts/pipelines-cloudfoundry.sh
What
----
PAAS_REGION_NAME is now env specific instead of set by the Makefile
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Remove unused variable

- concourse/pipelines/create-cloudfoundry.yml
What
----
See commit 2c2be1dacbbc3d784e2b5c0d490f5769719aed2d
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Remove unused variable region name (round 2)

- scripts/list-routes.rb
What
----
This may be useful when we're trying to understand what things are
running on the platform.
Possible future improvements:
- send a `dig` to custom domains to see if DNS is actually setup
- send an HTTP request to the domain to see if it's serving 200s
[skip-ci]
How to review
-------------
* Code review
* Run the script yourself and check it works
Who can review
--------------
> Add a script to list the routes in a region

- manifests/cf-manifest/scripts/rotate-vars-store-secrets.rb
What
----
This PR adds output to one of the scripts used by our secrets rotation. **The commit message explains more** but TL;DR I'm hoping this will make it easier to understand how our secrets/certificate rotation works.
How to review
-------------
Code review. I've checked that Ruby can parse this, but no more.
Who can review
--------------
Not @46bit
> Add output to a secret rotation script

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
Updates UAA-Customized Bosh release with https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/4
How to review
-------------
- Deploy to your dev env and follow the steps described in PR above
Merge Steps
------------
- Merge https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/4
- Update the WIP commit with the final release
Who can review
--------------
Not me
> [#166027802] Update UAA-Customized Release

- concourse/pipelines/create-cloudfoundry.yml
What
----
Removed the sed as it is not needed.
How to review
-------------
code review
Who can review
--------------
@46bit
> [#166056703] Remove sed from the cert cleanup

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
Ships this story. Includes these changes (all part of the story):
* https://github.com/alphagov/paas-admin/pull/269
* https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/6 and https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/7
How to review
-------------
Code review
Who can review
--------------
Not @46bit
> [#166116777] Make the region name a link to change region

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
What
----
This commit responds to a security bug in the alpine base image. It updated the hash of the alpine based docker containers we build and use in the pipeline.
How to review
-------------
Code review. I have run it down my pipeline
Who can review
--------------
anyone
> Update Docker container hashes

- manifests/cf-manifest/env-specific/prod.yml
What
----
A tenant is doing load testing on June 10/11, this is commit scales up
the routers for this event
How to review
-------------
Cod review 🐟
Who can review
--------------
Not @tlwr
> Scale up gorouters in `prod` (IE) from 3 to 6 [do not merge until June 10 8AM)

- concourse/pipelines/create-cloudfoundry.yml
What
----
Updates paas-accounts with https://github.com/alphagov/paas-accounts/pull/6
How to review
-------------
- Bring up your dev env using master and then deploy this branch (ensure paas-accounts is already running to test the migraton)
- Test the new routes added to paas-accounts' [README](https://github.com/alphagov/paas-accounts/pull/6/commits/22f09f2c8de9797bfd2b7fe7544fe42f1b206000)
Who can review
--------------
Not me or @LeePorte
> [#166334735] Update paas-accounts

- concourse/pipelines/create-cloudfoundry.yml
What
----
Reverts paas-accounts to v0.5.0
How to review
-------------
Code review
Who can review
--------------
Not me
> Revert paas-accounts to v0.5.0

- config/buildpacks.yml
What
----
Upgrade buildpacks to the latest releases
How to review
-------------
Run this down a dev env
Who can review
--------------
Not @tlwr
> [#166348071] Bump buildpacks to latest using update_buildpacks

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Since DiT have reenabled prometheus in the staging org we are triggering alerts.
How to review
-------------
code review
Who can review
--------------
anyone
> Scale up the number of API instances

- manifests/cf-manifest/env-specific/prod.yml
What
----
A tenant is doing load testing - scale up gorouter
How to review
-------------
🐟 review
Who can review
--------------
Anyone
> Scale up API in Ireland

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
Updated version includes https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/8 
How to review
-------------
Has already been tested in two dev envs
Who can review
--------------
Not me
> [#166697589] Bump paas-uaa-customized-boshrelease version

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations.d/331-uaa-database-key-rotation.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/operations.d/800-set-vcap-password.yml
What
----
Updated UAA to v73.3.0 
See https://www.pivotaltracker.com/story/show/167014830 for further details
How to review
-------------
Code review and deploy in dev running from current master
Who can review
--------------
Anyone
> [#167014830] Update UAA

- manifests/cf-manifest/env-specific/prod.yml
What
----
A tenant has finished load testing
How to review
-------------
Code review
> Scale down routers in prod/ireland

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
[Story](https://www.pivotaltracker.com/story/show/167170663)
What
----
Address USN BOSH Agent version: 2.215.3 USNs https://usn.ubuntu.com/3977-3/ by upgrading to latest PCF stemcells. https://docs.pivotal.io/pivotalcf/2-5/stemcells/stemcells.html#315-line
How to review
-------------
- 🔍 Code review
- 👀 [tlwr pipeline](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/18) (check the `paas-cf` resource)
See also
---
https://github.com/alphagov/paas-bootstrap/pull/292
Who can review
--------------
Not @tlwr
> Upgrade stemcells to 315.45

- terraform/pingdom/pingdom.tf
What
----
Fix typo, currently we have two checks with the same name
How to review
-------------
Code review
Who can review
--------------
@richardTowers
> Rename PaaS admin pingdom check to be correct

- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/lib/microsoft-oauth.sh
- concourse/scripts/pipelines-cloudfoundry.sh
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/operations/uaa-add-microsoft-oauth.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
- manifests/shared/spec/fixtures/environment-variables.yml
- scripts/upload-microsoft-oauth-secrets.sh
What
----
- Updates the pipeline so the MS OIDC env vars are supplied to paas-admin (https://github.com/alphagov/paas-admin/pull/285)
- Specifies the `enabled_microsoft_sso_166028126 ` paas-admin branch. **Please update this after the paas-admin PR is merged**
- Adds the paas-uaa-bosh-release dev build. **Please update this with the final build after merging https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/9**
- Switches uaa to our fork. **Review https://github.com/alphagov/paas-uaa-release/pull/4 and update the uaa release with the final build**
How to review
-------------
- Update paas-credentials due to https://github.com/alphagov/paas-credentials/pull/153
- Run the `upload-microsoft-oauth-secrets` make target
- Deploy to your dev env and follow the instructions …
> [#166028126] MS SSO flow

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/env-specific/default.yml
- manifests/cf-manifest/operations/scale-down-dev.yml
- manifests/cf-manifest/scripts/generate-manifest.sh
- manifests/cf-manifest/spec/manifest/dev_scaling_spec.rb
- manifests/cloud-config/cloud-config.yml
- manifests/variables.yml
- platform-tests/src/platform/availability/api/api_test.go
[Story](https://www.pivotaltracker.com/story/show/167228951)
What
----
More info in the story
- Vertically scale down the non-Diego
- Horizontally scale out the non-Diego, non-Broker instances
- Stop ignoring API availability tests during Dev
- Set API availability tests target reliability to 99% during Dev
How to review
-------------
- Code review
- Deploy to your developer environment (with pipeline changes)
- Trigger a full deployment (e.g. deploy stemcells `315.41`)
- Ensure the API availability tests pass (>=99%)
- Ensure the acceptance tests pass
- [tlwr pipeline](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/22)
Who can review
--------------
Not @tlwr
> [#167228951] Make slim developer environments highly available

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
What
----
See https://github.com/alphagov/paas-uaa/commit/f9705f0e3ed621cd7bc289261e69fc4cc9b9e611
Who can review
--------------
@richardTowers
> Update UAA to use our "fix"

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
See https://www.cloudfoundry.org/blog/usn-3977-3/
How to review
-------------
- Code review
- Green pipeline [tlwr](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/resources/paas-cf) see `4891b793`
Who can review
--------------
Not @tlwr
> Upgrade bosh stemcells to 315.64

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
See https://github.com/alphagov/paas-uaa/pull/5
How to review
-------------
Code review
[tlwr pipeline](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/27) see `paas-cf`
Who can review
--------------
@richardTowers
> Update UAA to use reverted migrations

- config/users.yml
What
----
- Remove Chris; different team, no more access
- Remove Rafal; different team, no more access
- Give Mo access to production; security clearance acquired and confirmed
- Add Emma (`cf_admin: false`; only SSO to Grafana)
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> User changes

- terraform/prod-lon.vpc_peering.json
What
----
Add VPC peering config for dit's staging/datasci-dev space
Why
----
Because DIT need VPC peering for this space
How to review
-------------
Code Review
Who can review
--------------
Not me!
> [SUPPORT] Add VPC peering config for dit-staging_datasci-dev

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
See
- alphagov/paas-cdn-broker#22
- alphagov/paas-cdn-broker-boshrelease#18
Bump of bump during review
> Bump CDN broker to use CNAMEExists version

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
Release https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/13, as built by https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-customized-release/jobs/build-final-release/builds/15.
How to review
-------------
Check the new build matches that merged PR.
Who can review
--------------
Not @46bit
> [#167666727] Improve SSO error sign in instruction text

- config/billing/config.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/billing/pricing_data.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
What
----
This adds the following Redis plans so we have more HA options available to tenants.
- tiny-ha-3.2 -> cache.t2.small
- small-ha-3.2 -> cache.t2.medium
How to review
-------------
- Code Review (confirm prices are correct)
- Deploy to your dev env 
- Create, bind and delete a service using the new plans 
Who can review
--------------
Not me
> [#167617997] Add Redis Plans

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Bump UAA to v74.1.0
How to review
-------------
- Pipeline
- Run down your pipeline and add a microsoft user, or use the TLWR dev environment to do so
Who can review
--------------
Not @tlwr
> Bump uaa to v74.1.0

- manifests/cf-manifest/env-specific/prod.yml
What
----
Scaling cells from 24 to 30
How to review
-------------
Code review
Who can review
--------------
Not me
> Scale Cells in Ireland

- terraform/prod-lon.vpc_peering.json
Adding a VPC peer for dit-staging / datasci-staging.
> Add VPC peer for dit-staging / datasci-staging

- concourse/pipelines/create-cloudfoundry.yml
What
----
We no longer need to copy logit secrets via the pipeline as it can be done via the Makefile.
How to review
-------------
Code review
Who can review
--------------
Not me
> Remove copying logit secrets to credhub concourse ns

- scripts/upload-logit-secrets.rb
What
----
The structure is:
- /logit/dev
- /logit/stg-lon
- /logit/prod
Prod has the same logit for both prod and prod-lon
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
Someone with access to paas-credentials
> Fix logit upload secret script

- manifests/cf-manifest/env-specific/prod.yml
What
----
We are currently undergoing dropped envelope events in Ireland. As a result we should increase the number of instances to aid in facilitating the throughput.
How to review
-------------
Code review
Who can review
--------------
Anyone
> [SUPPORT] Add some more doppler instances in Ireland

- README.md
What
----
We've migrated from travis-ci.org now, so this saves a redirect when you click the button.
How to review
-------------
* Check 'em
Who can review
--------------
Anyone
> Update README travis button to use travis-ci.com

- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
What
----
The commit "ac1f5401 Update exchange rate to prove we can" updated the
exchange rate, but did not actually generate the required output files
How to review
-------------
Code review
Who can review
--------------
@richardTowers (who generated the new exchange rate), or anyone else really
> Actually generate the new exchange rate

- terraform/cloudfoundry/cf_rds.tf
What
----
Upgrade CF DB to Postgres 11.1. We'll need a subsequent PR to upgrade to 11.5
How to review
-------------
- Scale your CF DB so it's HA
Who can review
--------------
Not me
> [#168372375] Upgrade CF DB to Postgres11

- platform-tests/src/platform/acceptance/http_forwarded_for_test.go
- platform-tests/src/platform/acceptance/plain_http_test.go
- terraform/cloudfoundry/dns-records.tf
- terraform/cloudfoundry/variables.tf
- terraform/dev.tfvars
- terraform/prod.tfvars
- terraform/staging.tfvars
What
----
Following on from https://github.com/alphagov/paas-cf/pull/2101, this updates the DNS records to point to the application load balancers. It also updates the custom acceptance tests to account for the changes.
How to review
-------------
Code review & deploy to your env 
Who can review
--------------
Not me
> [#167370656] Update CF Router DNS Records

- manifests/cf-manifest/operations.d/310-router.yml
What
----
Revert https://github.com/alphagov/paas-cf/pull/2103
🐝 Do not merge until we have verified that we are not receiving HTTP 1.0 requests 🐝 
How to review
-------------
Code review
Kibana chart
```
https://kibana.logit.io/s/665ca355-efc3-46a2-96cf-21d31a5305bb/app/kibana#/visualize/create?type=line&indexPattern=logstash-*&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(filters:!(),linked:!f,query:(query_string:(analyze_wildcard:!t,query:'_exists_:gorouter.httpversion')),uiState:(),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'4',params:(field:'@source.deployment.keyword',order:desc,orderBy:'1',row:!t,size:5),schema:split,type:terms),(enabled:!t,id:'2',params:(customInterval:'2h',extended_bounds:(),fiel …
```
> Revert "Revert "Increase gorouter number of idle connections""

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Upgrade cf-deployment to v12.1.0
How to review
-------------
Who can review
--------------
Not me
> [#168704085] Upgrade CF to v12.1.0

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/168452207)
What
----
See alphagov/paas-uaa#12
See alphagov/paas-uaa-release#14
How to review
-------------
Cherry pick the commit
Run your pipeline
Invite a user and spam the refresh button on the accept page
Who can review
--------------
Not @tlwr
> [#168452207] Bump UAA to 74.5 modified with robust invitations

- manifests/prometheus/alerts.d/s3_bucket_count.yml
- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
What
----
The s3 bucket limit in the prod account has been increased to 250. This updates
the alert to reflect the new value.
How to review
-------------
Code review
Who can review
--------------
Not me
> Update S3 Bucket limit

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Brings the two environments' rate limits in to parity. See the commit messages.
How to review
-------------
1. Read the commit messages
2. Check the changes
3. Look at the Kibana charts
4. Suggest better numbers?
Who can review
--------------
Anyone
> [#168454509] Adjust cc api rate limits

- concourse/pipelines/create-cloudfoundry.yml
What
----
Adds Credhub Interpolation To PaaS Admin Session
How to review
-------------
Code review
Who can review
--------------
Not me
> Add Credhub Interpolation To PaaS Admin Session

- platform-tests/src/platform/acceptance/apps_domain_dns_tls_test.go
- platform-tests/src/platform/acceptance/http_forwarded_for_test.go
- platform-tests/src/platform/acceptance/init_test.go
- platform-tests/src/platform/acceptance/plain_http_test.go
- platform-tests/src/platform/broker-acceptance/init_test.go
[Story](https://www.pivotaltracker.com/story/show/167370830)
What
----
- Remove FIXMEs after we've moved the Router LBs to be ALB only
- Remove FIXMEs after S3 broker is GA
How to review
-------------
Code review
Pipeline review of [tlwr](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/77)
Who can review
--------------
Not @tlwr
> [#167370830] Remove FIXMEs

- config/users.yml
What
----
Onboard Rafal again
How to review
-------------
Code review
There will be some manual cleanup to get rid of his old user account which I will do with Rafal
Who can review
--------------
Not @tlwr
> Onboard Rafal again

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
[Story](https://www.pivotaltracker.com/story/show/169617536)
What
----
Bump stemcells to 456.51
Bump cflinuxfs3-release to 0.140.0
These are the latest non-vulnerable releases from cf-deployment.
How to review
-------------
Code review
Review [`tag-releases`](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/80) 
Who can review
--------------
Not @tlwr
> [#169617536] Respond to CVEs

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
* fixing issue with Microsoft Edge not allowing people to login
More details in: alphagov/paas-uaa-customized-boshrelease#14
How to review
-------------
- Deploy the changes to your dev environment
> Bump Customised UAA

- terraform/cloudfoundry/shield_and_waf.tf
🚨 Do not merge this PR until PR 193 in the account wide terraform has been merged and applied in all environments 🚨 
What
----
We've subscribed to AWS Shield Advanced in our AWS parent account, and that gives our other accounts access. This applies DDoS protection to the application and system load balancers using an AWS WAF rate based rule.
How to review
-------------
1. Code review
2. Run it down your dev env, then check in the AWS console that your app and system load balancers are protected by the WAF (see the integrated services tab)
Who can review
--------------
Anyone
> [#167507410] Enable AWS Shield

- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
To take advantage of the security patches from upstream.
How to review
-------------
* Check the tests pass
* Check the hash matches https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-release/jobs/build-final-release/builds/2
Who can review
--------------
> Update UAA to our fork of v74.7.0

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/310-router.yml
[Story](https://www.pivotaltracker.com/story/show/169821848)
What
----
Respond to CVEs, see commit messages for USN/CVE numbers
- Upgrade routing release to 0.193
- Explicitly disable keepalives (enabled by default in 0.193) (we will change this later) (supersedes #2129)
- Updates [stemcells](https://docs.pivotal.io/platform/2-7/stemcells/stemcells.html) to 456.58
- Updates cflinuxfs3-release to 0.144
How to review
-------------
Code review
Run it down your pipeline
Read the story
Who can review
--------------
Not @tlwr
> [#169821848] Respond to CVEs

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
Bumps the stemcell version to 621.23
How to review
-------------
Paired on with @tlwr
> [#169620545][Blocked] Bump stemcell version to 621.23

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/upload-test-artifacts.yml
- scripts/credhub_shell.sh
- scripts/upload_secrets.rb
What
----
Following on from https://github.com/alphagov/paas-bootstrap/pull/324, this updates the credhub shell script to use a user's key.
How to review
-------------
⚠️ Blocked on ~https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/178~ ✅  and ~https://github.com/alphagov/paas-bootstrap/pull/324~
- Code review
- Update image tag before merging 
Who can review
--------------
Not me
> [#166500017] Update credhub_shell.sh to use individual keys

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are currently receiving alerts, prompting us that we may run out of compute power.
How to review
-------------
- Sanity check
> Increase number of cells in London

- config/service-brokers/aiven/config.json
What
----
We have at least one private beta participant using a trial org. We need them
to be able to provision the service.
How to review
-------------
1. Code review
Who can review
--------------
Anyone
> Make InfluxDB private beta plans available to trial orgs

- manifests/cf-manifest/operations.d/750-s3-broker.yml
What
----
We've added CORS functionality to the S3 broker and should release the
new version into the wild.
How to review
-------------
- Check if the version has been released
> Bump S3 broker

- scripts/upload_secrets.rb
What
----
We are now using personal ssh keys
The script previously relied on using the shared BOSH id_rsa
Now it should use our personal key
How to review
-------------
Code review
`make dev upload-aiven-secrets`
Who can review
--------------
Not @paroxp or @tlwr
> Fix upload_secrets.rb for personal BOSH ssh keys

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
Bumps cflinuxfs3 to v0.150.0
How to review
-------------
- Code review
- I've run it down my dev env 
Who can review
--------------
Not me
> [Support] Bump cflinuxfs3 to v0.150.0

- config/users.yml
What
----
The instructions had a warning about unexplained behaviour. We fixed that behaviour in #2185. This
PR updates the instructions to stop mentioning the behaviour.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit.
> Update instructions in `users/config.yml`

- config/accounts/documents/terms-of-use.md
What
----
There are content changes on Google Document that are now factored into
the platform. This content should hopefully be updated for people.
How to review
-------------
- Sanity check
- Validate content with the Doc ( https://www.diffchecker.com/ ) is probably enough...
> Update the terms of use

- concourse/pipelines/create-cloudfoundry.yml
What
----
This was missed during a previous upgrade of concourse.
How to review
-------------
Code review
Who can review
--------------
Anyone
> [support] switch last `aggregate` to `in_parallel`

- concourse/pipelines/create-cloudfoundry.yml
- manifests/prometheus/operations.d/302-scrape-paas-auditor.yml
What
----
We've done [a bunch of work on paas-auditor](https://github.com/alphagov/paas-auditor/compare/951653ff85f7434e748886b781ba0b84af740ed3...873bd133ad7ea7ba075f0716808517999efdf82c)
This PR:
- Removes paas-audit-to-splunk
- Deploys paas-auditor using a tagged release
- Scrapes paas-auditor using Prometheus
How to review
-------------
- Ensure the secrets exist in paas-credentials
- Ensure the secrets exist in your environment
- Run the pipeline
- Check Splunk
- Check metrics
Who can review
--------------
Worked on as a pair with @paroxp
> Paas auditor boogaloo

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
[Story](https://www.pivotaltracker.com/story/show/170455868)
What
----
See https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/22
How to review
-------------
Code review of attached PR
Review screenshot below from my dev environment
_Image of CloudFront distribution which shows `ServiceInstance` tag_
Who can review
--------------
Not @tlwr
> Bump CDN broker to tag distributions with guid

- tools/pipecleaner/README.md
What
----
Adds a readme for pipecleaner
How to review
-------------
Read the readme and check it makes sense
Who can review
--------------
Not @tlwr
> Add readme for pipecleaner

- manifests/cf-manifest/operations.d/750-s3-broker.yml
[Story](https://www.pivotaltracker.com/story/show/168696372)
What
----
See the following PRs
- https://github.com/alphagov/paas-service-broker-base/pull/3
- https://github.com/alphagov/paas-s3-broker/pull/18
- https://github.com/alphagov/paas-s3-broker-boshrelease/pull/9 
How to review
-------------
Paired with @schmie
Tested this in my development environment
> [#168696372] Use s3 broker with locks from service-broker-base

- tools/buildpacks/main.go
What
-------------
Fix update_buildpacks.sh to use latest rather than current release to read dependencies.
Also renamed the variable "release" to "latestRelease" to make the
variable name more descriptive (is this controversial?!)
How to review
-------------
Code review of `tools/buildpack/main.go`.
Run `scripts/update_buildpacks.sh` and check that `config/buildpacks.yml` is updated correctly, such that dependency versions match with (latest) buildpack release on GitHub.
Who can review
--------------
not @schmie
> Fix update_buildpacks to use latest version deps

- config/buildpacks.yml
What
----
Upgrade buildpacks to the latest releases
How to review
-------------
- Code review
Who can review
--------------
Not me
> [#170795651] Upgrade buildpacks

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
[Story](https://www.pivotaltracker.com/story/show/171123524)
What
----
Bump to latest pivotal network stemcell
Bump to latest cflinuxfs3 release which has sensible release notes
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> [#171123524] Bump stemcells to 621.55 and cflinuxfs3 to 0.162.0

- concourse/pipelines/create-cloudfoundry.yml
What
----
Bump to a version of paas-auditor which includes improved informer metrics and logs
Paired with @paroxp
> Bump paas-auditor to v0.64

- concourse/pipelines/create-cloudfoundry.yml
What
----
Bump to version with higher page sizing and faster ship cadence
Pair with @paroxp
> Bump paas-auditor to v0.66

- manifests/cf-manifest/operations.d/310-router.yml
- manifests/cf-manifest/spec/manifest/router_spec.rb
[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/170545858)
What
----
Re-enable HTTP keepalives to apps behind gorouter
We think this will increase performance and decrease latency
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Re-re-re-enable keepalives

- scripts/credhub_shell.sh
What
----
We can now use the hostname directly
How to review
-------------
Code review
Try it out
Who can review
--------------
@richardTowers
> Lookup BOSH hostname via DNS not AWS

- concourse/pipelines/create-cloudfoundry.yml
What
----
This includes more memory in the app manifest
How to review
-------------
Code review
[See changes](https://github.com/alphagov/paas-auditor/commit/b04c2ffc49dbe140bb8728589321905b805d7d63)
Who can review
--------------
Not @tlwr
> Bump paas-auditor to v0.67

- manifests/cf-manifest/operations.d/320-cc-ship-logs-for-auditing.yml
- manifests/cf-manifest/operations.d/330-uaa-ship-logs-for-auditing.yml
What
----
Adds an auth logs Cloudwatch log group and ships the auth.log from all instances to this group. It also adds a Cloudwatch subscription so these logs are shipped to Splunk.
How to review
-------------
Code review and deploy to your dev env 
Who can review
--------------
Not me
> [#169623326] Retain SSH logs from VMs

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
Cod review
Who can review
--------------
@AP-Hunt
> Increase number of cells from 42 to 45 in London

- concourse/pipelines/create-cloudfoundry.yml
What
----
We have now procured Aiven's InfluxDB service! We did a small private beta for particular users, and now this commit enables the existing tiny plan for everyone.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit.
> [#171539917] Enable tiny InfluxDB for everyone

- scripts/credhub_shell.sh
What
----
[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/171787442)
Updates a link
How to review
-------------
Code review
Try it out
Who can review
--------------
Not @tlwr
> Update bosh UAA link in credhub-shell script

- manifests/cf-manifest/env-specific/prod.yml
What
----
We are hitting our required == current alert in Ireland, and we may need
to scale more in the coming days
How to review
-------------
Code review
Who can review
--------------
@richardTowers
> Scale ireland to 33 cells from 30

- manifests/cf-manifest/env-specific/prod.yml
What
----
As there are some high demand services being deployed to the PaaS let's
make sure we have plenty of capacity.
How to review
-------------
Code review
Who can review
--------------
Anyone
> Scale up cells in Ireland

- manifests/cf-manifest/env-specific/prod.yml
What
----
We are experiencing logging unreliability due to low capacity in ireland
Increase provisioning by 20%
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Scale dopplers in ireland

- manifests/cf-manifest/env-specific/prod.yml
What
----
Adding a further 3 cells to Ireland to ensure that we have plenty of headroom. As we're likely to get pretty busy.
How to review
-------------
Code review
Who can review
--------------
Anyone
> Add a further 3 cells to Ireland

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
More details at alphagov/paas-cdn-broker#30
> Introduce self-healing CDN Broker

- config/billing/config-parts/redis_pricing_plans.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/billing/pricing_data.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
What
----
Adds large and xlarge redis plans
How to review
-------------
Code review and deploy to your dev env 
Who can review
--------------
Not me
> [#171978668] Add large and xlarge redis plans

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
In order to mitigate USN-4298-1 we need to update the stemcell to the
latest version.
How to review
-------------
Code review
Who can review
--------------
Anyone
> [SUPPORT] Update stemcells

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
[Story](https://www.pivotaltracker.com/story/show/171896697)
What
----
See https://github.com/alphagov/paas-cdn-broker/pull/33
How to review
-------------
Code review
The bulk of the review has happened in the CDN broker PR which has detailed steps for how a review was conducted
Who can review
--------------
Not @tlwr
> [#171896697] Bump CDN broker to include necessary fields

- concourse/pipelines/create-cloudfoundry.yml
https://github.com/alphagov/paas-aiven-broker/releases/tag/v0.24.0
> Bump to the latest aiven broker

- config/service-brokers/aiven/config.json
- config/spec/service_broker_spec.rb
- manifests/cf-manifest/operations.d/711-rds-broker-postgres95-plans.yml
- manifests/cf-manifest/operations.d/712-rds-broker-mysql57-plans.yml
- manifests/cf-manifest/operations.d/713-rds-broker-mysql57-plans-high-iops.yml
- manifests/cf-manifest/operations.d/714-rds-broker-postgres10-high-iops-plans.yml
- manifests/cf-manifest/operations.d/715-rds-broker-postgres10-plans.yml
- manifests/cf-manifest/operations.d/716-rds-broker-postgres11-plans.yml
- manifests/cf-manifest/operations.d/717-rds-broker-postgres11-high-iops-plans.yml
- manifests/cf-manifest/operations.d/718-rds-broker-mysql80-plans.yml
- manifests/cf-manifest/operations.d/719-rds-broker-mysql80-plans-high-iops.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/spec/manifest/elasticache_broker_spec.rb
- manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
What
----
This PR:
- Updates the URL for RDS documentation for Pazmin marketplace
- Removes cost metadata for service brokers (this has never been used)
- Adds spec tests for broker metadata
- Makes broker metadata display names more consistent
How to review
-------------
Code review commit by commit
Review [tlwr marketplace](https://admin.tlwr.dev.cloudpipeline.digital/marketplace)
Who can review
--------------
Not @tlwr
Review with https://github.com/alphagov/paas-admin/pull/696
---
I plan on getting this out tomorrow
> Update marketplace metadata

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Increases the number of cells in London and reduces the number in Ireland
How to review
-------------
Code review
Who can review
--------------
Not me
> [Support] Bump cells in London and reduce cells in Ireland

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/230-loggregator-deployment.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Upgrades CF to v12.41
UAA PRs
https://github.com/alphagov/paas-uaa/pull/18
https://github.com/alphagov/paas-uaa-release/pull/21
How to review
-------------
- Deploy to your dev env 
- Update UAA release
Who can review
--------------
Not me
> [#172330788] Upgrade CF to v12.41

- manifests/cloud-config/paas-cf-cloud-config.yml
- manifests/prometheus/env-specific/default.yml
- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
- manifests/prometheus/env-specific/stg-lon.yml
- manifests/prometheus/operations.d/100-set-persistent-disks.yml
What
----
We will soon run out of space in London, so increase it (but only in London)
How to review
-------------
Code review
[Check my pipeline](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/prometheus-deploy/builds/13)
Who can review
--------------
Not @tlwr
> Increase prometheus persistent disk size in London

- concourse/scripts/check-certificates.rb
What
----
Colorize the output to make it more obvious
Reduce the complexity of the script:
* ideally it shouldn't ignore _old but that is for another day
* we don't actually care about which certificate is expiring
(transitional or not), if we have got 15 days or fewer to go there is a
problem
* highlight transitional certificates so we can see if a pipeline run is
going to change things
* adds some error handling
How to review
-------------
Code review please
[Check the output](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/check-certificates/builds/21)
Who can review
--------------
Not @tlwr
> Improve check certificates output

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
[Story](https://www.pivotaltracker.com/story/show/172458520)
What
----
See the commits for the individual CVEs and USNs
See https://docs.pivotal.io/platform/stemcells/stemcells.html
How to review
-------------
Code review
Look at https://grafana-1.tlwr.dev.cloudpipeline.digital/d/bosh_deployments/bosh-deployments?orgId=1 🥧 💹 
Who can review
--------------
Not @tlwr
> [#172458520] Stemcell 621.71

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
[Story](https://www.pivotaltracker.com/story/show/170185372)
What
----
See https://github.com/alphagov/paas-cdn-broker/pull/34
Tested manually in my development environment
Who worked on this
--------------
Paired with @barsutka
> [#170185372] Bump cdn-broker version to not overwrite headers

- manifests/prometheus/env-specific/prod.yml
What
----
We are at 90% disk space, we should provision more
200GB matches prod-lon
How to review
-------------
Code review
[Alert](https://grafana-1.cloud.service.gov.uk/explore?left=%5B%22now-6h%22,%22now%22,%22prometheus%22,%7B%22expr%22:%22bosh_job_persistent_disk_percent%20%3E%2050%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
Who can review
--------------
Not @tlwr
> Prod (ireland) prometheus disk size matches london

- concourse/pipelines/create-cloudfoundry.yml
[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/172669686)
What
----
See https://github.com/alphagov/paas-billing/pull/90
How to review
-------------
YAML review
Who can review
--------------
Not @tlwr
> [#172669686]  Bump paas-billing to use go 1.13

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
https://github.com/alphagov/paas-cdn-broker/pull/35
I've deployed this to my development environment
How to review
-------------
See the PR
Who can review
--------------
Not @tlwr
> Bump CDN broker to fix renewals

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
[Story](https://www.pivotaltracker.com/story/show/172855757)
What
----
CVEs
How to review
-------------
Code review
Ran this down my dev env - [check it](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/16)
Who can review
--------------
Not @tlwr
> [#172855757] Respond to CVEs

- manifests/cf-manifest/env-specific/prod-lon.yml
Signed-off-by: Toby Lorne <toby.lornewelch-richards@digital.cabinet-office.gov.uk>
What
----
Over the past week we've been touching the limit, I think it is time to scale up again
_Chart of the last 7 days of capacity_
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
> Add more cells in London

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
See
https://github.com/alphagov/paas-cdn-broker/pull/37
https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/34
How to review
-------------
I've done happy path create/update/delete in my development environment, [check the version](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/47)
Who can review
--------------
Not @tlwr
> Bump cdn-broker: no automated undesired behaviour

- terraform/prod-lon.vpc_peering.json
What
----
In the dev space of the ukef-staging org, there should be a VPC peering as per https://govuk.zendesk.com/agent/tickets/4105542
How to review
-------------
Code review
CI
Who can review
--------------
Someone from the GOV.UK PaaS team
Someone who can check on UKEF side
> Add VPC peering for ukef-staging dev

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We've seen a steady upward trend in usage over the last 30 days, and we've reached our threshold for adding new cells.
How to review
-------------
1. Check I added a multiple of 3
Who can review
--------------
Anyone
> Add 3 cells in the London region

- manifests/cf-manifest/env-specific/prod.yml
What
----
We aren't that close to capacity, however I want to check if increasing capacity has a tangible effect on Notify's API latency
This represents an 8% increase in capacity
How to review
-------------
YAML review
Who can review
--------------
Not @tlwr
> Increase the number of cells in Ireland

- manifests/cf-manifest/operations.d/330-uaa.yml
[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/173342691)
What
----
Read https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/17
Pair with @kr8n3r
> [#173342691] Update uaa-customized release to be more a11y

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
- manifests/cf-manifest/spec/manifest/base_properties_spec.rb
[Story](https://www.pivotaltracker.com/story/show/170700038)
What
----
⚠️  See https://github.com/alphagov/paas-cf/pull/2328 and https://github.com/alphagov/paas-admin/pull/893 which should both be merged before this
How to review
-------------
Deploy to your development environment and do a user journey, or [check my development environment](https://admin.tlwr.dev.cloudpipeline.digital/password/request-reset)
Who can review
--------------
Not @tlwr
> [#170700038] Use pazmin for password resets

- concourse/pipelines/create-cloudfoundry.yml
What
----
See
https://github.com/alphagov/paas-aiven-broker/pull/23
https://github.com/alphagov/paas-aiven-broker/pull/24
How to review
-------------
Code review
CI
Who can review
--------------
Not @tlwr
> Bump aiven broker to v26 (better prometheus)

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Release shows if a service needs updating
https://github.com/alphagov/paas-cdn-broker/pull/39
How to review
-------------
Run down my pipeline
Andy tested the CDN manually with the DB
Going to release on Monday
> release of cdn broker to include dns updates

- manifests/prometheus/env-specific/prod-lon.yml
What
----
In case 7117469421 we increased our London RDS limit to 750, we should update it in the repo
How to review
-------------
Code review
> Increase configured RDS limit

- manifests/cf-manifest/env-specific/prod.yml
What
----
This should be reverted when they are finished
How to review
-------------
Code review
> Add 6 more cells in Ireland for Notify load test

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
[Story](https://www.pivotaltracker.com/story/show/173382894)
What
----
Respond to CVEs, see story
How to review
-------------
Deployed to my development environment
> [#173382894] Update stemcells to 621.76

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/upload-test-artifacts.yml
What
----
See this PR https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/191
How to review
-------------
Code review
CI
Who can review
--------------
@paroxp :bowtie:
> Use latest ruby 2.7 images

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
[Story](https://www.pivotaltracker.com/story/show/173513661)
How to review
-------------
Code review
Check https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/tag-release/builds/60 is green with this commit
Who can review
--------------
@whi-tw
> [#173513661] Bump cflinuxfs3 to 0.197

- concourse/tasks/tag-repo.yml
What
----
Otherwise we see WARNING: UNPROTECTED PRIVATE KEY FILE!
How to review
-------------
Code review
Review [pipeline failure](https://deployer.london.staging.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/deploy-paas-billing/builds/174)
> create-cloudfoundry: tag-repo sets permissions

- terraform/prod-lon.vpc_peering.json
What
----
Prashanth from Cabinet Office NSRA team, has asked for VPC peering
providing the following details for the connection.
How to review
-------------
- Sanity check
> Add new VPC peering configuration

- concourse/pipelines/create-cloudfoundry.yml
What
----
For whatever reason this was not done before
How to review
-------------
Code review
Check dev Kibana for `@source.app_name:"aiven-broker"` 
Who can review
--------------
Not @tlwr
> Ship aiven broker logs to Logit

- config/buildpacks.yml
[Story](https://www.pivotaltracker.com/story/show/173660600)
What
----
Updates the buildpacks for July
How to review
-------------
Code review
Look at the email in the story
> [#173660600] [do not merge until July 14] buildpacks: july update

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
London:  57 => 54
Ireland: 45 => 42
How to review
-------------
Check I put the numbers in right and did the maths right. Cells numbers should be multiples of 3.
Who can review
--------------
Anyone
> Adjust cell counts in London and Ireland prod regions

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are very close to capacity, so we should scale out
https://grafana-1.london.cloud.service.gov.uk/d/paas-user-impact/user-impact-prod-lon?orgId=1&refresh=5s&fullscreen&panelId=11
How to review
-------------
Code review
Dashboard review
> cf: scale out cells to 57 in London

- terraform/scripts/generate_vpc_peering_test.go
What
----
We are going to allow GOV.UK to set up a VPC peering which is outside of the
range we normally grant to tenants. This will introduce a wider set of CIDR
blocks being alloated to tenants, in a way that isn't wholly consistent. To
prevent future us from accidentally allocating a block that overlaps with our
own infrastructure, this commit adds a test to check that very thing.
How to review
-------------
1. Code review
2. Check the tests pass
Who can review
--------------
Anyone
> Ensure VPC peering CIDR blocks don't overlap with our infrastructure

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/19
Pair with @kr8n3r
> cf: use accessible side by side UAA customised

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/20
Who can review
--------------
not @kr8n3r
> Update UAA Customised to fix error summary link href syntax and update layout

- concourse/pipelines/create-cloudfoundry.yml
- concourse/spec/pipelines_spec.rb
What
----
In #2403 we typo'd in a dev branch name, this has been merged but not deployed yet
This PR:
- adds a test that alphagov branches are appropriately named
- fixes the branch name for paas-cf
How to review
-------------
Code review
CI
Who can review
--------------
@schmie
> Fix branch name

- concourse/pipelines/create-cloudfoundry.yml
What
----
Remove S3_BROKER_PASS from app-autoscaler job
Doesn't seem needed or used?
How to review
-------------
Who can review
--------------
Not @philandstuff
> Remove S3_BROKER_PASS from app-autoscaler job

- config/buildpacks.yml
[Story](https://www.pivotaltracker.com/story/show/174418394)
What
----
Update buildpacks
Hi,
We will be upgrading most of the platform's buildpacks on or after 2020-08-27.
We’re letting you know about the planned buildpack updates so you can make any necessary changes to your application before the upgrade takes place. Please make sure that the versions of the languages you’ve pinned are compatible with the versions available in the planned releases. If you've pinned the patch version, please review the release notes below to confirm if it's supported. We recommend pinning the minor version to minimise the changes required.
If you have any problems using the new versions in the buildpacks, or working to these timelines, please contact us via our help desk: …
> [#174418394] buildpacks: update for August [do not merge until 27th]

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/310-router.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
What
----
[Story](https://www.pivotaltracker.com/story/show/174548879)
How to review
-------------
Code review
Story review
Who can review
--------------
Not @tlwr
> [#174548879] Respond to CVEs

- config/billing/config-parts/elasticsearch_pricing_plans.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/service-brokers/aiven/config.json
- platform-tests/aiven-broker-acceptance/elasticsearch_service_test.go
What
----
- fixes typo in 6.x metadata
- adds Elasticsearch 7.x in Aiven broker and billing
- re-enables Elasticsearch acceptance test using 7.x
How to review
-------------
Code review
Check billing configuration particularly
Run down your pipeline and check that it spins up an Elasticsearch instance
Who can review
--------------
Not @tlwr
> Enable elasticsearch 7.x

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Increase number of cells in London as we would like more capacity
Decrease number of cells in Ireland as we have excess capacity
How to review
-------------
Code review commit by commit, to look at the linked dashboards
Who can review
--------------
Not @tlwr
> Adjust number of cells in production

- platform-tests/go.mod
What
----
Maxim's fixup commit got dropped during my rebase
How to review
-------------
This was reviewed in #2444
> Adjusting the cf-test-helpers in go.mod

- terraform/prod.vpc_peering.json
What
----
Added VPC peering details for Pay's test environment
How to review
-------------
Sense check with @danworth or @rjbaker 
Who can review
--------------
PaaS team members
> Pay Test VPC Peering

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/23
How to review
-------------
compare values with concourse build
Who can review
--------------
not @kr8n3r
> Update to latest uaa-customised

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
The body of this work is covered in https://github.com/alphagov/paas-rds-broker/pull/122
How to review
-------------
Review https://github.com/alphagov/paas-rds-broker/pull/122
CI
Check out TLWR dev env, you should be able to:
```
cf t -o admin -s billing
cf conduit accounts-db -- psql
> CREATE SCHEMA hello;
> SET search_path TO hello;
> CREATE TABLE foo (id TEXT);
```
Who can review
--------------
Not @tlwr
> cf: rds-broker search path stays intact

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Staging timeouts because R takes a long time to build
How to review
-------------
code review
Who can review
--------------
Shmeh
> R takes a long time to build

- .github/PULL_REQUEST_TEMPLATE.md
What
----
Remove "Who can review" from the PR template, because it's invariably "Not me"
How to review
-------------
Read the code, smash the tick button
Who can review
--------------
Not me
> Remove "who can review" from the PR template

- config/service-brokers/sqs/prod-lon-config.json
What
----
we are trialing the sqs integration with the DCS team and want the
service enabled for their london org.
---
> sqs: enable for gds-document-checking-service org

- manifests/cf-manifest/operations.d/760-sqs-broker.yml
What
----
New version of SQS broker that supports synchronous binding.
How to review
-------------
---
> sqs-broker: bump version.

- manifests/cf-manifest/operations.d/760-sqs-broker.yml
What
----
I forgot to pull the submodule in the boshrelease repo so 0.1.9 didn't
have the code i thought it had :grimacing:
How to review
-------------
🤷 
---
> bump sqs-broker again

- manifests/cf-manifest/operations.d/760-sqs-broker.yml
What
----
0.1.10 was broken because i pulled the wrong branch for the submodule
:facepalm:
How to review
-------------
---
> bump sqs-broker again, again

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
From
https://github.com/alphagov/paas-rds-broker-boshrelease/pull/96
https://github.com/alphagov/paas-rds-broker/pull/123
How to review
-------------
Works in my dev env:
Gonna merge it on Monday
---
> cf: bump rds broker update minor version

- manifests/cf-manifest/operations.d/710-rds-broker.yml
[Story](https://www.pivotaltracker.com/story/show/175373731)
What
----
➡️  Instructions for review ➡️ https://github.com/alphagov/paas-rds-broker/pull/124
ℹ️  Related: https://github.com/alphagov/paas-rds-broker-boshrelease/pull/97
⚠️  This needs to be updated to use a non-dev release once ⬆️  is merged
---
> [#175373731] bump rds broker to point in time recovery

- manifests/app-autoscaler/operations.d/300-set-plans.yml
What
----
Make people happy about having details on autoscaler.
How to review
-------------
- Deploy to your devenv (or see tlwr)
- Checkout the marketplace for detailed view
---
> autoscaler: Add metadata

- terraform/prod-lon.vpc_peering.json
What
----
Added VPC peering for the activity-stream space in the  dit-services organisation.
How to review
-------------
?
---
> Add VPC peering for dit-services / activity-stream

- concourse/pipelines/create-cloudfoundry.yml
- config/service-brokers/aiven/config.json
- platform-tests/aiven-broker-acceptance/elasticsearch_service_test.go
What
----
Re-enable ES6 service access and plans
Reverts https://github.com/alphagov/paas-cf/pull/2506
How to review
-------------
Code review
---
> [Support] Re-enable ES6 service access and plans

- terraform/prod-lon.vpc_peering.json
What
----
Add VPC peering for dit-staging_lite (4318693)
How to review
-------------
Code review
---
> [Support] Add VPC peering for dit-staging_lite

- terraform/prod-lon.vpc_peering.json
What
----
Updates VPC peering for dit-staging_lite as the previous one was setup incorrectly
How to review
-------------
Code review
---
> [Support] Update VPC peering for dit-staging_lite

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Scale doppler instances due to logging alerts firing.
How to review
-------------
Code review
---
> [Support] Scale dopplers in london and ireland

- terraform/cloudfoundry/vpc_peering.tf
What
----
Reverting as it resulted in a provider error.
The bug: https://github.com/hashicorp/terraform-provider-aws/issues/12829
How to review
-------------
Code review
---
> [Support] Revert VPC peering terraform update

- terraform/pingdom/pingdom.tf
- terraform/scripts/set-up-pingdom.sh
What
----
We had not set `responsetime_threshold` which means that the default of
30000 ms is used.
How to review
-------------
Code review and check against https://github.com/russellcardullo/terraform-provider-pingdom
---
> Add `responsetime_threshold` to Pingdom checks

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
The trend for the last 30 days has been generally upward. We're reaching a point where we need to scale again.
How to review
-------------
Check it's a multiple of 3.
---
> Scale prod-lon cells to 66

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
[Story](https://www.pivotaltracker.com/story/show/174949344)
This PR is to deploy a new uaa-customised bosh release - the actual change is in this [PR](https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/24)
How to review
-------------
1. Code review
2. Deploy to your DEV env. 
3. Goto "https://admin.(your-system-dns)" - pazmin login page (a redirected page to uaa-customised) should show two additional links - "Forgot your password?" and "Request an account" under the **Sign in to GOV.UK PaaS** form.
Who can review
---
Not @barsutka 
---
> Bump uaa-customized release version

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
This ships https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/25 - a footer update for our UAA user interface.
YAML as provided by https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-customized-release/jobs/build-final-release/builds/12.
How to review
-------------
Cursory review--check the YAML.
---
> [#175850494] Ship UAA Customised build with custom footer

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
This ships alphagov/paas-uaa-customized-boshrelease#26 - a footer link to our channel on cross-gov Slack instance
YAML as provided by https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-customized-release/jobs/build-final-release/builds/13
---
> [175890889]Ship UAA Customised build with x-gov slack link

- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
See Zendesk ticket #4374840
How to review
-------------
Check my spelling, and which region it's in
---
> Grant govuk-accounts org access to Splunk broker in London

- tools/metrics/gauges_aws_health.go
- tools/metrics/gauges_aws_health_test.go
What
----
AWS had an incident with WAF recently, and we weren't monitoring for it. We may
have caught it earlier if we were.
Also adds a handful of other services that would be of interest to us.
How to review
-------------
1. Do you agree with the serivces?
2. Do the tests pass?
---
> Monitor more services via AWS Health

- concourse/pipelines/create-cloudfoundry.yml
- config/buildpacks.yml
- platform-tests/example-apps/app-autoscaler-cpu-usage/manifest.yml
- platform-tests/example-apps/healthcheck-pinger/manifest.yml
- platform-tests/example-apps/healthcheck-ponger/manifest.yml
- platform-tests/example-apps/healthcheck/go.mod
- platform-tests/example-apps/healthcheck/manifest.yml
- platform-tests/example-apps/healthcheck/vendor/modules.txt
- platform-tests/example-apps/http-tester/go.mod
- platform-tests/example-apps/http-tester/manifest.yml
- platform-tests/example-apps/logging-pipeline/manifest.yml
What
----
Upgrade buildpacks and bump platform test apps to go 1.15
How to review
-------------
Code review and deploy to your dev env
Don't forget to remove the WIP commit
---
> [#175905444] Buildpack upgrade

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
Bumps stemcell version and scales cells in london 
How to review
-------------
Deploy to your dev env
---
> [#176187151] Bump stemcell version and scale London

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Add 3 to London
Remove 12 from Ireland
How to review
-------------
See if you agree with the numbers
---
> Scale Ireland and London

- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
We've deleted `cabinet-office-nsra` and without this change our pipelines are blocked.
---
> Remove cabinet-office-nsra org

- concourse/pipelines/create-cloudfoundry.yml
What
----
We'd like to deprecate the older database versions, meaning, along with our tenants, we need to move on with our lives.
The idea here is to run the update manually once on all of the environments, and have this merged as oppose to over-engineering and future proofing it.
How to review
-------------
- Sanity check
---
> billing: Update database

- config/service-brokers/sqs/prod-lon-config.json
What
----
Gives access to `dof-dss` and `nicts-probate` in response to Zendesk ticket 4413824
How to review
-------------
Check I got the names right
---
> Grant SQS broker access to Northern Ireland orgs

- concourse/pipelines/create-cloudfoundry.yml
What
----
We're deprecating postgres 9.5. Upgrading to the latest.
How to review
-------------
- Sanity check
---
> Upgrade accounts-db

- manifests/prometheus/spec/dashboard_validation_spec.rb
What
----
It's easy to add a new dashboard with JSON that will result in an error uploading it. We should test for the most common things that stop it.
How to review
-------------
1. Check the tests pass
---
> Add a test to ensure Grafana dashboards have the correct JSON

- config/billing/config-parts/influxdb_pricing_plans.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/billing/pricing_data.yml
- config/service-brokers/aiven/config.json
What
----
Creates a larger InfluxDB so that:
1. We can bill tenants who are already on it
2. We can allow tenants to upgrade when they need i
How to review
-------------
Run it down your pipeline and try provision one
---
> Add new InfluxDB plan: small. 1vm/8gb mem/50gb storage

- terraform/prod.vpc_peering.json
What
----
It's blocking our pipeline at the minute.
Dom has confirmed, that the peering connection has been intentional, and won't
be coming back.
How to review
-------------
* Sanity check
* Ask Rafal for proof :trollface: 
---
> Remove VPC Peering with Pay

- scripts/upload-secrets/upload-paas-trusted-people.sh
What
----
Update paas-trusted-people to `main` as we're moving default branches
How to review
-------------
Code review
---
> Update paas-trusted-people to `main`

- concourse/pipelines/create-cloudfoundry.yml
- concourse/scripts/pipelines-cloudfoundry.sh
- concourse/spec/pipelines_spec.rb
What
----
Changed our repos to use the `main` default branch because that is now the default.
How to review
-------------
code review
---
> Changed our repos to use the `main` default branch.

- concourse/pipelines/create-cloudfoundry.yml
Followup PR: https://github.com/alphagov/paas-admin/pull/1159
---
> Use platform prometheus credentials in pazmin

- config/buildpacks.yml
What
----
Upgrades buildpacks
How to review
-------------
Code review and deploy to env 
---
> [#176478600] Upgrade buildpacks

- concourse/pipelines/create-cloudfoundry.yml
What
----
Introduce a job deploying static data as a private app for pazmin to consume.
How to review
-------------
- Run pipeline on your devenv
- Expect private app to have been created and running
- View performance dashboard to see valid and working data
---
> Introduce paas-admin-data app

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
This updates UAA to use the latest version with the updated banner
reflecting our live status.
How to review
-------------
code review against https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-customized-release/jobs/build-final-release/builds/14
---
> Update uaa-customised to remove beta banner

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Deploys [`paas-rds-broker` PR 132](https://github.com/alphagov/paas-rds-broker/pull/132).
How to review
-------------
1. Has been reviewed by @LeePorte 
---
> [#176574936] Prevent skipping major versions in RDS broker

- terraform/globals.tf
What
----
We're about to undergo a pen test and it will be off site this year so we need to add in the appropriate IP addresses
How to review
-------------
Code review against IP addresses in https://www.pivotaltracker.com/story/show/176768079
---
> [#176768079] Add Pen tester IP ranges

- terraform/globals.tf
What
----
Updated as the block wasn't correct
How to review
-------------
code review
---
> Update penterster IP addresses

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Upgrades CF from v15.4.0 to v16.1.0
Before merging 
-----
Review and rebase UAA PRs
Update UAA WIP commit to use the final build
How to review
-------------
Code review and deploy to your dev env
---
> [#176943877] Upgrade CF to v16.1.0

- .github/workflows/test_on_pr.yml
- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
Enable Splunk for cabinet office orgs
* cabinet-office-papt
* cabinet-office-tu-facility-time
How to review
-------------
Compare with ZenDesk ticket 4475956
---
> Enable Splunk for cabinet office orgs

- config/service-brokers/sqs/prod-lon-config.json
What
----
Add ccs-conclave-sssos to the list of orgs with SQS enabled
How to review
-------------
Check that I've added 'ccs-conclave-sssos' to the file, make sure I can json.
---
> support: Enable SQS for `ccs-conclave-sssos`

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- scripts/upload-secrets/upload-pingdom-secrets.rb
> Allow the scraper to interact with pingdom

- concourse/pipelines/create-cloudfoundry.yml
> Remove re-copying secret

- Makefile
- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/scripts/generate-manifest.sh
- manifests/cf-manifest/spec/support/manifest_helpers.rb
- scripts/upload-secrets/upload-psn-secrets.rb
- terraform/psn/data/security-group-seed.json.tpl
- terraform/psn/psn.tf
How to review
-------------
- Sanity check
---
> Introduce PSN connection

- concourse/pipelines/create-cloudfoundry.yml
- terraform/psn/psn.tf
What
----
The PSN Terraform failed when it got to production, because we aren't really able to test it before it gets there. This PR addresses the issues which came up in this iteration.
How to review
-------------
1. Code review
2. Try and spot anything else which might be an issue
---
> [#177001717] Correct PSN terraform variables

- manifests/cf-manifest/operations.d/760-sqs-broker.yml
What
----
This PR updates the SQS broker to include https://github.com/alphagov/paas-sqs-broker/pull/19
How to review
-------------
Check the changes against https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/sqs-broker-release/jobs/build-final-release/builds/13
---
> [#177115112] Update SQS Broker

- terraform/cloudfoundry/nat.tf
- terraform/vpc-peering/vpc_peering.tf
What
----
Adds a tag to the cf route tables so it can be used in vpc_peering.tf
How to review
-------------
Code review and deploy to dev env
---
> [Support] Specify CF Route Tables

- terraform/globals.tf
What
----
Our pen test is now complete, this PR removes the Pen test IP addresses from the restrictions
How to review
-------------
Code review
---
> [#176768129] Remove pentesters

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Deploys RDS broker 1.8.0
🚨 This branch currently has a WIP commit deploying a dev release of the broker, which will become 1.8.0 if testing passes🚨 
How to review
-------------
Deploy and test
---
> [#177267449] Deploy RDS broker 1.8.0

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
Mitigates the CVEs listed in the title. See Pivotal story #177461962 and the contents of the commits for more information.
How to review
-------------
- Check I'm upgrading to the right things
- Test in a dev environment?
---
> [#177461962] CVE mitigations for USN-4760-1, USN-4754-4, USN-4761-1, USN-4759-1

- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
Enable Splunk services for CCS orgs
ccs-pmp-idam
ccs-document-upload
How to review
-------------
---
> Enable Splunk services for CCS orgs

- Makefile
- config/billing/config-parts/influxdb_pricing_plans.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/billing/pricing_data.yml
- config/service-brokers/aiven/config.json
What
----
DIT want an InfluxDB instance with 1TB of storage. That would equate to an XXL plan on our scale.
How to review
-------------
1. It's deployed to the `dev02` environment, so go  provision and delete an instance.
---
> XXL InfluxDB service plan

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Utilisation has been steadily increasing over the last 30 days
Raises from 84 to 87.
How to review
-------------
Check it's a multiple of 3.
---
> Increase London's diego cell count to 87

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
We want to make sure we're running the latest, secure versions of the components we're using.
How to review
-------------
- Commit by Commit
- Sanity check
---
> Perform component upgrades

- terraform/prod-lon.vpc_peering.json
What
----
Add extra VPC peering for dit, as per [#4529613](https://govuk.zendesk.com/agent/tickets/4529613)
How to review
-------------
Code review
---
> [Support] Add VPC Peering for dit-staging_platform-staging

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/runtime-config/operations.d/510-add-prometheus-blackbox-exporter.yml
What
----
Upgrades Prometheus to version 26.4
How to review
-------------
Code review and deploy to dev 
---
> [#177183932] Upgrade Prometheus to version 26.4

- config/buildpacks.yml
What
----
Upgrades buildpacks 
How to review
-------------
Code review and deploy to dev 
---
> [#177183914] Upgrade Buildpacks

- manifests/cf-manifest/data/100-tenant-uaa-client-config.yml
What
----
Changed the scopes
How to review
-------------
Code review
---
> Change scopes for terraform-provider

- manifests/cf-manifest/data/100-tenant-uaa-client-config.yml
What
----
add in an `authorities: ` section
How to review
-------------
Code review
---
> Add `authorities: `

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/021-bionic-set-stemcells.yml
- manifests/cf-manifest/operations.d/030-bosh-dns.yml
- manifests/cf-manifest/operations.d/200-awslogs.yml
- manifests/cf-manifest/operations.d/320-cc-ship-logs-for-auditing.yml
- manifests/cf-manifest/operations.d/330-uaa-ship-logs-for-auditing.yml
- manifests/cf-manifest/spec/manifest/base_properties_spec.rb
What
----
Updates the Stemcell to Bionic, it also updates the version awslogs as the existing version would not compile on Bionic, there is also a bump for BOSH-DNS to the latest version
How to review
-------------
Code review and see https://deployer.lp.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry
How to merge
--------------
Review and merge https://github.com/alphagov/paas-awslogs-boshrelease/pull/2 then update the TMP commit with the final boshrelease details. Merge and deploy https://github.com/alphagov/paas-bootstrap/pull/454 first
Who can review
--------------
Anyone
---
> [#177960633] Upgrade Stemcells to Bionic

- manifests/prometheus/alerts.d/cc-api-job-queue-length.yml
- manifests/prometheus/alerts.d/cc-failed-job-count.yml
- manifests/prometheus/alerts.d/cc-log-error-count.yml
What
----
1. Include deploy env in example Kibana filters
2. Point to a known issue with Cloud Controller worker errors
How to review
-------------
1. Do you agree?
2. Has the deploy env been populated correctly?
---
> Improved alert messages

- concourse/pipelines/create-cloudfoundry.yml
- terraform/az-management/.gitignore
- terraform/az-management/.terraform.lock.hcl
- terraform/az-management/README.md
- terraform/az-management/main.tf
- terraform/az-management/variables.tf
- terraform/az-management/versions.tf
> Introduce AZ Management

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We've had pretty steady growth recently. We need more cells.
How to review
-------------
Are 102 cells enough?
---
> Add 6 cells to London, bringing it to 102

- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
What
----
To include https://github.com/alphagov/paas-elasticache-broker-boshrelease/pull/14
How to review
-------------
Check it matches https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/elasticache-broker-release/jobs/build-final-release/builds/5#L609bd9cc:43:46
---
> Bump Elasticache broker boshrelease

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
105 cells in London. We're seeing steady growth
How to review
-------------
Too few? Just enough?
---
> 105 cells in London

- concourse/pipelines/create-cloudfoundry.yml
What
----
Specifies the aiven broker in the pipeline, related to https://github.com/alphagov/paas-cf/pull/2679
How to review
-------------
Code review
---
> Specify aiven broker by using the -b flag

- config/buildpacks.yml
What
----
Performs the buildpack upgrades for June 2021
How to review
-------------
Check it matches what we told tenants.
---
> [#178298531] Perform buildpack upgrades for June 2021

- config/service-brokers/csls-splunk/prod-config.json
> Add Notify to Splunk broker

- config/service-brokers/csls-splunk/prod-lon-config.json
> Add another CCS org

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
[Story](https://www.pivotaltracker.com/story/show/178518722)
Updates:
cf-deployment: 16.15
cflinuxfs3: 0.242
stemcell ubuntu-bionic: 1.10
Set upstream UAA version to 75.2 to reflect 16.15 version, keeping local at 1.28 (74..) due to bugfix for sing-up being broken in 75.x
How to review
-------------
- Code review
- Test in development environment ([db migration for CAPI 1.111](https://github.com/cloudfoundry/cloud_controller_ng/blob/a3a1fc74df66e4532d217714a6fedea808247866/db/migrations/20210427221541_create_spaces_application_supporters_table.rb)).
Who can review
---
Not @schmie, @tomrosier 
---
> [#178518722] Address CVEs 14 06 2021

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
In d9bd96e81f3b we bumped to branch 16.15, but it either never existed or no longer exists.
How to review
-------------
Does the branch exist?
---
> Use CF acceptance test branch 16.14

- tools/metrics/go.mod
- tools/metrics/manifest.yml
> metrics: Bump Go version

- concourse/pipelines/create-cloudfoundry.yml
> autoscaler: Point to an existing branch upstream

- scripts/all_syslog_service_instances.py
What
----
Add script to list user-provided services with syslog URLs.
This can be used to find broken user-provided services that need tenant attention.
Based heavily on a script @risicle wrote for card 178432987.
Going to refer to this from team-manual.
How to review
-------------
Code review
---
> Add script to list user-provided services with syslog URLs

- concourse/pipelines/create-cloudfoundry.yml
What
----
Bump paas-prometheus-endpoints tag to include https://github.com/alphagov/paas-prometheus-endpoints/pull/10
How to review
-------------
Code review
---
> Bump paas-prometheus-endpoints tag

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/check-az-is-enabled-in-manifest.yml
- concourse/tasks/check-az-is-enabled-in-vpc.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/send-nagging-email-alert.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
> Use node chromium for acceptance tests

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
([Link to story](https://www.pivotaltracker.com/story/show/178824207)).
Upgrade bionic-stemcell to 1.13
Upgrade cflinuxfs3 to 0.247.0
How to review
-------------
- Code review
- Deploy in dev env that has been bootstrapped using https://github.com/alphagov/paas-bootstrap/pull/461
---
> [#178824207] Address CVEs

- manifests/cf-manifest/spec/manifest/env_spec.rb
- manifests/cf-manifest/spec/manifest/instance_type_counts_in_envs_spec.rb
What
----
Letting our numbers of API, scheduler, and CC worker instances get out of kilter has caused us problems recently. We should prevent that happening again by testing for it.
How to review
-------------
Code review
---
> Ensure scheduler and cc worker ratios

- Makefile
- config/logit/output/generated_logit_filters.conf
- scripts/generate_logit_filters.sh
What
----
Bump our copy of logsearch-for-cloudfoundry to a few commits ahead of the latest release
In particular we're after the gorouter performance fix as logit has noticed high CPU usage.
How to review
-------------
Review `config/logit/output/generated_logit_filters.conf` by running `make logit-filters` and check
the result is identical.
Code review the rest.
---
> Bump our copy of logsearch-for-cloudfoundry to a few commits ahead of the latest release

- terraform/az-monitoring/module/main.tf
> Restrict port 22 only to EC2 Instance Connect

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Increases cc workers and schedulers in london
How to review
-------------
Code review
---
> [Support] Increase cc workers and schedulers in london

- manifests/cf-manifest/operations.d/100-cf-update-vm-types.yml
What
----
Scale up diego-api instance type to xlarge
How to review
-------------
Code review
---
> [Support] Scale up diego-api instance type to xlarge

- terraform/cloudfoundry/cdn_broker.tf
- terraform/cloudfoundry/cf_rds.tf
What
----
Upgrade from PG11 to PG12
How to review
-------------
Wait for the size increase to go out to prod, then apply this and see if applys in staging
---
> Upgrade to pg 13 cf db, **Do not merge till after 01/11/21**

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Cell usage is creeping up.  Gotta keep up!
How to review
-------------
That right? Should we add another 3 on top? 
---
> Raise London diego cells to 126

- concourse/pipelines/create-cloudfoundry.yml
- config/billing/config-parts/currency_rates.json.erb
- config/billing/config-parts/vat_rates.json.erb
- config/billing/output/eu-west-1.json
- config/billing/output/eu-west-2.json
- config/billing/tests/eu-west-1_billing_rds_charges.feature
- config/billing/tests/eu-west-2_billing_rds_charges.feature
What
----
In order to run the billing cucumber changes they need to be run during the billing acceptance tests.
As they are different per region we have two different feature sets (getting them automatically created when the charges change is probably a good idea).
How to review
-------------
Deploy to a dev environment with the gherkin_test branch deployed
---
> Include billing cucumber tests

- Makefile
What
----
* Rather than hardcoding "devxx" as targets, use a wildcard rule.
* Add `current-branch` target, that populates the `BRANCH`
environment variable as the current checked out branch
How to review
-------------
* Code review, really.
---
> Update dev* make targets and add branch target

- manifests/prometheus/env-specific/prod-lon.yml
What
----
As per AWS support ticket #9138478491
---
> Raise Elasticache node count limit to 1000

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Releases https://github.com/alphagov/paas-rds-broker/pull/145
How to review
-------------
Release to a dev env, check you can restore a mysql database.
---
> rdsbroker: bump to version 1.18.0

- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/isolation-segments/prod/govuk-notify-production.yml
- manifests/cf-manifest/isolation-segments/prod/govuk-notify-staging.yml
What
----
Notify may have some extra traffic ahead and want to be able to do some load testing.
How to review
-------------
Look at it, check for typos. Don't think it's really testable.
---
> Notify isolation segments management

- config/buildpacks.yml
Upgrading:
- java_buildpack (CVE-2021-45046, CVE-2021-45105)
- php_buildpack (CVE-2021-45046, CVE-2021-44228)
> Bump buildpacks: php v4.4.53, java v4.47

- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
https://www.pivotaltracker.com/story/show/180738224
What
----
Unless aws are lying to me it should now be 600
How to review
-------------
Look at it, be happy.
---
> prometheus: bump aws_limits_s3_buckets to 600 for prod & prod-lon

- Makefile
- config/buildpacks.yml
What
----
Performs a buildpack upgrade for January 2022
How to review
-------------
Run it down a pipeline and make sure stuff is OK.
---
> [#180345496][2022/01/14] Buildpack upgrade for Jan 2022

- manifests/cf-manifest/operations.d/710-rds-broker.yml
https://www.pivotaltracker.com/story/show/179954369
What
----
This includes https://github.com/alphagov/paas-rds-broker/pull/148 and https://github.com/alphagov/paas-rds-broker/pull/149
How to review
-------------
Deploy to dev env and let the broker acceptance tests run? 
---
> paas-rds-broker: 1.21.0 -> 1.24.0

- terraform/globals.tf
What
----
Use static IP to reduce reliance on VPN and VPN/Docker conflicts.
How to review
-------------
Code review
---
> Add SMS IP to allow list

- concourse/pipelines/create-cloudfoundry.yml
What
----
The new billing work introduces database tests into the acceptance
tests.
As it stands this doesn't make much sense for smoke testing. 'make smoke' in
the nbi-part-two branch (the branch that should be merged to make the
new billing code live), change 'make smoke' to exclude the database
tests and be appropriate for running api tests.
How to review
-------------
Make pipelines in a dev environment and check the continuous-billing-smoke-tests
---
> Run make smoke for billing smoke tests

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are expecting and increase in load and prefer to over-provision in the first instance.
How to review
-------------
- Code review (any typos?)
- Wait for Linter/CI to be happy
---
> Increase router instances in London to 30

- config/buildpacks.yml
What
----
Performs a buildpack upgrade
How to review
-------------
Deploy to dev env
---
> [#181282586] Buildpack Upgrade

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/check-az-is-enabled-in-manifest.yml
- concourse/tasks/check-az-is-enabled-in-vpc.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/curl-az-healthcheck.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/send-nagging-email-alert.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
- manifests/app-autoscaler/operations.d/001-release.yml
- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
What
----
Updated the autoscaler to the latest release and updated the stemcell series to bionic
How to review
-------------
Review the code and the output in [the deployment job](https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/app-autoscaler-deploy/builds/136)
---
> Update autoscaler 5.0.4

- manifests/app-autoscaler/operations.d/001-release.yml
What
----
Updated the Autoscaler to 5.0.6 in order to address some CVEs
How to review
-------------
1. Code review
1. Review [deployment output](https://deployer.dev03.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/app-autoscaler-deploy/builds/32)
1. Review [test output](https://deployer.dev03.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/app-autoscaler-acceptance-tests/builds/23)
---
> [#181805761]  Update Autoscaler to 5.0.6

- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
Bump stemcell to 1.76
How to review
-------------
Deployed to dev02
---
> [#181943509] Bump stemcell to 1.76

- concourse/pipelines/create-cloudfoundry.yml
What
----
Update to latest tags with versions which use go1.18
How to review
-------------
Check the versions correspond to the latest tag in each
https://github.com/alphagov/paas-accounts/tags
https://github.com/alphagov/paas-prometheus-endpoints/tags
https://github.com/alphagov/paas-auditor/tags
---
> Upgrade app versions in pipeline

- manifests/prometheus/env-specific/prod-lon.yml
- manifests/prometheus/env-specific/prod.yml
What
----
...following an increase request.
Bumping the value used by this alert should quieten it until it starts to reach the new limit.
See https://www.pivotaltracker.com/story/show/182154107
How to review
-------------
:eyes:
---
> alerts: increase s3 bucket count limit in prod to 750

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Metrics suggest we're edging over 66% capacity in london.
How to review
-------------
:eyes: 
---
> prod-lon: bump number of cells to 150

- manifests/cf-manifest/operations.d/320-cc-add-quotas.yml
What
----
Adds a new 16xlarge org quota
How to review
-------------
Code review
---
> [Support] Add new org quota

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
https://www.pivotaltracker.com/story/show/182283743
Bumped both of these to address vulnerabilities.
How to review
-------------
Deploy to a dev env.
I've successfully deployed it to `dev03`. Needed quite a few retries, but that's not hugely uncommon for a slim deployment. Deploy it yourself if you're anxious.
---
> cflinuxfs3: 0.278.0 -> 0.299.0, bionic stemcell: 1.76 -> 1.84

- manifests/prometheus/dashboards.d/user-impact-redux.json
- manifests/prometheus/dashboards.d/user-impact.json
What
----
Update the user impact dashboard to ignore the Watchdog alert - this is always firing, which is *good*.
How to review
-------------
Code review?
---
> [#181945547] Ignore heartbeat alert in user impact dashboard

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We find ourselves overprovisioned now that a tenant has decided to kill their surplus tasks.
How to review
-------------
:eyes: 
---
> prod-lon: reduce number of cells now a tenant is being less wasteful

- .github/workflows/automatic_buildpack_bump_pr_body.md
- .github/workflows/generate_buildpack_bump_pr.yml
What
----
Adds some extra detail to the body of the PR which is raised when our buildpacks get bumped once a month.
How to review
-------------
Do you agree with what I've written?
---
> Improve the contents of the buildpack bump PR

- manifests/cf-manifest/env-specific/prod.yml
What
----
This is the same as the total number of cells in prod, which is still absurd but not obscene.
How to review
-------------
:eyes: 
---
> prod: reduce number of routers to 48

- manifests/cf-manifest/env-specific/prod.yml
What
----
This should help us learn more about its scaling characteristics ahead of our RI-re-purchasing.
How to review
-------------
:eyes:
---
> prod: reduce number of loggregator instances

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
https://www.pivotaltracker.com/story/show/182790768
Dopplers still aren't really breaking a sweat.
How to review
-------------
:eyes: 
---
> prod-lon: reduce number of dopplers to 45

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
Deploy changes in https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/31
How to review
-------------
- check against https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-customized-release/jobs/build-final-release/builds/4
---
> Update UAA release

- manifests/prometheus/dashboards.d/bosh-jobs-heatmaps.json
- manifests/prometheus/dashboards.d/doppler-heatmaps.json
- manifests/prometheus/dashboards.d/forwarder-agents.json
- manifests/prometheus/dashboards.d/log-cache.json
- manifests/prometheus/dashboards.d/reverse-log-proxy.json
- manifests/prometheus/dashboards.d/syslog-agents.json
What
----
Added a "doppler heatmap" dashboard which (I think) is more useful than the supplied "Doppler Server v2" dashboard.
Made stacked dropped-messages plots linear as logarithmic plots weirdly distort stacked plots.
A couple of other minor tweaks.
How to review
-------------
:eyes:
---
> Various dashboard improvements

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Releasing https://www.pivotaltracker.com/story/show/181790593 (https://github.com/alphagov/paas-rds-broker/pull/158)
How to review
-------------
:eyes: , have already tested this TBH, but you could deploy it to a dev env if you like and check the custom broker acceptance tests pass.
---
> paas-rds-broker: 1.31.0 -> 1.34.0

- manifests/app-autoscaler/operations.d/001-release.yml
What
----
Update autoscaler to 6.1.0
How to review
-------------
* Code Review
* 2i on acceptance tests in dev03 (they have passed, but just look at them to convince yourself!
---
> Update autoscaler to 6.1.0

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/spec/manifest/certificates_spec.rb
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
* Upgrade cf-deployment checkout to v21.8.0
* Upgrade bionic-stemcell to 1.97 (added in alphagov/paas-bootstrap/pull/515)
How to review
-------------
- Code review - any typos
- Deploy to dev environment 
---
> [#183012348] Upgrade cf-deployment to v21.8.0

- config/buildpacks.yml
- scripts/update_buildpacks.sh
- tools/buildpacks/main.go
What
----
1. Enables buildpack upgrades to be targeted
2. Upgrades Python buildpack
How to review
-------------
Code review, please
---
> [2022-08-29] Enable targeted buildpack upgrades

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
https://www.pivotaltracker.com/story/show/181795532
Contains changes from https://github.com/alphagov/paas-cdn-broker/pull/62 & https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/52
How to review
-------------
You _could_ send it to a dev env, but that has already been done really (see dev03's release history)
---
> cdn-broker: 0.1.49 -> 0.1.50

- manifests/prometheus/alerts.d/aws-elb-unhealthy-nodes.yml
- manifests/prometheus/alerts.d/cloudfront_tls_certificates_validity.yml
- manifests/prometheus/alerts.d/concourse-billingsmoketests-failures.yml
- manifests/prometheus/alerts.d/concourse-check-certificates-failures.yml
- manifests/prometheus/alerts.d/ec2_cpu_credits.yml
- manifests/prometheus/alerts.d/gorouter-latency.yml
- manifests/prometheus/alerts.d/platform_tls_certificates_expiry.yml
- manifests/prometheus/alerts.d/rds_cpu_credits.yml
- manifests/prometheus/alerts.d/rds_disk_utilisation.yml
- manifests/prometheus/alerts.d/uaa-failed-login-user-not-found.yml
- manifests/prometheus/alerts.d/uaa-failed-login-wrong-password.yml
- manifests/prometheus/alerts.d/watchdog.yml
- manifests/prometheus/spec/alerts/gorouter-latency.test.yml
What
----
- Fixes broken links
- Adds suggestion for resolving ConcourseBillingSmoketestsFailuresCritical
How to review
-------------
Check the links work, and that you agree with the suggestion
---
> Fix broken links, add detail to ConcourseBillingSmoketestsFailuresCritical

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
~*This depends on https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/246 and will need its docker image tags changed to the final value once that is merged*~
https://www.pivotaltracker.com/story/show/183025078
This deploys the improvements from https://github.com/alphagov/paas-rds-broker/pull/160 ~and adds custom broker acceptance test coverage for it.~
How to review
-------------
Deploy to a dev env, look at the custom broker acceptance tests.
---
> rds-broker: 1.34.0 -> 1.36.0

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/check-az-is-enabled-in-manifest.yml
- concourse/tasks/check-az-is-enabled-in-vpc.yml
- concourse/tasks/check-billing-comparison-with-cf.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/curl-az-healthcheck.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/send-nagging-email-alert.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
What
----
How to review
-------------
---
> Use bionic pg for billing

- concourse/pipelines/autodelete-cloudfoundry.yml
- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/deployment-kick-off.yml
- concourse/pipelines/destroy-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- concourse/pipelines/test-certificate-rotation.yml
- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/app-autoscaler-acceptance-tests-run.yml
- concourse/tasks/check-az-is-enabled-in-manifest.yml
- concourse/tasks/check-az-is-enabled-in-vpc.yml
- concourse/tasks/check-billing-comparison-with-cf.yml
- concourse/tasks/configure-grafana.yml
- concourse/tasks/create_admin.yml
- concourse/tasks/cronitor-monitor-ping-action.yml
- concourse/tasks/curl-az-healthcheck.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
- concourse/tasks/delete_admin.yml
- concourse/tasks/forget-access-keys.yml
- concourse/tasks/generate-git-keys.yml
- concourse/tasks/generate-test-config.yml
- concourse/tasks/get-cf-cli-config.yml
- concourse/tasks/remove-db.yml
- concourse/tasks/send-nagging-email-alert.yml
- concourse/tasks/smoke-tests-run.yml
- concourse/tasks/tag-repo.yml
- concourse/tasks/upload-test-artifacts.yml
- concourse/tasks/wait-for-api-availability-tests.yml
- concourse/tasks/wait-for-app-availability-tests.yml
- manifests/app-autoscaler/operations.d/001-release.yml
Description:
- Updates app-autoscaler to 8.0.0
- Updates submodule to point to latest commit so that app autoscaler tests can use this
What
----
How to review
-------------
---
> 182889631 Upgrade brokered autoscaler to V8

- concourse/tasks/aiven-broker-acceptance-tests-run.yml
- concourse/tasks/custom-acceptance-tests-run.yml
- concourse/tasks/custom-broker-acceptance-tests-run.yml
What
----
Somehow I missed 3 references to bare use of `ginkgo`.
Fix that
How to review
-------------
Ensure this runs correctly down a pipeline
---
> Replacing the last 3 uses of `ginkgo ...`

- scripts/credhub_shell.sh
What
----
Same change / reasoning as in https://github.com/alphagov/paas-bootstrap/pull/492
How to review
-------------
Code review / check if `make XXX credhub` still works
---
> use same ssh method as in paas-bootstrap

- config/service-brokers/csls-splunk/prod-lon-config.json
What
----
Requested in Zendesk ticket #5136029
How to review
-------------
Checks pass
---
> Grant ccs-conclave-data-migration access to the Splunk broker

- concourse/pipelines/destroy-cloudfoundry.yml
- scripts/unbind-and-delete-all-services.sh
What
----
This script can be used in isolation, or as part of the destroy-cloudfoundry pipeline to iterate over the orgs/spaces/apps/bindings in any targeted cloud foundry platform and will unbind any bound services before deleting them.
The PR also includes the necessary changes to the destroy-cf pipeline yaml
How to review
-------------
Run the script locally against a dev env using the test and or dryrun mode
Configure a dev pipeline to use this branch and trigger a destroy job in a dev env 
---
> added script to unbind and delete all services

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
App usage appears to have reduced to allow this quite comfortably. We'll get a notification if/when we need to scale back up.
How to review
-------------
No sensible way to test as this is env-specific. Just :eyes: I guess.
---
> Reduce diego-cells in prod, prod-lon to 144, 21 respectively

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Possibly I was over-eager in down-scaling prod-lon before xmas.
How to review
-------------
:eyes:  but no merge till after the freeze.
---
> prod-lon: bump diego cells to 147

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Pushing out new version of rds-broker.
This includes:
https://github.com/alphagov/paas-rds-broker/pull/165
https://github.com/alphagov/paas-rds-broker/pull/166
https://github.com/alphagov/paas-rds-broker/pull/167
https://github.com/alphagov/paas-rds-broker/pull/168
How to review
-------------
Ensure you are happy to push the new version.
---
> Bump rds-broker version

- manifests/cf-manifest/operations.d/330-uaa.yml
What
----
Releases https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/33
How to review
-------------
- check version and sha against the [CI build](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/uaa-customized-release/jobs/build-final-release/builds/5)
---
> Update custom UAA release

- terraform/staging.vpn.json
Signed-off-by: Andy Hunt <andy.hunt@digital.cabinet-office.gov.uk>
What
----
We need to test the vpn functionality in staging.
> [#183932518] Staging dummy vpn config

- terraform/vpn/security.tf
What
----
We were filtering by tag, but should be filtering by `default=true`.
How to review
-------------
Code review
---
> VPN terraform: find default ACL by filters

- terraform/prod.dms.json
What
----
Re-add production dms config after refactor
How to review
-------------
Check dms config.
---
> Re-add production dms config after refactor

- Gemfile.lock
- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/714-rds-broker-postgres10-high-iops-plans.yml
- manifests/cf-manifest/operations.d/715-rds-broker-postgres10-plans.yml
- manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
> Revert "[#183231038] Disable all Postgres 10 plans"

- terraform/prod-lon.vpn.json
What
----
There's a bug somewhere in the Terraform configuration that prevents things being cleanly modified. I need this change to be in production in 24h so I'm going the long way around: delete and re-add.
How to review
-------------
Did I remove it?
---
> [#184451435] Remove BJSS VPN configuration before re-adding

- terraform/prod-lon.vpn.json
What
----
Adds configuration to `prod-lon` for a new site-to-site VPN
How to review
-------------
- Check that they match the details on the email
- Am I missing a comma/bracket?
---
> Prepare the site-to-site VPN for BJSS' prod environment

- terraform/prod-lon.vpn.json
What
----
Fixes missing comma
How to review
-------------
Spot other missing commas
---
> Fix missing comma

- concourse/pipelines/create-cloudfoundry.yml
What
----
Added explicit time window for healthcheck-db maintenance window
How to review
-------------
Look at the code
---
> set healthcheck-db maintenance window to in hours

- .github/workflows/generate_buildpack_bump_pr.yml
- .github/workflows/test_on_pr.yml
- common-go/basic_logit_client/go.mod
- concourse/pipelines/create-cloudfoundry.yml
- go.mod
- platform-tests/example-apps/app-autoscaler-cpu-usage/manifest.yml
- platform-tests/example-apps/healthcheck-pinger/manifest.yml
- platform-tests/example-apps/healthcheck-ponger/manifest.yml
- platform-tests/example-apps/healthcheck/go.mod
- platform-tests/example-apps/healthcheck/manifest.yml
- platform-tests/example-apps/http-tester/go.mod
- platform-tests/example-apps/http-tester/manifest.yml
- platform-tests/example-apps/logging-pipeline/manifest.yml
- tools/metrics/go.mod
- tools/metrics/go.sum
- tools/metrics/manifest.yml
- tools/pipecleaner/go.mod
- tools/user_emails/go.mod
What
----
- Bump go to 1.20
How to review
-------------
- Ensure this branch runs down a pipeline
- Ensure all other PRs in the Pivotal story are merged **first**
- Revert changes to branch names
---
> [#184518969] Update to Go 1.20

- terraform/az-monitoring/module/main.tf
What
----
move healthcheck docker startup to systemd service in cloudinit
How to review
-------------
Look at the code
---
> move healthcheck docker startup to systemd service

- terraform/az-monitoring/module/main.tf
Reverts alphagov/paas-cf#3157
Breaks in prod.
> Revert "move healthcheck docker startup to systemd service"

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
https://www.pivotaltracker.com/story/show/184821981
WFM deployed on dev05
How to review
-------------
Deploy to a dev env.
---
> cflinuxfs3: 0.352.0 -> 0.361.0

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Memory demand has been lower for a couple of weeks now.
How to review
-------------
:eyes: 
---
> prod-lon cell_instances: 153 -> 141

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
This brings an openssl update that we probably want sooner rather than later.
How to review
-------------
Deploy to dev env? Look at https://deployer.dev05.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/3 ?
---
> cflinuxfs3: 0.362.0 -> 0.364.0

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
https://www.pivotaltracker.com/story/show/184821976
How to review
-------------
Deploy to dev env or look at dev05?
---
> jammy stemcells: 1.83 -> 1.102

- concourse/pipelines/fast-startup-and-shutdown-cf-env.yml
- concourse/scripts/fast-startup-and-shutdown-cf-env.sh
What
----
renamed the keyval resources to avoid clashes.
removed un-needed triggers.
refactored the main script for the rename.
How to review
-------------
look at the changes
configure a pipeline with this branch and run a startup ands shutdown
---
> renamed keyval resources and removed triggers

- manifests/cf-manifest/env-specific/prod-lon.yml
How to review
-------------
:eyes: 
---
> prod-lon: increase diego cells 138 -> 141

- Makefile
- scripts/enable_vpc_peer_db_access.rb
What
----
We introduced a ruby script and make action which allows the creation of a security group against a predefined peering connection. This security group will in turn be attached to a specified RDS database to allow connectivity through that peer.
How to review
-------------
Follow the steps on the story.
---
> [185302168] A script attaching peering security group for RDS

- manifests/prometheus/dashboards.d/dodgy-cell-detector.json
- manifests/prometheus/dashboards.d/logging-demand.json
What
----
A new dashboard showing a few metrics that could serve as a helpful telltale of a cell having some dodgy networking (the most common way a cell tends to be dodgy).
How to review
-------------
Deploy to a dev env. See it working.
---
> dashboards: add dodgy cell detector

- manifests/prometheus/dashboards.d/logging-demand.json
What
----
Make this cope with apps changing their names. Problem only revealed because of the new firehose exporter.
---
> logging demand dashboard: fix join condition

- manifests/prometheus/dashboards.d/dodgy-cell-detector.json
What
----
Some of the underlying metrics changed with the new firehose-exporter release, with some labels changing too.
---
> dodgy cell detector dashboard: fix for new firehose-exporter release

- terraform/prod-lon.vpc_peering.json
What
----
Add a VPC Peer connection to the new DLUHC AWS account
How to review
-------------
👀 
---
> Create a VPC Peer to DLUHC

- manifests/prometheus/operations.d/100-update-vm-types.yml
- manifests/prometheus/spec/operations/update_vm_types_spec.rb
What
----
I'm amazed it's managed on a nano so far, but heavy usage lately has pushed it into swap.
How to review
-------------
Look at this deploying happily on dev02?
---
> grafana: upgrade vm_type from nano -> small

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
What
----
app-autoscaler stemcell version needs to be in sync
How to review
-------------
Deploy and verify the use of the stemcell
---
> Delayed update of app-autoscaler stemcell

- terraform/prod-lon.vpc_peering.json
What
----
DLUHC have set up a VPC they'd like us to peer with. This sets up that peer so they can access their databases from the new VPC.
How to review
-------------
👀 
---
> Add the new DLUHC vpc peer information

- terraform/prod-lon.vpc_peering.json
What
----
Add a VPC peer to the UK Space agency
How to review
-------------
👀 
---
> add vpc peer for uk space agency

- scripts/unbind-and-delete-all-services.sh
What
----
enhanced tests, added special char handling
ensured script will not run against sleeping env
How to review
-------------
run the script against a dev env
use the test modes
---
> enhanced tests, added special char handling

- manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
https://www.pivotaltracker.com/story/show/185824641
How to review
-------------
Deploy to dev env, create a cdn service instance, look at its configuration in aws console?
---
> paas-cdn-broker: bump & add extra_request_headers for WAF's benefit

- concourse/pipelines/create-cloudfoundry.yml
- concourse/pipelines/monitor-remote.yml
- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/010-set-cflinuxfs3-default-stack-UPSTREAM.yml
- manifests/cf-manifest/operations.d/010-set-cflinuxfs3-default-stack.yml
- manifests/cf-manifest/operations.d/011-use-cflinuxfs3-UPSTREAM.yml
- manifests/cf-manifest/operations.d/011-use-cflinuxfs3.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/320-cc-release.yml
- manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
https://www.pivotaltracker.com/story/show/185698046
Copied cflinuxfs3 opsfiles from last version before bumping, bumped stemcells to latest available.
Have performed all the UAA tests except the "test with a non-work google account" - I don't have a non-work google account. Volunteer welcomed.
Have tested the `test-certificate-rotation` pipeline.
How to review
-------------
Deploy to a dev env and :crossed_fingers: 
---
> cf-deployment: 30.5.0 -> 32.1.0

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
Seems like for the last couple of weeks our max peaks have been at a reduced ~135
How to review
-------------
:eyes: 
---
> prod-lon: reduce cells 141 -> 135

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
Upgrade cflinuxfs4 to 1.32.0
How to review
-------------
Tested [in dev05](https://deployer.dev05.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/55#L64f6ffd2:88)
---
> Upgrade cflinuxfs4 to 1.32.0

- manifests/cf-manifest/isolation-segments/prod/govuk-notify-production.yml
- manifests/cf-manifest/isolation-segments/prod/govuk-notify-staging.yml
What
----
Update notify's isolation segments cell counts for staging and production
Why
----
https://govuk.zendesk.com/agent/tickets/5486546
How to review
-------------
Look at the changes
---
> Update notify's isolation segments cell counts for staging and production

- config/logit/filters.d/30_various_timestamps.conf
- config/logit/filters.d/99_clean_alb_access.conf
- config/logit/output/generated_logit_filters.conf
What
----
As part of https://www.pivotaltracker.com/story/show/185739015, this is an improvement on how we currently have things, though not yet perfect. Working with logit to get things better.
How to review
-------------
:eyes: 
---
> logit filters: improve handling of alb_access logs

- terraform/globals.tf
Remove defunct VPN IP addresses
> Remove old VPN ips

- terraform/prod-lon.vpc_peering.json
Remove the dluhc vpc peer as they have finished migrating
👀 
> Remove dluhc vpc peer

- manifests/cf-manifest/operations.d/710-rds-broker.yml
* Includes new version of ginkgo testing lib
* Includes golang updates from previous rds broker merges
What
----
Updated RDS release with the production build artefact
How to review
-------------
- Run it against a dev env
- See all tests passing
- Try using the RDS broker with success
---
> New RDS broker release

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
Upgrade cflinuxfs4 for security updates
How to review
-------------
Deploy to a dev env
---
> Upgrade cflinuxfs4 to latest

- terraform/prod.dms.json
What
----
Add notify production dms instance and task
How to review
-------------
Check the changes.
---
> Add notify production dms

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/runtime-config/operations.d/510-add-prometheus-blackbox-exporter.yml
What
----
bumped prometheus bosh release 29.2.0 -> 29.5.0
How to review
-------------
Look at the changes
Deploy to a dev env - or look at my deployment to dev04
---
> bumped prometheus bosh release 29.2.0 -> 29.5.0

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
Stemcell update to the latest version 1.309.
How to review
-------------
Deploy on a test environment and see paas-cf pipelines go green.
---
> Stemcell update to 1.309

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
Cflinuxfs4-compat upgrade
How to review
-------------
Test it on a dev env
---
> cflinuxfs4-compat to v1.58.0

- manifests/cf-manifest/operations.d/200-awslogs.yml
What
----
bumped-awslogs-bosh-release-version-for-logrotate-fix
How to review
-------------
look at the changes
---
> bumped-awslogs-bosh-release-version-for-logrotate-fix

- manifests/cf-manifest/operations.d/710-rds-broker.yml
- manifests/cf-manifest/operations.d/720-cdn-broker.yml
- manifests/cf-manifest/operations.d/730-elasticache-broker.yml
- manifests/cf-manifest/operations.d/760-sqs-broker.yml
- platform-tests/broker-acceptance/cdn_broker_test.go
- platform-tests/broker-acceptance/init_test.go
- terraform/cloudfoundry/broker_alb.tf
- terraform/cloudfoundry/cdn_broker.tf
- terraform/cloudfoundry/elasticache_broker.tf
- terraform/cloudfoundry/rds_broker.tf
- terraform/cloudfoundry/sqs_broker.tf
What
----
We recently enabled TLS connectivity for our broker APIs. This PR will switch on this feature.
How to review
-------------
- Cross check the versions and changes. 
- Test this branch on a dev environment. 
- See pipelines go green.
---
> Enable TLS for most brokers

- manifests/prometheus/alerts.d/billing-eventcollector-activity.yml
- manifests/prometheus/alerts.d/billing-eventstore-jobs.yml
What
----
added billing alerts
How to review
-------------
look at the changes
deploy in a dev env
---
> added billing alerts

- scripts/add_permissions_boundary_to_existing_s3_broker_users.rb
What
----
Amended the add_permissions_boundary_to_existing_s3_broker_users script to handle batches of users correctly.
How to review
-------------
1 - Review the code change.
2 - Try it out in a dev with access set to ro and dry-run flag set. 
---
> Amend the add_permissions_boundary_to_existing_s3_broker_users.rb script

- manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
Just a simple removal of a duplicated spec
test with 👀 
> remove a duplicated shared spec

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Updated rds-broker version which uses latest metric collector.
How to review
-------------
1 - Check the code.
2 - Run into a dev env.
---
> Add rds-broker with updated metric-collector

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
The stemcell has been upgraded to v1.340.
How to review
-------------
1 - Check the code to ensure that the stemcell has been set wherever it needs to be specified.
2 - Run into a dev env.
---
> Upgrade stemcell

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Reduce cell count in ireland to 15->6
Reduce router count in ireland 33->12
Reduce cell count in London 72->48
How to review
-------------
Look at the changes
---
> Reduce cell and router counts to save money

- manifests/cf-manifest/operations.d/030-bosh-dns.yml
What
----
Existing bosh-dns-release is too old and causing troubles. Needed updating.
How to review
-------------
Deploy in a dev env - but we already did that.
---
> DNS healthcheck bug fix

- terraform/prod-lon.vpc_peering.json
What
----
Adds two DIT VPCs for peering with their apps, as requested via ZenDesk
---
> Add both new DIT peer VPCs

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
The stemcell has been upgraded to v1.445
How to review
-------------
1 - Check the code to ensure that the stemcell has been set wherever it needs to be specified.
2 - Run into a dev env.
---
> Upgraded stemcell to latest version 1.445

- terraform/pingdom/pingdom.tf
What
----
Some requests are taking ~5 seconds and alerting, this is a hotfix while we investigate the root cause
---
> Increase pingdom health check timeouts

- config/buildpacks.rolling.yml
- config/buildpacks.yml
What
----
Buildpacks versions upgrade
How to review
-------------
Deploy the changes on Dev environment and see if new versions has not broken anything. 
---
> 187631473 - buildpack versions upgrade

- manifests/app-autoscaler/diffs/patch_dynamic_policy_test.patch
- manifests/app-autoscaler/operations.d/001-release.yml
This reverts commit fe47bd71e6191ce5b952fb9ddf85e5cf41e49890.
What
----
How to review
-------------
---
> Revert "app-autoscaler upgrade to latest release 13.2.0"

- terraform/prod-lon.vpc_peering.json
What
----
Add VPCs for the new DIT directory service, as requested via support
---
> Add VPCs for DIT directory

- manifests/cf-manifest/operations.d/500-prometheus.yml
- manifests/runtime-config/operations.d/510-add-prometheus-blackbox-exporter.yml
What
----
How to review
-------------
---
> Revert prometheus bosh

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Save money. Add buffer
How to review
-------------
Deploy and monitor
---
> Altered Ireland api instances. Adding more cell capacity london

- manifests/cf-manifest/env-specific/prod-lon.yml
- manifests/cf-manifest/env-specific/prod.yml
What
----
Save money. We need to monitor latency after this
How to review
-------------
---
> Reduced the instances

- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/spec/manifest/env_spec.rb
What
----
How to review
-------------
---
> Updated the cell instances for Ireland

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced lon router instances

- manifests/cf-manifest/env-specific/prod.yml
What
----
How to review
-------------
---
> reduced instances in Ireland

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced instances

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
> Update cflinuxfs4-compat to 1.182.0

- manifests/cf-manifest/env-specific/prod.yml
- manifests/cf-manifest/spec/manifest/cc_spec.rb
What
----
How to review
-------------
---
> Updated cc and scheduler instances

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced instances for Lon, cc-worker and scheduler

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
Version number change
How to review
-------------
---
> Stemcell version bump to 1.631

- manifests/cf-manifest/operations.d/750-s3-broker.yml
> Use new release of S3 broker

- manifests/cf-manifest/operations.d/710-rds-broker.yml
See https://github.com/alphagov/paas-rds-broker/pull/199
---
> Use v1.60.0 release of rds-broker

- scripts/org-app-details.sh
What
----
How to review
-------------
---
> Space app details

- terraform/prod-lon.vpc_peering.json
What
----
How to review
-------------
---
> Removed datasets from vpc peering config

- terraform/prod-lon.vpc_peering.json
What
----
How to review
-------------
---
> Removed directory-uat from vpc config

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Downsizing the cell instances

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced the api instances

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced router instances

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced doppler instances

- terraform/cloudfoundry/cdn_broker.tf
What
----
How to review
-------------
---
> Upgraded cdn postgres to 13

- terraform/cloudfoundry/cdn_broker.tf
What
----
How to review
-------------
---
> Added postgres12 param group back in

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced cc worker & scheduler instances

- terraform/cloudfoundry/cdn_broker.tf
What
----
How to review
-------------
---
> Removed pg12 param group

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced log cache instances

- manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Update rds-broker release to 1.61
---
> Update rds-broker release to 1.61

- terraform/prod-lon.vpc_peering.json
What
----
How to review
-------------
---
> Removed dit directory from terraform

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced cell instances

- manifests/cf-manifest/env-specific/prod.yml
What
----
How to review
-------------
---
> Reduced scheduler ire instances

- concourse/pipelines/create-cloudfoundry.yml
- manifests/cf-manifest/operations.d/330-uaa.yml
This is still used by auditor
---
> Add billing secret back

- config/logit/filters.d/21_paas_billing_filters.conf
- scripts/generate_logit_filters.sh
What
----
Removed logit filters, config files and script for billing app bindings
How to review
-------------
Code review and check logit
---
> Removed logit filters, config files and script for billing app bindings

- manifests/cf-manifest/env-specific/prod-lon.yml
What
----
How to review
-------------
---
> Reduced Lon cell instances

- scripts/decommission_organisation.rb
What
----
How to review
-------------
---
> Updated the decomm script

- config/buildpacks.rolling.yml
> Add go buildpack for cflinuxfs4 back to rolling releases

- manifests/app-autoscaler/operations.d/020-bosh-set-stemcells.yml
- manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
How to review
-------------
---
> Bumped the stemcell version

- manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
See https://bosh.cloudfoundry.org/releases/github.com/cloudfoundry/cflinuxfs4-compat-release?all=1
---
> Update cflinuxfs4-compat to v1.267.0

- Makefile
- scripts/unbind-and-delete-all-services.sh
What
----
How to review
-------------
---
> Removing destroy protections for prod-lon
