scripts/create-user.sh
When re-inviting a user (eg because they've forgotten their password),
we don't need to specify an org because they'll already be assigned to
the orgs/spaces then need access to. In this case it's desirable to not
touch the orgs/spaces.
This therefore allows this script to run without an org specified when
re-inviting a user.
Test that the script works against a dev environment (the `--no-email` flag is useful here) for the following:
* Creating a user assigned to an org
* Re-inviting a user without an org specified
Not me.
=> [SUPPORT] Allow re-inviting user without assigning to org/space

terraform/datadog/cloud_controller.tf
This reverts commit 00cfcd466b94cf066616a9e19f5bd0b679b79ace.
I believe that this was fixed by 7bf2b74f58b69f203e32f9c606b2b749754f64ef so
we should display these on the dashboard again. I noticed this because I was
called out by PagerDuty in-hours and the alert wasn't on the dashboard.
Code review.
Anyone.
=> [SUPPORT] Revert "Remove *_monitors tag from CC monitors"

terraform/datadog/cloud_controller.tf
Somethings appears to have changed since the CF v257 upgrade and the
acceptance tests are now alerting me via PagerDuty on every successful run.
I've tracked this down to a log entry and found the corresponding API
requests in the test artefacts:
Stager error: Unsupported buildpack type: 'CATS-5-BPK-c816e215-00d4-4b56-7'
However I'm not able to find a fix yet and the alerts are very distracting.
I also think that this threshold is too low, so it seems safe to raise it.
Code review.
Anyone.
=> [#145517679] Increase thresholds for cc.log_count.error alert

terraform/datadog/cloud_controller.tf
So that you can see what log entries caused this metric to increase. I
thought about putting the queries in the Team Manual and linking to that,
but it seems quite heavyweight when we have no other information to describe
at the moment.
1. Code review
1. Use the queries in CI to see log errors described in `#918`
Anyone.
=> [#145517679] Add logsearch query for cc.log_count.error

terraform/datadog/cve.tf
As suggested by DataDog support in this email thread:
- https://groups.google.com/a/digital.cabinet-office.gov.uk/forum/#!msg/the-multi-cloud-paas-team/g5OfF62lGbs/4HN6zSUlAgAJ
I'm not very confident about their explanation. However we should do what
they suggest. If the monitor doesn't notify us about the next CVE then we
should revisit the other options described in the thread, including the
IFTTT notification that Alex has setup.
Code review.
Anyone.
=> [#141398611] Increase window for CVE monitor to 10m

terraform/dev.tfvars, terraform/globals.tf, terraform/prod.tfvars
Story: [Open up staging and CI so they match prod](https://www.pivotaltracker.com/story/show/144940081)
API is now open by default as in prod. We only override the value in DEV as we may want to restrict access to potentially insecure environments running experimental features.
* Deploy with this branch
* Check there is no change in cf-terraform job (DEV remains closed)
* Delete the `api_access_cidrs` variable in `dev.tfvars` to simulate CI/staging/prod in a TEMP commit
* Push, run the pipeline
* Access `https://api.<env>.dev.cloudpipeline.digital/` from outside (ex: your phone), It should be available
* Remove the TEMP commit and push
Not me
=> [#144940081] Open API in CI and staging

terraform/cloudfoundry/dns-records.tf
This PR adds in a CNAME to create status.cloud.gov.uk for the statuspage
to be accessed via. This follows the same pattern as notify.
Code review.
Not me.
=> Add CNAME record for statuspage.io

concourse/scripts/fly_sync_and_login.sh
Now that we have signed certs for the deployer concourse it's no longer
necessary to skip SSL validation when accessing it.
Run `make dev pipelines` from this branch and verify that it works.  Run the pipeline from this branch and verify that the self-update-pipelines step works.
Optionally, if you have a concourse that hasn't been updated to use a real cert, verify that this command fails.
🚨  Note: This should not be merged until dev environments have been updated to use valid certs.
Not me.
=> [#141423205] Don't skip SSL validation for concourse.

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
It's a recommended version of the UAA release, that will protect us
against the [CVE-2016-4991](https://www.cloudfoundry.org/cve-2017-4991/).
- Check if the correct release is tagged
- I've managed to run the successful deployment on `dev` - You don't _have_ to run it yourself
=> [#145666887] Bump the UAA release version to v30.2

terraform/datadog/concourse.tf
The concourse btrfs monitor levels appear to be too low for production as we're getting spurious warnings. This raises the levels and also ensures that we only track btrfs processes on the concourse host rather than the wider cluster.
* Code review.
* Check that the levels are higher than what we've seen in production: https://app.datadoghq.com/monitors#2083141?group=*&from_ts=1495098656256&to_ts=1495102256543
Anybody, probably @paroxp.
=> Raise concourse btrfs monitor levels

manifests/cf-manifest/env-specific/cf-prod.yml
We're getting alerts on running low on the disk space in production. For
the time being, we'd like to increase the disk space size, as we don't
have any archiving in place.
This change will add additional 256G to the current disk, which
currently is 512G.
- Sanity review over the change
- Agreement upon additional space
Preferably @alext
=> [SUPPORT] Increase the ES disk size

manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/manifest/800-logsearch.yml
We'd like to parse all fields from all access logs that appear in logsearch.
- Code review
- Check and memorise current state of `nginx` logs
- Interact with UAA for instance
- Re-check the logs and note the differences in extracted fields
Neither @saliceti nor myself.
=> [#144690295] Add new log parsers

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
It's a recommended version of the UAA release, that will protect us
against the [CVE-2016-4992](https://www.cloudfoundry.org/cve-2017-4992/).
- Check if the correct release is tagged
- I've managed to run the successful deployment on `dev` - You don't _have_ to run it yourself
=> [#145835803] Bump the UAA release version to v30.3

manifests/cf-manifest/cloud-config/020-cf-vm-types.yml
As we grow, we're slowly running out of disk space. We've reached a
little over 75% on two of our cells in production environment, according
to DataDog.
We'd like to double the disk space, for the time to stay safe and
alerted when other warnings hit production.
We have decided, to increase the disk space across all environments.
- Code sanity check
- I've managed to run the successful deployment on `dev` - You don't _have_ to run it yourself
=> [#133104393] Increase the cell disk size

concourse/pipelines/create-cloudfoundry.yml, concourse/resources/cf-secrets-keep.yml, config/service-brokers/compose/catalog.json, manifests/cf-manifest/scripts/generate-cf-secrets.rb, platform-tests/src/acceptance/compose_broker_test.go, platform-tests/src/acceptance/init_test.go
https://www.pivotaltracker.com/story/show/143868179
We want to deploy the Compose service broker as an application on the platform.
Preferably review in conjunction with https://github.com/alphagov/paas-compose-broker/pull/1
Deploy from this branch and make sure all of the tests passed. The tests haven't been changed, but the ordering of tasks in the CF deploy has.
The broker is a 'walking skeleton', so doesn't need to actually provision anything. Its 'correct' behaviour is to error when actually performing all operations except the _Services_ endpoint for returning the catalog.
Example of checking it serves the catalog:
```
curl -k -u compose-broker:$PASSWORD_FROM_CF_SECRETS https://compose-broker.${DEPLOY_ENV}.dev.cloudpipelineapps.digital/v2/catalog
```
Review and merge …
=> [#143868179] Deploy walking skeleton of Compose service broker

platform-tests/src/availability/helpers/concourse.go
The job [availability-tests/470](https://deployer.cloud.service.gov.uk/teams/main/pipelines/create-cloudfoundry/jobs/availability-tests/builds/470) has failed. We think it actually
shouldn't matter to us that much, if there is a one of connection issue
with the concourse API. We don't mean to get rid of the error
completely, therefore we're still printing it, allowing the script to
continue it's loop and hoping that the issue has resolved it self in the
mean time.
- Code review
- Run the deployment from this branch and expect the
`availability-tests` to pass
=> [SUPPORT] Print the error but do not stop the tests

concourse/pipelines/create-cloudfoundry.yml
Currently, we're not getting any error message which could confuse
someone who hasn't previously encounter this particular error. With this
change, we're reporting on the status of VMs, while the `bosh-tests`
run.
- Code review
- Run the pipeline and allow `bosh-tests` to pass
- Optionally, stop (change state) one of the VMs and re-run `bosh-tests` expecting them to fail
Neither @dcarley nor @paroxp
=> [SUPPORT] Improve the failure in bosh-tests

concourse/pipelines/create-cloudfoundry.yml
We do not want a tenant to be able to push an app using any of these
names, as it could be misleading to others[1].
There was a suggestion these hostnames should redirect to the product
page, but it was agreed to not add that complexity at this stage.
However, in case we do they have been placed in the same org as the
product page (govuk-paas), which seems to have been created manually
in the past.
The redundant `echo | ` has been removed because it does not appear
to do anything with our current usage of the CF CLI.
[1] https://www.pivotaltracker.com/story/show/145588187
Make sure a tenant in a different org can't push an app called api, www, or status.
Anyone but me
=> [#145588187] Reserve common hostnames on the apps domain

platform-tests/example-apps/healthcheck/Godeps/Godeps.json
Upgrade to Go 1.8 because that is the latest version supported by
the Go buildpack we are currently using[1]. The buildpack is Godep-aware
and will compile based on this version.
Files changed using `godep update -goversion`, which changes the files
based on what you have installed locally. Godep v79 is the version supported
by the buildpack[1].
The app is pushed using the blue-green-deployment plugin, which creates
a new app, therefore eliminating the need to restage when this is deployed.
[1] https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.7.19
The staging output is often supressed, so I am not sure how you prove it has compiled it using Go 1.8. I didn't see the staging output or the [`staging_task_id`](https://apidocs.cloudfoundry.org/258/apps/get_app_summary.html) …
=> [#145751037] Upgrade Go version used by the healthcheck app

manifests/cf-manifest/manifest/010-cf-jobs.yml
These logs were passing the UAA ELB IP address as the `nginx.clientip`
field instead of the client IP address. This was due to Nginx not
taking into account the use of X-Forwarded-For headers.
We set `set_real_ip_from` to only trust sources within our own VPC.
Configuration based on the example from Nginx's documentation[1].
[1] http://nginx.org/en/docs/http/ngx_http_realip_module.html
Ultimately, we want to be sure that any Nginx access logs have a `nginx.clientip` field which matches the client's IP, not the ELB's. The following example is how you could verify by setting up a user:
Against an existing environment login to the CF CLI and create a user:
```
./scripts/create-user.sh -e 'your.name+1@example.com' -o testers
```
Then search in Kibana for "invite_users", you should find an …
=> [#146084537] Fix uaa_nginx_access logs

platform-tests/example-apps/http_tester/manifest.yml, platform-tests/src/acceptance/http_edge_cases_test.go, platform-tests/src/acceptance/http_forwarded_for_test.go, platform-tests/src/acceptance/http_forwarded_proto_test.go
As we run tests in parallel we deploy multiple instances of http_tester
app at once. This may have an impact on the platform so we decided to
reduce available instance memory to 64m
Run the pipeline and check if tests pass. 
Not @combor
=> [#145024711 ] Reduce http_tester instance memory

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/060-cdn-broker.yml, terraform/cloudfoundry/cdn_broker.tf, terraform/datadog/cdn_broker.tf
This installs the new CDN broker healthchecks added in https://github.com/alphagov/paas-cdn-broker/pull/3 and configures a new datadog check for the master "check all the things" endpoint.
Note from @dcarley: I have tested this, but also contributed to it. I think code review only would be suitable especially because of the amount of time it takes to enable DataDog on an environment. Please talk to me if you're unsure.
* Deploy from this branch (with datadog enabled)
* [Instructions for paas-bootstrap](https://github.com/alphagov/paas-bootstrap/blob/master/doc/datadog.md)
* [Instructions for paas-cf](https://github.com/alphagov/paas-cf/blob/master/doc/datadog.md)
* Check that you have a green datadog healthcheck for the cdn-broker
* Check that the monitor goes red when one of the …
=> [#145037767] Monitor CDN broker

platform-tests/src/acceptance/http_edge_cases_test.go
As HTTP edge cases tests are misbehaving we have decided to temporarily
disable them to investigate the root cause.
This PR should be reverted once we know how to fix underlying
problem.
Sanity check.
Not @acombor
=> [#145024711] Skip HTTP edge cases

concourse/tasks/custom-acceptance-tests-run.yml
The test config[1] sets the artifact directory to `/tmp/artifacts`, which
didn't match where this was putting them. They therefore weren't being
found up by the upload task.
This change was missed in #895 when we switched away from using the
simulated errand environment.
[1] manifests/cf-manifest/manifest/900-cf-tests.yml line 23
Run the pipeline and verify that the artifacts from the custom-acceptance-tests get uploaded. This can be verified by looking at the output from the `upload-test-artifacts` step in this job, and fetching the artifacts as described there.
Not me.
=> [Support] Fix custom-acceptance-tests artifacts capture.

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
update  the UAA release, to protect us
against the CVE-2017-4994[1].
[1] https://www.cloudfoundry.org/cve-2017-4994/
Code review. I've applied this in a dev env and the tests pass.
Anyone but me
=> #[146759947]  Bump the UAA release version to v30.4

manifests/cf-manifest/cloud-config/020-cf-vm-types.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml
As part of the investigation into the 504 errors from the API we tested
different approaches, including scaling up the number of API instances
and increasing the instance size.
Increasing the instance size proved to be the most reliable method of
fixing this issue. This has not seen any test failures using the stress testing branch investigate_504_in_tests-146603775 
Deploy from this branch and all tests will pass
Additionally the following branch can be used to test as this contains this fix and a set of modified tests designed to place additional stress on the API instances. The branch is investigate_504_in_tests-146603775 
Not me or @bleach
=> Increase API instances to M4.Large. [146603775]

platform-tests/src/acceptance/http_edge_cases_test.go
The underlying cause of these test failures has been found and is fixed in #946. As a result
these tests can be reenabled.
1. Ensure that #946 has been merged
2. deploy from this branch, and wait for test results
Not me
=> Revert "Skip HTTP edge cases"

Makefile
We have changed the bucket name a while ago. This script currently
errors out, for a good reason. We'd like to correct that, before we
rotate the token properly.
- Attempt to `make dev upload-tracker-token` from the `master` branch - experience an error
- Checkout this branch and try the above command again - experience **no error**
- After merging, it's advised to run `make prod upload-tracker-token` so we can comeback to working rubbernecker next working day
=> [SUPPORT] Fix the script to upload Tracker Token

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/spec/manifest/release_versions_spec.rb
This was missed in a929e3e8. Existing BOSH directors will not have used the
new release because it was already considered present. New BOSH directors
fail with the following:
Checking whether release cflinuxfs2/1.117.0 already exists...NO
Using remote release 'https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-release?v=1.126.0'
Director task 29
Started downloading remote release > Downloading remote release. Done (00:00:05)
Started verifying remote release > Verifying remote release. Done (00:00:01)
Started extracting release > Extracting release. Done (00:00:01)
Started verifying manifest > Verifying manifest. Done (00:00:00)
Started resolving package dependencies > Resolving package dependencies. Done (00:00:00)
Started processing 1 existing package > Processing 1 existing package. …
=> [support] Update cflinuxfs2 version to match release URL

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
It's a recommended version of the UAA release that includes the fix for
CVE-2017-8032[1]
[1] https://www.cloudfoundry.org/cve-2017-8032/
Code review. I've deployed this in a dev env, and the tests all pass.
=> [#147088283] Bump the UAA release version to v30.5

manifests/cf-manifest/manifest/050-rds-broker.yml, manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
So that instances get created with an up-to-date version immediately
instead of being created wityh an older version, and then being upgraded
at the next maintenance window.
Run the pipeline from this branch and verify that all the tests pass. You can verify in the AWS console that the created RDS instances are using the most recent minor version.
Not me.
=> [#147010925] Specify only major DB version in RDS-broker catalog.

terraform/cloudfoundry/security-groups.tf
Change the description attributes of Cloud Foundry aws_security_group resources so that they accurately describe the purposes of the security groups.
The descriptions are out-of-date and misleading. For example, they suggest that traffic only comes from the office, and refer to the whitelist which has since been removed.
* Code review - check the new descriptions make sense.
* Run the pipeline against an existing deployment. Verify that it updates successfully, and that the availability tests pass.
Not me.
=> [#145583253] Update descriptions of CF Security Groups

scripts/create-user.sh
This required all email addresses to end in a component that was 2-4
characters long. We need to use emails from domains that don't fit this
pattern (the specific example in this case was an address like
user@example.email).
With the introduction of generic top-level domains, there are now many
domains that don't fit this pattern[1], so this commit therefore removes
the upper limit on this component.
[1]https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#ICANN-era_generic_top-level_domains
Code-review is probably enough. You could test with a long email address against a dev environment.
Not me.
=> [Support] Fix create-user.sh email validation

terraform/cloudfoundry/cdn_broker.tf, terraform/cloudfoundry/cf_rds.tf
So that we automatically get upgraded to newer point releases when there
are security issues etc.
This includes updating the engine_version to only specify the major
version so that terraform won't attempt to downgrade instances that have
been upgraded. It also means that newly created instances will get the
latest point release.
* Run the bootstrap pipeline.
* Observe that the CF and CDN RDS instance get auto_minot_version_upgrade set to true.
* Observe that terraform doesn't attempt to change the engine versions.
Not me.
=> [#139001857] Allow platform RDS instances to auto_minor_version_upgrade

Makefile, README.md, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/lib/compose.sh, concourse/scripts/pipelines-cloudfoundry.sh, config/service-brokers/compose/catalog.json, platform-tests/src/acceptance/compose_broker_test.go, platform-tests/src/acceptance/init_test.go, scripts/upload-compose-secrets.sh, terraform/cloudfoundry/security-groups.tf
This PR deploys new version of compose broker with single free plan that can provision a mongodb instance with 1 unit of resources. 
- code review
- run `make dev upload-compose-secrets`
- Deploy from this pipeline and check if all tests pass. 
- Try to enable the broker services with `cf enable-service-access mongodb` and provision a database
- run `make $env upload-compose-secrets` to apply to all other environments.
- ⚠️ make sure you merge https://github.com/alphagov/paas-compose-broker/pull/2 first
- ⚠️ remove https://github.com/alphagov/paas-cf/pull/945/commits/522a5b35637da87a1b69ebf47eb975d1c8ccce42
- Not @paroxp or @henrytk or @combor
=> [#143876117] Compose broker version bump

manifests/cf-manifest/env-specific/cf-prod.yml
Our current memory allocation doesn't fit within the limit described in
ADR017[1]. Wu currently have c. 450Gig total memory. To comply with the
ADR, we need 567Gig. Adding 6 more cells at c. 30Gig each will being us
within the limts again.
[1]https://government-paas-team-manual.readthedocs.io/en/latest/architecture_decision_records/ADR017-cell-capacity-assignment/
* Code review.
* Verify the current limit in prod allows for 21 r4.xlarge VMs.
Not me.
=> Add 6 more cells in prod.

config/admin_users.yml
Create a CF admin account for Lee Porte because he has production access now.
Code review. Check that the format is valid and that his email address is correct.
Anyone.
=> [#147443439] Admin CF account for Lee Porte

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/pipelines-cloudfoundry.sh
New rubbernecker feature, involves the listing of people on support. In
order to achieve that, it needs to communicate with PagerDuty.
We're providing a separate PagerDuty API token to authorise the
connection with their API.
- Deploy from this branch with `DEPLOY_RUBBERNECKER=true`
- If the alphagov/paas-rubbernecker#21 is not merged yet, `cf push` the app manually
- Visit it on your dev environment
- Experience no issues
- alphagov/paas-rubbernecker#21
- credentials
- Run `make prod upload-pagerduty-token`
=> Add pagerduty support to rubbernecker

Makefile, concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/deployment-kick-off.yml, concourse/scripts/pipelines-cloudfoundry.sh, concourse/scripts/trigger-deploy.sh, concourse/tasks/splay.yml
We'd like to kick our environments every morning if possible. To achieve
that, we can create a trigger based on the `time-resource` provided by
concourse, which has pretty neat configuration.
The intention is to speed up our development process.
- Code review
- Either:
- Deploy from branch right before leaving work and expect it to run the next morning
- Branch off from here and amend the `start` value; `git push`; `make dev pipelines` from a new branch
- alphagov/paas-bootstrap#71
=> [#147124125] Add deployment kick-off functionality

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
For multiple USNs:
- https://www.cloudfoundry.org/usn-3318-1/
- https://www.cloudfoundry.org/usn-3323-1/
- https://www.cloudfoundry.org/usn-3302-1/
- https://www.cloudfoundry.org/usn-3309-1/
- https://www.cloudfoundry.org/usn-3311-1/
- https://www.cloudfoundry.org/usn-3312-2/
They all specify different versions, but USN-3323-1 specifies 1.133.0, which
is the latest available.
The release notes for cflinuxfs2 1.126.0->1.133.0 are quite hard to read
because you have to click through multiple links, but all of the changes
appear to be related to USNs/CVEs:
- https://github.com/cloudfoundry/cflinuxfs2-release/releases
I have tested this in dev. All of the tests (`availability-tests`, `smoke-tests`, `acceptance-tests`, and `custom-acceptance-tests`) passed.
So I think code review only is …
=> [#147741737] Upgrade cflinuxfs2 for CVEs

concourse/pipelines/create-cloudfoundry.yml
Bump version of compose broker to the one that supports enterprise clusters.
- code review https://github.com/alphagov/paas-compose-broker/pull/4
- Deploy, create a DB, and check if it's using our enterprise cluster ( you need to enable it manually https://docs.cloudfoundry.org/services/access-control.html#enable-access )
- merge https://github.com/alphagov/paas-compose-broker/pull/4
- tag master with `v0.2.0` label
- remove https://github.com/alphagov/paas-cf/commit/14b2a2c408f7016e4c7ae25a8626688632bcf7d4
Not @timmow or @combor
=> [#147123149] Introduce compose enterprise clusters

manifests/cf-manifest/cloud-config/021-cf-vm-extensions.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/shared/spec/fixtures/terraform/terraform-outputs.yml, terraform/cloudfoundry/dns-records.tf, terraform/cloudfoundry/elbs.tf, terraform/cloudfoundry/outputs.tf
This endpoint has been deprecated and is no longer used. It will be [removed
from CC's info endpoint][0] in CF v260.
We tried to do this before in 7c71f5f during the upgrade from CF v240 to
v245 but reverted it in a9530cf because we saw this error instead of
getting staging logs during a `cf push`, but the deploy continued:
Warning: error tailing logs
Error dialing loggregator server: dial tcp: lookup loggregator.hector.dev.cloudpipeline.digital on 127.0.1.1:53: no such host.
Please ask your Cloud Foundry Operator to check the platform configuration (loggregator endpoint is wss://loggregator.hector.dev.cloudpipeline.digital:443).
This [error comes from][1] the old loggregator_consumer library when connecting
to the loggregator endpoint. We can tell from the error message and the
codebase …
=> [#146446991] 	Remove unused loggregator ELB

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
We've applied some logrotate fixes to the boshrelease, which will no
longer prevent logrotate from rotating the logs on ipsec.
- Code review
- Run the pipeline from this branch - inb4 Dan: I have run that myself :)
- Experience no issues
- For bonus points: Check if logrotate does warn about permission
=> [#148059799] Upgrade ipsec boshrelease

manifests/cf-manifest/manifest/050-rds-broker.yml
This commit enables the release of the RDS Broker with support for event triggers in Postgres. It contains a migration path for users of Postgres databases created under the previous versions of the broker. 
1. Create a Postgres instance using the previous RDS Broker (Master branch)
1. Bind the new database to an app
1. Use a [`cf ssh` tunnel](https://docs.cloud.service.gov.uk/#creating-tcp-tunnels-with-ssh) and `psql` to connect to the database and create a test table and insert some test data e.g. `CREATE TABLE test1 (name TEXT);` and `INSERT INTO test1 VALUES('Testing');`
1. Deploy from this branch
1. unbind and rebind the database
1. Verify using `psql` that the _manager role is available by using the `\du` command
1. Verify using `psql` that the test table is now under the _manager …
=> [#141113589] Postgres event triggers

scripts/create-user.sh
This commit adds signposting to https://status.cloud.service.gov.uk to
the new user email for status and incident updates.
Additionally the sign off has been updated
Code review
Not me
=> [145703963] Add statuspage into new user email

concourse/pipelines/create-cloudfoundry.yml
This bumps the broker to pull in the changes from https://github.com/alphagov/paas-compose-broker/pull/5
* Run the pipeline from this branch.
* Verify you can create and destroy a mongo service instance (you'll need to enable access first - `cf enable-service-access mongodb -o myorg`)
* Ensure https://github.com/alphagov/paas-compose-broker/pull/5 has been merged, and tagged as `v0.3.0`.
* Remove the TMP commit from this branch.
Not me.
=> [#147992413] Fix returned database name for mongodb

concourse/pipelines/create-cloudfoundry.yml
This will bump the version of Compose broker to support passing CA certs for TLS verification.
- merge https://github.com/alphagov/paas-compose-broker/pull/6
- put tag on paas-compose-broker master
- remove https://github.com/alphagov/paas-cf/pull/977/commits/0bd499cc06f8826148e0587c83ae1bbb0105c90c
- merge this
Not @chrisfarms or @combor
=> [#147418883] Mongo TLS verify

manifests/cf-manifest/manifest/050-rds-broker.yml, platform-tests/src/acceptance/rds_broker_test.go
Use a new version of the RDS broker than forces TLS connections to MySQL service instances. Adjust the acceptance tests to verify this in the same way we do for Postgres.
It's best to look at alphagov/paas-rds-broker#52
Before merging:
1. Make sure you've updated alphagov/paas-rds-broker-boshrelease#40 to use a merge commit
1. Make sure you've updated the `wip` commit in this PR to use a final build
Anyone.
=> [#147829023] Force TLS for MySQL service instances

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml, scripts/generate_buildpack_release_notes.sh
Upgrade nodejs-buildpack for advisory …In response to:
- https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
Which is fixed in versions:
- https://nodejs.org/en/blog/release/v8.1.4
- https://nodejs.org/en/blog/release/v7.10.1
- https://nodejs.org/en/blog/release/v6.11.1
- https://nodejs.org/en/blog/release/v4.8.4
This is the first time that we've taken a buildpack from outside a version
cf-release. It is something that we hope to do more frequently in the
future, so that we can respond to security advisories and bugs independent
of CF upgrades.
I've omitted nodejs-buildpack from the output of the release notes script so
that we don't send conflicting messages to tenants.
It takes us from the following versions in nodejs-buildpack …
=> [#148839033] Upgrade nodejs-buildpack for advisory

README.md
compose secrets are required to deploy cf environment, this alters the
readme to clarify that you must have credentials access or to ask
another team member to perform the upload credentials step.
REAME doc updated to mention requirement of credentials.
Check the readme makes sense.
Anyone
=> [#145991105] Clarify credentials/paas-pass requirement

manifests/cf-manifest/stubs/datadog-nozzle.yml
This was missed in 1be8635f because we don't enable DataDog in dev
environments. It failed in CI with:
Error 100: Unable to render instance groups for deployment. Errors are:
- Unable to render jobs for instance group 'uaa'. Errors are:
- Unable to render templates for job 'uaa'. Errors are:
- Error filling in template 'uaa.yml.erb' (line 57:
Missing property: uaa.clients.datadog-nozzle.redirect-uri)
I'm not sure the actual URI matters. I've copied the value we've used for
`graphite-nozzle`.
This is a bit time sensitive because we told tenants we'd be doing an upgrade on Tuesday. Given how long it takes to enable DataDog in an environment I think code review only is sufficient.
Anyone.
=> [#145991105] Set redirect_uri for datadog-nozzle

doc/ssl_certs.md
Update link to credentials-high repo
It has been moved to GitHub.com
1. Check the new link works.
1. Check that I have't missed any other links.
Anyone.
=> [#145672449] Update link to credentials-high repo

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
This Bosh release includes the fix provided on the paas-datadog-for-
cloudfoundry-boshrelease repository[1].
[1] https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/20
Check in the build CI this is the correct version and includes the fix mentioned above.
Anyone but me.
=> [#145682111] Fix Nats Stream Forwarder process check

Makefile, manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml
Split capi-release from cf-release to mitigate CVEs without having to upgrade Cloud Foundry. See commit message for details.
* Deploy from master. Make sure the healthcheck app deploys correctly.
* Deploy from this branch. This makes the deployment representative of upgrading a persistent environment.
* Restage the healthcheck app. (don't blue-green deploy). The idea here is to test that the changes to the way resources are stored in [capi-release 1.31.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.31.0) doesn't cause problems.
The acceptance tests have been disabled while we work on patching them. You will probably want to override this and run the acceptance tests to verify we are not disabling them erroneously. The expected failures are documented in [the Pivotal …
=> [#149220549] Split capi-release from cf-release

terraform/datadog/cloud_controller.tf
Current alert triggers always if the change if more that 15 errors per half an hour which feels not very suitable for prod. Also we've got false positives when metric is reset after CC redeployment.
The anomaly detection method works for UAA and it seems to be correctly detecting anomalies
while allowing for counter resets.
We use exactly same settings for uaa so compare this code with https://github.com/alphagov/paas-cf/blob/master/terraform/datadog/uaa.tf#L6 . Checking on dev may be time consuming as agile algorithm need one day of historical data to learn.  
Not @combor
=> [#145517679] Use anomaly detection for cc errors.

Makefile, platform-tests/upstream/run_acceptance_tests.sh
Until we have a version of capi-release that is compatible with the cf-release we will need to patch the cf-acceptance-tests. See commit message for further details.
Deploy on top of master. Make sure the acceptance tests actually run and pass.
The patch of the cf-acceptance-tests is stored on [a branch of our fork of the upstream tests](https://github.com/alphagov/paas-cf-acceptance-tests/tree/fix-v3-app-delete). This is just a branch with no intention to be merged into anything, because it is only useful to us.
Anyone but me or @chrisfarms
=> [#149220549] Patch cf acceptance tests

manifests/cf-manifest/manifest/050-rds-broker.yml
Updates rds broker to 0.1.14:
* [#149398715] Fixes postgres JDBC URL to include TLS query string
* [#177802031] Fixes issue with postgres snapshot restore for instances with legacy users
* Deploy
Anyone
=> Update RDS Broker to 0.1.14

manifests/cf-manifest/manifest/050-rds-broker.yml
We're fixing an issue with the RDS Broker where many concurrent
connections would cause the confusion and wrongly reassign the user
causing the API to fallout on push.
- Run your pipeline from this branch
- Experience no errors
- Follow the instructions from alphagov/paas-rds-broker#62
Neither @chrisfarms nor @paroxp
=> [#149421867] Upgrade RDS Broker

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/cloud-config/020-cf-vm-types.yml
We're currently using several orgs in prod. We want to rationalise this down to 2 orgs - `admin` for things that form part of the running of the platform itself, and `govuk-paas` for things relating to our team.
This reorganises the existing things we deploy in the pipeline into these 2 orgs.
**Note:** 🚨  moving the healthcheck app can't be done without downtime, so this will cause the availability tests to fail during deployment. We discussed this at kickoff, and decided that this was acceptable in this case.
To test thoroughly, it will be necessary to enable some things that are normally disabled in dev:
* rubbernecker - add `$(eval export DEPLOY_RUBBERNECKER=true)` to dev section of Makefile, and upload necessary creds (`make dev upload-tracker-token upload-pagerduty-token`)
* …
=> [#148289089] Rationalise our CF orgs

manifests/cf-manifest/manifest/050-rds-broker.yml
This pins the version of the broker which introduced the ability for
users to run `CREATE SCHEMA`[1][2].
[1] https://github.com/alphagov/paas-rds-broker-boshrelease/pull/45
[2] https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker-release/jobs/build-final-release/builds/16
* deploy from this branch.
* check the usual tests pass.
(code review was done as part of https://github.com/alphagov/paas-rds-broker/pull/64)
Anyone but me or @chrisfarms
=> [#149144401] Upgrade RDS broker

manifests/cf-manifest/manifest/060-cdn-broker.yml
Uses the `paas-cdn-broker` PR with [support for specifying headers to forward](https://github.com/alphagov/paas-cdn-broker/pull/5).
Deploy into a CloudFoundry environment and see https://github.com/alphagov/paas-cdn-broker/pull/5.
Not @46bit @henrytk.
=> [#146274197] Use CDN broker with header forwarding

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, platform-tests/upstream/run_acceptance_tests.sh
Upgrade CAPI in response to a CVE. Backport CATS to make the tests pass. See the commit messages for more detail.
I've run the tests in my dev environment, so I think a code review would be sufficient:
- check that we're using the correct release
- check that I've backported the right things from CATS
Not @dcarley
=> [#150043715] Upgrade CAPI and backport CATS

doc/pingdom.md, terraform/pingdom/pingdom.tf, terraform/scripts/set-up-pingdom.sh
We want to monitor the availability of the API in Pingdom, so that
we can report on its availability.
https://www.pivotaltracker.com/n/projects/1275640/stories/146074949
* Plan with `make dev pingdom ACTION=plan`. It should want to create all three Pingdom checks. When the same is done for ci, staging, and prod it should only want to create the new check.
* Apply with `make dev pingdom ACTION=apply`. This will test it can create them properly, but won't test the checks actually work because we don't have proper certificates in dev.
* It should alert `the-multi-cloud-paas-team@digital.cabinet-office.gov.uk` after two consecutive failed checks, which should run every minute.
* merge and apply the checks to ci, staging, and prod.
Anyone but me
=> [#146074949] Add a CF API Pingdom check

manifests/cf-manifest/env-specific/cf-prod.yml
Increase prod cells from 21 to 24
As suggested by:
➜  paas-cf git:(bugfix/149962332-increase_prod_cells) ✗ make prod show-cf-memory-usage
…
Memory reserved by orgs: 906240 MB (885 GB)
Memory reserved by apps: 308836 MB (301.6 GB)
Total cell memory required to meet ADR017: 679680 MB (663.8 GB)
cells use r4.xlarge which have 30G RAM, so this gives us:
➜  paas-cf git:(bugfix/149962332-increase_prod_cells) ✗ bc -q
21 * 30
630
24 * 30
720
We increase by three each time so that they are balance across 3 AZs.
The code change doesn't apply to any environment except prod so you won't be able to test this in dev.
So instead, code review, make sure the numbers make sense, and that the syntax is correct.
Anyone.
=> [#149962332] Increase prod cells from 21 to 24

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
Upgrade cflinuxfs2 to 1.145.0 specifically for:
- https://www.cloudfoundry.org/usn-3363-1/
- https://www.cloudfoundry.org/usn-3363-2/
1.146.0 is available, but it has only been out for <24hrs and doesn't appear
to address any CVEs/USNs.
Deploy from a branch and check that all of the acceptance tests pass.
I have done this in a dev environment, so I think it would be acceptable to code review only and let CI catch any mysterious test regressions.
Anyone.
=> [#150010843] Upgrade cflinuxfs2 to 1.145.0

concourse/pipelines/create-cloudfoundry.yml, platform-tests/src/api/api_test.go, platform-tests/src/api/run_tests.sh
Reduce the amount of output in the API availability tests so that it's easier to see the report.
1. Deploy the branch
1. Run the pipeline and look at the output of the `api-availability-tests` job
1. Code review
Anyone. @chrisfarms or @46bit have existing context.
=> [#146074923] Reduce output in API availability tests

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/lib/compose.sh, concourse/scripts/pipelines-cloudfoundry.sh, config/service-brokers/compose/catalog.json, scripts/upload-compose-secrets.sh
This is a minimal plan which can be used for the private beta testing phase. The word
'Compose' has been removed from the catalog because tenants don't need
to know what the underlying provider is (although they still have a
link to the Compose documentation if needed).
Merging this PR will add the catalogue and use the updated version of compose-broker.
Code Review
Not @henrytk or me.
=> [#149558193] Add a basic Elasticsearch plan

manifests/cf-manifest/manifest/020-cf-properties.yml
We need to add a larger plan so larger services don't need to create workarounds.
This adds an `xlarge` quota (200GB) which is double the previous `large` quota
(100GB).
I have tested this in a dev env so code review may be enough for this change, or deploy to dev
and check that the `xlarge` quota is available in `cf quotas`
Not @chrisfarms or @henrytk
=> [#149809192] Add "xlarge" quota

manifests/cf-manifest/manifest/020-cf-properties.yml
Tenants are hitting the service limits.
This increases the service limit up to 20 for all non-free plans of medium and above
=> [#150290946] Increase service limits for medium, large, xlarge quotas

platform-tests/upstream/run_smoke_tests.sh
No associated Pivotal story
We are having performance issues with certain CF API operations, such
as deleting orgs during the smoke tests. This means it is taking over
the timeout of 30 seconds and therefore causing continuous smoke test
failures.
We will patch the tests temporarily until the performance issue is investigated.
This has not been tested yet. It is unlikely you will experience the same performance issues as production, so I recommend:
* deploying from this branch
* hijacking the smoke tests container while they are running
* verifying the imported cf-release contains a smoke test module with this patch: https://github.com/cloudfoundry/cf-smoke-tests/compare/master...alphagov:increase-timeout
* doing a code review on …
=> Increase smoke test timeout

platform-tests/upstream/run_smoke_tests.sh
No associated Pivotal story.
This reverts commit 93a24f38af8fe5beec52bf0c5249e51a91429ad6.
We now know the smoke test failures were due to degraded API performance
caused by the CDN broker taking a long time to process the last operation
requests. This timeout should be restored so we can detect similar performance
degradations in future.
In my opinion deployment of this is unnecessary and a code review alone is sufficient.
Anyone but me.
=> Revert "Increase smoke test timeout"

concourse/pipelines/create-cloudfoundry.yml, config/service-brokers/compose/catalog.json
Upgrades compose-broker to v0.9.0
The catalog config has changed slightly in compose-broker v0.9.0 to
allow setting kind (databaseType) and scale (units) per service plan.
The public facing service name for Elasticsearch should be
'elasticsearch' not 'elastic_search'
Not @chrisfarms no @henrytk
=> [#149558193] Upgrade compose-broker to v0.10.0 and update service catalog

concourse/tasks/create_admin.yml, manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, platform-tests/upstream/run_acceptance_tests.sh, terraform/datadog/nats.tf
This PR upgrades our release to CF v269 from CF v264. Due to recent CVEs being addressed through individual component upgrades the overall upgrade is quite small. The NodeJS-buildpack has been unpinned as the current release version is ahead of our pinned version.
Additionally due to the creation of the API Availability Tests within the pipeline we have been able to monitor the downtime during both releases and upgrades. During this upgrade story we discovered the `max_in_flight` property that controls the number of individual components restarted at any one time. By setting this property to `1` we have been able to reduce the API downtime significantly.
Deploy from this branch on top of current Master brach in your dev environment.
Expect a small number of API Availability Test response …
=> [#149400231] Upgrade from Cloud Foundry v264 to v269

.gitignore, terraform/scripts/set-up-pingdom.sh
This was crafted out of my frustration while testing https://github.com/alphagov/paas-cf/pull/993
Now we make sure we pin and require terraform version. The version was unpinned and newer terraform doesn’t have `remote` command. Also the state file doesn’t match pingdom plugin version and complains that it was created with newer terraform while trying to use 0.8.5
Also, we try to not download terraform plugin every time. This was supper annoying while working via VPN and trying to find out while this script fails as the download was very slow.
Run `make ci pingdom ACTION=plan` and check if it works
Not me
=> Improve pingdom script

concourse/tasks/remove-healthcheck-db.yml
This was missed when we moved the healthcheck app into a different
org(#991). This therefore updates this task to look in the correct
org/space for the app.
I've removed the test for the org existing because the admin org always
exists.
Code review is probably enough. Alternatively, you could run the destroy pipeline, and verify that the `remove-healthcheck-db` task runs, and deletes the healthcheck app. (The DB isn't enabled in dev by default).
Not me.
=> [#148289089] Fix healthcheck-db destroy.

tools/paas_dashboard/dashboards/paas-overview.erb
We've previously removed the CI box without adjusting the existing boxes
to fill the screen.
At the moment, JavaScript is pushing the production box into third half
of the screen. Decreasing the number on these will essentially mean
they'll fit in a single view.
- Run the dashboard locally - or wait until it reaches production to see the changes :trollface:
=> Adjust the box position

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
This commit applies the mitigation to USN3392-2 by upgrading the
stemcells in use from 3421.19 to 3421.20
Deploy this branch on top of a dev master.
Some small API downtime may be recorded in the API availability tests.
Anyone but @LeePorte
=> [#147668907] Upgrade stemcells to mitigate USN-3392-2

README.md, scripts/bosh_cli_tunnel.sh, scripts/ssh_bosh_expose_vm.sh, scripts/ssh_bosh_temporary_gateway.sh
We're expanding the documentation on connecting to BOSH, to handle situations where we can't use `make bosh-cli`. The `paas-cf` README has become quite large, so we're putting this as a guide in the team manual: https://github.com/alphagov/paas-team-manual/pull/137.
* Wait until https://github.com/alphagov/paas-team-manual/pull/137 is merged and live.
* Consider if we should add a notice of where to find this information.
Not @46bit @henrytk @timmow
=> [#145189815] Removed instructions for connecting to BOSH and Concourse

concourse/scripts/pipelines-cloudfoundry.sh, concourse/scripts/set_pipeline_ordering.rb, concourse/scripts/set_pipeline_ordering_test.go
This makes it the default pipeline displayed when you go to the
concourse URL.
The fly command doesn't presently have a command to do this, so this
includes a ruby script to interact with the API using credentials read
from the `.flyrc` file. I've opened https://github.com/concourse/concourse/issues/1561
to request that a command be added to fly.
This is something that's been an irritation since https://www.pivotaltracker.com/story/show/137364635 was played to include
the `create-bosh-concourse` pipeline. This one was ordered first because it's
the first pipeline pushed to the Concourse.
Run the pipeline from this branch and verify that the `self-update-pipelines` step changes the ordering of the pipelines so that the `create-cloudfoundry` pipeline is first.
Not me.
=> Order create-cloudfoundry pipeline first in concourse.

manifests/cf-manifest/cloud-config/020-cf-vm-types.yml, manifests/cf-manifest/manifest/800-logsearch.yml
It seems that we have reached a limit what we can achieve with current
VM type for parsers. We are constantly maxing out CPU and it's about a
time to increase processing power for both parsers.
Sanity check
Not @combor
=> [#support] Change parser VM type

concourse/pipelines/create-cloudfoundry.yml
Fixes a small bug/typo in the merging of the compose broker manifest
with the generated environment. It would cause deployment to fail if the
broker's manifest file was altered to not contain any env variables of
it's own.
It's a minor change, I suspect code review to be enough
=> [#150512301] Fix bug in compose-broker manifest generation

tools/metrics/metrics.go, tools/metrics/metrics_test.go
Previously the error would be lost and the reader would halt if one of the
readers in a MultiMetricReader returned an error. We think this is the cause
of `ops.users.count` not being reported occasionally.
Handle this by sending the error to the buffer (which will be surfaced by
`ReadMetric()`) and restarting `CopyMetrics()` in a loop. We test this by
sending an error to one of the readers before sending the real metrics,
checking that we get our synthetic error, and then checking that we get all
of the metrics as before.
We had to change the type of `buffers` in order to have access to the
unexported `events` field. This means that we no longer need to do a type
assertion for `WriteMetrics()`. A new slice, of the interface type
`MetricReader`, then had to be made for …
=> [#150847112] Handle errors in MultiMetricReader

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/deployment-kick-off.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/pipelines/failure-testing.yml
Use IPv4-only GPG keyserver pool.
We're experiencing an intermittent problem since we've upgraded
Concourse and garden-runc where gpg will intermittently return an error:
```
gpg: keyserver receive failed: Address family not supported by protocol
```
Switching to an IPv4-only pool works around this, and will unblock the
pipeline while we investigate further.
* Push the pipelines using this branch: `BRANCH=ipv4_keyservers make dev pipelines`
* Run the pipeline
* Verify the git fetch in the first job succeeds.
🚨  Remove the `[TMP]` commit before merging.
Not me.
=> [#150512756] IPv4 Keyservers

terraform/datadog/concourse.tf
We've upgraded Concourse to 3.4.1, which no longer uses btrfs. This
check is therefore no longer useful.
Not me.
=> [#150512756] Remove Concourse btrfs process Datadog monitor.

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/deployment-kick-off.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/pipelines/failure-testing.yml
We're enabling IPv6 in the kernel on the Concourse machine (https://github.com/alphagov/paas-bootstrap/pull/90), so this
workaround is no longer needed.
This reverts #1035.
🚨  Make sure https://github.com/alphagov/paas-bootstrap/pull/90 is merged and deployed before merging this.
Code review is probably enough once https://github.com/alphagov/paas-bootstrap/pull/90 has been reviewed.
Not me.
=> [#150512756] Revert "Use IPv4-only keyserver pool."

Makefile, scripts/upload-compose-secrets.sh
This stopped working with the following error:
➜  paas-cf git:(master) ✗ make staging upload-compose-secrets
Error: compose/staging/access_token is not in the password store.
make: *** [upload-compose-secrets] Error 1
Because we have:
1. Moved the `compose/{staging,prod}/api_token` to
alphagov/paas-credentials-high and left `compose/dev/api_token` in
alphagov/paas-credentials.
2. Added `compose/billing/{email_address,password}` to
alphagov/paas-credentials which is used for all environments.
Fix this by setting an additional environment variable for the high
credential store location in the `staging` and `prod` make targets, and
using that to get the `api_token` if it's present.
This assume that you have the high credential store checked out in
`~/.paas-pass-high` which is the path also …
=> [#149806558] Fix upload-compose-secrets for staging and prod

manifests/cf-manifest/env-specific/cf-prod.yml
As suggested by:
$ make prod show-cf-memory-usage
>>
Memory reserved by orgs: 1315840 MB (1285 GB)
Memory reserved by apps: 446052 MB (435.6 GB)
Total cell memory required to meet ADR017: 986880 MB (963.8 GB)
cells use r4.xlarge which have 30G RAM, so this gives us:
bc -q
963 / 30
32
We increase by three each time so that they are balanced across 3 AZs,
giving 33 cells
The code change doesn't apply to any environment except prod so you won't be able to test this in dev.
So instead, code review, make sure the numbers make sense, and that the syntax is correct.
Important: Check with product team that we are ok to add this many VMS before merging
Anyone but me
=> Increase prod cells from 24 to 33

manifests/cf-manifest/env-specific/cf-default.yml, manifests/cf-manifest/env-specific/cf-prod.yml, manifests/cf-manifest/env-specific/cf-staging.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/manifest/800-logsearch.yml, manifests/cf-manifest/spec/manifest/router_spec.rb
We want to get all the logs from the router in our logsearch.
Gorouter is configured to send the logs to syslog, but it is not configured to stream the access logs.
This enables these logs to be sent to syslog, and from there, to be parsed correctly by logsearch.
Due to the expected increase in log volume (~10%) and the current high disk usage, we will increase the elasticsearch disk sizes as part of this changeset.
Check the code, deploy, and execute some queries to some app in CF.
Then search in kibana for `*gorouter*`. access_log entries should appear
This pull request has been resurrected on it's anniversary and brought up to date.
Not @chrisfarms or @samcrang 
...also not @keymon or @richardc ;-)
=> [#130899727] Enable gorouter access logs

manifests/cf-manifest/manifest/050-rds-broker.yml, manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
We've had tenants asking for databases with increased storage sizes, so
this adds/amends the existing plans to offer a range of sizes.
This won't affect existing instances. We're going to upgrade these separately once this has been deployed.
As part of this change, I've taken the opportunity to refactor how we define the plans to avoid some of the duplication between Postgres and Mysql.
* Code review - Verify the tests pass.
* Deploy from this branch and verify that the plans do update, and appear correctly in `cf marketplace`.
* You could go as far as to provision an instance with one of the changed plans and verify that the storage is as specified.
Not me.
=> [#151003385] Add XL RDS plans and increase M and L storage sizes.

manifests/cf-manifest/manifest/050-rds-broker.yml, manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
We've had a request for smaller plans with encryption enabled. Amazon
now support encryption for t2.small instances[1], so this adds the
corresponding plans.
[1] https://aws.amazon.com/about-aws/whats-new/2017/06/amazon-rds-enables-encryption-at-rest-for-additional-t2-instance-types/
* Verify that the new plans are visible in `cf marketplace`.
* Create an instance using one of these new plans. Verify it creates successfully and that the storage is encrypted.
Not me.
=> [#151289532] Add small encrypted RDS plans.

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
To fix the following:
USN-3418-1: GDK-PixBuf vulnerabilities
USN-3415-1: tcpdump vulnerabilities
USN-3411-1: Bazaar vulnerability
USN-3410-1: GD library vulnerability
USN-3405-2: Linux kernel (Xenial HWE) vulnerabilities
USN-3398-1: graphite2 vulnerabilities
USN-3420-2: Linux kernel (Xenial HWE) vulnerabilities
Deploy from this branch against an existing deployment. Verify that all the tests pass.
Not me.
=> [#151321276] Upgrade stemcell and cflinuxfs2 to fix USNs

scripts/create-user.sh
This script has `set -u` at the top, and was therefore erroring with:
```
./scripts/create-user.sh: line 181: uaa_uuid: unbound variable
```
For some reason this wasn't causing an issue with bash 3 (as included in
OS X). I presume bash 3 is not complaining because this variable is
declared as 'local' at the top of this function.
Test creating a new user in a dev environment using both bash 3 and bash 4 (the `--no-email` flag is useful when testing against dev).
Bash 4 is available in homebrew, but the `#!` line in the script will need to be updated to point to it while testing.
Not me.
=> [Support] Fix create-user.sh to work with bash 4

platform-tests/src/acceptance/redis_service_test.go
I got confused looking at test output when the database name was test-es
and assumed these were elasticsearch intstances - redis is more
descriptive
This should probably be applied to an environment - i'm in the middle of testing another story at the moment and we are having issues with composse so i've not done this yet. I'm slightly concerned if there are any issues around the length of the service name in compose
Anyone but me
=> Update generated prefix for redis instances

platform-tests/src/acceptance/elasticsearch_service_test.go, platform-tests/src/acceptance/mongodb_service_test.go, platform-tests/src/acceptance/redis_service_test.go
We've been experiencing intermittent 5xx errors from the Compose API.
This is causing frustration while developing and slowing down delivery.
As the Compose services are currently in private-beta we've therefore
decided to disable these tests until the issues are resolved.
Run the pipeline from this branch. Verify the tests that hit the Compose API are marked as skipped in the output from the custom-acceptance-tests.
Not me.
=> [#151437914] Temporarily disable the Compose acceptance tests.

scripts/cf_subshell_scoped_login
This is useful when you want to login to one of the persistent
environments for a specific task without that affecting other terminal
sessions.
For context, the CF CLI keeps information about the currently targeted
API endpoint along with auth tokens etc in $CF_HOME/.cf/config.json. If
CF_HOME is unset, it detaults to $HOME.
This script therefore creates a temporary directory and sets CF_HOME to
that before dropping into a subshell. An exit trap cleans all this up.
* Consider whether the script name makes sense (I found it hard to come up with a good name for this).
* In one terminal log in to a dev environment.
* In another terminal window, use this script to log in to staging or prod (`./scripts/cf_subshell_scoped_login staging`).
* Verify that first terminal session is unaffected and …
=> [Support] Add cf_subshell_scoped_login helper script.

Makefile, scripts/scripts_suite_test.go, scripts/uaa_lock_user.rb, scripts/uaa_lock_user_test.go
This will replace the rather cumbersome process for locking (or unlocking)
users that's currently described in the team manual:
- https://government-paas-team-manual.readthedocs.io/en/latest/guides/CF_UAA_user_management/#locking-a-user-account
I've mocked just enough of the UAA responses to make it work and verify that
we're sending PATCH requests when the state needs to change.
Per the original script, I've left TARGET and TOKEN as environments, to call
out the fact that they are mandatory and to help avoid you storing tokens in
your shell history.
1. Code review
1. See if the tests make sense and pass
1. Try it in a dev environment:
1. Create an account using `scripts/create-user.sh`
1. Verify that you can login
1. Lock the account and verify that you can no longer login
1. Unlock the …
=> [#149929104] Add uaa_lock_user.rb script

manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/manifest/050-rds-broker.yml
As part of the #150879493, we're reworking the parameters on the RDS
broker so that `cf update-service` commands trigger changes to applied immediately by default.
We're also fixing some other previously in correctly documented parameters to our users.
Deploy from this branch, then check that you can upgrade a plan for an RDS service instance by running something like:
```
cf update-service pg -p S-HA-dedicated-9.5
```
... the process of upgrading should begin immediately (visible from AWS console) and should complete in about an hour (from our experience)
Once that's done you can then check that you can request upgrade during a maintenance window using something like:
```
cf update-service pg -p M-HA-dedicated-9.5 -c '{"apply_at_maintenance_window": true, "preferred_maintenance_window": …
```
=> [#150879493] Upgrade the RDS Broker

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/deployment-kick-off.yml, concourse/scripts/rds_instances.sh, concourse/tasks/kill-instance.yml, concourse/tasks/upload-test-artifacts.yml
We believe it will decrease the costs for the development environments to
turn off the RDS instances over the night along with the rest of
`autodelete-cloudfoundry` pipeline.
These will start back up in the morning, with the use of
`deployment-kick-off` pipeline.
We've prepared a script which could be also used locally if needed in
order to not duplicate the same functionality before start/stop call.
We need some of the functionality from the newer version of AWS CLI. We
did that in our alphagov/paas-docker-cloudfoundry-tools#100 repo and needed to
include it in our pipelines.
- Code review
- Run `autodelete` pipeline
- Check all RDS instances have stopped for your environment
- Run the `kick-off` pipeline
- Check all RDS instances have started again
- Check `create-cloudfoundry` pipeline …
=> [#150926071] Add RDS Instance management

manifests/cf-manifest/manifest/050-rds-broker.yml
**NOTE: review migration scripts first and run them on prod**
As the migration period has passed some time ago we've decided to remove
the code responsible for migration to reduce codebase complexity and
maintenance burden.
This needs to be updated after
https://github.com/alphagov/paas-rds-broker-boshrelease/pull/48
is merged.
- deploy from this branch, create a service, bind it to an app and finally unbind
Not @combor or @46bit
=> [#146290921] Remove MigrateLegacyAdminUsers code

manifests/cf-manifest/manifest/020-cf-properties.yml
This enables mutual TLS between CloudController and Diego components. This change also means that much of this communication now happens directly as opposed to going through the cc_bridge components. Once this is deployed, there will be a follow-up PR to remove the unneeded cc_bridge components.
This PR is built on top of #1056, and includes the commits from that PR.
🚨  #1056 must be merged and deployed to prod before this is merged.
* Deploy from this branch against an environment with #1056 deployed.
* Verify that the deploy succeeds without any downtime, and that all the tests pass.
Not @bandesz or myself.
=> [#150397953] Migrate away from legacy bridge components

manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/manifest/020-cf-properties.yml
Following on from #1058, this cleans up the legacy bridge components that are no longer needed.
🚨  #1058 must be merged and deployed to prod before this is merged.
* Deploy from this branch against an environment with #1058 deployed.
* Verify that the deploy succeeds without any downtime, and that all the tests pass.
Not @bandesz or myself.
=> [#150397953] Cleanup legacy bridge components

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/deployment-kick-off.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/pipelines/failure-testing.yml, concourse/scripts/pipecleaner.py, concourse/scripts/pipelines-cloudfoundry.sh, concourse/scripts/spec/fixtures/pipecleaner_shellcheck.yml
We've upgraded concourse to the version 3.4.1 not so long ago. Although
the old templating is still supported it will be deprecated in the
future.
The new format supports proper types and variable interpolation.
Pipecleaner had to be modified in order to fit the new syntax.
Some of the functionality has been fixed after the upgrade. Removing it
may benefit us with a clean codebase.
- Sanity code check
- See if there aren't variables left out
- See if related `FIXME`s have been resolved
I have tested pushing the pipelines and running the `create-cloudfoundry` pipeline.
=> [#150881142] Update pipeline variables to new format

manifests/cf-manifest/manifest/060-cdn-broker.yml
cdn-broker version is updated to 0.1.5 and cdn-cron is added to the cdn_broker job.
The certificate renewal will run every hour (default schedule).
The cdn-broker changes can be found here: https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/6
* Deploy the changes
* We expect this to only run one instance of the cdn-cron job, to avoid race conditions in the renewal of certificates.
* Note: The renewal process was already tested as part of the cdn-broker bosh release PR.
Not me or @henrytk
=> [#151516133] Enable automatic certificate renewal cron job on cdn-broker

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml
In v50 there was a memory leak issue which was fixed in v51. We're
manually bumping the version of UAA to prevent this happening again.
This should be reverted once we upgrade the CF release to >= v276.
This is a critical release as the memory leak can cause another downtime in production soon.
* sanity check
* deploy the changes
* all tests should pass
not me or @paroxp
=> [#151808174] Upgrade UAA to v51

concourse/scripts/pipelines-cloudfoundry.sh, concourse/tasks/terraform_destroy_datadog.yml
Fixes the autodelete-cloudfoundry and destroy-cloudfoundry pipelines. If the datadog parameters (datadog_api_key, datadog_app_key) are empty they are passed as "null" string instead of empty strings. It seems this only happens when we trigger an external task in the pipeline.
Also removes a sed hack during the manifest generation which is not needed anymore because the new parameter format is able to handle arrays properly.
I added a temporary commit for testing to set the branch name to this one for the autodelete pipeline.
* Set your datadog keys (datadog_api_key, datadog_app_key) in the datadog-secrets.yml to an empty string
* Update the pipelines with ```BRANCH=fix_pipeline_variables_150881142 SKIP_COMMIT_VERIFICATION=false``` and check the diff
* Run the autodelete pipeline and check …
=> [#150881142] Fix autodelete/destroy pipelines and remove gpg_ids sed hack

scripts/usage_reporting/README.md
process_events.go now has start and end flags, these were not
documented when they were added. This commit adds them into the example in the
readme.
Code review
Not @LeePorte
=> Update readme to include start and end date params

concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/bosh-cli.sh
I've been using this successfully for ~week now, so it might be of interest to others...
The current bosh-cli make target works by hijacking a concourse
container that has recently run (and succeeded) to use as a temporary
shell to access bosh.
Some recent concourse updates changed the behaviour of how long and when
old containers are garbage collected, and where it used to be the case
that if you were logged in to a hijacked container the container would
be protected from garbage collection (or at least stay around for a very
long time), it is now the case that containers are cleaned up after
around 5mins and we get kicked out of our bosh-cli shell.... which is
frustrating.
To workaround this issue the following changes are made:
* the run-bosh-cli task will now sleep for as long as more …
=> [#151167914] Workaround for bosh-cli timeout

concourse/pipelines/create-cloudfoundry.yml
This is currently using the manifest from the state bucket. There have
been situations where this manifest doesn't match what's currently
deployed to bosh. In this case it can cause problems when interacting
with bosh because it complains that a deployment hasn't completed etc.
Switching this task to instead download the manifest from the bosh
director ensures that the manifest we're using matches Bosh's view of
the world.
Push pipelines from this branch, and then run `make dev bosh-cli`. Verify that you're logged into bosh correctly, and that the deployment is set correctly.
Not me.
=> bosh-cli: download manifest from bosh

manifests/cf-manifest/env-specific/cf-prod.yml
We need to scale the cell VMs in order to satisfy ADR017[1].
Output from `make prod show-cf-memory-usage`:
```
Memory reserved by orgs: 1408000 MB (1375 GB)
Memory reserved by apps: 510380 MB (498.4 GB)
Total cell memory required to meet ADR017: 1056000 MB (1031.3 GB)
```
Current cell memory = 1006.5GB = 30.5 (r4.xlarge memory) * 33 (number of cell VMs in prod).
This means we are currently not satisfying ADR017. 36 instances is enough to
cover the current shortfall and respond to a recent request to increase an
organisation's quota.
[1] https://government-paas-team-manual.readthedocs.io/en/latest/architecture_decision_records/ADR017-cell-capacity-assignment/
Code review. The chance of human error is small, but the consequences of error are potentially catastrophic.
Check my math.
ADR017 …
=> Scale cell VMs

terraform/datadog/aws.tf
We want in-hours alerting when RDS instances fail or run low storage. This applies to both tenant and platform instances. This PR creates both - see the commits for more information.
1. The final commit is purely for reviewing and should be removed before merging. With that commit present, the monitors will be created to monitor the staging environment. This is necessary because we have no Datadog RDS Integration in dev.
2. Create RDS instances in staging and fill them with data. You should see warnings generated when they reach 80% and alerts when they reach 90%. We have added an app in a temporary, not-to-be-merged app in the `filler` branch that can fill up MySQL instances but it does not work for Postgres.
3. We cannot generate test `failure` events, but you can temporarily modify …
=> [#147674123] Monitor RDS for instances failures and disk utilisation

concourse/tasks/remove-healthcheck-db.yml
This task runs early in the autodelete-cloudfoundry pipeline, and
previously would delete the healthcheck app so that it's database could
be deleted. If a job later in the pipeline failed, the system would be
left in a state where the app had been deleted, but the flag file in the
state bucket still indicated it was deployed. This then caused problems
in the next deployment as the availability tests would run and fail.
There's no need to delete the app in this task, and it's non-obvious
from the name that it will be. This therefore updates the task to merely
unbind the app from the database before deleting the database.
* Run a deploy from this branch to create the healthcheck DB.
* Run the `autodelete-cloudfoundry` pipeline and verify that the healthcheck DB is successfully deleted (the …
=> Don't delete healthcheck app when deleting healthcheck DB

Makefile, concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/scripts/pipelines-cloudfoundry.sh, concourse/tasks/remove-billing-db.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/scripts/generate-cf-secrets.rb, manifests/cf-manifest/spec/manifest/base_properties_spec.rb
We created a usage events collector application to collect app and service usage events for billing purposes. Cloud Foundry keeps the usage events only for a limited time (in our case currently for 45 days) and we need these events to be persisted for long-term.
The app repository can be found [here](https://github.com/alphagov/paas-usage-events-collector).
This pull requests contains the following changes:
* creates a new billing space in the admin organisation
* creates a new billing database in the billing space
* creates a new UAA client with admin_read_only scope (global_auditor is not able to read usage events)
* starts the usage events collector application in the billing space
* the database and the app is only created in prod
* on dev you can enable the database and the app by …
=> [#151838550] Add usage events collector app and billing database

scripts/get-instance-details.sh
As part of #147674123 we would like to have an easy way of establishing
the belongings of an individual instance.
Given we obtain an instance ID from either DataDog, Kibana or AWS
Console, we can run this script to learn which org and space the
instance belong to along with it's name and list of org managers.
- Shell code check
- Test the script to obtain some details about random instance (follow alphagov/paas-team-manual#155)
=> [#147674123] Add instance detailing script

tools/metrics/gauges.go
We have added new tags to app and services metrics reported by the `paas-metrics` application. This allows the product dashboard to be broken down by those tags. The caveat of this work is that minor business logic (the names of trial org quotas and free service plans) is now contained within that app. See the commit message for more details.
* I've already shown the Datadog results to Tom and he seems happy
* Thoughts on how we're detecting trial orgs and free services?
* Code review?
Not @46bit @LeePorte.
=> [#151014551] Tag app and service `paas-metrics` with their org's quota

manifests/cf-manifest/manifest/050-rds-broker.yml
This upgrades the broker to a version that includes a fix to allow
unbind to work for legacy bindings[1]
[1]https://github.com/alphagov/paas-rds-broker/pull/71
Simulate a legacy binding by doing the following against a deployment from master:
* Create a postgres instance, and bind an app to it.
* Login to the postgres instance as the master user, and delete the user corresponding to the binding. (The master password can be obtained using the [rds-broker-password](https://github.com/alphagov/paas-rds-broker/tree/master/rds-broker-passwd) utility.)
* Attempt to unbind the app and observe it fail.
Deploy the fix and test again:
* Deploy from this branch, and verify everything passes.
* RE-attempt the unbind, and verify that it now succeeds.
:rotating_light: This branch must be updated to …
=> [#152067657] Fix rds-broker unbind for legacy bindings

concourse/tasks/create_admin.yml, manifests/cf-manifest/cloud-config/020-cf-vm-types.yml, manifests/cf-manifest/cloud-config/021-cf-vm-extensions.yml, manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/spec/cloud-config/vm_types_spec.rb, manifests/cf-manifest/spec/manifest/jobs_spec.rb, terraform/cloudfoundry/elbs.tf
Whilst investigating UAA downtime during deploys we decided that we should move
UAA to run behind gorouter. This should mean we reduce (and possibly eliminate)
downtime during deploys because connections will be drained by removing the
route whilst UAA is shutting down.
In order to move UAA behind the gorouter, we will need a different way
of registrating our routes. We decided to fallback onto upstream to get
closer to the setup the community is running. We've implemented the
route-registrar configuration, strictly specific to UAA at this point.
Haproxy automatically adds a reason text to its http response statuses. E.g.
"201 Created" instead of plain 201. In our create_admin.yml task we should only
check if the response starts with 201, as the UAA was moved behind gorouter +
haproxy and …
=> [#151322324] Move UAA behind gorouter

concourse/tasks/create_admin.yml, manifests/cf-manifest/cloud-config/020-cf-vm-types.yml, manifests/cf-manifest/cloud-config/021-cf-vm-extensions.yml, manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/spec/cloud-config/vm_types_spec.rb, manifests/cf-manifest/spec/manifest/jobs_spec.rb, terraform/cloudfoundry/elbs.tf
Revert changes from #1081 
Deploying these changes resulted in significant (30mins +) APi downtime
in staging. We're therefore going to revert these changes to unblock the
pipeline while we work out a way to deploy this without the disruption.
Verify that this correctly reverts #1081 (for example `git diff HEAD prod-0.1.62`)
Not me.
=> [#151322324] Revert "Move UAA behind gorouter"

concourse/tasks/create_admin.yml, manifests/cf-manifest/cloud-config/020-cf-vm-types.yml, manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/spec/cloud-config/vm_types_spec.rb, manifests/cf-manifest/spec/manifest/jobs_spec.rb
Our previous approach #1081 causes a 30 minute downtime caused by the
modification of terraform resource and not updating the configuration in time.
We're eliminating this problem by splitting the previous approach into two separate
PRs, where at first we register the routes and prepare the use of newly configured 
ELB, causing the healthchecks to fail and not sending any traffic to it, and in the
second PR, we actually reconfigure the ELB which otherwise would cause the 
downtime, until the `cf-deploy` job ran its tasks.
---
Whilst investigating UAA downtime during deploys we decided that we should move
UAA to run behind gorouter. This should mean we reduce (and possibly eliminate)
downtime during deploys because connections will be drained by removing the
route whilst UAA is shutting …
=> [#151322324] Move UAA behind Gorouter 1/2

manifests/cf-manifest/cloud-config/021-cf-vm-extensions.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml, terraform/cloudfoundry/elbs.tf
Our previous approach #1081 causes a 30 minute downtime caused by the
modification of terraform resource and not updating the configuration in time.
We're eliminating this problem by splitting the previous approach into two separate
PRs, where at first we register the routes and prepare the use of newly configured 
ELB, causing the healthchecks to fail and not sending any traffic to it, and in the
second PR, we actually reconfigure the ELB which otherwise would cause the 
downtime, until the `cf-deploy` job ran its tasks.
---
Whilst investigating UAA downtime during deploys we decided that we should move
UAA to run behind gorouter. This should mean we reduce (and possibly eliminate)
downtime during deploys because connections will be drained by removing the
route whilst UAA is shutting …
=> [#151322324] Move UAA behind Gorouter 2/2

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
To fix the following:
- https://www.cloudfoundry.org/usn-3424-1/
- https://www.cloudfoundry.org/usn-3434-1/
- https://www.cloudfoundry.org/usn-3444-2/
- https://www.cloudfoundry.org/usn-3454-1/
- https://www.cloudfoundry.org/usn-3441-1/
- https://www.cloudfoundry.org/usn-3432-1/
They all reference the same minimum version of 3445.15 (for the stemcell
series that we're using).
To fix the following:
- https://www.cloudfoundry.org/usn-3454-1/
- https://www.cloudfoundry.org/usn-3424-1/
- https://www.cloudfoundry.org/usn-3434-1/
- https://www.cloudfoundry.org/usn-3441-1/
- https://www.cloudfoundry.org/usn-3432-1/
- https://www.cloudfoundry.org/usn-3437-1/
Version 1.161.0 is the minimum specified by USN-3454-1, whereas the other
advisories reference older versions.
I've run this in my dev …
=> [#152507627] Upgrade cflinuxfs2 and stemcells for CVEs

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
This supersedes the upgrade to 3445.15 in 961e427d because that stemcell
doesn't have a "light" version published. Meaning that:
- the same URL redirects to the "fat" version instead
- it takes longer to download/upload
- it possibly requires more time recompiling packages when deploying VMs,
but haven't haven't confirmed that
- it's not usable with bosh-init from a container
In order to be consistent with previous deployments and the stemcell that we
have to use in paas-bootstrap we're going to skip .15 in production and go
straight to .16 - the only difference in the contents are Ubuntu package
updates.
I've tested my dev environment upgrading from 3445.15 to 3445.16 - it took about an hour to run cf-deploy and the acceptance tests passed afterwards.
I'll leave it to the reviewer to …
=> [#152507627] Upgrade stemcell to 3445.16

terraform/datadog/elb.tf
Following on the UAA downtime incident from October 9, we would like to
monitor our API latency and get alerted if anomaly is detected.
This will create a monitor for each of four components:
- uaa
- cc
- router
- doppler
This will not trigger PagerDuty incident but will trigger our dashboard
to report a single alert.
- Code review
- Check if the threshold numbers make sense
- **Optionally:** Deploy from this branch, and manually change from `name:${DEPLOY_ENV}-cf-uaa` to `name:staging-cf-yaa` and perhaps change the thresholds to `c:1`, `w:0` to see the alerts
Neither @camelpunch nor myself
=> [#152150279] Create API Latency monitor

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
In order to protect ourselves from [CVE-2017-8031](https://www.cloudfoundry.org/cve-2017-8031/) exposure, we need to
upgrade the UAA release to at least version 52.1.
- Make sure that the version used will cover us against this CVE
~~I haven't tested this yet. It's still deploying in my pipelines.~~
=> [#152670116] Bump UAA version to 52.1

terraform/datadog/aws.tf
We would like to know if any of our EC2 instances has high CPU usage as it
might affect our services. We introduce two alerts:
* a warning if an EC2 instance has at least 50% CPU usage on average for two
hours or more
* a critical alert if an EC2 instance has at least 80% CPU usage on average
for 30 minutes or more
Please note that there is at least 10 minutes delay for AWS metrics.
In the warning alert we still have to specify a critical threshold, but it will never fire. We have to do this because we want to check different time windows for the two alerts.
* Enable Datadog in your dev environment, update the pipelines and run the create-cloudfoundry pipeline
```BRANCH=cpu_usage_monitors_152150260 ENABLE_DATADOG=true SELF_UPDATE_PIPELINE=false make dev pipelines```
* The cf-deploy job …
=> [#152150260] Add Datadog monitors for high CPU usage

terraform/datadog/elb.tf
We realised that the CC ELB will create a lot of noise in our production environment. We decided to amend the thresholds as well as the window to for the metrics to be monitored.
I've updated the window on other monitors too and took the decision to change the latency check from "both" to "above" as we probably don't care if it took less time than usual to serve the response.
We're also removing the router monitor as it's not strictly part of the API we mean to monitor and we may get some false alerts if tenant application would take time to serve response.
- Code review
- Deploy from this branch with DataDog enabled 
```
BRANCH=$(git rev-parse --abbrev-ref HEAD) ENABLE_DATADOG=true SELF_UPDATE_PIPELINE=false make dev pipelines
```
- Go into the DataDog and manually change the monitors …
=> [#152150279] Tune the Latency monitor

terraform/datadog/aws.tf
* We have excluded cells from the CPU utilisation monitor
* We have replaced the two CPU monitors with a single CPU monitor
* We have altered the name of the monitor 
It is expected behaviour that cells spike to relatively high levels of CPU for prolonged periods of time due to tenant activity, but this behaviour is currently triggering our CPU monitors and causing unwanted noise for support. We want to exclude them from these alerts and 
We were also seeing both "critical" and "warning" level notifications at the same time due to our split of "moderately high cpu over a long time" and "high cpu over a short time". We decided this doesn't add too much value, so have switched to using a single monitor with higher thresholds over a 1hr period instead.
The names were altered for consistency …
=> [#152150260] Exclude cells from CPU utilisation monitor

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
We have upgraded CF to v278 and upgraded cflinuxfs2 to 1.66.0. There are no buildpack changes in this upgrade.
Deploy from this branch on top of current master in dev with `ENABLE_DATADOG=true`
Check that the number of API test failures correlates with the acceptance criteria 
Not @LeePorte or @46bit
=> [152510403] CF upgrade to v278 

concourse/scripts/sleep_for_deploy_env.sh
We're seeing the deployment kick-off job fail regularly due to
rate-limiting and the like. For some people it almost never completes
successfully. This is an attempt to avoid this by increasing the
spread of the morning deployments to hopefully avoid the rate-limiting.
Code review
Verify the script still works (eg `docker run -ti --rm -v $(pwd):/app --env DEPLOY_ENV=foo alpine:3.4 /app/concourse/scripts/sleep_for_deploy_env.sh`)
Not me.
=> [#152840181] Increase the splay for the deployment kick-off jobs

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/manifest/800-logsearch.yml, platform-tests/src/platform/acceptance/account_management_test.go, terraform/cloudfoundry/elbs.tf
Sadly we still see some 503 errors. Out of 6 deploys only 2 had 1-1 errors.
We made the following changes:
* Nginx was removed from UAA as it was causing some of the downtime (the route-registrar health check was running against UAA and not Nginx) - this removed the 502 errors we saw
* We enabled the connection draining on the UAA ELB (with default draining timeout which is 300s), which removed the remaining EOF errors but introduced new 503 errors (from the haproxy in front of the gorouter).
* We set the drain_wait to 120s on the gorouter which decreased the number of 503 errors
* The uaa.self_service_links_enabled parameter now disables the self-service links (like create account and reset password links), not just removes the links therefore there is no need for nginx anymore.
Minor …
=> [#152543946] Eliminate most of the errors during UAA deploys

scripts/create-user.sh, scripts/templates/create_user_html.erb, scripts/templates/create_user_plain.erb, scripts/templates/email_template.erb, scripts/templates/reset_password_html.erb, scripts/templates/reset_password_plain.erb
This change adds a HTML version to our 'Welcome to PaaS' email which we send
when we create a new user or reset the password for an existing user.
I copied the HTML template from Notify: https://github.com/alphagov/notifications-utils/blob/master/notifications_utils/jinja_templates/email_template.jinja2
I extracted the existing plain text template to a Ruby ERB template and saved
the new HTML template next to it. The HTML code would be hard to handle in the
script and this way the templates are easier to manage.
Also we decided to separate the create user and the reset password emails therefore the multiple templates.
I added an email template file so we only have to define the content for the different emails.
If your not using your gov.uk email for testing you may have to verify it in …
=> [#152638275] Restyle the 'Welcome to PaaS' email

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, terraform/cloudfoundry/elbs.tf
The old health checking method is deprecated so we'll start to use the new one. (Details: https://github.com/cloudfoundry/gorouter#healthchecking-from-a-load-balancer)
Changes:
- use new haproxy release which creates a new frontend for the health checks
- use the /health path for health checking on the UAA and the router ELBs
1. Update your dev CF from this branch
1. Confirm that the `api-availability-tests` passed or only had some 503 errors. Confirm that the `app-availability-tests` had no errors.
1. Deploy from a temporary branch that includes the following stemcell change for `router` and `uaa`:
```patch
diff --git a/manifests/cf-manifest/manifest/000-base-cf-deployment.yml b/manifests/cf-manifest/manifest/000-base-cf-deployment.yml
index fc24d003..e639d6a4 100644
--- …
```
=> [#151948132] Use new gorouter health check

concourse/scripts/import_bosh_ca.sh
This change will suppress the following warning message:
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
It's not actually an indication of a problem but it could distract a team member working on an incident.
Run your CF pipeline and check if we're not logging the warnings anymore (e.g. pre-deploy/wait-for-app-availability-tests)
Not @bandesz
=> [#152150403] Suppress update-ca-certificates skipped warning in the logs.

concourse/scripts/pipecleaner_test.go
This test has failed in Travis a few times due because pipecleaner
doesn't return within 1 second. This therefore doubles the timeout to 2
seconds.
As part of this, I've also switched to using [`session.Wait()`](https://godoc.org/github.com/onsi/gomega/gexec#Session.Wait) as that
seems cleaner than continually polling for the exit code via
`Eventually`.
* Code review.
* Verify the test passes in Travis
Not me.
=> Increase pipecleaner timeout in tests.

terraform/cloudfoundry/cdn_broker.tf, terraform/cloudfoundry/rds_broker.tf
We do this to help with debugging issues reported by tenants when
doing various broker operations. We can use the existing bucket for
ELB logs as the prefix provides a suitable namespace.
I haven't deployed this, so you should. Run the pipeline, check it doesn't break anything, then look in the bucket for the logs.
There is a slight cost implication for storage.
Anyone but me.
=> Start collecting broker ELB logs

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml
Application Subdomain Takeover via Cloud Foundry Private Domains:
- https://www.cloudfoundry.org/cve-2017-14389/
This takes us from 1.44.0 which is included in cf-release v278 to an
individual release of 1.45.0.
I've updated all of the jobs that appear in this release:
- https://bosh.io/releases/github.com/cloudfoundry/capi-release?version=1.45.0
The release notes for the release say:
> Breaking logging change with introduction of property cc.log_db_queries which
> defaults to false for jobs cloud_controller_ng, cloud_controller_worker, and
> cloud_controller_clock. This causes DB logs to not be logged by default. If you
> want to see these logs then you'll need to switch this value to true.
This shouldn't affect us because we've already gone to
lengths to reduce the amount of noisy …
=> [#152962527] Upgrade CAPI for CVE-2017-14389

manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/spec/manifest/base_properties_spec.rb, scripts/create-user.sh
When the user receives an email to complete their registration it will
ask them to provide their password. Once the password is set
successfully, user has accepted an invitation and will be redirected to
the UAA home page.
It isn't very useful page, especially if you're just starting off with
CF. We've created our own landing page we'd like to be providing to our
users upon registration.
- Code review
- To be reviewed with alphagov/paas-product-page#41
- Create a new user in your `dev` env `./scripts/create-user.sh -e user@example.com -o govuk-paas --no-email`
- Click/Copy paste the URL into your browser
- Set user name
- Expect to be redirected into correct page (you may see 404 if the page is not deployed)
The alphagov/paas-product-page#41 needs to be merged …
=> [#152916557] Add custom redirection on user invite

concourse/scripts/val_from_yaml.rb, concourse/scripts/val_from_yaml_test.go
Rubocop autocorrect in 97a8a506 changed the order of a comparison which
broke `val_from_yaml.rb` when looking up array items by position. We noticed
this when `get-and-upload-stemcells` in the `create-cloudfoundry` pipeline
no longer uploaded the stemcell so a fresh deployment failed with:
Error 50003: Stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3468.5' doesn't exist
The use of `===` meant that the order of the comparison arguments were
significant. When regex is the first argument it compares the other value to
the regex, but when a string is the first argument it also asserts that the
other argument is also a `String`.
- https://apidock.com/ruby/Regexp/%3D%3D%3D
- https://apidock.com/ruby/String/%3D%3D%3D
Fix this by explicitly using `=~` to compare to a regex. I've added a test …
=> [#152962527] val_from_yaml.rb: Fix array lookup by position

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
This commit updates both the stemcells version and the cflinuxfs2
version in use in response to the latest Ubuntu CVEs announced.
I have deployed in my environment on top of a current master with no issues, if you wish you can deploy this branch on top of a current master.
Not @LeePorte
=> [#153213175] Update stemcells and cflinuxfs2 in use.

scripts/create-user.sh
We have had erroneous orgs generated by typos in the org name passed
to this script. Significant clean up is required once a tenant starts
developing in the wrong org.
Code review. Check it still creates users properly and prompts before creating new orgs.
Anyone but me.
=> Prompt before creating orgs when creating users

concourse/scripts/rds_instances.sh
This PR keeps the BOSH RDS instance in all dev environments running at night. We hope this will resolve errors in our morning deploys. See the commit message for more details.
* Code review.
* Deploy it and verify that your morning deploys start succeeding.
Not @46bit @dcarley
=> [#152840181] Keep dev BOSH RDS instances running at night

scripts/cleanup_unused_cdn_broker_iam_certs.rb
We're seeing multiple IAM server certificates for earh cdn-broker
service instance. Only the most recent one for each instance is actually
in use. These unused certs are causing us to come close to hitting the
AWS service limits for IAM server certificates.
This adds a script to clean these up. This is only a temporary solution
until the cdn-broker can be updated to clean these up itself.
Check the script makes sense.
This is one of those things that's hard to test in a dev environment because there won't be any cdn-broker instances in this state. Having said that, I believe this is low-risk because AWS won't allow us to delete a cert that's in use.
Not me.
=> [Support] Script to cleanup unused CDN broker IAM certs

terraform/cloudfoundry/rds_broker.tf
The default is 3 days which means that over the weekend, useful messages
can be gone and it's too late to investigate any issues on a Monday
morning.
* Create a Postgres instance in a dev env deployed from master.
* Verify that the log retention is updated on the instance (parameter group should be "in-sync")
Not me.
=> [#153170266] Extend rds-broker instance log retention to 7 days

concourse/pipelines/create-cloudfoundry.yml
In persistent environments, which have valid TLS certificates, having
CF_SKIP_SSL_VALIDATION unset meant that uaac was passed a quoted empty
string as an argument and failed with `Too many command line parameters given.`
I unquoted the argument to `uaac target` to avoid this happening.
Code review. I've run it in my dev env, for what it's worth
=> [#152144657] Fix cred rotation in envs with valid TLS certs

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/cell.yml, manifests/cf-manifest/cloud-config/020-cf-vm-types.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/spec/manifest/base_properties_spec.rb, manifests/cf-manifest/spec/support/manifest_helpers.rb
This has `rep` advertise cells as having 66% more memory capacity than they really have. This is safe: apps running on the platform use ~34% of their reserved memory, and we calculated this change assuming a more conservative 60% utilisation. See commit messages for details.
* Code review
* Deploy in your dev environment and check the `rep` metrics and monitors look good
Not @46bit @camelpunch
=> [#131354667] Overcommit cells by 66%

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/pipelines-cloudfoundry.sh
This is being moved to a separate pipeline on the build concourse as
it's not really related to the CF deployment.
With this, we no longer need the Pivotal tracker, or Pagerduty APi
tokens in the pipeline anywhere, so the handling for these can be
cleaned up as well.
Review in conjunction with https://github.com/alphagov/paas-release-ci/pull/46
Run the pipeline from this branch and verify nothing breaks.
Not me.
=> [#138512111] Remove rubbernecker deployment from pipeline.

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/manifest/020-cf-properties.yml
* Update the UAA client spec to allow the billing api app to request authorization for a selection of read-only scopes.
* Set paas-usage-events-collector app to pull in the branch at https://github.com/alphagov/paas-usage-events-collector/pull/5
Deploy this branch to your dev environment using:
```
ENABLE_USAGE_EVENTS_COLLECTION=true SELF_UPDATE_PIPELINE=false BRANCH=calculate_billing_152241494 make dev pipelines
```
Update the [TMP] commit to point to a tag not a branch.
not @chrisfarms
=> [#152241494] Enable Billing API Auth

platform-tests/src/platform/availability/api/api_test.go, platform-tests/src/platform/availability/monitor/monitor.go, platform-tests/src/platform/availability/monitor/monitor_test.go
https://www.pivotaltracker.com/story/show/152885584
We want to avoid putting the API and UAA under unnecessary load during availability tests. We only care about the API being continually available, this is not a form of load testing.
The tasks performed against the API are not simple, single-request tasks, so we can't use a library such as Vegeta to perform the rate limiting. For simplicity, the rate at which tasks are added to the queue has been throttled.
Under the new configuration we will not need as many workers, as only two tasks per second will be added to the queue.
If you have a deployment from master you can deploy from this branch and the temporary commit will rotate the `api/*` and `uaa/*` VM stemcells.
We want to know when a deployment happens the API availability tests …
=> [#152885584] Reduce load on API during availability tests

manifests/cf-manifest/manifest/070-elasticache-broker.yml
This PR updates the elasticache-broker BOSH release.
For detailed changes please see: https://github.com/alphagov/paas-elasticache-broker/pull/4
❗️ This PR only contains a temporary commit to set the elasticache-broker BOSH release to a dev version. Please replace the commit with the final release parameters after https://github.com/alphagov/paas-elasticache-broker-boshrelease/pull/2 was merged.
1. Update and run your CF pipeline from this branch
```BRANCH=elasticache-param-groups-cleanup-153321792 make dev pipelines```
2. While the custom-acceptance-tests are running you should see a new redis cluster being created. Write down its name and check if the cache parameter group was deleted after the custom-acceptance-tests finish successfully. (The blackbox tests are not testing this …
=> [#153321792] Clean up ElastiCache parameter groups for deprovisioned Redis instances

tools/metrics/pingdumb/pingdumb_test.go
This avoids a race between the pingdumb test's custom DNS server spinning up and the test being run.
See e.g. https://travis-ci.org/alphagov/paas-cf/builds/313015567 for an example build failure that should no longer occur.
Run `ginkgo -untilItFails tools/metrics/pingdumb` before and after the commit.
Anyone but @camelpunch
=> Metrics test: avoid a race

manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/manifest/900-cf-tests.yml
This PR enables Zipkin tracing within Cloud Foundry for use by tenants to monitor distributed requests through their applications.
The tests are separately enabled with a test config flag, so we can make sure the Zipkin functionality is always tested.
Related CF docs:
* https://docs.cloudfoundry.org/adminguide/zipkin_tracing.html
* https://docs.cloudfoundry.org/concepts/http-routing.html#http-headers
The upstream acceptance tests check two test cases:
- if there are no Zipkin trace headers in the request the router will generate new ones and these should be visible in the application request logs
- if there are Zipkin trace headers in the request the router should passed them to the application
1. Update and deploy your CF pipeline from this branch
```
BRANCH=148415719-Enable_zipkin make …
```
=> [#148415719] Enable Zipkin tracing in the router

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
CAPI 1.45.0 (upgraded in response to CVEs) has a bug where the process
exceeds the memory limit due to a leak. This has been fixed in 1.46.0.
Deploy this branch on top of a current master
Verify that all tests pass
Check cloud_controller_clock_ctl.err.log to see any evidence of the process being killed after the deployment.
Not @LeePorte
=> [153510057] Upgrade CAPI to 1.46.0

concourse/pipelines/create-cloudfoundry.yml
We upgrade the compose broker to fix the MongoDB bind/unbind errors. For more details please see https://github.com/alphagov/paas-compose-broker/pull/20.
❗️ We temporarily enabled the MongoDB acceptance tests, but it should be disabled after the review as we still get random 500 errors from the Compose API and the broker and/or the tests doesn't handle this.
1. Please do a code review for https://github.com/alphagov/paas-compose-broker/pull/20 first.
1. Update and run your dev CF pipeline from this branch:
```BRANCH=fix_mongodb_unbind_153170827 make dev pipelines```
1. Wait for the custom acceptance tests to pass (there is a small chance you'll get a 500 when provisioning, if it happens please run the acceptance tests again)
* Merge https://github.com/alphagov/paas-compose-broker/pull/20 …
=> [#153170827] Fix mongodb bind/unbind 

manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/scripts/generate-cf-secrets.rb, manifests/cf-manifest/spec/manifest/base_properties_spec.rb, scripts/lib/uaa_sync_admin_users.rb
We need a UAA client configuration for the paas-admin app to use. It currently has limited permissions, because the app only lists orgs at the moment as proof the authentication works.
Review in conjunction with https://github.com/alphagov/paas-admin/pull/1
There is little danger with this commit as the client is configured with much less scope than will eventually be required. This is on purpose.
Eyeball the code and deploy with passing tests should be enough.
Anyone but me, @chrisfarms @camelpunch or @carolinegreen
=> [#153072577] Add UAA client for paas-admin app

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
This fixes the following:
- https://www.cloudfoundry.org/usn-3498-1/
- https://www.cloudfoundry.org/usn-3496-3/
- https://www.cloudfoundry.org/usn-3489-1/
- https://www.cloudfoundry.org/usn-3504-1/
- https://www.cloudfoundry.org/usn-3496-1/
Most of them specify a minimum version of 1.171.0 except for USN-3504-1
which specifies 1.173.0 - nonetheless I'm taking the latest version
available because it contains other package updates. The release notes are
available here:
- https://github.com/cloudfoundry/cflinuxfs2-release/releases
I've deployed this to a dev environment, which was upgraded from `master` at cff9886e. All of the tests in the pipeline passed. For this reason I think it's sufficient to code review and check that I've chosen a suitable version.
Anyone.
=> [#153696695] Update cflinuxfs2 for Ubuntu CVEs

manifests/cf-manifest/manifest/800-logsearch.yml
For the router logs in Kibana the timestamps displayed in the `Time` column from the `@timestamp` field are misleading and don't match the real time of the request in the `gorouter.timestamp` field.
This commit sets the @timestamp to @gorouter.timestamp and removes @gorouter.timestamp.
1. Deploy your CF from this branch:
```BRANCH=fix_gorouter_timestamp_153369885 paas-dev make dev pipelines```  
2. Run the following search in Kibana:
```@source.component:gorouter AND healthcheck```
Check a message that arrived after the change was deployed
The @raw field looks like this:
```<6>2017-12-20T14:13:57.651426+00:00 10.0.49.101 vcap.gorouter [job=router index=1]  healthcheck.*.dev.cloudpipelineapps.digital - [2017-12-20T14:13:57.643+0000] ...```
You should see the second timestamp …
=> [#153369885] Use gorouter.timestamp as the common timestamp in logsearch

terraform/datadog/aws.tf
We've decided to amend the monitor in order to prevent it from being in
a warning stage constantly. We thought it would be the best thing to do,
due to our upcoming plans of moving to logit.
- Sanity check
=> [support] Amend the EC2 CPU monitor

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/pipelines-cloudfoundry.sh, terraform/datadog/certificates.tf, tools/metrics/README.md, tools/metrics/gauges.go, tools/metrics/gauges_test.go, tools/metrics/main.go, tools/metrics/tlscheck/tls.go
We want a monitor that will alert us if any of our public-facing TLS certs are invalid, or due to expire soon.
`paas-metrics` is extended to accept a list of domains for which you want to check the validity of SSL certificates for, and emit metrics for the number of valid days remaining. This is done via environment variable:
```
TLS_DOMAINS=x.example.com,y.example.com
```
A datadog monitor is created to emit WARNINGs at < 7 days and critical alerts at < 1 day.
The metrics also catch some misconfigurations (like incorrect common name, untrusted CA) by marking the cert as invalid (0days validity).
We want these checks in staging too, so have removed the `ENABLE_METRICS` pipeline flag so that deployment is soley based on the `ENABLE_DATADOG` flag.
* Code review
* Deploy this branch to dev …
=> [#142503647] Monitor TLS Certificate Validity

platform-tests/src/platform/performance/load_test.go
Refactor the tests and..
While waiting for the performance-tests to run I was reminded that I've long
thought that the 300ms threshold was too high to tell us anything useful. To
find out what it should be I took the output of builds over the past year in
production:
for i in {300..687}; do ./bin/fly -t ${DEPLOY_ENV} watch -j create-cloudfoundry/performance-tests -b $i | awk ' "/Latencies/ {print $i,\$0}"; done | tee perf_times.log
I then parsed the output with `awk` against various thresholds to find a value
that wouldn't alert us unnecessarily. Interestingly this build should have
failed with our current threshold, but I can't see why it didn't and I can't
reproduce it when the threshold is lowered:
- https://deployer.cloud.service.gov.uk/teams/main/pipelines/create-cloudfoundry/jobs/per …
=> [SUPPORT] Update performance-tests

terraform/cloudfoundry/policies/elb_access_log_bucket.json.tpl
This commit updates the policy in place for ELB log writing access to S3 in order to remove the false positives recently seen in Trusted Advisor. This will prevent us wasting time chasing false positives.
1. Deploy from this branch in your dev environment
1. Check that your elb-access-log bucket is no longer listed in the Trusted Advisor warnings
1. Check that logs are still being written to the bucket 
Not @LeePorte
=> [#153750019] Update ELB log bucket policy

concourse/pipelines/create-cloudfoundry.yml, terraform/cloudfoundry/outputs.tf
Pass the NAT gateway IPs along to the compose-broker app environment as a comma-separated list.
The broker consumes these IPs in https://github.com/alphagov/paas-compose-broker/pull/22
paas-bootstrap got https://github.com/alphagov/paas-bootstrap/pull/112 but I think this was for consistency (@henrytk can you confirm?)
- Deploy a dev environment with `BRANCH=paas-egres-ips` [sic].
- Once deployed, enable a compose service e.g. `cf enable-service-access compose-redis`
- Create a service instance with e.g. `cf create-service compose-redis tiny myredis`
- Push an app e.g. `cd rails-demo; cf push`
- Bind the service e.g. `cf bind-service rails-blog myredis`
- Restage the app, as the nice message says.
- Get the app's env to retrieve the redis URL: `cf env rails-blog | grep 'uri"'`
- Test that …
=> [#147833555] Pass the platform egress IPs to the Compose broker

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
Apply mitigations for CVE-2017-5754 (aka Meltdown)
Links:
CVE: https://people.canonical.com/~ubuntu-security/cve/2017/CVE-2017-5754.html
USN: https://usn.ubuntu.com/usn/usn-3522-2/
CF announcement: https://www.cloudfoundry.org/usn-3522-2/
Test an upgrade from current master applies cleanly.
Not me.
=> [#154202936] Stemcell bump for CVE-2017-5754 (aka Meltdown)

concourse/pipelines/create-cloudfoundry.yml, scripts/lib/uaa_sync_admin_users.rb, scripts/spec/uaa_sync_admin_users_spec.rb, scripts/sync-admin-users.rb
We want to use the CF API to delete users, not UAA. This is because
deleting them from UAA leaves an orphaned record in the Cloud Controller
database.
The UAA token being used was one from the UAA admin client, using the client
credentials grant. This token is not scoped to perform admin operations
in Cloud Foundry, so we have to get a user's token via the `cf` UAA client
and our CF admin user's name and password.
Also, if an admin has never logged in via SSO they will not exist in Cloud
Foundry, so if we get 404 trying to delete them we should attempt
deletion via UAA, as they may still exist in UAA's database.
* Amend the temporary commit to set up emails. I experienced complications by using the plus sign trick (`your-email+1@gmail.com`), so try to avoid that. Our dev accounts don't …
=> [#129452551] Delete admin users from CF, not UAA

scripts/lib/uaa_sync_admin_users.rb
- Move network access out of constructor into memoized method. Objects are [easier to compose](http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/) if they don't do their work during object graph construction.
- Remove redundant 'self.' (which usually indicates an attribute write)
- Make description of options a bit more accurate, make it a required parameter (we never call it otherwise)
- Make things private where the test permits. Code is easier to change if you can tell at a glance what depends on it.
- Remove redundant comments
- Break some long lines
- Remove redundant parens in a comparison (operators have a lower precedence than other expressions)
- Rename `ua` to `uaa`
- Use `%()` to avoid escaping quotes
Run tests (should have been done by Travis …
=> Refactor uaa_sync_admin_users

terraform/cloudfoundry/cdn_broker.tf, terraform/cloudfoundry/elasticache_broker.tf, terraform/cloudfoundry/logsearch.tf, terraform/cloudfoundry/rds_broker.tf, terraform/globals.tf
To make the ELB traffic more secure we want to remove support for TLSv1 and TLSv1.1.
The ELBSecurityPolicy-TLS-1-2-2017-01 additionally disables the following SSL ciphers:
- ECDHE-ECDSA-AES128-SHA
- ECDHE-ECDSA-AES256-SHA
- ECDHE-RSA-AES128-SHA
- ECDHE-RSA-AES256-SHA
- AES128-SHA
- AES256-SHA
The change effects the following ELBs:
- cf-cc
- cf-uaa
- cf-doppler
- cf-router
- metrics
- logsearch-kibana
- cdn-broker
- elasticache-broker
- rds-broker
- logsearch-ingestor
The following ELBs don't terminate SSL traffic:
- logsearch-es-master
- ssh-proxy
1. Update and run your create-cloudfoundry pipeline successfully:
```
$ BRANCH=elb_require_tls12_126788891 make dev pipelines
```
2. Check if the CF API doesn't accept TLSv1 or TLSv1.1 connections:
```
$ openssl s_client -connect …
```
=> [#126788891] Change default ELB security policy to ELBSecurityPolicy-TLS-1-2-2017-01

manifests/cf-manifest/manifest/050-rds-broker.yml
Pull in the latest rds-broker-boshrelease that contains the improvements around mapping RDS DBInstanceStatuses to server broker operation states.
* https://github.com/alphagov/paas-rds-broker-boshrelease/pull/50
* https://github.com/alphagov/paas-rds-broker/pull/72
* Make sure it deploys nicely
* 🚨 update the TMP commit for the proper boshrelease
=> [#153670955] bump rds-broker-boshrelease for updated DBInstanceStatus/LastOperation mappings

manifests/cf-manifest/manifest/020-cf-properties.yml
Our tenants are hitting their service instance limits. This change increases the limits by applying a doubling function between plans.
Eyeball it. Deploy it if you want. It'll get caught in staging if something is horribly wrong.
Anyone
=> Increase service instances in larger plans

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
Upgrade to the latest version of the ruby buildpack so that tenants can use Ruby 2.5.0
```
git fetch
git checkout upgrade-ruby-buildpack
BRANCH=$(git rev-parse --abbrev-ref HEAD) SELF_UPDATE_PIPELINE=false make dev pipelines
```
Push through dev Concourse.
After it's deployed create and deploy a simple Sinatra app (or something) that uses [Ruby 2.5.0](http://docs.cloudfoundry.org/buildpacks/ruby/index.html#runtime).
Anyone
=> [#154082061] Upgrade Ruby buildpack to provide at least Ruby 2.5.0

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/deployment-kick-off.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/tasks/forget-ses-smtp-access-key.yml, concourse/tasks/kill-instance.yml, concourse/tasks/upload-test-artifacts.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/spec/manifest/base_properties_spec.rb, manifests/cf-manifest/spec/manifest/jobs_spec.rb, manifests/shared/spec/fixtures/terraform/terraform-outputs.yml, platform-tests/example-apps/create-account-holding-page/index.html, platform-tests/example-apps/create-account-holding-page/manifest.yml, platform-tests/example-apps/create-account-holding-page/nginx.conf, platform-tests/src/platform/acceptance/account_management_test.go, terraform/cloudfoundry/outputs.tf, terraform/cloudfoundry/smtp.tf
We want to allow tenants to be able to reset their passwords, but not enable account creation.
See commit messages for details.
* deploy from this branch and make sure all tests pass
* check you can reset a user's password. You may need to verify your email with SES as our dev account is still in the sandbox:
```
aws ses verify-email-identity --email-address your-email@example.com
```
* check all account creation endpoints are blocked. I am not going to tell you what they are, you have to try and hack it. Go on, I dare you.
* check the password rotation works. Related pull request in the team manual: https://github.com/alphagov/paas-team-manual/pull/176
Anyone but me, @chrisfarms, or @46bit
=> [#143584125] Enable password resets

manifests/cf-manifest/stubs/oauth.yml
Logging in with Google only works for PaaS team members and it's not meant for
tenants. We want to change the link text to make it clear it's for internal
use.
1. Create the google-oauth-secrets.yml with the following content (it's empty by default):
```
secrets:
google_oauth_client_id: xxx
google_oauth_client_secret: yyy
```
1. Upload google-oauth-secrets.yml to your state S3 bucket:
```aws s3 cp google-oauth-secrets.yml s3://gds-paas-${DEPLOY_ENV}-state/google-oauth-secrets.yml```
1. Update your CF deployment from this branch
```NEW_ACCOUNT_EMAIL_ADDRESS=your.name@digital.cabinet-office.gov.uk SELF_UPDATE_PIPELINE=false BRANCH=change_google_login_link_153670556 make dev pipelines```
1. Go to https://login.${DEPLOY_ENV}.dev.cloudpipeline.digital/login and validate if the link text has …
=> [#153670556] Change Google Login link text

concourse/pipelines/create-cloudfoundry.yml
We tweaked some CSS in the Billing API output in paas-usage-event-collector. This bumps the version of the paas-usage-event-collector that is pulled in.
⚠️ Merge [the paas-usage-events-collector PR](https://github.com/alphagov/paas-usage-events-collector/pull/8) first!
⚠️ The version tag has been guessed. Ensure it is correct before merging!
This change does not change any logic in the event collection or billing api, and code review should be enough.
Not @chrisfarms or @keymon
=> [#154240758] Bump paas-usage-event-collector to v0.6.0

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml
Use custom loggregator BOSH release
We added a drain script to the loggregator_trafficcontroller job to make sure
traffic controller is stopped before the consul-agent. Previously when the VM
was stopped we got CF-StatsUnavailable from the CF API which was caused by the
following traffic controller errors:
```
2018/01/23 15:13:28 Could not get app information: [Get
https://cloud-controller-ng.service.cf.internal:9023/internal/v4/log_access/6ba02750-f073-444f-ba73-ee3cf4a02ec6:
dial tcp: lookup cloud-controller-ng.service.cf.internal on 10.0.0.2:53: no such host
```
We saw these errors when the consul-agent was stopped before the
trafficcontroller service and stopped providing DNS resolution.
❗️ This PR contains a temporary commit with the dev build of the loggregator-release. Please …
=> [#153561855] Add custom loggregator release

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/scripts/generate-cf-certs.sh
[#149928858 Deal with internal TLS certs expiring before March] https://www.pivotaltracker.com/n/projects/1275640/stories/149928858
What?
----
We want to be able to rotate the CF internal certificates in a automated
fashion, in a similar way we rotate other CF credentials.
Some public facing certs, like app or sys domains, won't be rotated with
this operation.
How to review?
-------
- Code review.  See commit for implementation details
- Rotate the certs:
1. Run the job rotate-cf-internal-certs
2. rerun the deploy script. There should be no downtime in the apis but a pair of expected `CF-StatsUnavailable` (fixed by https://github.com/alphagov/paas-cf/pull/1183)
3. Check you can use the platform, or run acceptance tests.
- Delete old certs:
1. run the job delete-old-cf-internal-certs
2. …
=> [#149928858] Implement logic to rotate CF internal certs

terraform/datadog/certificates.tf
We have been getting 'no data' alerts in prod for this monitor.  These
metrics are only collected every hour, which seems to be too sparse for
Datadog to consider it a 'full window' of data[1]. Also, Datadog advise
the 'no data' period be at least twice the window being evaluated.
[1] https://help.datadoghq.com/hc/en-us/articles/115002630843?input_string=no_data+alerts
Using the Datadog console. Make these changes manually and confirm the monitor turns healthy (should take 1 minute, as Datadog refreshes the monitor every minute).
Preferably @camelpunch, as he has context. Failing that, anybody else.
=> [#146463199] Do not require full window of CDN TLS metrics

concourse/pipelines/deployment-kick-off.yml
A Couple of tweaks to this pipeline:
* Pin it to master branch of paas-cf - for consistency with the autodelete, and so that it resumes RDS instances, even if the dev branch no longer exists.
* Trigger the job earlier - since we increased the splay, this hasn't been completing in time to be used for some people.
Not me.
=> [#154764726] Improve deployment kickoff pipeline

manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/spec/manifest/uaa_spec.rb, manifests/cf-manifest/spec/support/manifest_helpers.rb
https://www.pivotaltracker.com/story/show/149928858
What?
-----
Follow up of https://github.com/alphagov/paas-cf/pull/1184
We made a typo in the name of the key when pulling the old jwt
signing key for UAA during the certificate rotation.
The name should be <cert-name> + _old + _key, as per [1].
The issue would be shadowed by spruce, as we pull a default value
if the key is not defined. We added a test for this specific
case in the manifest.
[1] https://github.com/alphagov/paas-cf/blob/0567d631f09a8b352fc8629375a81731f523069a/concourse/pipelines/create-cloudfoundry.yml#L1304-L1313
How to review?
----------
Code review, the tests in travis shall run.
Who?
----
Anyone but @keymon, likely @alext
=> [#149928858] Fix wrong name for old jwt signing key

manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/manifest/800-logsearch.yml, manifests/cf-manifest/spec/manifest/router_spec.rb
This PR updates the logsearch filters we are using to be in line with the upstream release of logsearch. It also removes a no longer required filter.
In Dev
1. Code review and run https://github.com/alphagov/paas-bootstrap/pull/127
```BRANCH=upgrade_syslog_release_134014357 make dev deployer-concourse pipelines```
1. Code review  #https://github.com/alphagov/paas-logsearch-for-cloudfoundry/pull/3
1. Code review and run this branch
```BRANCH=upgrade_syslog_release_134014357 make dev pipelines```
1. Ensure logs are still being delivered to the ELK stack
1. Merge https://github.com/alphagov/paas-logsearch-for-cloudfoundry/pull/3 and update the temp commit in this PR with the final build created in CI
1. Merge this PR and run the create-cloudfoundry pipeline 
1. Merge …
=> [#134014357] Upgrade syslog release 

concourse/pipelines/create-cloudfoundry.yml
Remove FIXMEs **when** the paas-billing changes have been deployed to production.
1. Code review.
1. Confirm that #1195 has been deployed to production and the app is now available at https://paas-billing.cloudapps.digital/
@bandesz reviewed the original PRs, but anyone else can review this because it's relatively simple.
=> [#154524416] Remove FIXMEs for paas-billing rename

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
In order to secure ourselves against the [CVE-2018-1192](https://www.cloudfoundry.org/blog/cve-2018-1192/) we need to
upgrade UAA release to a version containing the fix.
The notes under the CVE suggest that it would be version 52.7 which is
the closest to the one we're currently running.
- Check if the chosen version does fix the CVE
- Check if the pipeline along with tests run (mine ~~is still running~~ has succeeded)
=> [#154835629] Bump UAA release version to 52.7

manifests/cf-manifest/manifest/020-cf-properties.yml, manifests/cf-manifest/spec/manifest/router_spec.rb
We disabled sending the gorouter access logs to syslog as we planned to enable Blackbox which would pick up the access logs from files. At this moment the access logs are not sent to Logsearch at all.
This reverts commit b3b25e4e9592f96775dc9cd7fbb109d51005f84c.
By enabling blackbox some logs written by the logger command are written to the
disk six times wouch could cause disk fillup and adverse effects on CPU and
disk usage.
Blackbox duplicates the logs handled by the logger command as usually the job
scripts write the logs both to a file and syslog. See [2].
In the latest syslog release notes [1] they only able to partially solve the
issue, that these duplicated logs are not sent to Logsearch but still written
to the disk duplicated.
We decided to not enable blackbox …
=> [#134014357] Revert "Stop sending gorouter logs to syslog"

manifests/cf-manifest/manifest/070-elasticache-broker.yml
We want to enable backups of Elasticache Redis instances.
Review https://github.com/alphagov/paas-elasticache-broker/pull/9 and then https://github.com/alphagov/paas-elasticache-broker-boshrelease/pull/5 first. The [final release of the Bosh release](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/elasticache-broker-release) will provide the manifest details to replace the temporary commit on this branch. 
* deploy
* check custom acceptance tests pass
We've created a tiny Redis instance already, so you can check with our whether a backup has been created. If you want to do it yourself:
* `cf enable-service-access redis`
* create a tiny Redis instance
* [wait for 1 day](http://fabquote.co/every-day-you-wait-is-one-day-youll-never-get-back-quote/)
* check a backup is …
=> [#154332167] Enable redis backups

manifests/cf-manifest/env-specific/cf-prod.yml
DataDog is constantly warning us about the rep memory being on the edge.
By going with the "tradition", we're increasing it by 3 again to provide
more power to the platform.
- Make sure the number of cells is sane
- Make sure it is raised by 3
- Make sure it complies with ADR021
=> [support] Increase number of cells for Production

concourse/pipelines/create-cloudfoundry.yml
What?
-----
This version of the broker to returns the multiple
endpoints (aka portals) in the credentials object
returned when binding, so that the app can use the service
with high availability.
In this version the response format for the credentials changes,
so that:
* remove `host` and `port`
* return a `hosts` with a list of `host:port`
* mongodb: `uri` returns the mongodb with multiple endpoints[1]
* elasticsearch: New `uris` as a list of urls with all the endpoints.
[1] https://docs.mongodb.com/manual/reference/connection-string/
Dependencies
-----------
This PR must be merged:
* After the implementation is merged  https://github.com/alphagov/paas-compose-broker/pull/23
* Once a new version is created in the build pipeline
* Once we have notified the tenants about the API changes …
=> [#147258015] Upgrade compose-broker version to 0.14.0

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml
The Makefile is the source of truth for defining what AWS region we are
targetting. We should not hardcode the region anywhere else, unless it
is because something needs to operate across regions. This was
discovered when investigating running the platform in Ireland and London
simultaneously.
Deploy from this branch. Run the pipeline.
Anyone but me or @samcrang
=> [#154328623] Stop hardcoding AWS region

concourse/pipelines/create-cloudfoundry.yml, platform-tests/src/platform/availability/helpers/concourse.go
At the moment, we have two places where some post-deploy tasks are run.
One is sort of inline with the cf-deploy and the other has a dedicated
separate task. We think this will get confusing as to where any future
tasks would come in.
Here, we're moving them back into cf-deploy as it requires less
refactoring to achieve what we need, which is running the tests in the
same time as cf-deploy and post-deploy tasks.
- Run the pipelines and expect the `cf-deploy` task to succeed
- Make sure the tasks moved have been executed
- Make sure the tasks moved are in the right place
I'd like it to be someone from the initial pair that implemented a new task. /cc @chrisfarms @henrytk 
But I imagine anyone could pick that up.
=> [#154760148] Unify post-deploy tasks

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
Due to [USN-3534], we'd like to upgrade our stemcell to the version that
fixes the vulnerabilities. The USN info mention it to be version 3468.19
which happens to be the closest one to ours.
[USN-3534]: https://www.cloudfoundry.org/blog/usn-3534-1/
- Sanity check - validate the version used is sufficient
- Run `create-cloudfoundry` pipeline (running mine at the moment)
- Expect successes
=> [#154879166] Bump stemcell version to 3468.19

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
Due to [USN-3534], we'd like to upgrade our cflinuxfs2 to the version
that fixes the vulnerabilities. The USN info mention it to be version
1.181.0 which happens to be the closest one to ours.
[USN-3534]: https://www.cloudfoundry.org/blog/usn-3534-1/
- Sanity check - validate the version used is sufficient
- See if I didn't miss any places for `cflinuxfs2` nor `stemcell`
- Run `create-cloudfoundry` pipeline (running mine at the moment)
- Expect successes
=> [#154879166] Bump cflinuxfs2 version to 1.181.0

manifests/cf-manifest/manifest/070-elasticache-broker.yml
We enabled automated backups in
https://github.com/alphagov/paas-cf/pull/1199, so this entry in the
description is no longer correct.
Verify the rationale makes sense.
Not me.
=> [#154332167] Remove 'no backups' from Redis plan description.

manifests/cf-manifest/cloud-config/030-logsearch.yml
This PR changes the instance type used by Elasticsearch to a compute
optimised type as we are currently hitting the CPU limits of the general
purpose instance type.
Code review and deploy this branch to dev
Not @LeePorte
=> [Support] Change ES instance type to compute optimised

concourse/pipelines/create-cloudfoundry.yml
These 2 should be pinned on the output of post-deploy and the 2
availability tests. Otherwise they will start running even if the
availability tests fail.
These look to have been erroneously removed in the refactoring in
3344249
* Verify this makes sense.
* Push the pipeline to a concourse and verify the pinning looks correct.
Not me.
=> Fix pipeline pinning for acceptance tests.

concourse/pipelines/create-cloudfoundry.yml, tools/metrics/Gopkg.toml
In 8e12c13e, we had to workaround an issue in the go-datadog-api that the terraform datadog provider uses. This PR reverts that change and upgrades the go-datadog-api across the board.
- Use our latest terraform docker image in concourse, which uses a recent datadog terraform provider with a recent go-datadog-api
- Revert 8e12c13e, which applied the workaround for datadog in terraform that has now been [fixed upstream](https://github.com/zorkian/go-datadog-api/issues/56).
- As a bonus, upgrade tools/metrics go-datadog-api to the same version, 2.7 (optional - feel free to not merge this)
- Check that nothing untoward happens when deploying the pipeline with/without Datadog. Note the diff moves from a [do stanza](http://concourse.ci/single-page.html#do-step) back into a regular list of …
=> Undo require full window workaround

manifests/cf-manifest/manifest/800-logsearch.yml
The parsers are set up with static IP addresses. This allocates another
one for the newly added instances.
Code review
Not @LeePorte
=> [SUPPORT] Add an additional IP address for each new parser

terraform/cloudfoundry/dns-records.tf, terraform/cloudfront/cloudfront_distribution/distribution.tf, terraform/cloudfront/cloudfront_redirect/distribution.tf
Now that we have a system domain ELB, we can switch the DNS over (the wildcard DNS is already in place).
~~⚠️ make sure https://github.com/alphagov/paas-cf/pull/1217 has at least started deploying to prod before merging.~~ Done.
You must have an existing deployment that includes https://github.com/alphagov/paas-cf/commit/e664eaffd27d27bdfabfac9b649d78ea0fdbbc83
It would also be useful to have CloudFront Distributions in place for the product page and tech docs.
⚠️ the Terraform needs to be run manually _before_ the deployment happens, to ensure the system domain apex DNS record remains in place. This is true for all environments, so you will have to sit and nurse this through staging and prod.
* Use the master branch to deploy the CloudFront Distributions. This will set up DNS. 
* Check …
=> [#154959067] Remove UAA, Product Page, and Tech Docs DNS

concourse/pipelines/create-cloudfoundry.yml
Update the Compose broker to allow tenants to restore backups as new service instances for Elasticsearch and MongoDB.
We didn't add tests for restoring Redis as we will remove it from the broker in the near future.
* Review https://github.com/alphagov/paas-compose-broker/pull/24
* Check if the integration tests on the build CI pass
Review and merge https://github.com/alphagov/paas-compose-broker/pull/24 first.
❗️ Replace the temporary commit in this branch to point the paas-compose-broker repository to the latest release tag (similarly to what was done in https://github.com/alphagov/paas-cf/commit/0e401ba0.)
Not @LeePorte, @46bit or @bandesz
=> [#154332832] Upgrade compose broker

Makefile
We now have an ELB unfortunately named `<env>-cf-router-system-domain`
(your're welcome), so, due to the limit of 32 characters in an ELB name,
we have to limit this variable to 8 characters.
`DEPLOY_ENV=12345678 make check-env-vars` should exit zero.
`DEPLOY_ENV=123456789 make check-env-vars` should exit non-zero.
Anyone but me.
=> [#154959067] Lower `DEPLOY_ENV` maximum length to 8

platform-tests/src/platform/availability/api/api_test.go
Handle CF-StatsUnavailable errors as warning in the api-availability tests
We investigated the remaining CF-StatsUnavailable errors and decided that it
isn't worth to fix them. We don't want these errors to make the pipeline fail,
so we handle them as warnings. Too many warnings will still make the pipeline
fail.
These errors usually happen in a really small time window (<1s)
We found two causes:
* When the Consul servers are updated the clients can fail to resolve some DNS
requests when the leader is restarted. This could be solved by handling retry
in the Consul agents. See [1] and [2]. We would need to upgrade to Consul 1.x
which would need a lot of work (there is no BOSH release for it) and eventually
we plan to remove it completely.
* BBS is running with a hot-standby and at any …
=> [#154808699] Investigate/fix CF-StatsUnavailable error

concourse/pipelines/create-cloudfoundry.yml
[#154329640 Pricing Calculator: Implement price estimation via billing API](https://www.pivotaltracker.com/story/show/154329640)
What?
-----
Bump version of paas-billing to v0.9.0
We want to deploy the pricing simulation feature implemented in alphagov/paas-billing#11
How to review?
------------
- Review and merge alphagov/paas-billing#11 first
- ~~Once our CI tagged a new version (expected to be v0.8.0), remove the WIP commit in this branch.~~
Who?
---
Anyone but @dcarley or @keymon
=> [#154329640] paas-billing v0.9.0 add pricing estimation endpoint

concourse/pipelines/create-cloudfoundry.yml, platform-tests/src/platform/acceptance/plain_http_test.go
Test our new behaviour that we don't listen on port 80 for the system domain. See commit messages for more details.
N.B. for @samcrang: I've ignored the situation where these are run from our office (behind its HTTP proxy.) The connection being closed instead of not accepted could happen at various points, so it wouldn't guarantee that HTTP requests weren't sent over the wire.
I have successfully run these custom acceptance tests in my dev environment and think that code review will suffice.
Not @46bit
=> [#154959067] System domain should not be listening on port 80

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/800-logsearch.yml, terraform/datadog/queue.tf
We want to monitor the queue length in Redis as the ingestor will start to drop messages if the queue reaches 1 million items [1]. We want to be alerted before this happens and manually intervene if necessary.
[1] https://github.com/logsearch/logsearch-boshrelease/blob/v203.0.0/jobs/ingestor_syslog/spec#L61-L63
❗️ This PR contains a temporary commit, please update the `datadog-for-cloudfoundry` Bosh release params after 
1. Deploy your CF from this branch and enable Datadog in `paas-bootstrap` and `paas-cf`:
```
paas-bootstrap$ make dev deployer-concourse pipelines DEPLOY_ENV=hector BRANCH=$(git rev-parse --abbrev-ref HEAD)  SELF_UPDATE_PIPELINE=false ENABLE_DATADOG=true 
paas-cf$ make dev pipelines BRANCH=$(git rev-parse --abbrev-ref HEAD)  SELF_UPDATE_PIPELINE=false DEPLOY_ENV=hector …
```
=> [#155178552] Monitor Logsearch Redis queue length

terraform/datadog/queue.tf
So that the person viewing the alert can more easily discover how to
respond to it.
This is a minor tweak I noticed while approving the story and it didn't seem worth sending it all the way back to doing.
It takes ages to deploy DataDog to a dev environment so I haven't tested this.
I think that eyeballing the change to see if the formatting is correct should be sufficient. You can compare it to one of the other alerts that also use this format.
Anyone.
=> [#155178552] Link to logsearch queue alert in team manual

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/040-graphite.yml, manifests/cf-manifest/manifest/800-logsearch.yml
The `datadog-agent-forwarder` job is failing to start in staging with the
following error:
Couldn't initialize logging: [Errno 13] Permission denied: '/var/vcap/data/packages/datadog-agent/4ed37e76994196bbc48fbd89ba2d9ffdf9ab7bf3/agent/datadog.conf'
It feels like this could be the same problem we saw with umask changes for
logsearch in 94a70d11. I tried 3541.4, which includes some umask fixes,
but that didn't make any difference.
In order to unblock the pipelines in the meantime we're going to
downgrade all VMs to the latest version of the previous series. We'll
investigate a proper fix for upgrading series later.
I've tested this in a dev environment. I don't think you need to repeat this. You should check that I've used the right stemcell from …
=> [#154769249] Downgrade stemcell to 3468 series

terraform/datadog/router.tf
This sets up a gorouter datadog monitor with a warning threshold of
400ms and a critical threshold set at 800ms. These values have been
derived from reviewing the data held in datadog for the past month. If
we had them implemented during the load testing session then they would
have fired.
Deploy from this branch with `ENABLE_DATADOG=true` and check the monitors for your deployment in datadog.
Not @LeePorte
=> [#120268519] Add gorouter latency monitor to datadog

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/scripts/bosh_login.sh, manifests/cf-manifest/manifest/000-base-cf-deployment.yml
We have migrated to using BOSH CLI v2 commands. This includes updates to use the latest binaries in bosh-cli-v2 docker images.
Changes:
* We extract the bosh_CA.crt file as a separate resource so we can use it easily for `bosh login` commands easily. This is done in bootstrap already but we duplicate it here to avoid requiring running create-bosh-concourse.
* Don't generate director_uuid into the deployment manifest (the v2 cli doesn't need it)
⚠️ Please ensure that the `bosh-cli-v2` docker images referenced are using the SHA not the tag before merging.
⚠️ Please ensure that the paas-bootstrap is merged and applied to staging/production environments before merging.
* Try to deploy from master.
* Try from from [paas-bootstrap](https://github.com/alphagov/paas-bootstrap/pull/140)
* Try to …
=> [#154437854] Use Bosh CLI v2

terraform/datadog/queue.tf
We accidentally averaged over all Redis queues which would cause us not to be
alerted properly for individual Redis issues.
I also changed avg to max which shouldn't matter, but would have been safer in the first place.
Code review.
I don't think there is value in enabling Datadog in a dev env just for this. I got the fixed query from Datadog directly.
Not me.
=> [#15517855] Change Redis queue length alert to check hosts individually.

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/cloud-config/030-logsearch.yml, manifests/cf-manifest/env-specific/cf-default.yml, manifests/cf-manifest/env-specific/cf-prod.yml, manifests/cf-manifest/env-specific/cf-staging.yml
* Use `c4.2xlarge` AWS instances for production and staging;
* Use `m4.large` AWS instances for dev;
* Redeploy Elasticsearch faster.
See commit messages for details.
Suggested:
* Consider our rationale for using larger instances;
* Critique our choice of instances;
* Critique our faster deployment process.
We've tested this in a dev environment. We suggest pausing prod before this is deployed, so as to check that staging Kibana looks good before rolling out to prod.
Not @46bit nor @dcarley. I'd suggest @henrytk and @LeePorte as they have some knowledge of this problem but weren't involved in choosing a solution.
=> [#155367490] Provide more RAM for production ELK Elasticsearch

manifests/cf-manifest/manifest/010-cf-jobs.yml
These recently changed in diego-release v1.33.0 and later which caused our BBS
check to fail with certificate errors because it couldn't do mutual TLS against
BBS:
- cloudfoundry/diego-release@c9ff9ed3b9ea40b14b1b46b3ae3c985183dddee7
The defaults are hardcoded in alphagov/paas-datadog-bbs-integration but
that's difficult to update because:
- the tests are currently failing because of unpinned dependencies
- it requires three PRs to update the submodule and releases
So I'm fixing it here for the moment. I've set them as properties of the
job, rather than the VM, just in case the `bbs` key overrides something
in the `bbs` job. I've had to move the `url` because otherwise the job
properties overwrite it.
If you currently have DataDog enabled in your dev environment then you can deploy this …
=> [#154769249] Update cfdot cert paths for BBS health check

concourse/pipelines/create-cloudfoundry.yml
This PR updates the tag used for paas-billing to the latest version.
Update the temp commit with the tag value created by CI after merging https://github.com/alphagov/paas-billing/pull/14
Not @camelpunch or @LeePorte
=> [#154395415] Update paas-billing release tag

terraform/datadog/router.tf
This commit increases the thresholds on the gorouter monitor in order to
avoid false positives.
The inital monor values were set too low and as a result were triggering
the alert in a flapping manner. This is not useful for us as a team.
Code review should suffice.
If you wish you can deploy from this branch with `ENABLE_DATADOG=true`
Not @LeePorte
=> [#120268519] Monitoring gorouter latency

terraform/datadog/router.tf
Or it fails to apply with this annoying error that we haven't seen for a while:
* datadog_monitor.gorouter_latency: error updating monitor: API error 400 Bad Request: {"errors":["Critical threshold (1500.0) does not match that used in the query (2500.0)."]}
Code review.
Anyone.
=> [#120268519] Make gorouter latency query match thresholds

manifests/cf-manifest/manifest/020-cf-properties.yml
Add a 2xlarge quota definition, because Notify want to scale up, and are restricted by xlarge.
Code review, possibly involving a deployment to dev. It should be pretty safe, though.
Anyone by @camelpunch
=> Add a 2xlarge quota definition

concourse/pipelines/create-cloudfoundry.yml
What?
----
From PR alphagov/paas-compose-scraper#3, it does not pin the minor version
of python runtime
How to review
-------------
code review, merge after the alphagov/paas-compose-scraper#3 and tagging.
Who?
---
Not me
=> [#154769249] Use paas-compose-scrapper v0.1.2

manifests/cf-manifest/env-specific/cf-staging.yml
Staging is [hovering around the 75%](https://app.datadoghq.com/metric/explorer?live=false&page=0&is_auto=false&from_ts=1514764800000&to_ts=1519948799999&tile_size=m&exp_metric=system.disk.in_use&exp_scope=deploy_env%3Astaging%2Cbosh-job%3Aelasticsearch_master%2Cdevice%3A%2Fdev%2Fxvdf1&exp_group=bosh-index&exp_agg=avg&exp_row_type=metric) mark at the moment, and has been for
nearly a month. Adding another 50% will give us some headroom until we
get to migrate away.
Code review. Check my rationale makes sense.
Not me.
=> [Support] Embiggen staging elasticsearch disks.

concourse/scripts/kibana_set_utc.rb, concourse/scripts/kibana_set_utc_test.go, manifests/cf-manifest/manifest/800-logsearch.yml
[#145336911 Update logsearch and logstash](https://www.pivotaltracker.com/story/show/145336911)
What?
-----
We want to upgrade logsearch to move the ELK stack to at least v5.0.
We decided to go for [v205. of logsearch](https://github.com/cloudfoundry-community/logsearch-boshrelease/releases/tag/v205.0.1),
which is the closest version that upgrades ELK to 5.
The corresponding [release for logsearch-for-cloudfoundry is v203](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/releases/tag/v203.0.0).
See commits for details about the changes required
Dependencies
------------
1. Review and merge first https://github.com/alphagov/paas-logsearch-for-cloudfoundry/pull/5
2. Once merged, wait for a new final release to be generated and update the corresponding commit in this …
=> [#145336911]  Update logsearch to v205 and logsearch-for-cf to v203

scripts/create-user.sh
Making this require a CR makes it consistent with our uses of read in
other places.
* Login to a dev environment
* create a new org with `./scripts/create-user.sh -o foo -e foo@example.com --no-email`
* Verify that the new-org prompt behaves as expected
Not me.
=> [Support] Require CR in create-user.sh org prompt

manifests/cf-manifest/manifest/800-logsearch.yml, manifests/cf-manifest/spec/manifest/logsearch_spec.rb
The parsers were accidentally both pointed at the first queue during the
recent upgrade (see https://github.com/alphagov/paas-cf/pull/1255/files#r172181513), leaving nothing processing the second queue.
Code review is probably enough. Compare with the diff from the above PR
Not me.
=> [#145336911] Fix logsearch parsing.

concourse/pipelines/create-cloudfoundry.yml
Bumps paas-billing version for the associated changes:
https://github.com/alphagov/paas-billing/pull/17
* Deploy from this branch with `ENABLE_BILLING_APP=true` and `SELF_UPDATE_PIPELINE=false`
* Ensure paas-billing is still alive and kicking
* Merge https://github.com/alphagov/paas-billing/pull/17
* Replace the [TMP] commit with the proper version from build ci
Not @chrisfarms or @dcarley
=> [#155130407] Replace go-bindata in paas-billing

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/deployment-kick-off.yml, concourse/pipelines/destroy-cloudfoundry.yml
https://www.pivotaltracker.com/story/show/155462110
What?
----
We were using the bosh-cli docker image in some places where it was not
needed as we did not use the bosh cli.
In this commit we remove such dependency. Alpine is enough.
How to review?
------------
Code review. You can try to run the job.
Who?
---
=> [#155462110] Use alpine instead of bosh-cli where needed

manifests/cf-manifest/cloud-config/020-cf-vm-types.yml, manifests/cf-manifest/env-specific/cf-default.yml, manifests/cf-manifest/env-specific/cf-prod.yml, manifests/cf-manifest/env-specific/cf-staging.yml, manifests/cf-manifest/spec/cloud-config/env_spec.rb
They are [not presently keeping up](https://app.datadoghq.com/notebook/21812/Logsearch%20metrics) with the volume of incoming messages.
This is partly due to issues with the logging stack not being balanced,
meaning that often one of the queues is empty with all incoming messages
going to the other queue.
We believe that the underlying cause for this unbalance is down to how
the ingestors are load-ballanced. Because all the VMs use persistent TCP
connections to the ingestors via the ELB, when one of the ingestors is
restarted this results in all the VMs connecting to the other one, and
therefore all log messages ending up in one queue.
A longer term fix would be to restructure things so that we use a single
shared queue (possibly using AWS Elasticache), however given we hope to
have …
=> [Support] Enlarge the parser VMs in staging and prod.

manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/spec/manifest/instance_group_spec.rb
[#155623416 Restructure/rename jobs to match cf-deployment](https://www.pivotaltracker.com/story/show/155623416)
Remove and re-order VMs.
Review in conjunction with https://github.com/alphagov/paas-cf/pull/1263. This branch should be deployed on top that one. We need:
* code review
* check app and API availability tests pass.
* check acceptance tests et cetera pass
This pull request involves removing the global route-emitter while we have cell-local route emitters in place, so we are mainly concerned about availability of routes during the deployment.
* review and merge https://github.com/alphagov/paas-cf/pull/1263 . **Must be deployed in Prod before the rest**
* review and merge https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/23 and replace the temporary commit …
=> [#155623416] Restructure/rename instance_groups to match cf-deployment (PR 2 of 4)

manifests/cf-manifest/manifest/010-cf-jobs.yml, manifests/cf-manifest/manifest/020-cf-properties.yml
[#155623416 Restructure/rename jobs to match cf-deployment](https://www.pivotaltracker.com/story/show/155623416)
What?
-----
We want to refactor our manifest to be based on the upstream [cf-deployment](https://github.com/cloudfoundry/cf-deployment).
In pr https://github.com/alphagov/paas-cf/pull/1263 we did several changes, but we decided to delay this change to a specific separated PR, as it is an important change in the architecture and there is some risk when running route_emitter in global and local_mode.
In this PR we move the `route_emitter` to the `diego-cell` and we run it at the same time in global mode in the `route_emitter` instance group and in local mode in the cells.
We had to split this change in two different PRs, as moving services between instance groups in one go caused …
=> [#155623416] Restructure/rename instance_groups to match cf-deployment - move route-emitter (PR 3 of 4)

concourse/pipelines/create-cloudfoundry.yml
We update the paas-billing app, see https://github.com/alphagov/paas-billing/pull/20 for details.
❗️ This PR contains a temporary commit, please replace it with the final release tag before merging.
1. Deploy the paas-billing app from this branch
```BRANCH=paas_billing_vat_rates_155326674 ENABLE_BILLING_APP=true SELF_UPDATE_PIPELINE=false make dev pipelines```
1. Test the price updater script:
```COLLECTOR_URL=https://paas-billing.${DEPLOY_ENV}.dev.cloudpipelineapps.digital ./push-pricing.sh update pricing_plans.json pricing_plan_components.json```
It should not return with an error and it should populate the pricing_plan and pricing_plan_components tables.
Not me.
=> [155326674] Add VAT rates to the paas-billing app

README.md
The website has moved to a new domain after the old domain as hijacked:
- https://www.cloudfoundry.org/blog/cve-2018-1227/
Check that the domain matches the advisory and that I haven't missed any occurrences.
Anyone.
=> [support] Replace concourse.ci domain in docs

terraform/datadog/compose_scraper.tf
This is constantly warning at the moment. We're attempting to increase
the size of our Compose cluster, but we don't know how long it will take
to go through procurement.
Increase the critical threshold so that it still tells us when we've
reached a level that makes it unlikely we'll be able to provision any
more service instances. This is based behaviour that we observed last
week. Remove the warning threshold because we no longer have enough
headroom for this to be useful.
This commit should be reverted when the cluster has been resized.
I haven't tested this in dev because of the amount it time it takes to `ENABLE_DATADOG`. I don't think that you should either. Code review should be sufficient and we'll fix it if something goes terribly wrong in prod.
Anyone.
=> [support] Temporarily increase threshold for Compose memory

manifests/cf-manifest/stubs/oauth.yml
Previously we moved all global properties to the specific jobs. We tested everything on dev but we missed the oauth properties as those are only added in staging and prod.
❗️ we have to set up a new staging Google Ouath client before we merge this.
Code review only.
I ran the following command and validated from the generated manifest, that the oauth config is properly added to the uaa job.
```
BRANCH=move_properties_to_specific_jobs_155463715_fix_oauth SELF_UPDATE_PIPELINE=false NEW_ACCOUNT_EMAIL_ADDRESS=andras.ferencz-szabo@digital.cabinet-office.gov.uk make dev pipelines
```
Not me or @keymon
=> [#155463715] Move UAA oauth properties to the UAA job

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, terraform/datadog/aws.tf
What?
-----
Fix some issues caused in datadog after renaming the instance_groups:
1. For the EC2 metrics monitors, after renaming the `instance_group` the VM did not get recreated and the AWS tag `job:` is still the old one. To solve it we use the tag `bosh-job:*` emitted by the datadog agent, as it will be always updated .
2. The CC worker includes the `instance_group` in the process. We need to use a new process search include the job name from https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/24
How to review
-------------
- Review first https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/24, wait for a new build in https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/datadog-for-cloudfoundry-release and update the latest …
=> [#155936773] Use bosh-job instead of job in datadog queries

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/manifest/010-cf-jobs.yml
Change billing app domain to billing.${system_domain}.
We want to have a "production" domain for the paas-billing app.
We don't recommend that our tenants use *.cloudapps.digital domains for live services and so we should follow our own advice.
Notes:
* the old route has to be deleted separately as `cf push` doesn't remove it. I automated this in the deploy task
* at the moment we can't use blue-green deploy for the API as the app also runs the collectors which should not run in parallel multiple times. There will be a follow up story to have separate commands in the billing app.
1. Deploy your CF from this branch:
```BRANCH=paas_billing_domain_154842336 SELF_UPDATE_PIPELINE=false ENABLE_BILLING_APP=true make dev pipelines```
1. Go e.g. to …
=> [#154842336] Set up production domain for the billing app

manifests/cf-manifest/manifest/070-elasticache-broker.yml, platform-tests/src/platform/acceptance/redis_service_test.go
We want to introduce unclustered plans as some client libraries used by the
tenants are not compatible with clustered setups.
See https://github.com/alphagov/paas-elasticache-broker/pull/12 for details.
1. Code review for the following PRs:
* https://github.com/alphagov/paas-elasticache-broker/pull/12
* https://github.com/alphagov/paas-elasticache-broker-boshrelease/pull/8
1. Deploy your CF from this branch:
```BRANCH=tiny_unclustered_plan_155894002 make dev pipelines```
1. You have to enable all new redis plans:
```cf enable-service-access redis -o admin```
1. You can create the unclustered plan with:
```cf create-service redis tiny-unclustered redis-test-unclustered```
Not me.
=> [#155894002] Allow to create Redis clusters with cluster mode enabled

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/spec/manifest/instance_group_spec.rb
This is the first step in a three-part deployment to move Cloud Controller behind GoRouter.
* deploy on top of master.
* confirm the route is set up. One way of doing this:
* get an IP address for a system domain ELB IP:
```
dig "irrelevant-subdomain-due-to-dns-wildcard.${DEPLOY_ENV}.dev.cloudpipeline.digital"
```
* use `curl` to prove the route is set up by resolving the hostname of the API to the IP you just fetched:
```
curl \
--resolve "api.${DEPLOY_ENV}.dev.cloudpipeline.digital:443:52.209.9.54" \
"https://api.${DEPLOY_ENV}.dev.cloudpipeline.digital/v2/info"
```
* make sure all tests pass, particularly availability tests.
A lot of properties for the api instance group have been removed, so you may want to check I didn't bin anything important :)
Anyone but me
=> [#155856825] Register routes for Cloud Controller

manifests/cf-manifest/manifest/050-rds-broker.yml, terraform/prod.vpc_peering.json
We added a cron job process to the RDS broker to clean up old RDS snapshots. We only delete manual snapshots which have a matching `Broker Name` AWS tag.
We define a separate job for it so it can run as a separate process.
The cron process will only run on the first instance.
Related PRs:
* https://github.com/alphagov/paas-rds-broker-boshrelease/pull/53
* https://github.com/alphagov/paas-rds-broker/pull/73
❗️ This PR contains a temporary commit which needs to replaced when the final rds-broker BOSH release was built.
1. If you want to see the cron job working you need to add a temporary commit to change the rds-broker-cron config to run every minute and delete some RDS snapshots. Alternatively you can change this manually on the VM when testing.
```diff
--- …
```
=> [#155625342] Cleanup final RDS snapshots

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, terraform/cloudfoundry/dns-records.tf
This reverts https://github.com/alphagov/paas-cf/pull/1287. 
We switched the CF API endpoint over to the cf_router_system_domain ELB but we overlooked the idle timeout which is much lower (19s) than it was on the API ELB (300s). The lower idle timeout caused `cf push` commands taking longer than 19s to be aborted.
We'll revert this change for now so we'll have time to figure out the right solution.
Code review is enough. All the manifest property changes are a no-op as those are the default values in the job spec files.
The only real change is adding back the route 53 record for the API.
Not me.
=> [#155856825] Revert: Switch DNS from CC ELB to system domain ELB.

concourse/pipelines/create-cloudfoundry.yml
Set `serial: true` on app and API availability test jobs.
I frequently have to manually stop these tests to avoid false negatives.
We don't ever want them to run on top of each other.
Run in dev env, think about the consequences. It means that jobs might queue up instead of overlapping.
Anyone but @camelpunch
=> Don't let app or API availability tests overlap

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
We accidentally used `<%=` instead of `<%` which printed the object reference to a BOSH job template. This caused the nats instances being constantly redeployed.
The generated template looked something like this:
```
#<Bosh::Template::EvaluationContext::InactiveElseBlock:0x00007fdd049545f0>
init_config:
...
```
See https://github.com/cloudfoundry/bosh/issues/1923 for details.
❗️ This PR contains a temporary commit which needs to be updated with the final datadog-for-cloudfoundry BOSH release.
1. Code review: https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/27
1. Deploy your CF twice from this branch:
```BRANCH=nats_port_156188483 make dev pipelines```
In the second deployment you should not see the nats instances being redeployed.
Not me.
=> [#156188483] Stop NATS instances from being constantly redeployed

concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/tasks/generate-test-config.yml
This PR uses the new bosh-cli-v2 image that contains Bosh CLI 3.0.1
to mitigate against https://www.cloudfoundry.org/blog/cve-2018-1231/
Code review against https://hub.docker.com/r/governmentpaas/bosh-cli-v2/tags/ for the tag
Deploy in your environment on top of master and see the tests pass
Not @LeePorte
=> [Support] Update Docker image for Bosh CLI cve-2018-1231

manifests/cf-manifest/env-specific/cf-default.yml, manifests/cf-manifest/env-specific/cf-prod.yml, manifests/cf-manifest/env-specific/cf-staging.yml, manifests/cf-manifest/manifest/operations/080-logsearch.yml
This increases the queue VMs from t2.small to m3.medium instances.
We have been seeing the queue VMs maxing out on CPU and running out
of credits. The m3.medium instances offer twice the vCPU and a fixed
performance.
~~There is the option to change this just in prod, as we only see the
high stress on the queue VM CPU in that environment, but we do not
have many instances of this VM, so the environment parity seems more
valuable than the cost saving.~~
**Update:**
This has been made into an environment-specific configuration because
we anticipate our logging stack to be scaled in numerous ways as we
grow, so there will be large cumulative cost savings.
Code review should be enough. I have deployed it and it didn't cause chaos and destruction.
Anyone but me
=> Use medium VM type for queue VMs

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
[#156340018 Increase number of dopplers per AZ](https://www.pivotaltracker.com/story/show/156340018)
What?
-----
We want to increase the number of doppler nodes to 2 per AZ, as
- "Two dopplers per AZ is actually the recommended architecture
for high availability," says cf-deployment v1.7.0.[1]
- We see that the current instances are using 80-90% CPU which may
cause them to drop log messages or behave otherwise wrongly.
[1] https://github.com/cloudfoundry/cf-deployment/releases/tag/v1.7.0
How to review?
-------------
- Code review
- deploy
- test this?????
Who?
----
Anyone but @keymon or @camelpunch
=> [#156340018] Increase the number of doppler VMs to 2 per AZ

manifests/cf-manifest/manifest/000-base-cf-deployment.yml
[#155854402 Restructure internal certs to match cf-deployment](https://www.pivotaltracker.com/story/show/155854402)
What
----
the adapter service verifies the CN of the certificate of
the reverse log proxy. In cf-deployment it is used reverselogproxy
and we generated the certs using that name.
We must update the adapter service to use the same.
How to test?
------------
Deploy, check that the adapter service is not logging:
```
2018/04/04 14:15:01 Failed to connect to loggregator API: x509: certificate is valid for reverselogproxy, not reverse_log_proxy
```
Who?
---
=> [#155854402] Use the right CN for cert validation in adapter

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/test-config/acceptance_tests.yml, platform-tests/upstream/run_acceptance_tests.sh
https://www.pivotaltracker.com/n/projects/1275640/stories/156299675
What?
-----
We are tracking the cf-deployment blessed version v1.21.0.
This version points to:
- smoke-tests:
- https://github.com/cloudfoundry/cf-smoke-tests-release/tree/40.0.1
- submodule: https://github.com/cloudfoundry/cf-smoke-tests/tree/923e2a158722a37a9ed28c0216b3b5a4009e9ac9
- CATS: https://github.com/cloudfoundry/cf-acceptance-tests/tree/cf1.21
I updated our fork https://github.com/alphagov/paas-cf-smoke-tests/tree/gds-cf-deployment-v1.21.0
and changed the references in the pipeline.
How to review?
-------------
Check that the pipeline ends OK.
Who?
----
=> [#156299675] Pin the smoke-tests and CATs to blessed versions

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/operations/010-cert-rotation.yml
https://www.pivotaltracker.com/n/projects/1275640/stories/156299675
What?
-----
We configured the bbs service incorrectly in the PR alphagov/paas-cf#1306. The properties must be under `loggregator.*`, not `diego.loggregator`.
Without this, the bbs service does not send the metrics to the metron agent.
This is causing some monitors fail in datadog, as metrics for the lock held by BBS are missing.
How to review?
------------
- code review
- deploy this
- check that the files are populated in the vm `diego-api/0`: `/var/vcap/jobs/bbs/config/certs/loggregator/*` and `/var/vcap/jobs/bbs/config/bbs.json` has the property `loggregator_use_v2_api":false`
You can check in my deployment instead of deploying yours, ask me
Who?
---
=> [#156299675] Fix properties for loggregator in bbs service

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/operations/080-logsearch.yml, manifests/cf-manifest/spec/manifest/router_spec.rb
The logs were truncated for multiple reasons:
- the logger command splits the messages at 1k
- the rsyslog max message size is 4k (this will also result in log splitting)
We enabled blackbox with TCP mode which would replace logger therefore eliminating the 1k size limit. It turned out blackbox (probably accidentally) truncates the messages at ~10k. We opened an issue [1] and PR [2] upstream to fix this (to increase it to ~100k).
We forked and patched blackbox. Because of this we have to use the paas-syslog-release fork again.
We also increased the rsyslog max message size to 64k.
Messages sent by logger (tagged with vcap.*) will be ignored by rsyslog.
By enabling blackbox we'll finally have all logs in logsearch which were written to a file under /var/vcap/sys/log
We had to amend some of …
=> [#156302820] Enable blackbox and stop truncating/splitting logs

concourse/pipelines/create-cloudfoundry.yml
https://www.pivotaltracker.com/n/projects/1275640/stories/156313150
What?
-----
During alphagov/paas-cf#1232 we added a task that would check
if the healthcheck is deployed and if the environment is a dev
environment, skipping the execution if it is not with a `try`
block.
But that semantically makes the job to always be "green" because
all the sequence is under a `try` block, even when the smoke test
actually fails. Although the email alert is sent, this prevents
our datadog monitor to be trigger because it checks if there
was a "green" build in the last X minutes.
We can rewrite the flow of the job so that the assertion runs first,
and if it fails, it stops all the execution of the task. The email
would be sent only if the smoke test fails.
In development we do not have datadog …
=> [#156313150] Split continuous smoke test assert and payload

manifests/cf-manifest/env-specific/cf-prod.yml
We're currently hovering around 32% advertised capacity remaining on the
cells, which is below the threshold we're aiming for in ARD021[1].
Adding 3 cells beings this back up to around 40%.
[1]https://government-paas-team-manual.readthedocs.io/en/latest/architecture_decision_records/ADR021-cell-capacity-assignment-2/
Not me.
=> [Support] Increase prod cells to 27

terraform/datadog/cell.tf
This is currently failing since rep was updated to require TLS and
client certs. This disables the monitor to avoid noise on the dashboards
until the story to fix it[1] is played.
[1]https://www.pivotaltracker.com/story/show/156570305
Not me.
=> [Support] Temporarily disable the rep_healthy monitor.

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/lib/notify.sh, concourse/scripts/pipelines-cloudfoundry.sh, manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/manifest/operations/200-paas-admin-uaa-client.yml, manifests/cf-manifest/scripts/generate-cf-secrets.rb, manifests/cf-manifest/scripts/generate-manifest.sh, manifests/cf-manifest/spec/manifest/base_properties_spec.rb, scripts/upload-notify-secrets.sh
https://www.pivotaltracker.com/story/show/155783706
What?
-----
We want to deploy the paas-admin application for the tenants.
We consider that the admin tool is part of every platform, so we decided to add the deployment as part of the paas-cf deployment pipeline.
The deployment requires:
- A new UAA client to integrate with UAA oauth for tenants.
- Deploy the app from master
- Inject secrets from notify.
> We follow the same pattern than other secrets, although I personally consider it extremely   overcomplicated and difficult to maintain
How to review?
--------------
1. Code review
2. Go to `http://admin.${DEPLOY_ENV}.dev.cloudpipeline.digital/`, try to login and use the app.
3. try to invite a user. You shall receive notifications.
Related
-------- …
=> [#155783706] Deploy paas-admin as part of the PaaS deployment

platform-tests/src/platform/availability/api/api_test.go, terraform/cloudfoundry/dns-records.tf
Now that the ELB is configured we can switch DNS over to serve via GoRouter.
* Deploy on top of https://github.com/alphagov/paas-cf/pull/1314
* Make sure all tests pass, particularly availlability tests.
* Merge https://github.com/alphagov/paas-cf/pull/1314
* Rebase on master
Anyone but me, @46bit or @chrisfarms
=> [#155856825] Move Cloud Controller behind GoRouter - Part 2: The Return of the Router

manifests/cf-manifest/manifest/operations/070-elasticache-broker.yml, manifests/cf-manifest/scripts/generate-cf-secrets.rb, manifests/cf-manifest/scripts/rotate-cf-secrets.rb
❗️ This PR should be merged only after the auth token migration was finished in prod.
In https://github.com/alphagov/paas-cf/pull/1318 we started to generate and store auth tokens in Secrets Manager.
This PR remove the auth token seed from the Elasticache Broker.
For details please see https://github.com/alphagov/paas-elasticache-broker/pull/14
The old auth token seed will be automatically removed at the next secret rotation.
❗️ This PR contains a temporary commit which needs to be updated with the final elasticache-broker release
1. Review https://github.com/alphagov/paas-elasticache-broker/pull/14
1. Review https://github.com/alphagov/paas-elasticache-broker-boshrelease/pull/10
1. Deploy your CF from this branch and make sure all tests pass …
=> [#156226677] Update elasticache broker (cleanup part)

scripts/cf_subshell_scoped_login.sh
This can then be used to add an indicator to your shell prompt to
indicate which CF env you're targetting. eg:
```sh
PS1='\u@\h:\w${CF_SUBSHELL_TARGET+ (cf-$CF_SUBSHELL_TARGET)}\$ '
```
* Code review
* Does the name of the new variable make sense?
* Verify that the variable is present in the subshell created by this script
Not me
=> [Support] cf_subshell_scoped_login: export target env variable.

manifests/cf-manifest/manifest/000-base-cf-deployment.yml, manifests/cf-manifest/spec/manifest/base_properties_spec.rb, scripts/create-user.sh
Redirect to Paas Admin as previously on login the user would have been directed to next steps on the product page.  However this content has now been moved to Paas Admin, so redirect to the new location of next steps.
Depends on https://github.com/alphagov/paas-product-page/pull/63
Make sure the pages are redirected.
Anyone who isn't me or @paroxp
=> Redirect to Paas Admin on Login

concourse/scripts/pipelines-cloudfoundry.sh
See commit message.
* Delete the Notify secrets from your S3 bucket and check that `make dev pipelines` fails with the expected message
* Upload the Notify secrets (following instructions in the message) and check that `make dev pipelines` succeeds
Not @46bit
=> Require Notify secrets to run `make pipelines`

concourse/tasks/get-cf-cli-config.yml
See commit message. This should fix the `remove-healthcheck-db` and `remove-billing-db` tasks of the `destroy-cloudfoundry` pipeline's `delete-deployment` job.
I am not certain if this fully fixes the `destroy-cloudfoundry`. This works fine in my temporary dev environment `mikie`, but it [fails in my permanent `miki` dev environment](https://deployer.miki.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-acceptance-tests/builds/18) even when I thought I'd cleared out RDS instances beforehand.
* Code review
* Try it in your dev environment (use `BRANCH=fix-destroy-cloudfoundry-api-url-156925097 make dev pipelines` to push these custom pipelines.) Check the `destroy-cloudfoundry` entirely succeeds (you'll need to destroy any service instances you've created …
=> [#156925097] Fix CF API url used by destroy-cloudfoundry

concourse/scripts/pipecleaner_test.go, platform-tests/upstream/run_acceptance_tests.sh
We originally disabled the test in [1] because it was incompatible with running CATS from a Concourse container (instead of a BOSH errand).
The test would have prevented us from breaking syslog drain functionality in the incident [2].
Also I increased the PipeCleaner timeout, because both @46bit and I had a timeout on Travis the last week.
[1] https://github.com/alphagov/paas-cf/commit/3a7d54a5c1f1e50283c16e99eb0a70e374984dbb
[2] https://www.pivotaltracker.com/story/show/156683943
1. Deploy CF from this branch, the acceptance tests should pass. Also validate that there is a test saying `forwards app messages to registered syslog drains` really runs.
```BRANCH=enable_syslog_acc_tests_156729524 make dev pipelines```
Not me.
=> [#156729524] Enable the syslog drain test in cf-acceptance-tests.

concourse/pipelines/create-cloudfoundry.yml
Bump paas-billing to the latest version that brings in many of the recent changes such as VAT calculations, declarative configuration of pricing, sub components, and more... see https://github.com/alphagov/paas-billing/pull/23 for more details.
If you want to test deployment in your dev env then:
```
ENABLE_BILLING_APP=true SELF_UPDATE_PIPELINE=false BRANCH=configuring-plans-155326294 make dev pipelines
```
Ensure that https://github.com/alphagov/paas-billing/pull/23 is merged first and then replace the [TMP] commit in this commit with the proper release tag.
Not @chrisfarms or @camelpunch
=> [#155326294] update paas-billing release

manifests/cf-manifest/operations.d/240-cf-set-buildpack-release.yml
What
----
Respond to https://www.cloudfoundry.org/blog/ms-isac-2018-046
Multiple upstream vulnerabilities have been discovered in all
supported PHP versions in the PHP buildpack. MS-ISAC reports
that the most severe of these vulnerabilities could allow
an attacker to execute arbitrary code. An attacker could take advantage
of this type of vulnerability to steal credentials, modify application
code, cause a denial of service attack, or take other malicious actions.
Releases that have fixed this issue include:
-  php-buildpack version 4.3.53
How to review
-------------
Code review.
I am deploying this in my env
https://deployer.hector.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry?groups=all, you can simply check if it is deployed there.
Follow up
---------
Notify the …
=> Update the php-buildpack to 4.3.53

manifests/cf-manifest/operations.d/710-logsearch.yml, manifests/cf-manifest/spec/manifest/logsearch_spec.rb
https://www.pivotaltracker.com/story/show/157219548
What
----
We were configuring two different parsers consuming messages from
the specific redis queue of each AZ.
But there is no really a reason for this, and having this setup
can cause issues, as only one queue might start receiving messages
when the ingestors are redeployed and marked as unhealthy in the
ELBs. When this happens, one of the parsers will be really busy
and unable to cope with the backlog meanwhile the other is idle.
If the two parsers consume both queues, the load would be evenly
distributed across both of them and they will not be saturated.
Analysing the parser template[1], we found out that we might able
to define multiple redis "inputs" and override specific options in
each, specifically `host`.
With this change we …
=> [#157219548] Configure logsearch parse to consume both queues

terraform/datadog/aws.tf
https://www.pivotaltracker.com/story/show/157219548
What
----
Now there is only one instance_group for the parsers called `parser`
only. We update the exclusion on the ec2-cpu-utilization monitor in
datadog.
How to review
-------------
Code review
Who can review
--------------
not me
=> [#157219548] Update parser name in ec2-cpu-utilization monitor

manifests/cf-manifest/env-specific/cf-prod.yml
What
----
We're currently hovering around 32% advertised capacity remaining on the
cells, which is below the threshold we're aiming for in ARD021[1].
Adding 3 cells beings this back up to around 40%.
Same than [2]
[1] https://alphagov.github.io/paas-team-manual/architecture_decision_records/ADR021-cell-capacity-assignment-2/#decision
[2] 5cf3323d5773a245dd9406f65824dde8342b0a99
How to review
-------------
Code review.
Who can review
--------------
not @keymon
=> [SUPPORT] Increase prod cells to 30

concourse/pipelines/create-cloudfoundry.yml
What
----
We've broken our pipelines, as we're deploying an application that is
going to fail due to missing environment variable.
This should be addressed in already backlogged story that will enable
tagging for that application.
How to review
-------------
- See if the changes make sense
- I'd say run through pipelines, but it's a blocker for staging. Perhaps unblock the pipeline and test on staging?
=> Add billing URL to PaaS Admin

terraform/datadog/cloud_controller.tf
What
----
So that you can easily find out what jobs have failed. Similar to the CC
errors alert that's next to it.
I've removed the text about checking the API because I don't think it's
useful. Errors can happen even if CC API is fine. The error logs will
tell you the actual problem.
How to review
-------------
I haven't tested that this applies and I suggest you don't either because enabling DataDog takes too long. Check the changes for syntax and that the search query returns the right things in Logsearch.
Who can review
--------------
Anyone.
=> [support] Add logsearch query for CC failed jobs alert

terraform/datadog/router.tf
What
----
We are using DBSCAN[1] outlider monitoring on the number of registered
routes in the go routers. But since we added a third gorouter[2] this
monitor has been flapping, despite it does not seem to be outliers.
We opened a support case in datadog[3] and they suggested to use
scaledDBSCAN instead[4].
I tested the algorithms DBSCAN, MAD and scaledDBSCAN in cloned
monitors, and I confirmed that scaledDBSCAN did not flap, meanwhile
the other two did.
The scaledDBSCAN is still working, as I simulated a scenario by
blocking the traffic from one gorouter to NATS to prevent it from
receiving route updates, and adding some routes.
[1] https://docs.datadoghq.com/monitors/monitor_types/outlier/
[2] https://github.com/alphagov/paas-cf/pull/1336
[3] …
=> [#SUPPORT] Use scaledDBSCAN rather than DBSCAN in datadog

concourse/pipelines/create-cloudfoundry.yml
We're building a (somewhat) [live infrastructure map dashboard](https://github.com/alphagov/paas-infrastructure-map/pull/1) to get an overview of deployed components.
We create a job that can be run in the pipeline to create a snapshot of the state of what the BOSH deployment looks like (via the BOSH director API) and a dump some EC2/ELB info which gets written to the state bucket as JSON.
The state should not be too sensitive, but making it public should be considered leaking too much information about the platform internals.... So to allow the generated JSON state dump to be consumed by an external service, a pre-signed URL is created (valid for 1 week) and stored in a secrets file in the state bucket. A deployment pipeline (like build/ci) can fetch the presigned secret url and use it …
=> [Firebreak] Periodically dump infrastructure state to bucket

manifests/cf-manifest/operations.d/520-datadog-add-instance-group-checks.yml, terraform/datadog/cell.tf
Remove rep cell Datadog monitor and rep service endpoint check.
After the upgrade done in [1], the rep cell monitor is broken. The reason is that the datadog rep check does not work because it uses mutual TLS. [2]
The monitor was disabled in [3] while we decided what to do about it.
We've now decided that we should remove this, as we don't believe this offers much value above the existing process monitor that's in place.
[1] https://www.pivotaltracker.com/story/show/156299675
[2] https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/blob/8d8ae64cba528dc31d432f45699b3de8e100a92b/jobs/datadog-rep/templates/http_check.yaml.erb#L4-L7
[3] https://github.com/alphagov/paas-cf/pull/1317
1. Review and merge https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/2 …
=> [#156570305] Remove datadog rep health monitor

manifests/cf-manifest/operations.d/710-rds-broker.yml
Update the rds-broker release to use SHA256 for generating usernames/passwords.
During the pentest it came up that MD5 isn't considered safe anymore and we
should use SHA256 instead.
We also found that the MySQL instances [were not reseting the Master Password when changing the seed or the algorithm](https://github.com/alphagov/paas-rds-broker/pull/75)
1. ~~Review https://github.com/alphagov/paas-rds-broker/pull/74~~ already reviewed by @keymon 
1. Review https://github.com/alphagov/paas-rds-broker/pull/75
1. Review https://github.com/alphagov/paas-rds-broker-boshrelease/pull/54
1. Create one `mysql` and `psql` RDS instance in your environment. Create some binding creds with `cf create-service-key <service> key1`
1. Deploy your CF from this branch and wait for all tests to pass
``` …
```
=> [#156224236] Update the rds-broker release to use SHA256 for generating usernames/passwords and MySQL password reset.

concourse/pipelines/create-cloudfoundry.yml
What
----
We are printing also credentials in the output and we shouldn't.
Also remove some spurious whitespaces.
How to review
-------------
Code review
Who can review
--------------
Not me
=> Remove verbose output when deploying paas-admin

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Due a bug we were not reseting all the passwords of all the existing
instances when the seed or the algorithm of the master password
changed.
This new version fixes the issue.
See https://github.com/alphagov/paas-rds-broker/pull/76
How to review
-------------
Code review
Who can review
--------------
not me
=> [#156224236] Update rds-broker-relase to 0.1.26

manifests/cf-manifest/operations.d/240-cf-set-buildpack-release.yml
What
----
We are upgrading to the latest buildpacks.
At the time of writing (02/05/2018) the following buildpacks had a newer version in Github,
but were not used as they were not published at bosh.io:
* https://bosh.io/releases/github.com/cloudfoundry/nodejs-buildpack-release?all=1
* https://bosh.io/releases/github.com/cloudfoundry/java-buildpack-release?all=1
* https://bosh.io/releases/github.com/cloudfoundry/ruby-buildpack-release?all=1
How to review
-------------
* Verify the versions being upgraded to match the [announcement](https://groups.google.com/a/digital.cabinet-office.gov.uk/forum/#!topic/gov-uk-paas-announce/VGku440sQxc)
* Deploy this branch to a dev environment.
* Verify everything passes
Who can review
--------------
Not @henrytk or myself.
=> [#157246492] Upgrade buildpacks

concourse/pipelines/create-cloudfoundry.yml
What
----
When we roll out the London region, we're going to host apps under this
subdomain there, so we want to ensure that tenants can't deploy an app
here in the Ireland region because that app would stop receiving traffic
when we rolled out London.
How to review
-------------
Who can review
--------------
Not me.
=> [#156164399] Reserve london.cloudapps.digital to prevent future conflicts

manifests/cf-manifest/operations.d/330-uaa.yml, manifests/cf-manifest/spec/manifest/uaa_spec.rb
What
-----
We want to force login sessions to last no longer than a day, due to a
recommendation in a recent penetration test. The access token validity
is set via cf-deployment, but we set the refresh token validity via our
own ops files, so we add a test to make sure the value is set correctly
and cf-deployment does not override our value.
How to review
-------------
Code review.
If you want you can deploy from this branch, login with the CF CLI, and inspect the token to see what access and refresh expiries it has:
The access token expiry token should be 10 minutes from when the token was issued:
```bash
date -r $(cf oauth-token | awk '{ print $2 }' | cut -d. -f2 | base64 -D | jq '.exp')
```
And the refresh token expiry should be 20 hours from when the token was issued.
You can grab the …
=> [#157189960] Set token expiry for CF CLI UAA client

manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml, manifests/cf-manifest/operations.d/240-cf-upgrade-garden-runc.yml
What
----
This upgrades garden-runc to 1.13.3 which includes the fix for the [Docker image layer bug](https://github.com/cloudfoundry/garden-runc-release/issues/77).
To fully apply the fix it's necessary to recreate all the cell VMs. I've therefore included a stemcell bump in this PR as that seems like the easiest, and most tested way we have for achieving this.
How to review
-------------
* Push an app using a docker image that demonstrates the problem:
```
cf push docker-test --docker-image cfgarden/opaque-whiteouts-regression-image --no-route --health-check-type none
cf ssh docker-test
ls /test/foo # Will cause "No such file or directory" errors
```
* Observe that the above test app now no longer exhibits these errors.
* Verify all other tests pass
Who can …
=> [#157803606] Bump garden-runc to fix Docker layer bug

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/710-rds-broker.yml, manifests/cf-manifest/operations.d/730-elasticache-broker.yml, manifests/cf-manifest/spec/manifest/rds_broker_spec.rb, platform-tests/src/platform/acceptance/init_test.go, platform-tests/src/platform/acceptance/mysql_service_test.go, platform-tests/src/platform/acceptance/postgres_service_test.go, platform-tests/src/platform/acceptance/redis_service_test.go
What
----
We want to consolidate the naming convention for all the backing services
we offer, as it is described in ADR025: https://team-manual.cloud.service.gov.uk/architecture_decision_records/ADR025-service-plan-naming-conventions/
We also want to only offer encrypted plans and deprecate the non
encrypted ones. We will not remove them, but make them unavailable
To disable the plans, we add a script in the task that enable the broker to
specifically disable those.
How to review
-------------
- Code review
- Deploy this, let the tests pass
- Check the marketplace as a normal (non admin) user:
```
cf create-user testuser password123
cf set-org-role testuser govuk-paas OrgManager
cf auth testuser password123
cf marketplace
cf marketplace mysql
cf marketplace postgres
cf marketplace redis …
```
=> [#157470481] Rename service plans according ADR025

concourse/pipelines/create-cloudfoundry.yml
What
----
When creating the healthcheck-db We were relying on the behaviour that
`cf create-service` is a no-op when creating a plan with the exact same
name, plan and args.
However we recently renamed the plan which causes the create-service
call to fail.
To resolve this a guard is added to check for the existance of the
database before attempting to create it.
How to review
-------------
Code review
Who can review
--------------
=> [#157470481] Check if healthcheck-db exists before creating

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/710-rds-broker.yml, manifests/cf-manifest/spec/manifest/rds_broker_spec.rb, platform-tests/src/platform/acceptance/mysql_service_test.go, platform-tests/src/platform/acceptance/postgres_service_test.go
What
----
In PRs #1377 #1376 and #1375 we renamed the RDS services to the
new convention and added some `tiny-*` ones using t2.micro with
encryption.
But AWS RDS does not support t2.micro RDS instances with encryption.
Creating an instance tiny-* would result in a error:
Server error, status code: 502, error code: 10001, message: Service broker error: InvalidParameterCombination: DB Instance class db.t2.micro does not support encryption at rest
We remove tiny-5.7 and tiny-9.5, and enable the unencrypted ones
to everybody.
How to review
-------------
- Code review
- Optionally: Deploy this and check the tests pass
Who can review
--------------
Anyone but me
=> [#157470481] Remove invalid tiny encrypted RDS plans

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/540-log-cache.yml, manifests/cf-manifest/test-config/acceptance_log_cache_tests.yml, platform-tests/upstream/run_acceptance_tests.sh
https://www.pivotaltracker.com/story/show/157083954
What
----
We want to deploy log-cache https://github.com/cloudfoundry/log-cache to
transfer and cache tenants metrics. One of the harder problems with
collecting metrics (and logs) and exposing them to tenants is if/how to
cache them, transport them, drop them, and scale delivery of them to
authenticated tenants. Loggregator already solves this problem so it
would be nice to take advantage of that.
log-cache allows us to retrieve this metrics and cache them reducing the
overhead caused on the dopplers when there are several consumers. It is
proposed as a new addition to the loggregator for the normal log
shipping.
We tried this service in a previous spike [#156731599](https://www.pivotaltracker.com/n/projects/1275640/stories/156731599) …
=> [#157083954] Deploy Log Cache service

concourse/pipelines/create-cloudfoundry.yml
What
----
New plans have been added to paas-billing for the new plans that were
added to the cf marketplace offering.
This bumps paas-billing to latest version.
How to review
-------------
Code review should suffice
Who can review
--------------
=> [#157470481] Bump paas-billing to v0.28.0

terraform/datadog/certificates.tf, tools/metrics/gauges_tls.go, tools/metrics/gauges_tls_test.go, tools/metrics/metrics_test.go, tools/metrics/tlscheck/tls.go, tools/metrics/tlscheck/tls_test.go
We'll report expiry and validity metrics separately.
Also don't stop reporting domain metrics when any of the domain TLS check fails.
When any of the domain TLS check has an error we just log it and continue with the next one.
Also we changed the DaysUntilExpiry method so it always returns an error when a certificate has a non-expiry related issues.
We only want to be alerted when correctly set up domains are near expiry.
When tenants don't set up DNS for their domain, or point it to the wrong domain we shouldn't get an alert.
Separate monitors to check expiry and validity.
For the metrics reporter I think a code review should be enough.
Deploy CF from this branch and with Datadog enabled and check the new monitors (it's quicker if you set ENABLED_DATADOG to true in the …
=> [#156154997] Separate TLS expiry and validity metrics

concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/pipelines-cloudfoundry.sh, manifests/cf-manifest/operations.d/500-syslog-forwarder.yml, manifests/cf-manifest/operations/datadog.yml, manifests/cf-manifest/scripts/generate-manifest.sh, manifests/cf-manifest/spec/manifest/datadog_spec.rb, manifests/cf-manifest/spec/manifest/syslog_forwarder_spec.rb, manifests/cf-manifest/spec/support/manifest_helpers.rb, manifests/shared/spec/fixtures/environment-variables.yml
What
----
This is the companion PR to alphagov/paas-bootstrap#166.
We want to move away from using runtime-config to reduce the coupling between this repo and paas-bootstrap.
This adds the configure that used to be provided by the runtime config to the CF manifest.
How to review
-------------
* Deploy alphagov/paas-bootstrap#166
* Deploy CF from this branch with Datadog enabled.
* Verify that metrics still appear in Datadog
* Verify that logs are still shipped to logsearch.
This needs to be coordinated with alphagov/paas-bootstrap#166 when merging and applying. This needs to be deployed immediately after alphagov/paas-bootstrap#166 has been deployed to avoid a gap in metrics to Datadog.
Who can review
--------------
Not me
=> [#157047494] Migrate away from runtime config

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/scripts/check-certificates.rb, concourse/tasks/generate-test-config.yml, manifests/cf-manifest/operations.d/540-log-cache.yml, manifests/cf-manifest/operations.d/900-cf-cert-rotation.yml, manifests/cf-manifest/scripts/rotate-cf-certs.rb, manifests/cf-manifest/spec/manifest/rotate_certs_spec.rb
We use the BOSH cli to generate certificates into a variable stare - based on the manifest variable definitons.
There is a known issue if you try to rotate the CA certificates outlined in [1].
The root of the problem is that when OpenSSL is configured to trust multiple CAs, and two of them have the same subject name, OpenSSL will only verify certificates against the first one (see [2] in OpenSSL code).
One solution for the CA certificate rotation problem is to set the Subject Key Identifiers so OpenSSL will be able to handle multiple certificates with the same subject name.
We patched the bosh-cli to generate certificates with an SKI. This will solve the problem long-term but the first rotation _would_ still cause downtime as OpenSSL is still not able to find the right CA unless all CAs …
=> [#157032509] Fix CA certification rotation

manifests/cf-manifest/operations.d/330-uaa.yml
What
----
The default is true upstream but we've set it to false in [1].
If require_https is disabled the Current-User cookie won't have the secure flag which came up in our latest pentest.
There is no reason to disable this anymore. Whatever caused issues previously it doesn't seem to be present anymore.
[1] https://github.com/alphagov/paas-cf/commit/9a4dda67ead70bd39d811cc373d8fd10dbb9df44
How to review
-------------
1. Deploy your CF from this branch
2. Make sure the tests pass. Log in to UAA on the web.
Who can review
--------------
Not me.
=> [#156224014] Don't disable the uaa.require_https flag.

concourse/pipelines/create-cloudfoundry.yml
What
----
We're implementing the version bumping for that application from the
build pipeline. We should fully make use of it in order to avoid any
incompatibilities in the future and run the desired version of the
application across all of our environments.
This does however introduces the inconvenience of the need to come into
this repo, and manually bump the version as we go.
How to review
-------------
- Make sure this version exists in build CI
Dependencies
-------------
This PR is the last one in the chain of PRs.
Before merging, make sure the following are already merged:
- alphagov/paas-admin#61
- alphagov/paas-release-ci#70
=> [#156721553] Version pin paas-admin

concourse/pipelines/create-cloudfoundry.yml, concourse/tasks/smoke-tests-run.yml, manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml, manifests/cf-manifest/operations.d/240-cf-upgrade-garden-runc.yml, manifests/cf-manifest/operations.d/240-cf-upgrade-loggregator.yml, platform-tests/upstream/run_smoke_tests.sh
What
----
- We've upgraded to cf-deployment v1.38.0
- We've upgraded to the latest loggregator release to resolve multiple CVEs (see commit).
How to review
-------------
We've deployed this a couple of times to dev environments. You can do so too if you want, however it probably isn't necessary and you can just eyeball the changes and lean on staging.
Who can review
--------------
Not me. Not Henry.
=> [#157965597] Upgrade cf-deployment and loggregator

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
We want to install the [paas-rds-metrics-collector](https://github.com/alphagov/paas-rds-metric-collector/)
to get metrics from the tenant's RDS instances created by the [RDS broker](https://github.com/alphagov/paas-rds-broker)
into loggregator.
The user can then consume them using loggregator, or, probably, the
log-cache service added in https://github.com/alphagov/paas-cf/pull/1371
Dependencies
------------
Review with:
- https://github.com/alphagov/paas-rds-metric-collector/pull/1
- https://github.com/alphagov/paas-rds-broker-boshrelease/pull/58
How to review
-------------
- Code review
- Deploy the instance
- Create a RDS instance (or use the billing one for instance) and get
the guid with `cf service <name> --guid`
- Install the log-cache-cli plugin (see below)
- Query …
=> [#157084165] Add RDS broker metrics collector

concourse/pipelines/create-cloudfoundry.yml
What
----
paas-billing v0.30.0 updates the pricing formulas for Compose-hosted
services to calculate prices based on a fraction of the total cluster
memory usage.
How to review
-------------
Code review
Who can review
--------------
=> [#157510099] Bump paas-billing to v0.30.0

concourse/pipelines/create-cloudfoundry.yml
What
----
Bump paas-admin to v0.4.0
- paas-admin v0.3.0 implements the first version of the pricing calculator
- v0.4.0 handles not allow remove the latest org manager
How to review
-------------
Code review
Who can review
--------------
=> [#157510099] bump paas-admin to v0.4.0

concourse/pipelines/create-cloudfoundry.yml
What
----
We'd like to allow our tenants to pull metrics for their prometheus
setup from our platform. To allow that, we're deploying the previously
developed paas-log-cache-adapter and exposing the endpoint publicly.
How to review
-------------
- Sanity check
- Run pipeline from this branch
- Make sure the app is deployed and accessible
```sh
curl -H "Accept: application/json" -H "Authorization: $(cf oauth-token)" https://metrics.${DEPLOY_ENV}.dev.cloudpipeline.digital/metrics
```
Dependencies
--------------
This is the last PR out of three.
Needs to be merged after:
- alphagov/paas-log-cache-adapter#2
- alphagov/paas-release-ci#73
⚠️  Remove or ask to remove the TMP commit before merging.
=> [#158353106] Deploy log-cache-adapter

concourse/pipelines/create-cloudfoundry.yml
What
----
- `0.5.0` several fixes: https://github.com/alphagov/paas-admin/pull/53
- `0.6.0` Prevents deleting last billing manager
- `0.7.0` fixes a bug with lack of permssions https://github.com/alphagov/paas-admin/pull/66
- `0.8.0` introduces feature to resend user invites by org managers.
How to review
-------------
- Make sure this is the latest version (see build ci)
Dependencies
--------------
Merge after alphagov/paas-admin#64
=> [#157111626] Bump paas-admin version

terraform/dev.tfvars, terraform/prod.tfvars, terraform/staging.tfvars
The ids for the contacts in Pingdom appear to have changed since we last
ran this terraform. The existing checks are still linked to the correct
contacts, it's just that the internal IDs of these are now different.
This means that future terraform runs will attempt to set these back to
the old ids, which will fail because they no longer exist.
I found this while trying to deploy to London and setup pingdom for these.
How to review
-------------
* Run a pingdom terraform plan against staging and prod from this branch and verify that terraform doesn't want to make any changes.
* Login to the Pingdom site and verify that the correct contacts are linked to the checks.
Who can review
--------------
Not me.
=> Fix Pingdom contact ids

concourse/pipelines/create-cloudfoundry.yml
What
----
We were generating the SESSION_SECRET env var for paas-admin wrong,
so it is always `session-(( grab ...`. This is because we use
spruce interpolation wrong
We fix it as the intention is use the UAA secret of the paas-admin
client.
To deploy this would logout all the users.
How to review
-------------
Code review shall be enough
Who can review
--------------
Anynone but me
=> [bugfix] Fix how SESSION_SECRET for paas-admin is generated

manifests/cf-manifest/operations.d/240-cf-set-buildpack-release.yml
Upgrade the buildpacks to the latest versions
These versions are the same as in cf-deployment v1.40.0: https://github.com/cloudfoundry/cf-deployment/blob/2118b5d8ac09feed153f6eea552fd561dd6aa999/cf-deployment.yml#L1623
See commit for detailed buildpack changes.
The tenant notification draft is attached to the story: https://www.pivotaltracker.com/story/show/158108798/comments/190615158
❗️ This PR should not be merged before 20th June.
Deploy your CF from this branch and make sure all tests pass.
Not me.
=> [#158108798] Upgrade the buildpacks to the latest versions

terraform/datadog/auctioneer.tf, terraform/datadog/aws.tf, terraform/datadog/bbs.tf, terraform/datadog/bosh-jobs.tf, terraform/datadog/cdn_broker.tf, terraform/datadog/cell.tf, terraform/datadog/certificates.tf, terraform/datadog/cloud_controller.tf, terraform/datadog/compose_scraper.tf, terraform/datadog/concourse.tf, terraform/datadog/consul.tf, terraform/datadog/dns.tf, terraform/datadog/elb.tf, terraform/datadog/general.tf, terraform/datadog/ipsec.tf, terraform/datadog/nats.tf, terraform/datadog/queue.tf, terraform/datadog/route-emitter.tf, terraform/datadog/router.tf, terraform/datadog/syslog_drains.tf, terraform/datadog/tps.tf
It seems we forgot to add the email notification for many alerts and we didn't get emails for alerts which should've been investigated, like the daily increase in the gorouter latency caused by a Verify perf test.
I didn't enable the email notifications for the DNS response time monitor as we know this monitor alerts a lot, so it would cause a lot of noise.
Also I removed the escalation_message field from the Datadog monitors. This field is only needed if we enable renotify_interval, but we don't use it (except for 2 Compose monitors).
1. Code review
1. Deploy the Datadog monitors from this branch and check if they deploy cleanly (You can speed up review if you manually enable Datadog only for the datadog-terraform-apply in the pipeline)
Not me.
=> [#158386152] Add missing datadog notifications

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/scripts/environment.sh, concourse/scripts/pipelines-cloudfoundry.sh, concourse/scripts/self-update-pipeline.sh, concourse/scripts/tag_release.sh, manifests/cf-manifest/env-specific/cf-prod-lon.yml, manifests/cf-manifest/env-specific/cf-stg-lon.yml, scripts/cf_subshell_scoped_login.sh, scripts/upload-compose-secrets.sh, scripts/upload-datadog-secrets.sh, scripts/upload-google-oauth-secrets.sh, scripts/upload-notify-secrets.sh
What
----
This adds the targets etc for deploying the staging and prod environments in the London region.
How to review
-------------
As per the paas-bootstrap PR, other than code review, the best way to test this is probably to try deploying the London staging deployment. Given the fiddly nature of this process it's probably best to pair with @henrytk or myself while deploying.
* Perform review steps from https://github.com/alphagov/paas-bootstrap/pull/168 to get a deployer concourse
* checkout this branch
* Load staging AWS keys (if you haven't already)
* Checkout the credstore branches: https://github.com/alphagov/paas-credentials/pull/121 and https://github.com/alphagov/paas-credentials-high/pull/37
* Upload the secrets: `COMPOSE_PASSWORD_STORE_HIGH_DIR=/path/to/paas-credentials-high …
=> [#156164640] Create staging and prod London deployments.

manifests/cf-manifest/operations.d/260-cf-upgrade-uaa.yml
What
----
We are bumping uaa-release to v60 separate from cf-deployment to address
a [CVE](https://www.cloudfoundry.org/blog/cve-2018-11041/). 
How to review
-------------
* Review code
* Test deployment
Who can review
--------------
=> Upgrade uaa-release to v60

manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
We bump stemcells to 3468.51/3586.23 ~~and bump cflinuxfs2 to 1.218.0~~ to
mitigate the following CVEs:
https://www.cloudfoundry.org/blog/usn-3676-2/
https://www.cloudfoundry.org/blog/usn-3686-1/
https://www.cloudfoundry.org/blog/usn-3675-1/
https://www.cloudfoundry.org/blog/usn-3684-1/
* Check the versions picked mitigate the issues
* Code review (this is my first Opsfile/overriding cf-deployment change)
* Check it deploys cleanly in dev
=> Stemcell bumps for CVEs

concourse/pipelines/create-cloudfoundry.yml
What
----
We have to ignore another test as we did in d141e72dci and
f8c5638151d999bcedd5eae62e8552d5f3607133, due the
bug in the cf-cli plugin for log-cache[1]
[1] https://github.com/cloudfoundry/log-cache-cli/issues/32
How to review
-------------
Code review. The ignored test is the one failing here:
https://deployer.staging.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/acceptance-tests/builds/1032
Who can review
--------------
Not me
=> [#158459529] Ignore flaky acceptance test when testing logcache

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/test-config/acceptance_log_cache_tests.yml
What
----
We run the "apps" suite of the acceptance tests enabling using
cf tail to test log-cache[1][2]
But this feature is quite new and in development and the tests
might be flaky. [3]
We will separate the execution of these tests to a different job
so they can be rerun independently from the more lenghtly acceptance
tests.
[1] https://github.com/alphagov/paas-cf/pull/1371
[2] https://github.com/alphagov/paas-cf/pull/1371/commits/d141e72dc214f3cbda02855014faa6d66438c532
[3] https://github.com/alphagov/paas-cf/pull/1410
How to review
-------------
Code review.
Push the pipeline, check that it applies clean.
Who can review
--------------
Anyone but me
=> [#158459529] Split out log-cache acceptance tests

terraform/datadog/elb.tf
We are constantly seeing our Doppler ELB Latency monitor triggered as
a result of the anomaly detection algorithm noticing large %-changes of
what are ultimately very small values.
This alters the monitor configuration to use the 'agile' detection
algorithm (which takes into account a larger history of data), uses a
smaller window for sampling and uses warning/alert thresholds at a
25%-change and 50%-change respectfully.
The result should be a monitor that is less sentitive to short spikes of
%-change but still trigger on more sustained deviations.
This may mean that it takes a bit longer for an alert to trigger and may
potentially be prone to miscalculation if the value rises very slowly over
say a few weeks. However we have not seen such behaviour and that could
be caught using a more …
=> [support] desensitize doppler elb latency monitor

concourse/pipelines/create-cloudfoundry.yml
What
----
This pulls in https://github.com/alphagov/paas-cf-acceptance-tests/pull/1 to fix some flakiness in one of the upstream tests.
How to review
-------------
Code review is probably the best. I've tested the change using `ginkgo -untilItFails` against my dev env, and it didn't fail after around 20 cycles whereas it would previously fail in around 3-4 cycles.
Merge https://github.com/alphagov/paas-cf-acceptance-tests/pull/1, and update the TMP commit to point at the `cf1.38-gds` branch of our fork.
Who can review
--------------
Not me.
=> [#158459529] Use forked acceptance tests to fix flakey test

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
We have added the rds-metrics-collector job in the rds-broker
instance-group to collect tenants metrics. But this job runs
periodically (every 1-5 minutes) instead of in a burst mode as
the broker use to. Because that the VM ends running out of credits.
We will try to increase with the `small` size, which is a
t2.small, and see if it behaves better with it.
How to review
-------------
Code review
Who can review
--------------
Anyone but me
=> [#157084165] Increase rds-broker instance type to small

misc/chrome_plugins/clean_concourse_pipeline/manifest.json, misc/chrome_plugins/clean_concourse_pipeline/src/inject.user.js
What
----
Now that we're running PaaS in London, we've created a subdomain to
differentiate between both.
The plugin requires adding an extra string to the array the script
matches against.
How to review
-------------
- Test whether the plugin works
- Update the dashboard
=> Add london domain to the match array

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
We are worried of the overhead of having metrics per table from
RDS broker instance, so we disabled them in
https://github.com/alphagov/paas-rds-metric-collector/pull/4
Here we bump the corresponding bosh-release version.
How to review
-------------
Code review
Who can review
--------------
not me
=> [#158594217] Bump rds-broker release to disable table metrics

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
This version of the rds broker includes setting the number of retries on
calls to the AWS API. This was recommended by AWS support in response to
a request regarding the throttling we are occasionally seeing.
How to review
-------------
Code review to check that the broker version matches https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker-release/jobs/build-final-release/builds/33
Deploy in dev
Who can review
--------------
Not @LeePorte
=> Update paas-rds-broker to 0.17.0

concourse/pipelines/create-cloudfoundry.yml
What
----
paas-billing v0.32.0 collects service_plans and service records from the
CF API and versions them to allow for queries against historic data.
How to review
-------------
Check the paas-billing tag matches the one produced by build ci
Who can review
--------------
=> [#157438891] Bump paas-billing to v0.32.0

terraform/datadog/elb.tf
These ELBs no longer exist, so these monitors no longer apply. They're
currently reporting no data in London because the ELBs have never
existed there. In other environments, they aren't alerting because
they're not set to alert on no data.
How to review
-------------
* Code review.
* Verify that my assertion about these monitors applying to a non-existent ELB is correct
Who can review
--------------
Not me.
=> Remove CC and UAA ELB latency monitors from Datadog.

manifests/cf-manifest/operations.d/710-rds-broker.yml
This includes https://github.com/alphagov/paas-rds-broker-boshrelease/pull/60 which
makes these properties optional, so we can remove them from the
manifest.
How to review
-------------
Deploy from this branch. Verify all the tests pass.
Who can review
--------------
Not me.
=> Update rds-broker - blank AWS keys no longer needed.

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Even after the bump to `t2.small` we're exhausting all the available CPU
credits. Bumping again.
How to review
-------------
Just merge it #yolo.
Who can review
--------------
Anyone.
=> Bump `rds_broker` VM instance size

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Includes the changes from
- https://github.com/alphagov/paas-rds-broker-boshrelease/pull/61
- https://github.com/alphagov/paas-rds-metric-collector/pull/5
- https://github.com/alphagov/paas-rds-broker/pull/83
We are experiencing rate limiting throttling in our RDS brokers,
very likely due the amount of calls to the ListTagsForResource
operation.
This version would cache the response and efectivelly reduce
the amount of requests to the AWS api.
How to review
-------------
Quick code review and check the PRs
Who can review
--------------
Anyone
=> [#158520831] Upgrade rds-broker release to fix rate limiting

scripts/org-usage-report.sh
What
----
The intention of this script is to provide a CSV output for analysing
whether some orgs are unused and can be deleted.
Example usage:
cf login ...
./scripts/org-usage-report.sh
How to review
-------------
This is the minimum scripting required to deliver the required information. In my opinion, the review should only be concerned with making sure the information is mostly accurate. There is little need for precision, because the output of this script is just advising us which orgs we should think about decommissioning.
Note: continuous-smoke-tests result in orgs, spaces, and apps disappeared during script execution, which occassionally creates erroneous data.
Who can review
--------------
Anyone but me or @LeePorte
=> [#158525694] Add a script for reporting org usage

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/deployment-kick-off.yml
The latest tag was recently updated to point to the 3.8 release, but
this release was broken[1]. attempting to pull the container locally
resulted in the error:
```
$ docker pull alpine:latest
latest: Pulling from library/alpine
no matching manifest for linux/amd64 in the manifest list entries
```
This has caused the continuous smoke tests to fail to start in all
environments as of around 9:40 today.  Pinning this to the version we
were previously using (3.7) should help avoid this sort of issue in
future.
[1]https://github.com/gliderlabs/docker-alpine/issues/418
How to review
-------------
Code review.  I've already tested this in my dev env, so that's probably enough.
Who can review
--------------
Not me.
=> [Support] Pin a specific version of the Alpine containers.

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
This updates the broker so that the startup credential check and rotate only runs on a single instance. This is to reduce the number of AWS API calls we make, and hopefully help prevent us hitting the rate-limits.
This also updates the cron schedule to only run the stale snapshot cleanup job daily.
How to review
-------------
* Verify all still works
* Verify the check-and-rotate still runs, and only runs on a single instance (easiest way is probably to check the logs)
* Verify the cron process still runs, and only runs on one instance (again the logs are probably the easiest way to check this)
Merge https://github.com/alphagov/paas-rds-broker-boshrelease/pull/63 and update the TMP commit with the resulting boshrelease build.
Who can review …
=> [#158520831] Only run RDS broker housekeeping on one instance.

manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
This is being done to force the changes in https://github.com/alphagov/paas-bootstrap/pull/171 to apply (they only
take effect the next time the VMs are recreated.
This includes a bunch of ubuntu trusty updates. Nothing specifically
significant.
How to review
-------------
Code review is probably enough. I've already tested this in my dev environment.
Ensure that https://github.com/alphagov/paas-bootstrap/pull/171 has been merged and applied in all persistent environments.
Who can review
--------------
Not me.
=> [#158791033] Bump stemcells to force NTP changes to apply.

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/230-cf-set-metron-agent-deployment.yml, manifests/cf-manifest/operations.d/299-cf-rename-vars-to-terraform.yml, manifests/cf-manifest/operations.d/710-logsearch.yml, manifests/cf-manifest/operations.d/710-rds-broker.yml, manifests/cf-manifest/operations.d/720-cdn-broker.yml, manifests/cf-manifest/operations.d/730-elasticache-broker.yml, manifests/cf-manifest/operations.d/900-cf-cert-rotation.yml, manifests/cf-manifest/operations/datadog.yml, manifests/cf-manifest/scripts/generate-manifest.sh
What
----
Upgrade cf-deployment from 1.38 to 2.6.0.
This was mostly pain free, but we had to do a few things to support the
new version:
- Removed the override on the version of cflinuxfs as the version in cf
is newer
- Fixed a bunch of yaml paths which had changed
- Updated the rds-broker not to depend on certificate files on disk -
the location of these had changed
- Added use-external-blobstore.yml to the manifest - required in the
newer version
How to review
-------------
See also https://github.com/alphagov/paas-rds-broker-boshrelease/pull/64
which is the update in rds-broker.
Who can review
--------------
Anyone
=> [#158938536] Update cf-deployment to 2.6.0

concourse/pipelines/create-cloudfoundry.yml
What
----
paas-admin v0.21.0 adds the multiple-org cost reporting available at
/reports/cost/YYYY-MM it is currently not advertised to tenants as it is
mainly for interval usage right now, but may be useful to managers of
multiple orgs in the future.
How to review
-------------
Check version is legit
Who can review
--------------
Not me
=> [#158974168] upgrades paas-admin to v0.21.0

manifests/cf-manifest/operations.d/260-cf-upgrade-uaa.yml
What
----
This commit updates UAA from 60 to 60.2 in order to mitigate against
accepting a refresh token as an access token.
How to review
-------------
Code review and deploy to dev on top of current master
Who can review
--------------
Not @LeePorte
=> [#159162443] Update UAA to 60.2 for CVE-2018-11047

manifests/cf-manifest/env-specific/cf-prod.yml
What
----
We are hovering around 33% advertised capacity remaining on the
cells, which is below the threshold we're aiming for in ARD021[1].
Adding 3 cells beings this back up to around 40%.
[1] https://team-manual.cloud.service.gov.uk/architecture_decision_records/ADR021-cell-capacity-assignment-2/#decision
How to review
-------------
Code review
Who can review
--------------
Not @LeePorte
=> [SUPPORT] Increase prod cells to 33

concourse/scripts/pipelines-cloudfoundry.sh
This means that the pipeline will fail early if the API token hasn't
been uploaded, instead of waiting until the post-deploy task before
failing.
How to review
-------------
* Run `make dev pipelines` without aiven secrets uploaded, and verify you get a helpful error message.
* Upload the secrets (`make dev upload-aiven-secrets`), and repeat. Verify it now works.
Who can review
--------------
Not me.
=> [#157737884] Add check for Aiven API token in pipelines script

terraform/prod.tfvars
What
----
This commit adds in the variables with the correct values that are used
for calculating the ElastiCache alerts in datadog.
How to review
-------------
Code review against patterns use in other env vars
Who can review
--------------
Not @LeePorte
=> [support] Increase ElastiCache parameter group number

concourse/pipelines/create-cloudfoundry.yml
What
----
This commit bumps the version of PaaS-Billing to 0.35 in order to
include the Aiven Elasticsearch plans.
How to review
-------------
Code review
Who can review
--------------
Not @LeePorte
=> [#158943954] Bump pass-billing to 0.35

concourse/pipelines/create-cloudfoundry.yml, config/service-brokers/aiven/config.json, config/service-brokers/aiven/manifest.yml, platform-tests/src/platform/acceptance/elasticsearch_service_test.go
What
----
The `es` suffix in the name doesn't confirm to the [naming ADR](https://team-manual.cloud.service.gov.uk/architecture_decision_records/ADR025-service-plan-naming-conventions/). This updates them to conform.
We had some debate as to whether the version should be expressed as 5.x
or merely 5. We decided to go with 5.x as that makes it more obvious
that this represents a version.
I've also taken the opportunity to move the app's base CF manifest into the app repo.
How to review
-------------
* Review https://github.com/alphagov/paas-aiven-broker/pull/6
* Update the broker pinning in the TMP commit.
* Verify this runs and the tests pass in the pipeline
Who can review
--------------
Not me.
=> [#159200278] Fix elasticsearch plan names

manifests/cf-manifest/operations.d/240-cf-set-buildpack-release.yml
What
----
After https://github.com/alphagov/paas-cf/pull/1442 we want to upgrade
the buildpacks after telling the tenants.
Update all the buildpacks we use to the same versions defined in the
cf-deployment v2.6.0 [1]
[1] https://github.com/cloudfoundry/cf-deployment/blob/v2.6.0/cf-deployment.yml
How to review
-------------
Deploy it and test should pass.
Merge after the agreed date in the tenants announcement
Dependencies
----------
After https://github.com/alphagov/paas-cf/pull/1442. Rebase this branch once that PR has been merged.
Who can review
--------------
Not me :)
=> [#158999833] Update buildpacks to match cf-deployment v2.6.0

terraform/cloudfoundry/metrics-exporter.tf, terraform/cloudfoundry/smtp.tf
What
----
The `terraform-destroy` step of `destroy-cloudfoundry` fails with the
following:
```
Error deleting IAM User ses-smtp-tlwr: DeleteConflict: Cannot delete entity, must delete access keys first.
```
These access keys are allegedly required for bits of backing services etc.
We can get terraform to do the work to remove them by using the
`force_destroy` attribute, which will remove group membership, access
keys, etc
No other work is required.
How to review
-------------
- code review
- `make dev pipelines` and ensure that `destroy-cloudfoundry`/`destroy-terraform` runs green
Who can review
-------------
Anyone except @tlwr @blairboy362
=> [#159230666] Use force_destroy param for iam_users

concourse/pipelines/create-cloudfoundry.yml
What
----
paas-billing v0.37.0 [fixes an issue](https://github.com/alphagov/paas-billing/pull/44) with UPDATE events that alter plan guids of services.
How to review
-------------
* Code review (does the version look like the right one)
Who can review
--------------
=> [#159268475] Bump paas-billing v0.37.0

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
This PR bumps the RDS broker BOSH release to include the code PR'd at https://github.com/alphagov/paas-rds-metric-collector/pull/6, which exposes stats from MySQL instances.
How to review
-------------
- Take the release from the CI output produced by the merging of https://github.com/alphagov/paas-rds-broker-boshrelease/pull/66 (probably the latest green run of https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker-release/jobs/build-final-release) and update this PR's WIP commit to reference the new final BOSH release at the bottom of the `build` step.
- Run this PR's branch's commit down your dev env.
- After the `cf-deploy` step, log into your CF and provision a mysql instance:
- `cf create-service mysql large-5.7 test-stats`
- Install the log-cache …
=> [#158946642] Bump rds-broker to include MySQL stats collection

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Deploy a new version of the rds-metric-collector which doesn't duplicate metrics.
How to review
-------------
* review https://github.com/alphagov/paas-rds-metric-collector/pull/7
* review https://github.com/alphagov/paas-rds-broker-boshrelease/pull/67
* code review this pull request
* ⚠️ update the temporary commit using the build details from: https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker-release/jobs/build-final-release
If you want to deploy you can use:
```bash
BRANCH=stop-double-emitting-metrics ENABLE_DATADOG=true make dev pipelines
```
Who can review
--------------
Anyone but me or @richardTowers
=> [#158333555] Stop double emitting metrics

concourse/pipelines/create-cloudfoundry.yml
What
----
We want to run some end-to-end integration/acceptance tests for
paas-admin, to check that everything works as expected with a real CF
api.
We add a task to the `custom-acceptance-tests` job that runs the tests
implemented in the paas-admin project itself, using a nodejs container.
Dependencies
------------
* PR in paas-admin: https://github.com/alphagov/paas-admin/pull/81
How to review
-------------
Code review. Run the pipeline and check that the tests run.
**IMPORTANT**: Before merge, merge the PR from paas-admin https://github.com/alphagov/paas-admin/pull/81 and remove the
WIP commit here once a new tag is generated. Check that is v0.22.0
Who can review
--------------
Anyone
=> [#156911499] Run paas-admin integration/acceptance tests in the pipeline

concourse/pipelines/create-cloudfoundry.yml
What?
------
The PR in  alphagov/paas-cf#1463 does not had into account the agreements to accept after login. We need to revert this to unblock the pipeline
How to review?
--------------
No need
Who?
-----
Anyone
=> [#156911499] "Revert Run paas-admin integration/acceptance tests in the pipeline"

concourse/pipelines/create-cloudfoundry.yml, terraform/datadog/aiven.tf, tools/metrics/aiven.go, tools/metrics/aiven_test.go, tools/metrics/fakes/fake_aiven.go, tools/metrics/main.go
What
----
Monitor how much we are spending with Aiven and alert if necessary.
We want to know if we reach the limit internally agreed with
accounting, so that we can discuss what to do on time.
How to review
-------------
- Code review
Check that works, either by yourself:
- Deploy with datadog enabled (tip: you comment out or remove the addon in the
`manifests/cf-manifest/operations/datadog.yml` in a tmp commit so it does not re deploy
all VMs, you only need the nozzle)
- Check that the metric is there in datadog
Or check that works on the `leeporte` environment in datadog directly.
Who can review
--------------
Anyone. @leeporte can merge, as we paired and I am happy with the
implementation.
=> [#158944131] Collect aiven estimated cost and add datadog monitor

concourse/pipelines/create-cloudfoundry.yml
What
----
When running the paas-admin acceptance tests, we create test users.
These users must have any agreement accepted before we can do
testing of the paas-admin app.
Dependency
---------
https://github.com/alphagov/paas-admin/pull/82=
How to review
-------------
Code review, and test should pass.
Who can review
--------------
Anyone
=> [#156911499] paas-admin acceptance tests accepts all aggrements

concourse/pipelines/create-cloudfoundry.yml
What
----
Bump paas-billing to 0.38.0 to enable historical record of names for
org/space GUIDs.
How to review
-------------
If you really want to you can have a look at
https://github.com/alphagov/paas-billing/pull/45
Who can review
--------------
Anyone
=> [#157205103] Bump paas-billing to 0.38.0

concourse/pipelines/create-cloudfoundry.yml
The issue[1] that we encountered has been fixed upstream as of version
2.2, so we no longer need to use our fork of these with the workaround.
[1]https://github.com/cloudfoundry/cf-acceptance-tests/pull/312
How to review
-------------
Run the pipeline, verify that the acceptance tests pass.
You could go as far as checking out the referenced version of the tests and running locally with the loggregator test focussed to confirm that it's not flakey, or you could take my word for it that I've already done this testing.
Who can review
--------------
Not me.
=> [Support] Switch back to upstream acceptance tests.

config/service-brokers/aiven/config.json
What
----
The 2 Elasticsearch plans we're launching with are both the same size,
varied only by ES version (5 vs 6). Also, Aiven doesn't perform a
version upgrade when moving an existing service instance from the
small-ha-5 plan to the small-ha-6 plan.
Taken together, these two facts mean that there's no meaningful plan
change that can be made - so in this commit we mark these plans as
non-updatable.
The above holds, technically, for now, but may not be true in the
future.  We are choosing to delay the work to implement selective
update-ability until we actually introduce differently-sized plans.
How to review
-------------
- Point a dev env at this branch
- Update CF (possibly just the `post-deploy` job)
- Enable service access to `elasticsearch` …
=> Aiven service instances cannot change plans

tools/metrics/tlscheck/tls_test.go
What
----
This is an issue with badssl.com and the fact their certificate expired.
The nature of our monitor relies on it being reported as 0 days
remaining. This would not happen in production systems if we're having
the monitoring in place.
Once the badssl.com has resolved their issue, it should be reverted
back.
How to review
-------------
- Make sure we're happy with the change.
=> Ignore the test causing travis to fail

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
We're now scraping a lot of metrics every 1 minute. We presume that's
OK, however this includes querying the AWS CloudWatch, which is really
expensive. For the time being in order to save some moneys, we'd like to
run the queries every 10 minutes. A downside is that at the current
state of an application it has to apply these for all metric collectors.
This should be a temporary change, and ideally be reverted back and
sorted in a different way.
How to review
-------------
- Make sure the change makes sense
I haven't tested this. Base on https://github.com/alphagov/paas-rds-broker-boshrelease/blob/master/jobs/rds-metric-collector/spec#L40-L42
=> Increase the collection interval

manifests/cf-manifest/operations.d/520-datadog-add-instance-group-checks.yml
What
----
Bump the datadog Bosh release to include a BAU change which tests Consul's reporting of its leader against IPs, not against DNS names.
How to review
-------------
- Merge https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/pull/31
- Update the WIP commit in this PR's branch referencing the final BOSH release
- Deploy a dev env on this branch with datadog integrations enabled
- Check that the `<env name> consul cluster has at least one leader` datadog monitor is not red
Who can review
--------------
Anyone except myself.
=> [#159136460] Bump datadog BOSH release

manifests/cf-manifest/operations.d/540-log-cache.yml
What
----
We're periodically experiencing responses with `502` on `/v1/meta`
endpoint, and before the issue is raised with the upstream, we'd like to
make sure it doesn't only happen to that specific version of log-cache.
The upgrade also involves other bug fixes and features, including:
- Fix data duplication bug
- Additional metrics for CFAuthProxy
This may solve one of our other stories we have in the backlog.
How to review
-------------
- Check if latest version has been used
- Optionally, run through pipeline
=> [#159172134] Bump log-cache version

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
This is to fix the bug where RDS instances would have some flags
overwritten during operations like master password resets.
How to review
-------------
See:
* the [bosh-release build](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker-release/jobs/build-final-release/builds/42?)
* the [rds-broker build](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker/jobs/tag-releases/builds/24)
* the [PR](https://github.com/alphagov/paas-rds-broker/pull/85)
Who can review
--------------
Anyone
=> [#159620811] rds-broker to 0.1.42 (v0.20.0 of paas-rds-broker)

concourse/pipelines/create-cloudfoundry.yml
What
----
Bump paas-billing to 0.39.0.
Why
----
The new version **stops** enforcing a minimum 1p charge per resource.
How to review
-------------
This **is** the review of https://github.com/alphagov/paas-billing/pull/46.
Who can review
--------------
@richardTowers and myself are doing&reviewing.
=> [#159790813] Bump paas-billing to 0.39.0

terraform/prod.tfvars
What
----
We have raised our limits for number of elasticache param groups in
ireland and london. This bumps the var to keep our monitor in parity
with reality.
How to review
-------------
Code review should suffice
Who can review
--------------
=> [support] raise aws elasticache param group limits in prod

manifests/cf-manifest/operations.d/500-syslog-forwarder.yml
What
----
We've had some suspected issues with rsyslog using a lot of memory. If
this happens again it would be nice to have enough detail available in
the logs to diagnose the issue.
Adding the impstats module in this way causes rsyslog to log a set of
diagnostic information every one minute like the following:
```
2018-08-16T15:42:13.195272+00:00 localhost rsyslogd-pstats: { "name": "global", "origin": "dynstats", "values": { } }
2018-08-16T15:42:13.195290+00:00 localhost rsyslogd-pstats: { "name": "imuxsock", "origin": "imuxsock", "submitted": 8, "ratelimit!discarded": 0, "ratelimit!numratelimiters": 0 }
2018-08-16T15:42:13.195302+00:00 localhost rsyslogd-pstats: { "name": "action 1", "origin": "core.action", "processed": 328, "failed": 0, "suspended": 0, "suspended!duration": 0, …
```
=> [#159559834] - Add the rsyslog impstats module

manifests/cf-manifest/operations.d/540-log-cache.yml
What
----
The log-cache 1.4.1 has some problems freeing memory in the store[1][2]
This has caused some problems in production to us, where log-cache
grew to consume all the memory and swap of the doppler nodes.
This is meant to be fixed in 1.4.2 from comments in slack #log-cache[3]
but it is not ready yet.
The most recent stable version is 1.3.0, it is not as performant but
more stable.
[1] https://www.pivotaltracker.com/story/show/159699403
[2] https://www.pivotaltracker.com/story/show/157700747
[3] https://cloudfoundry.slack.com/archives/CBFB7NP9B/p1534518013000100
How to review
-------------
Code review, check the version in https://bosh.io/releases/github.com/cloudfoundry/log-cache-release?version=1.3.0
No point to test it, let it run in staging and if there are problems we
revert. …
=> Downgrade log-cache 1.3.0 to avoid memory leak

concourse/scripts/pipelines-cloudfoundry.sh
What
----
Now that we have implemented the slim dev deployment functionality, we
should make sure it doesn't break any of our persisting environments.
Falling back to nothing with bash should ensure the desired behaviour,
where it has failed on us in previous staging deployment.
How to review
-------------
- See if the thing makes sense
- Probably no need to deployment to dev. The only way to find out if it works, is to deploy it :D
=> Fix unbound variable

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
We'd like to collect CloudWatch metrics less frequently than the SQL
ones, as these cost us a lot of money.
The separation has been done in the rds-metric-collector itself.
How to review
-------------
- Deploy in your pipeline
~~⚠️ It needs to target correct boshrelease.~~
=> [#159174667] Setup the intervals for metric collection

terraform/datadog/router.tf
What
----
This monitor triggers when the % of gorouters marked as unhealthy
is >= 50%.
But it is incorrectly triggered sometimes when we do a change
that redeploys the VMs, for instance for a stemcell changes:
- BOSH would create new VMs which will replace the previous
ones, with different hostname.
- From the point of view of datadog, they are different instances.
- When this happens, if during the stop of the old VMs the check
failed (ie. haproxy stopped after gorouter and then the check run),
datadog would keep record of the failure on the VM for 24h
- In that case 3 instances would be marked as failed (old ones) and
3 instances would be marked as OK.
- If the threshold is >= 50%, the monitor would be incorrectly
triggered for 24h until the old VMs metrics are gone.
We opened tickets …
=> [#SUPPORT] Set monitor threshold for gorouter health to 55%

Makefile, scripts/test_posix_newline.sh, tools/metrics/tlscheck/tls_test.go
What
----
The issue has been fixed by the 3rd party maintainers of the site:
https://github.com/chromium/badssl.com/issues/359
This test can now be re-enabled.
How to review
-------------
1. Code review
1. Run the tests locally (`make test`)
Who can review
--------------
Anyone but me.
=> Re-enable the self-signed ssl test.

concourse/pipelines/create-cloudfoundry.yml
What
----
The new version contains upgrade of dependencies, including the GOV.UK
Frontend, and a fix to backing service metrics, causing the template to
throw white page.
How to review
-------------
- Sanity check the version against git tags
=> [#160021128] Bump paas-admin to version 0.33.0

concourse/pipelines/create-cloudfoundry.yml
What
----
The new version contains upgrade of dependencies to fix a minor
problem running acceptance tests.
https://github.com/alphagov/paas-admin/pull/93
How to review
-------------
Check the version number
Who can review
--------------
not me
=> [#160021128] Bump paas-admin to version 0.34.0

terraform/datadog/elb.tf
We do not want this monitor to generate spurious alerts.
Currently this monitor is being triggered a few times a day for up to 10
minutes at a time. The current behaviour that leads me to think this is
spurious: looking at the `aws.elb.latency` metric it seems normal for
the value to be around 9µs, but regularly spiking up to 20-30µs for only
5 minutes or so. The spikes consistently return to normal levels and
are, in my opinion, not high latencies.
Given the current alert window is 5 minutes and only 50% of values need
to be above the threshold, it seems correct for the alert to trigger as
often as it does[1]. Since a typical spike lasts no longer than 15
minutes and we want to trigger when 50% of values are above the
threshold I have decided to make the alert window 30 minutes.
In the …
=> [support task] Make Doppler ELB latency monitor more reliable

manifests/cf-manifest/operations.d/710-rds-broker.yml
This bumps the collector to the version which continues to collect
metrics when it hits an error[1].
[1] https://github.com/alphagov/paas-rds-metric-collector/pull/11
How to review
-------------
This has been code reviewed and merged without deployment, so if the reviewer thinks it is low risk enough they can merge this. Otherwise, at least deploy from this branch and check the custom acceptance tests pass.
Who can review
--------------
@tlwr
=> [#159986104] Bump metric collector to v0.9.0

concourse/pipelines/create-cloudfoundry.yml
What
----
Change the Prometheus metrics exporter to include TYPE annotations.
Interestingly `v0.2.0` was never deployed
How to review
-------------
See if https://github.com/alphagov/paas-log-cache-adapter/pull/4 looks legit
Who can review
--------------
Not me or Sam
=> [#159173326] Output metrics /w Prom exposition fmt

concourse/pipelines/destroy-cloudfoundry.yml
We want to destroy the prometheus deployment as well as CF when tearing
down a deployment, otherwise it's not possible to fully tear it down
(the terraform-destroy will fail because resources are in use).
How to review
-------------
* Code review
* test that the destroy pipeline works
Who can review
--------------
Not me.
=> [#158913461] Include prometheus deployment in destroy pipeline.

terraform/dev.tfvars, terraform/prod.tfvars, terraform/staging.tfvars
What
-----
We have dedicated email addresses (Google Groups) for alerting. They
are: govpaas-alerting-{dev,staging,prod}@digital.cabinet-office.gov.uk.
These addresses have been added as contacts in Pingdom, so we can use
them instead of the team email address. This will allow us to control
our subscription to Pingdom alerts with greater granularity.
How to review
-------------
- check contact IDs match contacts for the correct environment (Pingdom login details are in paas-credentials).
- check contacts have the correct email address
- apply the Terraform changes. This is still a manual process. Use the documentation in this repository to figure out how to do it. If you can't do it using the docs, we need to update the docs in this pull request
- after applying we may need to delete the …
=> [#133323615] Use per-environment Pingdom contacts

concourse/pipelines/create-cloudfoundry.yml
What
----
Bumps the version of paas-log-cache-adapter to v0.4.0
v0.4.0 contains improvements that causes promtool to complain less when scraping metrics, now it only complains about HELP annotations and naming
How to review
-------------
Version bump
Who can review
--------------
Not me
=> [#159173326] Bump paas-log-cache-adapter v0.4.0

Makefile, concourse/scripts/lib/logit.sh, concourse/scripts/pipelines-cloudfoundry.sh, scripts/upload-logit-secrets.sh
What
----
These are required for sending platform logs to Logit.
These were uploaded as part of paas-bootstrap, but nothing in that
repository uses these secrets now that Concourse logs aren't sent to
Logit.
How to review
-------------
Use it to upload secrets to your dev environment.
Related pull request: https://github.com/alphagov/paas-bootstrap/pull/180
Who can review
--------------
Anyone but me.
=> [Support task] Upload Logit secrets

Gemfile.lock
This issue appears to only affect Windows, and therefore is unlikely to
affect us. It's still worth updating to avoid noise.
https://nvd.nist.gov/vuln/detail/CVE-2018-1000201
How to review
-------------
Code review. Verify Travis passes.
Who can review
--------------
Not me.
=> Update ffi Gem to fix CVE-2018-1000201

concourse/pipelines/create-cloudfoundry.yml
This version of paas-admin has 512M defined for memory in the
manifest[1].
[1] https://github.com/alphagov/paas-admin/pull/94
How to review
-------------
In my opinion code review of this and the related pull request is sufficient.
It is intended to fix the issue defined in ZenDesk ticket 3116118, so if you have a lot of time on your hands you can see if it fixes/mitigates the issue, but I can do that on support. 
Who can review
--------------
Anyone but me.
=> [ZenDesk ticket 3116118] Bump paas-admin to v0.35.0 (scale to 512M memory)

terraform/datadog/doppler.tf, terraform/datadog/elb.tf
Despite various previous attempts to make this monitor less noisy we
still get spurious alerts. I believe this is because the nature of the
metric we are monitoring: the ELB latency is a very small value (around
9µs) and is subject to high spikes, but not to a level where the latency
is something we would worry about.
This monitor achieves the same result: it gives us an indication of the
health of the Dopplers and whether they are coping with the log and
metric volumes.
The monitor is a change alert because the metric is a count (and will
therefore keep increasing for the lifecycle of the VM). It checks the
maximum count in the last 10 minutes and compares it to the value an
hour ago[1].
[1] https://docs.datadoghq.com/api/?lang=python#create-a-monitor
How to review
-------------
I've …
=> [Support task] Replace Doppler latency monitor

concourse/pipelines/create-cloudfoundry.yml
What
----
Stop collecting Compose audit events
We are no longer using Compose, therefore we do not need to collect
Compose audit events. This upgrades to a version of the billing app in
which the Compose collector has been removed[1].
[1] https://github.com/alphagov/paas-billing/pull/51
How to review
-------------
Review in conjunction with https://github.com/alphagov/paas-billing/pull/51
Once you are ready to merge bump the version of paas-billing, as per
the code comment, and rebase this commit. See commit message.
Make sure it deploys okay.
Who can review
--------------
Anyone but me.
=> [#160233844] Remove Compose collector

concourse/pipelines/create-cloudfoundry.yml
This has now been removed in persistent environments, so we no longer
need it.
This reverts commit de3a0d6e72b2e498462e1d32e52c1ef9718228e9.
How to review
-------------
* Check this makes sense
* Check that #1515 has been deployed in all persistent envs.
Who can review
--------------
Not me.
=> [#157053149] Revert "Remove Compose API token from paas-billing"

concourse/pipelines/create-cloudfoundry.yml
What
----
This PR updates pass-billing to a new version that uses the broker
plan ID to select pricing plans rather than the Cloud Foundry ID. This
enables pass-billing to work in multiple environments including London
and in dev.
How to review
-------------
Deploy from this branch and check the admin org bill in your dev env. There will be billing entries for services on the bill.
Before merge
----
Update the commit to use the tag generated after merging https://github.com/alphagov/paas-billing/pull/49
Who can review
--------------
Not @LeePorte or @keymon
=> [#158665945] Update paas-billing release

manifests/cf-manifest/operations.d/310-router.yml
```
For cf-deployment v3.6.0
We have TLS between the gorouter and UAA, so we need tell the gorouter
to trust whatever CAs upstream has, AS WELL AS the CA that we use for
UAA.
We also do certificate rotations on all of these CA certs so we need to
add in the appropriate `${ca}_old` values.
```
What
----
We need to get gorouter to trust cloud controller (amongst others)
We're separating out our #159730005 v3.6.0 into separate releases so we do not get HTTP 526s when rolling out v3.6.0
How to review
-------------
Code review
Who can review
--------------
Not me or Richard
=> [#159730005] Cert rotation and uaa_ca on gorouter for v3.6.0

concourse/pipelines/create-cloudfoundry.yml, config/service-brokers/aiven/config.json, platform-tests/src/platform/acceptance/elasticsearch_service_test.go
What
----
For many use-cases tenants don't need a HA elasticsearch instance, and
therefore want one that's smaller and cheaper. This adds these
instances.
This also updates our integration tests to use one of these smaller
plans so that we spend less testing the platform.
Now that we have some smaller plans, this marks the larger ones as non-free as we don't want them to be available for trial orgs.
How to review
-------------
* Deploy the pipeline from this branch.
* Verify the custom acceptance tests pass.
* Verify the new plans appear in the pricing calculator (`https://admin.${DEPLOY_ENV}.dev.cloudpipeline.digital/calculator`)
Merge https://github.com/alphagov/paas-billing/pull/54 and update the TMP commit here accordingly.
Who can review
--------------
Not me.
=> [#159732085] Add smaller non-HA elasticsearch plans

concourse/pipelines/create-cloudfoundry.yml
What
----
Upgrade the acceptance tests to the correct versions for cf-deployment 3.6, as per [the team manual](https://team-manual.cloud.service.gov.uk/guides/upgrading_CF,_bosh_and_stemcells/#before-upgrading).
How to review
-------------
* "Code review"
* Run the tests down a pipeline (they've been down `towers` already - had a failure in logcache-acceptance-tests which I think was just flakiness, so look out for that)
Who can review
--------------
Someone who:
* can count
* has a dev environment to test with
=> [#159730005] upgrade upstream acceptance tests

concourse/pipelines/create-cloudfoundry.yml
This was bumped to 0.43.0 instead of 0.44.0 in #1520. 0.44.0 is the
version that includes https://github.com/alphagov/paas-billing/pull/54
which adds details of the new tiny ES plans to the billing config.
How to review
-------------
* Verify the new plans appear in the pricing calculator (https://admin.${DEPLOY_ENV}.dev.cloudpipeline.digital/calculator)
Who can review
--------------
Not me.
=> [#159732085] Bump paas-billing for new tiny ES plans

manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml, manifests/cf-manifest/operations.d/260-cf-upgrade-cflinuxfs2.yml
Includes fixes for the following:
- USN-3755-1: GD vulnerabilities
- USN-3756-1: Intel Microcode vulnerabilities
- USN-3753-2: Linux kernel (Xenial HWE) vulnerabilities
How to review
-------------
I've already tested this in my dev environment, so core review is probably sufficient.
Who can review
--------------
Not me.
=> [#160446591] Bump stemcell and cflinuxfs2 to fix USNs.

terraform/cloudfoundry/outputs.tf
We were interpolating the AWS region into the hostname being used here,
but SES is only available in 3 regions globally[1] - London isn't one of
them.  email-smtp.eu-west-2.amazonaws.com does not resolve.
This causes the password reset flow to fail with a 500 error because UAA
is unable to mail the reset link to the user.
We address this by hardcoding eu-west-1 (Ireland) as that's the closest
available region for all our deployments
[1] https://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html
How to review
-------------
To test this, you'll need a dev environment deployed in London. Test the password reset flow after deploying from this branch. (You'll need to verify the recipient address before email sending will work because dev SES is in sandbox mode. `aws --region=eu-west-1 …
=> [#160479583] Fix password reset in London

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/230-rename-buildpack-packages.yml, manifests/cf-manifest/spec/manifest/base_properties_spec.rb
In 88ad0226095eafc4c969828d3d98446065551247 we "fixed" a test which asserted
the wrong thing, in cf-deployment v3.6.0 they changed the package names,
however we override these because we pin our buildpack versions (because we
like our tenants).
The result of this was that creating a new environment left us with a grand
total of 1 buildpack (where the buildpack version we had pinned was the same as
v3.6.0 - binary_buildpack: they had the same package name)
This PR does three things:
- Revert the test which we fixed, this can be reverted in one weeks time when
we have upgraded the buildpacks (after we have notified our tenants).
- Add an ops file which changes the package names that we look for to be the
same as they were pre v3.6.0 upgrade. This means that they will be installed
when …
=> [#159730005] Ensure current buildpacks are installed.

concourse/pipelines/create-cloudfoundry.yml, platform-tests/src/platform/acceptance/init_test.go
We want to allow all users to be able to use this service. This adds the
call to the pipeline to enable it for everyone.
I've also updated the tests to not enable this service for the test org
so that we can verify it's on for all orgs by default.
How to review
-------------
* Run the pipeline
* Verify the tests pass
* Run `cf marketplace` after targetting an org/space and verify that the elasticsearch service is listed.
Who can review
--------------
Not me.
=> [#160383666] Enable Elsticsearch service for everyone.

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
This release fixes a bug restoring snapshots.
See  https://github.com/alphagov/paas-rds-broker/pull/87
How to review
-------------
- Review & merge first https://github.com/alphagov/paas-rds-broker-boshrelease/pull/71
- I guessed the version for the next in CI, check the release info in : https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rds-broker-release/jobs/build-final-release/builds/45 and update with the right version.
Who can review
--------------
Not @keymon
=> [#160176077] Bump rds-broker release to 0.1.45 to fix restore from snapshots

platform-tests/src/platform/acceptance/elasticsearch_service_test.go
The way this test selected the plan to use was non-obvious to me, and at
least one other team member. I've therefore refactored this to be
explicit about the plan that's being used in the test.
I've also changed it to use an elasticsearch 6.x plan to test as we
recommend that tenants use this version unless they have a good reason
to use 5.x.
How to review
-------------
Code review is probably enough. I've already run this through my env to test.
Who can review
--------------
Not me.
=> [Support] Be more explicit in defining elasticsearch test plan

terraform/datadog/certificates.tf
This was added in c3066ec with the intent of only alerting if a
significant number of certs were invalid, not when a single one was, so
that a cert that's in the process of being provisioned doesn't trigger
this monitor. It was intending to take the average of the values (which
are reported as 1 or 0 for each hostname), and alert if that fell below
a threshold.
However, because this was applying a `min` before doing the
`rollup(avg)`, it was taking the average of the minimum value, and hence
would always evaulate to 0 if any certs were invalid.
I've changed this to use the `avg` instead, and get rid of the rollup.
This results in a floating-point value representing the percentage of
certs that are valid. I've also changed the thresholds because a single
invalid cert in prod currently …
=> [Support] Fix CDN cert monitor to not alert for individual invalid certs

terraform/datadog/certificates.tf
I got it wrong in the previous commit and used the wrong threshold value
in the query, which causes Datadog to return an error.
How to review
-------------
* Code review.
* Verify that the value in the query matches the critical threshold.
Who can review
--------------
Not me.
=> [Support] Fix cert monitor query to match critical threshold.

manifests/cf-manifest/scripts/generate-manifest.sh
BBS had been using Consul for cell presence.  Therefore, despite Consul
not being the primary system for locks, its removal can still cause
problems.
How to review
-------------
Ensure this deploys with passing tests and no anticipated downtime.
Who can review
--------------
@tlwr
=> [#159136931] Stop relying on Consul

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/tasks/generate-test-config.yml
What
----
We want to use the bosh-cli v5.2.1 that includes support to
generate CA certificates with SKI[1], and stop using our
fork.
This new container includes the latest PR [2][3]
[1] https://github.com/cloudfoundry/bosh-cli/releases/tag/v5.2.1
[2] https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/134
[3] https://hub.docker.com/r/governmentpaas/bosh-cli-v2/builds/bdqhaxoavpkqqlgq2ivyg5k/
How to review
-------------
Code review. This has been tested in [2] and in the pipeline of alext.
Who can review
--------------
not me
=> [#160614327] Update bosh-cli-v2 image to use v5.2.1

concourse/scripts/fly_sync_and_login.sh
What
----
This PR make our fly login+sync wrapper capable of upgrading a fly binary over the v3/v4 major version boundary, in a way which the Concourse 4.0.0 release notes correctly say that `fly sync` can't do by itself. [1]
To make the different possible flows through the code clearer, the code is wrapped up in some shell functions which do what they say on the tin [2]. 
The script also exits early if any required envvars aren't set.
[1] https://concourse-ci.org/download.html#v400
[2] https://en.wikipedia.org/wiki/Does_exactly_what_it_says_on_the_tin
How to review
-------------
- Check out the branch
- Use your `$PAAS_CF/bin/fly` binary to log into a Concourse 3.8 instance
- Setting the envars appropriately (see Makefile:pipelines and its deps), use this script to log in to a Concourse …
=> [#158180318] Upgrade fly-login wrapper to cope with Concourse 4 upgrade

scripts/validate_aws_credentials.sh
What
----
`aws iam get-user` returns `Must specify userName when calling with
non-User credentials` when called with an assumed role.
We can use `aws sts get-caller-identity` instead, which will always
work.
See https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html
How to review
-------------
* Code review
* Check you can still run `make dev showenv` (for example) on this branch
Who can review
--------------
=> Fix validate_aws_credentials.sh for assumed roles

misc/chrome_plugins/clean_concourse_pipeline/src/inject.user.js
What
----
Now that we have upgraded concourse, some of the frontend has changed.
This means our plugin is out of date and should be updated if we'd like
to keep on using it on our dashboard TV.
In the new concourse version, upstream has decided to separate the
grouping bar into it's own place. This is a simple change really and
requires some minimal effort to hide new additional element.
Some other changes have been made, purely as a maintenance task to
keep the linter happy as well as the code more modern.
See commit for more details.
How to review
-------------
- Code review
- Copy contents of the file
- Open the deployer concourse on staging
- Open the `Inspect` console on Chrome (Cmd + Alt + J)
- Paste the contents of the file
- See no errors and expect the dashboard to be clean
After …
=> [#158180318] Update the chrome plugin

concourse/pipelines/create-cloudfoundry.yml
We've seen several occasions where the blue-green plugin will fail to
detect that the app already exists when deploying a dev environment. The
deploy then fails at the step when it attempts to rename the -new app
because the target appname is already taken.
I've not got to the bottom of why this happens, but switching to
autopilot has removed the issue for me. This plugin also has the
advantage that it purely relies on the manifest.yml for details of the
app, and doesn't attempt to preserve any details from the existing
deployment.
How to review
-------------
* Code review
* Optionally run this down a pipeline to verify it works (I've tested it in my environment several times).
Who can review
--------------
Not me.
=> Use autopilot for healthcheck app deployment

manifests/cf-manifest/operations.d/260-cf-networking-release-upgrade.yml
What
----
In order to upgrade to the latest version of cf-networking-release we
first have to go via 2.15.1 in order to avoid downtime[1].
[1] https://github.com/cloudfoundry/cf-networking-release/releases/tag/2.16.0
How to review
-------------
I've deployed it to my dev environment and it went green. I think it's probably good to just merge.
Who can review
--------------
Anyone.
=> [#160950252] Upgrade cf-networking-release  PART 1

manifests/cf-manifest/operations.d/260-cf-networking-release-upgrade.yml
What
----
Upgrade to the latest version of cf-networking-release
This resolves the following CVE:
- https://www.cloudfoundry.org/blog/cve-2018-15755/
How to review
-------------
Merge #1568 first.
I've run it through my dev environment and it went green—I tihnk it's probably good to just merge.
Who can review
--------------
Anyone.
=> [#160950252] Upgrade cf networking release PART 2

manifests/cf-manifest/operations.d/750-metric-exporter.yml, manifests/cf-manifest/spec/manifest/base_properties_spec.rb
What
----
This deploys the metric exporter to pull event data for all apps and parse them into useful HTTP metrics. It then feeds the metrics into Loggregator via a local Metron Agent.
It is colocated with the log-api VM for cost-saving purposes.
How to review
-------------
Ultimately we want users of Prometheus to be able to scrape the app metrics from `metrics.<system-domain>/metrics`. You can deploy from this branch and follow [the docs](https://docs.cloud.service.gov.uk/monitoring_apps.html) for getting a Dockerised Prometheus up and running.
Note: the response time metrics are currently not working. This only delivers a partial solution. We should just verify if the timing metrics are getting to log-cache, we can fix the Prometheus adapter in a follow-up story if required.
Review and …
=> [#159174283] Deploy Metric Exporter

manifests/cf-manifest/operations.d/260-cf-upgrade-cflinuxfs2.yml
What
----
Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.
Update to latest version of cflinuxfs2 to cover CVE USN-3791-1[1]
Git vulnerability
It was discovered that git did not properly validate git submodule urls
or paths. A remote attacker could possibly use this to craft a git
repository that causes arbitrary code execution when recursive
operations are used.
CVEs contained in this USN include: CVE-2018-17456
[1] https://www.cloudfoundry.org/blog/usn-3791-1/
How to review
-------------
Code review. Check the checksum at https://bosh.io/releases/github.com/cloudfoundry/cflinuxfs2-release?all=1
Any issue should be catched in staging, I think it is safe to merge.
Who can review
--------------
Not me
=> [#SUPPORT] Update cflinuxfs2 to 1.242.0 to fix git CVE

manifests/cf-manifest/operations.d/310-router.yml, manifests/cf-manifest/operations.d/350-diego-api.yml, manifests/cf-manifest/operations.d/350-diego-cell.yml, manifests/cf-manifest/operations.d/900-cf-cert-rotation.yml
What
----
Enable instance identity
How to review
-------------
Deploy from this branch. Make sure all tests pass. Because this doesn't enable Envoy proxy this change doesn't actually change how traffic is routed to apps. Therefore, this change is just preliminary work to make sure the certs are generated.
Who can review
--------------
Anyone but me or @LeePorte
=> [#155355978] Enable instance identity in diego 155355978

Makefile, README.md, concourse/pipelines/deployment-kick-off.yml, concourse/scripts/pause-kick-off.sh
What
----
We want to not trigger the deploy pipeline automatically for every
environment unless the developer opts in the day before.
To do so, we simply add an additional job that would pause the
timer that triggers the kick-off after the timer is triggered.
The developer must unpause the resource manually to get the deployment
the next day.
Known flaws: 
- The first time you deploy from scratch, the feature is not disabled by default. I think we can accept this instead of add more complexity.
How to review
-------------
Code review.
To test: Change the branch in concourse/pipelines/deployment-kick-off.yml and
the time window of the trigger to test it.
Who can review
--------------
Not me
=> [#161146691] Add logic to pause the kick-off after kick-off

Makefile, README.md
What
----
Fixes:
- The `unpause-kick-off` Makefile target should be phony. This is almost certainly a typo from a copy/paste.
- The docs refer to the triggering resource by a slightly wrong name.
Both of these should be uncontroversial.
How to review
-------------
Code review.
Who can review
--------------
Anyone. @henrytk reviewed the previous PR, so the context of that process would probably be handy.
=> [#161146691 ] Small fixes to auto-kickoff process and docs

concourse/pipelines/deployment-kick-off.yml
When the pipeline pausing was introduced in d3fee14, the
`AWS_DEFAULT_REGION` param was removed from these 2 tasks. This causes
them to fail when not in eu-west-1 (Ireland) as the s3 API returns a 400
error when trying to access the bucket in the wrong region (called from
the `environment.sh` script to get the concourse password[1]). This is
because the Makefile defaults this to eu-west-1 if it's not set[2].
[1]https://github.com/alphagov/paas-cf/blob/bb5bf1e/concourse/scripts/environment.sh#L33
[2]https://github.com/alphagov/paas-cf/blob/bb5bf1e/Makefile#L95
How to review
-------------
Code review. I've tested this change in my environment (which is in London).
Who can review
--------------
Not me.
=> [#161146691] Fix the pipeline kick-off pausing in London

scripts/list-all-users.sh
What
----
Uses the current `cf-cli` user's oauth token to query the uaa API
directly.
Could have used the uaa client instead of calling the API, but it's a
bit of a pain to use.
How to review
-------------
* Code review
* Run the script
Who can review
--------------
PaaS admins
=> [#SUPPORT] Add script to list all users

concourse/pipelines/deployment-kick-off.yml
What
----
Now the automatic kick-off is an opt-in feature[1], and our
environments won't we started unless the developer actively
sets it so.
But now we want to be able to trigger the kick-off to start
the DBs and the deployment without having to wait the
safe sleep time added to prevent all environments starting
at the same time and avoid rate limits.
To do so, we split the two parts: await and perform the kick-off.
The developer can trigger the kick-off at any time of the day.
The only restriction, due how concourse dependencies work,
is that the await-kick-off job has to be execute at least
once since the first bootstrap, but we can accept that.
[1] https://github.com/alphagov/paas-cf/pull/1583
How to review
-------------
Code review
Who can review
--------------
Not me
=> [#161146691] Split kick-off wait task from main one

scripts/org-usage-report.sh
What
----
If an organization as no spaces, then this script would return `null` as
the count of all services in that organization. If the input to `add` is
an empty array then it returns `null`.
How to review
-------------
Run the steps [from here](https://team-manual.cloud.service.gov.uk/guides/trial_accounts/#how-to-get-the-data), up to and including the database import. Before this change the data would error when importing into the database because of the `null` in the organization that had no spaces.
Who can review
--------------
Anyone.
=> [BAU] Return 0 if an organization has no spaces

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, terraform/datadog/aws.tf, terraform/datadog/datadog.tf
What
----
Currently if the RDS ultilisation monitor is triggered it will show for
both "prod" and "prod-lon". This is because it was only scoped to the
aws-account and we now have multiple things in each account.
To make this more intuitive, this change scopes the monitor to the same
region as the deploy_env. Since we do not expect to have multiple
deploy_envs within the same region this should result in alerts being
triggered for their respective deploy_env.
How to review
-------------
I have not tested this change as I didn't have a dev-env handy, so **please check/deploy to a dev env before merging**.
Who can review
--------------
=> [Support] Scope RDS disk utilisation monitor to region

concourse/pipelines/create-cloudfoundry.yml, config/service-brokers/aiven/config.json
What
----
We want to enable plan updates to the tenants
Include the changes from the PR [1] that fully
implements plan updates, and allow them in the
manifest.
[1] https://github.com/alphagov/paas-aiven-broker/pull/11
How to review
-------------
Code review
Who can review
--------------
Anyone
=> [#159845792] Bump Aiven broker and allow update plans

concourse/pipelines/create-cloudfoundry.yml
We want to be able to update the CC DB with the name of the key which
has been used to encrypt the values in it.
In the database's current state it is missing records for which key was
used to encrypt the values. This job is being added only temporarily to
fix the missing data. See [1,2] for more details.
Eventually, when we work out how we will do key rotations, the task in
this job should probably be run in the rotate-cloudfoundry-credentials
job. For now it is a standalone job to allow it to be run without
forcing you to do a full rotation.
[1] https://github.com/cloudfoundry/cf-deployment/pull/561
[2] https://github.com/cloudfoundry/cf-deployment/releases/tag/v2.9.0
This was split out from #1574 because the errand had a bug in it and we wanted to wait for the CF upgrade that included …
=> [#160556015] Rotation for cc db encryption key - Part 1.1

platform-tests/src/platform/acceptance/init_test.go
What
----
This commit improves the error output from a failed interaction with CF
during the running of the custom acceptance tests. We have been seeing some flakey tests and this should help in better understanding the cause.
How to review
-------------
Code review and optionally run through dev env.
Who can review
--------------
Not me
=> [SUPPORT] Improve error messages from tests

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/scripts/bosh_login.sh
What
----
We want to start using bosh with UAA. But using it seems to have
problem when we do a login first with `bosh login` and then
do not pass the `client` and `client-secret` to every command.
To workaround this, we decided to set the variables `BOSH_CLIENT` and
`BOSH_CLIENT_SECRET` in every job that uses bosh.
To fix this, we replace the script `bosh_login.sh` with the
corresponding snippet that sets the environment variables.
How to review
-------------
- Code review
- Run the pipeline
Who can review
--------------
anyone
=> [#161388997] Set BOSH_CLIENT* vars when using bosh

concourse/pipelines/create-cloudfoundry.yml
This reverts 86653a3c811f9169fc4b0bf12fd19d99f12dd695. It was not
reverted using `git revert` due to conflicts.
This health snapshot was broken when we enabled UAA in Bosh and would
have taken significant development time to fix. It is a maintenance
burden that is not currently delivering value, so it has been removed.
How to review
-------------
Who can review
--------------
@keymon
=> [#161411167] Remove health snapshot

manifests/cf-manifest/operations.d/260-cf-upgrade-cflinuxfs2.yml
What
----
This PR upgrades cflinuxfs2 to 1.244.0 in order to apply the
mitigations for USN-3800-1
How to review
-------------
Code review
Who can review
--------------
Not @LeePorte
=> [SUPPORT] Upgrade cflinuxfs2 to mitigate USN-3800-1

concourse/pipelines/create-cloudfoundry.yml, platform-tests/src/platform/acceptance/routes_test.go
What
----
We want to pre-assign a host '*' route for the main shared domains
(non-internal) into our admin org, so that no other tenant would be able to
register the wildcard domain.
This would prevent a potential issue if someone registers the wildcard for
any other application, potentially hijacking the traffic of apps being
unavailable, or any route not mapped yet.
For the time being the route remains unmapped, in the future we might want
to assign this to a custom application with some message and custom HTTP
status code.
We also add a custom acceptance test for this case.
How to review
-------------
- Code review
- Run the pipeline
- Check you cannot create a '*' route as a normal user:
```
DEPLOY_ENV=...
cf create-user testuser pass123
cf set-space-role testuser govuk-paas sandbox …
```
=> [#161716019] Pre-configure a wildcard hostname '*'

Makefile, platform-tests/src/platform/acceptance/routes_test.go, platform-tests/src/platform/availability/helpers/concourse.go
What
----
The staging pipeline failed because of a missing colon in the platform
tests - this sort of thing should be caught at unit test time. Because
we can't run the platform tests, we weren't even trying to compile them.
Using `go test -run ^$` makes go compile the test code, but doesn't run
any tests (because they don't match the empty string pattern).
Also fixing the missing colon that made the tests fail and an unrelated
error about `%s` that occurs with my version of the comiler.
How to review
-------------
* Code review
* Check the Travis build output to confirm it ran the new check
Who can review
--------------
=> Check that platform tests compile in test

manifests/prometheus/operations.d/222-monitor-cf-disable-cf-exporter.yml, manifests/prometheus/spec/operations/monitor_cf_spec.rb
What
----
We've discovered that this was DoSing the API. We're not replying on any
metrics from it at the moment, so we're going to disable it for the time
being until we have a need for it, at which point we can work out how to
configure this better.
How to review
-------------
* Code review is probably enough.
Who can review
--------------
Not me.
=> [Support] Disable Prometheus cf_exporter

scripts/reset-user.sh
What
----
In https://github.com/alphagov/paas-cf/pull/1584 we changed the
create-users.sh script to just create orgs, not users.
It turns out that script was also the canonical way of resetting users'
passwords -
https://team-manual.cloud.service.gov.uk/guides/common_support_tasks/#changing-a-user-39-s-password
I don't think it makes sense to use the same script for both tasks, so
here's another script that does more-or-less the same thing, but relies
on paas-admin to do the invite sending.
See
https://github.com/alphagov/paas-cf/blob/3579e0aa9f2c171b95be629a00a3c0b9c10fd8ee/scripts/create-user.sh
for the old implementation.
How to review
-------------
* Code review
* Try the script on a test user
Who can review
--------------
=> [#SUPPORT] Add a script to reset users' passwords

terraform/prod-lon.vpc_peering.json
What
----
Set up two new VPC peerings for DIT in prod-long, as per
https://govuk.zendesk.com/agent/tickets/3454682:
> Thanks for your response, and these are the details:
>
> Account ID: 588284153815
> VPC ID: vpc-03378ac5a1be3218d
> VPC CIDR: 172.16.0.0/22
> Org/Space: dit-services / tap
>
> Account ID: 604925858717
> VPC ID: vpc-0338ce744086cd767
> VPC CIDR: 172.16.4.0/22
> Org/Space: dit-services / datasci
The concourse pipeline runs:
```
ruby \
paas-cf/terraform/scripts/generate_vpc_peering_tfvars.rb \
"paas-cf/terraform/((deploy_env)).vpc_peering.json"
```
So even though the `prod-lon.vpc_peering.json` file is new it should
Just Work(TM).
How to review
-------------
* JSON review
* Check the tests pass
Who can review
--------------
=> [ZD3454682] Set up VPC peering for DIT London

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/lib/pagerduty.sh, concourse/scripts/pipelines-cloudfoundry.sh, concourse/tasks/smoke-tests-run.yml, scripts/upload-pagerduty-secrets.sh, terraform/datadog/concourse.tf
What
----
This PR modifies the pipeline to run the smoke tests in an attempts group with a email fired on each unsuccessful run of the tests. if 3 unsuccessful tests occur in a row Concourse will alert PagerDuty.
How to review
-------------
Code review
Upload PagerDuty secrets to your dev environment and run the pipeline on top of current master.
You should have emails on the paas-dev-alerts email address and then a followup from PagerDuty after 3 successive failures.
Before merging
--------------
Delete commit `7c99ba3` as this is only there for the purpose of reviewing.
Who can review
--------------
Not @LeePorte or @jpluscplusm
=> [#161387517] Concourse to alert PagerDuty on 24x7 continuous-smoke-test failures 

concourse/pipelines/create-cloudfoundry.yml
We were generating this keypair in the cloudfoundry pipeline if it
didn't already exist, but it's not used in this pipeline at all. It's
also generated in the create-bosh-concourse pipeline[1], and used there,
so it will always exist by the time this pipeline runs meaning that this
job is always a no-op.
Noticed this while tracking where secrets are used as part of the credhub work.
[1]https://github.com/alphagov/paas-bootstrap/blob/900d55b/concourse/pipelines/create-bosh-concourse.yml#L623
How to review
-------------
Code review is probably enough
Who can review
--------------
Not me.
=> Remove deployment-ssh-keypair from pipeline

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml, manifests/cf-manifest/operations.d/260-cf-upgrade-cflinuxfs2.yml, manifests/cf-manifest/operations.d/329-custom-capi-release.yml, manifests/cf-manifest/operations.d/350-diego-cell.yml, manifests/cf-manifest/operations.d/900-cf-cert-rotation.yml, manifests/cf-manifest/operations/datadog.yml, manifests/cf-manifest/scripts/generate-manifest.sh, manifests/cf-manifest/spec/manifest/env_spec.rb, manifests/cf-manifest/spec/manifest/release_versions_spec.rb, manifests/cf-manifest/spec/support/manifest_helpers.rb
What
----
We want to catchup our deployment and:
- upgrade to cf-deployment v6.0.0 [1] (now we are on v4.5.0
- upgrade the stemcell from Trusty to Xenial
We did not identify any major breaking change in the deployment.
During this upgrade:
- We had to update the datadog agent to work on Xenial. See https://github.com/alphagov/paas-datadog-agent-boshrelease/pull/14
- We had to create our own capi-release tarball (without changes) to workaround some issue with the upstream release. See https://github.com/cloudfoundry/cf-deployment/issues/663 and https://github.com/alphagov/paas-release-ci/pull/81
See commits for more info
[1] https://github.com/cloudfoundry/cf-deployment/releases/tag/v6.0.0
Related
--------
Bosh and stemcells upgrade: https://github.com/alphagov/paas-bootstrap/pull/210
and …
=> [#161544435] Upgrade to cf-deployment v6.0.0

concourse/pipelines/create-cloudfoundry.yml
What
----
Version 0.49.0 includes the location banner in the header
[1] https://github.com/alphagov/paas-admin/pull/114
How to review
-------------
Code review.
Version tagged in: https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-admin/jobs/tag-releases/builds/49
Who can review
--------------
Not me
=> [#160508552] Bump paas-admin to include location banner

terraform/prod.tfvars
What
----
AWS support:
> [I can] confirm that your ElastiCache Parameter Groups per Region limit in the
Ireland region is 100.
https://console.aws.amazon.com/support/v1#/case/?displayId=5516588401&language=en
How to review
-------------
* Sanity check
Who can review
--------------
=> [#SUPPORT] Update elasticache_cache_parameter_groups in prod

manifests/cf-manifest/env-specific/cf-default.yml, manifests/cf-manifest/env-specific/cf-prod-lon.yml, manifests/cf-manifest/env-specific/cf-prod.yml, manifests/cf-manifest/env-specific/cf-stg-lon.yml, manifests/cf-manifest/operations.d/370-scale-api.yml, manifests/cf-manifest/operations/scale-down-dev.yml, manifests/cf-manifest/spec/manifest/env_spec.rb
What
----
... and make sure they span three AZs.
We had an incident recently where enabling the prometheus cf_exporter
caused some API requests to time out. We think this wouldn't have been a
problem if the API instances had been scaled up.
We're going with 4 instances (rather than 3) so that there's enough
of a difference for us to notice any changes in our metrics.
We're not planning on re-enabling the cf_exporter as part of this story.
How to review
-------------
* Code review
* Observe that [`towers` has four API instances](https://deployer.towers.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/156)
Who can review
--------------
* Not @richardtowers
=> Scale API instances in production to 4

concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/uaa_set_email_domains.sh
The default allowlist for UAA's internal IDP only allows users with 4
parts in their email domain[1]. This means that UAA returns an error
when we (or an Org Manager) attempts to invide a user with 5 or more
components in their email domain.
It doesn't appear to be possible to configure this via UAA's config file
(as per a conversation on CF slack[2]), and therefore via the manifest,
so instead we have to add a post-deploy job to update this via UAA's
API. This extends the list to allow up to 6 components in the domain.
This should be enough for now, and it's reasonably simple to extend
further if needed.
[1]https://github.com/cloudfoundry/uaa/blob/4.24.0/server/src/main/java/org/cloudfoundry/identity/uaa/util/DomainFilter.java#L103 …
=> [#162113648] UAA: allow emails with more than 4 domain parts

terraform/datadog/cloud_controller.tf
What
----
During a recent incident we had a monitor which overloaded the API.
Afterwards we could see that the latency was much higher than normal
during the incident, but we didn't have a monitor for this so we didn't notice.
Once the API's performance fell below a certain point it started failing
its healtcheck and getting unregistered from gorouter.
The thresholds we've chosen here were picked so that they would not warn
under average conditions but would have been critical during the incident
See https://app.datadoghq.com/notebook/63780/Cloud%20Controller%20outage%20metrics
How to review
-------------
* Code review
* See the monitors in datadog for `towers`:
* https://app.datadoghq.com/monitors/7279410
* https://app.datadoghq.com/monitors/7279438
Who can review
--------------
Not …
=> [#162013441] Add monitors for cloud controller latency and unregistrys

scripts/cf_subshell_scoped_login.sh
This script points CF_HOME to a temporary directory to create an
indipendent login for the subshell. This has the side-effect of hiding
any cli plugins that are installed. To avoid this, this PR adds a
symlink back to plugins directory so that they can be found.
How to review
-------------
* Code review
* use the cf_subshell_scoped_login scipt, and verify that `cf plugins` still returns any plugins you have installed.
Who can review
--------------
Not me.
=> [Support] Make installed cf cli plugins available in subshell script

concourse/pipelines/create-cloudfoundry.yml
What
----
As of https://github.com/alphagov/paas-billing/pull/56 there are 2 apps for the API and the data collector. This commit deploys both during `post-deploy`, using the appropriate strategy to deliver HA and non-HA uptime as required by the apps' consumers.
How to review
-------------
- Code review
- Run down a dev pipeline, probably as part of validating https://github.com/alphagov/paas-billing/pull/56 
- After this has run in prod, the `FIXME` line in the concourse pipeline can be PR'd away. It's harmless to leave there, however.
Who can review
--------------
Anyone except @jpluscplusm or @bandesz
=> [#161316533] Deploy 2 separate apps from paas-billing

terraform/datadog/cloud_controller.tf
The first version of the monitor was too sensitive and was making a lot of
noise.
We decided to increase the thresholds by 50 ms and only consider the average of
all gorouter latencies.
Code review should be enough.
Not me.
=> [#162013441] Fine-tune "Cloud Controller latency as reported by gorouter" DataDog monitor

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/tasks/remove-db.yml
What
----
On #1629 we splitted the paas-billing in two different deployed
apps, so that we can run the API in HA and the collectors as
single instance.
But the autodelete-deployment needs to unbind all the apps to
delete the service, and now we have two apps bound to the same
service.
We extend the remove-db.yml task to accept a list of BOUND_APPS
to unbind, instead of only one app.
How to review
-------------
Code review.
I run the autodelete here: https://deployer.hector.dev.cloudpipeline.digital/teams/main/pipelines/autodelete-cloudfoundry/jobs/delete/builds/161
You can run your own, but you need to update the paas-cf branch in the
pipeline for `autodelete-cloudfoundry.yml`
Who can review
--------------
Not me
=> [#162233928] Unbind splitted paas-billing before delete

concourse/pipelines/create-cloudfoundry.yml, config/accounts/README.md, config/accounts/documents/terms-of-use.md
What
----
paas-accounts has a database containing documents that users should
agree to when they start using PaaS.
Because the documents are uploaded to the API manually in each
environment the environments don't all match.
Currently the terms of service is present in Ireland, but not London.
This adds the essential documents (that you would expect to exist in
every environment) to paas-accounts through the pipeline.
The API call is a PUT, so it should be safe to call it every time the
pipeline runs (although it will overwrite any edits made through the API
between deployments).
How to review
-------------
* Code review
* Run this down a dev pipeline
* Invite a new user in paas-admin for you dev env (use your email with a + on the end)
and observe that when you log in you see the terms …
=> [#161981619] Upload paas-accounts documents from the pipeline

concourse/pipelines/create-cloudfoundry.yml, manifests/prometheus/alerts.d/600-syslog_drains.yml, manifests/prometheus/operations.d/300-alertmanager-smtp.yml, manifests/prometheus/operations.d/310-alertmanager-routes.yml, manifests/prometheus/scripts/generate-manifest.sh, manifests/prometheus/spec/fixtures/prometheus-vars-file.yml, manifests/prometheus/spec/support/manifest_helpers.rb
What
----
Here we add a basic example of one alert using syslog drains on
prometheus and alertmanager.
We include a new directory `manifests/prometheus-manifest/alerts.d`
where one file per alert can be added.
We also setup receivers for email, that would allow to
configure notification for any alert. To do so, the alert must
add a new label `notify: ` including the words `email`.
How to review
-------------
Deploy this. Try to trigger the alert by, for instance, doing:
```
cf target -o admin -s billing
for i in $(seq 1 300); do
cf cups test-syslog-$i -l syslog://127.0.0.1.xip.io
cf bind-service paas-accounts test-syslog-$i
fone
```
To trigger alerts and test only the receivers, you can use
the following script:
https://gist.github.com/keymon/2dcfc653bd0e2099fda589cb19e983a3
Who can …
=> [#162157392] Add alert for Syslog Drains in prometheus

manifests/prometheus/alerts.d/700-cloud_controller_unregistry.yml, terraform/datadog/cloud_controller.tf
What
----
Datadog doesn't like sparse metrics, so we were unable to write this
alert there.
Hopefully with the `or vector(0)` thing in Prometheus this should be
more reliable.
How to review
-------------
* Code review
* Run it down a dev pipeline
* `monit stop cloud_controller_ng` to see the alert fire.
Who can review
--------------
=> Move CC unregistry alerts from datadog to prometheus

.travis.yml, concourse/scripts/set_pipeline_ordering_test.go
What
----
We've just upgraded paas-bootstrap to 1.11[1] because it was still on 1.6
which doesn't work with recent gomega versions.
It makes sense to also upgrade this repo so that they're consistent.
[1]alphagov/paas-bootstrap#221
How to review
-------------
Code review. Verify Travis passes.
Who can review
--------------
Not me.
=> [Support] Upgrade Go version for unit tests to 1.11

concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/tasks/forget-access-keys.yml, concourse/tasks/terraform_destroy_datadog.yml, terraform/cloudfoundry/metrics-exporter.tf, terraform/cloudfoundry/prometheus.tf, terraform/cloudfoundry/smtp.tf
What
----
This upgrades the AWS Terraform provider, and also resolves a couple of FIXMEs relating to this.
This is a precursor to switching to using Terraform to generate ACM certs. The version of the provider we're currently running doesn't support the necessary resources to enable this.
How to review
-------------
* Run the pipeline from this branch.
* Verify everything works etc.
* Merge https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/145
* Update the TMP commit to point the the relevant Docker image tag.
Who can review
--------------
Not me.
=> [#161184357] Upgrade AWS Terraform provider

manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
This PR updates the versions of cflinuxfs in order to mitigate usn-3829-1
see [the security page](https://www.cloudfoundry.org/blog/usn-3829-1/)
for further info.
How to review
-------------
Code review
Check against https://bosh.io/releases/github.com/cloudfoundry/cflinuxfs3-release and https://bosh.io/releases/github.com/cloudfoundry/cflinuxfs2-release
Who can review
--------------
Not @LeePorte
=> [#162299527] Update cflinuxfs release to mitigate usn-3829-1

concourse/pipelines/create-cloudfoundry.yml, terraform/cloudfoundry/acm.tf, terraform/cloudfoundry/elbs.tf
What
----
This moves the ACM cert management into Terraform because it's much more robust than our set of scripts.
Previously, the apps cert was generated by paas-bootstrap so that we didn't need to duplicate the scripts into this repo. That's no longer a concern when using Terraform, so it makes sense for the apps cert to be generated here as this is where it's used...  The system domain cert is used by both this repo and paas-bootstrap, so that remains in paas-bootstrap.
This additionally includes a temporary commit to import the existing apps cert into Terraform to prevent it attempting to create a second one.
How to review
-------------
* https://github.com/alphagov/paas-bootstrap/pull/222 should be reviewed and merged/deployed first.
* Run the pipeline from this branch
* Verify …
=> [#161184357] Use Terraform to create ACM certs.

manifests/cf-manifest/operations.d/319-custom-networking-release.yml, manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
Our deployment is affected by the bug described in
https://github.com/cloudfoundry/cf-networking-release/issues/59
some tenants assigned to more than 50 spaces cannot see some policies
in some specific spaces.
In this PR we want to deploy a forked version with a proposed patch
as in:
https://github.com/cloudfoundry/cf-networking-release/pull/60
Additionally, as it seems common to add new releases, I refactored the test to check the release versions to make it easier to pin older versions. 
How to review
-------------
Code review
Try to reproduce the issue as described in:
https://github.com/cloudfoundry/cf-networking-release/issues/59
Deploy this, and check that fixes the issue.
Who can review
--------------
Not me
=> [#162275131] cf-networking-release hotfix for paginated spaces

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/scripts/generate-manifest.sh, manifests/cf-manifest/spec/support/manifest_helpers.rb, manifests/prometheus/scripts/generate-manifest.sh
What
----
We want to be able to rotate the prometheus secrets generated
by bosh during the prometheus deployment.
As we store the secrets in a vars-store.yml file,
we reuse the script used for the cf-manifest:
manifests/cf-manifest/scripts/rotate-vars-store-secrets.rb
This script requires a version of the manifest without the variables
expanded, so we update the render-manifest.sh script to be able
to render the manifest without variables, and we pass the
right arguments as needed.
The rendered manifest without variables is stored as a resource
in the S3 bucket.
Note that currently the prometheus-vars-store only contains a set
of plain passwords, we do not use the `*_old` vars, and we do not
keep any variable. That is effectivelly like deleting all the
vars-store.yml file. But we decided …
=> [#160175665] Add job to rotate prometheus credentials

concourse/pipelines/create-cloudfoundry.yml
What
----
This reverts the temporary commit from #1652 that migrated the manually created certs into Terraform.
How to review
-------------
* ~~Rebase this after #1652 is merged~~ (done)
* Verify everyone has run the migration process
* Code review - does this revert the correct things.
Who can review
--------------
Not me.
=> [#161184357] Cleanup after migration to Terraform for ACM certs.

concourse/pipelines/create-cloudfoundry.yml
We initially introduced this job without it blocking the pipeline
because prometheus was an experimental thing. It's now something we rely
on, so we should block the pipeline on the job so that we catch broken
config in staging before it reaches prod.
How to review
-------------
Code review should be enough. I've pushed this change to my dev env.
Who can review
--------------
Not me.
=> [#162475243] Block pipeline on prometheus-deploy failures

manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml, manifests/cf-manifest/operations.d/040-set-tags.yml, manifests/prometheus/operations.d/040-set-tags.yml, terraform/cloudfoundry/cdn_broker.tf
What
----
We want to get the fixes for:
- https://www.cloudfoundry.org/blog/usn-3816-2/
- https://www.cloudfoundry.org/blog/usn-3816-3/
- https://www.cloudfoundry.org/blog/usn-3836-2/
Andras edit: I also pulled in some minor changes that we add the `deploy_env` everywhere. The new tag will only be added when the EC2 instances are recreated. 
How to review
-------------
code review.
Who can review
--------------
not me
=> [#162501716] Bump Stemcell to 170.12 with fixes for some CVEs

manifests/cf-manifest/operations.d/510-add-prometheus-blackbox-exporter.yml, manifests/prometheus/alerts.d/dns-resolution-time.yml, manifests/prometheus/alerts.d/dns-resolution-working.yml, manifests/prometheus/operations.d/512-scrape-dns-resolution.yml
What
----
- Added blackbox-exporter to cloudfoundry deployment
- Configured prometheus to scrape blackbox-exporter for DNS metrics (against bosh-dns endpoint)
- Added alerts to trigger when DNS is failing / slow
- Response time:
- 0.1s (Warning)
- 0.2s (Critical)
- Workingness:
- 25% fail over 5 minutes (Warning)
- 75% fail over 5 minutes (Critical)
See commits for more details.
How to review
-------------
- Code Review
- Run branch down a dev pipeline
- Ensure Alerts (`DNS.*`) are present in prometheus
- Run `monit stop bosh-dns` on any cf VM, and ensure alert fires within 5 minutes.
Who can review
--------------
Not @tnwhitwell / @richardTowers
=> [#161412619] Prometheus monitor dns

concourse/pipelines/create-cloudfoundry.yml, concourse/tasks/forget-access-keys.yml, config/cloudwatch-exporter/config.yml, manifests/prometheus/operations.d/301-scrape-cloudwatch-exporter.yml, terraform/cloudfoundry/outputs.tf, terraform/cloudfoundry/yace.tf
Deploy https://github.com/alphagov/paas-yet-another-cloudwatch-exporter to collect CloudWatch metrics and make them available for Prometheus.
Additional changes:
- add the `deploy_env` tag to all EC2 instances in the CF and Prometheus Bosh deployments (this is not used yet as the instances needs to be recreated to get the new tag)
For now we use the `deployment` EC2 tag for filtering, but in dev one env will get the metrics from all Prometheus, Concourse and Bosh instances. Later if a stemcell update recreates all instances we can depend on the new `deploy_env` tag.
❕ https://github.com/alphagov/paas-aws-account-wide-terraform/pull/144 - already reviewed and merged.
1. Review: https://github.com/alphagov/paas-bootstrap/pull/225
2. Run the create-cloudfoundry pipeline from this branch
3. …
=> [#162303736] Deploy the yace CloudWatch exporter and scrape it with Prometheus

platform-tests/src/platform/acceptance/apps_domain_dns_tls_test.go, platform-tests/src/platform/acceptance/init_test.go
What
----
Added some tests to check that the CDN broker's assumptions about the apps apex domain are valid:
- DNS A records are the same as the `apps.` domain
- Certificate for apex domain is valid, and contains the correct SAN
How to review
-------------
- Code Review
- Ensure tests pass in pipeline (Use [this](https://deployer.tnw.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/custom-acceptance-tests/builds/8) as an example if you want!)
Who can review
--------------
Not @tnwhitwell / @richardTowers
=> [#161511720] Apps Apex domain DNS and Cert SAN checks

manifests/prometheus/alerts.d/diego_cell_available_cpu_idle.yml, manifests/prometheus/alerts.d/diego_cell_available_memory.yml
What
----
In `528417be` we record a metric and alert on it per-diego-cell, but we actually want to alert on the average *aggregate* memory that the cells have free.
We can do this by recording a new derived metric (per-VM, recorded for all VMs regardless of purpose), averaging it across all our diego cells and comparing the resulting percentage against the existing 50% and 55% thresholds.
NB This is only valid as long as our diego cells are (memory-)homogenous!
How to review
-------------
- code review
- push to a dev env (`jonmtest` has it running currently, if you want to speed this up)
- maybe push a `[DELETE]` commit with 100%/99% thresholds to force it to fire. `jonmtest` env has already done this, however. Your call.
Who can review
--------------
Anyone except @jpluscplusm.
=> [#162199780] Alert on average total diego-cell memory used

concourse/pipelines/create-cloudfoundry.yml, manifests/prometheus/dashboards.d/user-impact.json, terraform/cloudfoundry/prometheus.tf
What
----
Added User Impact dashboard to Grafana to replace the current Datadog dashboard view
How to review
-------------
1. Run the pipeline against a deployment
2. In Grafana (https://grafana.${deployment_domain}), ensure "User Impact" dashboard is available to view (`/d/paas-user-impact/user-impact`) and shows the same information as the current Datadog one.
Who can review
--------------
Anyone but @tnwhitwell, @richardTowers & @jpluscplusm
=> [#162381973] Prometheus user impact dashboard 

manifests/prometheus/operations.d/230-do-not-monitor-concourse.yml
What
----
We're not currently running a prometheus exporter on concourse, so this
scraper is erroring.
We may decide to re-enable this once datadog is turned off and we can
enable the prometheus exporter on concourse.
How to review
-------------
* Code review
* Observe that the PrometheusScrape error does not fire *for Concourse* in
environments where this branch has been deployed (e.g.  https://prometheus.towers.dev.cloudpipeline.digital/alerts)
Who can review
--------------
=> Remove prometheus scraping of concourse

manifests/cf-manifest/cloud-config/000-base-cloud-config.yml, manifests/prometheus/operations.d/001-set-retention.yml, manifests/prometheus/operations.d/100-set-persistent-disks.yml, manifests/prometheus/spec/operations/set_persistent_disks_spec.rb
We decided to have a data retention period of 15 months, so we can look back at least a year (and some).
Based on our current usage we store ~120Mb/day, which would be 54G for 15 months. We want to leave some room for growing, so we'll attach a 100Gb disk as data storage.
Also after reading [1] I decided to explicitly set the max-block-duration to 7 days, as the default 45 days seemed unnecessarily high.
[1] https://github.com/prometheus/prometheus/issues/4110
1. Deploy Prometheus from your pipeline.
2. Check if the retention/max-block-duration values are correctly set (https://prometheus.$DEPLOY_ENV.dev.cloudpipeline.digital/flags)
3. Check that you didn't loose any data after the migration
Not me.
=> [#162540011] Set Prometheus data retention to 450 days

terraform/datadog/general.tf
What
----
The "overlay" device is for the containers of the applications, and
the space is restricted to the allowed disk for the application.
We do not want to alert if an application runs out of space, that
is up for the tenant to monitor.
Because that, we also ignore the overlay device.
Example output of a df command:
overlay             1024   998        27  98% /var/vcap/data/grootfs/store/unprivileged/images/ab308816-7857-4c76-5020-9114/rootfs
How to review
-------------
Code review
Who can review
--------------
Not me
=> [#SUPPORT] Ignore "overlay" device in disk-space alert

manifests/prometheus/alerts.d/dns-resolution-time.yml
What
----
The previous metric was concerned with lookup time from the bosh DNS
cache rather than the full resolution process.
How to review
-------------
Code review and compare graphs in story
Who can review
--------------
anyone
=> [#161412619] Switch metric used for DNS resolution

manifests/prometheus/operations.d/050-set-external-urls.yml
What
----
Grafana is not allowed to access Prometheus through the ELB, so we should still
use the internal address.
How to review
-------------
Quick deploy test
Who can review
--------------
Not me.
=> Do not use the external url for the Prometheus data source in Grafana

Makefile, concourse/pipelines/create-cloudfoundry.yml, manifests/prometheus/operations.d/240-grafana-monitoring-user.yml
What
----
Added the pre-seeding of a `mon` user to grafana, to remove the need for monitoring screens to be logged in to the grafana dashboard as _admin_.
How to review
-------------
1. Run the pipeline from this branch
1. Retrieve the `GRAFANA_MON_PASSWORD` with `make dev showenv`
1. Login to grafana with `mon`/`$GRAFANA_MON_PASSWORD`
1. Ensure you can view "User Impact - $env" dashboard with r/o permissions
Who can review
--------------
Not me
=> [#162551292] Grafana monitoring board user

platform-tests/src/platform/acceptance/tls_version_test.go
What
----
We want to ensure that our SSL endpoints for apps and system
only offer TLS 1.2.
We add a custom acceptance test that would check for all the old
disabled protocols, and expect failure.
How to review
-------------
Code review, test by changing the policy of the ELB in your environment.
Who can review
--------------
Not me
=> [#162604166] Add a test to check we only offer TLS 1.2

manifests/prometheus/alerts.d/concourse-check-certificates-errors.yml, manifests/prometheus/alerts.d/concourse-check-certificates-failures.yml, manifests/prometheus/alerts.d/concourse-check-certificates-no-data.yml, manifests/prometheus/alerts.d/concourse-smoketests-errors.yml, manifests/prometheus/alerts.d/concourse-smoketests-failures.yml, manifests/prometheus/alerts.d/concourse-smoketests-no-data.yml, manifests/prometheus/operations.d/230-do-not-monitor-concourse.yml
Reenable the Prometheus scraping for Concourse and migrate the continuous-smoke-tests and check-certificate monitors from DataDog.
The original `job` label collides with the Bosh job's `job` label, therefore it will be renamed to `exported_job`. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cscrape_config%3E - `honor_labels ` to understand why.
I decided to record a more complex expression like:
```
sum(
concourse_builds_finished{exported_job="check-certificates",pipeline="create-cloudfoundry",status="errored"}
or
(absent(concourse_builds_finished{exported_job="check-certificates",pipeline="create-cloudfoundry",status="errored"})-1)
)
```
as this way we'll have 0 values if Concourse doesn't report anything for a specific metric (it starts to report one …
=> [#162448881] Enable scraping Concourse metrics in Prometheus, add related missing alerts

manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
Medium
Canonical Ubuntu
*   Canonical Ubuntu 14.04
It was discovered that pixman incorrectly handled the general_composite_rect function. A remote attacker could use this issue to cause pixman to crash, resulting in a denial of service, or possibly execute arbitrary code.
CVEs contained in this USN include: CVE-2015-5297
_Severity is medium unless otherwise noted._
*   All versions of Cloud Foundry cflinuxfs2 prior to 1.255.0
Users of affected products are strongly encouraged to follow one of the mitigations below:
*   The Cloud Foundry project recommends that Cloud Foundry deployments run with cflinuxfs2 version 1.255.0 or later.
*   [USN-3843-1](https://usn.ubuntu.com/3843-1)
*   [CVE-2015-5297](https://people.canonical.com/~ubuntu-security/cve/CVE-2015-5297)
How to review …
=> Upgrade cflinuxfs2 to fix CVE-USN-3843-1

manifests/prometheus/dashboards.d/user-impact.json
What
----
We originally set up the "Firing alerts" panel to replace "no data" with
"N/A". This is a bit confusing, because really when there's no data it
means "0 alerts". To make matters worse, if the alerts fire the panel
goes red, but the transition from firing to not firing doesn't reset the
color.
Much better to set the panel to 0 if there's no data (which can be done
with `or vector(0)`). I also noticed that the thresholds were wrong (it
was showing as orange when there were 0 alerts).
How to review
-------------
* Code review
* See my dashboard (which was deployed through the pipeline) -
https://grafana.towers.dev.cloudpipeline.digital/d/paas-user-impact/user-impact-towers
Who can review
--------------
=> Fix firing alerts N/A on prometheus dashboard

platform-tests/src/platform/acceptance/tls_version_test.go
What
----
This PR adds in the doppler and concourse endpoints to the TLS tests. This is to verify that our ELBs are configured with the correct policies.
How to review
-------------
Run it through dev
Who can review
--------------
@alext
=> [#162604166] Add Doppler and concourse to TLS testing

manifests/prometheus/alerts.d/aws-elb-unhealthy-nodes.yml, manifests/prometheus/alerts.d/gorouter-latency.yml
They were producing the following error when rendering:
```
<error expanding template: error parsing template __alert_GorouterLatency_Warning: template: __alert_GorouterLatency_Warning:1: unexpected "\\" in operand>
```
The string isn't quoted, and yet the embedded quotes are escaped
resulting in them being rendered in the config file as:
```
Gorouter latency is too high ({{ $value | printf \\\"%.0f\\\" }} ms\") on {{ $labels.bosh_job_ip }}
```
There's also a spurious " in the GoRouter alert.
How to review
-------------
Who can review
--------------
Not me.
=> Fix quoting in some alert descriptions

manifests/cf-manifest/env-specific/prod.yml
Rep's advertised available memory capacity is currently dipping below
33%, so we should scale up to ensure availability in the case of an AZ
failure as per ADR021
https://team-manual.cloud.service.gov.uk/architecture_decision_records/ADR021-cell-capacity-assignment-2/
How to review
-------------
Code review. Verify I can add 3 to a number correctly...
Who can review
--------------
Not me.
=> [Support Add 3 more cells in prod

concourse/pipelines/create-cloudfoundry.yml
This has been run everywhere, so is no longer needed.
This reverts commit c84b8ba66074021ee03574df88c6fc72e5e4702f from #1688 
How to review
-------------
* Code review
* Verify that #1688 has been deployed everywhere
Who can review
--------------
Not me.
=> [#162381976] Cleanup Temporary task to cleanup datadog state from bucket

concourse/pipelines/create-cloudfoundry.yml, config/logit/11_app_syslog_drain.conf, config/logit/output/generated_logit_filters.conf, scripts/generate_logit_filters.sh
# What
We set up a syslog drain and bind it to the paas-admin app.
Also we add some logstash filters so the RTR/APP logs are properly processed.
1. Run `make logit-filters` and make sure the `config/logit/output/generated_logit_filters.conf` file didn't change.
2. Apply the contents of the `config/logit/output/generated_logit_filters.conf` to the dev Logit account. (See https://team-manual.cloud.service.gov.uk/guides/editing_logstash_filters/)
3. Run at least the `post-deploy` job from this branch on your dev
4. Generate some traffic on your admin and check the logs in Kibana with filtering for `tags: logmessage`
All Logstash configs will need to be updated manually for all envs. (See https://team-manual.cloud.service.gov.uk/guides/editing_logstash_filters/)
Not me.
=> [#161420552] Send PaaS Admin logs to Logit

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/pipelines-cloudfoundry.sh, manifests/prometheus/operations/disable-email.yml, manifests/prometheus/scripts/generate-manifest.sh
What
----
We want to stop the dev environments from sending email notifications
unless enabled.
We disable the notifications for the smoke tests and for the alert
manager, by adding a new parameter ENABLE_ALERT_EMAILS, that
is true by default and set to false in dev.
In prometheus, setting ENABLE_ALERT_EMAILS would add an opsfile
that removes the email_configs from the alert manager.
How to review
-------------
Code review
Who can review
--------------
Not me
=> [#162156376] Disable email alerts on development environments

manifests/cf-manifest/operations.d/510-add-prometheus-blackbox-exporter.yml
What
----
We had the github sha1 in the manifest despite pulling the release from
bosh.io. This commit updates it to keep it in sync.
How to review
-------------
Check the sha1 against [the bosh.io release](https://bosh.io/releases/github.com/cloudfoundry-community/prometheus-boshrelease?version=23.1.0)
Who can review
--------------
Anyone
=> Update prometheus sha1 to use bosh.io

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/320-cc-database-key-rotation.yml, manifests/cf-manifest/operations.d/331-uaa-database-key-rotation.yml, manifests/cf-manifest/operations.d/400-errands.yml, manifests/cf-manifest/scripts/rotate-vars-store-secrets.rb, manifests/cf-manifest/spec/manifest/database_encryption_keys_spec.rb, manifests/cf-manifest/spec/scripts/rotate-vars-store-secrets_spec.rb
What
----
Cloud Foundry is gradually starting to support multiple encryption keys for easier rotation. There are two types of encryption key for which this is supported we know of:
1. [UAA 4.13.0 introduced a new, required, passphrase for encryption keys used to encrypt UAA's MFA tokens](https://github.com/cloudfoundry/uaa-release/releases/tag/v58).
2. [CF release 2.9.0 changed](https://github.com/cloudfoundry/cf-deployment/releases/tag/v2.9.0) how the cloudcontroller database encryption key is specified.
Both of these support specifying multiple keys.
In this PR we implement what is needed to support the rotation of these
credentials:
1. We add a new dedicated job `rotate-db-encryption-key`
2. Configure the required errands to rotate the secrets in DB.
3. Configure the manifest to …
=> [#158179141] Implement rotation of DB encryption keys for CC and UAA

manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
The CVE usn-3840-1 [1] affects stemcells prior 170.14. We update
to the latest available stemcell.
[1] https://www.cloudfoundry.org/blog/usn-3840-1/
How to review
-------------
Code review
Who can review
--------------
Not me
=> [#162869390] Update to stemcell 170.15 to cover usn-3840-1

concourse/pipelines/create-cloudfoundry.yml, concourse/tasks/delete_admin.yml, scripts/cleanup-deleted-cf-users.sh
We have a lot of users in CF which don't exist in UAA. These users don't have a username field in the CF API response.
Most of these users are created by the continuous smoke tests. When the tests finish we delete the user with itself but we failed to recognise that the user is not fully deleted.
We'll change the helper tasks to delete the temporary admin user with the global admin.
If the admin user's credentials are rotated the smoke tests could fail, therefore we make sure the creds rotation and the smoke tests don't run at the same time and also the continuous smoke tests always use the latest credentials/manifest variables.
I created a script to clean up the left-over users under `scripts/clean_up_cf_users.sh`.
A user:
* will be skipped if a guid is not a UUID (some UAA clients)
* …
=> [#162265546] Clean up left-over CF users

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/destroy-cloudfoundry.yml, manifests/cf-manifest/operations.d/320-cc-database-key-rotation.yml, manifests/cf-manifest/operations.d/331-uaa-database-key-rotation.yml, manifests/cf-manifest/spec/manifest/database_encryption_keys_spec.rb
What
----
In https://github.com/alphagov/paas-bootstrap/pull/230 we migrated
to bosh-deployment and generate the secrets using `bosh interpolate`.
The bosh secrets are now stored in the file `bosh-vars-store.yml`
We update wherever we consume these secrets in the current project.
Dependencies
-------------
- Based on: https://github.com/alphagov/paas-cf/pull/1693 and
https://github.com/alphagov/paas-cf/pull/1692, rebase once merged.
- Review and merge first https://github.com/alphagov/paas-bootstrap/pull/230
How to review
-------------
Code review
Test the pipeline
Who can review
--------------
Not me
=> [#161591823] Consume bosh client password from bosh-vars-store.yml

concourse/pipelines/create-cloudfoundry.yml
This task was running in the same aggregate block as the task that
creates the space it uses - it was therefore erroring on a new
deployment because the public space didn't exist.
Combining it into the create-orgs task prevents this race.
I chose not to simply move it into the next aggregate block because that
contains app deployment tasks that require this service to be present.
How to review
-------------
Code review should be enough.
Who can review
--------------
Not me.
=> Fix creation of logit-syslog-drain for new envs.

scripts/org-usage-report.sh
What
----
Use the $CF_HOME env var in org-usage-report.sh.
This way we can run the script from a subshell created by the cf_subshell_scoped_login.sh script.
How to review
-------------
Code review and/or run the script
How to merge
---------
It’s okay to merge it from the Github UI by adding `[skip ci]` to the merge commit message
Who can review
--------------
Anyone
=> [SUPPORT] Use the $CF_HOME env var in org-usage-report.sh

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
* update the rds-broker to support restarting RDS instances
* update the rds-broker-metrics-collector to be more resilient and handle sql query timeouts properly
* fix the bosh release so the `sql_metrics_collector_interval` and `cloudwatch_metrics_collector_interval` config values are correctly written into the config json (this fix will change the effective sql metrics collection interval to 1 minute)
How to review
-------------
Review the following PRs first (these were partially reviewed by me):
* https://github.com/alphagov/paas-rds-broker/pull/94
* https://github.com/alphagov/paas-rds-metric-collector/pull/16
* https://github.com/alphagov/paas-rds-broker-boshrelease/pull/76
1. Deploy the pipeline from this branch
1. Check if the metrics collector still works as expected
1. …
=> [#162475628] Update the rds broker bosh release

concourse/pipelines/create-cloudfoundry.yml, manifests/prometheus/alerts.d/ec2_cpu_credits.yml, manifests/prometheus/alerts.d/rds_cpu_credits.yml, manifests/prometheus/alerts.d/rds_disk_utilisation.yml
What
----
* we've upgraded yace (https://github.com/ivx/yet-another-cloudwatch-exporter) to 0.11.1
* we added timestamps to yace, so Prometheus can scrape the AWS metrics with the correct timestamps
* we amended the existing AWS related Prometheus alerts as the metric names have changed
How to review
-------------
1. Review https://github.com/alphagov/paas-yet-another-cloudwatch-exporter/pull/1 first
1. Deploy your CF from this branch
1. Check if you still get data for: `aws_ec2_cpucredit_balance_minimum`, `aws_rds_cpucredit_balance_minimum`, `aws_rds_free_storage_space_minimum`
1. Check `https://cloudwatch-exporter.${DEPLOY_ENV}.dev.cloudpipelineapps.digital/metrics` whether the metrics have the promised timestamps (excluding the `*_info` ones and `yace_cloudwatch_requests_total`)
How to …
=> [#162507264] Add timestamp support to the cloudwatch-exporter

manifests/cf-manifest/env-specific/prod-lon.yml
What
----
As tenants have been migrating from Ireland to London we've been using
more of the available capacity. We're now at the point where we need to
scale up.
See this graph:
https://prometheus.london.cloud.service.gov.uk/graph?g0.range_input=8w&g0.expr=rep_memory_capacity_pct%3Aavg5m&g0.tab=0
How to review
-------------
* Code review
* Check that you agree that we need to scale based on [the prometheus graph](https://prometheus.london.cloud.service.gov.uk/graph?g0.range_input=8w&g0.expr=rep_memory_capacity_pct%3Aavg5m&g0.tab=0)
Who can review
--------------
=> Increase number of cells in London to meet demand

manifests/prometheus/alerts.d/bosh-high-cpu-utilisation.yml, manifests/prometheus/alerts.d/cc-latency-by-gorouter.yml, manifests/prometheus/alerts.d/cloud-controller-unregistry.yml, manifests/prometheus/alerts.d/dns-resolution-time.yml, manifests/prometheus/alerts.d/dns-resolution-working.yml, manifests/prometheus/alerts.d/gorouter-latency.yml, manifests/prometheus/alerts.d/router_total_routes.yml
What
----
The following alerts were amended so we'll get less noise:
* BOSHJobHighCPULoad
* GorouterLatency_Warning
* GorouterLatency_Critical
* CloudControllerLatencyByGorouter_Warning
* CloudControllerLatencyByGorouter_Critical
* CFCloudControllerUnregistry
* RouterTotalRoutesDiscrepancy
* DNSResolutionWorking_Warning
* DNSResolutionTime_Critical
How to review
-------------
1. Code review
1. Deploy your CF from this branch (running the prometheus-deploy with `make run_job` should be enough)
Who can review
--------------
Not me.
=> [#163113585] Fix noisy alerts

concourse/pipelines/create-cloudfoundry.yml
The bug fix issused for #162443556 incremented the paas-admin version to 0.51.0. This commit bumps the version in paas-cf to match.
What
----
Bumps the paas-admin version to 0.51.0 in order to deploy
How to review
-------------
Check the tag on paas-admin matches the version here
Who can review
--------------
Not @AP-Hunt
=> Bumps paas-admin version to 0.51.0

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml, manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml, manifests/cf-manifest/operations.d/319-custom-networking-release.yml, manifests/cf-manifest/operations.d/329-custom-capi-release.yml, manifests/cf-manifest/operations.d/330-uaa.yml, manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml, manifests/cf-manifest/operations.d/900-cf-cert-rotation.yml, manifests/cf-manifest/spec/manifest/base_properties_spec.rb, manifests/cf-manifest/spec/manifest/release_versions_spec.rb, manifests/cf-manifest/spec/support/manifest_helpers.rb
* We've upgraded CF from 6.0.0 to 6.10.0
* We found a security notice in the stemcell changelogs, so we upgraded to 170.19 (both in paas-cf and paas-bootstrap)
* We found another security notice in the cflinuxfs* changelogs, so we upgraded these to 1.259.0 and 0.50.0
* There were some new ca_cert params in the Manifest, so we added those to the certificate rotation opsfile
* we've removed the custom cf-networking release as our last patch is now included in this CF release
* we couldn't remove the custom capi release as we still encountered the same packaging errors like the last time (Alex opened https://github.com/cloudfoundry/bosh/issues/2118)
* The default runtime wrapper in Garden changed to containerd from garden-runc.
* Apps have annotations
* Spaces have experimental support for …
=> [#163220697] Upgrade CF to 6.10.0

.travis.yml, manifests/prometheus/alerts.d/gorouter-latency.yml, manifests/prometheus/spec/alerts/bosh-high-cpu-utilisation.test.yml, manifests/prometheus/spec/alerts/concourse-smoketests-errors.test.yml, manifests/prometheus/spec/alerts/gorouter-latency.test.yml, manifests/prometheus/spec/alerts_validation_spec.rb
What
----
Adds a handful of tests for Prometheus alerts using `promtool` https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/
How to review
-------------
Code review (https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/), check tests pass locally (`cd manifests/prometheus && bundle exec rspec`) and passes on Travis.
Who can review
--------------
Not me or @richardTowers
=> [#162446918] Creates a handful of Prometheus alert tests

terraform/cloudfoundry/rds_broker.tf
We've had tenants requesting this extension be added. Unlike some
extensions, it can't merely be enabled using `CREATE EXTENSION`, it
requires a preload library. This therefore creates an additional
parameter group with this enabled. We'll use this to manually assign
instances to when requested.
How to review
-------------
* Code review.  I've already run this down my dev environment
Who can review
--------------
Not me.
=> [Support] Add RDS parameter group that includes pg_stat_statements

terraform/cloudfoundry/rds_broker.tf
There's already a manually created parameter group called
rdsbroker-postgres95-prod-pg-stat-statements in prod Ireland which was
conflicting with this. This group has instances using it, so can't be
deleted.
I initially attempted to import this into the tfstate, but terraform
needs to update the description, and AWS doesn't allow that, so
terraform still attempts to delete the group. It's therefore necessary
to use a different name for the group.
How to review
-------------
Code review should suffice.
Who can review
--------------
Not me.
=> [Support] Rename parameter group for shared_preload_libraries

manifests/prometheus/operations.d/120-add-nginx-per-az.yml
What
----
This commit sets the instance count for nginx_z2 to 0.
Currently all firehose instances are scraped by all Prometheus instances and we
have some metrics/alerts which only expect one set of data.
For now we scale back so we can decide how to fix this issue.
How to review
-------------
Code review, maybe a run of prometheus-deploy.
Who can review
--------------
Not me.
=> [SUPPORT] Set the nginx_z2 instance count to 0

manifests/prometheus/dashboards.d/user-impact.json
Currently because we're not aggregating the metrics at all, during a
deployment we end up with 2 series for each metric which makes the graph
look odd. Aggregating these prevents this from happening.
How to review
-------------
Who can review
--------------
Not me.
=> [Support] Fix Application Instances graph on dashboard.

.gitmodules, Makefile, concourse/pipelines/create-cloudfoundry.yml, manifests/prometheus/operations.d/000-custom-prometheus-bosh-release.yml, manifests/prometheus/operations.d/050-set-external-urls.yml, manifests/prometheus/operations.d/120-add-nginx-per-az.yml, manifests/prometheus/operations.d/230-enable-service-discovery-UPSTREAM.yml, manifests/prometheus/operations.d/231-scrape-instances-from-same-az.yml, manifests/prometheus/operations.d/400-set-instance-count.yml
This change re-enables the Prometheus HA setup.
In the forked Prometheus BOSH release I created a `service_discovery` job, which will generate JSON files containing instances only from the same AZ.
Also the Prometheus urls in the configs will point to the instances in the first AZ (this only matters for alert email links and links in the alertmanager).
❗️ There is a WIP commit which needs to be updated before merge.
1. Review https://github.com/alphagov/paas-prometheus-boshrelease/pull/1 first
2. Deploy your env from this BRANCH, both with `SLIM_DEV_DEPLOYMENT` true/false. (to speed up things it's enough to run `make dev run_job JOB=prometheus-deploy`)
I tested what happens when Bosh is not available and the scrape configs based on the file service discovery still worked.
Not me.
=> [#160197650] Prometheus ha fixes 

concourse/pipelines/create-cloudfoundry.yml
What
----
Bump the paas-billing to 0.49.0
Increase the eventstore's init and refresh timeouts to 15 minutes
On prod it takes more than 5 minutes to initialise the database. The init
therefore timeouts and the application exits.
As a quickfix we'll increase the timeouts.
How to review
-------------
Code review.
Who can review
--------------
Not me.
=> [SUPPORT] Bump the paas-billing to 0.49.0

config/logit/output/generated_logit_filters.conf, scripts/generate_logit_filters.sh
What
----
Logstash filters were looking for component names beginning with "vcap." before
deserializing JSON. No components had this prefix.
Removes "vcap" from generated Logstash filters file inside the make task using
sed.
How to review
-------------
Check paas-dev ELK stack for events whose original JSON message (see `@raw`) has been broken down in to a field whose name matches the value of `@source.component`.
To deploy, copy and past `config/logit/output/generated_logit_filters.conf` to the relevant ELK stack logstash filters in Logit.
Who can review
--------------
Not @mogds or @AP-Hunt
=> [#162611438]Update Logstash filters to deserialize JSON messages

manifests/prometheus/operations.d/000-custom-prometheus-bosh-release.yml, manifests/prometheus/operations.d/223-unique-firehose-subscription-id.yml
What
----
Set a unique subscription id for the firehose-exporters, otherwise the exporters will receive only 50% of the data because of the same subscription id. (This is how Firehose works).
❗️ Make sure the WIP commit is replaced before merge.
How to review
-------------
1. Review https://github.com/alphagov/paas-prometheus-boshrelease/pull/2 first
1. Update your pipelines with `SLIM_DEV_DEPLOYMENT=false` and run the prometheus-deploy job
1. If you ssh onto the firehose nodes (prometheus deployment), you should see the firehose exporter runs with a unique subscription id flag
Who can review
--------------
Not me.
=> [#163596794] Set a unique subscription id for the firehose-exporters

Makefile
With the changes to ssh keypairs being made[1], this filter is no longer
matching correctly. Updating it to be based on the DEPLOY_ENV and
instance_group name makes it much more robust to any future changes.
[1]https://github.com/alphagov/paas-bootstrap/pull/244
How to review
-------------
* Code review
* Verify that `make dev showenv` continues to show the CONCOURSE_IP before and after https://github.com/alphagov/paas-bootstrap/pull/244 is deployed.
Who can review
--------------
Not me.
=> [#163558206] Update EC2 filters used for CONCOURSE_IP in Makefile

manifests/cf-manifest/operations.d/400-upgrade-log-cache-version.yml, manifests/cf-manifest/spec/manifest/release_versions_spec.rb
This pulls in our fork of log-cache-release which includes a backport of
the pagination fix.
How to review
-------------
TBC
Who can review
--------------
Not me.
=> [#163591232] Update log-cache to include CAPI pagination fix

concourse/pipelines/create-cloudfoundry.yml, tools/paas-uaa-assets/manifest.yml
What
----
It's better for the assets used by UAA to be served from the same parent
domain that UAA itself uses. This avoids issues with one domain potentially impacting the other domain.
This is part one to make the assets available on a new route as well as the existing route. Once this is deployed, we'll update UAA to point at the new route, and remove the existing one.
I've also updated the uaa-assets app to specify the buildpack so that it doesn't need to go through the buildpack detection process.
How to review
-------------
* Deploy from this branch, verify that UAA login page is still styled correctly.
Who can review
--------------
Not me.
=> [#163730761] Deploy paas-uaa-assets to system domain (part1)

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/330-uaa.yml, platform-tests/src/platform/acceptance/uaa_styling_test.go, tools/paas-uaa-assets/manifest.yml
What
----
This is the second part of moving the UAA assets to the system domain.
It updates UAA to point at the system domain, and removes the apps domain from the app. These are safe to combine in the same PR because UAA gets updated in the cf-deploy job, and the uaa-assets app then gets updated in the post-deploy.
How to review
-------------
* Review along with #1742 (commits from that are also included here until it can be rebased)
* Deploy from this branch, and verify that `login.$SYSTEM_DOMAIN` doesn't load anything from the apps domain.
Who can review
--------------
Not me.
=> [#163730761] Deploy paas-uaa-assets to system domain (part2)

manifests/cf-manifest/env-specific/prod-lon.yml
What
----
The "DiegoCellRepMemoryCapacity_Critical" is currently firing in
prod-lon, because `rep_memory_capacity_pct:avg5m` is sitting around
30.8%, which is less than the threshold of 33.
Increasing the number of instances to 10 would probably only increase
the free memory by 1/9, which would only just put us above the threshold
of 33:
30.8 + 30.8 * 1/9 = 34.2%
Scaling up to 11 should increase the free memory by 2/9, which gives us
a bit more margin:
30.8 + 30.8 * 2/9 = 37.6%
The numbers may not work out quite so neatly in reality, so we'll have
to keep an eye on the metrics.
How to review
-------------
* Code review only - no point in testing in a non-prod-lon environment.
Who can review
--------------
=> Increase cells in London from 9 to 11

manifests/prometheus/alerts.d/router_total_routes.yml
What
----
The existing expresion was causing the following error in Prometheus:
> Error executing query: many-to-many matching not allowed: matching
> labels must be unique on one side
In fact because we're using the same series on both sides of the /
operator, there's no need for the on() group_left() functions at all.
I initially fixed this by adding 'bosh_job_name,bosh_job_id' to the on()
function, but then realised that the whole thing was unnecessary.
How to review
-------------
* Code review.
* Try viewing the updated expression in the prometheus console in a production env.
Who can review
--------------
Not me.
=> [#162755282] Fix the RouterTotalRoutesDrop alert

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/lib/pagerduty.sh, concourse/scripts/pipelines-cloudfoundry.sh, manifests/prometheus/alerts.d/concourse-smoketests-errors.yml, manifests/prometheus/alerts.d/concourse-smoketests-failures.yml, manifests/prometheus/alerts.d/concourse-smoketests-no-data.yml, manifests/prometheus/operations.d/310-alertmanager-routes.yml, manifests/prometheus/operations/disable-alert-notifications.yml, manifests/prometheus/scripts/generate-manifest.sh, manifests/prometheus/spec/alerts/concourse-smoketests-errors.test.yml, manifests/prometheus/spec/alerts/concourse-smoketests-failures.test.yml, manifests/prometheus/spec/operations/alertmanager_routes_spec.rb, manifests/prometheus/spec/support/manifest_helpers.rb, manifests/shared/spec/fixtures/pagerduty-secrets.yml, scripts/upload-pagerduty-secrets.sh
Refactor the continuous-smoke-tests alerts.
* The retry logic was removed from the continuous-smoke-tests job on Concourse, as it was hiding intermittent errors
* The PagerDuty alert will be created from alertmanager instead of Concourse
* The smoke tests failure/increase alerts won't default to 0 value if the data is missing (this would cause big increases when it comes back and most alerts would fire)
* I created a new alert which will be triggered if the continuous-smoke-tests are paused (so we have data but no runs)
* The ENABLE_ALERT_EMAILS environment variable was renamed to ENABLE_ALERT_NOTIFICATIONS
* In the dev environments we won't create PagerDuty alerts (but it can be enabled with the ENABLE_ALERT_NOTIFICATIONS env var)
* The `pagerduty_integration_key` was removed from …
=> [#162014355] Refactor the continuous-smoke-tests alerts.

manifests/prometheus/env-specific/prod-lon.yml
What
----
We've had our limit raised by AWS, so this updates the thresholds used
by our alerts to match.
How to review
-------------
Verify the new limits match those in the AWS support ticket.
Who can review
--------------
Not me.
=> [Support] Increase Elasticache limits in London

manifests/cf-manifest/operations.d/530-ipsec.yml
What
----
The version of ipsec-release we're using doesn't compile correctly on Xenial. We've only just noticed this because we've disabled the bosh compiled package cache due to an issue with it reusing packages across stemcells incorrectly (https://github.com/alphagov/paas-bootstrap/pull/249). This means that we've been using the ipsec-release compiled on trusty up until now.
This pulls in an upstream change to the packaging script that fixes the compilation on xenial.
How to review
-------------
I've already run this down my dev environment, and it fixed this issue there, so code review is probably enough.
Who can review
--------------
Not me.
=> [Support] bump ipsec release to fix xenial compilation

concourse/pipelines/create-cloudfoundry.yml
This includes the changes in
https://github.com/alphagov/paas-aiven-broker/pull/17 which make it wait
until the user creds work before returning from the bind call.
How to review
-------------
* Code review (along with https://github.com/alphagov/paas-aiven-broker/pull/17)
* Test this in a dev env and ensure the acceptance tests pass.
🚨 Before merging 🚨 https://github.com/alphagov/paas-aiven-broker/pull/17 must be merged, and the TMP commit here updated with the created version.
Who can review
--------------
Not me.
=> [#164045929] Bump aiven broker to work around user creation delay

.gitmodules, manifests/prometheus/operations.d/000-custom-prometheus-bosh-release.yml
What
----
Bumps prometheus-boshrelease version to v24.1.0 on the upstream repository. Previously, we deployed a version from our [fork](https://github.com/alphagov/paas-prometheus-boshrelease) because it contained a number of commits we needed and weren't yet available in the upstream. v24.1.0 contains those commits. 
How to review
-------------
Reviewed during dev by running down the pipeline to a full-fat dev environment with this as the only change.
Who can review
--------------
Paired on throughout by @jpluscplusm and @AP-Hunt
=> [#163364479] Bumping prometheus-boshrelease version to v24.1.0

manifests/prometheus/alerts.d/dns-resolution-working.yml
During the recent issues in staging where DNS resolution wasn't working
on one of the API VMs, this alert didn't fire quickly enough / at all.
This updates it alert to fire if more than 10% of the probes failes in
the last 15mins.
As part of this I've also removed the separate Warning and Critical
alert as they haven't proved helpful.
How to review
-------------
Check the updated query in prometheus to verify it will alert appropriately.
Who can review
--------------
Not me.
=> [Support] Improve DNS resolution working alert.

concourse/pipelines/create-cloudfoundry.yml
What
----
At the moment we get a gap in the metrics this produces each time it
gets deployed. Making it zero-downtime to avoid this.
How to review
-------------
Code review - I've already tested this in my dev env.
Who can review
--------------
Not me.
=> [Support] Make paas-metrics deploy zero-downtime.

terraform/cloudfoundry/dns-records.tf
What
----
Added terraform to add a TXT record to the apps domain so it can be verified on my Google Search Console account.
How to review
-------------
Deploy in a dev environment, and ensure the record is created with:
`dig +short TXT ${env}.dev.cloudpipelineapps.digital`
Example of this working:
```
➜ dig +short TXT tnw.dev.cloudpipelineapps.digital
"google-site-verification=N2Pyk2D-qppi7bFBYUrdq3E3gNXOcwOacJMkIV_12Ec"
```
Who can review
--------------
Not me
=> [#163861624] Add `google-site-verification` TXT record to apex of apps domain

manifests/cf-manifest/operations.d/713-rds-broker-postgres10-plans.yml, manifests/cf-manifest/spec/manifest/rds_broker_spec.rb
The Postgres versioning scheme has changed starting with Postgres 10[1],
and it now only uses a 2 part version number instead of the 3 part
number that was used for 9.x and earlier.
For Postgres 9.x we're only specifying the first 2 parts so that we
don't have conflicts when RDS auto-upgrades the minor versions. We want
the same behaviour for Postgres 10.x, so we need this to only specify on
version part.
With this change, the plan names no longer reflect reality as RDS will
use postgres 10.6. We'l rename these in a separate PR becuase this
change will require notifying tenants.
[1]https://www.postgresql.org/support/versioning/
How to review
-------------
Code review may be enough. I've run this down my dev environment and verified that it works. I've also verified that doing an …
=> [#164104586] Stop specifying Postgres10 minor version for broker

manifests/cf-manifest/operations.d/710-rds-broker.yml, manifests/cf-manifest/operations.d/711-rds-broker-postgres95-plans.yml, manifests/cf-manifest/operations.d/712-rds-broker-mysql-plans.yml, manifests/cf-manifest/operations.d/713-rds-broker-postgres10-plans.yml
What
----
The RDS broker has been updated so users have the option to enable supported extensions. This PR adds a Postgres pg_stat_statements enabled parameter group to be consumed by the RDS broker.
How to review
-------------
- Deploy this branch to a dev env and go through a database service lifecycle, with and without different extensions enabled, using the `-c '{"enabled_extensions": ["pg_stat_statements"]}'` argument to `cf create-service`
- Confirm the correct parameter group has been applied, and connect to the RDS instance to confirm the correct extensions have been enabled
**Merge Steps**
- Merge the [RDS broker PR](https://github.com/alphagov/paas-rds-broker/pull/95)
- Remove the [branch line](https://github.com/alphagov/paas-rds-broker-boshrelease/pull/77/files#diff-8903239df47 …
=> [#161647315] Self-Enable RDS Broker Extensions

concourse/pipelines/create-cloudfoundry.yml
What
----
This replaces #1723 
We've seen this conflicting with the rotate-*-encryption-keys jobs when
trying to get a lock in the bosh director.
We've also seen this break the prometheus deploy job (which runs in
parallel to this)  because it deletes the prometheus releases between
them being uploaded, and the deployment happening.
Given it's not essential to run the cleanup, this removes it.
While doing this, I noticed that the aiven and elasticache post-deploy tasks were serialised, which they don't need to be, so this PR also fixes that.
How to review
-------------
* Code review (adding `?w=1` to the diff URL may help)
* Run the pipeline from this branch and verify all looks good (I've run this in my dev env already).
Who can review
--------------
Not me.
=> [Support] Remove bosh cleanup task

concourse/pipelines/create-cloudfoundry.yml
What
----
This PR deployed the updated paas-billing app that is not blocking access to the database during initialisation and refreshes of the data.
How to review
-------------
Deploy from this branch and view the recent logs from paas-billing to see a much faster init. Leave this running for an hour to verify that the refresh function has run correctly.
How to merge
--------------
Update the commit with the tagged release once https://github.com/alphagov/paas-billing/pull/62 has been merged.
Who can review
--------------
Not @LeePorte or @mogds
=> [#163651298] Deploy paas-billing-collector that doesn't block other queries while the init/refresh runs

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Bumps the version of the RDS broker bosh release to include changes made in [163084103](https://www.pivotaltracker.com/story/show/163084103)
Changes:
* separate max_tx_age/max_system_tx_age metrics
* fix mysql parameter group creation
How to review
-------------
1. Review https://github.com/alphagov/paas-rds-metric-collector/pull/17
1. Review https://github.com/alphagov/paas-rds-broker/pull/96
1. Review https://github.com/alphagov/paas-rds-broker-boshrelease/pull/78
1. Deploy and check the `max_tx_age/max_system_tx_age` metrics with `cf tail` on a Postgres db
Who can review
--------------
Not @tnwhitwell or I
=> [#163084103] Separate max_tx_age/max_system_tx_age metrics, fix mysql parameter group creation

manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
What
----
This commit updates UAA to address the newly released [CVE-2019-3775](https://www.cloudfoundry.org/blog/cve-2019-3775/). It replaces the component at risk with the updated version.
How to review
-------------
Code review should be enough, I have run it down my dev pipeline.
[UAA latest release data for manifest](https://bosh.io/releases/github.com/cloudfoundry/uaa-release?all=1#latest)
Who can review
--------------
Not @LeePorte
=> [support] Update UAA for CVE-2019-3775

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/713-rds-broker-postgres10-plans.yml, manifests/cf-manifest/spec/manifest/rds_broker_spec.rb, platform-tests/src/platform/acceptance/postgres_service_test.go
With the change in Postgres versioning[1], these plan names no longer
reflect reality as it won't necessarily be postgres 10.5 that tenants
end up with, it'll be the latest 10.x that RDS has available.
This therefore updates the plan names and descriptions to reflect this.
[1]https://www.postgresql.org/support/versioning/
How to review
-------------
Code review - run it down a pipeline and verify existing instances still work, and get the new plan names.
Who can review
--------------
Not me.
=> [#164104586] Rename Postgres 10 plans to reflect reality

manifests/cf-manifest/operations.d/710-rds-broker.yml
This pulls in a fix that makes user-update params to set the
maintenance/backup window work again. Prior to this, they were being
ignored.
How to review
-------------
Deploy, verify the custom acceptance tests pass.
Update the rds-broker version after https://github.com/alphagov/paas-rds-broker-boshrelease/pull/79 has been merged.
Who can review
--------------
Not me
=> [#164108622] Update rds-broker with fix for user-update params

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
This updates the broker to a version that rejects unrecognised user
params - alphagov/paas-rds-broker#99
How to review
-------------
Deploy from this branch and verify everything works. Attempt to update a service instance with some unrecognized params (eg `cf update-service my-db -c '{"foo": "bar"}'`) and verify it correctly returns an error.
Update the TMP commit with the version built after https://github.com/alphagov/paas-rds-broker-boshrelease/pull/80 is merged.
Who can review
--------------
Not me.
=> [#164248877] RDS-broker reject unknown params

manifests/cf-manifest/operations.d/720-cdn-broker.yml
This pulls in an updated version of the cdn-broker that configures
CloudFront to only support TLS 1.2
🚨 **Do not merge before 4th March** 🚨 
How to review
-------------
* Create a cdn-route instance.
* Once it's fully deployed, test is in an SSL tester (eg https://www.ssllabs.com/ssltest) to verify it only supports TLS 1.2
Update the TMP commit with the release created after https://github.com/alphagov/paas-cdn-broker-boshrelease/pull/13 is merged.
Who can review
--------------
Not me.
=> [#163524147] Update the cdn-broker with TLS 1.2 policy

config/billing/config.json.erb, config/billing/output/eu-west-1.json, config/billing/output/eu-west-2.json
What
----
The `ceil()` in the formula meant that every app was being charged for
one hour at a minimum, meaning that if an app was autoscaled for 30
seconds, they would still be charged for an hour.
This change ensures that the apps are now just charged for the seconds
they are active for.
How to review
-------------
* Code Review
* Ensure that a short-lived app is not billed for an hour:
1. Start an app for 30 seconds
1. Restart billing collector
1. Check that the app has not been billed for an hour
* Ensure that a longer-lived app is billed correctly
1. Start an app for an hour
1. Restart billing collector
1. Check the app has been billed correctly
(The second of these may be a bit too long in the tooth - if a sanity check of the formula seems correct, this may be skipped)
Who can …
=> Charge all apps by the second

terraform/cloudfoundry/dns-records.tf
What
----
This needs to be added here, as the root domain's TXT record is also applied in account-wide terraform.
The AWS api doesn't have a PATCH method for route53, so the google_site_verification record was being overwritten each time the pipeline ran.
With both records in both places, we will no longer have the TXT record flip-flopping between `spf` and `google-site-verification`
How to review
-------------
Ensure that both records are created when the pipeline runs terraform with dig:
```
➜ dig +short TXT cloudapps.digital
"google-site-verification=N2Pyk2D-qppi7bFBYUrdq3E3gNXOcwOacJMkIV_12Ec"
"v=spf1 -all"
➜ dig +short TXT london.cloudapps.digital                  
"google-site-verification=N2Pyk2D-qppi7bFBYUrdq3E3gNXOcwOacJMkIV_12Ec"
"v=spf1 -all"
```
Who can review
-------------- …
=> [#164372981] Add our SPF record to the TXT record tf resource

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/monitor-prod-lon.yml, concourse/pipelines/monitor-prod.yml, concourse/pipelines/monitor-remote.yml, concourse/scripts/pipelines-cloudfoundry.sh, concourse/scripts/smoke_tests_email.sh, concourse/tasks/set-smoke-test-creds.yml, concourse/tasks/smoke-tests-run.yml, manifests/cf-manifest/spec/manifest/release_versions_spec.rb, manifests/cf-manifest/spec/support/manifest_helpers.rb, manifests/prometheus/alerts.d/concourse-smoketests-errors.yml, manifests/prometheus/alerts.d/concourse-smoketests-failures.yml, manifests/prometheus/alerts.d/concourse-smoketests-no-data.yml, platform-tests/upstream/run_smoke_tests.sh
What
----
This PR adds the ability for one DEPLOY_ENV's deployer Concourse to monitor
one or more other DEPLOY_ENV's Cloud Foundries, via the standard CF smoke tests.
In order for env1 to monitor env2, the following must be true:
- env1 must be able to access env2's state bucket.
- env1 must be able to access env2's CF API
- this is more of a problem in dev than in prod; in dev you may wish to test this by having an env test itself - this works as expected.
- env2 must have had the `set-smoke-test-creds` job run at least once
- it's in the `credentials` job group of the `create-cloudfoundry` pipeline
- this job also rotates creds if they already exist.
- a symlink from `paas-cf::/concourse/pipelines/monitor-<env2>.yml` must point towards the target …
=> [#163951798] Run smoke tests continuously from other regions

manifests/cf-manifest/env-specific/default.yml, manifests/cf-manifest/env-specific/prod-lon.yml, manifests/cf-manifest/env-specific/prod.yml, manifests/cf-manifest/env-specific/stg-lon.yml, manifests/cf-manifest/operations.d/360-doppler.yml, manifests/cf-manifest/spec/manifest/env_spec.rb
What
----
* Number of doppler instances in production have been scaled to 12 in prod, and 6 in all other instances.
* Test has been added to ensure this is the case
How to review
-------------
* Code Review
* Check unit tests pass
* Check the number of doppler instances do not change when run down Dev pipeline.
Who can review
--------------
=> [SUPPORT] Scale up doppler in production

concourse/pipelines/create-cloudfoundry.yml
What
----
In staging I had to manually upgrade the billing-db from tiny-unencrypted-9.5 to medium-unencrypted-9.5 (upgrade is not supported between unecrypted <-> encrypted in the RDS broker).
If we ever recreate staging this change will make sure we use an encrypted one.
This change won't effect any existing databases.
How to review
-------------
Code review should be enough. It's unnecessary to run through the staging/prod pipelines, so a Github merge with `[skip ci]` should be enough IMO.
Who can review
--------------
Not me.
=> [#164467168] Change the billing-db's plan in staging to medium-9.5

manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
This was actioned because of
https://www.cloudfoundry.org/blog/usn-3900-1/, which mentions
CVE-2019-6977 and CVE-2019-6978.
The release notes also mention
https://people.canonical.com/~ubuntu-security/cve/CVE-2019-6111 (an
OpenSSH vulnerability) is fixed in 0.67.0 and 1.273.0 respectively, so
we may as well aim for those.
This uses the latest release of cflinuxfs2 and cflinuxfs3.
How to review
-------------
* Code review
* Check it has run down a pipeline
Who can review
--------------
=> USN-3900-1: Bump version of cflinuxfs to fix CVEs

concourse/pipelines/create-cloudfoundry.yml
...instead of blue-green-deploy. This makes it consistent with all the
other apps we push from this pipeline. It also means that we don't need
to manually cleanup the old app.
It has another advantage in that it renames the existing app before
pushing the new app, meaning the new app is initially pushed with the
correct name. This means that it will show up in billing with this name
instead of the -new variant.
How to review
-------------
Code review. I've already run this down my dev environment.
Who can review
--------------
Not me.
=> Use zero-downtime-push for Aiven broker.

.travis.yml, Makefile, manifests/cf-manifest/operations.d/001-rename-network-and-deployment-UPSTREAM.yml, manifests/cf-manifest/operations.d/002-aws-UPSTREAM.yml, manifests/cf-manifest/operations.d/003-use-external-blobstore-UPSTREAM.yml, manifests/cf-manifest/operations.d/004-use-s3-blobstore-UPSTREAM.yml, manifests/cf-manifest/operations.d/005-use-external-dbs-UPSTREAM.yml, manifests/cf-manifest/operations.d/006-stop-skipping-tls-validation-UPSTREAM.yml, manifests/cf-manifest/operations.d/007-enable-service-discovery-UPSTREAM.yml, manifests/cf-manifest/operations.d/008-add-prometheus-uaa-clients-UPSTREAM.yml, manifests/cf-manifest/scripts/generate-manifest.sh, scripts/test_posix_newline.sh, scripts/test_symlinks.sh
What
----
Removes hard-coded upstream operations files references out of `scripts/generate-manifest.sh`, and replaces them with numerically-ordered symlinks in the `operations.d` directory.
How to review
-------------
1. Code review
2. Check tests pass
~3. Run this branch down the pipeline and check everything is OK. (Double check things affected by the newly-symlinked ops files?)~ This is "obviously" correct, and anything going wrong will be so catastrophic that it'll also be obvious in staging.
Who can review
--------------
Paired on by @jpluscplusm and @AP-Hunt. Reviewed in pair.
=> [#163521334] Move CF manifest upstream opsfiles to ordered symlinks

config/service-brokers/aiven/config.json
What
----
Update the descriptions and displayNames for all Elasticsearch 5 plans to indicate that they are deprecated.
The amended blocks are removed in another PR, which will be merged after the tenants notice period.
How to review
-------------
Code review should be enough. The changes made only affect the marketplace output.
Who can review
--------------
Not @tnwhitwell or @AP-Hunt
=> [#163592114] Deprecate Elasticsearch 5.x

manifests/cf-manifest/env-specific/prod-lon.yml
What
----
We are currently triggering / hovering close to triggering the alarm in London for the available memory on cells. This means we need to add more cells.
`rep_memory_capacity_pct:avg5m` is sitting around 32.8%, which is less than the threshold of 33.
As we require the number of instances to be divisible by #AZs, we scale to 18 cells.
How to review
-------------
Code review
Who can review
--------------
Anyone but me
=> [SUPPORT] Add some more cells in London

manifests/cf-manifest/operations.d/329-capi-release.yml
What
----
This was actioned because of https://www.cloudfoundry.org/blog/cve-2019-3785/
How to review
-------------
* Code review
* Check it has run down a pipeline
Who can review
--------------
=> [SUPPORT] Update capi-release to mitigate CVE-2019-3785

.travis.yml
What
----
This PR pins Ruby version to 2.5.3 in Travis.
Ruby 2.5.4 was recently released, and appears to have problems with bundler. We
previously pinned Ruby at 2.5 in Travis, and Travis is now resolving this to
the "broken" 2.5.4. We pin to 2.5.3 to maintain passing builds.
We also add a Ruby 2.5 matrix build to Travis
When Travis began resolving 2.5 to 2.5.4 in [1], the build began failing for
reasons other than a test failure. This 2nd commit adds a second build to the
matrix, pinned to 2.5, which is allowed to fail. This should allow us to see
when the latest 2.5.x build is safe to use, without failing the build in the
meantime.
Matrix builds aren't carried out consecutively, so we don't believe it doubles
the build time.
How to review
-------------
Check the ruby 2.5.3 build is …
=> [FIX] Pin Travis to Ruby 2.5.3

manifests/cf-manifest/env-specific/prod-lon.yml
What
----
The memory usage in prod-lon has been climbing, and we're now below our
threshold again.
Judging from this graph:
https://prometheus-1.london.cloud.service.gov.uk/graph?g0.range_input=2w&g0.expr=rep_memory_capacity_pct%3Aavg5m&g0.tab=0
Last time we increased our scale by 3 instances we got an extra 23%
rep_memory_capacity_pct. We're now running at 23%, which is below our
threshold of 33%. Increasing the cell instances by 3 should give us
another 20% or so, which should take us above the threshold again.
I'll raise a separate PR to scale back Ireland, which seems to be
swimming in free memory now.
How to review
-------------
* Code review should be fine
Who can review
--------------
=> Add 3 cells to prod-lon

manifests/prometheus/dashboards.d/user-impact.json
What
----
Since we've switched to "highly available" prometheus the url is
prometheus-1... not prometheus...
The "Alerts" box in grafana should link to the right URL.
I'm just using -1 (rather than working out which instance we're actually
on) because it's easier.
How to review
-------------
* Code review
Who can review
--------------
=> Fix link to prometheus from grafana

manifests/cf-manifest/env-specific/prod-lon.yml
What
----
As predicted by Andras, the previous scale up only took gave us an extra
10 units of capacity, not the 20 we originally thought we'd get.
Adding another 3 cells should take us over the threshold.
How to review
-------------
* Code review
Who can review
--------------
=> Add another 3 cells to prod-lon

manifests/prometheus/alerts.d/aiven-cost.yml, manifests/prometheus/spec/alerts/aiven-cost.test.yml
What
----
The value of `paas_aiven_estimated_cost_pounds` is the current spend for
the month according to Aiven, so it goes up in a saw tooth from the
beginning of the month.
This uses a linear approximation that the cost for the month will be the
cost for the last 24 hours multiplied by 30 (for the days in the month).
The delta function just naively subtracts the value at the beginning of
the time period from the value at the end. You might think that the
`increase()` function would be a better fit, but sadly that only works
for counters that always strictly increase over time or reset to zero -
this one occasionally drops by a few pounds, which confuses prometheus.
For the first day of each month the value of
`delta(paas_aiven_estimated_cost_pounds[24h])` will be massively
negative as …
=> Estimate Aiven cost at the end of the month

manifests/prometheus/dashboards.d/user-impact.json
What
----
We found the cell used memory graph not really useful, so we are replacing it
with the current/required number of cells.
The required cell count means the minimum number of cells to have at least 33%
free memory capacity. See the relevant ADR [1]
[1] https://team-manual.cloud.service.gov.uk/architecture_decision_records/ADR021-cell-capacity-assignment-2/#decision
How to review
-------------
1. Code review should be enough as I deployed it to my dev env successfully
Who can review
--------------
Not me.
=> [SUPPORT] Replace the used memory graph with the number of cells graph in Grafana

manifests/cf-manifest/env-specific/prod-lon.yml
What
----
It needs scaling up again after the memory usage climbed again.
How to review
-------------
* Glance at the bottom left chart in
[Grafana](https://grafana-1.london.cloud.service.gov.uk/d/paas-user-impact/user-impact-prod-lon?refresh=5s&orgId=1) to confirm they really need scaling.
* Code review
Who can review
--------------
=> Add 3 more cells to London

config/logit/11_app_syslog_drain.conf, config/logit/20_custom_filters.conf, config/logit/output/generated_logit_filters.conf, scripts/generate_logit_filters.sh
What
----
Currently we send the PaaS admin logs to Logit - using a log service. The
current Logstash filters are parsing the JSON message twice, once by adding it
with "app." prefix and once more by adding the "[app guid]." prefix.
This commit:
- creates a new field @source.app_id which will contain the app guid (not using @cf.app_id here as that would have additional side effects)
- updates the syslog_program to "app", which will be the new value of @source.component
- adds a condition that we don't try to parse the JSON message if @source.component is "app"
- adds a condition that we don't try to parse app logs as platform logs
- removes the @message field for apps if it still contains the full JSON message
- removes the unnecessary syslog6587_msglen field
How to review
-------------
1. …
=> [#164278101] Parse application JSON logs correctly

concourse/pipelines/create-cloudfoundry.yml
What
----
Rather than registering and then enabling the S3 broker within the same aggregate block as the orgs and spaces are created, enable the broker as part of the next aggregate.
This prevents us from trying to enable the broker on a space that has not yet been created.
How to review
-------------
* Code Review
* `make dev pipelines BRANCH=fix_s3_broker_enabling_race_condition_164891660`
* If you're really feeling bored, run `destroy-cloudfoundry` pipeline, then run `create-cloudfoundry` on this branch, and if `post-deploy` does not error, this change is good.
Who can review
--------------
=> [#164891660] Enable s3 broker separately to registering it

config/logit/20_custom_filters.conf, config/logit/output/generated_logit_filters.conf
What
----
Cloud Controller outputs log lines like "Started VERB /api/uri for user: name, ip". We add an extra logstash filter to extract the verb, uri, username and source ip fields from those messages. This will allow us to get a more accurate picture of how many requests each user in the system is making in a timeframe, for the purposes of working out a reasonable request rate limit.
How to review
-------------
1. Code review
2. Check the dev Logit stack where this has already been applied, and ensure that log lines matching the above format have had the relevant fields extracted
Who can review
--------------
Not @tnwhitwell or @AP-Hunt.
=> [#164363210] Extract extra fields from cloud_controllger_ng logs

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
This updates the rds broker bosh release based on [this PR](https://github.com/alphagov/paas-rds-broker/pull/100) that adds the option to enable/disable extensions via an update call.
How to review
-------------
Deploy to your dev env and run the following.
- Create a postgres RDS instance via `cf create-service`
- Run `cf update-service svname -c '{"enable_extensions": ["pg_stat_statements"], "reboot": true}'`
- Confirm the right param group is in sync, extension is enabled via psql and tags are correct
- Run `cf update-service svname -c '{"disable_extensions": ["pg_stat_statements"], "reboot": true}'`
- Confirm the right param group is in sync, extension is disabled via psql and tags are correct
Merge Steps
------------
- Review and merge …
=> [#164143495] RDS broker enable/disable extensions

manifests/cf-manifest/env-specific/prod-lon.yml, manifests/cf-manifest/env-specific/prod.yml
What
--------------
As more tenants have migrated over to London we have a surplus of cells in Ireland, this commit removes another 3. Further reductions will take place over successive PRs.
Also we add 3 more in London as the memory capacity is below 35% again.
How to review
-------------
Code review alongside [User impact dashboard](https://grafana-1.cloud.service.gov.uk/d/paas-user-impact/user-impact-prod?refresh=5s&orgId=1)
Who can review
--------------
anyone
=> [SUPPORT] Reduce the number of cells to 30 in Ireland, add 3 in London

concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/monitor-remote.yml, manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml, manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml, manifests/cf-manifest/operations.d/320-cc-set-ccdb.yml, manifests/cf-manifest/operations.d/350-diego-cell.yml, manifests/cf-manifest/operations.d/400-upgrade-log-cache-version.yml, manifests/cf-manifest/operations.d/900-cf-cert-rotation.yml, manifests/cf-manifest/spec/manifest/database_encryption_keys_spec.rb, manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
CF upgrade from v7.5.0 to  v7.7.0 with the following changes
- Upgrade cf-smoke-tests-release from 40.0.45 to 40.0.47
- Updating the relevant ops files to take into account the `cc_deployment_updater` changes in v7.6.0
- Upgrading log-cache from 2.1.1 to 2.2.0 by removing our log-cache fork and using the upstream
Release Notes
-------
- https://github.com/cloudfoundry/cf-deployment/releases/tag/v7.6.0
- https://github.com/cloudfoundry/cf-deployment/releases/tag/v7.7.0
How to review
-------------
- Code Review 
- Deploy to your dev env 
Who can review
--------------
Not @mogds or @richardTowers
=> [#164864261] Upgrade to cf-deployment v7.7.0

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/330-uaa.yml
What
----
Recently we have had issues where the logging stack has been breaking, it has been difficult to pin this down to a specific cause. In order to gain more insight into what is happening I am electing to deploy this nozzle. in order to use it you will need the log-noise cf cli plugin installed `cf install-plugin -r CF-Community "log-noise"` and then issue `cf log-noise` to see the top log producing apps on the platform.
This is a stateless app and keeps 60 minutes of data in it's ring buffer.
How to review
-------------
- Install the log-noise cf cli plugin installed `cf install-plugin -r CF-Community "log-noise"`
- Issue `cf log-noise`
You should see something like
```
gds5508:paas-bootstrap leeporte$ cf log-noise
Volume Last Minute  App Instance
56 …
```
=> [#161684547] Enable noisy-neighbor-nozzle for CF

manifests/cf-manifest/env-specific/default.yml, manifests/cf-manifest/env-specific/prod-lon.yml, manifests/cf-manifest/env-specific/prod.yml, manifests/cf-manifest/env-specific/stg-lon.yml, manifests/cf-manifest/operations.d/360-log-api.yml
What
----
We are currently at risk of dropping tenant logs, which we experience
occasionally when log volume gets too high:
---
Environment: Prod Ireland
Date: 02 April 2019 to 04 April 2019
Query:
```
sum by(environment) (rate(firehose_counter_event_loggregator_rlp_dropped_total[1h]))
```
---
This commit follows an existing pattern for env-specific values
saturating ops files.
The default value for `log-api` instances is the same as
`cf-deployment`.
I chose 6 instances in prod-london and prod-ireland arbitrarily. However
I feel that we should get to a position where we are dropping hardly any
logs, draft a SLO for log deliverability, and then do cost optimisation
when we have deliverability budget to spend according to the SLO.
Caveats
---
I didn't have a pipeline to test this against, …
=> Support: Scale up log-api instances

manifests/prometheus/alerts.d/cloudfront_tls_certificates_expiry.yml, manifests/prometheus/alerts.d/cloudfront_tls_certificates_validity.yml
What
----
We have some alerts which require tenant action or communication to resolve.
These alerts should be segregated from platform level alerts to reduce alert blindness.
Cloud Foundry provides some alerts out of the box which will not be labelled, so lazily we can assume that any alert without a layer label is a platform level alert.
Tenant alerts will be available with the query:
```
ALERTS{layer="tenant"}
```
Non-tenant alerts will be available with the query:
```
ALERTS{layer!="tenant"}
```
Any alert without a layer (i.e. platform level alerts) will be available
with the query:
```
ALERTS{layer!~"^.+$"}
```
Thinking
---
- Alert blindness is bad
- If we separate out the platform into more layers (e.g. core, services, tenants) then these layers will scale
- The `layer` label is used …
=> Support: Add layer label to tenant alerts

concourse/pipelines/create-cloudfoundry.yml, config/buildpacks.yml, manifests/cf-manifest/spec/manifest/release_versions_spec.rb, platform-tests/example-apps/http_tester/Godeps/Godeps.json, tools/buildpacks/email.go, tools/buildpacks/go.mod, tools/buildpacks/go.sum, tools/buildpacks/main.go
**Blocked: Can't be merged until after 05/04/2019**
What
----
- Upgrades buildpacks to the latest versions 
- Adds R buildpack
- Adds Nginx buildpack
- Updates go-github module as I have issues with v21
- Fixes cf-acceptance-tests to latest commit on master with test app that supports the latest go buildpack
- Updates paas-accounts version with go bump
How to review
-------------
- Deploy to dev env
- Generate notification email via `create_buildpacks_email.sh`
Who can review
--------------
Not me
=> [#164728558] Buildpack upgrade

concourse/pipelines/create-cloudfoundry.yml
What
----
This updates the commit of the version of cf-acceptance-tests to the merge commit that pulls it into master.
How to review
-------------
Code review ~~and run down pipeline~~ I've run it down https://deployer.leeporte.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry
check that `git show 5550ae6462f849142a341f7f8e2bd2ba6571943f` gives a sensible commit on https://github.com/cloudfoundry/cf-acceptance-tests
Who can review
--------------
Anyone
=> Update cf-acceptance-tests commit

manifests/cf-manifest/operations.d/320-cc-add-quotas.yml
What
----
We have some tenants who are running many things, and thus they require
a larger quota.
We will one of our tenants to the 4xlarge and have the 8xlarge on
standby in case they need to scale at short notice
How to review
-------------
- YAML review
- Check the quotas make sense
Who can review
--------------
Not @tlwr
=> Support: Add 4xlarge and 8xlarge quotas

manifests/cf-manifest/operations.d/320-cc-add-quotas.yml
What
----
We were missing a digit - 8xlarge should have 1.6TB of memory, not
135GB.
How to review
-------------
* Check the numbers
Who can review
--------------
* Not @richardTowers (probably @tlwr)
=> Correct the memory allocation for 8xlarge plans

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
As part of the [buildpack upgrade](https://github.com/alphagov/paas-cf/pull/1832), we switched to specifying a tag for the cf-acceptance-tests as there wasn't a branch that supported the go buildpack update.
A cf7.9 branch has been added so this PR reverts the change described above. 
How to review
-------------
- Code review
- Deploy to your env (already tested in mine)
Who can review
--------------
Not me
=> Set the cf-acceptance-tests branch to cf7.9

manifests/cf-manifest/env-specific/default.yml, manifests/cf-manifest/env-specific/prod-lon.yml, manifests/cf-manifest/env-specific/prod.yml, manifests/cf-manifest/operations.d/320-cc-set-api-limits.yml
What
----
This PR sets API limits for Cloud Controller in order to prevent Denial of Service caused by one or two users.
Currently we have no API rate limiting in place. this sets global limits based upon https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/capi-release&version=1.77.0#p%3dcc.rate_limiter
If we require further fine tuning we can use https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/capi-release&version=1.77.0#p%3dcc.nginx_rate_limit_zones
I have arrived at these numbers by taking the defaults then reducing the reset time and then dividing the defaults by the time reduction factor and then applied a bit of rounding.
How to review
-------------
Who can review
--------------
Describe who …
=> [#164363210] Set API limits per user for Cloud Controller

manifests/prometheus/dashboards.d/user-impact.json
What
----
Let's have separate boxes for platform alerts and tenant alerts so it doesn't look like the platform is in trouble when there's a tenant cert due to expire:
We already have a `layer` label which is set to `tenant` for expiring certificate notifications.
How to review
-------------
* This has run down `towers` - see https://grafana-1.towers.dev.cloudpipeline.digital/d/paas-user-impact/user-impact-towers?refresh=5s&orgId=1
* The commits are broken down so you can see the changes - see b3f590d
Who can review
--------------
=> Separate tenant and platform alerts

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/330-uaa.yml
What
----
This reverts commits 84f4bebc9cfb4614feba78cb73adcc2d8400d349 and cda0ad64aef4ce41bb01df5af61a416c132071e9.
The noisy neighbour nozzle seems to have stopped working in production, and we're not sure why.
We think that using `cf top` instead is simpler and more reliable, so we're going to document that instead and remove the noisy neighbour nozzle.
Once this is released we'll need to manually remove the cf apps `nn-nozzle` and `nn-accumulator`.
How to review
-------------
* Code review
* Check it doesn't break the pipeline
Who can review
--------------
=> [#161684547] Revert "Enable noisy-neighbor-nozzle for CF"

manifests/cf-manifest/operations.d/329-capi-release.yml
What
----
Upgrade CAPI to v1.79.0 as recommended in mitigations for [cve-2019-3798](https://www.cloudfoundry.org/blog/cve-2019-3798/).
How to review
-------------
* Code review
* Ensure it has successfully run down a pipeline (has already been run down mine - that may be enough)
Who can review
--------------
Not me
=> [SUPPORT] Upgrade CAPI to 1.79.0 to mitigate cve-2019-3798

manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Bumps CDN broker to 0.11.1 to deploy changes made in https://github.com/alphagov/paas-cdn-broker/pull/11
How to review
-------------
Check the release version matches the one built [here](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/cdn-broker-release/jobs/build-final-release/builds/13)
Who can review
--------------
Not I
=> [#164397255] Bump paas-cdn-broker to 0.1.11

manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml, manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml
What
----
The following Ubuntu Security Notifications recommend bumping our
stemcells (the base OS for our virtual machines) and our stacks (the
base OS for cloud foundry applications):
- https://www.cloudfoundry.org/blog/usn-3931-2/
- https://www.cloudfoundry.org/blog/usn-3935-1/
- https://www.cloudfoundry.org/blog/usn-3945-1/
How to review
-------------
* Code review
* MAYBE wait for it to run down a pipeline, MAYBE just trust staging
(it's currently running down https://deployer.towers.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry)
Who can review
--------------
=> [SUPPORT] Bump stemcells and stacks to address USNs

concourse/pipelines/create-cloudfoundry.yml
What
----
Within `create-cloudfoundry` pipeline
- Move `paas-accounts` into its own Job
- Move `paas-admin` into its own Job
- Move `paas-billing` into its own Job
- Move `paas-metrics` into its own Job
How to review
-------------
- Code review commit-by-commit
- Observe [TLWR](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry)
- Run it through your pipeline
- Read [ADR](https://github.com/alphagov/paas-team-manual/pull/289)
Who can review
--------------
Not @tlwr
=> Separate jobs for PaaS services

manifests/cf-manifest/env-specific/stg-lon.yml
What
----
The API availability tests in `stg-lon` (our staging environment) were rate limited today. It appears that each run of them generally causes about 20,000 requests but this could be much higher in a long running deploy (e.g., BOSH recreating all VMs due to a new stemcell.)
This commit increases the per-user API rate limit in `stg-lon` to 100,000 requests/hour. This is roughly 30/second and should be enough to avoid any recurrence.
Alternative implementation choices:
* Disable rate limiting in staging. `bosh interpolate` does not appear to support ternary operators and I didn't want to have an extra variable to control whether rate limiting is on or off.
* Try to specifically avoid rate limiting the availability test users. This would take more research but seems a better fix.
How …
=> BAU: API availability tests should not be rate limited

manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
What
----
Upgraded the boshrelease for UAA to 71.0 in order to mitigate [CVE-2019-3788](https://www.cloudfoundry.org/blog/cve-2019-3788/)
How to review
-------------
I have run this down my pipeline without any issues, but it could be worth running that again.
Code review to ensure i can use a keyboard
Who can review
--------------
Not me!
=> [SUPPORT] Upgrade UAA to 71.0 to mitigate CVE-2019-3788

concourse/pipelines/create-cloudfoundry.yml
What
----
Bumps paas-admin and paas-billing. Billing has been updated so it adds the `quota_definition_guid` as part of the consolidation and admin has been updated pull the quota from this field if it exists.
Related Pull Requests
- https://github.com/alphagov/paas-billing/pull/64
- https://github.com/alphagov/paas-admin/pull/125
How to review
-------------
- Deploy to your env
Who can review
--------------
Not me
=> [#164763735] paas-admin/paas-billing add quota_definition_guid

manifests/cf-manifest/operations.d/720-cdn-broker.yml
What
----
Bumps the CDN broker to 0.1.12 to restore create/update CDN broker functionality
How to review
-------------
[Code review the version/sha](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/cdn-broker-release/jobs/build-final-release/builds/14)
Who can review
--------------
Done as a pair of @46bit & @tlwr
=> CDN broker bump to 0.1.12

manifests/cf-manifest/operations.d/040-cf-routing.yml
What
----
Adds a new ops file to bump cf-routing release to 0.188.0 which contains
the CVE fix for [CVE-2019-3789](https://www.cloudfoundry.org/blog/cve-2019-3789/)
How to review
-------------
- 🔍 [Release notes](https://github.com/cloudfoundry/routing-release/releases)
- Code review
- `cd paas-bootstrap ; DEPLOY_ENV=tlwr make dev bosh-cli ; bosh releases | grep routing`
- 🔍 [ATS & CATS in dev/tlwr](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry)
Who can review
--------------
Not @tlwr
=> CVE-2019-3789

manifests/cf-manifest/operations.d/310-router.yml
What
----
Make gorouter not hairpin: Gorouter as of routing release 0.188.0 forces all route services to
hairpin unless this configuration is set to true
new: https://bosh.io/jobs/gorouter?source=github.com/cloudfoundry-incubator/cf-routing-release&version=0.188.0
vs
old: https://bosh.io/jobs/gorouter?source=github.com/cloudfoundry-incubator/cf-routing-release&version=0.184.0
gorouter changes: https://github.com/cloudfoundry/gorouter/compare/a2e8fcfec056587806ca192fced3eb272b9770aa...e4915481282eddbd22f38f6965e0c5a3b2be8783
individual commit: https://github.com/cloudfoundry/gorouter/commit/e4915481282eddbd22f38f6965e0c5a3b2be8783
How to review
-------------
Code review
I have a [safelist route service](https://github.com/alphagov/re-paas-ip-safelist-service) working which I have demoed to …
=> Explicitly enable route_services_internal_lookup

concourse/pipelines/create-cloudfoundry.yml
What
----
Full diff: https://github.com/alphagov/paas-admin/compare/v0.82.0...v0.94.0
Contains the following PRs by human beings:
- alphagov/paas-admin#146 Stub APIs needed for the calculator
- alphagov/paas-admin#148 Request logging
- alphagov/paas-admin#160 Use javascript naming for request log interceptor
- alphagov/paas-admin#173 Support: Fix bug showing allocations
- alphagov/paas-admin#180 Skip calculator getQuote if there are no items
- alphagov/paas-admin#181 Remove low-value, flakey test
And the following dependabot specials:
- alphagov/paas-admin#161 Bump nunjucks from 3.1.3 to 3.2.0
- alphagov/paas-admin#165 Bump glob from 7.1.2 to 7.1.3
- alphagov/paas-admin#164 Bump @types/source-map-support from 0.4.1 to 0.5.0
- alphagov/paas-admin#162 Bump webpack-cli from 3.1.0 to 3.3.1
- …
=> Bump paas-admin to v0.96.0

manifests/cf-manifest/operations.d/320-cc-increase-max-app-disk.yml
What
----
One of our tenants wants to push a Docker image that is 2.2GB in size. Cloud Foundry limits the disk usage of apps to 2GB by default, and so they have not been able to release their app on the PaaS.
This PR increases that limit to 4GB. This is meant as an idea for discussion rather than a PR to definitely be merged.
How to review
-------------
Understand the change:
* https://github.com/cloudfoundry/cloud_controller_ng/blob/master/config/cloud_controller.yml#L51 https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/cf-release&version=203#p%3dcc.maximum_app_disk_in_mb
* https://pvtl.force.com/s/question/0D50P00003wKIRMSA4/we-are-new-to-pivotal-our-docker-image-is-approximately-7-gb-as-per-the-document-we-can-only-deploy-2gb-of-docket-image-please-let-us-know-if-w …
=> Increase maximum app disk to 4gb

manifests/cf-manifest/env-specific/prod.yml
What
----
During a tenant's performance testing, we expect `prod` to increase from 300 to 900 RPS. This PR doubles the number of gorouters we run in `prod` so that the load per gorouter will only increase 50%.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit
=> Increase gorouters in `prod` from 3 to 6

scripts/list-dev-envs.sh
What
----
Sometimes I find myself wondering what people have called their
developer environments. Am I `richt`? Or `towers`? You just have to
know.
It's possible to find out by looking at the names of the state buckets
in S3. This script does that, so people don't have to faff around in the
AWS web console.
[ci skip] - https://github.com/concourse/git-resource#check-check-for-new-commits
How to review
-------------
Who can review
--------------
=> Add a script to list the developer environments

concourse/pipelines/create-cloudfoundry.yml
What
----
This PR exists to release https://github.com/alphagov/paas-billing/pull/70, but also releases two refactoring PRs. See commit message for details.
Who can review
--------------
Not @46bit
=> [#164493738 ] Upgrade to paas-billing v0.57.0

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/monitor-remote.yml, manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml, manifests/cf-manifest/operations.d/339-uaa-set-uaa-boshrelease.yml
What
----
This mitigates USN-3947-1, USN-3885-2, USN-3943-1 and CVE-2019-3801 by upgrading versions in line with triaging done in this comment: https://www.pivotaltracker.com/story/show/165633078/comments/202039197.
How to review
-------------
* 🐝 **Wait for Miki to try this in their dev environment;** 🐝
* Review alongside https://github.com/alphagov/paas-bootstrap/pull/270;
* [Review the choice of versions](https://www.pivotaltracker.com/story/show/165633078/comments/202039197);
* See if the tests pass;
* Code review.
Who can review
--------------
Not @46bit
=> [#165633078] Mitigate USN-3947-1, USN-3885-2, USN-3943-1, CVE-2019-3801

concourse/pipelines/create-cloudfoundry.yml
What
----
See https://github.com/alphagov/paas-admin/compare/v0.97.0...v0.104.0
This includes these PRs by humans :meat_on_bone:
- alphagov/paas-admin#188 [#164493738] Remove currency rate and fix code to GBP
And these PRs by robots :space_invader:
- alphagov/paas-admin#183 Bump csurf from 1.9.0 to 1.10.0
- alphagov/paas-admin#184 Bump source-map-support from 0.5.8 to 0.5.12
- alphagov/paas-admin#187 Bump helmet from 3.13.0 to 3.16.0
- alphagov/paas-admin#190 Bump @types/nock from 9.3.0 to 10.0.1
- alphagov/paas-admin#191 Bump @types/route-parser from 0.1.1 to 0.1.2
- alphagov/paas-admin#192 Bump tslint-consistent-codestyle from 1.13.3 to 1.15.1
- alphagov/paas-admin#185 Bump showdown from 1.8.6 to 1.9.0
- alphagov/paas-admin#193 Bump passport-oauth2 from 1.4.0 to 1.5.0
How to review …
=> Bump paas-admin from v0.97 to v0.104

manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml, manifests/prometheus/alerts.d/bosh-stemcells-not-in-sync.yml
What
----
USN-3947-1
CVE-2019-11068
USN-3943-1
CVE-2018-20483
CVE-2019-5953
For https://www.pivotaltracker.com/n/projects/1275640/stories/165633059 and https://www.pivotaltracker.com/n/projects/1275640/stories/165633078
This also adds a `warning` alert which fires if our bosh stemcells are out of sync. We have 3 bosh deployments (concourse, prometheus, cf (eg prod or prod-lon)), therefore summing by the version should be 3. This alert would fire during deploys, therefore it should only fire if it is red for > 12h.
How to review
-------------
Code review
```
export DEPLOY_ENV=tlwr
cd paas-bootstrap
make dev bosh-cli
bosh stemcells
```
[Look at this chart of the new alert in tlwr](https://prometheus-1.tlwr.dev.cloudpipeline.digital/graph?g0.range_input=2h&g0.expr=sum%20by%20(bosh_stemcell_ve …
=> 165633059 + 165633078 CVEs

concourse/pipelines/create-cloudfoundry.yml
What
----
Full diff: https://github.com/alphagov/paas-billing/compare/v0.58.0...v0.59.0
Just the one PR - alphagov/paas-billing#66 ([#164493738] Billable events are already in GBP)
How to review
-------------
* Code review
* Probably not necessary to test this in a dev env, because it's very small
Who can review
--------------
=> Bump paas-billing from v0.58.0 to v0.59.0

manifests/cf-manifest/env-specific/prod.yml
What
----
The tenants in question have finished performance testing
How to review
-------------
Code review
Look [here](https://prometheus-1.cloud.service.gov.uk/graph?g0.range_input=1w&g0.expr=sum(rate(firehose_counter_event_gorouter_total_requests_total%5B1h%5D))&g0.tab=0) and see that yesterday usage was comfortably < 300rps
Who can review
--------------
Not @tlwr
=> Support: Scale down gorouters in `prod` (IE) from 6 to 3

concourse/pipelines/create-cloudfoundry.yml
What
----
Bumps paas-admin to v0.126.0
See https://github.com/alphagov/paas-admin/compare/v0.104.0...v0.126.0 for diff, or commit for a list
How to review
-------------
Code review
Who can review
--------------
Not @46bit
=> Bump paas-admin to 0.126.0

manifests/cf-manifest/operations.d/330-uaa.yml, platform-tests/src/platform/availability/monitor/monitor.go
What
----
Reformats the API availability summary message to include the number of errors.
Bumps the version of uaa-customized and uses the uaa-customized health check script for UAA's route registrar.
[See this PR for more info](https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/2)
How to review
-------------
Code review
Run it down your pipeline
Who can review
--------------
Not @tlwr
Notes
---
There is a WIP commit until https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/2 is merged
=> Bump UAA Customized release and alter UAA Route Registrar health checks

manifests/cf-manifest/operations.d/510-add-prometheus-blackbox-exporter.yml, manifests/prometheus/alerts.d/bosh-duplicate-releases.yml, manifests/prometheus/operations.d/001-set-retention.yml
What
----
The upgrade to Concourse 5 means that Prometheus cannot scrape concourse anymore, this is fixed in v25.
There were not many breaking changes other than prometheus retention time syntax.
Adds an alert to check for multiple bosh release versions (except for bpm as bpm is likely to have multiple versions)
How to review
-------------
Code review
```
cd paas-bootstrap
make dev bosh-cli
bosh releases # check prometheus with a * is only 25
```
Check that the alert works
Who can review
--------------
Not @tlwr
=> [#164728419]Bump Prometheus boshrelease to v25.0.0

manifests/cf-manifest/env-specific/prod.yml
What
----
[The dashboard](https://grafana-1.cloud.service.gov.uk/d/paas-user-impact/user-impact-prod)
has been showing <= 22 cells required in Ireland for the last week. This
is probably due to people stopping applications that are no longer
required instead of migrating them to cflinuxfs3.
We should be able to scale down to 24 instances and still have plenty
capacity.
How to review
-------------
* Code review is fine
Who can review
--------------
=> Reduce cells in ireland from 27 to 24

concourse/pipelines/create-cloudfoundry.yml
What
----
Runs paas-billing acceptance tests once paas-billing has been deployed
Review first
---
https://github.com/alphagov/paas-billing/pull/77
How to review
-------------
1. Code review;
2. Run it down your pipeline and test;
3. Review/merge https://github.com/alphagov/paas-billing/pull/77;
4. Replace the `[TMP]` commit with one that imports the resulting new version of `paas-billing`;
5. Done 🎉 
Who can review
--------------
Not @AP-Hunt @46bit
=> [#165534387] Run paas-billing acceptance tests after deployment

concourse/pipelines/autodelete-cloudfoundry.yml, concourse/pipelines/create-cloudfoundry.yml, concourse/pipelines/deployment-kick-off.yml, concourse/pipelines/destroy-cloudfoundry.yml, concourse/pipelines/monitor-remote.yml
What
----
So only resource checks run on the non-colocated node
We only have to add this to a few tasks, but doing it with a big vim
macro is better than blocking the pipeline with concourse whack-a-mole
How to review
-------------
Code review
Check that every task has tags
```
git grep -A1 'task: ' concourse/pipelines/* | grep -v 'task:' | grep -v colocated | grep -v -- --
```
[Witness greenery](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry)
Who can review
--------------
Not @tlwr
=> Add colocated-with-tag to all jobs

concourse/pipelines/create-cloudfoundry.yml
What
----
Full diff:
https://github.com/alphagov/paas-admin/compare/v0.131.0...v0.132.0
Just https://github.com/alphagov/paas-admin/pull/237
How to review
-------------
Who can review
--------------
Not Richard
=> Bump paas-admin to v0.132.0

manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml, manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
This is based on cflinuxfs3-release [v0.88.0](https://github.com/cloudfoundry/cflinuxfs3-release/releases/tag/v0.88.0)
but has an additional change that makes the `pre-start` script
idempotent.
See https://github.com/cloudfoundry/cflinuxfs3-release/compare/cloudfoundry:da46147...alphagov:c49d64f for a full diff from upstream
How to review
-------------
* Code review
* Check it's run down a dev environment
Who can review
--------------
=> Fork cflinuxfs3-release, bump to v0.88.0

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
bosh haven't released an official stemcell that patches the recent Intel
CPU vulnerabilities yet.
This commit switches to using one of their "candidate" stemcell releases
(from [this commit](https://github.com/bosh-io/stemcells-core-index/commit/ef0d9d9c281cb072d238ad9fa5b6814ae631fd96) ).
This won't have had the benefit of whatever testing upstream usually do
before releasing stemcells, but it does have the linux kernel update we
need to mitigate the CVEs.
Also note this is a "heavy" stemcell, rather than the usual "light"
stemcell we use (this means it includes the machine image, rather than
using an AMI that's already been pushed to AWS).
How to review
-------------
* Code review
* Confirm it ran down a dev env successfully (see …
=> Switch to using "candidate" stemcell

concourse/pipelines/create-cloudfoundry.yml
What
----
This won't actually have any effect, because the BILLING_DB_PLAN
variable is only used when creating new databases - we don't try and
update the plans once the DBs are there.
In actual fact the prod and prod-lon databases are on
medium-unencrypted-9.5, not medium-9.5, so ¯\_(ツ)_/¯
How to review
-------------
Who can review
--------------
Not Rich
=> [#165965445] Ensure billing-db created as "medium" in prod-lon

Makefile, scripts/update-user-origin.rb
What
----
- Shows UAA admin token in `showenv` `make` task
- Adds a script to change the origin of a user (this will be documented in the team manual)
How to review
-------------
Code review
Attempt to change the origin of a user (in a dev env)
Who can review
--------------
Not @tlwr
=> Switch user origin script

manifests/cf-manifest/operations.d/229-cf-update_cflinuxfs_releases.yml, manifests/cf-manifest/spec/manifest/release_versions_spec.rb
What
----
This contains some bumps to cflinuxfs3 that are tenuously related to the
recent Intel CVEs. In particular, the libc linux kernel headers are
updated to match the new kernel version - https://github.com/cloudfoundry/cflinuxfs3/commit/3befb4fcd84a4fd9e16cc16e23e359c3199fd1a1
I don't think this has any security impact, but it's good to be
thorough.
How to review
-------------
* Check [the 0.1.1 / 0.1.2 diff](https://github.com/alphagov/paas-cflinuxfs3-release/compare/c49d64f...fb87719)
* Make sure it's run down someone's dev environment
Who can review
--------------
Not Richard
=> Bump cflinuxfs3 to 0.1.2 (> 0.89.0 upstream)

concourse/pipelines/create-cloudfoundry.yml, manifests/cf-manifest/operations.d/020-bosh-set-stemcells.yml
What
----
The candidate stemcell we were using was 170.68, but 170.69 is the
"officially supported" version, so lets use that instead
How to review
-------------
Code review
Look at [tlwr](https://deployer.tlwr.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/resources/paas-cf) at resource version `5bff0df5584c5a3999778bea9aff95a4ed459bf9 ` and see it has passed the tests.
Who can review
--------------
Not @tlwr
=> Update to 170.69 Stemcell

manifests/prometheus/alerts.d/bosh-stemcells-not-in-sync.yml
What
----
We recently added an alert to warn us when more than one BOSH Stemcell version is in use. This alert is helpful because it is easy to forget that Stemcell upgrades must be performed in both https://github.com/alphagov/paas-bootstrap and https://github.com/alphagov/paas-cf.
The alert went off for the first time to warn of this problem, but the `paas-bootstrap and paas-cf are not in sync` description may not have been specific enough to explain the problem. This commit clarifies the message further to make the alert more effective.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit
=> Clarify alert when multiple Stemcells are in-use

tools/metrics/README.md
What
----
The README for `paas-metrics` lists all the metrics it exports, but it was out of date. This commit adds all the metrics and alphabetises them.
How to review
-------------
Have a read. Maybe compare it against the metrics exported by `paas-metrics` in production.
Who can review
--------------
Anyone
=> [#166000970] Document and order all metrics exposed by `paas-metrics` in the README

manifests/cf-manifest/scripts/rotate-vars-store-secrets.rb
What
----
#1909 output debugging information on `STDOUT` and corrupted the script's main output. This commit changes it to use `STDERR` instead.
How to review
-------------
Double-check all the `puts` introduced by #1909 now use `STDERR.puts`.
Who can review
--------------
Not @46bit
=> Fix output from secret rotation secret

concourse/pipelines/create-cloudfoundry.yml
What
----
We have several certs in the pipeline that are no longer required, these include the Consul certs, which were left unused after https://github.com/alphagov/paas-cf/commit/7fbe371cfe4fe04fc54213b320d95d7fb27e6809 was merged. And, metron related certs that are no longer required due to changes in the loggregator sub-system.
This commit will remove these certs from the vars store and enable our cert checking tests to pass again. The test has been failing as these carts are no longer part of the cert rotation job and have been left in the vars store.
How to review
-------------
code review
download one of the prod cf-vars-store-yaml and modify the paths in the script and run it locally. then verify that the certs have gone in the cf-vars-store-updated.yml
Who can review …
=> [#166056703] Remove certs that are no longer required

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/pipelines-cloudfoundry.sh, config/admin_users.yml, manifests/cf-manifest/scripts/generate-manifest.sh, manifests/cf-manifest/spec/manifest/oauth_spec.rb, manifests/cf-manifest/spec/support/manifest_helpers.rb, scripts/sync-admin-users.rb
What
----
We are using single sign on everywhere, so we should use it
This PR allows us to only create user accounts for individual users, depending on environment, and enables user account creation everywhere, as we want it enabled always.
How to review
-------------
Run this branch down your pipeline, and google oauth yourself into admin
Who can review
--------------
Not @tlwr
=> Introduce deploy_env specific user accounts, and always create users

concourse/pipelines/create-cloudfoundry.yml
What
----
These certs have been removed from `cf-vars-store.yml` and as a result this code is no longer required.
Once this has been merged and deployed we can forget about it as it is removing the code to remove the obsolete certificates from the vars store.
How to review
-------------
Code review
Who can review
--------------
Anyone
=> [#166056703] Remove the cert cleanup code

concourse/pipelines/create-cloudfoundry.yml
What
----
Mainly to release the self service uplift journey.
[Full diff](https://github.com/alphagov/paas-admin/compare/v0.132.0...v0.147.0).
Includes the following PRs:
* alphagov/paas-admin#240
* alphagov/paas-admin#239
* alphagov/paas-admin#238
* alphagov/paas-admin#236
* alphagov/paas-admin#235
* alphagov/paas-admin#246
* alphagov/paas-admin#245
* alphagov/paas-admin#243
* alphagov/paas-admin#242
* alphagov/paas-admin#248
* alphagov/paas-admin#247
* alphagov/paas-admin#253
* alphagov/paas-admin#252
* alphagov/paas-admin#251
* alphagov/paas-admin#256
* alphagov/paas-admin#257
* alphagov/paas-admin#258
* alphagov/paas-admin#259
* alphagov/paas-admin#260
* alphagov/paas-admin#261
* alphagov/paas-admin#262
* alphagov/paas-admin#227
* alphagov/paas-admin#244
* alphagov/paas-admin#254
How …
=> Bump paas-admin to v0.147.0

manifests/cf-manifest/operations.d/200-paas-admin-uaa-client.yml
What
----
As per the UAA API documentation [1], the `scim.write` authority is required
for clients to update or patch users. This commit grants that authority to the
paas-admin UAA client.
[1] https://docs.cloudfoundry.org/api/uaa/version/4.31.0/index.html#patch
How to review
-------------
Code review
See the docs and double check paas-admin has all the authorities granted that it needs to be able to modify a user's origin
Who can review
--------------
Anyone
=> [#166027792] Grant the `scim.write` authority to paas-admin UAA client

config/service-brokers/aiven/config.json, platform-tests/src/platform/acceptance/elasticsearch_service_test.go, scripts/audit-services.rb
What
----
Remove Elasticsearch 5.x plans from the Aiven broker
How to review
-------------
* Code Review
* Deploy in a dev environment, ensure the whole pipeline runs as expected and `cf m` no longer shows 5.x versions
* Ensure that no tenants have ES 5.x instances in any region:
* London: `scripts/audit_services.rb 8698b363-51a3-4734-bb31-11ecb4ade7f5 --filter '{"plan_regex": ".*5.x$"}'
* Ireland: `scripts/audit_services.rb b98f53e7-85a7-4964-bace-9ce27fac142a --filter '{"plan_regex": ".*5.x$"}'
Who can review
--------------
Not @tnwhitwell or @AP-Hunt
=> [#163592114] Remove Elasticsearch 5.x

Makefile, concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/lib/google-oauth.sh, concourse/scripts/lib/microsoft-oauth.sh, concourse/scripts/pipelines-cloudfoundry.sh, manifests/cf-manifest/operations.d/330-uaa.yml, manifests/cf-manifest/operations/uaa-add-google-oauth.yml, manifests/cf-manifest/operations/uaa-add-microsoft-oauth.yml, manifests/cf-manifest/scripts/generate-manifest.sh, manifests/shared/spec/fixtures/environment-variables.yml, scripts/upload-google-oauth-secrets.sh, scripts/upload-microsoft-oauth-secrets.sh
What
----
This PR is mainly for this PR: https://github.com/alphagov/paas-uaa-customized-boshrelease/pull/5
- Renames `oauth_client_...` to `google_client_...` for clarity
- Adds a task to upload Microsoft Azure Active Directory secrets (named `microsoft_oauth_...` to be consistent with `google_oauth_...`)
- Adds Microsoft as an IDP
- Bumps the uaa-customized release (***FIXME once merged***) to update the sign in page, and ignore Microsoft as an IDP
Notes
---
Credentials are added in this PR https://github.com/alphagov/paas-credentials/pull/151
How to review
-------------
- Code review
Who can review
--------------
Not @tlwr
This work was based heavily on a spike by @46bit and so perhaps Miki a good person to review
Further work in different stories
---
- Enable …
=> [#166028209] Scaffolding for Microsoft IDP

concourse/pipelines/create-cloudfoundry.yml
What
----
[Full diff](https://github.com/alphagov/paas-admin/compare/v0.147.0...v0.149.0)
PRs:
alphagov/paas-admin#265
alphagov/paas-admin#270
How to review
-------------
* Check the paas-admin changes are sensible
* Probably no need to deploy it, given the changes
Who can review
--------------
* Not @richardtowers
=> Bump paas-admin to v0.149.0

concourse/pipelines/create-cloudfoundry.yml
What
----
[Full diff](https://github.com/alphagov/paas-admin/compare/v0.150.0...v0.151.0)
I think this is just alphagov/paas-admin#271 to fix the ireland tag colour.
How to review
-------------
Who can review
--------------
=> Bump paas-admin to v0.151.0

manifests/cf-manifest/operations.d/750-s3-broker.yml
Signed-off-by: Toby Lorne <toby.lornewelch-richards@digital.cabinet-office.gov.uk>
What
----
https://www.pivotaltracker.com/story/show/165677471 indicates that the AWS s3 broker should be available to trial accounts, this is achieved by setting `free` to `true` (we will still generate chargeable events for it)
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
=> Set s3 bucket to "free"

manifests/prometheus/dashboards.d/user-impact.json
Why
----
The graphs showing 2xx, 4xx and 5xx were scaled according to the highest value (usually the 2xx requests), and so 4xx and 5xx were not easily visible. Also, the colours blended together quite a bit
What
----
The request type with the most requests has now been moved to the right
axis, which means that 4xx and 5xx are autoscaled separately.
Also, the 2xx results were a little too BIG and BOLD, which drew
attention away from the 'point' of the graph (showing the problems).
These are now much less bold, so the eye is drawn to the issues.
FINALLY, Colours for the request graphs have been set manually, so
they merge together less.
How to review
-------------
Do a deploy from this branch and behold the majesty of my creation
(This has been deployed to my environment already, so I guess …
=> Adjust user impact dashboard to be more legible

manifests/prometheus/dashboards.d/sli.json
What
----
We've decided to measure "uptime" based on metrics from the CloudFront CDN. CloudFront sits on the outside the platform, so any errors due to the platform will be seen in the cloud front metrics.
At the time of writing there are about 40 CloudFront CDNs on the platform (across London and Ireland). They cover both production and non-production services.
Our SLI should not be affected if a few services have high error rates - this probably indicates an issue with the individual applications.
If a large number of services have high error rates at the same time we should assume there's a problem with the platform.
Initially our application uptime SLI is:
```
The average (mean) percentage of 5XX responses from CloudFront, ignoring the 5 distributions with the highest percentage of …
```
=> Add initial SLI dashboard

manifests/prometheus/dashboards.d/sli.json
What
-------------
The dashboard I added in #1931 was missing the outer object (`{"dashboard":...`), so grafana's API was rejecting it.
How to review
-------------
* Code review (fe41bb8 is easier to review - the other commit re-indents the object)
* Confirm that this worked in Rich's dev environment 
* https://deployer.towers.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/prometheus-deploy/builds/11
* https://grafana-1.towers.dev.cloudpipeline.digital/d/service-level-indicators/service-level-indicators?orgId=1 (there's no data in my env because I haven't been running the latest paas-metrics...)
Who can review
--------------
Not richard
=> Fix unprocessable SLI dashboard

manifests/prometheus/dashboards.d/sli.json, manifests/prometheus/spec/dashboard_validation_spec.rb, manifests/prometheus/spec/spec_helper.rb
What
----
Every Grafana dashboard needs to have `{"overwrite": true}` otherwise we get `HTTP 412` when we attempt to create/update
This PR adds `overwrite` to the offending dashboard and adds some spec tests to prevent non-idempotent dashboard configurations.
How to review
-------------
Code review
Run the tests
Who can review
--------------
Not @tlwr
=> Fix Grafana idempotency and add spec tests

manifests/cf-manifest/operations.d/710-rds-broker.yml
What
----
Bumps `paas-cf` to target rds-broker-boshrelease [0.1.57](https://github.com/alphagov/paas-rds-broker-boshrelease/pull/84), so that the change in [`paas-rds-metrics-collector`](https://github.com/alphagov/paas-rds-metric-collector/pull/19) is deployed
How to review
-------------
1. Code review
Who can review
--------------
Not I
=> [#166495283] Bump rds-broker-boshrelease to 0.1.57

tools/metrics/gauges_cf.go, tools/metrics/gauges_custom_domain_cdn_metrics.go, tools/metrics/gauges_custom_domain_cdn_metrics_test.go, tools/metrics/gauges_tls.go, tools/metrics/gauges_tls_test.go, tools/metrics/metrics.go, tools/metrics/prometheus_reporter.go, tools/metrics/prometheus_reporter_test.go
What
----
Applying the boy scout rule. This was a problem hit during an earlier story, with an easy fix.
Previously, metric tags were a slice of strings, which were required to be "key:value" pairs. This wasn't clear from the interface alone, and was only obvious on seeing the error message in the prometheus reporter (which made the assumption about string format). In this commit, I refactored the tags to be a slice of the `MetricTag` struct, and added some stringer methods. This should make the interface clearer, and this particular error avoidable in future.
How to review
-------------
Code review
`cf push` to a dev env and check the metrics are the same as before.
Who can review
--------------
Anyone
=> Refactor metric tags to a slice of structs

concourse/pipelines/create-cloudfoundry.yml
What
----
Bump paas-account to v0.7.0 which includes https://github.com/alphagov/paas-accounts/pull/7
How to review
-------------
Code review
Who can review
--------------
Not me
=> [#166334735] Bump paas-account to v0.7.0

manifests/cf-manifest/env-specific/prod.yml, tools/metrics/tlscheck/tls_test.go
What
----
This reverts commit f8315caf4c2241503f358ecf85c82608d2fac0b8.
Notify can reproduce their load issues without scaling requests, so
there's no need for us to be running scaled up routers now.
How to review
-------------
Who can review
--------------
Not Rich
=> Revert "Scale up gorouters in `prod` (IE) from 3 to 6"

manifests/cf-manifest/spec/manifest/base_properties_spec.rb, manifests/variables.yml
What
----
We want to utilise Reserved Instances to reduce our EC2 costs. We want to reserve the newest type of instances so that we are investing effectively.
Until now our cells have used the `r4.xlarge` EC2 instance type. This commit changes us to use the `r5.xlarge` EC2 instance type. These new instances have more memory (32GiB rather than 30.5GiB [1]) and so this commit updates where that number is used.
[1] https://www.ec2instances.info/?min_memory=20&min_vcpus=4&region=eu-west-2&selected=r4.xlarge,r5.xlarge
How to review
-------------
Code review. This is deployed to the `miki` dev environment and everything went green [2].
[2] `custom-acceptance-tests` failed, but the only failing test is because I still haven't deleted the `cflinuxfs2` buildpacks from the `miki` dev environment. …
=> [#166440328] Change cells to `r5.xlarge` EC2 instance type

platform-tests/src/platform/acceptance/logging_pipeline_test.go
What
----
The custom acceptance test which checks logging is flakey because the logs are not guaranteed to be RTR/0 or APP/PROC/WEB/0 just APP/PROC/WEB/x or RTR/x
This PR removes the instance index from the test
How to review
-------------
Code review + YOLO merge
Who can review
--------------
Not @tlwr
=> Ignore instance ID in logs for custom acceptance

concourse/pipelines/create-cloudfoundry.yml, concourse/scripts/lib/google-oauth.sh, concourse/scripts/pipelines-cloudfoundry.sh, config/users.yml, manifests/prometheus/operations.d/250-grafana-oauth.yml, manifests/prometheus/scripts/generate-manifest.sh, manifests/prometheus/spec/support/manifest_helpers.rb, scripts/sync-admin-users.rb, scripts/upload-google-oauth-secrets.sh
What
----
As a GOV.UK PaaS operator, I want to be able to use Google OAuth to sign in to Grafana, so I can look at the health of the platform.
This PR does the following:
- Optimise the pipeline such that `prometheus-deploy` is faster (using `aggregate`)
- Refactor `admin_users.yml` into `users.yml` with a flag for whether they need a CF admin account
- Adds Prometheus deploy ops file to enable Grafana OAuth
- Adds Concourse task to manage Grafana users
Other PRs
---
- https://github.com/alphagov/paas-credentials/pull/152
How to review
-------------
- Code review
- Run this down your pipeline
- Log in to Grafana using OAuth
- Ensure SSO still works
Who can review
--------------
Not @tlwr
=> [#163359677] Grafana OAuth

platform-tests/src/platform/availability/api/api_test.go, platform-tests/src/platform/availability/monitor/monitor.go, platform-tests/src/platform/availability/monitor/monitor_suite_test.go, platform-tests/src/platform/availability/monitor/monitor_test.go, platform-tests/src/platform/availability/monitor/report.go, platform-tests/src/platform/availability/monitor/report_test.go
[Story](https://www.pivotaltracker.com/story/show/166116997)
What
----
Changes:
- Cleanup availability test code and remove duplication
- Cleanup old Golang package syntax
- Refactor the tests to use a % rule instead of constant
Ramifications:
- Tests will no longer fail for a single failure
- The test report output has changed
- For tests with a low number of executions, this will fail more often
> (4 failures out of 100 executions, which was previously okay, will fail)
How to review
-------------
- Code review
- Travis
- Run down pipeline -> green
- Run down pipeline, simulate a failure while the tests are running (e.g. `pkill -9 java` on a UAA instance)
Who can review
--------------
Not @tlwr
=> [#166116997] API availability tests

manifests/cloud-config/cloud-config.yml, manifests/prometheus/operations.d/100-update-vm-types.yml, manifests/prometheus/spec/operations/monitor_cf_spec.rb, manifests/prometheus/spec/operations/update_vm_types_spec.rb, manifests/variables.yml
[Story](https://www.pivotaltracker.com/story/show/166728064)
What
----
- Introduce variables for our instance types
- Upgrade instance types to latest generation of AWS
> note that the upgrade excludes the `prometheus` deployment as our version of the AWS CPI does not work well with NVMe instance types (c5, t3, m5, r5)
- ~Upgrades stemcells to `315x` series~
- Deletes the alert which warns us of our bosh stemcells being out sync (we will reinstate it when paas-bootstrap is up to date)
Why
---
New instance types are:
- Cheaper
- Faster
- More reliable network performance
Making instance types all the latest generation across GDS's entire estate would let us reserve instances and save money.
How to review
-------------
- Code review
- See [this …
=> Upgrade control plane

scripts/cf_admin_login_dev.sh
What
----
In the same spirit as `scripts/cf_subshell_scoped_login.sh`, this commit adds
an option to `scripts/cf_admin_login_dev` to allow users to scope the login to
a subshell. It uses the same method to do that as the former.
This is intended as a quality of life improvement, for those times when devs
are working across multiple spaces and the global nature of the `cf` tool is a
hindrance.
How to review
-------------
1. Code review
2. Try it out
Who can review
--------------
Not @AP-Hunt
=> Allow subshell scope logins for dev envs [skip ci]
